// 乐理闯关 · 支线大关卡（节奏、布鲁斯与爵士部分；结构与规则见 learn_units_side.js 顶部的说明）
// 修改题卡后运行 node scripts/annotate-learn.mjs 更新下面的汇总与 references.js 的 usedIn
// 依据汇总（本文件题卡引用的全部资料）：
//   ref:omt-pb-blues ref:wiki-twelve-bar ref:wiki-turnaround ref:wiki-harmonization ref:omt2e-chord-symbols
//   ref:omt2e-embellishing ref:omt2e-phrase-model ref:omt2e-cadences ref:omt2e-predominants ref:omt-pb-substitutions
//   ref:omt2e-iivi ref:omt2e-tonicization ref:wiki-circle-progression ref:wiki-ragtime-progression
// @refs-end

const t = (zh, ja, en) => ({ zh, ja, en });
const opt = (id, label) => ({ id, label });
const m = (at, label, place) => ({ at: [].concat(at), label, ...(place ? { place } : {}) });
const cells = (...texts) => texts.map((text) => (typeof text === 'string' || text.zh ? { text } : text));

export const UNITS = [
  // ======================= 布鲁斯 2 =======================
  {
    id: 'blues2', parent: 'blues', section: 'jazz', feature: 'blues', icon: 'B7',
    title: t('布鲁斯 2：属七、变格与各种布鲁斯', 'ブルース 2：属七・変格・いろいろなブルース', 'Blues 2: dominant sevenths, plagal closure and blues variants'),
    blurb: t('为什么全是属七、为什么用变格收束、16 小节布鲁斯、小调布鲁斯、爵士布鲁斯和 turnaround', 'なぜすべて属七か、なぜ変格で終わるか、16 小節・マイナー・ジャズのブルースとターンアラウンド', 'Why everything is a dominant seventh, why plagal closure, 16-bar, minor and jazz blues, and turnarounds'),
    cards: [
      { type: 'guide', ref: 'omt-pb-blues', demo: { play: [[48, 52, 55, 58], [53, 57, 60, 63], [48, 52, 55, 58]] },
        visual: { kind: 'blocks', rows: [
          { label: '1–4', cells: cells('I7', 'I7', 'I7', 'I7') },
          { label: '5–8', cells: cells({ text: 'IV7', lit: true }, 'IV7', 'I7', 'I7') },
          { label: '9–12', cells: cells('V7', { text: 'IV7', lit: true }, 'I7', 'I7') },
        ] },
        tour: [
          m(['row0', 'row1', 'row2'], t('三个四小节乐句 全是属七', '4 小節のフレーズ 3 つ、すべて属七', 'three four-bar phrases, all dominant sevenths')),
          m(['c1-0', 'c2-1'], t('IV–I 的变格运动才是收束', 'IV–I の変格が終止', 'IV–I plagal motion is the closure'), 'below'),
        ],
        title: t('布鲁斯不按古典的规矩来', 'ブルースは古典の決まりに従わない', 'The blues doesn’t follow classical rules'),
        steps: [
          t('布鲁斯和古典、爵士的和声有几个大差别：属七和弦可以有任何功能（主、属、下属）；收束靠变格终止，而不是正格终止；大三度和小三度可以自由混用，甚至同时出现。', 'ブルースは古典やジャズの和声と大きく違う：属七がどの働き（主・属・下属）にもなる。終止は正格でなく変格。長 3 度と短 3 度を自由に混ぜ、同時にも鳴らす。', 'The blues differs from tonal and jazz harmony in big ways: dominant sevenths can have any function (tonic, dominant or subdominant); closure comes from plagal rather than authentic cadences; major and minor thirds mix freely, even at once.'),
          t('标准的 12 小节布鲁斯是三个乐句，每句通常四小节：第一句全是主和弦，第二句两小节下属、两小节主和弦，第三句一小节属、一小节下属、两小节主和弦——所有和弦都是属七。', '標準の 12 小節ブルースは 3 フレーズ、各 4 小節：1 つ目はすべて主和音、2 つ目は下属 2 小節と主和音 2 小節、3 つ目は属 1・下属 1・主和音 2——すべて属七。', 'A standard 12-bar blues has three phrases, usually four bars each: all tonic; two bars subdominant and two tonic; one bar dominant, one subdominant, two tonic — every chord a dominant seventh.'),
        ] },
      { type: 'choice', ref: 'omt-pb-blues',
        prompt: t('标准 12 小节布鲁斯里，和弦都是什么性质？', '標準の 12 小節ブルースの和音はすべて？', 'In a standard 12-bar blues, what quality are the chords?'),
        options: [t('属七', '属七', 'dominant sevenths'), t('大七', 'メジャー・セブンス', 'major sevenths'), t('小七', 'マイナー・セブンス', 'minor sevenths')], answer: 0,
        hint: t('I7 IV7 V7。', 'I7 IV7 V7。', 'I7 IV7 V7.'),
        explain: t('所有和弦都是属七，而且不属于同一个调——属七在布鲁斯里可以有任何功能。', 'すべて属七で 1 つの調に収まらない——ブルースでは属七がどの働きにもなる。', 'All dominant sevenths, not fitting one key — in the blues a dominant seventh can have any function.') },
      { type: 'choice', ref: 'omt-pb-blues',
        prompt: t('布鲁斯的结构性收束主要靠哪种终止？', 'ブルースの構造的な終止は主にどれ？', 'Structural closure in the blues comes mainly from…'),
        options: [t('变格终止（IV–I）', '変格終止（IV–I）', 'plagal cadences (IV–I)'), t('正格终止（V–I）', '正格終止（V–I）', 'authentic cadences (V–I)'), t('阻碍终止', '偽終止', 'deceptive cadences')], answer: 0,
        hint: t('第三句是 V–IV–I。', '3 つ目は V–IV–I。', 'The third phrase is V–IV–I.'),
        explain: t('第三句 V 之后回到 IV 再到 I：布鲁斯强调的是变格而不是正格。', '3 つ目は V から IV、そして I：ブルースは正格より変格を強調。', 'The third phrase goes V back to IV then I: the blues emphasizes plagal, not authentic, cadences.') },
      { type: 'fill', ref: 'omt-pb-blues',
        prompt: t('12 小节布鲁斯第三句：___ – IV – I – I', '12 小節ブルースの 3 つ目：___ – IV – I – I', 'The third phrase of a 12-bar blues: ___ – IV – I – I'),
        bank: [opt('V', 'V'), opt('ii', 'ii'), opt('vi', 'vi')], answer: ['V'],
        hint: t('一小节属。', '属を 1 小節。', 'One bar of dominant.'),
        explain: t('V（属）一小节、IV 一小节、I 两小节。', 'V 1 小節、IV 1 小節、I 2 小節。', 'One bar V, one bar IV, two bars I.') },
    ],
    branch: [
      {
        title: t('quick change 与 16 小节布鲁斯', 'クイック・チェンジと 16 小節ブルース', 'Quick change and the 16-bar blues'),
        cards: [
          { type: 'guide', ref: ['wiki-twelve-bar', 'omt-pb-blues'],
            visual: { kind: 'blocks', rows: [
              { label: 'quick change', cells: cells('I7', { text: 'IV7', lit: true }, 'I7', 'I7') },
              { label: t('16 小节', '16 小節', '16-bar'), cells: cells({ text: 'T' }, { text: 'T' }, { text: 'S' }, { text: 'D', lit: true }) },
            ] },
            tour: [
              m('c0-1', t('第二小节就到 IV', '2 小節目で IV へ', 'IV already in bar 2')),
              m('row1', t('四个四小节乐句', '4 小節 × 4', 'four four-bar phrases'), 'below'),
            ],
            title: t('早一点变化，或者多一个乐句', '早めに変える、または 1 フレーズ足す', 'Change earlier, or add a phrase'),
            steps: [
              t('quick change（quick to four）：第二小节先到 IV7，第三小节再回 I7——第一句里就有了对比。', 'クイック・チェンジ（クイック・トゥ・フォー）：2 小節目で IV7、3 小節目で I7 に戻る——1 つ目のフレーズで対比が生まれる。', 'Quick change (quick to four): bar 2 goes to IV7 and bar 3 returns to I7 — contrast already in the first phrase.'),
              t('16 小节布鲁斯是四个四小节乐句，通常两遍主和弦之后接下属和属；它没有 12 小节那么常见，但在布鲁斯摇滚里出现得较多。', '16 小節ブルースは 4 小節のフレーズ 4 つ。ふつう主和音 2 回の後に下属と属。12 小節ほど多くないがブルース・ロックでは比較的多い。', 'The 16-bar blues has four four-bar phrases, usually two tonic phrases then subdominant and dominant; less common than the 12-bar but more frequent in blues-based rock.'),
            ] },
          { type: 'choice', ref: 'wiki-twelve-bar',
            prompt: t('quick change 改的是哪一小节？', 'クイック・チェンジで変えるのは何小節目？', 'Which bar does the quick change alter?'),
            options: [t('第二小节改成 IV', '2 小節目を IV に', 'bar 2 becomes IV'), t('第十二小节改成 V', '12 小節目を V に', 'bar 12 becomes V'), t('第九小节改成 ii', '9 小節目を ii に', 'bar 9 becomes ii')], answer: 0,
            hint: t('"quick to four"。', '「クイック・トゥ・フォー」。', '"Quick to four."'),
            explain: t('第二小节就到 IV（下属），所以叫 quick to four。', '2 小節目で IV（下属）へ行くので quick to four。', 'Bar 2 already goes to IV, hence "quick to four".') },
          { type: 'choice', ref: 'omt-pb-blues',
            prompt: t('16 小节布鲁斯有几个四小节乐句？', '16 小節ブルースの 4 小節フレーズはいくつ？', 'How many four-bar phrases are in a 16-bar blues?'),
            options: ['4', '3', '2'], answer: 0,
            hint: t('16 ÷ 4。', '16 ÷ 4。', '16 ÷ 4.'),
            explain: t('四个四小节乐句，通常两遍主和弦之后接下属与属。', '4 小節 × 4、ふつう主和音 2 回の後に下属と属。', 'Four four-bar phrases, usually two of tonic then subdominant and dominant.') },
          { type: 'choice', ref: 'omt-pb-blues',
            prompt: t('布鲁斯的伴奏声部常怎样连接和弦，得到平滑的进行？', 'ブルースの伴奏はなめらかにするため和音をどうつなぐ？', 'How do blues accompaniments often connect the chords smoothly?'),
            options: [t('连接各和弦的三音与七音', '各和音の 3 音と 7 音をつなぐ', 'by connecting the chords’ thirds and sevenths'), t('只弹根音', '根音だけ', 'by playing only roots'), t('每个和弦都用同一个指型平移', 'すべて同じ形を平行移動', 'by sliding one shape everywhere')], answer: 0,
            hint: t('根音走五度和级进，三音和七音可以级进相接。', '根音は 5 度と順次、3 音と 7 音は順次でつながる。', 'Roots move by fifth and step; thirds and sevenths connect by step.'),
            explain: t('布鲁斯的根音按五度和级进移动，连接三音与七音就能得到一路级进的声部。', 'ブルースの根音は 5 度と順次で動くので、3 音と 7 音をつなぐと順次の声部になる。', 'Since blues roots move by fifth and step, linking thirds and sevenths yields stepwise voice leading.') },
        ],
      },
      {
        title: t('小调布鲁斯', 'マイナー・ブルース', 'Minor blues'),
        cards: [
          { type: 'guide', ref: ['omt-pb-blues', 'wiki-twelve-bar'], demo: { play: [[48, 51, 55, 58], [53, 56, 60, 63], [50, 53, 56, 60], [43, 53, 59, 62], [48, 51, 55, 58]] },
            visual: { kind: 'blocks', rows: [
              { label: t('和弦', '和音', 'chords'), cells: cells({ text: 'i7', lit: true }, { text: 'iv7', lit: true }, { text: 'V7' }) },
              { label: t('第三句', '3 つ目', 'third phrase'), arrows: true, cells: cells({ text: 'ii' }, { text: 'V' }, { text: 'i', lit: true }) },
            ] },
            tour: [
              m(['c0-0', 'c0-1'], t('主与下属是小七', '主と下属はマイナー・セブンス', 'tonic and subdominant are minor sevenths')),
              m('row1', t('V–IV–I 换成 ii–V–I', 'V–IV–I を ii–V–I に', 'V–IV–I becomes ii–V–I'), 'below'),
            ],
            title: t('i 与 iv 变成小七', 'i と iv がマイナー・セブンスに', 'i and iv become minor sevenths'),
            steps: [
              t('小调布鲁斯里，i 和 iv 用小七和弦，V 保持属七。', 'マイナー・ブルースでは i と iv がマイナー・セブンス、V は属七のまま。', 'In a minor blues, i and iv are minor seventh chords; V stays a dominant seventh.'),
              t('因为大三的 V 走到小三的 iv 听起来会泄气，小调布鲁斯的第三句通常把 V–IV–I 换成 ii–V–I。', '長三の V から短三の iv へは気が抜けて聞こえるので、3 つ目の V–IV–I はふつう ii–V–I に。', 'Because major V moving to minor iv can sound anticlimactic, the third phrase usually replaces V–IV–I with ii–V–I.'),
            ] },
          { type: 'choice', ref: 'omt-pb-blues',
            prompt: t('小调布鲁斯里 V 用什么性质？', 'マイナー・ブルースの V は？', 'In a minor blues, V is…'),
            options: [t('属七', '属七', 'a dominant seventh'), t('小七', 'マイナー・セブンス', 'a minor seventh'), t('大七', 'メジャー・セブンス', 'a major seventh')], answer: 0,
            hint: t('只有 i 与 iv 改成小七。', 'i と iv だけがマイナーに。', 'Only i and iv become minor.'),
            explain: t('i、iv 是小七，V 保持属七（维基也提到 V 可以是大的 V7 或小的 v7）。', 'i・iv はマイナー・セブンス、V は属七のまま（V7 か v7 のどちらもありうる）。', 'i and iv are minor sevenths; V stays dominant (it may be major V7 or minor v7).') },
          { type: 'choice', ref: 'omt-pb-blues',
            prompt: t('为什么小调布鲁斯常把第三句的 V–IV–I 换成 ii–V–I？', 'なぜマイナー・ブルースは 3 つ目の V–IV–I を ii–V–I にする？', 'Why does a minor blues often swap V–IV–I for ii–V–I?'),
            options: [t('大三的 V 走到小三的 iv 会泄气', '長三の V から短三の iv は気が抜ける', 'major V to minor iv sounds anticlimactic'), t('因为小调没有 IV', '短調に IV がない', 'minor has no IV'), t('为了换调', '転調するため', 'to modulate')], answer: 0,
            hint: t('从紧张的属走到暗的下属。', '緊張した属から暗い下属へ。', 'From a tense dominant to a dark subdominant.'),
            explain: t('V 之后接小的 iv 听起来像退回去，所以改成 ii–V–i 直接回家。', 'V の後の短い iv は後退に聞こえるので、ii–V–i でまっすぐ帰る。', 'Minor iv after V sounds like backing off, so ii–V–i goes straight home.') },
          { type: 'choice', ref: 'omt-pb-blues', audio: { notes: [[48, 51, 55, 58], [53, 56, 60, 63]], mode: 'chords' },
            prompt: t('听：Cm7 – Fm7，这是小调布鲁斯里的？', '聴いて：Cm7 – Fm7。マイナー・ブルースの？', 'Listen: Cm7 – Fm7. In a minor blues this is…'),
            options: ['i7 – iv7', 'I7 – IV7', 'ii7 – V7'], answer: 0,
            hint: t('两个都是小七。', 'どちらもマイナー・セブンス。', 'Both are minor sevenths.'),
            explain: t('C 小调的 i7 到 iv7，正是小调布鲁斯第一、二句用的和弦。', 'ハ短調の i7 から iv7、マイナー・ブルースの最初の和音。', 'i7 to iv7 in C minor — the chords of the minor blues’ first phrases.') },
        ],
      },
      {
        title: t('爵士布鲁斯', 'ジャズ・ブルース', 'Jazz blues'),
        cards: [
          { type: 'guide', ref: 'omt-pb-blues',
            visual: { kind: 'blocks', rows: [
              { label: t('第 8 小节', '8 小節目', 'bar 8'), cells: cells({ text: t('副属 ii–V → ii', '副属 ii–V → ii', 'applied ii–V → ii'), lit: true }) },
              { label: t('第三句', '3 つ目', 'third phrase'), arrows: true, cells: cells('ii', 'V', { text: 'I', lit: true }) },
            ] },
            tour: [
              m('row0', t('第 8 小节不再停在主和弦', '8 小節目は主和音に留まらない', 'bar 8 no longer sits on the tonic')),
              m('row1', t('V–IV–I 换成 ii–V–I', 'V–IV–I を ii–V–I に', 'V–IV–I becomes ii–V–I'), 'below'),
            ],
            title: t('布鲁斯 + 爵士的 ii–V', 'ブルース + ジャズの ii–V', 'The blues plus jazz ii–Vs'),
            steps: [
              t('爵士布鲁斯在 12 小节布鲁斯里加入好几个 ii–V，减弱变格收束的分量；它同样是三个四小节乐句。', 'ジャズ・ブルースは 12 小節ブルースに ii–V をいくつも加え、変格終止の比重を減らす。やはり 4 小節 × 3。', 'The jazz blues adds several ii–V progressions to the 12-bar blues, softening its reliance on plagal closure; it still has three four-bar phrases.'),
              t('第 8 小节不再停在主和弦，而是一个指向第 9 小节 ii 的副属 ii–V；第三句的 V–IV–I 换成 ii–V–I。它同时保留了布鲁斯的特色：不在 V 上的属七与变格的解决。', '8 小節目は主和音に留まらず、9 小節目の ii を指す副属の ii–V。3 つ目の V–IV–I は ii–V–I に。属七が V 以外にあることと変格の解決というブルースらしさも残す。', 'Bar 8 no longer stays on the tonic but has an applied ii–V leading to ii in bar 9; the third phrase replaces V–IV–I with ii–V–I. It keeps blues traits: dominant sevenths off V and plagal resolutions.'),
            ] },
          { type: 'choice', ref: 'omt-pb-blues',
            prompt: t('爵士布鲁斯第三句的和弦是？', 'ジャズ・ブルースの 3 つ目は？', 'The jazz blues’ third phrase uses…'),
            options: ['ii – V – I', 'V – IV – I', 'IV – iv – I'], answer: 0,
            hint: t('爵士最常见的终止。', 'ジャズでいちばん多い終止。', 'Jazz’s most common cadence.'),
            explain: t('V–IV–I 被换成爵士常用的 ii–V–I。', 'V–IV–I がジャズの ii–V–I に。', 'V–IV–I is replaced by jazz’s ii–V–I.') },
          { type: 'choice', ref: 'omt-pb-blues',
            prompt: t('爵士布鲁斯第 8 小节的副属 ii–V 指向哪里？', 'ジャズ・ブルース 8 小節目の副属 ii–V はどこを指す？', 'The applied ii–V in bar 8 of a jazz blues points to…'),
            options: [t('第 9 小节的 ii', '9 小節目の ii', 'the ii in bar 9'), t('第 1 小节', '1 小節目', 'bar 1'), t('第 5 小节的 IV', '5 小節目の IV', 'the IV in bar 5')], answer: 0,
            hint: t('第三句从 ii 开始。', '3 つ目は ii から。', 'The third phrase starts on ii.'),
            explain: t('第 8 小节用一个副属 ii–V 引出第 9 小节的 ii。', '8 小節目の副属 ii–V が 9 小節目の ii を導く。', 'Bar 8’s applied ii–V leads into ii in bar 9.') },
          { type: 'choice', ref: 'omt-pb-blues',
            prompt: t('爵士布鲁斯保留了布鲁斯的什么特色？', 'ジャズ・ブルースが残すブルースの特徴は？', 'Which blues trait does the jazz blues keep?'),
            options: [t('不在 V 上的属七与变格解决', 'V 以外の属七と変格の解決', 'dominant sevenths off V and plagal resolutions'), t('只用三和弦', '三和音だけ', 'triads only'), t('没有主和弦', '主和音がない', 'no tonic chord')], answer: 0,
            hint: t('它是两种语言的混合。', '2 つの言語の混合。', 'It mixes two languages.'),
            explain: t('它把布鲁斯的属七与变格解决和爵士的 ii–V、turnaround 混在一起。', 'ブルースの属七と変格の解決に、ジャズの ii–V とターンアラウンドを混ぜる。', 'It blends blues dominant sevenths and plagal resolutions with jazz ii–Vs and turnarounds.') },
        ],
      },
      {
        title: t('布鲁斯的 turnaround', 'ブルースのターンアラウンド', 'Blues turnarounds'),
        cards: [
          { type: 'guide', ref: ['omt-pb-blues', 'wiki-turnaround'],
            visual: { kind: 'blocks', rows: [
              { label: t('简单', 'シンプル', 'simple'), cells: cells('I7', { text: 'V7', lit: true }) },
              { label: t('完整', '完全', 'full'), arrows: true, cells: cells('III7', 'VI7', 'II7', { text: 'V7', lit: true }) },
            ] },
            tour: [
              m('c0-1', t('最后一小节放一个 V7', '最後の小節に V7', 'a V7 in the last bar')),
              m('row1', t('一串属七 一路五度下行', '属七の連鎖、5 度下行', 'a chain of dominants falling by fifths'), 'below'),
            ],
            title: t('结尾推回开头', '終わりを始まりへ押し戻す', 'Pushing the end back to the start'),
            steps: [
              t('turnaround 放在段落结尾，把音乐带回开头；在 12 小节布鲁斯里，第十二小节常常停在属和弦上。', 'ターンアラウンドは段落の終わりに置き、音楽を最初へ戻す。12 小節ブルースでは 12 小節目が属和音で終わることが多い。', 'A turnaround at the end of a section leads back to the beginning; in a 12-bar blues the twelfth bar often ends on the dominant.'),
              t('布鲁斯的 turnaround 可以简单到只有一个 V7，也可以是完整的 III–VI–II–V（一串属七），例如 E7–A7–D7–G7 回到 C。', 'ブルースのターンアラウンドは V7 1 つだけのこともあれば、完全な III–VI–II–V（属七の連鎖）、例えば E7–A7–D7–G7 から C のこともある。', 'A blues turnaround can be as simple as one V7 or a full III–VI–II–V chain of dominants, e.g. E7–A7–D7–G7 back to C.'),
            ] },
          { type: 'choice', ref: 'omt-pb-blues',
            prompt: t('III7–VI7–II7–V7 在 C 调是？', 'III7–VI7–II7–V7 はハ調で？', 'III7–VI7–II7–V7 in C is…'),
            options: ['E7 A7 D7 G7', 'Em7 Am7 Dm7 G7', 'E7 Am7 D7 Gm7'], answer: 0,
            hint: t('全部是属七。', 'すべて属七。', 'All dominant sevenths.'),
            explain: t('一串属七：E7 → A7 → D7 → G7，根音一路下行五度回到 C。', '属七の連鎖：E7 → A7 → D7 → G7、5 度下行で C へ。', 'A chain of dominants E7 → A7 → D7 → G7, falling by fifths to C.') },
          { type: 'choice', ref: 'wiki-turnaround',
            prompt: t('turnaround 的作用是？', 'ターンアラウンドの役割は？', 'What does a turnaround do?'),
            options: [t('在段落结尾把音乐带回开头', '段落の終わりで最初へ戻す', 'lead back to the beginning at the end of a section'), t('在开头转调', '最初で転調', 'modulate at the start'), t('让音乐停下来', '音楽を止める', 'stop the music')], answer: 0,
            hint: t('turn around：转回去。', 'turn around：戻る。', 'Turn around.'),
            explain: t('turnaround 在段落末尾，把音乐推回下一遍（多半是同一段或整首重来）。', '段落の終わりで次の周（同じ部分か曲全体）へ戻す。', 'It sits at the end of a section and leads into the next time round.') },
          { type: 'choice', ref: 'wiki-turnaround',
            prompt: t('布鲁斯里常见的 V–IV–I 结尾也被列为一种？', 'ブルースの V–IV–I も何の一種とされる？', 'The blues ending V–IV–I is also listed as a kind of…'),
            options: ['turnaround', t('正格终止', '正格終止', 'authentic cadence'), t('三全音替代', 'トライトーン代理', 'tritone substitution')], answer: 0,
            hint: t('维基的 turnaround 列表里有 "V–IV–I (blues turnaround)"。', 'ウィキの一覧に「V–IV–I (blues turnaround)」。', 'Wikipedia lists "V–IV–I (blues turnaround)".'),
            explain: t('V–IV–I 被称作布鲁斯的 turnaround。', 'V–IV–I はブルースのターンアラウンド。', 'V–IV–I is called the blues turnaround.') },
        ],
      },
    ],
  },

  // ======================= 再和声 =======================
  {
    id: 'reharm', parent: 'substitutions', section: 'jazz', feature: 'harmonize', toolQuery: '@sub:reharm', icon: 'Re',
    title: t('再和声：旋律不变，换掉和弦', 'リハーモナイズ：旋律はそのまま和音を変える', 'Reharmonization: same melody, new chords'),
    blurb: t('旋律音在不同和弦里的角色、半音与小九度的摩擦、同一旋律的古典 / 爵士 / 布鲁斯三种配法', '旋律音の和音ごとの役割、半音と短 9 度の摩擦、同じ旋律の古典 / ジャズ / ブルースの付け方', 'A melody note’s role in different chords, semitone and minor-ninth clashes, and classical / jazz / blues settings of one tune'),
    cards: [
      { type: 'guide', ref: 'wiki-harmonization',
        visual: { kind: 'blocks', rows: [
          { label: t('旋律音 E', '旋律音 E', 'melody E'), cells: cells({ text: 'E', sub: t('根音', '根音', 'root') }, { text: 'C', sub: t('三音', '3 音', 'third'), lit: true }, { text: 'Dm7', sub: t('九音', '9 音', 'ninth') }, { text: 'A♭+', sub: t('增五度', '増 5 度', '♯5') }) },
        ] },
        tour: [
          m('row0', t('同一个音 不同的身份', '同じ音、違う役割', 'one note, many roles')),
          m('c0-2', t('当作延伸音', '延長音として', 'as an extension'), 'below'),
        ],
        title: t('一个旋律音可以有很多身份', '1 つの旋律音にいろいろな役割', 'One melody note, many identities'),
        steps: [
          t('再和声是保留原来的旋律、换掉下面的和弦。同一个旋律音可以用很多和弦来配：E 可以是 E 大三和弦的根音、C 大三和弦的三音、Dm7 的九音，或 A♭ 增三和弦的增五度。', 'リハーモナイズは旋律を残して和音を変えること。同じ旋律音でもいろいろな和音で付けられる：E は E の長三の根音、C の長三の 3 音、Dm7 の 9 音、A♭ の増三の増 5 度。', 'Reharmonization keeps the melody and changes the chords. One melody note can be harmonized many ways: E can be the root of E major, the third of C, the ninth of Dm7 or the ♯5 of A♭ augmented.'),
          t('但一段旋律里有好几个音落在同一个和弦上，要全部考虑。旋律音和和弦音成半音或小九度时会很刺耳，需要懂和声、有好耳朵才能处理。', 'ただし旋律では 1 つの和音の上に複数の音が乗るので、すべて考える。旋律音と和音の音が半音や短 9 度になるときつく、扱うには和声の理解と耳が必要。', 'But several melody notes usually sit over one chord, and all must be considered. Melody notes a semitone or minor ninth from chord tones clash hard and need a good ear and real understanding to handle.'),
        ] },
      { type: 'choice', ref: 'wiki-harmonization',
        prompt: t('旋律音 E 配 Dm7 时，E 是？', '旋律音 E に Dm7。E は？', 'Melody E over Dm7 is…'),
        options: [t('九音（延伸音）', '9 音（延長音）', 'the ninth (an extension)'), t('根音', '根音', 'the root'), t('七音', '7 音', 'the seventh')], answer: 0,
        hint: t('D 往上九度。', 'D から 9 度上。', 'A ninth above D.'),
        explain: t('Dm7 = D F A C；E 是 D 上方的九度，属于延伸音。', 'Dm7 = D F A C。E は D の 9 度上、延長音。', 'Dm7 = D F A C; E is a ninth above D, an extension.') },
      { type: 'choice', ref: 'wiki-harmonization',
        prompt: t('旋律 E♭ F G 原本配 E♭maj7，换成 D7 为什么不太好？', '旋律 E♭ F G は元々 E♭maj7。D7 に代えるとよくないのは？', 'A melody E♭ F G originally over E♭maj7 — why is D7 a poor replacement?'),
        options: [t('每个旋律音都和和弦音成半音或小九度', 'どの旋律音も和音の音と半音か短 9 度になる', 'each melody note clashes by semitone or minor ninth with chord tones'), t('D7 太简单', 'D7 は単純すぎる', 'D7 is too simple'), t('D7 不能用在爵士', 'D7 はジャズで使えない', 'D7 isn’t allowed in jazz')], answer: 0,
        hint: t('D7 = D F♯ A C。', 'D7 = D F♯ A C。', 'D7 = D F♯ A C.'),
        explain: t('E♭ 对 D、G 对 F♯ 都是半音（小九度）摩擦；维基用的正是这个例子。', 'E♭ と D、G と F♯ が半音（短 9 度）でぶつかる。ウィキの例そのもの。', 'E♭ against D and G against F♯ are semitone (minor-ninth) clashes — the very example Wikipedia gives.') },
      { type: 'match', ref: 'wiki-harmonization',
        prompt: t('旋律音 E 配下面的和弦 ↔ 角色', '旋律音 E とこの和音 ↔ 役割', 'Melody E over this chord ↔ role'),
        pairs: [['E', t('根音', '根音', 'root')], ['C', t('三音', '3 音', 'third')], ['Am', t('五音', '5 音', 'fifth')], ['Dm7', t('九音', '9 音', 'ninth')]],
        hint: t('从和弦根音往上数。', '和音の根音から数える。', 'Count up from each root.'),
        explain: t('E 是 E 的根音、C 的三音、A 小三的五音、Dm7 的九音。', 'E は E の根音、C の 3 音、Am の 5 音、Dm7 の 9 音。', 'E is the root of E, the third of C, the fifth of Am and the ninth of Dm7.') },
    ],
    branch: [
      {
        title: t('和弦音、延伸音与需要解决的音', '和音の音・延長音・解決が必要な音', 'Chord tones, tensions and clashes'),
        cards: [
          { type: 'guide', ref: ['wiki-harmonization', 'omt2e-chord-symbols', 'omt2e-embellishing'],
            visual: { kind: 'blocks', rows: [
              { label: t('C 大三上的旋律音', 'C の長三の上の旋律音', 'melody over C'), cells: cells({ text: 'E', sub: t('和弦音', '和音の音', 'chord tone') }, { text: 'D', sub: t('延伸音 9', '延長音 9', 'tension 9') }, { text: 'F', sub: t('需要解决', '要解決', 'needs resolution'), lit: true }) },
            ] },
            tour: [
              m(['c0-0', 'c0-1'], t('属于和弦或它的延伸', '和音かその延長', 'in the chord or its extensions')),
              m('c0-2', t('比三音 E 高半音', '3 音 E の半音上', 'a semitone above the third E'), 'below'),
            ],
            title: t('给每个旋律音分类', '旋律音を分類する', 'Classify every melody note'),
            steps: [
              t('配和声时把每个旋律音分成三类：和弦音（根、三、五、七）、延伸音（9、11、13，变化的延伸音写在属七上，如 ♭9 ♯9 ♭13），以及和和弦音成小二度、需要级进解决的和弦外音。', '和声付けでは旋律音を 3 つに分ける：和音の音（根・3・5・7）、延長音（9・11・13、変化した延長音は属七に ♭9 ♯9 ♭13）、和音の音と短 2 度になり順次で解決が必要な和音外音。', 'Sort each melody note into three kinds: chord tones (root, 3rd, 5th, 7th), tensions (9, 11, 13; altered ones like ♭9 ♯9 ♭13 written on dominant sevenths), and non-chord tones a minor second from a chord tone that must resolve by step.'),
              t('例如 C 大三和弦上：E 是和弦音，D 是延伸音 9，F 比三音 E 高半音，会摩擦，多半当作经过音或倚音来解决。再和声工具会把这些角色直接标出来。', '例えば C の長三和音上：E は和音の音、D は延長音 9、F は 3 音 E の半音上でぶつかり、経過音や倚音として解決することが多い。リハーモナイズ・ツールはこれらの役割を表示する。', 'Over C major: E is a chord tone, D is the tension 9, and F, a semitone above the third E, clashes and is usually treated as a passing tone or appoggiatura that resolves. The reharmonization tool labels these roles.'),
            ] },
          { type: 'choice', ref: 'omt2e-chord-symbols',
            prompt: t('旋律音 A 配 C 大三和弦，是？', '旋律音 A に C の長三和音。これは？', 'Melody A over C major is…'),
            options: [t('延伸音 13（6）', '延長音 13（6）', 'the tension 13 (6)'), t('和弦音', '和音の音', 'a chord tone'), t('需要解决的音', '解決が必要な音', 'a clash')], answer: 0,
            hint: t('C 往上六度 / 十三度。', 'C から 6 度 / 13 度。', 'A sixth / thirteenth above C.'),
            explain: t('A 不在 C E G 里，也没有和它们成小二度，是 13（6）的延伸音色彩。', 'A は C E G に入らず、短 2 度にもならない。13（6）の延長音。', 'A is not in C E G and clashes with none of them: the 13th (6th) colour.') },
          { type: 'choice', ref: 'omt2e-chord-symbols',
            prompt: t('A♭ 配 G7，算什么？', 'A♭ に G7。何？', 'A♭ over G7 is…'),
            options: [t('变化延伸音 ♭9（属七上可用）', '変化した延長音 ♭9（属七で使える）', 'the altered tension ♭9 (usable on a dominant)'), t('和弦音', '和音の音', 'a chord tone'), t('一定要删掉', '必ず削除', 'always forbidden')], answer: 0,
            hint: t('变化延伸音写在属七上。', '変化した延長音は属七に書く。', 'Altered tensions go on dominant sevenths.'),
            explain: t('A♭ 是 G 上方的小九度，在属七上是常见的变化延伸音 ♭9。', 'A♭ は G の短 9 度上、属七でよく使う変化した延長音 ♭9。', 'A♭ is a minor ninth above G — the common altered tension ♭9 on a dominant.') },
          { type: 'choice', ref: 'omt2e-embellishing',
            prompt: t('F 落在 C 大三和弦上、比三音 E 高半音，通常怎样处理？', 'F が C の長三和音上で 3 音 E の半音上。ふつうどうする？', 'F over C major, a semitone above the third E, is usually treated as…'),
            options: [t('当作经过音或倚音 级进解决', '経過音や倚音として順次で解決', 'a passing tone or appoggiatura resolving by step'), t('长时间停在上面', '長く留まる', 'something to dwell on'), t('当作根音', '根音として', 'the root')], answer: 0,
            hint: t('和弦外音要解决。', '和音外音は解決する。', 'Non-chord tones resolve.'),
            explain: t('F 和 E 成小二度摩擦，通常是经过音或倚音，接着级进到 E。', 'F と E が短 2 度でぶつかり、ふつう経過音か倚音で E へ順次。', 'F clashes a minor second with E and usually resolves by step to E as a passing tone or appoggiatura.') },
        ],
      },
      {
        title: t('古典配法：每个旋律音都是和弦音', '古典の付け方：旋律音はすべて和音の音', 'Classical setting: every melody note a chord tone'),
        cards: [
          { type: 'guide', ref: ['omt2e-phrase-model', 'omt2e-cadences'],
            visual: { kind: 'blocks', rows: [
              { label: t('旋律', '旋律', 'melody'), cells: cells('E', 'F', 'G', 'A', 'G', 'F', 'D', 'C') },
              { label: t('古典', '古典', 'classical'), cells: cells({ text: 'I', lit: true }, 'IV', 'I', 'IV', 'I', 'ii', { text: 'V', lit: true }, { text: 'I', lit: true }) },
            ] },
            tour: [
              m('row1', t('主 → 下属 → 属 → 主', '主 → 下属 → 属 → 主', 'T → PD → D → T')),
              m(['c1-6', 'c1-7'], t('以 V–I 收束 旋律落在 do', 'V–I で終わり旋律は do', 'ends V–I with do on top'), 'below'),
            ],
            title: t('功能清楚的配法', '働きのはっきりした付け方', 'A functionally clear setting'),
            steps: [
              t('古典的配法让每个旋律音都是和弦音，开头是主和弦，经过下属走向属，最后以正格终止收束（V–I，旋律落在 do 是完全正格终止）。', '古典の付け方は旋律音をすべて和音の音にし、主和音で始まり下属から属へ進み、正格終止で終わる（V–I、旋律が do なら完全正格終止）。', 'A classical setting makes every melody note a chord tone, starts on the tonic, moves through predominant to dominant, and ends with an authentic cadence (V–I; with do on top it is a PAC).'),
              t('旋律配和声面板的"固定旋律再和声"里，古典这一行就是这样配出来的；接下来的爵士配法从这里出发。', '旋律和声付けパネルの「固定旋律のリハーモナイズ」の古典の行はこうして作られる。次のジャズの付け方はここから出発する。', 'In the harmonize panel’s reharmonization tool, the classical row is built this way; the jazz setting starts from it.'),
            ] },
          { type: 'choice', ref: 'omt2e-phrase-model',
            prompt: t('古典配法的乐句通常怎样走？', '古典の付け方のフレーズはふつう？', 'How does a classical setting usually move?'),
            options: ['T – PD – D – T', 'D – T – PD – D', 'PD – PD – PD – T'], answer: 0,
            hint: t('乐句模型。', 'フレーズ・モデル。', 'The phrase model.'),
            explain: t('主 → 下属 → 属 → 主，是乐句模型。', '主 → 下属 → 属 → 主のフレーズ・モデル。', 'Tonic → predominant → dominant → tonic: the phrase model.') },
          { type: 'choice', ref: 'omt2e-cadences',
            prompt: t('旋律最后是 D → C，配 V–I，这是什么终止？', '旋律の最後が D → C で V–I。どの終止？', 'The melody ends D → C over V–I. Which cadence?'),
            options: [t('完全正格终止（两个和弦原位时）', '完全正格終止（両方基本形なら）', 'a perfect authentic cadence (with both chords in root position)'), t('半终止', '半終止', 'a half cadence'), t('变格终止', '変格終止', 'a plagal cadence')], answer: 0,
            hint: t('旋律落在 do。', '旋律が do に落ちる。', 'The melody lands on do.'),
            explain: t('V–I 两个和弦原位、旋律落在 do，就是完全正格终止。', 'V–I が両方基本形で旋律が do なら完全正格終止。', 'V–I in root position with do on top is a perfect authentic cadence.') },
          { type: 'choice', ref: 'omt2e-predominants',
            prompt: t('旋律 F 落在 IV 上，F 是 IV 的？', '旋律の F が IV の上。F は IV の？', 'Melody F over IV is IV’s…'),
            options: [t('根音', '根音', 'root'), t('三音', '3 音', 'third'), t('五音', '5 音', 'fifth')], answer: 0,
            hint: t('IV = F A C。', 'IV = F A C。', 'IV = F A C.'),
            explain: t('C 大调的 IV 是 F A C，F 是根音。', 'ハ長調の IV は F A C、F は根音。', 'IV in C is F A C; F is the root.') },
        ],
      },
      {
        title: t('爵士配法：加七音与替换', 'ジャズの付け方：七の和音と代理', 'Jazz setting: sevenths and substitutions'),
        cards: [
          { type: 'guide', ref: ['omt-pb-substitutions', 'omt2e-iivi'],
            visual: { kind: 'blocks', rows: [
              { label: t('古典', '古典', 'classical'), cells: cells('I', 'IV', 'ii', 'V', 'I') },
              { label: t('爵士', 'ジャズ', 'jazz'), cells: cells('Imaj7', 'IVmaj7', 'ii7', { text: '♭II7', lit: true }, 'Imaj7') },
            ] },
            tour: [
              m('row1', t('先按上下文加七音', 'まず文脈で七の和音に', 'first, sevenths by context')),
              m('c1-3', t('终止处的 V7 换成三全音替代', '終止の V7 をトライトーン代理に', 'the cadential V7 becomes its tritone sub'), 'below'),
            ],
            title: t('换之前先检查旋律', '代える前に旋律を確かめる', 'Check the melody before you substitute'),
            steps: [
              t('爵士配法从古典配法出发：先按上下文加七音（Imaj7、ii7、V7……），再在旋律允许的地方做替换，例如 IV → ii7、vi → VI7（副属）、终止处的 V7 → ♭II7（三全音替代）。', 'ジャズの付け方は古典から出発：まず文脈で七の和音（Imaj7・ii7・V7…）、次に旋律が許す所で代理：IV → ii7、vi → VI7（副属）、終止の V7 → ♭II7（トライトーン代理）。', 'The jazz setting starts from the classical one: add sevenths by context (Imaj7, ii7, V7…), then substitute where the melody allows, e.g. IV → ii7, vi → VI7 (applied), and the cadential V7 → ♭II7 (tritone sub).'),
              t('每次替换都要检查：旋律音在新和弦里会不会变成需要解决的音？会的话就不换。替换不保证任何旋律都能照用。', '代理のたびに確認：旋律音が新しい和音で解決の必要な音にならないか？なるなら代えない。代理はどんな旋律でもそのまま使えるとは限らない。', 'Check each substitution: would a melody note become a clash in the new chord? If so, don’t substitute. No substitution is guaranteed to fit every melody.'),
            ] },
          { type: 'choice', ref: 'omt-pb-substitutions',
            prompt: t('旋律音 B 落在 G7 上，换成 D♭7 后会怎样？', '旋律音 B が G7 の上。D♭7 に代えると？', 'Melody B over G7 — what happens with D♭7 instead?'),
            options: [t('B = C♭ 变成 D♭7 的七音 仍然可以', 'B = C♭ は D♭7 の 7 音、まだ使える', 'B = C♭ becomes D♭7’s seventh — still fine'), t('一定会摩擦', '必ずぶつかる', 'it always clashes'), t('B 变成根音', 'B が根音に', 'B becomes the root')], answer: 0,
            hint: t('两个和弦共享三全音 B–F。', '2 つの和音は 3 全音 B–F を共有。', 'Both chords share the tritone B–F.'),
            explain: t('B 是 G7 的三音，同音异名的 C♭ 是 D♭7 的七音，所以替换后旋律仍是和弦音。', 'B は G7 の 3 音、異名同音の C♭ は D♭7 の 7 音なので、代理後も和音の音。', 'B is G7’s third; as C♭ it is D♭7’s seventh, so the melody stays a chord tone.') },
          { type: 'choice', ref: 'omt-pb-substitutions',
            prompt: t('爵士配法为什么只在终止处用三全音替代？', 'なぜジャズの付け方はトライトーン代理を終止だけで使う？', 'Why does the jazz setting use the tritone sub only at the cadence?'),
            options: [t('三全音替代最适合解决到 I 的 V7', 'トライトーン代理は I へ解決する V7 にいちばん向く', 'it works best on a V7 resolving to I'), t('因为只能用一次', '1 回しか使えない', 'it may only be used once'), t('因为中间没有属七', '途中に属七がない', 'there are no other dominants')], answer: 0,
            hint: t('OMT 的说法。', 'OMT の説明。', 'OMT’s advice.'),
            explain: t('OMT 说不是每个 V7 都该换，三全音替代在 V7 解决到 I 时最好听。', 'OMT はすべての V7 を代えるべきではなく、V7 が I へ解決する時がいちばん良いと言う。', 'OMT says not every V7 should be replaced; the tritone sub sounds best when V7 resolves to I.') },
          { type: 'choice', ref: 'omt2e-tonicization',
            prompt: t('vi 换成 VI7 的条件是？', 'vi を VI7 に代える条件は？', 'When can vi become VI7?'),
            options: [t('后面接 ii（VI7 = V7/ii）且旋律不摩擦', '次が ii（VI7 = V7/ii）で旋律がぶつからない', 'when ii follows (VI7 = V7/ii) and the melody doesn’t clash'), t('随时都可以', 'いつでも', 'always'), t('只有在小调里', '短調だけ', 'only in minor')], answer: 0,
            hint: t('副属要有目标。', '副属には目標が必要。', 'An applied chord needs a target.'),
            explain: t('VI7 是指向 ii 的副属，要接到 ii 才成立；同时还要检查旋律音（例如 C 在 A7 上会和 C♯ 冲突）。', 'VI7 は ii を指す副属で、ii に進んで成立。旋律も確認（例えば C は A7 の C♯ とぶつかる）。', 'VI7 is an applied chord to ii, so ii must follow; and check the melody (a C would clash with A7’s C♯).') },
        ],
      },
      {
        title: t('布鲁斯配法', 'ブルースの付け方', 'Blues setting'),
        cards: [
          { type: 'guide', ref: 'omt-pb-blues',
            visual: { kind: 'blocks', rows: [
              { label: t('旋律', '旋律', 'melody'), cells: cells('C', 'E', 'G', 'A', 'G', 'F', 'D', 'C') },
              { label: t('布鲁斯', 'ブルース', 'blues'), cells: cells({ text: 'C7', lit: true }, 'C7', 'C7', 'F7', 'C7', 'F7', { text: 'G7' }, { text: 'C7', lit: true }) },
            ] },
            tour: [
              m('row1', t('只用 I7 IV7 V7', 'I7 IV7 V7 だけ', 'only I7 IV7 V7')),
              m(['c1-0', 'c1-7'], t('开头和结尾都是 I7', '始まりと終わりは I7', 'start and end on I7'), 'below'),
            ],
            title: t('三个属七就够了', '属七 3 つで十分', 'Three dominant sevenths are enough'),
            steps: [
              t('布鲁斯配法只用 I7、IV7、V7：每个旋律音挑一个让它成为和弦音（或至少是延伸音）的和弦，开头和结尾用 I7。', 'ブルースの付け方は I7・IV7・V7 だけ。各旋律音に、それが和音の音（少なくとも延長音）になる和音を選び、始まりと終わりは I7。', 'The blues setting uses only I7, IV7 and V7: for each melody note pick the one where it is a chord tone (or at least a tension), starting and ending on I7.'),
              t('这些属七不需要解决到别的和弦；IV7–I7 的变格收束很自然。', 'これらの属七はほかの和音へ解決しなくてよい。IV7–I7 の変格終止が自然。', 'These dominant sevenths need not resolve; an IV7–I7 plagal close is natural.'),
            ] },
          { type: 'choice', ref: 'omt-pb-blues',
            prompt: t('旋律音 A 在布鲁斯配法里最适合配哪个和弦？（C 调）', '旋律音 A にブルースの付け方でいちばん合うのは？（ハ調）', 'In a blues setting in C, melody A fits best over…'),
            options: ['F7', 'C7', 'G7'], answer: 0,
            hint: t('F7 = F A C E♭。', 'F7 = F A C E♭。', 'F7 = F A C E♭.'),
            explain: t('A 是 F7 的三音；在 C7 上是 13，在 G7 上是 9，F7 让它成为和弦音。', 'A は F7 の 3 音。C7 では 13、G7 では 9、F7 なら和音の音。', 'A is F7’s third; over C7 it is the 13th, over G7 the 9th — F7 makes it a chord tone.') },
          { type: 'choice', ref: 'omt-pb-blues',
            prompt: t('布鲁斯配法里，IV7 之后一定要接 V7 吗？', 'ブルースの付け方で IV7 の後は必ず V7？', 'In a blues setting, must IV7 be followed by V7?'),
            options: [t('不必 IV7–I7 的变格收束很自然', '必要ない、IV7–I7 の変格が自然', 'no — an IV7–I7 plagal close is natural'), t('必须', '必ず', 'yes, always'), t('必须接 ii7', 'ii7 が必要', 'it must go to ii7')], answer: 0,
            hint: t('布鲁斯强调变格。', 'ブルースは変格を強調。', 'The blues favours plagal motion.'),
            explain: t('布鲁斯的属七不必解决，IV7 直接回 I7 很常见。', 'ブルースの属七は解決しなくてよく、IV7 から I7 へ戻るのはよくある。', 'Blues dominants need not resolve; IV7 straight back to I7 is common.') },
          { type: 'match', ref: ['omt2e-phrase-model', 'omt-pb-substitutions', 'omt-pb-blues'],
            prompt: t('配法 ↔ 特点', '付け方 ↔ 特徴', 'Setting ↔ trait'),
            pairs: [[t('古典', '古典', 'classical'), t('T–PD–D–T 以 V–I 收束', 'T–PD–D–T、V–I で終止', 'T–PD–D–T, ending V–I')], [t('爵士', 'ジャズ', 'jazz'), t('七和弦与替换', '七の和音と代理', 'sevenths and substitutions')], [t('布鲁斯', 'ブルース', 'blues'), t('只用 I7 IV7 V7', 'I7 IV7 V7 だけ', 'only I7 IV7 V7')]],
            hint: t('想想再和声工具里的三行。', 'リハーモナイズ・ツールの 3 行。', 'The three rows of the tool.'),
            explain: t('古典重功能与终止，爵士加七音和替换，布鲁斯用三个属七。', '古典は働きと終止、ジャズは七の和音と代理、ブルースは属七 3 つ。', 'Classical stresses function and cadence, jazz adds sevenths and substitutions, blues uses three dominant sevenths.') },
        ],
      },
    ],
  },

  // ======================= 爵士进行分析 2：turnaround 家族 =======================
  {
    id: 'turnarounds', parent: 'keycenter', section: 'jazz', feature: 'other', icon: 'TA',
    title: t('爵士进行分析 2：turnaround 家族', 'ジャズ進行分析 2：ターンアラウンドの仲間', 'Jazz analysis 2: the turnaround family'),
    blurb: t('I–vi–ii–V 与它的变体：大三的 VI、副属链、ii–♭II–I、ragtime 进行与 Tadd Dameron turnaround', 'I–vi–ii–V とその変化：長三の VI・副属の連鎖・ii–♭II–I・ラグタイム進行・タッド・ダメロン', 'I–vi–ii–V and its variants: major VI, chains of applied dominants, ii–♭II–I, the ragtime progression and the Tadd Dameron turnaround'),
    cards: [
      { type: 'guide', ref: ['wiki-turnaround', 'wiki-circle-progression'], demo: { play: [[48, 55, 64, 71], [45, 55, 60, 64], [50, 53, 57, 60], [43, 53, 59, 62]] },
        visual: { kind: 'blocks', rows: [{ arrows: true, cells: cells({ text: 'I', lit: true }, 'vi', 'ii', { text: 'V', lit: true }) }] },
        tour: [
          m('c0-0', t('通常从主和弦（或代替它的 iii）开始', 'ふつう主和音（または代わりの iii）から', 'usually starts on the tonic (or iii)')),
          m('c0-3', t('结束在属七 下一段从 I 开始', '属七で終わり、次は I から', 'ends on V7; the next section starts on I'), 'below'),
        ],
        title: t('最常见的一种：I–vi–ii–V', 'いちばん多い：I–vi–ii–V', 'The commonest: I–vi–ii–V'),
        steps: [
          t('turnaround 放在段落结尾，带回下一段（多半是同一段或整首重来）。典型的 turnaround 从主和弦（或代替它的 iii）开始，结束在属七上，下一段从 I 开始。', 'ターンアラウンドは段落の終わりで次の部分（同じ部分か曲全体）へ導く。典型的には主和音（または代わりの iii）で始まり属七で終わり、次は I から。', 'A turnaround at the end of a section leads into the next (usually a repeat). Typical turnarounds begin on the tonic (or iii in its place) and end on the dominant seventh, with the next section starting on I.'),
          t('最常见的是 I–vi–ii–V，常在一段的最后两小节出现；它也是 rhythm changes A 段里两小节的模式。turnaround 里的和弦常都是七和弦：大三和弦用属七、小三和弦用小七。', 'いちばん多いのは I–vi–ii–V、段落の最後の 2 小節によく出る。リズム・チェンジの A 部分の 2 小節の型でもある。ターンアラウンドの和音はふつう七の和音：長三は属七、短三はマイナー・セブンス。', 'The most common is I–vi–ii–V, often in the last two bars of a section; it is also the two-bar pattern of the rhythm-changes A section. Turnaround chords are often all sevenths: dominant sevenths on major chords, minor sevenths on minor ones.'),
        ] },
      { type: 'choice', ref: 'wiki-turnaround',
        prompt: t('turnaround 通常结束在哪个和弦上？', 'ターンアラウンドはふつうどの和音で終わる？', 'A turnaround usually ends on…'),
        options: [t('属七（V7）', '属七（V7）', 'the dominant seventh (V7)'), t('主和弦', '主和音', 'the tonic'), t('下属和弦', '下属和音', 'the subdominant')], answer: 0,
        hint: t('下一段从 I 开始。', '次の部分は I から。', 'The next section starts on I.'),
        explain: t('turnaround 结束在 V7（或它的替代 ♭II7），下一段从主和弦开始。', 'V7（またはその代理 ♭II7）で終わり、次は主和音から。', 'It ends on V7 (or its substitute ♭II7), with the next section starting on I.') },
      { type: 'choice', ref: 'wiki-circle-progression',
        prompt: t('I–vi–ii–V 为什么也被叫作"circle progression"的一种？', 'I–vi–ii–V がサークル進行の一種とされるのは？', 'Why is I–vi–ii–V counted among circle progressions?'),
        options: [t('vi ii V I 的根音沿五度圈下行', 'vi ii V I の根音が 5 度圏を下る', 'the roots of vi ii V I fall around the circle of fifths'), t('它有十二个和弦', '和音が 12 ある', 'it has twelve chords'), t('它只用大三和弦', '長三和音だけ', 'it uses only major chords')], answer: 0,
        hint: t('A → D → G → C。', 'A → D → G → C。', 'A → D → G → C.'),
        explain: t('vi–ii–V–I 的根音一路下行五度（A D G C），是五度链的末段。', 'vi–ii–V–I の根音は 5 度下行（A D G C）、5 度の連鎖の最後の部分。', 'The roots of vi–ii–V–I fall by fifths (A D G C), the tail of the circle progression.') },
      { type: 'choice', ref: 'wiki-turnaround',
        prompt: t('turnaround 里的和弦都加七音时，大三和弦通常用？', 'ターンアラウンドの和音をすべて七にする時、長三和音はふつう？', 'When every turnaround chord has a seventh, major chords usually take…'),
        options: [t('属七', '属七', 'dominant sevenths'), t('大七', 'メジャー・セブンス', 'major sevenths'), t('减七', '減七', 'diminished sevenths')], answer: 0,
        hint: t('维基："typically dominant seventh chords for major chords"。', 'ウィキ：長三には属七。', 'Wikipedia: dominant sevenths for major chords.'),
        explain: t('turnaround 里大三和弦常用属七，小三和弦用小七（如 ii7）。', 'ターンアラウンドでは長三が属七、短三がマイナー・セブンス（ii7 など）。', 'In turnarounds, major chords usually take dominant sevenths and minor chords minor sevenths (e.g. ii7).') },
    ],
    branch: [
      {
        title: t('大三的 VI：I–VI–ii–V', '長三の VI：I–VI–ii–V', 'Major VI: I–VI–ii–V'),
        cards: [
          { type: 'guide', ref: 'wiki-turnaround', demo: { play: [[48, 55, 64], [45, 57, 61, 64], [50, 57, 65], [43, 55, 62, 65]] },
            visual: { kind: 'blocks', rows: [
              { label: t('和弦', '和音', 'chords'), arrows: true, cells: cells('C', { text: 'A', sub: 'C♯', lit: true }, 'Dm', 'G7') },
              { label: t('半音线', '半音の線', 'chromatic line'), cells: cells('C', { text: 'C♯', lit: true }, 'D', '') },
            ] },
            tour: [
              m('c0-1', t('VI = V/ii', 'VI = V/ii', 'VI = V/ii')),
              m('row1', t('C – C♯ – D 半音上行', 'C – C♯ – D の半音上行', 'C – C♯ – D rising chromatically'), 'below'),
            ],
            title: t('小三变大三，产生半音线', '短三を長三に、半音の線', 'Minor to major creates a chromatic line'),
            steps: [
              t('布鲁斯和爵士里常把本来是小三和弦的 vi 改成大三和弦：I–VI–ii–V。VI 的三音（C 调里是 C♯）让 C–C♯–D 半音上行，VI 成为指向 ii 的副属 V/ii。', 'ブルースやジャズでは本来短三の vi を長三にすることが多い：I–VI–ii–V。VI の 3 音（ハ調で C♯）で C–C♯–D の半音上行、VI は ii を指す副属 V/ii。', 'Blues and jazz often make the minor vi major: I–VI–ii–V. VI’s third (C♯ in C) creates the chromatic rise C–C♯–D, making VI the applied V/ii.'),
              t('同样的道理也可以用在 II：II7–V7–I（V7/V–V7–I）代替 ii–V–I。', '同じ考えは II にも：ii–V–I の代わりに II7–V7–I（V7/V–V7–I）。', 'The same idea works on II: II7–V7–I (V7/V–V7–I) instead of ii–V–I.'),
            ] },
          { type: 'choice', ref: 'wiki-turnaround',
            prompt: t('C 调 I–VI–ii–V 里，VI 的三音是？', 'ハ調の I–VI–ii–V で VI の 3 音は？', 'In C, the third of VI in I–VI–ii–V is…'),
            options: ['C♯', 'C', 'E'], answer: 0,
            hint: t('A 大三和弦。', 'A の長三和音。', 'A major.'),
            explain: t('A 大三 = A C♯ E；C♯ 把 C 和 D 连成半音线。', 'A の長三 = A C♯ E。C♯ が C と D を半音でつなぐ。', 'A major = A C♯ E; C♯ links C and D chromatically.') },
          { type: 'choice', ref: 'wiki-turnaround',
            prompt: t('VI 在这里的功能是？', 'ここでの VI の働きは？', 'What is VI’s function here?'),
            options: ['V/ii', 'V/V', t('主和弦', '主和音', 'tonic')], answer: 0,
            hint: t('它后面接 ii。', '次は ii。', 'ii follows.'),
            explain: t('A（VI）往下五度到 D（ii），是 ii 的副属：V/ii。', 'A（VI）から 5 度下の D（ii）、ii の副属 V/ii。', 'A (VI) falls a fifth to D (ii): V/ii.') },
          { type: 'choice', ref: 'wiki-turnaround',
            prompt: t('II7–V7–I 里的 II7 是？', 'II7–V7–I の II7 は？', 'In II7–V7–I, II7 is…'),
            options: ['V7/V', 'V7/ii', t('三全音替代', 'トライトーン代理', 'a tritone substitute')], answer: 0,
            hint: t('D7 → G7。', 'D7 → G7。', 'D7 → G7.'),
            explain: t('D7 是 G（V）的属七：V7/V。', 'D7 は G（V）の属七：V7/V。', 'D7 is the dominant of G (V): V7/V.') },
        ],
      },
      {
        title: t('副属链：ragtime 进行', '副属の連鎖：ラグタイム進行', 'Chains of applied dominants: the ragtime progression'),
        cards: [
          { type: 'guide', ref: ['wiki-ragtime-progression', 'wiki-turnaround'],
            visual: { kind: 'blocks', rows: [{ arrows: true, cells: cells({ text: 'E7', sub: 'V7/vi' }, { text: 'A7', sub: 'V7/ii' }, { text: 'D7', sub: 'V7/V' }, { text: 'G7', sub: 'V7', lit: true }, { text: 'C', sub: 'I' }) }] },
            tour: [
              m(['c0-0', 'c0-1', 'c0-2'], t('每个都是下一个的属七', 'それぞれ次の和音の属七', 'each is the dominant of the next')),
              m('c0-3', t('最后回到真正的 V', '最後は本当の V', 'finally the real V'), 'below'),
            ],
            title: t('一路属七回到主和弦', '属七の連鎖で主和音へ', 'Dominants all the way home'),
            steps: [
              t('ragtime 进行是 V7/vi–V7/ii–V7/V–V7–I：在 C 调是 E7–A7–D7–G7–C，每个属七都指向下一个和弦，根音一路下行五度。', 'ラグタイム進行は V7/vi–V7/ii–V7/V–V7–I。ハ調で E7–A7–D7–G7–C、各属七が次の和音を指し、根音は 5 度下行。', 'The ragtime progression is V7/vi–V7/ii–V7/V–V7–I: in C, E7–A7–D7–G7–C, each dominant pointing to the next with roots falling by fifths.'),
              t('同样的链也出现在 turnaround 里：iii–VI–ii–V（或全用属七 III7–VI7–II7–V7）。', '同じ連鎖はターンアラウンドにも：iii–VI–ii–V（すべて属七なら III7–VI7–II7–V7）。', 'The same chain appears in turnarounds: iii–VI–ii–V (or all dominants, III7–VI7–II7–V7).'),
            ] },
          { type: 'choice', ref: 'wiki-ragtime-progression',
            prompt: t('C 调的 ragtime 进行是？', 'ハ調のラグタイム進行は？', 'The ragtime progression in C is…'),
            options: ['E7 A7 D7 G7 C', 'C Am Dm G7 C', 'C E7 Am C7 F'], answer: 0,
            hint: t('V7/vi 开始。', 'V7/vi から。', 'It starts on V7/vi.'),
            explain: t('V7/vi（E7）→ V7/ii（A7）→ V7/V（D7）→ V7（G7）→ I（C）。', 'V7/vi（E7）→ V7/ii（A7）→ V7/V（D7）→ V7（G7）→ I（C）。', 'V7/vi (E7) → V7/ii (A7) → V7/V (D7) → V7 (G7) → I (C).') },
          { type: 'choice', ref: 'wiki-ragtime-progression',
            prompt: t('A7 在 ragtime 进行里是？', 'ラグタイム進行の A7 は？', 'In the ragtime progression, A7 is…'),
            options: ['V7/ii', 'V7/V', 'V7/vi'], answer: 0,
            hint: t('它后面是 D7（ii 的根音）。', '次は D7（ii の根音）。', 'D (the root of ii) follows.'),
            explain: t('A7 往下五度到 D：指向第二级，V7/ii。', 'A7 から 5 度下の D：第 2 度を指す V7/ii。', 'A7 falls a fifth to D: V7/ii.') },
          { type: 'choice', ref: 'wiki-turnaround',
            prompt: t('iii–VI–ii–V 在 C 调是？', 'iii–VI–ii–V はハ調で？', 'iii–VI–ii–V in C is…'),
            options: ['Em A Dm G', 'E A D G', 'Em Am Dm G'], answer: 0,
            hint: t('只有 VI 是大三。', 'VI だけ長三。', 'Only VI is major.'),
            explain: t('iii = Em、VI = A（大三）、ii = Dm、V = G。', 'iii = Em、VI = A（長三）、ii = Dm、V = G。', 'iii = Em, VI = A (major), ii = Dm, V = G.') },
        ],
      },
      {
        title: t('ii–♭II–I 与 Tadd Dameron', 'ii–♭II–I とタッド・ダメロン', 'ii–♭II–I and Tadd Dameron'),
        cards: [
          { type: 'guide', ref: ['wiki-turnaround', 'omt-pb-substitutions'], demo: { play: [[50, 57, 60, 65], [49, 56, 59, 65], [48, 55, 59, 64]] },
            visual: { kind: 'blocks', rows: [
              { label: 'ii–♭II–I', arrows: true, cells: cells('Dm', { text: 'D♭', lit: true }, 'C') },
              { label: 'Tadd Dameron', arrows: true, cells: cells('I', '♭III', '♭VI', { text: '♭II7', lit: true }) },
            ] },
            tour: [
              m('row0', t('根音 D – D♭ – C', '根音 D – D♭ – C', 'roots D – D♭ – C')),
              m('c1-3', t('结尾也可以是 ♭II7（V 的替代）', '終わりは ♭II7（V の代理）でもよい', 'it may end on ♭II7, a V substitute'), 'below'),
            ],
            title: t('换掉 V，换来半音线', 'V を代えて半音の線', 'Swap V for a chromatic line'),
            steps: [
              t('ii–♭II–I（Dm–D♭–C）是 ii–V–I 的变体：用 ♭II 代替 V 就是三全音替代。根音 D–D♭–C、三音 F–F–E、五音 A–A♭–G 都在半音移动。', 'ii–♭II–I（Dm–D♭–C）は ii–V–I の変化：V の代わりに ♭II、これがトライトーン代理。根音 D–D♭–C、3 音 F–F–E、5 音 A–A♭–G がみな半音で動く。', 'ii–♭II–I (Dm–D♭–C) varies ii–V–I: ♭II in place of V is the tritone substitution. Roots D–D♭–C, thirds F–F–E and fifths A–A♭–G all move by semitone.'),
              t('turnaround 也可以结束在 ♭II7（属的替代）上，例如 Tadd Dameron turnaround I–♭III–♭VI–♭II7。', 'ターンアラウンドは ♭II7（属の代理）で終わることもある。例：タッド・ダメロン・ターンアラウンド I–♭III–♭VI–♭II7。', 'A turnaround can also end on ♭II7 (a dominant substitute), as in the Tadd Dameron turnaround I–♭III–♭VI–♭II7.'),
            ] },
          { type: 'choice', ref: 'wiki-turnaround',
            prompt: t('ii–♭II–I 里，♭II 代替了谁？', 'ii–♭II–I で ♭II は何の代わり？', 'In ii–♭II–I, ♭II replaces…'),
            options: ['V', 'IV', 'vi'], answer: 0,
            hint: t('三全音替代。', 'トライトーン代理。', 'Tritone substitution.'),
            explain: t('♭II 是 V 的三全音替代，低音变成 D–D♭–C 的半音下行。', '♭II は V のトライトーン代理、バスは D–D♭–C の半音下行。', '♭II is the tritone sub for V, giving the chromatic bass D–D♭–C.') },
          { type: 'choice', ref: 'wiki-turnaround',
            prompt: t('Tadd Dameron turnaround 在 C 调是？', 'タッド・ダメロンはハ調で？', 'The Tadd Dameron turnaround in C is…'),
            options: ['C E♭ A♭ D♭7', 'C A D G7', 'C E A D7'], answer: 0,
            hint: t('I–♭III–♭VI–♭II7。', 'I–♭III–♭VI–♭II7。', 'I–♭III–♭VI–♭II7.'),
            explain: t('I = C、♭III = E♭、♭VI = A♭、♭II7 = D♭7。', 'I = C、♭III = E♭、♭VI = A♭、♭II7 = D♭7。', 'I = C, ♭III = E♭, ♭VI = A♭, ♭II7 = D♭7.') },
          { type: 'choice', ref: 'wiki-turnaround',
            prompt: t('Dm–D♭–C 里，五音的半音线是？', 'Dm–D♭–C で 5 音の半音の線は？', 'In Dm–D♭–C, the fifths move…'),
            options: ['A – A♭ – G', 'F – F – E', 'D – D♭ – C'], answer: 0,
            hint: t('Dm 的五音是 A。', 'Dm の 5 音は A。', 'Dm’s fifth is A.'),
            explain: t('五音 A → A♭ → G；三音 F → F → E；根音 D → D♭ → C。', '5 音 A → A♭ → G、3 音 F → F → E、根音 D → D♭ → C。', 'Fifths A → A♭ → G; thirds F → F → E; roots D → D♭ → C.') },
        ],
      },
      {
        title: t('综合：认出 turnaround 的变体', '総合：ターンアラウンドの変化を見分ける', 'Spotting turnaround variants'),
        cards: [
          { type: 'guide', ref: ['wiki-turnaround', 'wiki-circle-progression'],
            visual: { kind: 'blocks', rows: [
              { label: t('基本', '基本', 'basic'), cells: cells('I', 'vi', 'ii', 'V') },
              { label: t('副属', '副属', 'applied'), cells: cells('I', { text: 'VI', lit: true }, { text: 'II', lit: true }, 'V') },
              { label: t('替代', '代理', 'substitute'), cells: cells('I', 'vi', 'ii', { text: '♭II', lit: true }) },
            ] },
            tour: [
              m('row0', t('骨架', '骨組み', 'the skeleton')),
              m(['row1', 'row2'], t('改性质或换根音', '性質を変えるか根音を変える', 'change quality or swap roots'), 'below'),
            ],
            title: t('先找骨架，再看改了什么', 'まず骨組み、何が変わったか', 'Find the skeleton, then what changed'),
            steps: [
              t('看到一串和弦，先找 I–vi–ii–V 的骨架：最后是不是 V（或 ♭II）、前面是不是一串五度下行。', '和音の並びを見たら、まず I–vi–ii–V の骨組み：最後が V（か ♭II）か、前が 5 度下行の連鎖か。', 'Facing a string of chords, look for the I–vi–ii–V skeleton: does it end on V (or ♭II), with falling fifths before it?'),
              t('再看哪里改了：小三变大三（VI、II → 副属）、V 换成 ♭II（三全音替代）、前面换成 iii（主的替代）。在调性中心与进行分析里输入进行，可以看到每个和弦的分析。', '次に変わった所：短三が長三（VI・II → 副属）、V が ♭II（トライトーン代理）、最初が iii（主の代理）。調性中心と進行分析に入力すると各和音の分析が見られる。', 'Then see what changed: minor made major (VI, II → applied), V swapped for ♭II (tritone sub), the start replaced by iii (a tonic substitute). Enter the progression in key-center analysis to see each chord analysed.'),
            ] },
          { type: 'choice', ref: 'wiki-turnaround',
            prompt: t('C – A7 – D7 – G7 是哪一种 turnaround？', 'C – A7 – D7 – G7 はどのターンアラウンド？', 'C – A7 – D7 – G7 is which turnaround?'),
            options: [t('I–VI–II–V（副属）', 'I–VI–II–V（副属）', 'I–VI–II–V (applied dominants)'), t('I–vi–ii–V', 'I–vi–ii–V', 'I–vi–ii–V'), 'Tadd Dameron'], answer: 0,
            hint: t('A7、D7 都是属七。', 'A7・D7 はどちらも属七。', 'A7 and D7 are both dominants.'),
            explain: t('VI 与 II 都变成大三 / 属七：I–V/ii–V/V–V。', 'VI と II が長三 / 属七に：I–V/ii–V/V–V。', 'VI and II become dominants: I–V/ii–V/V–V.') },
          { type: 'choice', ref: 'wiki-turnaround',
            prompt: t('Em – Am – Dm – G 开头的 iii 代替了谁？', 'Em – Am – Dm – G の最初の iii は何の代わり？', 'In Em – Am – Dm – G, the opening iii replaces…'),
            options: [t('主和弦 I', '主和音 I', 'the tonic I'), 'V', 'IV'], answer: 0,
            hint: t('turnaround 通常从 I 或它的替代开始。', 'ふつう I かその代わりから。', 'Turnarounds start on I or a substitute.'),
            explain: t('维基：turnaround 通常从主和弦或代替它的 iii 开始。', 'ウィキ：主和音か代わりの iii から始まる。', 'Wikipedia: turnarounds usually begin on the tonic or a substitute such as iii.') },
          { type: 'choice', ref: 'wiki-turnaround',
            prompt: t('C – Am – Dm – D♭7 的最后一个和弦是？', 'C – Am – Dm – D♭7 の最後の和音は？', 'The last chord of C – Am – Dm – D♭7 is…'),
            options: [t('V 的三全音替代（♭II7）', 'V のトライトーン代理（♭II7）', 'the tritone substitute for V (♭II7)'), t('借用的 ♭II', '借用の ♭II', 'a borrowed ♭II'), t('IV 的替代', 'IV の代わり', 'a substitute for IV')], answer: 0,
            hint: t('它接回 C 时根音半音下行。', 'C に戻る時、根音が半音下行。', 'Its root slides down a semitone to C.'),
            explain: t('D♭7 代替 G7，半音下行回到下一段开头的 C。', 'D♭7 が G7 の代わり、半音下行で次の C へ。', 'D♭7 replaces G7, sliding down a semitone to the C that starts the next section.') },
        ],
      },
    ],
  },
];
