// 乐理闯关 · 和弦与和声：每张题卡标出依据（ref），只使用 references.js 中已登记、已核实的资料；解析用尽量通俗的话转述这些资料。
// 依据汇总（由 scripts/annotate-learn.mjs 生成）：
//   ref:omt-triads ref:omt2e-triads ref:omt2e-sevenths ref:omt2e-figured-bass ref:wiki-chord-notation
//   ref:omt2e-chord-symbols ref:wiki-suspended-chord ref:wiki-added-tone ref:wiki-power-chord ref:wiki-sixth-chord
//   ref:wiki-voicing ref:omt2e-roman-numerals ref:omt2e-jazz-voicings ref:omt2e-phrase-model ref:omt2e-cadences
//   ref:omt2e-predominants ref:wiki-dominant-seventh ref:musictheory-net-cadences ref:omt2e-la-bass ref:omt2e-cad64
//   ref:omt2e-64-chords ref:omt-rondo ref:omt2e-form-concepts ref:omt2e-phrase ref:omt2e-binary ref:omt2e-ternary
//   ref:omt2e-sonata ref:omt2e-tonicization ref:omt2e-modulation ref:omt2e-mixture ref:omt2e-neapolitan
//   ref:omt2e-aug6 ref:omt2e-common-tone ref:wiki-circle-of-fifths ref:omt2e-neo-riemannian
// @refs-end

const t = (zh, ja, en) => ({ zh, ja, en });
const opt = (id, label) => ({ id, label });

const ALL = [
  {
    id: 'triads', section: 'harmony', feature: 'chord', icon: '△',
    title: t('三和弦：叠起来的三度', '三和音：重ねた 3 度', 'Triads: stacked thirds'),
    blurb: t('大、小、减、增', '長・短・減・増', 'Major, minor, diminished, augmented'),
    cards: [
      { type: 'guide', ref: ['omt-triads', 'omt2e-triads'], demo: { keys: [60, 64, 67], play: [[60, 64, 67], [60, 63, 67]] },
        title: t('三个音叠成一个和弦', '3 つの音を重ねて和音に', 'Three notes, one chord'),
        steps: [
          t('隔一个音取一个：C、E、G——像叠积木一样叠两个三度，就是三和弦。', '1 つおきに C・E・G。3 度を 2 つ積み木のように重ねると三和音。', 'Skip every other note: C, E, G — two thirds stacked like blocks make a triad.'),
          t('先听两个：第一个是大三和弦（C E G），第二个是小三和弦（C E♭ G）。哪个更明亮？', '2 つ聴いてみよう：長三和音（C E G）と短三和音（C E♭ G）。どちらが明るい？', 'Hear two: a major triad (C E G) then a minor triad (C E♭ G). Which is brighter?'),
          t('区别只在中间那个音：根音上方是大三度还是小三度。', '違いは真ん中の音だけ。根音の上が長 3 度か短 3 度か。', 'The only difference is the middle note: a major or minor third above the root.'),
        ] },
      { type: 'choice', ref: 'omt-triads', audio: { notes: [57, 60, 64], mode: 'chord' },
        prompt: t('听：这是什么三和弦？', '聴いて：何の三和音？', 'Listen: which triad is this?'),
        options: [t('小三和弦', '短三和音', 'minor'), t('大三和弦', '長三和音', 'major'), t('减三和弦', '減三和音', 'diminished')], answer: 0,
        hint: t('偏暗、偏柔和？', '少し暗くて柔らかい？', 'A bit darker and softer?'),
        explain: t('A C E：A 到 C 是小三度，A 到 E 是纯五度——小三和弦。', 'A C E：A–C は短 3 度、A–E は完全 5 度。短三和音。', 'A C E: A–C a minor third, A–E a perfect fifth — a minor triad.') },
      { type: 'match', ref: 'omt-triads',
        prompt: t('三和弦 ↔ 根音上方的音程', '三和音 ↔ 根音上の音程', 'Triad ↔ intervals above the root'),
        pairs: [[t('大三和弦', '長三和音', 'major'), 'M3 + P5'], [t('小三和弦', '短三和音', 'minor'), 'm3 + P5'], [t('减三和弦', '減三和音', 'diminished'), 'm3 + d5'], [t('增三和弦', '増三和音', 'augmented'), 'M3 + A5']],
        hint: t('M 大、m 小、P 纯、d 减、A 增。', 'M 長・m 短・P 完全・d 減・A 増。', 'M major, m minor, P perfect, d diminished, A augmented.'),
        explain: t('大 = 大三度 + 纯五度；小 = 小三度 + 纯五度；减 = 小三度 + 减五度；增 = 大三度 + 增五度。', '長 = 長 3 度 + 完全 5 度、短 = 短 3 度 + 完全 5 度、減 = 短 3 度 + 減 5 度、増 = 長 3 度 + 増 5 度。', 'Major = M3 + P5; minor = m3 + P5; diminished = m3 + d5; augmented = M3 + A5.') },
      { type: 'fill', ref: 'omt-triads',
        prompt: t('D 大三和弦：D、___、A', 'D 長三和音：D・___・A', 'D major triad: D, ___, A'),
        bank: [opt('F#', 'F♯'), opt('F', 'F'), opt('G', 'G')], answer: ['F#'],
        hint: t('D 往上大三度：数 4 个半音。', 'D から長 3 度：半音 4 つ。', 'A major third above D: count four half steps.'),
        explain: t('D → D♯ → E → F → F♯，4 个半音是 F♯。', 'D → D♯ → E → F → F♯、半音 4 つで F♯。', 'D → D♯ → E → F → F♯: four half steps lands on F♯.') },
      { type: 'choice', ref: 'omt-triads', audio: { notes: [60, 64, 68], mode: 'chord' },
        prompt: t('听这个有点"悬着"的和弦：', '少し「宙に浮いた」和音：', 'This one sounds a bit "floating":'),
        options: [t('增三和弦', '増三和音', 'augmented'), t('减三和弦', '減三和音', 'diminished'), t('大三和弦', '長三和音', 'major')], answer: 0,
        hint: t('最上面的音被往上推了一点。', 'いちばん上の音が少し押し上げられています。', 'The top note has been nudged upward.'),
        explain: t('C E G♯：大三度 + 增五度，是增三和弦。', 'C E G♯：長 3 度 + 増 5 度で増三和音。', 'C E G♯: major third + augmented fifth — augmented.') },
    ],
  },
  {
    id: 'symbols', section: 'harmony', feature: 'chordsymbols', icon: 'Cm',
    title: t('读懂和弦标记', 'コード表記を読む', 'Reading chord symbols'),
    blurb: t('Cm、C-、C°、Cø7 是什么？', 'Cm・C-・C°・Cø7 って何？', 'What are Cm, C-, C°, Cø7?'),
    cards: [
      { type: 'guide', ref: 'omt2e-chord-symbols',
        title: t('一个标记 = 根音 + 性质', '表記 = 根音 + 種類', 'A symbol = root + quality'),
        steps: [
          t('大写字母就是根音。只写一个字母（C）就是大三和弦。', '大文字が根音。文字だけ（C）なら長三和音。', 'The capital letter is the root. A bare letter (C) means a major triad.'),
          t('后面加 m 就是小三和弦（Cm）；加 7 就多一个七度，默认是小七度（C7）。', 'm を付けると短三和音（Cm）。7 を付けると 7 度が加わり、既定は短 7 度（C7）。', 'Add m for minor (Cm); add 7 for a seventh, which is minor by default (C7).'),
          t('同一个和弦常有好几种写法：Cm 也写作 C-、Cmin。', '同じ和音にいくつもの書き方：Cm は C-・Cmin とも。', 'One chord often has several spellings: Cm is also C- or Cmin.'),
        ] },
      { type: 'match', ref: 'wiki-chord-notation',
        prompt: t('不同写法 ↔ 标准写法', '別の書き方 ↔ 標準表記', 'Other spelling ↔ standard symbol'),
        pairs: [['C-', 'Cm'], ['C°', 'Cdim'], ['C+', 'Caug'], ['Cø7', 'Cm7b5']],
        hint: t('- 是小，° 是减，+ 是增，ø 是半减。', '- は短、° は減、+ は増、ø は半減。', '- minor, ° diminished, + augmented, ø half-diminished.'),
        explain: t('这些符号只是缩写：C- = Cm，C° = Cdim，C+ = Caug，Cø7 = Cm7b5（半减七和弦）。', '記号は略記にすぎません：C- = Cm、C° = Cdim、C+ = Caug、Cø7 = Cm7b5。', 'They are shorthands: C- = Cm, C° = Cdim, C+ = Caug, Cø7 = Cm7b5.') },
      { type: 'choice', ref: 'omt2e-chord-symbols',
        prompt: t('C7 是哪一种？', 'C7 はどれ？', 'C7 is…'),
        options: [t('大三和弦 + 小七度（属七）', '長三和音 + 短 7 度（属七）', 'major triad + minor seventh (dominant 7th)'), t('大三和弦 + 大七度', '長三和音 + 長 7 度', 'major triad + major seventh'), t('小三和弦 + 小七度', '短三和音 + 短 7 度', 'minor triad + minor seventh')], answer: 0,
        hint: t('三和弦默认是大的，7 默认是小七度。', '三和音は既定で長、7 は既定で短 7 度。', 'Triads default to major; a plain 7 defaults to minor.'),
        explain: t('C7 = C E G B♭：大三和弦加小七度，叫属七和弦。', 'C7 = C E G B♭：長三和音に短 7 度、属七の和音。', 'C7 = C E G B♭: a major triad plus a minor seventh — a dominant seventh.') },
      { type: 'fill', ref: 'omt2e-chord-symbols',
        prompt: t('Cmaj7：C、E、G、___', 'Cmaj7：C・E・G・___', 'Cmaj7: C, E, G, ___'),
        bank: [opt('B', 'B'), opt('Bb', 'B♭'), opt('A', 'A')], answer: ['B'],
        hint: t('maj7 说的是"大七度"。', 'maj7 は「長 7 度」。', 'maj7 means a major seventh.'),
        explain: t('C 往上大七度是 B，所以 Cmaj7 = C E G B。', 'C から長 7 度は B。Cmaj7 = C E G B。', 'A major seventh above C is B, so Cmaj7 = C E G B.') },
      { type: 'choice', ref: 'wiki-chord-notation',
        prompt: t('C/E 里斜杠后面的 E 是什么意思？', 'C/E のスラッシュの後の E は？', 'In C/E, what does the E after the slash mean?'),
        options: [t('最低的音（低音）是 E', 'いちばん低い音（ベース）が E', 'E is the lowest note (bass)'), t('再加一个 E', 'E を足す', 'add an E'), t('E 调', 'E の調', 'in the key of E')], answer: 0,
        hint: t('想想贝斯手要弹哪个音。', 'ベーシストが弾く音を考えて。', 'Think about what the bass player plays.'),
        explain: t('斜杠后面是低音：C/E = C 和弦，最低音弹 E（第一转位）。', 'スラッシュの後はベース：C/E = C の和音でベースが E（第 1 転回形）。', 'After the slash is the bass: C/E is a C chord with E in the bass (first inversion).') },
    ],
  },
  {
    id: 'sevenths', section: 'harmony', feature: 'ear', icon: '7',
    title: t('七和弦', '七の和音', 'Seventh chords'),
    blurb: t('再叠一个三度', 'もう 1 つ 3 度を重ねる', 'One more third on top'),
    cards: [
      { type: 'guide', ref: ['omt-triads', 'omt2e-sevenths'], demo: { play: [[55, 59, 62, 65], [48, 52, 55, 59]] },
        title: t('四个音的和弦', '4 音の和音', 'Four-note chords'),
        steps: [
          t('在三和弦上面再叠一个三度，就有了第四个音——七度。', '三和音の上にもう 1 つ 3 度を重ねると 4 つ目の音、7 度ができます。', 'Stack one more third on a triad and you get a fourth note: the seventh.'),
          t('常见的七和弦有五种：大七（大大七）、属七（大小七）、小七（小小七）、半减七、减七（全减七）。', 'よく使う七の和音は 5 種類：長七（長長七）・属七（長短七）・短七（短短七）・半減七・減七。', 'There are five common seventh chords: major seventh (major-major), dominant seventh (major-minor), minor seventh (minor-minor), half-diminished and (fully) diminished seventh.'),
          t('听：先是 G7（想往前走），再是 Cmaj7（柔和、像到家）。', '聴いて：G7（先へ進みたい）と Cmaj7（柔らかく家に着いた感じ）。', 'Listen: G7 (wants to move on), then Cmaj7 (soft, like arriving home).'),
        ] },
      { type: 'match', ref: 'omt-triads',
        prompt: t('七和弦 ↔ 根音上方的音程', '七の和音 ↔ 根音上の音程', 'Seventh chord ↔ intervals above the root'),
        pairs: [['maj7', 'M3 P5 M7'], ['7', 'M3 P5 m7'], ['m7', 'm3 P5 m7'], ['m7b5', 'm3 d5 m7'], ['dim7', 'm3 d5 d7']],
        hint: t('看三和弦是哪种，再看七度是大、小还是减。', '三和音の種類と、7 度が長・短・減のどれかを見る。', 'Check the triad, then whether the seventh is major, minor or diminished.'),
        explain: t('五种常见七和弦：大七、属七、小七、半减七、减七。', 'よく使う七の和音は 5 種類：長七・属七・短七・半減七・減七。', 'The five common sevenths: major 7th, dominant 7th, minor 7th, half-diminished, diminished.') },
      { type: 'choice', ref: 'omt-triads', audio: { notes: [55, 59, 62, 65], mode: 'chord' },
        prompt: t('听：这是哪种七和弦？', '聴いて：どの七の和音？', 'Listen: which seventh chord?'),
        options: [t('属七', '属七', 'dominant 7th'), t('大七', '長七', 'major 7th'), t('小七', '短七', 'minor 7th')], answer: 0,
        hint: t('有一种"迫不及待想解决"的感觉。', '「早く解決したい」感じ。', 'It sounds eager to resolve.'),
        explain: t('G B D F：大三和弦 + 小七度 = 属七和弦。', 'G B D F：長三和音 + 短 7 度 = 属七。', 'G B D F: major triad + minor seventh = dominant seventh.') },
      { type: 'fill', ref: 'omt-triads',
        prompt: t('Bdim7：B、D、F、___', 'Bdim7：B・D・F・___', 'Bdim7: B, D, F, ___'),
        bank: [opt('Ab', 'A♭'), opt('A', 'A'), opt('G#', 'G♯')], answer: ['Ab'],
        hint: t('减七度：要用 A 这个字母，又比 A 低一点。', '減 7 度：文字は A で、A より低い。', 'A diminished seventh: still the letter A, but lower.'),
        explain: t('B 往上七度是 A，减七度再降半音成 A♭（写 G♯ 就成了六度）。', 'B から 7 度は A、減 7 度でさらに半音下げて A♭（G♯ と書くと 6 度になる）。', 'A seventh above B is A; diminished lowers it to A♭ (G♯ would be a sixth).') },
      { type: 'choice', ref: 'omt-triads',
        prompt: t('dim7 和 m7b5 只差一个音，差在哪？', 'dim7 と m7b5 は 1 音違い。どこ？', 'dim7 and m7b5 differ in one note. Which?'),
        options: [t('七度（减七度 vs 小七度）', '7 度（減 7 度 と 短 7 度）', 'the seventh (d7 vs m7)'), t('三度', '3 度', 'the third'), t('五度', '5 度', 'the fifth')], answer: 0,
        hint: t('两者的三和弦都是减三和弦。', 'どちらも減三和音の上にできています。', 'Both sit on a diminished triad.'),
        explain: t('都是减三和弦；dim7 加减七度，m7b5 加小七度。', 'どちらも減三和音。dim7 は減 7 度、m7b5 は短 7 度を加えます。', 'Both use a diminished triad; dim7 adds a diminished seventh, m7b5 a minor seventh.') },
    ],
  },
  {
    id: 'functions', section: 'harmony', feature: 'harmonize', icon: 'T',
    // 五度圈上可以把调里各级和弦（罗马数字）标出来，方便看主、下属、属的位置
    extraTools: [{ feature: 'circle' }],
    title: t('和弦的角色：家、准备、想回家', '和音の役割：家・準備・帰りたい', 'Chord roles: home, getting ready, longing'),
    blurb: t('主、下属、属与终止式', '主・下属・属と終止', 'Tonic, predominant, dominant & cadences'),
    cards: [
      { type: 'guide', ref: 'omt2e-phrase-model', demo: { play: [[48, 52, 55], [53, 57, 60], [55, 59, 62], [48, 52, 55]] },
        title: t('一句音乐像一次小旅行', '音楽の一節は小さな旅', 'A phrase is a little trip'),
        steps: [
          t('从"家"出发（主 T），做点准备（下属 PD），走到最想回家的地方（属 D），再回家（T）。', '「家」（主 T）を出て、準備（下属 PD）をし、帰りたくてたまらない所（属 D）へ行き、家に帰る（T）。', 'Leave home (tonic, T), get ready (predominant, PD), reach the point of longing (dominant, D), then go home (T).'),
          t('在 C 大调里：I（C）是家，IV 和 ii 是准备，V（G）最想回家。听听 I–IV–V–I。', 'C 長調では I（C）が家、IV と ii が準備、V（G）が帰りたい。I–IV–V–I を聴こう。', 'In C major: I (C) is home, IV and ii get ready, V (G) longs for home. Hear I–IV–V–I.'),
        ] },
      { type: 'match', ref: ['omt2e-cadences', 'omt2e-predominants'],
        prompt: t('和弦 ↔ 角色', '和音 ↔ 役割', 'Chord ↔ role'),
        pairs: [['I', t('主（家）', '主（家）', 'tonic (home)')], ['ii6', t('下属（准备）', '下属（準備）', 'predominant (getting ready)')], ['V', t('属（想回家）', '属（帰りたい）', 'dominant (longing)')]],
        hint: t('主功能只有 I。', '主機能は I だけ。', 'Only I has tonic function.'),
        explain: t('主功能是 I；属功能是 V（以及 vii°）；ii6 和 IV 是很强的下属。', '主機能は I、属機能は V（と vii°）、ii6 と IV は強い下属。', 'Tonic is I; dominant is V (and vii°); ii6 and IV are strong predominants.') },
      { type: 'choice', ref: 'omt2e-cadences',
        prompt: t('一句话停在 V 上就结束了，像个问号。这叫？', 'V で止まって終わる、疑問符のような終わり方は？', 'A phrase that stops on V, like a question mark, ends with a…'),
        options: [t('半终止', '半終止', 'half cadence'), t('完全正格终止', '完全全終止', 'perfect authentic cadence'), t('没有名字', '名前はない', 'it has no name')], answer: 0,
        hint: t('只走了"一半"——还没回家。', '「半分」だけ。まだ家に帰っていない。', 'Only "halfway" — not home yet.'),
        explain: t('停在 V 上叫半终止（HC），像问句。', 'V で止まると半終止（HC）、問いかけのよう。', 'Stopping on V is a half cadence (HC) — like a question.') },
      { type: 'choice', ref: 'omt2e-cadences',
        prompt: t('完全正格终止（PAC）要满足什么？', '完全全終止（PAC）の条件は？', 'What makes a perfect authentic cadence (PAC)?'),
        options: [t('V–I 都是原位，最后旋律落在 do', 'V–I が両方基本形で、旋律の最後が do', 'V–I both in root position, melody ends on do'), t('只要有 V 就行', 'V があれば良い', 'any V will do'), t('最后停在 IV', '最後が IV', 'it ends on IV')], answer: 0,
        hint: t('最"完全"的回家：低音和旋律都回到主音。', 'いちばん「完全な」帰宅：ベースも旋律も主音へ。', 'The most complete homecoming: bass and melody both land on the tonic.'),
        explain: t('PAC：V 和 I 都是原位，最后旋律唱 do。V–I 但不满足这些，叫不完全正格终止（IAC）。', 'PAC は V と I が基本形で旋律が do。満たさない V–I は不完全全終止（IAC）。', 'PAC: V and I in root position with the melody on do. A V–I that misses this is an imperfect authentic cadence (IAC).') },
      { type: 'choice', ref: 'wiki-dominant-seventh',
        prompt: t('为什么 V7 那么想回到 I？', 'V7 がそんなに I へ帰りたいのはなぜ？', 'Why does V7 want to go to I so much?'),
        options: [t('它的三音和七音构成三全音，很不稳定', '3 度と 7 度が三全音を作り、とても不安定', 'its third and seventh form an unstable tritone'), t('因为它最响', 'いちばん大きいから', 'because it is loudest'), t('因为它最低', 'いちばん低いから', 'because it is lowest')], answer: 0,
        hint: t('里面藏着一个"紧张"的音程。', '「緊張」した音程が隠れています。', 'A tense interval hides inside it.'),
        explain: t('G7 里的 B 和 F 构成三全音，听起来很紧张，于是强烈地推向主和弦。', 'G7 の B と F は三全音で緊張が強く、主和音へ強く進もうとします。', 'In G7, B and F form a tritone; that tension drives strongly toward the tonic.') },
    ],
  },
  {
    id: 'form', section: 'harmony', feature: 'form', icon: '§',
    title: t('乐句与曲式', 'フレーズと楽式', 'Phrases & form'),
    blurb: t('音乐也有"句号"和"段落"', '音楽にも「句点」と「段落」', 'Music has full stops and paragraphs too'),
    cards: [
      { type: 'guide', ref: 'omt2e-phrase-model',
        title: t('句子与标点', '文と句読点', 'Sentences and punctuation'),
        steps: [
          t('一个乐句就像一句话，结尾处的"标点"叫终止式：半终止像逗号或问号，正格终止像句号。', 'フレーズは文のようなもの。終わりの「句読点」が終止：半終止は読点や疑問符、全終止は句点。', 'A phrase is like a sentence; its punctuation is the cadence — a half cadence is a comma or question mark, an authentic cadence a full stop.'),
          t('很多乐曲会让主要的段落 A 反复回来，中间穿插别的段落。', '多くの曲では主要部分 A が何度も戻り、その間に別の部分が入ります。', 'Many pieces keep bringing back a main section A with other sections in between.'),
        ] },
      { type: 'choice', ref: 'omt-rondo',
        prompt: t('回旋曲式（Rondo）的样子是？', 'ロンド形式の形は？', 'What does a rondo look like?'),
        options: ['A B A C A', 'A B', 'A A A'], answer: 0,
        hint: t('主题一次又一次地"回旋"回来。', '主題が何度も「回って」戻ってきます。', 'The theme keeps coming back around.'),
        explain: t('五部回旋是 A B A C A：A 每次都回来，中间换不同的插部。', '5 部ロンドは A B A C A。A が毎回戻り、間に違う挿入部が入ります。', 'A five-part rondo is A B A C A: A returns each time with different episodes between.') },
      { type: 'fill', ref: 'omt-rondo',
        prompt: t('七部回旋：A B A C A ___ A', '7 部ロンド：A B A C A ___ A', 'Seven-part rondo: A B A C A ___ A'),
        bank: [opt('B', 'B'), opt('C', 'C'), opt('D', 'D')], answer: ['B'],
        hint: t('前半段的插部又出现了一次。', '前半の挿入部がもう一度。', 'An earlier episode returns.'),
        explain: t('七部回旋是 A B A C A B A。', '7 部ロンドは A B A C A B A。', 'A seven-part rondo is A B A C A B A.') },
      { type: 'choice', ref: 'omt2e-phrase-model',
        prompt: t('乐句模型 T–PD–D–T 最后通常以什么结束？', 'フレーズモデル T–PD–D–T はふつう何で終わる？', 'The phrase model T–PD–D–T usually ends with…'),
        options: [t('终止式', '終止', 'a cadence'), t('转调', '転調', 'a modulation'), t('休止符', '休符', 'a rest')], answer: 0,
        hint: t('就是句子的"标点"。', '文の「句読点」です。', 'The sentence’s punctuation.'),
        explain: t('乐句以终止式结束——半终止或正格终止。', 'フレーズは終止で終わります（半終止か全終止）。', 'A phrase ends with a cadence — half or authentic.') },
    ],
  },
  {
    id: 'figured', section: 'harmony', feature: 'figured', icon: '6',
    title: t('数字低音', '数字付き低音', 'Figured bass'),
    blurb: t('低音上方的小数字', 'ベースの上の小さな数字', 'Little numbers above the bass'),
    cards: [
      { type: 'guide', ref: 'omt2e-figured-bass',
        title: t('数字是从低音往上数的', '数字はベースから数える', 'Numbers count up from the bass'),
        steps: [
          t('巴洛克时代的乐谱只写低音，再在上面写数字，告诉演奏者要弹哪些音。', 'バロック時代の楽譜はベースだけを書き、その上の数字で弾く音を示しました。', 'Baroque scores wrote only the bass, with numbers telling players what to add.'),
          t('数字表示"离低音几度"，不是离根音。什么都不写 = 原位；写 6 = 第一转位；写 6/4 = 第二转位。', '数字は「ベースから何度」で、根音からではありません。何もなし = 基本形、6 = 第 1 転回、6/4 = 第 2 転回。', 'Numbers mean intervals above the bass, not the root. Nothing = root position; 6 = first inversion; 6/4 = second inversion.'),
        ] },
      { type: 'match', ref: 'omt2e-figured-bass',
        prompt: t('三和弦的数字 ↔ 位置', '三和音の数字 ↔ 形', 'Triad figures ↔ position'),
        pairs: [[t('不写数字', '数字なし', 'no figure'), t('原位', '基本形', 'root position')], ['6', t('第一转位', '第 1 転回', 'first inversion')], ['6/4', t('第二转位', '第 2 転回', 'second inversion')]],
        hint: t('数字越"奇怪"，低音离根音越远。', '数字が変わるほど、ベースは根音から離れます。', 'The odder the figure, the further the bass is from the root.'),
        explain: t('原位不写数字；第一转位写 6；第二转位写 6/4。', '基本形は数字なし、第 1 転回は 6、第 2 転回は 6/4。', 'Root position has no figure; first inversion 6; second inversion 6/4.') },
      { type: 'match', ref: 'omt2e-figured-bass',
        prompt: t('七和弦的数字 ↔ 位置', '七の和音の数字 ↔ 形', 'Seventh-chord figures ↔ position'),
        pairs: [['7', t('原位', '基本形', 'root position')], ['6/5', t('第一转位', '第 1 転回', 'first inversion')], ['4/3', t('第二转位', '第 2 転回', 'second inversion')], ['4/2', t('第三转位', '第 3 転回', 'third inversion')]],
        hint: t('数字越小，转位越多。', '数字が小さいほど転回が進みます。', 'Smaller numbers, later inversions.'),
        explain: t('七和弦：7、6/5、4/3、4/2 依次是原位到第三转位。', '七の和音：7・6/5・4/3・4/2 が基本形から第 3 転回。', 'Sevenths: 7, 6/5, 4/3, 4/2 run from root position to third inversion.') },
      { type: 'choice', ref: 'omt2e-figured-bass',
        prompt: t('数字是从哪个音开始往上数的？', '数字はどの音から上へ数える？', 'Figures count up from which note?'),
        options: [t('低音', 'ベース', 'the bass'), t('根音', '根音', 'the root'), t('最高的音', 'いちばん高い音', 'the top note')], answer: 0,
        hint: t('名字就叫"数字低音"。', '名前が「数字付き低音」。', 'It is called figured *bass*.'),
        explain: t('永远从低音往上数，这是最容易弄错的地方。', 'いつもベースから数えます。間違えやすいポイント。', 'Always from the bass — the most common mix-up.') },
      { type: 'choice', ref: 'omt2e-figured-bass',
        prompt: t('C 大调里，低音 E 上写 6，是什么和弦？', 'C 長調で、ベース E に 6。何の和音？', 'In C major, bass E with a 6 is…'),
        options: [t('C 大三和弦第一转位', 'C 長三和音の第 1 転回', 'C major in first inversion'), t('E 小三和弦原位', 'E 短三和音の基本形', 'E minor in root position'), t('A 小三和弦', 'A 短三和音', 'A minor')], answer: 0,
        hint: t('6 = 低音上方的六度和三度：E 上面是？', '6 = ベースの上の 6 度と 3 度。E の上は？', '6 = a sixth and a third above the bass: what lies above E?'),
        explain: t('E 上方三度是 G、六度是 C：E G C，就是低音在三音上的 C 和弦（第一转位）。', 'E の上の 3 度は G、6 度は C：E G C は C の和音の第 1 転回。', 'A third above E is G, a sixth is C: E G C is a C chord with its third in the bass.') },
    ],
  },
  {
    id: 'inversions', section: 'harmony', feature: 'chord', icon: 'C/E',
    title: t('转位：谁站在最下面', '転回形：いちばん下にいるのは誰？', 'Inversions: who is at the bottom?'),
    blurb: t('原位、第一转位、第二转位与斜杠和弦', '基本形・第 1 転回形・第 2 転回形と分数コード', 'Root position, first and second inversion, slash chords'),
    cards: [
      { type: 'guide', ref: ['omt2e-figured-bass', 'wiki-chord-notation'], demo: { play: [[48, 52, 55], [52, 55, 60], [55, 60, 64]] },
        title: t('同一个和弦，换一个低音', '同じコードで低音を変える', 'Same chord, different bass'),
        steps: [
          t('和弦里最低的那个音（低音）决定它是哪种"转位"。', 'コードのいちばん低い音（ベース）で転回形が決まります。', 'The lowest note of a chord — the bass — decides its inversion.'),
          t('根音在最低 = 原位；三音在最低 = 第一转位；五音在最低 = 第二转位；七和弦的七音在最低 = 第三转位。听：C 和弦的原位、第一转位、第二转位。', '根音が最低 = 基本形、第 3 音 = 第 1 転回形、第 5 音 = 第 2 転回形、七の和音の第 7 音 = 第 3 転回形。聴いて：C の基本形・第 1・第 2 転回形。', 'Root at the bottom = root position; third = first inversion; fifth = second inversion; a seventh chord’s seventh = third inversion. Listen: C in root position, first and second inversion.'),
          t('转位不改变和弦"是谁"，只换了最下面的音。和弦标记里用斜杠写出低音：C/E 就是 C 和弦、E 在最低。', '転回しても「何のコードか」は変わらず、いちばん下が変わるだけ。コード記号ではスラッシュでベースを書きます：C/E は C のコードで E が最低音。', 'Inverting doesn’t change which chord it is, only the bottom note. Chord symbols show the bass after a slash: C/E is a C chord with E at the bottom.'),
          t('数字低音里：第一转位记作 6，第二转位记作 6/4。', '数字付き低音では第 1 転回形が 6、第 2 転回形が 6/4。', 'In figured bass, first inversion is 6 and second inversion is 6/4.'),
        ] },
      { type: 'choice', ref: 'omt2e-figured-bass', audio: { notes: [52, 55, 60], mode: 'harmonic' },
        prompt: t('C 和弦（C E G），E 在最低，是哪种？', 'C のコード（C E G）で E が最低音なら？', 'A C chord (C E G) with E at the bottom is…'),
        options: [t('第一转位', '第 1 転回形', 'first inversion'), t('原位', '基本形', 'root position'), t('第二转位', '第 2 転回形', 'second inversion')], answer: 0,
        hint: t('E 是 C 和弦的三音。', 'E は C のコードの第 3 音。', 'E is the third of a C chord.'),
        explain: t('三音在低音 = 第一转位。', '第 3 音がベース = 第 1 転回形。', 'Third in the bass = first inversion.') },
      { type: 'match', ref: 'omt2e-figured-bass',
        prompt: t('C 和弦：最低音 ↔ 转位', 'C のコード：最低音 ↔ 転回形', 'C chord: lowest note ↔ inversion'),
        pairs: [['C', t('原位', '基本形', 'root position')], ['E', t('第一转位', '第 1 転回形', 'first inversion')], ['G', t('第二转位', '第 2 転回形', 'second inversion')]],
        hint: t('根音、三音、五音依次在下。', '根音・第 3 音・第 5 音の順。', 'Root, third, fifth in turn.'),
        explain: t('C（根音）原位，E（三音）第一转位，G（五音）第二转位。', 'C（根音）基本形、E（第 3 音）第 1、G（第 5 音）第 2 転回形。', 'C (root) root position, E (third) first inversion, G (fifth) second inversion.') },
      { type: 'choice', ref: 'omt2e-figured-bass',
        prompt: t('G7（G B D F）的第三转位，最低音是？', 'G7（G B D F）の第 3 転回形の最低音は？', 'G7 (G B D F) in third inversion has which bass note?'),
        options: ['F', 'D', 'B'], answer: 0,
        hint: t('第三转位 = 七音在最低。', '第 3 転回形 = 第 7 音が最低。', 'Third inversion = the seventh in the bass.'),
        explain: t('G7 的七音是 F，所以第三转位 F 在最低。', 'G7 の第 7 音は F なので F が最低音。', 'G7’s seventh is F, so F is in the bass.') },
      { type: 'choice', ref: 'wiki-chord-notation',
        prompt: t('C/G 是哪种转位？', 'C/G はどの転回形？', 'C/G is which inversion?'),
        options: [t('第二转位', '第 2 転回形', 'second inversion'), t('第一转位', '第 1 転回形', 'first inversion'), t('G 和弦', 'G のコード', 'a G chord')], answer: 0,
        hint: t('斜杠前是和弦，斜杠后是低音。', 'スラッシュの前がコード、後ろがベース。', 'Before the slash is the chord; after it, the bass.'),
        explain: t('C 和弦、G（五音）在最低 = 第二转位。', 'C のコードで G（第 5 音）が最低 = 第 2 転回形。', 'A C chord with G (the fifth) in the bass = second inversion.') },
      { type: 'fill', ref: 'omt2e-figured-bass',
        prompt: t('数字低音：三和弦第一转位写 ___，第二转位写 ___', '数字付き低音：三和音の第 1 転回形は ___、第 2 転回形は ___', 'Figured bass: a triad’s first inversion is ___, second inversion ___'),
        bank: [opt('6', '6'), opt('64', '6/4'), opt('7', '7'), opt('43', '4/3')], answer: ['6', '64'],
        hint: t('数字是从低音往上数的音程。', '数字はベースから上への音程。', 'The figures are intervals counted up from the bass.'),
        explain: t('E–G–C：从 E 往上有三度和六度，简写为 6；G–C–E：有四度和六度，写 6/4。', 'E–G–C は 3 度と 6 度で 6、G–C–E は 4 度と 6 度で 6/4。', 'E–G–C has a third and a sixth, shortened to 6; G–C–E has a fourth and a sixth: 6/4.') },
    ],
  },
  {
    id: 'voicing', section: 'harmony', feature: 'chord', icon: '⋮',
    title: t('紧密排列与开放排列', '密集配置と開離配置', 'Close and open position'),
    blurb: t('同一个和弦怎么排：紧凑还是拉开；四部和声的间距与重复', '同じコードを詰めるか広げるか、四声体の間隔と重複', 'Packing a chord tightly or spreading it out; spacing and doubling in four parts'),
    cards: [
      { type: 'guide', ref: ['wiki-voicing', 'omt2e-roman-numerals'], demo: { play: [[60, 64, 67], [48, 55, 64], [48, 55, 64, 67]] },
        title: t('音还是那几个，排法不一样', '音は同じ、並べ方が違う', 'Same notes, different arrangement'),
        steps: [
          t('同一个和弦，可以把音排得很紧，也可以拉得很开——这叫"配置"或"排列"。', '同じコードでも、音を詰めたり広げたりできます。これを「配置（ヴォイシング）」と呼びます。', 'One chord can be packed tight or spread wide — that is its voicing.'),
          t('最紧凑的排法叫"紧密排列"（密集排列），例如 C4 E4 G4；把音拉开、间隔更宽的叫"开放排列"，例如 C3 G3 E4。听：先紧密，再开放——都还是 C 大三和弦原位。', 'いちばん詰めた並べ方が「密集配置」（例 C4 E4 G4）、間を広げたのが「開離配置」（例 C3 G3 E4）。聴いて：密集 → 開離。どちらも C の基本形です。', 'The most compact arrangement is close position (e.g. C4 E4 G4); spreading the notes wider is open position (e.g. C3 G3 E4). Listen: close, then open — both are still C major in root position.'),
          t('同一个音可以在不同八度里出现两次，这叫"重复"（第三个例子里 G 出现了两次）。', '同じ音を別のオクターヴで 2 回使うことを「重複」と呼びます（3 つ目の例では G が 2 回）。', 'A note can appear in two octaves at once — that is doubling (the third example doubles G).'),
          t('四部和声（女高、女中、男高、男低）有间距规则：相邻的上方声部之间不超过八度，男高和男低之间不超过十二度；声部不能交叉。', '四声体（ソプラノ・アルト・テノール・バス）の間隔：隣り合う上 3 声の間はオクターヴ以内、テノールとバスは 12 度以内。声部は交差させない。', 'In four-part writing (soprano, alto, tenor, bass): adjacent upper voices stay within an octave, tenor and bass within a twelfth, and voices don’t cross.'),
        ] },
      { type: 'choice', ref: 'wiki-voicing', audio: { notes: [60, 64, 67], mode: 'harmonic' },
        prompt: t('听：C4 E4 G4，这是？', '聴いて：C4 E4 G4 は？', 'Listen: C4 E4 G4 is…'),
        options: [t('紧密排列', '密集配置', 'close position'), t('开放排列', '開離配置', 'open position')], answer: 0,
        hint: t('三个音挤在不到一个八度里。', '3 音がオクターヴ未満に収まっている。', 'All three notes fit inside less than an octave.'),
        explain: t('音和音之间没有空出可以再放和弦音的位置，是最紧凑的排法：紧密排列。', '間にほかのコード音を入れる余地がない最も詰めた形：密集配置。', 'No room left between the notes for another chord tone — the most compact arrangement: close position.') },
      { type: 'choice', ref: 'wiki-voicing', audio: { notes: [48, 55, 64], mode: 'harmonic' },
        prompt: t('听：C3 G3 E4，这是？', '聴いて：C3 G3 E4 は？', 'Listen: C3 G3 E4 is…'),
        options: [t('开放排列', '開離配置', 'open position'), t('紧密排列', '密集配置', 'close position'), t('另一个和弦', '別のコード', 'a different chord')], answer: 0,
        hint: t('C3 和 G3 之间本可以塞进一个 E。', 'C3 と G3 の間に E を入れられる。', 'There’s room for an E between C3 and G3.'),
        explain: t('还是 C、E、G 三个音，只是拉开了：开放排列。', '音は C・E・G のまま、広げただけ：開離配置。', 'Still C, E and G — just spread out: open position.') },
      { type: 'choice', ref: 'wiki-voicing',
        prompt: t('把紧密排列改成开放排列，和弦的名字会变吗？', '密集を開離に変えると、コード名は変わる？', 'Does changing close position to open position change the chord’s name?'),
        options: [t('不变，只是排法不同', '変わらない。並べ方だけ', 'No — only the arrangement changes'), t('会变成另一个和弦', '別のコードになる', 'Yes, it becomes another chord')], answer: 0,
        hint: t('音名没有变，最低音也没变。', '音名もベースも変わっていない。', 'Same note names, same bass.'),
        explain: t('紧密和开放只是"摆法"，和弦和转位都不变；只有最低音换了，转位才会变。', '密集・開離は並べ方だけ。コードも転回形も同じで、ベースが変わったときだけ転回形が変わります。', 'Close and open are just layouts; chord and inversion stay the same. Only a new bass note changes the inversion.') },
      { type: 'match', ref: 'omt2e-roman-numerals',
        prompt: t('四部和声的常用音域', '四声体の音域', 'Usual ranges in four-part writing'),
        pairs: [[t('女高音', 'ソプラノ', 'soprano'), 'C4–G5'], [t('女中音', 'アルト', 'alto'), 'G3–D5'], [t('男高音', 'テノール', 'tenor'), 'C3–G4'], [t('男低音', 'バス', 'bass'), 'F2–D4']],
        hint: t('男低音最低，下到 F2。', 'バスがいちばん低く F2 まで。', 'The bass goes lowest, down to F2.'),
        explain: t('女高 C4–G5，女中 G3–D5，男高 C3–G4，男低 F2–D4。', 'ソプラノ C4–G5、アルト G3–D5、テノール C3–G4、バス F2–D4。', 'Soprano C4–G5, alto G3–D5, tenor C3–G4, bass F2–D4.') },
      { type: 'choice', ref: 'omt2e-roman-numerals',
        prompt: t('四部和声里，男高音和男低音之间最多可以隔多远？', '四声体でテノールとバスの間は最大どれくらい？', 'In four-part writing, how far apart may tenor and bass be?'),
        options: [t('十二度', '12 度', 'a twelfth'), t('八度', 'オクターヴ', 'an octave'), t('没有限制', '制限なし', 'no limit')], answer: 0,
        hint: t('上方三个声部之间是八度，最下面可以宽一点。', '上 3 声の間はオクターヴ、いちばん下は少し広くてよい。', 'The upper voices stay within an octave; the bottom gap may be wider.'),
        explain: t('S–A、A–T 不超过八度；T–B 可以到十二度。最常见的错误出在女中音和男高音之间，因为它们写在不同的谱表上。', 'S–A、A–T はオクターヴ以内、T–B は 12 度まで。よくある誤りはアルトとテノールの間（別の譜表に書くため）。', 'S–A and A–T within an octave; T–B up to a twelfth. The usual slip is alto–tenor, because they sit on different staves.') },
      { type: 'choice', ref: 'omt2e-roman-numerals',
        prompt: t('四部写三和弦，多出来的一个声部通常重复哪个音？', '三和音を四声で書くとき、余る 1 声はふつう何を重複する？', 'Writing a triad in four parts, which note is usually doubled?'),
        options: [t('低音上的那个音', 'ベースの音', 'the bass note'), t('导音', '導音', 'the leading tone'), t('随便哪个都行', 'どれでもよい', 'any note at all')], answer: 0,
        hint: t('导音永远不重复。', '導音は決して重複しない。', 'The leading tone is never doubled.'),
        explain: t('三和弦通常在上方声部重复低音；导音和和弦七音这类"倾向音"不重复。七和弦有四个音，正好一人一个，不用重复。', '三和音はふつうベースの音を重複。導音や第 7 音のような傾向音は重複しません。七の和音は 4 音なので重複不要。', 'Triads usually double the bass note; tendency tones like the leading tone or a chordal seventh are never doubled. Seventh chords have four notes — one per voice.') },
      { type: 'choice', ref: 'omt2e-jazz-voicings',
        prompt: t('爵士钢琴配置：低音区的音该怎么排？', 'ジャズ・ピアノの配置：低音域はどう並べる？', 'Jazz voicing: how should notes be spaced in the low register?'),
        options: [t('间隔宽一些', '広い間隔で', 'with wide intervals'), t('挤得越紧越好', 'できるだけ詰める', 'packed as tightly as possible')], answer: 0,
        hint: t('模仿泛音列：下面宽、上面窄。', '倍音列をまねる：下は広く、上は狭く。', 'Imitate the harmonic series: wide below, close above.'),
        explain: t('低音区用宽音程、高音区用窄音程，听起来最清楚；延伸音放在上面的声部。', '低音域は広い音程、高音域は狭い音程にすると明瞭に響きます。テンションは上の声部に。', 'Wide intervals low and close intervals high sound clearest; put extensions in the upper voices.') },
    ],
  },
  {
    id: 'chordplus', section: 'harmony', feature: 'chordsymbols', icon: 'sus',
    title: t('sus、add、6 与强力和弦', 'sus・add・6・パワーコード', 'sus, add, sixth and power chords'),
    blurb: t('换掉三音、加一个音、只留根音和五音', '3 度を入れ替える・音を足す・根音と 5 度だけ', 'Swap the third, add a note, or keep only root and fifth'),
    cards: [
      { type: 'guide', ref: ['wiki-suspended-chord', 'wiki-added-tone', 'wiki-power-chord', 'wiki-sixth-chord'], demo: { play: [[60, 64, 67], [60, 65, 67], [60, 62, 67], [48, 55, 60]] },
        title: t('在三和弦上动一点手脚', '三和音にちょっと手を加える', 'Small changes to a triad'),
        steps: [
          t('sus（挂留）和弦把三音换掉：Csus4 = C F G（用四度代替三度），Csus2 = C D G（用二度代替）。没有三音，听起来"悬着"、分不出大小调。', 'sus コードは 3 度を入れ替えます：Csus4 = C F G、Csus2 = C D G。3 度がないので宙に浮いたように聞こえ、長短がわかりません。', 'A sus chord replaces the third: Csus4 = C F G (a fourth instead), Csus2 = C D G (a second instead). With no third it sounds suspended and neither major nor minor.'),
          t('add 和弦是三和弦再加一个音，而且不带七音：Cadd9 = C E G + D。', 'add コードは三和音に 1 音を足したもので、7 度は含みません：Cadd9 = C E G + D。', 'An add chord is a triad plus one extra note, with no seventh: Cadd9 = C E G + D.'),
          t('六和弦是三和弦再加根音上方的六度：C6 = C E G A。', 'シックス・コードは三和音に根音から 6 度上を足したもの：C6 = C E G A。', 'A sixth chord adds the sixth above the root: C6 = C E G A.'),
          t('强力和弦（写作 C5）只有根音和五音（可以再加八度），电吉他加失真时特别干净有力。听：C、Csus4、Csus2、C5。', 'パワーコード（C5）は根音と 5 度だけ（オクターヴを足すことも）。歪ませたエレキギターでもすっきり力強く響きます。聴いて：C、Csus4、Csus2、C5。', 'A power chord (C5) is just root and fifth (plus octaves), which stays clean and punchy through distortion. Listen: C, Csus4, Csus2, C5.'),
        ] },
      { type: 'match', ref: ['wiki-suspended-chord', 'wiki-added-tone', 'wiki-power-chord', 'wiki-sixth-chord'],
        prompt: t('和弦标记 ↔ 组成音', 'コード記号 ↔ 構成音', 'Symbol ↔ notes'),
        pairs: [['Csus4', 'C F G'], ['Cadd9', 'C E G D'], ['C6', 'C E G A'], ['C5', 'C G']],
        hint: t('sus 没有 E；5 只有两个音。', 'sus には E がない。5 は 2 音だけ。', 'sus has no E; 5 has only two notes.'),
        explain: t('sus4 用 F 换掉 E；add9 加 D；6 加 A；5 只留根音和五音。', 'sus4 は E の代わりに F、add9 は D を足す、6 は A を足す、5 は根音と 5 度だけ。', 'sus4 swaps E for F; add9 adds D; 6 adds A; 5 keeps only root and fifth.') },
      { type: 'choice', ref: 'wiki-suspended-chord', audio: { notes: [60, 65, 67], mode: 'harmonic' },
        prompt: t('为什么 sus 和弦听起来分不出大调小调？', 'sus コードはなぜ長短がわからない？', 'Why does a sus chord sound neither major nor minor?'),
        options: [t('因为没有三音', '3 度がないから', 'It has no third'), t('因为没有根音', '根音がないから', 'It has no root'), t('因为有七音', '7 度があるから', 'It has a seventh')], answer: 0,
        hint: t('决定大小的是哪个音？', '長短を決めるのはどの音？', 'Which note decides major or minor?'),
        explain: t('大三度还是小三度决定大小调色彩；sus 把三音换成四度或二度，所以"悬着"。', '長 3 度か短 3 度かで長短が決まります。sus は 3 度を 4 度や 2 度に替えるので宙に浮く。', 'Major or minor third decides the colour; sus replaces the third with a fourth or second, so it hangs in the air.') },
      { type: 'choice', ref: 'wiki-added-tone',
        prompt: t('Cadd9 和 C9 有什么不同？', 'Cadd9 と C9 の違いは？', 'How does Cadd9 differ from C9?'),
        options: [t('Cadd9 没有七音', 'Cadd9 には 7 度がない', 'Cadd9 has no seventh'), t('Cadd9 没有三音', 'Cadd9 には 3 度がない', 'Cadd9 has no third'), t('完全一样', 'まったく同じ', 'They are identical')], answer: 0,
        hint: t('"加音"指的是七音以外加进来的音。', '「付加音」は 7 度以外に足される音。', '“Added” means a note other than a seventh.'),
        explain: t('add9 = 三和弦 + 9，不经过七音；C9 = C E G B♭ D，包含七音。', 'add9 = 三和音 + 9 で 7 度を含まない。C9 = C E G B♭ D は 7 度を含む。', 'add9 = triad + 9 with no seventh; C9 = C E G B♭ D includes the seventh.') },
      { type: 'fill', ref: 'wiki-power-chord',
        prompt: t('强力和弦 G5 由根音 ___ 和五音 ___ 组成', 'パワーコード G5 は根音 ___ と 5 度 ___', 'The power chord G5 is root ___ plus fifth ___'),
        bank: [opt('G', 'G'), opt('D', 'D'), opt('B', 'B'), opt('C', 'C')], answer: ['G', 'D'],
        hint: t('G 往上数五个字母。', 'G から 5 文字数える。', 'Count five letters up from G.'),
        explain: t('G A B C D：五音是 D。没有三音 B，所以也不分大小。', 'G A B C D で 5 度は D。3 度の B がないので長短なし。', 'G A B C D: the fifth is D. No third (B), so neither major nor minor.') },
      { type: 'choice', ref: 'wiki-sixth-chord',
        prompt: t('C6 里加进来的是哪个音？', 'C6 で足されるのは？', 'Which note is added in C6?'),
        options: ['A', 'B♭', 'D'], answer: 0,
        hint: t('从 C 往上数六度。', 'C から 6 度上。', 'A sixth above C.'),
        explain: t('C D E F G A：六度是 A，所以 C6 = C E G A。', 'C D E F G A で 6 度は A。C6 = C E G A。', 'C D E F G A: the sixth is A, so C6 = C E G A.') },
    ],
  },
  {
    id: 'roman', section: 'harmony', feature: 'classical', icon: 'IV',
    // 五度圈上可以把调里各级和弦（罗马数字）标出来，方便看主、下属、属的位置
    extraTools: [{ feature: 'circle' }],
    title: t('罗马数字：给和弦编号', 'ローマ数字：和音に番号をつける', 'Roman numerals: numbering the chords'),
    blurb: t('大写、小写、°；大调和小调里每级和弦的性质', '大文字・小文字・°、長調と短調の各和音の種類', 'Upper case, lower case and °; chord qualities in major and minor'),
    cards: [
      { type: 'guide', ref: 'omt2e-roman-numerals', demo: { play: [[60, 64, 67], [62, 65, 69], [64, 67, 71], [65, 69, 72], [67, 71, 74], [69, 72, 76], [71, 74, 77]] },
        title: t('换调也不用重新记', '調が変わっても覚え直さなくていい', 'Change key without relearning'),
        steps: [
          t('罗马数字说的是"和弦的根音是音阶里的第几个音"：在 C 大调里，C 上的和弦是 I，D 上的是 ii……', 'ローマ数字は「根音が音階の何番目か」を表します。C 長調なら C の和音が I、D の和音が ii……', 'A Roman numeral tells which scale degree the chord’s root is: in C major the chord on C is I, on D is ii…'),
          t('大写 = 大三和弦，小写 = 小三和弦，小写加 ° = 减三和弦，大写加 + = 增三和弦。', '大文字 = 長三和音、小文字 = 短三和音、小文字 + ° = 減三和音、大文字 + + = 増三和音。', 'Upper case = major, lower case = minor, lower case with ° = diminished, upper case with + = augmented.'),
          t('大调里：I、ii、iii、IV、V、vi、vii°——每个大调都一样。听：C 大调从 I 到 vii°。', '長調では I・ii・iii・IV・V・vi・vii°。どの長調でも同じ。聴いて：C 長調の I から vii° まで。', 'In any major key: I, ii, iii, IV, V, vi, vii°. Listen: C major from I to vii°.'),
          t('小调里：i、ii°、III、iv、v、VI、VII；如果把导音升高，v 会变成 V、VII 会变成 vii°。', '短調では i・ii°・III・iv・v・VI・VII。導音を上げると v が V に、VII が vii° になります。', 'In minor: i, ii°, III, iv, v, VI, VII — raise the leading tone and v becomes V, VII becomes vii°.'),
        ] },
      { type: 'fill', ref: 'omt2e-roman-numerals',
        prompt: t('大调：I ii iii ___ V vi ___', '長調：I ii iii ___ V vi ___', 'Major: I ii iii ___ V vi ___'),
        bank: [opt('IV', 'IV'), opt('iv', 'iv'), opt('viio', 'vii°'), opt('VII', 'VII')], answer: ['IV', 'viio'],
        hint: t('C 大调里 F 和弦是大三和弦，B 和弦是减三和弦。', 'C 長調で F の和音は長三和音、B の和音は減三和音。', 'In C major the F chord is major and the B chord is diminished.'),
        explain: t('IV 是大三和弦（大写），vii° 是减三和弦（小写加 °）。', 'IV は長三和音（大文字）、vii° は減三和音（小文字 + °）。', 'IV is major (upper case); vii° is diminished (lower case plus °).') },
      { type: 'choice', ref: 'omt2e-roman-numerals',
        prompt: t('在 C 大调里，vi 是哪个和弦？', 'C 長調の vi は？', 'In C major, vi is…'),
        options: [t('A 小三和弦', 'A の短三和音', 'A minor'), t('A 大三和弦', 'A の長三和音', 'A major'), t('F 大三和弦', 'F の長三和音', 'F major')], answer: 0,
        hint: t('第 6 个音是 A；小写 = 小三和弦。', '第 6 音は A、小文字 = 短三和音。', 'The 6th note is A; lower case = minor.'),
        explain: t('C D E F G A——第 6 个音 A，小写 vi 表示小三和弦：A C E。', 'C D E F G A の 6 番目が A、小文字 vi なので短三和音 A C E。', 'The 6th note is A; lower-case vi means minor: A C E.') },
      { type: 'match', ref: 'omt2e-roman-numerals',
        prompt: t('写法 ↔ 和弦性质', '書き方 ↔ 和音の種類', 'Notation ↔ chord quality'),
        pairs: [['V', t('大三和弦', '長三和音', 'major')], ['ii', t('小三和弦', '短三和音', 'minor')], ['vii°', t('减三和弦', '減三和音', 'diminished')], ['III+', t('增三和弦', '増三和音', 'augmented')]],
        hint: t('看大小写，再看后面的小符号。', '大文字か小文字か、そして後ろの記号。', 'Check the case, then any symbol after it.'),
        explain: t('大写大三，小写小三，° 减，+ 增。', '大文字 = 長、小文字 = 短、° = 減、+ = 増。', 'Upper = major, lower = minor, ° = diminished, + = augmented.') },
      { type: 'choice', ref: 'omt2e-roman-numerals',
        prompt: t('A 小调里把导音 G 升成 G♯，五级和弦怎么写？', 'A 短調で導音 G を G♯ にすると、V 度の和音は？', 'In A minor, raising G to G♯ makes the fifth-degree chord…'),
        options: [t('V（大三和弦 E G♯ B）', 'V（長三和音 E G♯ B）', 'V (major: E G♯ B)'), t('v（小三和弦 E G B）', 'v（短三和音 E G B）', 'v (minor: E G B)')], answer: 0,
        hint: t('三音 G 变成了 G♯。', '第 3 音 G が G♯ に。', 'Its third G becomes G♯.'),
        explain: t('E G B 是小三和弦 v；升高导音后 E G♯ B 是大三和弦，写成大写 V。', 'E G B は短三和音 v、導音を上げた E G♯ B は長三和音なので大文字 V。', 'E G B is minor (v); with the raised leading tone, E G♯ B is major: V.') },
      { type: 'choice', ref: 'omt2e-roman-numerals',
        prompt: t('大调里的七和弦：V7 是哪一种？', '長調の七の和音：V7 はどれ？', 'Seventh chords in major: V7 is a…'),
        options: [t('属七和弦（大小七）', '属七（長短七）', 'dominant seventh (major-minor)'), t('大七和弦', '長七', 'major seventh'), t('半减七和弦', '半減七', 'half-diminished seventh')], answer: 0,
        hint: t('C 大调的 V7 = G B D F。', 'C 長調の V7 = G B D F。', 'In C major V7 = G B D F.'),
        explain: t('大三和弦 + 小七度 = 属七。大调里 I7、IV7 是大七，vii 是半减七（vii∅7）。', '長三和音 + 短 7 度 = 属七。長調の I7・IV7 は長七、vii は半減七（vii∅7）。', 'Major triad + minor seventh = dominant seventh. In major, I7 and IV7 are major sevenths and vii is half-diminished (vii∅7).') },
    ],
  },
  {
    id: 'cadences', section: 'harmony', feature: 'progression', icon: '.',
    // 五度圈上可以把调里各级和弦（罗马数字）标出来
    extraTools: [{ feature: 'circle' }],
    title: t('终止式：音乐的标点', '終止形：音楽の句読点', 'Cadences: musical punctuation'),
    blurb: t('完全正格、不完全正格、半终止、变格、阻碍终止', '完全終止・不完全終止・半終止・変格終止・偽終止', 'Perfect and imperfect authentic, half, plagal and deceptive'),
    cards: [
      { type: 'guide', ref: ['omt2e-cadences', 'musictheory-net-cadences', 'omt2e-la-bass'], demo: { play: [[43, 59, 62, 67], [48, 55, 64, 72]] },
        title: t('句号、逗号和"出乎意料"', '句点・読点・「意外」', 'Full stop, comma and surprise'),
        steps: [
          t('乐句的结尾叫终止式，就像句子的标点。', 'フレーズの終わりを終止形と呼び、文の句読点にあたります。', 'The ending of a phrase is a cadence — punctuation for music.'),
          t('正格终止 V–I：如果两个和弦都是原位、最高声部落在主音 do 上，就是"完全正格终止"，像句号；否则是"不完全正格终止"。听：V–I。', '正格終止 V–I：両方基本形で最上声が主音 do に着けば「完全正格終止」（句点）、そうでなければ「不完全」。聴いて：V–I。', 'Authentic cadence V–I: both chords in root position with do on top makes a perfect authentic cadence (a full stop); otherwise it is imperfect. Listen: V–I.'),
          t('半终止停在 V 上，像逗号或问号，等着下文。', '半終止は V で止まり、読点や疑問符のように続きを待ちます。', 'A half cadence stops on V — a comma or question mark, waiting for more.'),
          t('变格终止 IV–I（"阿们"终止）；阻碍终止是 V 之后不去 I、跑到 vi，出乎意料。', '変格終止 IV–I（アーメン終止）。偽終止は V のあと I に行かず vi に進む「意外」な終わり方。', 'Plagal: IV–I (the “Amen” cadence). Deceptive: V goes to vi instead of I — a surprise.'),
        ] },
      { type: 'match', ref: ['omt2e-cadences', 'musictheory-net-cadences'],
        prompt: t('终止式 ↔ 和弦', '終止形 ↔ 和音', 'Cadence ↔ chords'),
        pairs: [[t('正格终止', '正格終止', 'authentic'), 'V – I'], [t('半终止', '半終止', 'half'), '… – V'], [t('变格终止', '変格終止', 'plagal'), 'IV – I'], [t('阻碍终止', '偽終止', 'deceptive'), 'V – vi']],
        hint: t('停在 V 上的是哪一种？', 'V で止まるのはどれ？', 'Which one stops on V?'),
        explain: t('V–I 正格；停在 V 半终止；IV–I 变格；V–vi 阻碍。', 'V–I 正格、V で止まる半終止、IV–I 変格、V–vi 偽終止。', 'V–I authentic; ending on V half; IV–I plagal; V–vi deceptive.') },
      { type: 'choice', ref: 'musictheory-net-cadences', audio: { notes: [[43, 59, 62, 67], [45, 60, 64, 69]], mode: 'chords' },
        prompt: t('听：V 之后没有回到 I，是哪种终止？', '聴いて：V のあと I に戻らない。どの終止？', 'Listen: V does not go home to I. Which cadence?'),
        options: [t('阻碍终止', '偽終止', 'deceptive'), t('完全正格终止', '完全正格終止', 'perfect authentic'), t('变格终止', '変格終止', 'plagal')], answer: 0,
        hint: t('第二个和弦是 A 小三和弦（vi）。', '2 つ目は A の短三和音（vi）。', 'The second chord is A minor (vi).'),
        explain: t('V–vi：耳朵等着回家，却被"骗"到了 vi，所以叫阻碍（欺骗）终止。', 'V–vi：家に帰ると思ったら vi へ。だから偽終止。', 'V–vi: the ear expects home but is “deceived” into vi.') },
      { type: 'choice', ref: 'omt2e-cadences',
        prompt: t('V–I 都是原位，但最高声部停在 mi（E）上，是？', 'V–I が両方基本形だが最上声が mi（E）なら？', 'V–I both in root position, but the top voice ends on mi (E). That is…'),
        options: [t('不完全正格终止', '不完全正格終止', 'an imperfect authentic cadence'), t('完全正格终止', '完全正格終止', 'a perfect authentic cadence'), t('半终止', '半終止', 'a half cadence')], answer: 0,
        hint: t('完全正格终止要求最高声部落在 do。', '完全正格終止は最上声が do。', 'A PAC needs do on top.'),
        explain: t('两个条件少一个就是不完全正格终止：要原位，也要最高声部是 do。', '条件が 1 つ欠ければ不完全：基本形であること、最上声が do であること。', 'Missing either condition makes it imperfect: root position and do on top.') },
      { type: 'choice', ref: 'omt2e-cadences', audio: { notes: [[48, 60, 64, 67], [43, 59, 62, 67]], mode: 'chords' },
        prompt: t('听：停在 V 上就结束了，像个问号。这是？', '聴いて：V で終わり、疑問符のよう。これは？', 'Listen: it stops on V like a question mark. That is…'),
        options: [t('半终止', '半終止', 'a half cadence'), t('正格终止', '正格終止', 'an authentic cadence'), t('阻碍终止', '偽終止', 'a deceptive cadence')], answer: 0,
        hint: t('最后一个和弦是 G（V）。', '最後の和音は G（V）。', 'The last chord is G (V).'),
        explain: t('任何和弦 → V 收尾都是半终止，听起来还没说完。', 'どの和音からでも V で終われば半終止。まだ続きそうに聞こえます。', 'Anything → V at the end is a half cadence — it sounds unfinished.') },
    ],
  },
  {
    id: 'sixfour', section: 'harmony', feature: 'classical', icon: '6/4',
    title: t('四六和弦的四种用法', '四六の和音の 4 つの使い方', 'Four uses of 6/4 chords'),
    blurb: t('终止四六、经过、辅助与琶音四六', '終止・経過・刺繍・分散の四六', 'Cadential, passing, neighbour and arpeggiating 6/4'),
    cards: [
      { type: 'guide', ref: ['omt2e-cad64', 'omt2e-64-chords'], demo: { play: [[43, 60, 64, 72], [43, 59, 62, 71], [36, 55, 64, 72]] },
        title: t('看起来是 I，其实在装饰 V', 'I に見えて、実は V の飾り', 'Looks like I, actually decorates V'),
        steps: [
          t('"四六和弦"是第二转位的三和弦：低音上方有一个四度和一个六度。', '「四六の和音」は第 2 転回形の三和音で、ベースの上に 4 度と 6 度があります。', 'A 6/4 chord is a triad in second inversion: a fourth and a sixth above the bass.'),
          t('终止四六：低音是 sol（C 大调里的 G），上方的 C 和 E 其实是两个装饰音，接着 6 度落到 5 度、4 度落到 3 度，变成 V。听：G 上的 C–E 落到 B–D。', '終止の四六：ベースは sol（C 長調の G）。上の C と E は飾りの音で、6 度 → 5 度、4 度 → 3 度と下がって V になります。聴いて：G の上の C–E が B–D へ。', 'Cadential 6/4: the bass is sol (G in C major); the C and E above are embellishing tones that fall 6 → 5 and 4 → 3 to become V. Listen: C–E over G falls to B–D.'),
          t('所以分析时把终止四六和后面的 V 当成一个整体，它属于"属"的部分。', 'だから分析では終止の四六とそれに続く V をひとまとまりと見なし、属の働きに含めます。', 'So in analysis the cadential 6/4 and its V are labelled as one unit — part of the dominant.'),
          t('另外三种：经过四六（低音是经过音，两边是同功能的和弦）、辅助四六（低音不动，上面两个声部做上邻音，两边都是原位），以及琶音四六（低音在和弦音之间分解）。', 'ほかの 3 つ：経過の四六（ベースが経過音、両側は同じ働きの和音）、刺繍の四六（ベースは動かず上 2 声が上刺繍、両側は基本形）、分散の四六（ベースが和音を分散）。', 'Three more: passing 6/4 (a passing tone in the bass between chords of the same function), neighbour 6/4 (a static bass with upper neighbours above, root position on both sides) and arpeggiating 6/4 (the bass arpeggiates the chord).'),
        ] },
      { type: 'fill', ref: 'omt2e-cad64',
        prompt: t('终止四六解决时：低音上方的 6 度落到 ___ 度，4 度落到 ___ 度', '終止の四六の解決：6 度は ___ 度へ、4 度は ___ 度へ', 'Resolving a cadential 6/4: the sixth falls to a ___, the fourth to a ___'),
        bank: [opt('5', '5'), opt('3', '3'), opt('7', '7'), opt('8', '8')], answer: ['5', '3'],
        hint: t('两个声部都往下走一步。', 'どちらも 1 歩下がる。', 'Both voices step down.'),
        explain: t('6→5、4→3：C 大调里 C→B、E→D，于是 G 上出现 G B D，也就是 V。', '6→5、4→3：C 長調では C→B、E→D で G B D（V）に。', '6→5 and 4→3: in C major C→B and E→D, giving G B D — V.') },
      { type: 'choice', ref: 'omt2e-cad64',
        prompt: t('C 大调的终止四六，低音是哪个音？', 'C 長調の終止の四六のベースは？', 'In C major, the bass of the cadential 6/4 is…'),
        options: ['G', 'C', 'E'], answer: 0,
        hint: t('它的低音就是 V 的根音 sol。', 'ベースは V の根音 sol。', 'Its bass is sol, the root of V.'),
        explain: t('G 上方是 C 和 E（看起来像 C 和弦的第二转位），之后解决到 G 和弦。', 'G の上に C と E（C の第 2 転回形に見える）があり、G の和音へ解決します。', 'C and E sit above G (it looks like C in second inversion), then resolve to G.') },
      { type: 'choice', ref: 'omt2e-cad64',
        prompt: t('分析时，终止四六算哪种功能？', '分析で終止の四六はどの働き？', 'In analysis, the cadential 6/4 belongs to which function?'),
        options: [t('属（装饰后面的 V）', '属（後ろの V を飾る）', 'dominant (it decorates the V)'), t('主', '主', 'tonic'), t('下属', '下属', 'predominant')], answer: 0,
        hint: t('上面的两个音只是装饰音。', '上の 2 音は飾りにすぎない。', 'The two upper notes are just embellishments.'),
        explain: t('它和 V 被当作一个单位标记；任何本来通向 V 的和弦（多半是强下属和弦）都可以通向它。', 'V と一緒にひとまとめに表記します。V に進める和音（多くは強い下属和音）ならどれでも進めます。', 'It is labelled together with V, and any chord that can approach V — usually a strong predominant — can approach it.') },
      { type: 'match', ref: 'omt2e-64-chords',
        prompt: t('四六和弦 ↔ 低音在做什么', '四六の和音 ↔ ベースの動き', '6/4 type ↔ what the bass does'),
        pairs: [[t('经过四六', '経過の四六', 'passing 6/4'), t('低音是经过音', 'ベースが経過音', 'bass is a passing tone')], [t('辅助四六', '刺繍の四六', 'neighbour 6/4'), t('低音保持不动', 'ベースは動かない', 'bass stays put')], [t('琶音四六', '分散の四六', 'arpeggiating 6/4'), t('低音分解和弦', 'ベースが和音を分散', 'bass arpeggiates the chord')]],
        hint: t('名字就说明了低音的动作。', '名前がベースの動きを表している。', 'Each name describes the bass.'),
        explain: t('经过：低音一步步经过；辅助：低音不动、上方做邻音；琶音：低音在和弦音之间跳。', '経過：ベースが順に通過、刺繍：ベース静止で上が刺繍、分散：ベースが和音を分散。', 'Passing: the bass steps through; neighbour: the bass holds while upper voices neighbour; arpeggiating: the bass leaps through chord tones.') },
    ],
  },
  {
    id: 'forms', section: 'harmony', feature: 'form', icon: 'ABA',
    title: t('乐句、乐段与大型曲式', 'フレーズ・楽節と大きな形式', 'Phrases, periods and larger forms'),
    blurb: t('句子式与乐段；二部、三部与奏鸣曲式', '文型と楽節、二部・三部・ソナタ形式', 'Sentence and period; binary, ternary and sonata form'),
    cards: [
      { type: 'guide', ref: ['omt2e-form-concepts', 'omt2e-phrase', 'omt2e-binary', 'omt2e-ternary', 'omt2e-sonata'],
        title: t('从一个小动机，到一整首曲子', '小さな動機から 1 曲全体へ', 'From a tiny motive to a whole piece'),
        steps: [
          t('曲式是一层套一层的：乐曲里有乐章，乐章里有段落，段落里有主题，主题里有乐句……最小的单位是"动机"——短短一小段会反复出现的音乐。', '形式は入れ子です：曲 → 楽章 → 部分 → 主題 → フレーズ……最小単位は「動機」、繰り返し現れる短い断片です。', 'Form is nested: pieces contain movements, movements sections, sections themes, themes phrases… The smallest unit is the motive — a short recurring bit.'),
          t('乐句是一个比较完整的意思，朝着一个目标（通常是终止式）走。"句子式"由呈示和展开两部分组成；"乐段"由前句和后句组成。', 'フレーズはまとまった考えで、目標（ふつう終止形）へ向かいます。「文型」は提示と継続、「楽節」は前楽句と後楽句でできています。', 'A phrase is a fairly complete thought heading for a goal, usually a cadence. A sentence has a presentation and a continuation; a period has an antecedent and a consequent.'),
          t('二部曲式有两个"反复段"，每段通常各反复一次；第二段末尾回到开头材料的叫"再现二部"，否则是"单纯二部"。三部曲式是 A B A：中间的 B 形成对比，常在新的调上。', '二部形式は 2 つの反復部分（それぞれふつう繰り返す）。後半の終わりで冒頭が戻れば「回帰二部」、そうでなければ「単純二部」。三部形式は A B A で、B は対照的、しばしば新しい調。', 'Binary form has two reprises, each usually repeated; if the opening returns at the end of the second it is rounded, otherwise simple. Ternary is A B A, with a contrasting B, often in a new key.'),
          t('奏鸣曲式：呈示部（主部主题、过渡、副部主题、结束部，两个主题在不同的调上）→ 发展部 → 再现部（副部主题回到主调）。前面可以有引子，后面可以有尾声。', 'ソナタ形式：提示部（第 1 主題・推移・第 2 主題・小結尾。2 つの主題は別の調）→ 展開部 → 再現部（第 2 主題は主調に戻る）。序奏やコーダがつくことも。', 'Sonata form: exposition (primary theme, transition, secondary theme, closing — the themes in different keys) → development → recapitulation (the secondary theme back in the home key). An introduction and coda are optional.'),
        ] },
      { type: 'match', ref: 'omt2e-phrase',
        prompt: t('乐句结构 ↔ 组成', 'フレーズの型 ↔ 構成', 'Phrase type ↔ parts'),
        pairs: [[t('句子式', '文型', 'sentence'), t('呈示 + 展开', '提示 + 継続', 'presentation + continuation')], [t('乐段', '楽節', 'period'), t('前句 + 后句', '前楽句 + 後楽句', 'antecedent + consequent')], [t('重复乐句', '反復フレーズ', 'repeated phrase'), t('第二句把第一句写出来重复', '2 つ目が 1 つ目をそのまま繰り返す', 'the second phrase repeats the first')]],
        hint: t('"前句、后句"像一问一答。', '前楽句・後楽句は問いと答え。', 'Antecedent and consequent are question and answer.'),
        explain: t('句子式 = 呈示 + 展开；乐段 = 前句 + 后句；重复乐句 = 原样再来一遍。', '文型 = 提示 + 継続、楽節 = 前楽句 + 後楽句、反復フレーズ = もう一度。', 'Sentence = presentation + continuation; period = antecedent + consequent; repeated phrase = once more.') },
      { type: 'choice', ref: 'omt2e-form-concepts',
        prompt: t('曲式里最小的单位叫什么？', '形式の最小単位は？', 'The smallest unit of form is the…'),
        options: [t('动机', '動機', 'motive'), t('乐句', 'フレーズ', 'phrase'), t('乐章', '楽章', 'movement')], answer: 0,
        hint: t('它很短，而且会反复出现。', '短くて、繰り返し現れる。', 'It is short and keeps coming back.'),
        explain: t('动机是反复出现的小单位，通常比一个"乐思"还短——别把整条旋律当成动机。', '動機は繰り返し現れる小さな単位で、ふつうアイデアより短い。旋律全体を動機と呼ばないこと。', 'A motive is a short recurring unit, usually smaller than an idea — don’t call a whole melody a motive.') },
      { type: 'choice', ref: 'omt2e-binary',
        prompt: t('二部曲式第二段结尾又回到开头的材料，这叫？', '二部形式の後半の終わりに冒頭が戻るのは？', 'If the opening material returns at the end of a binary form’s second reprise, it is…'),
        options: [t('再现二部曲式', '回帰二部形式', 'rounded binary'), t('单纯二部曲式', '単純二部形式', 'simple binary'), t('奏鸣曲式', 'ソナタ形式', 'sonata form')], answer: 0,
        hint: t('"再现"= 回来。', '「回帰」= 戻ってくる。', '“Rounded” = it comes back around.'),
        explain: t('二部曲式分单纯和再现两种；开头材料在结尾回来就是再现二部。', '二部形式には単純と回帰の 2 種類。冒頭が最後に戻れば回帰二部。', 'Binary form is simple or rounded; the opening returning at the end makes it rounded.') },
      { type: 'fill', ref: 'omt2e-ternary',
        prompt: t('三部曲式：A ___ A', '三部形式：A ___ A', 'Ternary form: A ___ A'),
        bank: [opt('B', 'B'), opt('A', 'A'), opt('C', 'C')], answer: ['B'],
        hint: t('中间是一段对比。', '真ん中は対照部分。', 'The middle contrasts.'),
        explain: t('A B A：中间的 B 对比鲜明，常在新调上，之后回到 A。（A B C 每段都不同，一般叫通谱体。）', 'A B A：B は対照的でしばしば新しい調、その後 A に戻ります。（A B C は通作形式と呼ばれることが多い。）', 'A B A: the contrasting B, often in a new key, then A returns. (A B C, all different, is usually called through-composed.)') },
      { type: 'choice', ref: 'omt2e-sonata',
        prompt: t('奏鸣曲式的再现部里，副部主题在哪个调上？', 'ソナタ形式の再現部で、第 2 主題はどの調？', 'In a sonata recapitulation, the secondary theme is in…'),
        options: [t('主调', '主調', 'the home key'), t('和呈示部一样的新调', '提示部と同じ新しい調', 'the same new key as the exposition'), t('随便哪个调', 'どの調でも', 'any key')], answer: 0,
        hint: t('呈示部里两个主题在不同的调上，再现部要"回家"。', '提示部では 2 つの主題が別の調、再現部では「帰宅」する。', 'The exposition puts the themes in different keys; the recapitulation goes home.'),
        explain: t('再现部把副部主题移回主调，整首曲子才稳稳地结束。', '再現部では第 2 主題を主調に戻し、曲全体が落ち着いて終わります。', 'The recapitulation brings the secondary theme into the home key so the whole piece can close.') },
      { type: 'match', ref: 'omt2e-sonata',
        prompt: t('奏鸣曲式的顺序', 'ソナタ形式の順序', 'The order of sonata form'),
        pairs: [[t('第 1 部分', '第 1 部', 'part 1'), t('呈示部', '提示部', 'exposition')], [t('第 2 部分', '第 2 部', 'part 2'), t('发展部', '展開部', 'development')], [t('第 3 部分', '第 3 部', 'part 3'), t('再现部', '再現部', 'recapitulation')]],
        hint: t('先摆出主题，再把它们打散，最后再回来。', 'まず主題を示し、ばらばらにして、最後に戻る。', 'Present the themes, take them apart, then bring them back.'),
        explain: t('呈示 → 发展 → 再现；第一个反复段是呈示部，第二个包括发展部和再现部。', '提示 → 展開 → 再現。最初の反復部分が提示部、2 つ目に展開部と再現部が入ります。', 'Exposition → development → recapitulation; the first reprise is the exposition, the second holds development and recapitulation.') },
    ],
  },
  {
    id: 'tonicization', section: 'harmony', feature: 'classical', icon: 'V/V',
    title: t('离调与转调', '一時的転調と転調', 'Tonicization and modulation'),
    blurb: t('副属和弦 V/x、直接转调与共同和弦转调', '副属和音 V/x、直接転調と共通和音転調', 'Applied chords V/x, direct and pivot-chord modulation'),
    cards: [
      { type: 'guide', ref: ['omt2e-tonicization', 'omt2e-modulation'], demo: { play: [[48, 60, 64, 67], [50, 62, 66, 69], [43, 59, 62, 67], [48, 60, 64, 72]] },
        title: t('借别人的家一会儿', 'ちょっとだけ他人の家を借りる', 'Borrowing someone else’s home for a moment'),
        steps: [
          t('离调：让一个不是主和弦的和弦，暂时听起来像"家"。办法是在它前面放一个它自己的属和弦（或导七和弦），叫副属和弦。', '一時的転調：主和音でない和音を一時的に「家」のように聞かせること。その和音自身の属和音（または導七）を前に置きます。これを副属和音と呼びます。', 'Tonicization makes a non-tonic chord sound like home for a moment, by putting its own dominant (or leading-tone chord) in front of it — an applied chord.'),
          t('写法用斜杠：V/V 读作"五级的五级"，就是"属和弦的属和弦"。C 大调里 V/V = D F♯ A，它把 G 和弦当作临时的家。听：I – V/V – V – I。', '書き方はスラッシュ：V/V は「V の V」。C 長調では V/V = D F♯ A で、G の和音を一時的な家にします。聴いて：I – V/V – V – I。', 'They use a slash: V/V is read “five of five”. In C major V/V = D F♯ A, treating the G chord as a temporary home. Listen: I – V/V – V – I.'),
          t('副属和弦几乎总带临时记号，而且多半是升高音。', '副属和音にはほとんどいつも臨時記号がつき、多くは音を上げる記号です。', 'Applied chords nearly always carry accidentals, usually ones that raise a note.'),
          t('转调则是长时间换了一个新的主音。可以直接换（突然），也可以借一个两个调都有的"共同和弦"慢慢转过去。终止式会确立新调。', '転調は長い時間、新しい主音に移ること。突然変える直接転調と、両方の調にある「共通和音」を経由する穏やかな転調があります。終止形が新しい調を確立します。', 'Modulation is a longer-term change of tonic: either abrupt (direct) or smooth via a pivot chord shared by both keys. Cadences establish the new key.'),
        ] },
      { type: 'choice', ref: 'omt2e-tonicization',
        prompt: t('V/ii 怎么读？', 'V/ii の読み方は？', 'How do you read V/ii?'),
        options: [t('"二级的五级"——ii 的属和弦', '「ii の V」— ii の属和音', '“five of two” — the dominant of ii'), t('"五除以二"', '「5 割る 2」', '“five divided by two”'), t('先弹 V 再弹 ii 的和弦', 'V と ii を同時に弾く和音', 'V and ii played at once')], answer: 0,
        hint: t('斜杠读作"的"。', 'スラッシュは「の」と読む。', 'Read the slash as “of”.'),
        explain: t('斜杠前是副属和弦在临时调里的身份，斜杠后是被离调的和弦：V/ii = ii 的五级。', 'スラッシュの前は一時的な調での役割、後ろが一時的な主和音：V/ii = ii の V。', 'Before the slash is the chord’s role in the temporary key; after it, the chord being tonicized: V/ii = five of two.') },
      { type: 'choice', ref: 'omt2e-tonicization',
        prompt: t('C 大调里，V/V 是哪个和弦？', 'C 長調の V/V は？', 'In C major, V/V is…'),
        options: [t('D 大三和弦（D F♯ A）', 'D の長三和音（D F♯ A）', 'D major (D F♯ A)'), t('D 小三和弦（D F A）', 'D の短三和音（D F A）', 'D minor (D F A)'), t('G 大三和弦', 'G の長三和音', 'G major')], answer: 0,
        hint: t('C 大调的 V 是 G；G 的属和弦是？', 'C 長調の V は G、G の属和音は？', 'C major’s V is G; what is G’s dominant?'),
        explain: t('G 大调的 V 是 D 大三和弦。也可以想成把 ii（D F A）的 F 升高成 F♯。', 'G 長調の V は D の長三和音。ii（D F A）の F を F♯ にしたものとも考えられます。', 'G’s V is D major — or think of ii (D F A) with F raised to F♯.') },
      { type: 'choice', ref: 'omt2e-tonicization',
        prompt: t('副属和弦里常见的临时记号多半是？', '副属和音によく出る臨時記号は？', 'Applied chords usually carry accidentals that…'),
        options: [t('升高音', '音を上げる', 'raise notes'), t('降低音', '音を下げる', 'lower notes'), t('不带临时记号', '臨時記号はつかない', 'they have none')], answer: 0,
        hint: t('临时的导音要比"临时主音"低半音。', '一時的な導音は「一時的な主音」の半音下。', 'The temporary leading tone sits a half step under the temporary tonic.'),
        explain: t('例如 V/V 里的 F♯ 是 G 的临时导音，需要升高。', 'たとえば V/V の F♯ は G の一時的な導音で、上げる必要があります。', 'For example, V/V’s F♯ is G’s temporary leading tone — a raised note.') },
      { type: 'match', ref: 'omt2e-modulation',
        prompt: t('概念 ↔ 描述', '概念 ↔ 説明', 'Concept ↔ description'),
        pairs: [[t('离调', '一時的転調', 'tonicization'), t('短暂地把某个和弦当成家', '一瞬だけある和音を家にする', 'briefly treat a chord as home')], [t('直接转调', '直接転調', 'direct modulation'), t('突然换到新调', '突然新しい調へ', 'jump abruptly to the new key')], [t('共同和弦转调', '共通和音転調', 'pivot-chord modulation'), t('借两个调都有的和弦过渡', '両方の調にある和音を経由', 'pass through a chord both keys share')]],
        hint: t('离调是"暂时"，转调是"长期"。', '一時的転調は「一時」、転調は「長期」。', 'Tonicization is brief; modulation lasts.'),
        explain: t('离调只停留一下；转调真正换了主音，可以突然换，也可以经过共同和弦。', '一時的転調はすぐ戻り、転調は主音そのものが替わります。突然でも、共通和音経由でも。', 'Tonicization is a visit; modulation changes the tonic — abruptly or via a pivot chord.') },
      { type: 'choice', ref: 'omt2e-modulation',
        prompt: t('分析时，怎样最容易找到新调在哪里确立？', '新しい調がどこで確立したか、見つけやすい手がかりは？', 'What best shows where a new key is established?'),
        options: [t('找终止式', '終止形を探す', 'Find the cadences'), t('看第一个音', '最初の音を見る', 'Look at the first note'), t('看速度记号', '速度記号を見る', 'Look at the tempo marking')], answer: 0,
        hint: t('终止式会确立调性。', '終止形が調を確立する。', 'Cadences establish keys.'),
        explain: t('先找出终止式，就知道新调落在哪里；同一个临时记号反复出现也是线索。', 'まず終止形を見つければ新しい調がわかります。同じ臨時記号が繰り返し出るのも手がかり。', 'Find the cadences first and you know where the keys are; a recurring accidental is another clue.') },
    ],
  },
  {
    id: 'chromatic', section: 'harmony', feature: 'classical', icon: 'N6',
    title: t('半音化和弦：借用、那不勒斯与增六', '半音的和音：借用・ナポリ・増六', 'Chromatic chords: mixture, Neapolitan and augmented sixth'),
    blurb: t('调式混合、♭II6、意/法/德增六和弦、共同音减七', '同主調借用・♭II6・伊／仏／独の増六・共通音減七', 'Modal mixture, ♭II6, It/Fr/Ger sixths, common-tone diminished sevenths'),
    cards: [
      { type: 'guide', ref: ['omt2e-mixture', 'omt2e-neapolitan', 'omt2e-aug6', 'omt2e-common-tone'], demo: { play: [[48, 60, 64, 67], [53, 61, 65, 68], [43, 59, 62, 67], [48, 60, 64, 72]] },
        title: t('给和弦加一点"别的颜色"', '和音に「別の色」を少し', 'Adding a dash of another colour'),
        steps: [
          t('调式混合：从同主音的另一个调里"借"音。最常见的是大调向同主音小调借，比如 C 大调里用 A♭ 大三和弦，写成 ♭VI。借来的和弦颜色变了，但功能不变。', '同主調借用：同じ主音のもう一方の調から音を借ります。多いのは長調が同主短調から借りる例で、C 長調で A♭ の和音（♭VI）など。色は変わっても働きは同じ。', 'Modal mixture borrows notes from the parallel key — most often major borrowing from minor, like A♭ major in C major, written ♭VI. The colour changes, the function doesn’t.'),
          t('那不勒斯六和弦：建在降低的第二级（ra）上的大三和弦，几乎总是第一转位，写作 ♭II6，是下属功能。C 大调里是 D♭ F A♭，D♭ 再往下走到 B。听：I – ♭II6 – V – I。', 'ナポリの六の和音：下げた第 2 音（ra）上の長三和音で、ほぼいつも第 1 転回形（♭II6）。下属の働き。C 長調では D♭ F A♭ で、D♭ は B へ下がります。聴いて：I – ♭II6 – V – I。', 'The Neapolitan sixth is a major triad on the lowered 2nd (ra), almost always in first inversion (♭II6), a predominant. In C major it is D♭ F A♭, and D♭ steps down to B. Listen: I – ♭II6 – V – I.'),
          t('增六和弦：里面有 le 与 fi 之间的增六度（C 大调里 A♭ 与 F♯），分意大利、法国、德国三种。它们没有根音，向外张开解决到原位的属和弦。', '増六の和音：le と fi の間の増 6 度（C 長調では A♭ と F♯）を含み、イタリア・フランス・ドイツの 3 種類。根音はなく、外へ開いて基本形の属和音に解決します。', 'Augmented sixth chords contain an augmented sixth between le and fi (A♭ and F♯ in C major) and come in Italian, French and German types. They have no root and resolve outward to a root-position dominant.'),
          t('共同音减七：和 vii°7 音一样，但用途不同——它和后面的和弦共享根音，只是用来装饰那个和弦。', '共通音減七：vii°7 と同じ音でも用途が違い、次の和音と根音を共有してそれを飾ります。', 'The common-tone diminished seventh has the same notes as vii°7 but a different job: it shares the root of the next chord and simply decorates it.'),
        ] },
      { type: 'choice', ref: 'omt2e-mixture',
        prompt: t('调式混合最常见的方向是？', '同主調借用でいちばん多い方向は？', 'Modal mixture most often goes…'),
        options: [t('大调向同主音小调借', '長調が同主短調から借りる', 'major borrowing from the parallel minor'), t('小调向关系大调借', '短調が平行長調から借りる', 'minor borrowing from the relative major'), t('随便向哪个调借', 'どの調からでも', 'from any key at all')], answer: 0,
        hint: t('"同主音"= 主音一样的另一个调。', '「同主」= 主音が同じもう一方の調。', '“Parallel” = the other key on the same tonic.'),
        explain: t('混合是向同主音调借音，最常见的是大调借小调的音。', '借用は同主調から。多いのは長調が短調の音を借りるケース。', 'Mixture borrows from the parallel key, most often major borrowing minor’s notes.') },
      { type: 'choice', ref: 'omt2e-mixture',
        prompt: t('借来的和弦会改变什么？', '借用和音で変わるのは？', 'What does a borrowed chord change?'),
        options: [t('和弦的性质（颜色）', '和音の種類（色）', 'the chord’s quality (colour)'), t('和弦的功能', '和音の働き', 'the chord’s function'), t('调号', '調号', 'the key signature')], answer: 0,
        hint: t('iv 还是下属，只是变成小三和弦了。', 'iv は下属のまま、短三和音になっただけ。', 'iv is still a predominant — just minor now.'),
        explain: t('混合改变性质，不改变功能：C 大调里借来的 F 小三和弦（iv）仍然是下属和弦。', '借用は種類を変えても働きは変えません：C 長調で借りた F の短三和音（iv）は下属のまま。', 'Mixture changes quality, not function: a borrowed F minor (iv) in C major is still a predominant.') },
      { type: 'fill', ref: 'omt2e-neapolitan',
        prompt: t('C 大调的那不勒斯和弦：___ F A♭，通常写作 ♭II6', 'C 長調のナポリの和音：___ F A♭、ふつう ♭II6', 'C major’s Neapolitan: ___ F A♭, usually written ♭II6'),
        bank: [opt('Db', 'D♭'), opt('D', 'D'), opt('C', 'C')], answer: ['Db'],
        hint: t('建在降低的第二级上。', '下げた第 2 音の上に作る。', 'Built on the lowered second degree.'),
        explain: t('第二级 D 降低成 D♭（ra），上面叠大三和弦：D♭ F A♭。解决时 D♭ 往下走到 B。', '第 2 音 D を D♭（ra）に下げ、長三和音 D♭ F A♭。解決では D♭ が B へ下がります。', 'D lowered to D♭ (ra) with a major triad on top: D♭ F A♭. When it resolves, D♭ steps down to B.') },
      { type: 'match', ref: ['omt2e-neapolitan', 'omt2e-aug6', 'omt2e-common-tone', 'omt2e-mixture'],
        prompt: t('和弦 ↔ 特点', '和音 ↔ 特徴', 'Chord ↔ trait'),
        pairs: [['♭II6', t('建在 ra 上的大三和弦', 'ra 上の長三和音', 'major triad on ra')], [t('增六和弦', '増六の和音', 'augmented sixth'), t('le 与 fi 形成增六度', 'le と fi が増 6 度', 'le and fi form an augmented sixth')], [t('共同音减七', '共通音減七', 'common-tone dim7'), t('和下一个和弦共享根音', '次の和音と根音を共有', 'shares the next chord’s root')], ['♭VI', t('从同主音小调借来', '同主短調から借用', 'borrowed from the parallel minor')]],
        hint: t('♭ 写在罗马数字前面，表示根音被降低了。', 'ローマ数字の前の ♭ は根音が下がったしるし。', 'A ♭ before the numeral means the root is lowered.'),
        explain: t('♭II6 那不勒斯；增六有 le–fi 增六度；共同音减七装饰下一个和弦；♭VI 是借用和弦。', '♭II6 はナポリ、増六は le–fi、共通音減七は次の和音を飾る、♭VI は借用。', '♭II6 Neapolitan; augmented sixth has le–fi; the common-tone dim7 decorates the next chord; ♭VI is borrowed.') },
      { type: 'choice', ref: 'omt2e-aug6',
        prompt: t('增六和弦通常解决到哪里？', '増六の和音はふつうどこへ解決する？', 'An augmented sixth chord normally resolves to…'),
        options: [t('原位的属和弦（V）', '基本形の属和音（V）', 'a root-position dominant (V)'), t('主和弦 I', '主和音 I', 'the tonic I'), t('下属和弦 IV', '下属和音 IV', 'the subdominant IV')], answer: 0,
        hint: t('它本身是下属功能的和弦。', 'それ自体は下属の働き。', 'It is itself a predominant.'),
        explain: t('le 往下、fi 往上，两个音向外张开到 sol 的八度，于是到达 V。', 'le は下へ、fi は上へ、外側に開いて sol のオクターヴに着き、V になります。', 'le falls and fi rises, opening outward to an octave on sol — arriving at V.') },
    ],
  },
  {
    id: 'neoriemann', section: 'harmony', feature: 'neo', icon: 'PLR',
    title: t('和声连接论：P、R、L', '和音の連結：P・R・L', 'Chord connections: P, R and L'),
    blurb: t('新黎曼变换：只动一个音就换和弦', 'ネオ・リーマン変換：1 音だけ動かしてコードを変える', 'Neo-Riemannian moves: change chords by moving one note'),
    cards: [
      { type: 'guide', ref: 'omt2e-neo-riemannian', demo: { play: [[60, 64, 67], [60, 63, 67], [60, 64, 69], [59, 64, 67]] },
        title: t('只挪一个音，换一个和弦', '1 音だけ動かして別のコードへ', 'Move one note, get a new chord'),
        steps: [
          t('新黎曼理论关心的是：两个三和弦共享多少个音，而不一定在同一个调里。', 'ネオ・リーマン理論は、同じ調にあるかよりも、2 つの三和音がいくつ音を共有するかに注目します。', 'Neo-Riemannian theory cares about how many notes two triads share, not whether they sit in one key.'),
          t('每个变换都在一个大三和弦和一个小三和弦之间来回切换。最基本的三种只动一个音、保留两个共同音。', 'どの変換も長三和音と短三和音を行き来します。基本の 3 つは 1 音だけ動かし、共通音を 2 つ残します。', 'Every transformation toggles between one major and one minor triad. The three basic ones move one note and keep two common tones.'),
          t('P（平行）：C ↔ Cm，同根音；R（关系）：C ↔ Am，小三度以下；L（导音交换）：C ↔ Em，大三度以上。听：C、Cm、Am、Em。', 'P（平行）：C ↔ Cm（同じ根音）、R（平行調）：C ↔ Am（短 3 度下）、L（導音交換）：C ↔ Em（長 3 度上）。聴いて：C・Cm・Am・Em。', 'P (parallel): C ↔ Cm, same root; R (relative): C ↔ Am, a minor third down; L (leading-tone exchange): C ↔ Em, a major third up. Listen: C, Cm, Am, Em.'),
          t('还有动两个音、只留一个共同音的 S（C ↔ C♯m）和 N（C ↔ Fm）；H（C ↔ A♭m）三个音都各挪半音，一个共同音也没有。', '2 音を動かし共通音 1 つの S（C ↔ C♯m）と N（C ↔ Fm）、3 音すべてを半音ずつ動かし共通音なしの H（C ↔ A♭m）もあります。', 'S (C ↔ C♯m) and N (C ↔ Fm) move two notes and keep one; H (C ↔ A♭m) moves all three by a half step and keeps none.'),
        ] },
      { type: 'match', ref: 'omt2e-neo-riemannian',
        prompt: t('从 C 大三和弦出发：变换 ↔ 结果', 'C の長三和音から：変換 ↔ 結果', 'Starting from C major: move ↔ result'),
        pairs: [['P', 'Cm'], ['R', 'Am'], ['L', 'Em']],
        hint: t('P 同根音；R 是关系小调。', 'P は同じ根音、R は平行調。', 'P keeps the root; R is the relative minor.'),
        explain: t('P：E→E♭ 得 Cm；R：G→A 得 Am；L：C→B 得 Em。', 'P：E→E♭ で Cm、R：G→A で Am、L：C→B で Em。', 'P: E→E♭ gives Cm; R: G→A gives Am; L: C→B gives Em.') },
      { type: 'choice', ref: 'omt2e-neo-riemannian', audio: { notes: [[60, 64, 67], [59, 64, 67]], mode: 'chords' },
        prompt: t('C（C E G）→ Em（B E G），动的是哪个音？', 'C（C E G）→ Em（B E G）で動くのは？', 'C (C E G) → Em (B E G): which note moved?'),
        options: [t('C 往下半音到 B', 'C が半音下がって B', 'C down a half step to B'), t('E 往上到 F', 'E が F へ', 'E up to F'), t('G 往上到 A', 'G が A へ', 'G up to A')], answer: 0,
        hint: t('E 和 G 都还在。', 'E と G は残っている。', 'E and G are still there.'),
        explain: t('这就是 L（导音交换）：根音 C 换成导音 B，两个共同音 E、G 不动。', 'これが L（導音交換）：根音 C が導音 B に替わり、共通音 E・G はそのまま。', 'That is L (leading-tone exchange): the root C becomes B, with E and G kept.') },
      { type: 'choice', ref: 'omt2e-neo-riemannian',
        prompt: t('P、R、L 每一步保留几个共同音？', 'P・R・L は 1 回で共通音をいくつ残す？', 'How many common tones do P, R and L keep?'),
        options: ['2', '1', '0'], answer: 0,
        hint: t('三个音里只动了一个。', '3 音のうち 1 つだけ動く。', 'Only one of the three notes moves.'),
        explain: t('三种基本变换都只挪一个音，所以两个共同音保留。', '基本の 3 つは 1 音だけ動かすので共通音は 2 つ。', 'The three basic moves shift one note, keeping two common tones.') },
      { type: 'choice', ref: 'omt2e-neo-riemannian',
        prompt: t('哪个变换一个共同音也不保留？', '共通音を 1 つも残さない変換は？', 'Which move keeps no common tones?'),
        options: [t('H（C ↔ A♭m）', 'H（C ↔ A♭m）', 'H (C ↔ A♭m)'), t('P（C ↔ Cm）', 'P（C ↔ Cm）', 'P (C ↔ Cm)'), t('N（C ↔ Fm）', 'N（C ↔ Fm）', 'N (C ↔ Fm)')], answer: 0,
        hint: t('每个音都挪了半音。', 'すべての音が半音ずつ動く。', 'Every note moves a half step.'),
        explain: t('H：C→C♭(B)、E→E♭、G→A♭，三个音各挪半音。', 'H：C→C♭(B)、E→E♭、G→A♭、すべて半音ずつ。', 'H: C→C♭ (B), E→E♭, G→A♭ — each by a half step.') },
      { type: 'fill', ref: 'omt2e-neo-riemannian',
        prompt: t('从 C 出发：S 得到 ___，N 得到 ___', 'C から：S で ___、N で ___', 'From C: S gives ___, N gives ___'),
        bank: [opt('csm', 'C♯m'), opt('fm', 'Fm'), opt('am', 'Am'), opt('gm', 'Gm')], answer: ['csm', 'fm'],
        hint: t('S（滑动）到半音以上的小三和弦；N 到五度以下的小三和弦。', 'S は半音上の短三和音、N は 5 度下の短三和音。', 'S slides to the minor triad a half step up; N goes to the minor triad a fifth below.'),
        explain: t('S：C ↔ C♯m（共享 E）；N：C ↔ Fm（共享 C）。', 'S：C ↔ C♯m（E を共有）、N：C ↔ Fm（C を共有）。', 'S: C ↔ C♯m (sharing E); N: C ↔ Fm (sharing C).') },
    ],
  },
  {
    id: 'circle', section: 'harmony', feature: 'circle', icon: 'C·G',
    title: t('五度圈：调与和声功能的地图', '五度圏：調と和声の機能の地図', 'The circle of fifths: a map of keys and functions'),
    blurb: t('学过主、下属、属和转调之后，再看五度圈怎么把它们串起来', 'トニック・下属・ドミナントと転調を学んだあと、五度圏がそれらをどうつなぐか', 'After tonic, predominant, dominant and modulation: how the circle ties them together'),
    cards: [
      { type: 'guide', ref: 'wiki-circle-of-fifths', visual: { kind: 'circle', highlight: ['C'], inner: ['A'] }, tool: { feature: 'circle' },
        title: t('一张把 12 个调排成钟面的地图', '12 の調を時計のように並べた地図', 'A clock-face map of all 12 keys'),
        steps: [
          t('五度圈把 12 个音按"上行纯五度"排成一圈：C G D A E B F♯/G♭ D♭ A♭ E♭ B♭ F，再回到 C。顺时针一格 = 上行纯五度，逆时针一格 = 上行纯四度。', '五度圏は 12 音を「完全 5 度上」の順に一周させる：C G D A E B F♯/G♭ D♭ A♭ E♭ B♭ F、そして C へ。時計回り 1 つ = 完全 5 度上、反時計回り 1 つ = 完全 4 度上。', 'The circle lines up the 12 notes by ascending perfect fifths: C G D A E B F♯/G♭ D♭ A♭ E♭ B♭ F, back to C. One step clockwise = up a perfect fifth; counterclockwise = up a perfect fourth.'),
          t('你学过的三种功能在圈上是挨着的：主（I = C）在中间，属（V = G）在顺时针一格，下属（IV = F）在逆时针一格。外圈写大调和它的调号，内圈写调号相同的关系小调（C 对应 a）。', '学んだ 3 つの機能は圏上で隣り合う：トニック（I = C）が真ん中、ドミナント（V = G）が時計回り 1 つ、下属（IV = F）が反時計回り 1 つ。外側は長調とその調号、内側は同じ調号の平行短調（C と a）。', 'The three functions you know sit side by side: tonic (I = C) in the middle, dominant (V = G) one step clockwise, subdominant (IV = F) one step counterclockwise. The outer ring shows major keys and their signatures, the inner ring the relative minors (C with a).'),
          t('和弦按五度往下走就是在圈上逆时针走：ii → V → I（D → G → C）一格一格走回主音，所以 ii 比 IV 更接近属；I–ii–V–I 的正格终止也比 I–IV–I 的变格终止更有"到家"的感觉。', '5 度ずつ下がる進行は圏上を反時計回り：ii → V → I（D → G → C）が 1 つずつ主音へ戻る。だから ii は IV よりドミナントに近く、I–ii–V–I の正格終止は I–IV–I の変格終止より「帰った」感じが強い。', 'Chords falling by fifths walk counterclockwise: ii → V → I (D → G → C) step home one at a time — so ii sits closer to the dominant than IV, and I–ii–V–I sounds more final than I–IV–I.'),
          t('相邻的调只差一个升降号，转调最常去隔壁（V、IV 的调和它们的关系小调）——也就是你在"离调与转调"里学到的近关系调。', '隣の調は調号が 1 つ違うだけ。転調はたいてい隣（V・IV の調とその平行短調）へ——「一時的転調と転調」で学んだ近親調です。', 'Neighbouring keys differ by one accidental, so modulations usually go next door (the keys of V and IV and their relative minors) — the closely related keys from the tonicization lesson.'),
        ] },
      { type: 'fill', ref: 'wiki-circle-of-fifths', visual: { kind: 'circle', highlight: ['C', 'G', 'D'] },
        prompt: t('顺时针：C G D ___ E B', '時計回り：C G D ___ E B', 'Clockwise: C G D ___ E B'),
        bank: [opt('A', 'A'), opt('F', 'F'), opt('B', 'B♭')], answer: ['A'],
        hint: t('D 往上一个纯五度。', 'D から完全 5 度上。', 'A perfect fifth above D.'),
        explain: t('D 往上五度是 A，A 再往上五度是 E。', 'D の 5 度上は A、その 5 度上が E。', 'A fifth above D is A; a fifth above A is E.') },
      { type: 'match', ref: 'wiki-circle-of-fifths', visual: { kind: 'circle', highlight: ['F', 'C', 'G'] },
        prompt: t('C 大调：功能 ↔ 在五度圈上的位置', 'C 長調：機能 ↔ 五度圏上の位置', 'C major: function ↔ place on the circle'),
        pairs: [[t('主（I = C）', 'トニック（I = C）', 'tonic (I = C)'), t('中间', '真ん中', 'the centre')], [t('属（V = G）', 'ドミナント（V = G）', 'dominant (V = G)'), t('顺时针一格', '時計回り 1 つ', 'one step clockwise')], [t('下属（IV = F）', '下属（IV = F）', 'subdominant (IV = F)'), t('逆时针一格', '反時計回り 1 つ', 'one step counterclockwise')]],
        hint: t('G 在 C 上方纯五度，F 在 C 上方纯四度。', 'G は C の完全 5 度上、F は完全 4 度上。', 'G is a fifth above C, F a fourth above.'),
        explain: t('I、IV、V 在五度圈上是连着的三格：F – C – G。', 'I・IV・V は圏上で連続する 3 つ：F – C – G。', 'I, IV and V are three neighbouring slots: F – C – G.') },
      { type: 'choice', ref: 'wiki-circle-of-fifths',
        prompt: t('为什么说 ii 比 IV 更接近属和弦？', 'なぜ ii は IV よりドミナントに近い？', 'Why is ii said to be closer to the dominant than IV?'),
        options: [t('在五度圈上 ii 紧挨着 V，往下五度就到 V', '五度圏で ii は V の隣で、5 度下がれば V', 'on the circle ii sits next to V — a fifth down reaches V'), t('因为 ii 是大三和弦', 'ii が長三和音だから', 'because ii is a major chord'), t('因为 ii 和 V 同根音', 'ii と V の根音が同じだから', 'because ii and V share a root')], answer: 0,
        hint: t('C 调：D → G → C。', 'C：D → G → C。', 'In C: D → G → C.'),
        explain: t('ii（D）在 V（G）顺时针一格，往下五度直接到 V；IV（F）则在主和弦的另一边。', 'ii（D）は V（G）の時計回り隣で 5 度下がれば V。IV（F）は主和音の反対側。', 'ii (D) sits one step clockwise of V (G) and falls straight to it; IV (F) is on the far side of the tonic.') },
      { type: 'choice', ref: 'wiki-circle-of-fifths',
        prompt: t('从 C 逆时针走一格是哪个调？它有几个降号？', 'C から反時計回りに 1 つ進むと？フラットはいくつ？', 'One step counterclockwise from C is which key, with how many flats?'),
        options: [t('F，一个降号', 'F、フラット 1 つ', 'F, one flat'), t('G，一个升号', 'G、シャープ 1 つ', 'G, one sharp'), t('B♭，两个降号', 'B♭、フラット 2 つ', 'B♭, two flats')], answer: 0,
        hint: t('逆时针 = 往上四度，多一个降号。', '反時計回り = 4 度上、フラットが 1 つ増える。', 'Counterclockwise = up a fourth, one more flat.'),
        explain: t('C 往上纯四度是 F，F 大调一个降号（B♭）。', 'C の完全 4 度上は F、F 長調はフラット 1 つ（B♭）。', 'A perfect fourth above C is F; F major has one flat (B♭).') },
      { type: 'choice', ref: 'wiki-circle-of-fifths', visual: { kind: 'circle', highlight: ['G'], inner: ['E'] },
        prompt: t('外圈 G 旁边的内圈写的是哪个小调？', '外側 G の内側にある短調は？', 'Which minor key sits inside G on the circle?'),
        options: [t('e 小调', 'e 短調', 'E minor'), t('g 小调', 'g 短調', 'G minor'), t('b 小调', 'b 短調', 'B minor')], answer: 0,
        hint: t('内圈 = 调号相同的关系小调。', '内側 = 調号が同じ平行短調。', 'Inner ring = the relative minor with the same signature.'),
        explain: t('G 大调和 e 小调都是一个升号，所以写在同一个位置。', 'G 長調と e 短調はどちらもシャープ 1 つなので同じ位置。', 'G major and E minor both have one sharp, so they share a slot.') },
      { type: 'choice', ref: 'wiki-circle-of-fifths',
        prompt: t('和弦进行 G → C（V → I）在五度圈上是往哪个方向走？', 'G → C（V → I）は五度圏のどちら向き？', 'Which way does G → C (V → I) move on the circle?'),
        options: [t('逆时针一格', '反時計回りに 1 つ', 'one step counterclockwise'), t('顺时针一格', '時計回りに 1 つ', 'one step clockwise'), t('转半圈', '半周', 'half a turn')], answer: 0,
        hint: t('G 在 C 的顺时针旁边。', 'G は C の時計回り隣。', 'G sits just clockwise of C.'),
        explain: t('从 G 回到 C 是逆时针一格——按五度往下走的进行都是逆时针。', 'G から C は反時計回り 1 つ。5 度下がる進行はすべて反時計回り。', 'G back to C is one step counterclockwise — falling-fifth progressions all run counterclockwise.') },
      { type: 'match', ref: 'wiki-circle-of-fifths',
        prompt: t('大调 ↔ 调号', '長調 ↔ 調号', 'Major key ↔ key signature'),
        pairs: [['G', t('1 个升号', 'シャープ 1', '1 sharp')], ['D', t('2 个升号', 'シャープ 2', '2 sharps')], ['F', t('1 个降号', 'フラット 1', '1 flat')], ['B♭', t('2 个降号', 'フラット 2', '2 flats')]],
        hint: t('从 C 出发数格子：顺时针数升号，逆时针数降号。', 'C から数える：時計回りはシャープ、反時計回りはフラット。', 'Count steps from C: clockwise for sharps, counterclockwise for flats.'),
        explain: t('G、D 在 C 顺时针第 1、2 格；F、B♭ 在逆时针第 1、2 格。', 'G・D は時計回り 1・2 つ目、F・B♭ は反時計回り 1・2 つ目。', 'G and D are 1 and 2 steps clockwise; F and B♭ are 1 and 2 steps counterclockwise.') },
    ],
  },
];

// 关卡顺序（从简到难）
const ORDER = ['triads', 'sevenths', 'inversions', 'symbols', 'chordplus', 'voicing', 'roman', 'figured', 'functions', 'cadences', 'sixfour', 'form', 'forms', 'tonicization', 'chromatic', 'circle', 'neoriemann'];
export const UNITS = ORDER.map((id) => {
  const unit = ALL.find((u) => u.id === id);
  if (!unit) throw new Error(`unknown unit ${id}`);
  return unit;
});
if (UNITS.length !== ALL.length) throw new Error('every unit must appear in ORDER');
