// 乐理闯关 · 二十世纪与微分音：每张题卡标出依据（ref），只使用 references.js 中已登记、已核实的资料；解析用尽量通俗的话转述这些资料。
// 依据汇总（由 scripts/annotate-learn.mjs 生成）：
//   ref:omt2e-row-naming ref:omt2e-normal-order ref:omt2e-pitch-class ref:omt2e-integer-intervals
//   ref:omt2e-collections ref:wiki-messiaen-modes ref:omt2e-prime-form ref:omt2e-ic-vector ref:omt2e-twelve-tone
//   ref:wiki-pythagorean ref:wiki-turkish-makam ref:wiki-arabic-maqam ref:wiki-neutral-third ref:wiki-limit
//   ref:hf-intervals ref:gann-ji
// @refs-end

const t = (zh, ja, en) => ({ zh, ja, en });
const opt = (id, label) => ({ id, label });

const ALL = [
  {
    id: 'posttonal', section: 'modern', feature: 'posttonal', icon: '0',
    title: t('把音变成数字', '音を数字にする', 'Turning notes into numbers'),
    blurb: t('音级、移位与十二音序列', '音高クラス・移高・12 音列', 'Pitch classes, transposition and tone rows'),
    cards: [
      { type: 'guide', ref: ['omt2e-row-naming', 'omt2e-normal-order'],
        title: t('像钟表一样数音', '時計のように音を数える', 'Count notes like a clock'),
        steps: [
          t('二十世纪的很多音乐不讲调性，于是把 12 个音当成 0–11 的数字（固定零：C = 0）。', '20 世紀の多くの音楽は調性によらず、12 の音を 0–11 の数字で扱います（固定ゼロ：C = 0）。', 'Much 20th-century music has no key, so the 12 notes become numbers 0–11 (fixed zero: C = 0).'),
          t('数字像钟表一样转圈：到 12 就回到 0。', '数字は時計のように回り、12 で 0 に戻ります。', 'The numbers wrap like a clock: 12 comes back to 0.'),
          t('"移位 Tn"就是每个数都加 n。', '「移高 Tn」はすべての数に n を足すこと。', 'Transposition Tn adds n to every number.'),
        ] },
      { type: 'fill', ref: 'omt2e-normal-order',
        prompt: t('把 {0, 4, 7}（C 大三和弦）移位 T2：{2, ___, 9}', '{0, 4, 7}（C 長三和音）を T2：{2, ___, 9}', 'Transpose {0, 4, 7} (C major) by T2: {2, ___, 9}'),
        bank: [opt('6', '6'), opt('5', '5'), opt('7', '7')], answer: ['6'],
        hint: t('4 + 2 = ?', '4 + 2 = ?', '4 + 2 = ?'),
        explain: t('每个都加 2：{2, 6, 9} = D F♯ A，D 大三和弦。', 'すべてに 2 を足して {2, 6, 9} = D F♯ A、D 長三和音。', 'Add 2 to each: {2, 6, 9} = D F♯ A, a D major triad.') },
      { type: 'choice', ref: 'omt2e-normal-order',
        prompt: t('在音级世界里，11 + 3 = ？', '音高クラスでは 11 + 3 = ？', 'In pitch-class world, 11 + 3 = ?'),
        options: ['2', '14', '0'], answer: 0,
        hint: t('像钟表：过了 11 就从 0 再数。', '時計のように、11 の次は 0 から。', 'Like a clock: after 11, start again from 0.'),
        explain: t('14 − 12 = 2，所以是 2（B 往上小三度是 D）。', '14 − 12 = 2（B から短 3 度上は D）。', '14 − 12 = 2 (a minor third above B is D).') },
      { type: 'match', ref: 'omt2e-row-naming',
        prompt: t('十二音序列的四种形式', '12 音列の 4 つの形', 'The four forms of a tone row'),
        pairs: [['P', t('原形', '原形', 'prime')], ['I', t('倒影（上下翻转）', '反行（上下反転）', 'inversion (flipped)')], ['R', t('逆行（倒着走）', '逆行（後ろから）', 'retrograde (backwards)')], ['RI', t('逆行倒影', '反行の逆行', 'retrograde inversion')]],
        hint: t('R = 倒着来，I = 上下颠倒。', 'R = 後ろから、I = 上下ひっくり返す。', 'R = backwards, I = upside down.'),
        explain: t('一行序列有 P、I、R、RI 四种形式。', '音列には P・I・R・RI の 4 つの形があります。', 'A row has four forms: P, I, R and RI.') },
    ],
  },
  {
    id: 'micro', section: 'modern', feature: 'micro', icon: '∞',
    title: t('微分音：把八度切得更细', '微分音：オクターヴをもっと細かく', 'Microtones: slicing the octave finer'),
    blurb: t('音分、24 平均与 53 个 koma', 'セント・24 平均・53 コマ', 'Cents, 24-TET and 53 commas'),
    cards: [
      { type: 'guide', ref: ['wiki-pythagorean', 'wiki-turkish-makam'],
        title: t('八度不一定只切 12 份', 'オクターヴは 12 分割だけじゃない', 'The octave needn’t have only 12 slices'),
        steps: [
          t('用"音分"来量音高：一个八度 = 1200 音分。', '音高は「セント」で測ります：オクターヴ = 1200 セント。', 'Measure pitch in cents: an octave is 1200 cents.'),
          t('钢琴把八度平均切成 12 份；四分之一音的记谱切成 24 份。', 'ピアノはオクターヴを 12 等分、四分音の記譜は 24 等分。', 'A piano slices the octave into 12 equal parts; quarter-tone notation uses 24.'),
          t('土耳其古典音乐的理论更细：一个八度 53 个 koma。', 'トルコ古典音楽の理論はもっと細かく、オクターヴ 53 コマ。', 'Turkish classical theory is finer still: 53 commas per octave.'),
        ] },
      { type: 'fill', ref: 'wiki-pythagorean',
        prompt: t('一个八度 1200 音分；十二平均里每个半音 = ___ 音分', 'オクターヴ 1200 セント。12 平均の半音 = ___ セント', 'Octave = 1200 cents; a 12-TET half step = ___ cents'),
        bank: [opt('100', '100'), opt('50', '50'), opt('120', '120')], answer: ['100'],
        hint: t('1200 ÷ 12', '1200 ÷ 12', '1200 ÷ 12'),
        explain: t('1200 ÷ 12 = 100 音分。', '1200 ÷ 12 = 100 セント。', '1200 ÷ 12 = 100 cents.') },
      { type: 'choice', ref: 'wiki-arabic-maqam',
        prompt: t('24 平均（四分之一音）每一步是多少音分？', '24 平均（四分音）の 1 歩は何セント？', 'One step of 24-TET (quarter tones) is how many cents?'),
        options: ['50', '25', '100'], answer: 0,
        hint: t('半个半音。', '半音の半分。', 'Half of a half step.'),
        explain: t('1200 ÷ 24 = 50 音分，正好半个半音。', '1200 ÷ 24 = 50 セント、ちょうど半音の半分。', '1200 ÷ 24 = 50 cents — exactly half a half step.') },
      { type: 'match', ref: 'wiki-turkish-makam',
        prompt: t('土耳其 53 koma 体系', 'トルコの 53 コマ体系', 'The Turkish 53-comma system'),
        pairs: [[t('一个八度', 'オクターヴ', 'one octave'), t('53 koma', '53 コマ', '53 commas')], [t('一个全音', '全音', 'one whole step'), t('9 koma', '9 コマ', '9 commas')], [t('bakiye（小半音）', 'バキイェ（小さい半音）', 'bakiye (small semitone)'), t('4 koma', '4 コマ', '4 commas')]],
        hint: t('全音比两个 bakiye 还多一点。', '全音はバキイェ 2 つより少し大きい。', 'A whole step is a bit more than two bakiye.'),
        explain: t('八度 53 koma，全音 9 koma，bakiye 4 koma。', 'オクターヴ 53、全音 9、バキイェ 4 コマ。', 'Octave 53, whole step 9, bakiye 4 commas.') },
      { type: 'choice', ref: 'wiki-turkish-makam',
        prompt: t('一个 koma 大约多少音分？（1200 ÷ 53）', '1 コマは約何セント？（1200 ÷ 53）', 'About how many cents is one comma? (1200 ÷ 53)'),
        options: ['22.6', '50', '9'], answer: 0,
        hint: t('比 24 平均的一步（50）小得多。', '24 平均の 1 歩（50）よりずっと小さい。', 'Much smaller than a 24-TET step (50).'),
        explain: t('1200 ÷ 53 ≈ 22.6 音分——比四分之一音还小一半多。', '1200 ÷ 53 ≈ 22.6 セント。四分音の半分よりも小さい。', '1200 ÷ 53 ≈ 22.6 cents — less than half a quarter tone.') },
    ],
  },
  {
    id: 'pitchclass', section: 'modern', feature: 'posttonal', icon: '0–11',
    title: t('音高、音级与整数音程', 'ピッチ・ピッチクラス・整数の音程', 'Pitch, pitch class and integer intervals'),
    blurb: t('C = 0；音程用半音数来量；音程级不超过 6', 'C = 0、音程は半音の数、音程クラスは 6 以下', 'C = 0; intervals in semitones; interval classes never exceed 6'),
    cards: [
      { type: 'guide', ref: ['omt2e-pitch-class', 'omt2e-integer-intervals'],
        title: t('先忘掉字母，只数半音', 'まず文字を忘れて半音だけ数える', 'Forget the letters, count semitones'),
        steps: [
          t('"音高"是一个具体的音，比如 C4，它和 C3 不是同一个音高。"音级"（pitch class）把所有八度关系和同音异名的音归成一组：A♭4、A♭3、G♯2 都属于同一个音级。', '「ピッチ」は C4 のような具体的な音で、C3 とは別のピッチ。「ピッチクラス」はオクターヴ違いや異名同音をひとまとめにしたもの：A♭4・A♭3・G♯2 は同じピッチクラス。', 'A pitch is a specific note like C4 — not the same pitch as C3. A pitch class groups all octave-related and enharmonic notes: A♭4, A♭3 and G♯2 share one pitch class.'),
          t('二十世纪的分析常用整数记音级：C = 0，C♯/D♭ = 1……B = 11，像钟表一样转圈。', '20 世紀の分析ではピッチクラスを整数で書きます：C = 0、C♯/D♭ = 1……B = 11。時計のように一周します。', 'Post-tonal analysis writes pitch classes as integers: C = 0, C♯/D♭ = 1 … B = 11, around a clock face.'),
          t('音程就用半音数：有序音高音程带方向（+/−），无序音高音程不带方向；有序音级音程总是在钟面上顺时针数（像 9 点到 5 点是 8 小时，不是 4 小时）。', '音程は半音の数で：順序付きピッチ音程は向き（+/−）つき、順序なしは向きなし。順序付きピッチクラス音程は時計回りに数えます（9 時から 5 時は 8 時間で、4 時間ではない）。', 'Intervals become semitone counts: ordered pitch intervals carry a direction (+/−), unordered ones don’t; ordered pitch-class intervals always count clockwise (9 to 5 o’clock is 8 hours, never 4).'),
          t('最抽象的是"音程级"：两个音级之间最短的距离，所以总是 0 到 6。', 'いちばん抽象的なのが「音程クラス」：2 つのピッチクラスの最短距離で、必ず 0〜6。', 'Most abstract is the interval class: the shortest distance between two pitch classes, so always 0–6.'),
        ] },
      { type: 'match', ref: 'omt2e-pitch-class',
        prompt: t('音名 ↔ 整数', '音名 ↔ 整数', 'Note ↔ integer'),
        pairs: [['C', '0'], ['E', '4'], ['G', '7'], ['B', '11']],
        hint: t('从 C = 0 开始，每半音加 1。', 'C = 0 から半音ごとに 1 足す。', 'Start at C = 0 and add 1 per semitone.'),
        explain: t('C 0、E 4、G 7、B 11——C 大三和弦就是 {0, 4, 7}。', 'C 0・E 4・G 7・B 11。C の長三和音は {0, 4, 7}。', 'C 0, E 4, G 7, B 11 — a C major triad is {0, 4, 7}.') },
      { type: 'choice', ref: 'omt2e-pitch-class',
        prompt: t('A♭4 和 G♯2 属于同一个音级吗？', 'A♭4 と G♯2 は同じピッチクラス？', 'Are A♭4 and G♯2 the same pitch class?'),
        options: [t('是（都是 8）', 'はい（どちらも 8）', 'Yes (both are 8)'), t('不是，八度不同', 'いいえ、オクターヴが違う', 'No, different octaves'), t('不是，拼法不同', 'いいえ、綴りが違う', 'No, different spellings')], answer: 0,
        hint: t('音级不管八度，也不管拼法。', 'ピッチクラスはオクターヴも綴りも問わない。', 'Pitch class ignores octave and spelling.'),
        explain: t('它们是不同的音高，却是同一个音级 8。', '違うピッチでも同じピッチクラス 8。', 'Different pitches, same pitch class: 8.') },
      { type: 'choice', ref: 'omt2e-integer-intervals',
        prompt: t('音级 2 和 11 之间的音程级是多少？', 'ピッチクラス 2 と 11 の音程クラスは？', 'What is the interval class between pitch classes 2 and 11?'),
        options: ['3', '9', '−9'], answer: 0,
        hint: t('钟面上走短的那条路。', '時計の短いほうの道。', 'Take the short way around the clock.'),
        explain: t('11 → 2 顺时针是 3 步（另一边是 9 步），取较小的：3。', '11 → 2 は時計回りに 3（反対回りは 9）、小さいほうで 3。', '11 → 2 clockwise is 3 (the other way is 9); take the smaller: 3.') },
      { type: 'choice', ref: 'omt2e-integer-intervals',
        prompt: t('从音级 9 到音级 5 的"有序音级音程"是？', 'ピッチクラス 9 から 5 への順序付きピッチクラス音程は？', 'The ordered pitch-class interval from 9 to 5 is…'),
        options: ['8', '4', '−4'], answer: 0,
        hint: t('总是顺时针数，像 9 点到 5 点。', 'いつも時計回り、9 時から 5 時のように。', 'Always count clockwise, like 9 o’clock to 5.'),
        explain: t('9 → 10 → 11 → 0 → … → 5，一共 8 步。', '9 → 10 → 11 → 0 → … → 5 で 8 歩。', '9 → 10 → 11 → 0 → … → 5 is 8 steps.') },
      { type: 'fill', ref: 'omt2e-integer-intervals',
        prompt: t('音程级最小是 ___，最大是 ___', '音程クラスの最小は ___、最大は ___', 'Interval classes range from ___ to ___'),
        bank: [opt('0', '0'), opt('6', '6'), opt('11', '11'), opt('12', '12')], answer: ['0', '6'],
        hint: t('超过 6 时，绕另一边更近。', '6 を超えたら反対回りのほうが近い。', 'Past 6, the other way round is shorter.'),
        explain: t('两个音级之间最短的距离不会超过半个钟面：0 到 6。', '最短距離は時計の半分を超えないので 0〜6。', 'The shortest distance never exceeds half the clock: 0 to 6.') },
    ],
  },
  {
    id: 'setclass', section: 'modern', feature: 'posttonal', icon: '(037)',
    title: t('音级集合：标准顺序、原型与音程级向量', 'ピッチクラス・セット：ノーマル・オーダー・プライム・フォーム・音程ベクトル', 'Pc sets: normal order, prime form and interval vectors'),
    blurb: t('给任何和弦一个"原位"', 'どんな和音にも「基本形」を', 'A “root position” for any chord'),
    cards: [
      { type: 'guide', ref: ['omt2e-normal-order', 'omt2e-prime-form', 'omt2e-ic-vector'],
        title: t('不靠调性，也能比较和弦', '調性に頼らず和音を比べる', 'Comparing chords without a key'),
        steps: [
          t('一组音级叫"音级集合"。"标准顺序"（normal order）是把它按升序排得最紧凑的写法，作用就像三和弦的原位。', 'ピッチクラスの集まりが「ピッチクラス・セット」。「ノーマル・オーダー」はそれを上行順で最も詰めて書いたもので、三和音の基本形のような役割。', 'A group of pitch classes is a pc set. Its normal order is the most compressed ascending arrangement — like root position for any chord.'),
          t('移位 Tn：每个数都加 n。倒影 In：用 n 减去每个数（n − x）。', '移高 Tn：各数に n を足す。反転 In：n から各数を引く（n − x）。', 'Transposition Tn adds n to each number; inversion In subtracts each number from n (n − x).'),
          t('彼此能通过移位或倒影得到的集合，属于同一个"集合类"，用"原型"（prime form）命名：移到 0 开头、并且（和它的倒影相比）往左边最紧凑的那个。大三和弦和小三和弦都是 (037)。', '移高か反転で互いに移れるセットは同じ「セット・クラス」に属し、「プライム・フォーム」で名づけます：0 から始まり、反転と比べて左側に最も詰まったもの。長三和音も短三和音も (037)。', 'Sets related by transposition or inversion form one set class, named by its prime form: transposed to start on 0 and most compact to the left compared with its inversion. Major and minor triads are both (037).'),
          t('音程级向量是 6 位数，依次数出集合里有几个音程级 1、2、3、4、5、6。C 大三和弦是 <001110>。', '音程クラス・ベクトルは 6 桁で、セット内の音程クラス 1〜6 の数を順に数えたもの。C の長三和音は <001110>。', 'The interval-class vector is six digits counting interval classes 1 to 6 in the set. A C major triad is <001110>.'),
        ] },
      { type: 'fill', ref: 'omt2e-normal-order',
        prompt: t('把 {0, 4, 7} 做 T5：{5, ___, 0}', '{0, 4, 7} を T5：{5, ___, 0}', 'Apply T5 to {0, 4, 7}: {5, ___, 0}'),
        bank: [opt('9', '9'), opt('11', '11'), opt('2', '2')], answer: ['9'],
        hint: t('每个数加 5，超过 11 就减 12。', '各数に 5 を足し、11 を超えたら 12 を引く。', 'Add 5 to each; subtract 12 past 11.'),
        explain: t('0+5 = 5，4+5 = 9，7+5 = 12 → 0：{5, 9, 0} 就是 F 大三和弦。', '0+5 = 5、4+5 = 9、7+5 = 12 → 0。{5, 9, 0} は F の長三和音。', '0+5 = 5, 4+5 = 9, 7+5 = 12 → 0: {5, 9, 0} is F major.') },
      { type: 'choice', ref: 'omt2e-normal-order',
        prompt: t('用 I0 倒影 {0, 4, 7}，得到？', '{0, 4, 7} を I0 で反転すると？', 'Inverting {0, 4, 7} with I0 gives…'),
        options: ['{0, 8, 5}', '{0, 4, 7}', '{0, 3, 7}'], answer: 0,
        hint: t('0 − x：0 − 4 = −4 → 8。', '0 − x：0 − 4 = −4 → 8。', '0 − x: 0 − 4 = −4 → 8.'),
        explain: t('0−0 = 0，0−4 = 8，0−7 = 5：{0, 8, 5} = F、A♭、C，是 F 小三和弦——大三和弦倒过来成了小三和弦。', '0−0 = 0、0−4 = 8、0−7 = 5：{0, 8, 5} = F・A♭・C で F の短三和音。長三和音を反転すると短三和音に。', '0−0 = 0, 0−4 = 8, 0−7 = 5: {0, 8, 5} = F, A♭, C — F minor. Inverting a major triad gives a minor one.') },
      { type: 'choice', ref: 'omt2e-prime-form',
        prompt: t('大三和弦和小三和弦属于同一个集合类吗？', '長三和音と短三和音は同じセット・クラス？', 'Are major and minor triads in the same set class?'),
        options: [t('是，都是 (037)', 'はい、どちらも (037)', 'Yes — both are (037)'), t('不是', 'いいえ', 'No')], answer: 0,
        hint: t('它们互为倒影。', '互いに反転の関係。', 'They are inversions of each other.'),
        explain: t('集合类把移位和倒影相关的集合归在一起，所以大三、小三和弦共用原型 (037)。', 'セット・クラスは移高と反転で結ばれたセットをまとめるので、長短三和音はどちらも (037)。', 'A set class groups sets related by transposition or inversion, so major and minor triads share the prime form (037).') },
      { type: 'match', ref: ['omt2e-normal-order', 'omt2e-prime-form', 'omt2e-ic-vector'],
        prompt: t('术语 ↔ 意思', '用語 ↔ 意味', 'Term ↔ meaning'),
        pairs: [[t('标准顺序', 'ノーマル・オーダー', 'normal order'), t('升序、最紧凑的排法', '上行で最も詰めた並べ方', 'the most compact ascending order')], [t('原型', 'プライム・フォーム', 'prime form'), t('从 0 开始、往左最紧凑', '0 から始まり左に詰めた形', 'starts on 0, packed to the left')], [t('音程级向量', '音程クラス・ベクトル', 'interval-class vector'), t('6 位数，数各音程级', '6 桁で各音程クラスを数える', 'six digits counting each interval class')]],
        hint: t('标准顺序像"原位"；原型是整个集合类的名字。', 'ノーマル・オーダーは「基本形」、プライム・フォームはセット・クラス全体の名前。', 'Normal order is like root position; prime form names the whole set class.'),
        explain: t('标准顺序写一个具体集合；原型命名集合类；向量总结它含有的音程。', 'ノーマル・オーダーは具体的なセット、プライム・フォームはセット・クラスの名前、ベクトルは含まれる音程のまとめ。', 'Normal order writes one set; prime form names its class; the vector summarises its intervals.') },
      { type: 'choice', ref: 'omt2e-ic-vector',
        prompt: t('任何三音集合的音程级向量，6 个数字加起来是？', '3 音セットの音程ベクトルの 6 桁を足すと？', 'The six digits of any trichord’s interval vector add up to…'),
        options: ['3', '6', '10'], answer: 0,
        hint: t('三个音两两配对有几对？', '3 音を 2 つずつ組むと何組？', 'How many pairs can three notes make?'),
        explain: t('三个音有 3 对，所以总和是 3；四音集合 6 对，五音集合 10 对。', '3 音で 3 組なので合計 3。4 音は 6、5 音は 10。', 'Three notes make 3 pairs, so the total is 3; tetrachords make 6 and pentachords 10.') },
    ],
  },
  {
    id: 'collections', section: 'modern', feature: 'posttonal', icon: '1-3',
    title: t('二十世纪的音集', '20 世紀の音の集まり', 'Twentieth-century collections'),
    blurb: t('五声、全音、八声、六声与 acoustic 音集；梅西安的有限移位调式', '五音・全音・八音・六音・アコースティック、メシアンの移調の限られた旋法', 'Pentatonic, whole-tone, octatonic, hexatonic and acoustic; Messiaen’s modes'),
    cards: [
      { type: 'guide', ref: ['omt2e-collections', 'wiki-messiaen-modes'], demo: { play: [[60], [61], [64], [65], [68], [69], [72]] },
        title: t('用"台阶模式"造音阶', '「段差のパターン」で音階を作る', 'Building scales from step patterns'),
        steps: [
          t('二十世纪很多作曲家喜欢几种特别的音集：五声音集（钢琴黑键；也能由五个纯五度叠出来；台阶 2–2–3–2–3）、全音音集、八声音集（全音半音交替）。', '20 世紀の作曲家が好んだ音の集まり：五音音集（ピアノの黒鍵、完全 5 度を積んでも作れる、段差 2–2–3–2–3）、全音音集、八音音集（全音と半音が交互）。', 'Many 20th-century composers favoured special collections: pentatonic (the black keys; also a stack of fifths; steps 2–2–3–2–3), whole-tone, and octatonic (alternating whole and half steps).'),
          t('六声音集按 1–3–1–3–1–3 的半音数排列。听：C D♭ E F A♭ A。', '六音音集は半音数 1–3–1–3–1–3 で並びます。聴いて：C D♭ E F A♭ A。', 'The hexatonic collection follows 1–3–1–3–1–3 semitones. Listen: C D♭ E F A♭ A.'),
          t('acoustic 音集来自泛音列最低的几个音程：像大调，但第 4 音升高、第 7 音降低——也就是 Lydian dominant。', 'アコースティック音集は倍音列の低い音程から：長音階に似て第 4 音を上げ第 7 音を下げたもの、つまりリディアン・ドミナント。', 'The acoustic collection comes from the lowest intervals of the overtone series: like major but with a raised 4th and lowered 7th — the Lydian dominant.'),
          t('梅西安的"有限移位调式"：不能移出 12 个不同版本的音阶。全音音阶（只有 2 个版本）和八声音阶（3 个版本）都在其中。', 'メシアンの「移調の限られた旋法」：12 通りの異なる移高ができない音階。全音音階（2 通り）や八音音階（3 通り）もその仲間。', 'Messiaen’s modes of limited transposition can’t be transposed into 12 distinct versions; the whole-tone (2 versions) and octatonic (3 versions) scales are among them.'),
        ] },
      { type: 'match', ref: 'omt2e-collections',
        prompt: t('音集 ↔ 台阶（半音数）', '音の集まり ↔ 段差（半音数）', 'Collection ↔ step pattern (semitones)'),
        pairs: [[t('五声', '五音', 'pentatonic'), '2–2–3–2–3'], [t('全音', '全音', 'whole-tone'), '2–2–2–2–2–2'], [t('八声', '八音', 'octatonic'), '2–1–2–1–2–1–2–1'], [t('六声', '六音', 'hexatonic'), '1–3–1–3–1–3']],
        hint: t('数一数每种有几个数字，就是几个音。', '数字の数がそのまま音の数。', 'The number of steps equals the number of notes.'),
        explain: t('五声 5 个音、全音 6 个、八声 8 个、六声 6 个；每组台阶加起来都是 12。', '五音 5・全音 6・八音 8・六音 6 音。どれも段差を足すと 12。', 'Pentatonic 5 notes, whole-tone 6, octatonic 8, hexatonic 6; every pattern sums to 12.') },
      { type: 'choice', ref: 'omt2e-collections',
        prompt: t('钢琴上的五个黑键组成哪种音集？', 'ピアノの 5 つの黒鍵はどの音集？', 'The five black keys of a piano form which collection?'),
        options: [t('五声音集', '五音音集', 'pentatonic'), t('全音音集', '全音音集', 'whole-tone'), t('六声音集', '六音音集', 'hexatonic')], answer: 0,
        hint: t('五个音。', '5 音。', 'Five notes.'),
        explain: t('黑键 C♯ D♯ F♯ G♯ A♯ 就是一个五声音集，也能看成五个纯五度叠出来的音。', '黒鍵 C♯ D♯ F♯ G♯ A♯ は五音音集で、完全 5 度を積んだ音とも見られます。', 'The black keys C♯ D♯ F♯ G♯ A♯ are a pentatonic collection — also a stack of perfect fifths.') },
      { type: 'choice', ref: 'omt2e-collections', audio: { notes: [60, 62, 64, 66, 67, 69, 70, 72], mode: 'melody' },
        prompt: t('听：C D E F♯ G A B♭，这是哪种音集？', '聴いて：C D E F♯ G A B♭ はどの音集？', 'Listen: C D E F♯ G A B♭ is which collection?'),
        options: [t('acoustic 音集', 'アコースティック音集', 'acoustic'), t('全音音集', '全音音集', 'whole-tone'), t('八声音集', '八音音集', 'octatonic')], answer: 0,
        hint: t('像大调，但升 4、降 7。', '長音階に似て ♯4・♭7。', 'Like major but with ♯4 and ♭7.'),
        explain: t('acoustic 音集和泛音列最低的几个泛音大致对应。', 'アコースティック音集は倍音列の低い倍音とほぼ対応します。', 'The acoustic collection roughly matches the lowest partials of the harmonic series.') },
      { type: 'choice', ref: 'wiki-messiaen-modes',
        prompt: t('"有限移位调式"是什么意思？', '「移調の限られた旋法」とは？', 'What does “mode of limited transposition” mean?'),
        options: [t('移不出 12 个不同的版本', '12 通りの異なる移高ができない', 'it can’t be transposed into 12 different versions'), t('只能在一个调里用', '1 つの調でしか使えない', 'it can only be used in one key'), t('只有 5 个音', '5 音しかない', 'it has only five notes')], answer: 0,
        hint: t('全音音阶往上移全音还是同一组音。', '全音音階を全音ずらしても同じ音。', 'Shift whole-tone up a whole step — same notes.'),
        explain: t('这些音阶是对称的，移几步就回到原来那组音，所以版本有限。', '対称なので数歩ずらすと元の音に戻り、種類が限られます。', 'They are symmetric: a few shifts bring back the same notes, so versions are limited.') },
    ],
  },
  {
    id: 'twelvetone', section: 'modern', feature: 'posttonal', icon: 'P0',
    title: t('十二音音乐', '12 音音楽', 'Twelve-tone music'),
    blurb: t('序列、四种变形与 P0 的两种命名法', '音列・4 つの変形・P0 の 2 つの呼び方', 'Rows, four transformations and two ways to name P0'),
    cards: [
      { type: 'guide', ref: ['omt2e-twelve-tone', 'omt2e-row-naming'],
        title: t('十二个音，人人平等', '12 の音はみな平等', 'Twelve notes, all equal'),
        steps: [
          t('十二音作曲大致平均地使用全部 12 个音级，所以通常不去找调、主音这类调性元素。', '12 音技法は 12 のピッチクラスをほぼ均等に使うので、ふつう調や主音のような調性の要素を探しません。', 'Twelve-tone composition uses all twelve pitch classes roughly equally, so it usually isn’t right to look for a key or tonic.'),
          t('作曲家常把 12 个音排成一个固定顺序，叫"序列"（row），再用四种方式变化：移位 T、倒影 I、逆行 R、逆行倒影 RI。', '作曲家は 12 音を決まった順に並べた「音列」を使い、移高 T・反行 I・逆行 R・逆反行 RI で変化させます。', 'Composers often fix an order of the twelve — a row — and vary it by transposition (T), inversion (I), retrograde (R) and retrograde inversion (RI).'),
          t('"序列主义"范围更广：把任何音乐要素（音高、时值、力度……）排成顺序都算，并不一定用十二音序列。', '「セリエリズム」はもっと広く、音高・音価・強弱など何であれ順序づけるもので、12 音列を使うとは限りません。', 'Serialism is broader: ordering any musical element — pitch, duration, dynamics — and not every serial piece uses a twelve-tone row.'),
          t('给序列编号有两种习惯：P0 固定从 C 开始（固定零），或 P0 从序列自己的第一个音开始（可动零）。读别人的文章两种都会遇到，自己用就选一种并保持一致。', '音列の番号づけには 2 つの流儀：P0 を C から始める（固定ゼロ）か、音列の最初の音から始める（移動ゼロ）。どちらにも出会うので、自分は 1 つ選んで一貫させること。', 'Rows are labelled two ways: P0 always starts on C (fixed zero), or P0 starts on the row’s own first note (movable zero). Expect both in the literature; pick one and stay consistent.'),
        ] },
      { type: 'match', ref: 'omt2e-twelve-tone',
        prompt: t('变形 ↔ 做法', '変形 ↔ やり方', 'Transformation ↔ what it does'),
        pairs: [['T', t('整体移高或移低', '全体を上下にずらす', 'shift the whole row up or down')], ['I', t('音程方向上下翻转', '音程の上下を反転', 'flip every interval upside down')], ['R', t('从最后一个音倒着走', '最後の音から逆に進む', 'play it backwards')], ['RI', t('先倒影，再倒着走', '反行してから逆に', 'invert it, then play it backwards')]],
        hint: t('R = retrograde（逆行）。', 'R = レトログレード（逆行）。', 'R = retrograde.'),
        explain: t('T 移位、I 倒影、R 逆行、RI 逆行倒影——四种基本变形。', 'T 移高・I 反行・R 逆行・RI 逆反行の 4 つ。', 'T transposes, I inverts, R reverses, RI reverses the inversion.') },
      { type: 'choice', ref: 'omt2e-twelve-tone',
        prompt: t('分析十二音作品时，通常要先找它的调和主音吗？', '12 音作品を分析するとき、まず調と主音を探す？', 'When analysing a twelve-tone piece, should you start by finding its key and tonic?'),
        options: [t('通常不用', 'ふつう探さない', 'Usually not'), t('一定要', '必ず探す', 'Always')], answer: 0,
        hint: t('12 个音大致平均地使用。', '12 音をほぼ均等に使う。', 'All twelve are used about equally.'),
        explain: t('十二音音乐刻意平均使用所有音级，一般不适合找调性中心。', '12 音音楽はすべてのピッチクラスを意図的に均等に使うので、調の中心を探すのはふつう不適切。', 'Twelve-tone music deliberately spreads all pitch classes evenly, so looking for a tonal centre usually doesn’t fit.') },
      { type: 'choice', ref: 'omt2e-twelve-tone',
        prompt: t('"序列主义"和"十二音作曲"是同一回事吗？', '「セリエリズム」と「12 音技法」は同じ？', 'Are “serialism” and “twelve-tone composition” the same thing?'),
        options: [t('不完全是：序列主义范围更广', '同じではない：セリエリズムのほうが広い', 'Not quite: serialism is broader'), t('完全相同', 'まったく同じ', 'Exactly the same')], answer: 0,
        hint: t('时值、力度也可以排成序列。', '音価や強弱も順序づけられる。', 'Durations and dynamics can be serialised too.'),
        explain: t('序列主义指给任何要素排顺序；十二音作曲专指以 12 个音级的排列为基础的音乐。', 'セリエリズムはあらゆる要素の順序づけ、12 音技法は 12 のピッチクラスの並びに基づく音楽。', 'Serialism orders any element; twelve-tone composition specifically builds on orderings of the twelve pitch classes.') },
      { type: 'choice', ref: 'omt2e-row-naming',
        prompt: t('"固定零"的命名法里，P0 从哪个音开始？', '「固定ゼロ」の呼び方で P0 はどこから？', 'Under “fixed zero”, P0 starts on…'),
        options: ['C', t('序列的第一个音', '音列の最初の音', 'the row’s first note'), t('最低的音', 'いちばん低い音', 'the lowest note')], answer: 0,
        hint: t('C = 0。', 'C = 0。', 'C = 0.'),
        explain: t('固定零：P0 总是从 C 开始；可动零：P0 从序列本身的第一个音开始。', '固定ゼロ：P0 はいつも C から。移動ゼロ：音列自身の最初の音から。', 'Fixed zero: P0 always starts on C; movable zero: P0 starts on the row’s own first note.') },
    ],
  },
  {
    id: 'microharmony', section: 'modern', feature: 'micro', icon: '11/9',
    title: t('微分音和声：中立三和弦与质数极限', '微分音の和声：中立三和音と素数リミット', 'Microtonal harmony: neutral triads and prime limits'),
    blurb: t('不大不小的三和弦；按最大质数给纯律音程分类', '長でも短でもない三和音、最大の素数で純正音程を分類', 'A triad neither major nor minor; sorting just intervals by their largest prime'),
    cards: [
      { type: 'guide', ref: ['wiki-neutral-third', 'wiki-limit', 'hf-intervals'], tool: { feature: 'micro' }, demo: { play: [[60, 64, 67], [60, 63, 67], [60, 63.5, 67]] },
        title: t('在大三度和小三度之间', '長 3 度と短 3 度の間', 'Between the major and minor third'),
        steps: [
          t('中立三度比小三度宽、比大三度窄：24 平均里是 350 音分，纯律里常取 11:9（约 347.41 音分），它和大三度、小三度都差约四分之一音。', '中立 3 度は短 3 度より広く長 3 度より狭い：24 平均で 350 セント、純正では 11:9（約 347.41 セント）。長・短 3 度からそれぞれ約四分音離れる。', 'A neutral third is wider than minor and narrower than major: 350 cents in 24-TET, often 11:9 (about 347.41 cents) in just intonation — roughly a quarter tone from each.'),
          t('两个中立三度叠成的三和弦既不大也不小：C、E 降四分之一音（E½♭）、G。十二平均律里弹不出来，24 平均、31 平均里有。听：大三、小三、中立三和弦。', '中立 3 度を 2 つ重ねた三和音は長でも短でもない：C・四分音低い E（E½♭）・G。12 平均律では弾けず、24 平均や 31 平均にはある。聴いて：長三・短三・中立三和音。', 'Two neutral thirds make a triad that is neither major nor minor: C, E a quarter tone flat (E½♭), G. It isn’t in 12-tone equal temperament but exists in 24- and 31-TET. Listen: major, minor, neutral.'),
          t('纯律音程可以按频率比里出现的最大质数分类，叫质数极限（prime limit，Harry Partch 提出）：只用 2、3 是 3-limit，用到 5 是 5-limit，用到 7 是 7-limit（septimal），用到 11 是 11-limit（undecimal）。11:9 属于 11-limit，标准名称是 undecimal neutral third。', '純正音程は比に出てくる最大の素数で分類できる。これを素数リミット（prime limit、Harry Partch が提唱）という：2・3 だけなら 3-limit、5 まで使えば 5-limit、7 なら 7-limit（septimal）、11 なら 11-limit（undecimal）。11:9 は 11-limit で、標準名は undecimal neutral third。', 'Just intervals can be sorted by the largest prime in their ratio — the prime limit, a term coined by Harry Partch: only 2 and 3 is 3-limit, using 5 is 5-limit, 7 is 7-limit (septimal), 11 is 11-limit (undecimal). 11:9 is 11-limit; its standard name is the undecimal neutral third.'),
        ] },
      { type: 'choice', ref: 'wiki-neutral-third', audio: { notes: [60, 63.5, 67], mode: 'harmonic' },
        prompt: t('听：C、E½♭、G。这个三和弦是？', '聴いて：C・E½♭・G。この三和音は？', 'Listen: C, E½♭, G. This triad is…'),
        options: [t('中立三和弦', '中立三和音', 'a neutral triad'), t('大三和弦', '長三和音', 'a major triad'), t('小三和弦', '短三和音', 'a minor triad')], answer: 0,
        hint: t('三音正好在大小三度中间。', '3 度がちょうど長短の中間。', 'The third sits right between major and minor.'),
        explain: t('两个约 350 音分的中立三度叠成，既不大也不小。', '約 350 セントの中立 3 度 2 つで、長でも短でもない。', 'Two neutral thirds of about 350 cents: neither major nor minor.') },
      { type: 'choice', ref: ['wiki-neutral-third', 'gann-ji'],
        prompt: t('纯律的中立三度 11:9 大约多少音分？', '純正の中立 3 度 11:9 は約何セント？', 'About how many cents is the just neutral third 11:9?'),
        options: ['347', '386', '316'], answer: 0,
        hint: t('在 316（小三度 6:5）和 386（大三度 5:4）中间。', '316（短 3 度 6:5）と 386（長 3 度 5:4）の間。', 'Between 316 (6:5) and 386 (5:4).'),
        explain: t('11:9 ≈ 347.41 音分；24 平均的中立三度是 350 音分，两者听起来几乎分不出来。', '11:9 ≈ 347.41 セント、24 平均は 350 セントでほとんど区別できない。', '11:9 ≈ 347.41 cents; 24-TET’s neutral third is 350, nearly indistinguishable.') },
      { type: 'match', ref: 'hf-intervals',
        prompt: t('频率比 ↔ 标准音程名（Huygens-Fokker 音程表）', '比 ↔ 標準の音程名（Huygens-Fokker の音程表）', 'Ratio ↔ standard interval name (Huygens-Fokker list)'),
        pairs: [['3/2', t('perfect fifth（纯五度）', 'perfect fifth（完全 5 度）', 'perfect fifth')], ['5/4', t('major third（大三度）', 'major third（長 3 度）', 'major third')], ['7/4', t('harmonic seventh（泛音七度）', 'harmonic seventh（ハーモニック・セブンス）', 'harmonic seventh')], ['11/9', t('undecimal neutral third（十一限中立三度）', 'undecimal neutral third（11 リミットの中立 3 度）', 'undecimal neutral third')]],
        hint: t('3-limit、5-limit、7-limit、11-limit 各一个。', '3・5・7・11-limit から 1 つずつ。', 'One each from the 3-, 5-, 7- and 11-limit.'),
        explain: t('3/2 = perfect fifth，5/4 = major third，7/4 = harmonic seventh（第 7 泛音），11/9 = undecimal neutral third。', '3/2 = perfect fifth、5/4 = major third、7/4 = harmonic seventh（第 7 倍音）、11/9 = undecimal neutral third。', '3/2 = perfect fifth, 5/4 = major third, 7/4 = harmonic seventh (the 7th harmonic), 11/9 = undecimal neutral third.') },
      { type: 'choice', ref: ['wiki-limit', 'hf-intervals'],
        prompt: t('7/4 属于哪个质数极限？', '7/4 はどの素数リミット？', 'Which prime limit is 7/4?'),
        options: ['7-limit', '5-limit', '11-limit', '3-limit'], answer: 0,
        hint: t('看比里最大的质数。', '比の中の最大の素数。', 'Look at the largest prime in the ratio.'),
        explain: t('最大质数是 7，所以是 7-limit（septimal）；7/4 的标准名称是 harmonic seventh。', '最大の素数は 7 なので 7-limit（septimal）。7/4 の標準名は harmonic seventh。', 'Its largest prime is 7, so it is 7-limit (septimal); 7/4 is called the harmonic seventh.') },
    ],
  },
];

// 关卡顺序（从简到难）
const ORDER = ['posttonal', 'pitchclass', 'collections', 'setclass', 'twelvetone', 'micro', 'microharmony'];
export const UNITS = ORDER.map((id) => {
  const unit = ALL.find((u) => u.id === id);
  if (!unit) throw new Error(`unknown unit ${id}`);
  return unit;
});
if (UNITS.length !== ALL.length) throw new Error('every unit must appear in ORDER');
