// 学习页题目的补充：三个选项的选择题加第 4 个选项（干扰项——都是错的，其中少数是一眼就能看出的玩笑答案），
// 不到四对的连线题补成四对真实的配对（每一对都能连对，必要时同时改写题干）。
// 按题目内容（中文题干 + 选项 / 配对）的哈希对应：题目改了，这里就要重新补（learn_content.test.mjs 会检查）。
// 新配对用到的知识点都来自同一关已经引用的出处（见各题的 ref 与解析）。
const t = (zh, ja, en) => ({ zh, ja, en });

/** 题目的内容键：选择题看题干 + 选项，连线题看题干 + 配对（只取中文） */
export function decoyKey(card) {
  const zh = (v) => (typeof v === 'string' ? v : v?.zh ?? '');
  const core = card.type === 'match' ? `${zh(card.prompt)}|${card.pairs.map(([a, b]) => `${zh(a)}=${zh(b)}`).join('|')}` : `${zh(card.prompt)}|${card.options.map(zh).join('|')}`;
  let h = 5381; for (let i = 0; i < core.length; i += 1) h = ((h * 33) ^ core.charCodeAt(i)) >>> 0;
  return `d${h.toString(36)}`;
}

/** 选择题的第 4 个选项（错误答案） */
export const EXTRA_OPTIONS = {
  dc3dxub: 'D♯',
  d1vdun9v: 'D',
  dybiowl: t('黑键 F♯', '黒鍵 F♯', 'the black key F♯'),
  d1gyvf32: 'E – F',
  dccfeng: 'A',
  d1h68nbw: t('黑键 A♭', '黒鍵 A♭', 'the black key A♭'),
  d15wgd1e: t('高音喇叭谱号', 'ツイーター記号', 'tweeter clef'),
  d1tcvzzq: 'C2',
  d15bol6: 'A3',
  d1odr8v9: 'E4',
  dlykms6: t('为了让谱子看起来更花哨', '楽譜を派手に見せるため', 'to make the score look fancier'),
  d9d5h43: 'C6',
  d14d73mv: t('1.5 个四分音符', '4 分音符 1 つ半', '1.5 quarter notes'),
  d1etn3k6: '8',
  dkh6l9w: '5',
  d1tyi9bd: '8',
  d1sqbegh: t('附点', '付点', 'a dot'),
  dhzray6: t('演奏 3 遍', '3 回演奏する', 'play it 3 times'),
  d2awm32: '6',
  d19qywba: '4',
  d10ogaq8: '6',
  dut92pd: t('3/4 是复拍子，6/8 是单拍子', '3/4 が複合拍子、6/8 が単純拍子', '3/4 is compound, 6/8 is simple'),
  dht51xo: t('节拍调制', 'メトリック・モジュレーション', 'metric modulation'),
  d6iiza2: t('切分', 'シンコペーション', 'syncopation'),
  dwvck5v: t('小二度', '短 2 度', 'minor second'),
  dux59j5: t('四度', '4 度', 'fourth'),
  d1qwtrfg: 'D',
  dsqsba2: t('A 商调式', 'A 商調式', 'A Shang mode'),
  d1o3wbq4: t('G 商调式', 'G 商調式', 'G Shang mode'),
  dp5enob: 'A',
  dl5ug0s: t('布鲁斯音阶', 'ブルース・スケール', 'a blues scale'),
  d110wwrs: 'G A B C D',
  d16gg1o9: 'G',
  d163a7ai: 'E♯',
  dtq6zzc: t('G 大调', 'G 長調', 'G major'),
  d1yd7s22: t('F 大调', 'F 長調', 'F major'),
  d1rh30xn: '3',
  d738vu: 'B',
  d68dyrd: 'G♭',
  dmslf7o: t('第 2 个音降低了半音', '第 2 音が半音下がる', 'The 2nd note is lowered'),
  d8p0ugt: t('A 小调', 'A 短調', 'A minor'),
  d1x0m3pq: t('F♯ 小调', 'F♯ 短調', 'F♯ minor'),
  d6qbbdq: t('中音', '上中音', 'mediant'),
  do19kag: 'G B♭ D',
  dwo0eim: t('小三度', '短 3 度', 'a minor third'),
  dgr3x3n: t('增五度', '増 5 度', 'augmented fifth'),
  duhqg13: t('大十度', '長 10 度', 'a major tenth'),
  d1mssw9j: t('大六度', '長 6 度', 'major sixth'),
  d1rjexcq: t('小十度', '短 10 度', 'a minor 10th'),
  d1gac29s: 'Mixolydian',
  dnu9wld: 'Phrygian',
  d10pay90: 'A♭',
  d97ptdn: t('第 7 个音', '第 7 音', 'the 7th'),
  d8bbg9j: t('支声', 'ヘテロフォニー', 'heterophony'),
  dvpd8zv: t('单声部', 'モノフォニー', 'monophony'),
  d195om94: t('支声', 'ヘテロフォニー', 'heterophony'),
  d12wg7nq: t('单声部', 'モノフォニー', 'monophony'),
  dn0d2fm: t('支声', 'ヘテロフォニー', 'heterophony'),
  dl2aig6: t('复调', 'ポリフォニー', 'polyphony'),
  d12rs5fw: t('主调', 'ホモフォニー', 'homophony'),
  d75o2r5: t('所有声部同度齐唱同一条旋律', '全声部がユニゾンで同じ旋律', 'all sing one tune in unison'),
  d1bd56ul: t('乐谱纸摸起来的手感', '楽譜の紙の手ざわり', 'how the sheet-music paper feels'),
  d1bsy7td: t('支声', 'ヘテロフォニー', 'heterophony'),
  d2bbwbl: t('支声', 'ヘテロフォニー', 'heterophony'),
  d2hzbyh: t('增三和弦', '増三和音', 'augmented'),
  d1minvjv: t('小三和弦', '短三和音', 'minor'),
  d1sjfu90: 'E G♯ C♯',
  dp6c8f: 'IV',
  d43u3h: t('减七', '減七', 'diminished 7th'),
  d12f6035: t('根音', '根音', 'the root'),
  d96wq4d: 'Gdim7',
  d1pwt3sq: t('第三转位', '第 3 転回形', 'third inversion'),
  dh1vjm6: 'G',
  db0wb1h: t('第三转位', '第 3 転回形', 'third inversion'),
  d3c1srq: '7',
  d17bezd0: t('Am 的第二转位', 'Am の第 2 転回形', 'Am in second inversion'),
  dt38xer: t('小三和弦 + 大七度', '短三和音 + 長 7 度', 'minor triad + major seventh'),
  dhbo9zg: t('作曲家写错了，划掉就行', '作曲家の書き間違い、消せばいい', 'a typo — just cross it out'),
  d1lnz0pb: t('根音', '根音', 'the root'),
  dq0jbom: 'B♭',
  di4nlko: t('Cadd9 没有五音', 'Cadd9 には 5 度がない', 'Cadd9 has no fifth'),
  d1gm4y2n: t('因为它还没想好', 'まだ決めかねているから', 'It hasn’t made up its mind yet'),
  d179sjsi: t('Cadd9 没有根音', 'Cadd9 には根音がない', 'Cadd9 has no root'),
  dr8q6b7: 'E♭',
  d15dgta3: 'E',
  d177em18: 'D F A',
  d1twojbk: t('没有根音', '根音がない', 'it has no root'),
  d1fn1x8s: 'Em7',
  df4m3vx: 'C E♭ G♭ D',
  dh5zsx4: t('有没有七音', '7 度の有無', 'whether there is a seventh'),
  d12qh1cs: 'A C E',
  d1padlye: t('因为吉他手每天都擦琴弦', 'ギタリストが毎日弦を拭いているから', 'because guitarists polish their strings daily'),
  d1l6404m: t('增三和弦', '増三和音', 'an augmented chord'),
  d1cdi2sm: t('两个八度', '2 オクターヴ', 'two octaves'),
  d9xixra: t('和弦七音', '和音の第 7 音', 'the chordal seventh'),
  dew3d6w: t('一定更小声', '必ず音量が小さい', 'is always quieter'),
  djfmb0w: t('女中音和男高音同度', 'アルトとテノールがユニゾン', 'alto and tenor are in unison'),
  d1tp812x: 'C',
  dj9ukyi: t('一个都不能省，四个音都要弹', 'どれも省けない、4 音とも弾く', 'none — all four notes must stay'),
  djgba2h: t('E 小三和弦', 'E の短三和音', 'E minor'),
  dex0oof: t('减七和弦', '減七', 'diminished seventh'),
  df5kn16: 'V7',
  dn9jnp5: 'vi7',
  dv2iycr: t('属七和弦的第三转位', '属七の第 3 転回形', 'a dominant seventh in third inversion'),
  dyv9igr: 'V6',
  d1nqrrdj: 'V6/4',
  d1qbgn0e: t('指挥站的位置', '指揮者の立ち位置', 'where the conductor stands'),
  d1difphd: t('G 大三和弦第二转位', 'G 長三和音の第 2 転回', 'G major in second inversion'),
  d1mh11tc: t('G 和弦第一转位', 'G の第 1 転回形', 'G in first inversion'),
  dhquhnh: t('C 和弦第一转位', 'C の第 1 転回形', 'C in first inversion'),
  d7ddvib: t('F 和弦第二转位', 'F の第 2 転回形', 'F in second inversion'),
  dw5erlh: t('G7 的第三转位', 'G7 の第 3 転回形', 'G7 in third inversion'),
  d94xa39: t('整个和弦升高半音', '和音全体を半音上げる', 'raise the whole chord a half step'),
  dkurwvn: t('六度要弹得更响', '6 度を強く弾く', 'play the sixth louder'),
  ddjchn2: t('变格终止', '変格終止', 'plagal cadence'),
  d15ivcoz: t('V–I 里的 I 必须是第一转位', 'V–I の I が第 1 転回形であること', 'the I must be in first inversion'),
  doa5fgu: t('因为 I 那边有好吃的', 'I のほうにおやつがあるから', 'because I has snacks'),
  dkmlvof: 'ii6 – V – IV',
  d1mlysud: t('第三转位', '第 3 転回形', 'third inversion'),
  dducixt: 'D – T – PD – T',
  dscay1v: t('构成阻碍终止', '偽終止を作る', 'makes a deceptive cadence'),
  d1tirmme: t('只能用作全曲的第一个和弦', '曲の最初の和音にしか使えない', 'can only be the very first chord'),
  d8tb1b5: t('半终止', '半終止', 'half'),
  d1c6rf1s: t('阻碍终止', '偽終止', 'a deceptive cadence'),
  dar28ha: t('变格终止', '変格終止', 'a plagal cadence'),
  dd4zb2a: t('阻碍终止', '偽終止', 'a deceptive cadence'),
  dfc198v: t('变格终止', '変格終止', 'plagal'),
  d1w9y707: 'A – G',
  ddjkuwl: 'D',
  djwb8qm: t('休息（大家喝口水）', '休憩（みんなで水を飲む）', 'a break (everyone sips water)'),
  d14z74jk: t('属七和弦 V7', '属七 V7', 'the dominant seventh V7'),
  d1ypofrs: t('C 低音，上方 E 和 G', 'ベース C、上に E と G', 'C in the bass, with E and G above'),
  d5jp9u2: t('一定都是属七和弦', '必ず 2 つとも属七', 'they must both be dominant sevenths'),
  d1oizq00: t('只有那不勒斯和弦', 'ナポリの和音だけ', 'only the Neapolitan'),
  d3xo5hb: 'I6/4',
  dzit7ru: t('琶音四六', '分散の四六', 'an arpeggiated 6/4'),
  dp2cejv: t('标成 N6', 'N6 と書く', 'labelled N6'),
  d1c8a6sx: t('跳到八度', 'オクターヴへ跳ぶ', 'it leaps to the octave'),
  d1c2aoo: t('琶音四六', '分散の四六', 'arpeggiated'),
  dpvnb09: 'A B C D',
  dcxy8x4: t('全场起立鼓掌', '総立ちの拍手', 'a standing ovation'),
  d1ppo5r3: t('四部', '4 部', 'four-part'),
  d6zqgqs: '4',
  dtuqwk7: t('作曲家的生日', '作曲家の誕生日', 'the composer’s birthday'),
  d16zjoyc: t('间奏曲', '間奏曲', 'intermezzo'),
  d1tu2cko: t('乐章', '楽章', 'movement'),
  d2q247k: t('段落', '部分', 'section'),
  d1gnhd0w: t('回旋曲式', 'ロンド形式', 'rondo'),
  dob9v1a: t('属调的属调', '属調の属調', 'the dominant of the dominant'),
  d11n6ogl: t('主部 + 插部', '主部 + 挿入部', 'refrain + episode'),
  d9wayi9: t('三部曲式', '三部形式', 'ternary form'),
  d23xyy2: t('因为要反复练习才能弹好', '繰り返し練習しないと弾けないから', 'because you have to practise them over and over'),
  dfmojzy: t('电子噪音音乐', '電子ノイズ音楽', 'electronic noise music'),
  d1mpil2c: t('奏鸣曲式', 'ソナタ形式', 'sonata form'),
  djz2p4k: t('只能用打击乐演奏', '打楽器だけで演奏する', 'played on percussion only'),
  d5mftpr: t('再现二部曲式', '回帰二部形式', 'rounded binary'),
  dbk54p1: t('呈示部', '提示部', 'exposition'),
  d1ayfc3c: t('两个主题必须由不同乐器演奏', '2 つの主題は別の楽器で演奏しなければならない', 'they must be played by different instruments'),
  d1qadyx6: t('"五点二"，一种音量', '「5.2」という音量', '“five point two”, a volume level'),
  dmtsxb: t('B 减三和弦（B D F）', 'B の減三和音（B D F）', 'B diminished (B D F)'),
  dd07gp0: t('重升记号', 'ダブルシャープ', 'double sharps'),
  d1dqzm8v: t('数一数小节线', '小節線を数える', 'Count the bar lines'),
  d1353lm1: 'C♯',
  ddn9bgt: t('六级和弦弹五遍', 'vi を 5 回弾く', '“play vi five times”'),
  dnwbmh8: t('B♭（两个调里都没有）', 'B♭（どちらの調にもない）', 'B♭ (in neither key)'),
  d1rjvc97: t('离调只会出现在小调', '一時的転調は短調だけ', 'tonicization happens only in minor'),
  d1tt8bwe: t('大调向属调借', '長調が属調から借りる', 'major borrowing from the dominant key'),
  d1v3afuf: t('演奏速度', '演奏の速さ', 'the tempo'),
  d4vhn7a: t('那不勒斯和弦', 'ナポリの和音', 'the Neapolitan'),
  d100t1ka: 'F A C♯',
  d5klhem: t('终止四六', '終止の四六', 'a cadential 6/4'),
  d2bmovj: t('一定是写错了', '必ず書き間違い', 'it must be a misprint'),
  dqidlut: t('A♭ 到 B♭，F♯ 到 E', 'A♭ → B♭、F♯ → E', 'A♭ to B♭, F♯ to E'),
  davpabv: t('那不勒斯六和弦', 'ナポリの六', 'the Neapolitan sixth'),
  d1flocxq: 'F',
  d1uot46q: t('CTo7 总是当终止式里的属和弦用', 'CTo7 はいつも終止のドミナント', 'the CTo7 always acts as a cadential dominant'),
  d1j5dreg: t('鼓手的独奏', 'ドラムのソロ', 'the drum solo'),
  dgdngaz: t('因为 ii 的音比 IV 多', 'ii のほうが音が多いから', 'because ii has more notes'),
  djtgxmy: t('E♭，三个降号', 'E♭、フラット 3 つ', 'E♭, three flats'),
  d14537rw: t('a 小调', 'a 短調', 'A minor'),
  doi6opo: t('原地不动', 'その場にとどまる', 'it stays put'),
  dc0ctq3: 'D',
  d86uy6w: t('大二度', '長 2 度', 'a major second'),
  dm8o267: t('Mixolydian 轴', 'ミクソリディア軸', 'the Mixolydian axis'),
  d1i3aapw: t('三个音都往上半音', '3 音とも半音上がる', 'all three move up a half step'),
  d1fbuci9: '3',
  d1u4frwq: t('L（C ↔ Em）', 'L（C ↔ Em）', 'L (C ↔ Em)'),
  dvhz7cm: '12',
  d1a7otbf: t('五声音阶', '五音音階', 'pentatonic'),
  drvu77o: t('全音音阶', '全音音階', 'whole-tone'),
  d1dc73mx: t('因为它太好听了，舍不得用', '美しすぎてもったいないから', 'it is too beautiful to use up'),
  dsdlqp4: t('只用减三和弦', '減三和音だけ', 'it uses only diminished triads'),
  d49yi84: t('小七和弦', '短七の和音', 'the minor seventh'),
  d18gqw4v: 'B♭',
  d1j51oyk: 'E',
  dpn6otn: t('低两个八度', '2 オクターヴ低い', 'two octaves lower'),
  d1la30it: 'C7',
  d1kih4pt: t('C 大调', 'C 長調', 'C major'),
  d1te9waw: t('C 大调', 'C 長調', 'C major'),
  dmof2xb: 'E–A',
  d1wxw42n: 'D',
  d1kcs43i: t('第 2 品', '2 フレット', 'fret 2'),
  dpjcqlj: 'F',
  d11azcop: 'A',
  d1a7iy1k: 'C',
  d4u1hbg: t('先现音', '先取音', 'anticipation'),
  d104melx: t('持续音', '保続音', 'pedal tone'),
  dm1pzdb: t('先现音', '先取音', 'an anticipation'),
  dp3yloe: t('延留音', '掛留音', 'a suspension'),
  d3kn1k7: t('持续音', '保続音', 'pedal tone'),
  duxkjmx: t('持续音', '保続音', 'pedal tone'),
  dkncbi9: t('只出现在休止符上', '休符の上だけ', 'only on rests'),
  d1dy3z9r: t('先现音', '先取音', 'an anticipation'),
  d1lnlljj: t('经过音', '経過音', 'passing tone'),
  d1oyzzhd: t('持续音', '保続音', 'a pedal tone'),
  d1o9lliu: t('五度', '5 度', 'the fifth'),
  d1awx6td: t('倚音', '倚音', 'an appoggiatura'),
  d18qgjpl: t('上行延留音的不协和音更响', '逆掛留の不協和音のほうが大きい', 'the retardation’s dissonance is louder'),
  d1g46wkj: t('最后一个音', '最後の音', 'the last note'),
  d2hizks: t('只在最后一小节', '最後の小節だけ', 'only in the last bar'),
  dnrocs1: t('看心情', '気分しだい', 'depends on the mood'),
  d1top1h0: t('先停一拍，再跳进到达', '1 拍休んでから跳躍で', 'after a one-beat rest, by leap'),
  dijnkq0: t('越多越好', '多いほど良い', 'the more the better'),
  d17h9bez: t('导音', '導音', 'the leading tone'),
  d9rrhpe: t('fa（F）', 'fa（F）', 'fa (F)'),
  dupah1v: t('两个声部同时休止', '2 声が同時に休む', 'both voices resting'),
  d8pfqt: t('先现音', '先取音', 'anticipation'),
  du8zvpb: '3–4, 6–7',
  d1nr0h9x: t('先现音', '先取音', 'anticipation'),
  de0snxk: t('因为作曲家嫌五度太空', '作曲家が 5 度は空っぽだと嫌うから', 'because composers find fifths too empty'),
  dn7usei: t('第 1 拍', '1 拍目', 'beat 1'),
  d1ooj9w5: t('因为九度太难唱了', '9 度は歌いにくすぎるから', 'because ninths are too hard to sing'),
  d4llf6g: t('反向', '反行', 'contrary'),
  d18cmu9h: t('让学生少睡一会儿', '生徒を寝かせないため', 'to keep students from sleeping'),
  d5q9q0h: '4',
  d1gzp4tb: t('全部弹成十六分音符', '全部 16 分音符で弾く', 'all played as sixteenths'),
  d1281jhe: t('第 3 拍', '3 拍目', 'beat 3'),
  dnd085l: t('只在散板里', '散板の中だけ', 'only in free rhythm'),
  d13kcnn6: t('一个二分音符', '2 分音符 1 つ', 'one half note'),
  dnttev: t('因为三连音的"3"太难写', '「3」の字が書きにくいから', 'because the “3” is too hard to write'),
  d1utlpqg: '1:2',
  d13ht1l0: t('一种调号', '調号の一種', 'a kind of key signature'),
  d1utn5ig: t('音量突然变大', '音量が急に大きくなる', 'the volume suddenly jumps'),
  dq1t2ut: 'vi',
  d1wfl59s: 'C F A',
  d1n5nqgg: t('第 5 小节', '5 小節目', 'bar 5'),
  dbsy5wt: 'Cmaj7',
  d1wqy6cf: 'Thelonious Monk',
  d7zt3o7: t('只用一个和弦', 'コード 1 つだけ', 'uses only one chord'),
  d1s172vg: t('全音音阶', '全音音階', 'whole-tone scale'),
  d18ud571: 'aaaa',
  dr0bm74: t('减七和弦', '減七の和音', 'diminished seventh'),
  d7ip5rr: 'C',
  d1bojnp8: t('乐队在调音', 'バンドがチューニング中', 'the band is tuning'),
  d5229am: 'dim7',
  d84onvu: t('F 大调', 'F 長調', 'F major'),
  dj4memu: 'Am7',
  dlt4gra: t('往上到 E', 'E へ上がる', 'up to E'),
  d1obgm17: t('终止四六', '終止の四六', 'cadential 6/4'),
  d18tk5j0: 'D Lydian',
  d1aw3t12: 'D',
  d1bsoi8d: 'Am7 → Dm7',
  dsv02wg: t('乐手换了一身衣服', '奏者が服を着替えた', 'the players changed outfits'),
  dfoskix: 'E',
  d1at6v3t: t('A Dorian', 'A ドリア', 'A Dorian'),
  d1y4q37n: t('只有自然小调', '自然短音階だけ', 'natural minor only'),
  d1ko3z4i: t('导音以外的所有音', '導音以外の全部', 'everything except the leading tone'),
  dq8wzca: t('C 升高八度', 'C をオクターヴ上げる', 'C rises an octave'),
  d13bbhai: t('三度', '3 度', 'third'),
  d17ud7p8: t('减七和弦', '減七', 'diminished seventh'),
  d2o352h: '♭9, ♯9, ♭13',
  d1tgeubp: t('什么都不弹，休息', '何も弾かず休む', 'nothing — it rests'),
  drzfhn: t('经过音', '経過音', 'passing tones'),
  dxjjmej: 'A Lydian',
  d152ubui: 'F Locrian',
  d1u7qgs7: t('它的名字太长了', '名前が長すぎる', 'its name is too long'),
  d1d510n8: t('Schoenberg 的十二音技法', 'シェーンベルクの 12 音技法', 'Schoenberg’s twelve-tone method'),
  d1sb6ypy: t('让听众睡着', '聴衆を眠らせる', 'sends the audience to sleep'),
  d1yrogxc: 'C D E♭ F♯ G A B♭',
  d8cih1l: t('F 爵士小调', 'F ジャズ・マイナー', 'F jazz minor'),
  d1g3dkv9: 'Whole-tone',
  d18btafs: t('E 爵士小调', 'E ジャズ・マイナー', 'E jazz minor'),
  dy54yux: t('B 爵士小调', 'B ジャズ・マイナー', 'B jazz minor'),
  dcts99b: t('第 3 音升高', '第 3 音が上がる', 'a raised 3rd'),
  d89qp0k: t('第 1 和第 2 音之间', '第 1 音と第 2 音の間', 'between the 1st and 2nd'),
  d1uk7xtj: 'Lydian',
  d1lbsm3l: 'ii',
  d1nqi3tr: t('G 和声小调', 'G 和声短音階', 'G harmonic minor'),
  d1n6197s: 'Lydian',
  d1yahuj1: 'Palestrina',
  d1yqy93l: '5',
  dcxlbvn: t('小三和弦', '短三和音', 'minor'),
  db0pph6: t('因为它听起来像下雨', '雨みたいに聞こえるから', 'Because it sounds like rain'),
  dvdqc5o: t('C E G♯ 与 E♭ G B', 'C E G♯ と E♭ G B', 'C E G♯ and E♭ G B'),
  d1gnkhia: t('缺 B♭', 'B♭ がない', 'B♭ is missing'),
  d19plcdl: t('布鲁斯音阶', 'ブルース・スケール', 'the blues scale'),
  duwvpv8: t('因为它是星期三发明的', '水曜日に発明されたから', 'because it was invented on a Wednesday'),
  d1ysyg6: t('多了一个全音', '全音が 1 つ多い', 'an extra whole step'),
  da3a6zf: '3',
  d1xjebed: t('为了让乐手多赚一个音的钱', '奏者が 1 音分多く稼ぐため', 'so players get paid for one more note'),
  dox0s2s: t('C 和 D 之间', 'C と D の間', 'between C and D'),
  d19wujsn: t('第 5 音', '第 5 音', 'the 5th'),
  d6bv7fx: t('升高第 2 和第 6 音', '第 2 と第 6 音を上げる', 'raise the 2nd and 6th'),
  d1i7v1il: t('利底亚半音阶', 'リディアン・クロマチック', 'the Lydian chromatic scale'),
  d3povt4: 'A♭7',
  d7az982: t('借用和弦', '借用和音', 'a borrowed chord'),
  d24c1rg: t('一个阻碍终止', '偽終止', 'a deceptive cadence'),
  d1xye6he: 'Dm7 – G7 – F',
  d1u5fs52: t('因为 B♭ 带降号，降号什么都能代替', 'B♭ はフラットで、フラットは何でも代われるから', 'because B♭ is a flat, and flats can replace anything'),
  d9nab31: 'C, E♭, F♯',
  dt2ssf2: 'C D♭ G',
  d1axcf72: 'E',
  dgj8xhv: t('布鲁斯音阶', 'ブルース・スケール', 'the blues scale'),
  d19qg85o: 'G B D♯ F',
  d1yicirw: 'Gblk',
  ds0dz3h: t('五声音阶', '五声音階', 'the pentatonic'),
  d1mk0vjf: 'i (A C E)',
  d8csvg3: 'D F♯ A C',
  d1rj4tua: t('负和声要倒着弹', '負の和声は逆再生で弾く', 'negative harmony is played backwards'),
  dyg4f6w: 'Johann Sebastian Bach',
  d31ah0g: 'Am',
  d6oh1a7: 'C Locrian',
  d1rpb93n: t('发明了电吉他', 'エレキギターを発明した', 'inventing the electric guitar'),
  d1mh4tcq: 'vertical',
  d1whmrz1: t('第 5 和第 6 个', '第 5 と第 6', 'the 5th and 6th'),
  d11fo3h4: 'D Lydian',
  d1scf72a: 'B',
  dkxxljd: t('大三度', '長 3 度', 'a major third'),
  d11ot40e: '24',
  droy5hw: 'E Lydian',
  d132jpyf: t('五声音阶', '五声音階', 'pentatonic'),
  d1xm7yz3: t('只能用变宫', '変宮だけ', 'only biangong'),
  d1dd1der: t('变奏', '変奏', 'a variation'),
  d1golfhv: t('五声音阶', '五声音階', 'pentatonic'),
  d1ppd4dd: t('十二音技法', '12 音技法', 'twelve-tone technique'),
  d1w6irww: t('《三国演义》', '『三国志演義』', 'Romance of the Three Kingdoms'),
  d1ibdd4h: t('给乐器上漆', '楽器にニスを塗る', 'varnishing instruments'),
  d12kp3ze: 'Ravi Shankar',
  d8pb3xr: 'Kalyan',
  d1mqsj5d: 'Ga, Dha',
  d1mxsy9x: t('因为 32 是 Bhatkhande 的幸运数字', '32 がバートカンデのラッキーナンバーだから', 'because 32 was Bhatkhande’s lucky number'),
  d1u9596r: t('Ga 降低', 'Ga が低い', 'a lowered Ga'),
  dy1ow3r: 'dastgah',
  d1aifqjp: t('三个半音', '半音 3 つ', 'three half steps'),
  duowv15: t('Lydian', 'リディアン', 'Lydian'),
  dlngyei: t('它只能在早上演奏', '朝にしか演奏できない', 'it may only be played in the morning'),
  d1etwxam: '7',
  d1xh7hrl: t('Saba 或 Bayati', 'サバかバヤーティー', 'Saba or Bayati'),
  dpma3ay: 'Segâh',
  d4ryuhl: '17',
  d14jiczf: t('一个全音', '全音', 'a whole step'),
  d1ecz67d: t('因为小提琴比较贵', 'ヴァイオリンのほうが高価だから', 'because the violin costs more'),
  diyf5jc: t('乐器走音了', '楽器の調律がずれた', 'the instrument being out of tune'),
  dvm3yfe: t('大提琴', 'チェロ', 'cello'),
  d1n79o3z: 'Dorian',
  d1u1krlk: t('大三度', '長 3 度', 'major thirds'),
  d1f7jwdz: t('三全音', '三全音', 'tritones'),
  d1jqm0bx: t('作曲家很中庸的性格', '作曲家の中庸な性格', 'the composer’s moderate personality'),
  d1niw6t4: t('只在唐朝', '唐の時代だけ', 'only in the Tang dynasty'),
  d88e6cn: t('因为钢琴调音师特别努力', '調律師ががんばったから', 'because piano tuners try very hard'),
  d82nkeb: '720',
  d1fbwg2n: t('狐狸五度', 'キツネの 5 度', 'the fox fifth'),
  dd61boe: t('约 100 音分', '約 100 セント', 'about 100 cents'),
  d15j4jmn: 'E–B, B–F♯',
  d1foq5x7: '1850',
  d1y3epj: '12',
  d12mrt6q: '3',
  duv5hg9: '[0, 3, 7]',
  d1wpqig0: t('乐谱的封面', '楽譜の表紙', 'the cover of the score'),
  dyuzbj1: t('不是，一个是黑键一个是白键', 'いいえ、片方は黒鍵で片方は白鍵', 'No, one is a black key and one is white'),
  d10bhab1: '13',
  d1do2gcf: '14',
  dcnhto3: t('有序音级音程', '順序付き音級音程', 'ordered pitch-class interval'),
  d1sj2dji: t('八声音集', '八音音集', 'octatonic'),
  d1x91hp6: t('五声音集', '五音音集', 'pentatonic'),
  d21tqax: t('作曲家只能用它写有限的几首', '作曲家が限られた数しか書けない', 'composers may write only a few pieces in it'),
  dqdx55g: t('acoustic 音阶', 'アコースティック音階', 'the acoustic scale'),
  dwfdjwd: t('八声音集', '八音音集', 'octatonic'),
  da1ufgk: 'Locrian',
  danaeba: '{0, 5, 9}',
  dk3yohj: '12',
  dho0kvo: t('最高的音', 'いちばん高い音', 'the highest note'),
  ds1pjlw: 'G',
  d1dphgtg: 'P8',
  df4mcjb: t('浪漫乐派的歌剧作曲家', 'ロマン派のオペラ作曲家', 'Romantic opera composers'),
  d1l02i2g: '12',
  d19d8h2k: '100',
  ddn7oda: t('八度', 'オクターヴ', 'an octave'),
  did7pw6: '702',
  dp4wi3z: t('因为 11 和 9 都是吉利数字', '11 と 9 が縁起のいい数だから', 'because 11 and 9 are lucky numbers'),
  d1bjhxzl: t('增三和弦', '増三和音', 'an augmented triad'),
  d290o4q: '400',
  dgj79lm: '4',
  d60lfef: '6',
  da1hx7y: '6',
  drt2eff: t('复节奏只能用打击乐', 'ポリリズムは打楽器だけ', 'polyrhythm is for percussion only'),
  d1he3lrk: t('换一种乐器', '楽器を替える', 'switch instruments'),
  dtdgos9: '120',
  dufce0k: t('不变的音量', '変わらない音量', 'an unchanged volume'),
  d1lnoeqy: t('消失了', '消える', 'they disappear'),
  d11931e8: '100',
  dr0ng4t: '180',
  d17dukk0: t('同一段旋律反复两遍', '同じ旋律を 2 回繰り返す', 'the same tune played twice'),
  db1x8fw: t('因为乐手忘了告诉观众', '奏者が観客に言い忘れたから', 'because the players forgot to tell the audience'),
  dkpj6v: t('一个全音符', '全音符 1 つ', 'one whole note'),
  dp2az0t: t('作曲家的电话号码', '作曲家の電話番号', 'the composer’s phone number'),
  d1mqq3c4: t('一个附点四分音符', '付点 4 分音符 1 つ', 'one dotted quarter note'),
  db2ay9n: t('五线谱 → 点格 → 斜线记号', '五線譜 → ドット → スラッシュ記号', 'staff notation → dot grid → slashes'),
  d1qkyq9a: t('下 下 上', '下 下 上', 'down, down, up'),
  d1okyea: 'ti',
  d17kg88k: t('一直重听同一个音', '同じ音だけを聴き続ける', 'keep replaying a single note'),
  dnpy9ps: '6',
  dxk9ar7: t('阻碍终止', '偽終止', 'a deceptive cadence'),
  ds5ysfx: t('演奏者的表情', '奏者の表情', 'the player’s facial expression'),
  d15vrtvx: 'I',
  d1o259rn: 'IV – V – ii',
  dwnjv2r: t('没有功能，只是噪音', '働きはない、ただの雑音', 'no function — just noise'),
  d1bnvz7f: t('Phrygian 终止', 'フリギア終止', 'phrygian cadence'),
  d6ehyvw: t('le（降低的第六级）', 'le（下がった第 6 音）', 'le (lowered 6th)'),
  dldhd8v: t('音量', '音量', 'the volume'),
  d1pbse6m: t('lydian cadence', 'リディアン・カデンツ', 'the lydian cadence'),
  d1wfl9od: t('因为它太好听，没人想停', '気持ちよすぎて誰も止めたくないから', 'because it feels too good to stop'),
  d1ui0qiv: t('它用了升高的导音 ti', '上がった導音 ti を使う', 'it uses the raised leading tone ti'),
  dg0te05: 'Locrian',
  dx2bom: t('第二级', '第 2 音', 'the 2nd'),
  d1mtq8d8: t('构成阻碍终止', '偽終止を作る', 'form a deceptive cadence'),
  dkb14ig: t('aeolian cadence', 'エオリアン・カデンツ', 'the aeolian cadence'),
  d110p425: t('Phrygian 的 ♭II', 'フリギアの ♭II', 'Phrygian ♭II'),
  d2xtrlm: t('ra', 'ra', 'ra'),
  d1mbl94i: 'Phrygian',
  d14fqy3h: 'Phrygian',
  d1ysffu0: 'Mixolydian',
  d6ltswj: t('是它的两倍大', 'その 2 倍の大きさ', 'it is twice as big'),
  d26bmxw: '5',
  d1idue50: '12',
  d156d32v: t('D 小五声', 'D マイナー', 'D minor pentatonic'),
  d5ffk4o: t('乐器的颜色', '楽器の色', 'the colour of the instruments'),
  dadmrez: t('三音和七音', '3 音と 7 音', 'third and seventh'),
  d1xqtp4t: t('会变成十二音序列', '12 音列になる', 'it turns into a twelve-tone row'),
  d1fkiz79: t('re 与 ri', 're と ri', 're and ri'),
  dw9i8kg: t('因为吉他手只会一个指型', 'ギタリストが 1 つの形しか知らないから', 'because guitarists know only one shape'),
  ds3qdfl: t('鼓点', 'ドラムのパターン', 'the drum pattern'),
  djtdol7: t('D–G 与 C–A', 'D–G と C–A', 'D–G and C–A'),
  dwoggo7: 'ii – vi – I – V',
  dkqmood: t('是十二音音乐', '12 音音楽', 'it is twelve-tone music'),
  d7c9q2u: t('阻碍终止', '偽終止', 'a deceptive cadence'),
  d1vwmmku: t('悲怆终止', '悲愴終止', 'a pathetic cadence'),
  d13e9o8v: t('正格终止的一种新叫法', '正格終止の新しい呼び名', 'a new name for the authentic cadence'),
  d115vaev: t('第七级 → 第一级', '第 7 音 → 第 1 音', 'from degree 7 to 1'),
  d191gwgq: 'VI',
  dwelwvo: t('因为它是用古琴弹的', '古琴で弾くから', 'because it is played on a guqin'),
  d17pt1dy: 'A C E♭',
  d6epi1g: t('乐曲速度的快慢', '曲の速い・遅い', 'fast or slow tempos'),
  d77bjno: t('快终止 / 慢终止', '速い終止 / 遅い終止', 'fast / slow cadences'),
  d7f3dln: 'i–iv–♭VII–III',
  d1q2mrgk: t('只在婚礼上用', '結婚式でだけ使う', 'only at weddings'),
  d5p3vks: t('阻碍终止', '偽終止', 'deceptive cadence'),
  d1ezoao7: 'Dm7♭5 – G7 – Cm7',
  ducjxgn: 'm7 – m7 – m7',
  d8lrnzy: t('阻碍终止', '偽終止', 'a deceptive cadence'),
  dwou5w8: t('乐队转身面向观众', 'バンドが観客のほうを向く', 'the band turning to face the audience'),
  d1h09dwv: t('只是一个写错的音', 'ただの書き間違い', 'just a wrong note'),
  d1smpwvn: t('同向', '並行（同方向）', 'similar'),
  dpxam6i: t('平行', '平行', 'parallel'),
  dy41jcy: t('平行八度', '平行 8 度', 'parallel octaves'),
  dhxd5s: t('只有在三拍子里才算', '3 拍子のときだけ', 'only in triple meter'),
  d1s76x1k: t('因为太难唱了', '歌うのが難しすぎるから', 'because they are too hard to sing'),
  d14quku8: t('声部交叉', '声部交差', 'voice crossing'),
  dhrqhlk: t('导音的解决', '導音の解決', 'a leading-tone resolution'),
  dk9d1ec: t('因为会让乐谱变长', '楽譜が長くなるから', 'because the score gets longer'),
  dwogie1: 'D',
  d1k9zonb: t('往下跳八度', 'オクターヴ下へ跳ぶ', 'leap down an octave'),
  d5b920b: t('可以，只要唱得小声', '小さい声ならよい', 'yes, if sung quietly'),
  d1fdbhxp: t('保持不动，变成下一个和弦的根音', 'そのまま次の和音の根音になる', 'stay put as the next chord’s root'),
  d11eaooj: 'D',
  d412jcv: 'B♭ (♭VII)',
  d2tegdf: 'C G Em F',
  dyvhl74: 'royal road',
  d1d3j6tf: t('因为 ii 是减三和弦', 'ii が減三和音だから', 'because ii is diminished'),
  dkx0yrv: t('逆行', '逆行', 'retrograde'),
  dfv7wz6: t('因为它有四个和弦', 'コードが 4 つあるから', 'because it has four chords'),
  dbn8bla: 'vi–IV–I–V',
  d33wgys: t('变格终止', '変格終止', 'a plagal cadence'),
  d16gyos1: 'royal road',
  dvglcpm: 'I',
  d11zv7kb: 'F G C Am',
  dhtmro5: 'iii',
  d1aezm73: t('一条半音阶', '半音階', 'a chromatic scale'),
  d13rbwg8: t('终止四六', '終止の四六', 'a cadential 6/4'),
  dhaae3q: t('re → ri（第二级）', 're → ri（第 2 音）', 're → ri (degree 2)'),
  dhlbw2x: '♯V',
  d7uw829: t('后一个是前一个的倒影', '後のほうが前の反行形', 'the second is the inversion of the first'),
  dx4bk00: t('只在大调歌曲的副歌里', '長調の曲のサビだけ', 'only in choruses of major-key songs'),
  d1f1jxuy: 'Dm7♭5',
  d1w8iawk: 'C7 Fm7 Gmaj7',
  d1qgaoro: t('Fm–F–C（顺序反过来）', 'Fm–F–C（逆順）', 'Fm–F–C (reversed)'),
  d193m4zi: 'C–G♭',
  d19hg2by: t('鼓手加了一个过门', 'ドラマーがフィルを入れた', 'the drummer plays a fill'),
  dqblt0i: t('Coltrane 进行', 'コルトレーン・チェンジ', 'Coltrane changes'),
  d1cb780y: t('第六遍反复', '6 回目の繰り返し', 'the sixth repeat'),
  d1ql9pi2: t('每个音都弹八遍', '各音を 8 回弾く', 'play every note eight times'),
  d1fn4hoh: t('全部用增三和弦', 'すべて増三和音', 'augmented triads throughout'),
  d13mxu59: t('第三和第六级', '第 3 と第 6 音', 'degrees 3 and 6'),
  d1pzu4s3: t('第二转位', '第 2 転回形', 'second inversion'),
  d1h33hiw: t('4/2（G7 第三转位）', '4/2（G7 の第 3 転回形）', '4/2 (G7 in third inversion)'),
  d1ftusnc: t('只在全曲第一个和弦', '曲の最初の和音だけ', 'only on the very first chord'),
  d1iqtpse: t('让低音停下来', 'バスを止める', 'makes the bass stop'),
  dadpcpv: '6/4',
  d1kjdp2x: t('因为纯五度太好听了', '完全 5 度がきれいすぎるから', 'because perfect fifths sound too good'),
  d16p2n3i: t('半音模进只能用在小调', '半音階的反復進行は短調だけ', 'chromatic sequences only work in minor'),
  d108g3hx: t('变成了五声音阶', '五声音階になる', 'it becomes pentatonic'),
  dm102im: t('E 与 G', 'E と G', 'E and G'),
  d17wv75f: t('B 减三和弦', 'B の減三和音', 'B diminished'),
  dfx3vt7: t('只有两个：上行版和下行版', '上行版と下行版の 2 つだけ', 'exactly two: one up, one down'),
  dpekesb: 'IV7',
  d1uxsauw: t('因为它印在乐谱最上方', '楽譜のいちばん上に印刷されるから', 'because it is printed at the top'),
  dz9tnuu: 'iii',
  d1jtfiq7: t('是，F♯ 是 C 大三和弦的五音', 'はい、F♯ は C 長三和音の 5 度', 'yes — F♯ is the fifth of C major'),
  d1mp5yh5: 'A C E G',
  dsvyi92: t('D 大三和弦第二转位', 'D 長三和音の第 2 転回形', 'D major in second inversion'),
  d8q4ons: t('先把 6 擦掉', 'まず 6 を消す', 'erase the 6 first'),
  dccfdkp: t('Cadd9 多了一个 F', 'Cadd9 には F もある', 'Cadd9 also has an F'),
  dphss20: 'G C E',
  dwdkqk5: 'C4sus7',
  d1av2xbv: 'F/E',
  d1os9lpd: 'I6',
  d7jls7j: 'iii / v',
  d1rthqrd: t('一整首交响曲', '交響曲 1 曲まるごと', 'an entire symphony'),
  d1u958uv: t('把乐谱挪到另一页', '楽譜を別のページへ', 'moving it to another page'),
  d15xykxu: 'D F A',
  d11rb7p6: t('全曲的第一个音', '曲の最初の音', 'the very first note'),
  di2mtl5: t('每个音的音名', '各音の音名', 'each note’s letter name'),
  d78buh1: 'C E G',
  dk2z6g0: 'C E D',
  d216t89: t('格里高利圣咏', 'グレゴリオ聖歌', 'Gregorian chant'),
  d17217fp: t('四个全音符', '全音符 4 つ', 'four whole notes'),
  doy7ts8: t('乐器', '楽器', 'the instrument'),
  d1rcop0m: t('改变动机的音量', '動機の音量を変える', 'changing its volume'),
  d24dype: t('先现音', '先取音', 'an anticipation'),
  dvadjjg: t('乐谱纸', '楽譜の紙', 'the sheet music'),
  d1omaewg: t('十二小节布鲁斯', '12 小節ブルース', 'a 12-bar blues'),
  d1vchxp2: t('全曲最后的尾声', '曲の最後のコーダ', 'the final coda'),
  d19abvu: t('为了让歌手休息', '歌手を休ませるため', 'to rest the singer'),
  d1ef0yzg: t('模进', '反復進行', 'sequence'),
  d5vc5ir: t('八小节', '8 小節', 'eight bars'),
  dh89gqh: t('展开部分一个音也没有', '展開部分に音がひとつもない', 'a continuation with no notes at all'),
  dgrk88: t('终止 → 再终止 → 结束', '終止 → また終止 → 終わり', 'cadence → cadence → end'),
  dxxefq6: t('紧缩', '圧縮', 'compression'),
  d1qnxp3e: t('算，而且是最长的那种扩充', 'はい、しかも最長の拡張', 'yes, the longest kind'),
  dx6tdff: t('紧缩', '圧縮', 'compression'),
  doo17vw: t('全曲开始前调音的时候', '曲の前のチューニング中', 'before the piece, during tuning'),
  d9j8q1j: t('停在 ii 像尾声', 'ii で止まりコーダ', 'on ii — like a coda'),
  du4rc2f: t('换了乐器', '楽器が変わる', 'the instrument changes'),
  de9tgsa: t('前句第一拍之前', '前楽節の 1 拍目の前', 'before the antecedent’s first beat'),
  d16pvv5s: t('一段鼓独奏', 'ドラム・ソロ', 'a drum solo'),
  d1ywx31h: t('因为太远了，乐手走不过去', '遠すぎて奏者がたどり着けないから', 'because it is too far for the players to walk'),
  d1tzgi4s: t('借用和弦（调式混合）', '借用和音（モーダル・ミクスチャー）', 'borrowed chords (mixture)'),
  domxvng: t('它只用在布鲁斯里', 'ブルースだけで使う', 'it is only used in the blues'),
  d1ndpm9n: t('为了让和弦变成大三和弦', '長三和音にするため', 'to make the chord major'),
  d1eeds7o: t('是，因为出现了升号', 'はい、シャープが出るから', 'yes, because sharps appear'),
  dnx1kyt: 'B♭',
  dsfy09d: 'A',
  d7i16rh: t('D♭', 'D♭', 'D♭'),
  d1hsdo98: t('减七和弦', '減七', 'a diminished seventh'),
  den9d1t: t('跳到 G', 'G へ跳ぶ', 'leaps to G'),
  d39xekh: t('因为乐谱上的升降号变少了', '楽譜の臨時記号が減るから', 'because the score has fewer accidentals'),
  dckyrkw: '3',
  d1d66ohr: t('三全音', '三全音', 'a tritone'),
  dxyliro: 'G',
  dh7tto6: t('蟹行卡农', '蟹行カノン', 'a crab canon'),
  d4t8lcv: t('谁先唱、谁请客', '誰が先に歌い、誰がおごるか', 'who sings first and who buys dinner'),
  d1qx1zb3: t('一次事故', '事故', 'an accident'),
  dn2bvh9: t('因为第二遍歌词不一样', '2 番の歌詞が違うから', 'because the second verse has different lyrics'),
  d153gjm1: t('纯八度', '完全 8 度', 'a perfect octave'),
  d14jakmx: t('扩大卡农', '拡大カノン', 'an augmentation canon'),
  dedgev9: 'G–A',
  dpao4bx: t('二度', '2 度', 'the second'),
  dhnz6q3: t('往上五度', '5 度上がる', 'rises a fifth'),
  d26vcs: t('缩小卡农', '縮小カノン', 'a diminution canon'),
  d1sd48k2: t('逆行卡农', '逆行カノン', 'a retrograde canon'),
  dpvsp6: t('两个声部都在休息', '2 声部とも休んでいる', 'both voices are resting'),
  dffcnue: t('因为那个音会被删掉', 'その音が消されるから', 'because the note gets deleted'),
  dawxcfv: t('检查器坏了', 'チェッカーが壊れた', 'the checker is broken'),
  d9mkfgu: t('减七', '減七', 'diminished sevenths'),
  d1behwpb: t('弗里吉亚半终止', 'フリギア半終止', 'Phrygian half cadences'),
  d446wjx: t('第五小节改成 I', '5 小節目を I に', 'bar 5 becomes I'),
  d1l9urzo: '6',
  dvgnauq: t('每个和弦都加一个三全音替代', 'すべての和音に裏コードを足す', 'by adding a tritone sub to every chord'),
  d1fqm9nr: t('减七', '減七', 'a diminished seventh'),
  d1l6xeah: t('因为 ii–V–I 字母更少', 'ii–V–I のほうが文字が少ないから', 'because ii–V–I has fewer letters'),
  dca3b9s: 'V7 – I7',
  d1usrzz6: 'I – I – I',
  d1dwqzzj: t('第 12 小节之后的尾声', '12 小節目の後のコーダ', 'a coda after bar 12'),
  d1wwaczj: t('一直不停的十六分音符', '止まらない 16 分音符', 'nonstop sixteenth notes'),
  d16ak0ew: 'Emaj7 Amaj7 Dmaj7 Gmaj7',
  d1d2w3ac: t('让鼓手有时间换鼓棒', 'ドラマーがスティックを替える時間', 'gives the drummer time to change sticks'),
  d17wod7q: t('阻碍终止', '偽終止', 'deceptive cadence'),
  d3nz9ob: t('三音', '3 音', 'the third'),
  dfnf7xl: t('D7 的音太低了', 'D7 の音が低すぎる', 'D7 is pitched too low'),
  d1el867e: t('根音', '根音', 'the root'),
  d3tf7a1: t('根音', '根音', 'the root'),
  dhbw51h: t('一直反复地弹它', 'ずっと繰り返して弾く', 'repeat it over and over'),
  d6nuggr: 'T – T – T – T',
  djgsawp: t('阻碍终止', '偽終止', 'a deceptive cadence'),
  denis89: t('七音', '7 音', 'seventh'),
  d1sk9trs: t('B 变成 D♭7 的三音', 'B が D♭7 の 3 音になる', 'B becomes D♭7’s third'),
  dig7w8y: t('因为三全音替代要另外收费', 'トライトーン代理は追加料金だから', 'because tritone subs cost extra'),
  dzez82n: t('只要旋律音是 C 就行', '旋律が C ならいつでも', 'whenever the melody note is C'),
  d3yxasc: 'B♭7',
  d18dy0tw: t('必须先停两小节', 'まず 2 小節休む必要がある', 'it must first rest for two bars'),
  dukcidp: t('一个休止符', '休符', 'a rest'),
  d16rg6tg: t('因为画出来是一个圆', '描くと丸くなるから', 'because it looks like a circle when drawn'),
  d1u2baly: t('小大七', 'マイナー・メジャー・セブンス', 'minor-major sevenths'),
  dgwrnjl: 'D',
  djc0ydm: 'V/IV',
  d2i4cxd: 'V7/vi',
  dryavtx: 'C G Am F',
  djd9pbe: 'V7/IV',
  db1xqe0: 'Em A D G',
  d1ofrb0i: 'I',
  dfoiijz: 'C E♭ A♭ G7',
  d1kgt18u: 'C – C – B',
  d1ezmq1a: 'ii–V–I',
  dcrrs5o: 'vi',
  d1fdudna: t('那不勒斯六和弦', 'ナポリの六', 'a Neapolitan sixth'),
};

/** 连线题补上的真实配对（prompt：配对扩展后题干要跟着改的） */
export const EXTRA_PAIRS = {
  d6h1100: { pairs: [['D♯', 'E♭']] },
  dhbez79: { pairs: [[t('四分休止符', '4 分休符', 'quarter rest'), '1']] },
  dwmm39k: { pairs: [[t('E 大调', 'E 長調', 'E major'), '4']] },
  d1viylt6: { prompt: t('三种小调与关系大调 ↔ 特点', '3 種類の短音階と平行調 ↔ 特徴', 'The three minors and the relative major ↔ what marks them'), pairs: [[t('关系大调', '平行調（長調）', 'relative major'), t('主音比小调主音高小三度', '主音が短調の主音より短 3 度上', 'tonic a minor third above the minor tonic')]] },
  d1rj49yw: { pairs: [['ra', '♭2']] },
  d1dpn3ul: { pairs: [[t('几位乐手同时奏同一曲调、各加装饰', '数人が同じ旋律をそれぞれ装飾して同時に', 'several players ornamenting one tune at once'), t('支声', 'ヘテロフォニー', 'heterophony')]] },
  dgqpecf: { pairs: [[t('减减七', '減減七', 'diminished-diminished seventh'), t('减七和弦', '減七の和音', 'diminished seventh')]] },
  d1q2coww: { prompt: t('C7 和弦（C E G B♭）：最低音 ↔ 转位', 'C7（C E G B♭）：最低音 ↔ 転回形', 'C7 (C E G B♭): lowest note ↔ inversion'), pairs: [['B♭', t('第三转位', '第 3 転回形', 'third inversion')]] },
  d1o89fzv: { pairs: [['F', t('原位', '基本形', 'root position')]] },
  d1ps9wav: { pairs: [['♯11', 'F♯']] },
  dveulol: { prompt: t('数字低音 ↔ 位置', '数字付き低音 ↔ 配置', 'Figures ↔ position'), pairs: [['7', t('七和弦原位', '七の和音の基本形', 'seventh chord, root position')]] },
  d1z00pke: { pairs: [['vii°6', t('属（代替倒置的 V）', '属（転回した V の代わり）', 'dominant (stands in for an inverted V)')]] },
  dcat2rn: { pairs: [[t('终止四六', '終止の四六', 'cadential 6/4'), t('低音是属音，接着解决到 V', 'ベースは属音で、続いて V へ解決', 'bass is the dominant, then resolves to V')]] },
  dqj5szy: { pairs: [[t('琶音四六', '分散の四六', 'arpeggiated 6/4'), t('两边是同一个和弦（低音分解它）', '両側は同じ和音（ベースがそれを分散）', 'the same chord on both sides (bass arpeggiates it)')]] },
  d1y4lyx: { pairs: [[t('乐句', 'フレーズ', 'phrase'), t('乐思', '楽想', 'ideas')]] },
  d1nt8y6g: { pairs: [[t('复乐段', '複楽節', 'compound period'), t('两个句子式组成前句 + 后句', '2 つの文型が前楽句 + 後楽句になる', 'two sentences as antecedent + consequent')]] },
  d11sg0r9: { pairs: [[t('最后（可以没有）', '最後（なくてもよい）', 'at the end (optional)'), t('尾声', 'コーダ', 'coda')]] },
  d9a6j2: { pairs: [[t('调式混合', 'モーダル・ミクスチャー', 'modal mixture'), t('向同主音调借和弦', '同主調から和音を借りる', 'borrow chords from the parallel key')]] },
  d1fs021: { prompt: t('C 调：变化和弦 ↔ 音', 'C 調：変化和音 ↔ 音', 'In C: chromatic chord ↔ notes'), pairs: [[t('那不勒斯', 'ナポリ', 'Neapolitan'), 'D♭ F A♭']] },
  d4odzi3: { pairs: [[t('关系小调（vi = Am）', '平行調（vi = Am）', 'relative minor (vi = Am)'), t('和 C 同一格的内圈', 'C と同じ位置の内側の円', 'the inner ring beside C')]] },
  d14q8jyp: { pairs: [['F♯', t('主轴（C 的对极）', 'トニック軸（C の対極）', 'tonic axis (C’s counterpole)')]] },
  d1nf2gih: { pairs: [['H', 'A♭m']] },
  d1f13bzw: { pairs: [[t('次中音萨克斯', 'テナー・サックス', 'tenor saxophone'), t('低大九度', '長 9 度下', 'a major 9th lower')]] },
  dzid39t: { pairs: [[t('降 B 调单簧管', 'B♭ クラリネット', 'B♭ clarinet'), t('低大二度', '長 2 度下', 'a major 2nd lower')]] },
  d1yiec5u: { pairs: [[t('中提琴', 'ヴィオラ', 'viola'), 'C G D A']] },
  dqarbau: { pairs: [[t('倚音', '倚音', 'appoggiatura'), t('跳进进入、级进离开', '跳躍で入り、順次で離れる', 'leap in, step out')]] },
  d1jfyafl: { pairs: [[t('上行延留音的解决', '逆掛留の解決', 'resolving a retardation'), t('往上一步', '1 歩上へ', 'a step up')]] },
  d181yi5g: { pairs: [[t('十度、十二度', '10 度・12 度', 'tenths, twelfths'), t('复音程：按减去八度后的音程归类', '複音程：オクターヴを引いた音程で分類', 'compound: classed like the interval minus an octave')]] },
  d1vo8r8u: { pairs: [[t('9–8 延留的解决音程', '9–8 掛留の解決の音程', 'resolution interval of a 9–8'), t('八度', '8 度', 'an octave')]] },
  d1rypgh7: { prompt: t('四类对位：说法 ↔ 内容', '第 4 類対位法：項目 ↔ 内容', 'Fourth species: item ↔ what it is'), pairs: [[t('延留音解决的方向', '掛留が解決する向き', 'direction a suspension resolves'), t('往下一步', '1 歩下へ', 'one step down')], [t('两个声部之间的进行', '2 声の間の動き', 'motion between the two voices'), t('斜向进行', '斜行', 'oblique motion')]] },
  d1xdanf0: { pairs: [[t('反拍（backbeat）', 'バックビート', 'backbeat'), t('四拍子里重音放在第 2、4 拍', '4 拍子でアクセントを 2・4 拍目に', 'accents on beats 2 and 4 in four')]] },
  dfrc36c: { pairs: [[t('整整十二小节', '12 小節全体', 'all twelve bars'), t('一段歌词（aab 一轮）', '歌詞 1 番（aab 1 回分）', 'one verse (one round of aab)')]] },
  d14kayeo: { pairs: [['Altered', '♭2, ♭3, ♭4, ♭5, ♭6, ♭7']] },
  d1ntg819: { prompt: t('对称音阶：说法 ↔ 内容', '対称音階：項目 ↔ 内容', 'Symmetric scales: item ↔ answer'), pairs: [[t('全音音阶一共有几种', '全音音階は何種類', 'distinct whole-tone scales'), t('2 种', '2 種類', 'two')], [t('减音阶一共有几种（十二平均律）', '減音階は何種類（12 平均律）', 'distinct diminished scales (12-TET)'), t('3 种', '3 種類', 'three')]] },
  d13d8j4q: { pairs: [[t('和声小调', '和声短音階', 'harmonic minor'), 'C D E♭ F G A♭ B']] },
  d1h54k4n: { pairs: [[t('旋律小调（爵士小调）', '旋律短音階（ジャズ・マイナー）', 'melodic minor (jazz minor)'), t('5 与 6 之间，而且三度是 ♭3', '5 と 6 の間、しかも 3 度は ♭3', 'between 5 and 6, and the third is ♭3')]] },
  dgn3i9x: { pairs: [[t('Lydian 半音阶', 'リディアン・クロマチック・スケール', 'Lydian chromatic scale'), t('Lydian 音阶的终极形式：十二音的音阶', 'リディアン音階の究極の形：12 音の音階', 'the ultimate, twelve-tone form of the Lydian scale')]] },
  dr2lrw3: { prompt: t('音阶 ↔ 五声之外加进来的偏音', '音階 ↔ 五声に加わる偏音', 'Scale ↔ notes added to the five tones'), pairs: [[t('五声音阶', '五声音階', 'pentatonic'), t('不加偏音', '偏音を加えない', 'none added')]] },
  d1io5vli: { prompt: t('七声音阶 ↔ 别名或组成', '七声音階 ↔ 別名や構成', 'Heptatonic scale ↔ other name or make-up'), pairs: [[t('燕乐音阶的组成', '燕楽音階の構成', 'what Yanyue is made of'), t('五声 + 清角 + 闰', '五声 + 清角 + 閏', 'five tones + qingjue + run')]] },
  ddm2wc6: { pairs: [['Bhairav', 'Bhairav']] },
  d1ssdydv: { pairs: [['Nahawand', t('第 5 级（Hijaz 或 Kurd）', '第 5 音（ヒジャーズかクルド）', 'degree 5 (Hijaz or Kurd)')]] },
  dheswzz: { pairs: [[t('音色', '音色', 'timbre'), t('主要由各泛音的强弱比例决定', '主に倍音の強さの比率で決まる', 'set mainly by the relative strengths of the overtones')]] },
  dbktvcv: { pairs: [[t('毕达哥拉斯律', 'ピタゴラス音律', 'Pythagorean tuning'), t('11 个纯五度，最后一个是狼五度', '純正 5 度 11 個、最後がウルフ', 'eleven pure fifths and one wolf')]] },
  d1kf8lze: { pairs: [[t('毕达哥拉斯律', 'ピタゴラス音律', 'Pythagorean'), t('整个音差都堆在一个五度上', 'コンマ全部を 1 つの 5 度に', 'the whole comma in one fifth')]] },
  d1q4jidz: { prompt: t('C4 与下方的 A3：说法 ↔ 数值', 'C4 と下の A3：項目 ↔ 数値', 'C4 and the A3 below: item ↔ number'), pairs: [[t('C4 的音级', 'C4 の音級', 'pitch class of C4'), '0']] },
  dfvecwl: { pairs: [[t('集合级', 'セット・クラス', 'set class'), t('能用移位或倒影互相得到的集合归成一类', '移高や反行で移り合う集合をまとめた類', 'sets related by transposition or inversion, grouped together')]] },
  d18vzurr: { pairs: [[t('一个八度里实际用到的音', '1 オクターヴで実際に使う音', 'notes actually used in an octave'), t('24 个音', '24 音', '24 notes')]] },
  dh0u3r1: { pairs: [['2 : 5', '10']] },
  d1u891gs: { prompt: t('节奏手法 ↔ 结果', 'リズムの手法 ↔ 結果', 'Rhythmic device ↔ result'), pairs: [[t('左手三下、右手两下同时进行', '左手 3 打・右手 2 打を同時に', 'left hand three against right hand two'), t('复节奏', 'ポリリズム', 'a polyrhythm')], [t('拍号一个接一个地换', '拍子を次々に替える', 'switching time signatures one after another'), t('变拍子', '変拍子', 'changing meter')]] },
  d1y8rlr7: { pairs: [['·', t('一个拍点（还没标记）', '拍の点（まだ記入なし）', 'a beat (not yet marked)')]] },
  d1js13m1: { pairs: [[t('E 小五声', 'E マイナー・ペンタトニック', 'E minor pentatonic'), 'E G A B D']] },
  d1fdynpe: { prompt: t('终止式的说法 ↔ 意思', '終止の呼び名 ↔ 意味', 'Cadence term ↔ meaning'), pairs: [[t('悲怆终止', '悲愴終止', 'pathetic cadence'), t('那不勒斯六接正格终止（旧称）', 'ナポリの六から正格終止（旧称）', 'Neapolitan sixth before an authentic cadence (old name)')], [t('皮卡迪三度', 'ピカルディの 3 度', 'Picardy third'), t('小调段落用大三主和弦收尾', '短調の部分を長三の主和音で終える', 'a minor passage ending on a major tonic')]] },
  dih5qms: { pairs: [[t('男高音高过女中音', 'テノールがアルトより高い', 'tenor above alto'), t('声部交叉', '声部交差', 'voice crossing')]] },
  d13hm0bd: { prompt: t('套路 ↔ 特点', '定番進行 ↔ 特徴', 'Schema ↔ feature'), pairs: [[t('王道进行', '王道進行', 'royal road'), 'IV–V–iii–vi']] },
  dd5mia5: { pairs: [[t('F 大调', 'ヘ長調', 'F major'), t('II7（= V7/V）', 'II7（= V7/V）', 'II7 (= V7/V)')]] },
  dhbn37n: { prompt: t('乐段与乐句型：部分 ↔ 说明', '楽段と楽節型：部分 ↔ 説明', 'Periods and sentences: part ↔ description'), pairs: [[t('呈示部分', '提示部分', 'presentation'), t('基本乐思 + 它的重复', '基本楽想 + その反復', 'basic idea + its repetition')], [t('展开部分', '展開部分', 'continuation'), t('碎片化、模进、和声节奏加快', '断片化・反復進行・和声リズムの加速', 'fragmentation, sequence, faster harmonic rhythm')]] },
  dmisfzy: { pairs: [[t('紧缩', '圧縮', 'compression'), t('乐句内部，让乐句变短', 'フレーズ内部で短くする', 'inside, making it shorter')]] },
  d1paq9aj: { pairs: [[t('倒影卡农', '反行カノン', 'inversion canon'), t('答句反向进行', '後続声部が反行する', 'the follower moves in contrary motion')]] },
  d501ox7: { prompt: t('再和声：说法 ↔ 特点', 'リハーモナイズ：項目 ↔ 特徴', 'Reharmonization: item ↔ feature'), pairs: [[t('旋律音和和弦音成小二度', '旋律音と和音の音が短 2 度', 'melody note a minor second from a chord tone'), t('需要解决的摩擦', '解決が必要なぶつかり', 'a clash that needs resolving')]] },
};

/** 给一道题补上第 4 个选项 / 第 4 对 */
export function withDecoys(card) {
  if (card?.type === 'choice' && card.options?.length === 3) {
    const extra = EXTRA_OPTIONS[decoyKey(card)];
    return extra === undefined ? card : { ...card, options: [...card.options, extra] };
  }
  if (card?.type === 'match' && card.pairs?.length < 4) {
    const extra = EXTRA_PAIRS[decoyKey(card)];
    return extra ? { ...card, pairs: [...card.pairs, ...extra.pairs], ...(extra.prompt ? { prompt: extra.prompt } : {}) } : card;
  }
  return card;
}
