// 乐理闯关 · 世界音乐与律学：每张题卡标出依据（ref），只使用 references.js 中已登记、已核实的资料；解析用尽量通俗的话转述这些资料。
// 依据汇总（由 scripts/annotate-learn.mjs 生成）：
//   ref:zhwiki-heptatonic ref:huain-xuangong ref:wiki-thaat ref:wiki-double-harmonic ref:wiki-arabic-maqam
//   ref:maqamworld-jins ref:wiki-harmonic-series ref:wiki-pythagorean ref:wiki-meantone ref:wiki-werckmeister
//   ref:wiki-vallotti
// @refs-end

const t = (zh, ja, en) => ({ zh, ja, en });
const opt = (id, label) => ({ id, label });

const ALL = [
  {
    id: 'world', section: 'world', feature: 'world', icon: '½',
    title: t('木卡姆与四分之一音', 'マカームと四分音', 'Maqam and quarter tones'),
    blurb: t('琴键缝里的音', '鍵盤のすき間の音', 'Notes between the keys'),
    cards: [
      { type: 'guide', ref: 'wiki-arabic-maqam',
        title: t('比半音还小', '半音よりも小さい', 'Smaller than a half step'),
        steps: [
          t('阿拉伯音乐会用到钢琴键缝里的音。记谱时用"四分之一音"：半个半音。', 'アラブ音楽は鍵盤のすき間の音も使います。記譜では「四分音」＝半音の半分。', 'Arabic music uses notes between the piano keys. They are notated as quarter tones: half a half step.'),
          t('不过这只是记谱习惯——真正唱奏时的音高因地区和年代而异。', 'ただしこれは記譜の習慣で、実際の音高は地域や時代で違います。', 'But that is only a notation habit — real intonation varies by region and era.'),
          t('木卡姆由几个小"音组"（jins）拼起来。', 'マカームは小さな「音組」（ジンス）をつなげて作ります。', 'A maqam is built from small note groups called ajnas (singular jins).'),
        ] },
      { type: 'choice', ref: 'wiki-arabic-maqam',
        prompt: t('记谱上的"四分之一音"是多大？', '記譜の「四分音」の大きさは？', 'How big is a notated quarter tone?'),
        options: [t('半个半音', '半音の半分', 'half a half step'), t('一个半音', '半音 1 つ', 'one half step'), t('一个全音', '全音 1 つ', 'one whole step')], answer: 0,
        hint: t('名字里就有答案："四分之一"个全音。', '名前に答え：全音の「4 分の 1」。', 'The name says it: a quarter of a whole step.'),
        explain: t('全音的四分之一 = 半音的一半。', '全音の 4 分の 1 = 半音の半分。', 'A quarter of a whole step = half of a half step.') },
      { type: 'fill', ref: 'maqamworld-jins',
        prompt: t('Jins Rast 的四步（全音记作 1）：1、¾、___、1', 'ジンス・ラストの 4 歩（全音 = 1）：1・¾・___・1', 'Jins Rast’s four steps (whole step = 1): 1, ¾, ___, 1'),
        bank: [opt('3/4', '¾'), opt('1/2', '½'), opt('3/2', '1½')], answer: ['3/4'],
        hint: t('中间两步一样大。', '真ん中の 2 歩は同じ大きさ。', 'The two middle steps are the same size.'),
        explain: t('Rast：1、¾、¾、1——两个"四分之三音"让第三个音落在 E 和 E♭ 之间。', 'ラスト：1・¾・¾・1。2 つの ¾ で第 3 音が E と E♭ の間に。', 'Rast: 1, ¾, ¾, 1 — two three-quarter steps put the third between E and E♭.') },
      { type: 'choice', ref: 'wiki-arabic-maqam',
        prompt: t('演奏时，四分之一音一定是精确的"半个半音"吗？', '演奏では四分音はいつもぴったり半音の半分？', 'In performance, is a quarter tone always exactly half a half step?'),
        options: [t('不一定，因地区和年代而异', 'そうとは限らない。地域や時代で違う', 'Not necessarily — it varies by region and era'), t('一定', '必ずそう', 'Always')], answer: 0,
        hint: t('记谱 ≠ 实际。', '記譜 ≠ 実際。', 'Notation ≠ practice.'),
        explain: t('24 平均只是方便记谱，实际音高会有差别——工具里可以对比 MaqamWorld 的音高。', '24 平均は記譜の便宜で、実際の音高は違います。ツールで MaqamWorld の音高と比べられます。', '24-TET is a notation convenience; real pitches differ — compare with MaqamWorld’s pitches in the tool.') },
      { type: 'choice', ref: 'wiki-thaat',
        prompt: t('印度斯坦音乐的 Bilaval thaat 跟哪个西方音阶一样？', 'ヒンドゥスターニーの Bilaval ターートはどの西洋音階と同じ？', 'Hindustani Bilaval thaat matches which Western scale?'),
        options: [t('大调（Ionian）', '長音階（イオニアン）', 'major (Ionian)'), t('小调', '短音階', 'minor'), t('全音音阶', '全音音階', 'whole-tone')], answer: 0,
        hint: t('它全部用本位音（没有升降）。', 'すべて本位音（変化なし）。', 'It uses only natural notes.'),
        explain: t('Bilaval 的 S R G M P D N 全是本位音，对应 C D E F G A B。', 'Bilaval の S R G M P D N はすべて本位音で C D E F G A B。', 'Bilaval’s S R G M P D N are all natural: C D E F G A B.') },
    ],
  },
  {
    id: 'temperaments', section: 'world', feature: 'temperaments', icon: '≈',
    title: t('律制：怎样给钢琴调音', '音律：ピアノをどう調律する？', 'Temperaments: how to tune a keyboard'),
    blurb: t('纯五度、狼五度与平均律', '純正 5 度・ウルフ・平均律', 'Pure fifths, wolves and equal temperament'),
    cards: [
      { type: 'guide', ref: 'wiki-pythagorean',
        title: t('没法让所有音程都完美', 'すべての音程を完璧にはできない', 'You can’t make every interval perfect'),
        steps: [
          t('最"纯"的五度，两个音的频率比是 3:2。', 'いちばん「純正」な 5 度は、周波数比 3:2。', 'The purest fifth has a 3:2 frequency ratio.'),
          t('如果十二个音全用纯五度来调，到最后会剩下一个特别难听的五度——"狼五度"。', '12 音すべてを純正 5 度で調律すると、最後にひどく濁った 5 度が残ります——「ウルフ」。', 'Tune all twelve notes by pure fifths and one awful fifth is left over: the "wolf".'),
          t('各种律制就是在"哪些音程要纯、哪些让一点"之间做选择。', '音律とは「どの音程を純正にし、どれを譲るか」の選択です。', 'Each temperament chooses which intervals stay pure and which give a little.'),
        ] },
      { type: 'choice', ref: 'wiki-pythagorean',
        prompt: t('毕达哥拉斯律里，用来调音的五度都是？', 'ピタゴラス音律で調律に使う 5 度は？', 'In Pythagorean tuning the fifths used are all…'),
        options: [t('纯五度（3:2）', '純正 5 度（3:2）', 'pure fifths (3:2)'), t('平均律五度', '平均律の 5 度', 'equal-tempered fifths'), t('狼五度', 'ウルフ', 'wolf fifths')], answer: 0,
        hint: t('它追求的就是"纯"。', '目指すのは「純正」。', 'Purity is the whole point.'),
        explain: t('全部用纯五度，结果剩下一个狼五度。', 'すべて純正 5 度。その結果ウルフが 1 つ残ります。', 'All pure fifths — leaving one wolf fifth.') },
      { type: 'choice', ref: 'wiki-meantone',
        prompt: t('四分之一音差中庸全音律把五度稍微缩窄，是为了让什么变纯？', '1/4 コンマ・ミーントーンが 5 度を少し狭くするのは何を純正にするため？', 'Quarter-comma meantone narrows its fifths to make what pure?'),
        options: [t('大三度', '長 3 度', 'major thirds'), t('八度', 'オクターヴ', 'octaves'), t('小二度', '短 2 度', 'minor seconds')], answer: 0,
        hint: t('C G D A E 四个五度连起来……', 'C G D A E の 4 つの 5 度をつなげると……', 'Chain four fifths C G D A E…'),
        explain: t('每个五度缩窄一点，四个五度叠起来 C–E 就成了纯大三度。', '5 度を少しずつ狭めると、4 つ重ねた C–E が純正長 3 度になります。', 'Narrow each fifth slightly and four of them make a pure major third C–E.') },
      { type: 'fill', ref: 'wiki-pythagorean',
        prompt: t('十二平均律里每个五度是 ___ 音分（八度 = 1200 音分）', '12 平均律の 5 度は ___ セント（オクターヴ = 1200 セント）', 'In 12-tone equal temperament each fifth is ___ cents (octave = 1200)'),
        bank: [opt('700', '700'), opt('702', '702'), opt('696', '696')], answer: ['700'],
        hint: t('每个半音 100 音分，五度 7 个半音。', '半音 1 つ 100 セント、5 度は半音 7 つ。', 'Each half step is 100 cents; a fifth is seven half steps.'),
        explain: t('7 × 100 = 700。纯五度约 702，所以平均律的五度只比纯五度窄一点点。', '7 × 100 = 700。純正 5 度は約 702 なので、平均律の 5 度はほんの少し狭いだけ。', '7 × 100 = 700. A pure fifth is about 702, so the tempered fifth is only slightly narrow.') },
    ],
  },
  {
    id: 'heptatonic', section: 'world', feature: 'chinese', icon: '清',
    title: t('中国七声调式与旋宫', '中国の七声旋法と旋宮', 'Chinese seven-tone modes and xuangong'),
    blurb: t('清乐、燕乐、雅乐三种七声音阶；旋相为宫', '清楽・燕楽・雅楽の 3 つの七声音階、旋相為宮', 'Qingyue, Yanyue and Yayue scales; rotating the gong'),
    cards: [
      { type: 'guide', ref: ['zhwiki-heptatonic', 'huain-xuangong'], demo: { keys: [60, 62, 64, 65, 67, 69, 71], play: [[60], [62], [64], [65], [67], [69], [71], [72]] },
        title: t('在五声的"缺口"里各加两个音', '五声の「すき間」に 2 音ずつ加える', 'Fill the gaps of the pentatonic with two more notes'),
        steps: [
          t('七声调式是在五声调式的小三度缺口里加两个"偏音"。以 C 为宫：清角 = F，变徵 = F♯，闰（清羽）= B♭，变宫 = B。', '七声旋法は五声旋法の短 3 度のすき間に 2 つの「偏音」を加えたもの。C を宮とすると：清角 = F、変徵 = F♯、閏（清羽）= B♭、変宮 = B。', 'Seven-tone modes add two “bian” notes into the minor-third gaps of the pentatonic. With C as gong: qingjue = F, bianzhi = F♯, run (qingyu) = B♭, biangong = B.'),
          t('清乐音阶：加清角和变宫（C D E F G A B，点亮的键）；燕乐音阶：加清角和闰（C D E F G A B♭）；雅乐音阶：加变徵和变宫（C D E F♯ G A B）。', '清楽音階：清角と変宮（C D E F G A B、光っている鍵）。燕楽音階：清角と閏（C D E F G A B♭）。雅楽音階：変徵と変宮（C D E F♯ G A B）。', 'Qingyue: add qingjue and biangong (C D E F G A B, the lit keys). Yanyue: add qingjue and run (C D E F G A B♭). Yayue: add bianzhi and biangong (C D E F♯ G A B).'),
          t('加了两个音，五声的基本特点并没变：仍用宫商角徵羽命名（如"清乐宫调式"），主音一般也只用这五个正音，偏音很少当主音。', '2 音増えても五声の性格は変わらず、宮商角徵羽で名づけ（「清楽宮調式」など）、主音もふつうこの 5 つの正音から。偏音が主音になることはまれ。', 'The pentatonic character stays: modes are still named by gong, shang, jue, zhi, yu (e.g. “Qingyue gong mode”), and the tonic is usually one of those five; bian notes rarely serve as tonic.'),
          t('"旋宫"：《礼记·礼运》说"五声六律十二管旋相为宫"——让宫音在十二律上轮转。在同一个宫系统里换调式叫"同宫转调"，换到另一个宫系统叫"异宫转调"。', '「旋宮」：『礼記・礼運』に「五声六律十二管旋りて相い宮と為る」。宮音を十二律の上で回すこと。同じ宮の中で旋法を替えるのが「同宮転調」、別の宮に移るのが「異宮転調」。', 'Xuangong: the Book of Rites says “the five tones, six pitch-pipes and twelve tubes take turns as gong” — the gong rotates through the twelve lü. Changing mode within one gong system is same-gong modulation; moving to another gong system is cross-gong modulation.'),
        ] },
      { type: 'match', ref: 'zhwiki-heptatonic',
        prompt: t('以 C 为宫：偏音 ↔ 音名', 'C を宮として：偏音 ↔ 音名', 'With C as gong: bian note ↔ pitch'),
        pairs: [[t('清角', '清角', 'qingjue'), 'F'], [t('变徵', '変徵', 'bianzhi'), 'F♯'], [t('闰（清羽）', '閏（清羽）', 'run (qingyu)'), 'B♭'], [t('变宫', '変宮', 'biangong'), 'B']],
        hint: t('"清"比正音高半音，"变"比正音低半音。', '「清」は正音の半音上、「変」は正音の半音下。', '“Qing” is a half step above a main tone; “bian” a half step below.'),
        explain: t('清角 = 角（E）上方半音 F；变徵 = 徵（G）下方半音 F♯；清羽 = 羽（A）上方半音 B♭；变宫 = 宫（C）下方半音 B。', '清角 = 角（E）の半音上 F、変徵 = 徵（G）の半音下 F♯、清羽 = 羽（A）の半音上 B♭、変宮 = 宮（C）の半音下 B。', 'Qingjue = a half step above jue (E): F; bianzhi = a half step below zhi (G): F♯; qingyu = above yu (A): B♭; biangong = below gong (C): B.') },
      { type: 'match', ref: 'zhwiki-heptatonic',
        prompt: t('七声音阶 ↔ 加进来的偏音', '七声音階 ↔ 加わる偏音', 'Seven-tone scale ↔ the added bian notes'),
        pairs: [[t('清乐', '清楽', 'Qingyue'), t('清角 + 变宫', '清角 + 変宮', 'qingjue + biangong')], [t('燕乐', '燕楽', 'Yanyue'), t('清角 + 闰', '清角 + 閏', 'qingjue + run')], [t('雅乐', '雅楽', 'Yayue'), t('变徵 + 变宫', '変徵 + 変宮', 'bianzhi + biangong')]],
        hint: t('雅乐又叫"古音阶"，里面有 F♯。', '雅楽は「古音階」とも呼ばれ、F♯ を含む。', 'Yayue, the “ancient scale”, contains F♯.'),
        explain: t('清乐 C D E F G A B；燕乐 C D E F G A B♭；雅乐 C D E F♯ G A B。', '清楽 C D E F G A B、燕楽 C D E F G A B♭、雅楽 C D E F♯ G A B。', 'Qingyue C D E F G A B; Yanyue C D E F G A B♭; Yayue C D E F♯ G A B.') },
      { type: 'choice', ref: 'zhwiki-heptatonic', audio: { notes: [60, 62, 64, 66, 67, 69, 71, 72], mode: 'melody' },
        prompt: t('听：C D E F♯ G A B（C 为宫），这是哪种七声音阶？', '聴いて：C D E F♯ G A B（C が宮）。どの七声音階？', 'Listen: C D E F♯ G A B (C as gong). Which seven-tone scale?'),
        options: [t('雅乐音阶', '雅楽音階', 'Yayue'), t('清乐音阶', '清楽音階', 'Qingyue'), t('燕乐音阶', '燕楽音階', 'Yanyue')], answer: 0,
        hint: t('有变徵（F♯）。', '変徵（F♯）がある。', 'It has bianzhi (F♯).'),
        explain: t('雅乐 = 五声 + 变徵 + 变宫，又叫古音阶、正声音阶。', '雅楽 = 五声 + 変徵 + 変宮。古音階・正声音階とも。', 'Yayue = pentatonic + bianzhi + biangong, also called the ancient or zhengsheng scale.') },
      { type: 'choice', ref: 'zhwiki-heptatonic',
        prompt: t('七声调式的主音一般用哪些音？', '七声旋法の主音はふつうどの音？', 'Which notes usually serve as tonic in a seven-tone mode?'),
        options: [t('宫商角徵羽五个正音', '宮商角徵羽の 5 つの正音', 'the five main tones gong–shang–jue–zhi–yu'), t('两个偏音', '2 つの偏音', 'the two bian notes'), t('任何一个都一样常见', 'どれも同じくらい', 'any of the seven equally')], answer: 0,
        hint: t('偏音很不稳定。', '偏音はとても不安定。', 'Bian notes are very unstable.'),
        explain: t('偏音很少作主音；所以七声调式仍按五声的方法命名，比如"燕乐羽调式"。', '偏音が主音になることはまれ。だから七声旋法も五声と同じく「燕楽羽調式」のように名づけます。', 'Bian notes rarely act as tonic, so seven-tone modes keep pentatonic names like “Yanyue yu mode”.') },
      { type: 'choice', ref: 'huain-xuangong',
        prompt: t('在同一个宫系统里，从宫调式换到羽调式，叫？', '同じ宮の中で宮調式から羽調式へ替えるのは？', 'Moving from gong mode to yu mode within the same gong system is…'),
        options: [t('同宫转调', '同宮転調', 'same-gong modulation'), t('异宫转调', '異宮転調', 'cross-gong modulation'), t('没有转调', '転調ではない', 'not a modulation')], answer: 0,
        hint: t('宫音没变，只换了主音。', '宮は同じで主音だけが替わる。', 'The gong stays; only the tonic changes.'),
        explain: t('同宫：五个音不变、换主音；异宫：宫音本身移到另一律上，音也跟着变了。', '同宮：音はそのまま主音だけ替える。異宮：宮そのものが別の律に移り、音も変わる。', 'Same-gong: same notes, new tonic. Cross-gong: the gong itself moves to another lü, changing the notes.') },
    ],
  },
  {
    id: 'thaat', section: 'world', feature: 'world', icon: 'Sa',
    title: t('印度的十种 thaat', 'インドの 10 のタート', 'India’s ten thaats'),
    blurb: t('给拉格分类的"母音阶"', 'ラーガを分類する「親音階」', 'Parent scales for classifying ragas'),
    cards: [
      { type: 'guide', ref: ['wiki-thaat', 'wiki-double-harmonic'], demo: { play: [[60], [61], [64], [65], [67], [68], [71], [72]] },
        title: t('先分好类，再认拉格', 'まず分類して、ラーガを知る', 'Sort first, then meet the ragas'),
        steps: [
          t('thaat 是北印度（印度斯坦）音乐的"母音阶"。它主要用来给拉格分类，而不是拿来作曲；属于某个 thaat 的拉格不一定用全它的音。', 'タートは北インド（ヒンドゥスターニー）音楽の「親音階」。作曲の道具というより、ラーガを分類するためのもので、あるタートに属するラーガがその音をすべて使うとは限りません。', 'A thaat is a parent scale in North Indian (Hindustani) music. It is mainly for classifying ragas, not for composing, and a raga in a thaat need not use all its notes.'),
          t('现代 thaat 体系由 V. N. Bhatkhande（1860–1936）建立：他整理出 32 种，挑出最重要的 10 种。每个 thaat 都是七声的，以一个代表性拉格命名。', '現代のタート体系は V. N. バートカンデ（1860–1936）が作り、32 種のうち重要な 10 種を選びました。どれも 7 音で、代表的なラーガの名がつきます。', 'The modern system is V. N. Bhatkhande’s (1860–1936): he found 32 and highlighted ten. Every thaat has seven notes and is named after a prominent raga.'),
          t('音名叫 Sa Re Ga Ma Pa Dha Ni，像首调唱名一样，Sa 可以放在任何音高上。', '音名は Sa Re Ga Ma Pa Dha Ni。移動ドのように Sa はどの高さにも置けます。', 'The notes are Sa Re Ga Ma Pa Dha Ni; like movable solfège, Sa can sit on any pitch.'),
          t('有几个 thaat 和西方调式正好同音：Bilawal = Ionian（大调），Kalyan = Lydian，Khamaj = Mixolydian，Kafi = Dorian，Asavari = Aeolian，Bhairavi = Phrygian。Bhairav 则和双和声音阶同音。听：C 上的 Bhairav。', 'いくつかは西洋の旋法と同じ音：ビラーワル = イオニアン、カリヤーン = リディアン、カマージ = ミクソリディアン、カーフィー = ドリアン、アーサーワリー = エオリアン、バイラヴィー = フリジアン。バイラヴはダブル・ハーモニックと同じ。聴いて：C のバイラヴ。', 'Several match Western modes: Bilawal = Ionian (major), Kalyan = Lydian, Khamaj = Mixolydian, Kafi = Dorian, Asavari = Aeolian, Bhairavi = Phrygian. Bhairav matches the double harmonic scale. Listen: Bhairav on C.'),
        ] },
      { type: 'match', ref: 'wiki-thaat',
        prompt: t('thaat ↔ 同音的西方调式', 'タート ↔ 同じ音の西洋旋法', 'Thaat ↔ matching Western mode'),
        pairs: [['Bilawal', 'Ionian'], ['Kalyan', 'Lydian'], ['Kafi', 'Dorian'], ['Bhairavi', 'Phrygian']],
        hint: t('Bilawal 是参考的基本音阶，全用"本位"音。', 'ビラーワルは基準の音階で、すべて本来の音。', 'Bilawal is the reference scale, all natural notes.'),
        explain: t('Bilawal = 大调，Kalyan 升 Ma = Lydian，Kafi = Dorian，Bhairavi = Phrygian。', 'ビラーワル = 長音階、カリヤーン（Ma を上げる）= リディアン、カーフィー = ドリアン、バイラヴィー = フリジアン。', 'Bilawal = major, Kalyan (raised Ma) = Lydian, Kafi = Dorian, Bhairavi = Phrygian.') },
      { type: 'choice', ref: 'wiki-thaat',
        prompt: t('thaat 主要是用来做什么的？', 'タートの主な役割は？', 'What is a thaat mainly for?'),
        options: [t('给拉格分类', 'ラーガを分類する', 'classifying ragas'), t('作曲时规定只能用哪些音', '作曲で使える音を決める', 'dictating which notes a composition may use'), t('调乐器', '楽器の調律', 'tuning instruments')], answer: 0,
        hint: t('属于某个 thaat 的拉格可以少用或多用几个音。', 'あるタートのラーガが音を減らしたり増やしたりしてもよい。', 'A raga in a thaat may omit or add notes.'),
        explain: t('它和西方的"音阶"不完全一样：主要功能是分类，而不是作曲工具。', '西洋の「音階」とは違い、主に分類のための枠組み。', 'It isn’t quite a Western scale: its main job is classification, not composition.') },
      { type: 'choice', ref: 'wiki-thaat',
        prompt: t('现代十种 thaat 的体系是谁建立的？', '現代の 10 タート体系を作ったのは？', 'Who created the modern ten-thaat system?'),
        options: ['V. N. Bhatkhande', 'Venkatamakhin', 'Rimsky-Korsakov'], answer: 0,
        hint: t('他参考了南印度的 melakarta 分类。', '南インドのメーラカルタ分類を参考にした。', 'He modelled it on the Carnatic melakarta system.'),
        explain: t('Bhatkhande 走访各个流派，整理出 32 种 thaat，最后突出 10 种；melakarta 分类则由 Venkatamakhin 在约 1640 年提出。', 'バートカンデは各流派を訪ねて 32 種を整理し 10 種を選びました。メーラカルタは 1640 年ごろヴェンカタマキンが考案。', 'Bhatkhande surveyed the schools, found 32 thaats and highlighted ten; the melakarta system was devised by Venkatamakhin around 1640.') },
      { type: 'choice', ref: 'wiki-double-harmonic', audio: { notes: [60, 61, 64, 65, 67, 68, 71, 72], mode: 'melody' },
        prompt: t('听：C D♭ E F G A♭ B，这个音阶和哪个 thaat 同音？', '聴いて：C D♭ E F G A♭ B と同じ音のタートは？', 'Listen: C D♭ E F G A♭ B matches which thaat?'),
        options: ['Bhairav', 'Bilawal', 'Kafi'], answer: 0,
        hint: t('它就是双和声音阶。', 'これはダブル・ハーモニック。', 'It is the double harmonic scale.'),
        explain: t('双和声音阶（♭2、♭6）和 Bhairav thaat、南印度的 Mayamalavagowla 同音。', 'ダブル・ハーモニック（♭2・♭6）はバイラヴ・タート、南インドのマーヤーマーラヴァゴウラと同じ音。', 'The double harmonic scale (♭2, ♭6) matches Bhairav thaat and the Carnatic Mayamalavagowla.') },
    ],
  },
  {
    id: 'welltemper', section: 'world', feature: 'temperaments', icon: '¢',
    title: t('音差与"良好律"', 'コンマと「良い音律」', 'Commas and “good” temperaments'),
    blurb: t('毕达哥拉斯音差、狼五度、Werckmeister 与 Vallotti', 'ピタゴラス・コンマ・ウルフ・ヴェルクマイスター・ヴァロッティ', 'The Pythagorean comma, the wolf, Werckmeister and Vallotti'),
    cards: [
      { type: 'guide', ref: ['wiki-pythagorean', 'wiki-meantone', 'wiki-werckmeister', 'wiki-vallotti'],
        title: t('十二个纯五度绕不回原点', '純正 5 度を 12 回重ねても元に戻らない', 'Twelve pure fifths don’t quite close the circle'),
        steps: [
          t('纯五度的频率比是 3:2，大约 701.955 音分，比平均律的 700 音分宽一点点。', '純正 5 度は 3:2 で約 701.955 セント、平均律の 700 セントより少し広い。', 'A pure fifth is 3:2, about 701.955 cents — a hair wider than equal temperament’s 700.'),
          t('叠 12 个纯五度会比 7 个八度多出约 23.46 音分，这就是"毕达哥拉斯音差"。毕达哥拉斯律只用 11 个纯五度，剩下那个五度特别难听，叫"狼五度"。', '純正 5 度を 12 回重ねると 7 オクターヴより約 23.46 セント多くなります。これが「ピタゴラス・コンマ」。ピタゴラス音律は純正 5 度を 11 回だけ使い、残る 1 つがひどく濁った「ウルフ」になります。', 'Twelve pure fifths overshoot seven octaves by about 23.46 cents — the Pythagorean comma. Pythagorean tuning uses eleven pure fifths and leaves one badly out-of-tune “wolf” fifth.'),
          t('中庸全音律把五度缩窄，换来纯正的大三度（5:4），但狼五度还在（落在 G♯–E♭）。', 'ミーントーンは 5 度を狭めて純正な長 3 度（5:4）を得ますが、ウルフは残ります（G♯–E♭）。', 'Meantone narrows the fifths to get pure 5:4 major thirds, but a wolf remains (at G♯–E♭).'),
          t('"良好律"把音差分摊给部分五度：Werckmeister III 只把 C–G、G–D、D–A、B–F♯ 四个五度各缩窄 1/4 音差，其余保持纯五度；常见的 Vallotti 把六个五度各缩窄 1/6 个毕达哥拉斯音差。十二平均律则平均分给全部 12 个五度。', '「良い音律」はコンマを一部の 5 度に分けます。ヴェルクマイスター III は C–G・G–D・D–A・B–F♯ の 4 つだけを 1/4 コンマずつ狭め、残りは純正。よく使われるヴァロッティは 6 つの 5 度を 1/6 ピタゴラス・コンマずつ。12 平均律は 12 の 5 度すべてに均等に。', '“Good” temperaments spread the comma over some fifths: Werckmeister III narrows only C–G, G–D, D–A and B–F♯ by 1/4 comma each, keeping the rest pure; the common Vallotti narrows six fifths by 1/6 Pythagorean comma. Equal temperament shares it among all twelve.'),
        ] },
      { type: 'choice', ref: 'wiki-pythagorean',
        prompt: t('一个纯五度（3:2）大约多少音分？', '純正 5 度（3:2）は約何セント？', 'About how many cents is a pure 3:2 fifth?'),
        options: ['701.955', '700', '696.6'], answer: 0,
        hint: t('比平均律五度宽一点。', '平均律の 5 度より少し広い。', 'Slightly wider than the equal-tempered fifth.'),
        explain: t('纯五度约 701.955 音分；平均律的五度正好 700 音分。', '純正 5 度は約 701.955 セント、平均律の 5 度はちょうど 700。', 'A pure fifth is about 701.955 cents; the equal-tempered fifth is exactly 700.') },
      { type: 'fill', ref: 'wiki-pythagorean',
        prompt: t('12 个纯五度比 7 个八度多出约 ___ 音分，叫毕达哥拉斯音差', '純正 5 度 12 回は 7 オクターヴより約 ___ セント多い（ピタゴラス・コンマ）', 'Twelve pure fifths exceed seven octaves by about ___ cents: the Pythagorean comma'),
        bank: [opt('23', '23.46'), opt('2', '1.955'), opt('50', '50')], answer: ['23'],
        hint: t('每个纯五度多出约 1.955 音分，乘以 12。', '1 つの純正 5 度で約 1.955 セント多い、×12。', 'Each pure fifth is about 1.955 cents too wide; times 12.'),
        explain: t('1.955 × 12 ≈ 23.46 音分。', '1.955 × 12 ≈ 23.46 セント。', '1.955 × 12 ≈ 23.46 cents.') },
      { type: 'choice', ref: 'wiki-pythagorean',
        prompt: t('毕达哥拉斯律里那个特别难听的五度叫什么？', 'ピタゴラス音律でひどく濁る 5 度の名前は？', 'What is the badly out-of-tune fifth in Pythagorean tuning called?'),
        options: [t('狼五度', 'ウルフの 5 度', 'the wolf fifth'), t('完全五度', '完全 5 度', 'the perfect fifth'), t('三全音', '三全音', 'the tritone')], answer: 0,
        hint: t('听起来像狼嚎。', 'オオカミの遠吠えのように聞こえる。', 'It howls.'),
        explain: t('11 个五度都是纯的，音差全部堆到最后一个五度上，它就成了狼五度。', '11 個の 5 度が純正で、コンマが最後の 1 つに集まりウルフになります。', 'With eleven pure fifths, the whole comma piles onto the last one — the wolf.') },
      { type: 'match', ref: ['wiki-werckmeister', 'wiki-vallotti', 'wiki-meantone'],
        prompt: t('律制 ↔ 怎样处理五度', '音律 ↔ 5 度の扱い', 'Temperament ↔ how it treats the fifths'),
        pairs: [['Werckmeister III', t('四个五度各缩 1/4 音差', '4 つの 5 度を 1/4 コンマずつ', 'four fifths narrowed by 1/4 comma')], ['Vallotti', t('六个五度各缩 1/6 音差', '6 つの 5 度を 1/6 コンマずつ', 'six fifths narrowed by 1/6 comma')], [t('中庸全音律', 'ミーントーン', 'meantone'), t('五度都缩窄，换纯大三度', 'すべて狭めて純正長 3 度', 'all fifths narrowed for pure thirds')]],
        hint: t('1/4 × 4 = 1，1/6 × 6 = 1：都正好分完一个音差。', '1/4 × 4 = 1、1/6 × 6 = 1：どちらもちょうど 1 コンマ。', '1/4 × 4 = 1 and 1/6 × 6 = 1 — each shares out exactly one comma.'),
        explain: t('良好律只缩窄一部分五度；中庸全音律把五度一律缩窄来换纯大三度。', '良い音律は一部の 5 度だけ狭め、ミーントーンはすべてを狭めて純正長 3 度を得ます。', 'Good temperaments narrow only some fifths; meantone narrows them all to win pure thirds.') },
    ],
  },
  {
    id: 'harmonics', section: 'world', feature: 'micro', icon: '1:2:3',
    title: t('泛音列：一个音里藏着很多音', '倍音列：1 つの音に多くの音が隠れている', 'The harmonic series: many notes inside one'),
    blurb: t('基频的整数倍、八度与五度从哪里来', '基音の整数倍、オクターヴと 5 度の由来', 'Integer multiples of a fundamental — where octaves and fifths come from'),
    cards: [
      { type: 'guide', ref: 'wiki-harmonic-series', demo: { play: [[36], [48], [55], [60], [64], [67]] },
        title: t('琴弦一边振动整体，一边振动分段', '弦は全体と部分で同時に振動する', 'A string vibrates as a whole and in parts at once'),
        steps: [
          t('乐器的弦或空气柱会同时以很多种方式振动。产生的频率是"基频"的整数倍：f、2f、3f、4f……这串频率叫泛音列。', '弦や空気柱は同時にいくつもの形で振動し、その周波数は「基音」の整数倍：f、2f、3f、4f……これが倍音列。', 'A string or air column vibrates in many modes at once, at integer multiples of a fundamental: f, 2f, 3f, 4f… — the harmonic series.'),
          t('我们一般把最低的基频听成"这个音的音高"；其他高于它的成分叫泛音。各泛音的强弱比例决定了音色。', 'ふつう最も低い基音を「音の高さ」として聞き、それより上の成分を倍音（上音）と呼びます。倍音の強さの比率が音色を決めます。', 'We usually hear the lowest, the fundamental, as the pitch; everything above it is an overtone. The balance of overtones shapes the timbre.'),
          t('第 2 泛音（2f）高一个八度；第 3 泛音（3f）比第 2 泛音高一个纯五度；第 4 泛音（4f）比第 3 泛音高一个纯四度，也就是基频上方两个八度。听：C2 的前几个泛音。', '第 2 倍音（2f）はオクターヴ上、第 3 倍音（3f）は第 2 倍音の完全 5 度上、第 4 倍音（4f）は第 3 倍音の完全 4 度上で基音の 2 オクターヴ上。聴いて：C2 の倍音。', 'The 2nd harmonic (2f) is an octave up; the 3rd (3f) is a perfect fifth above the 2nd; the 4th (4f) is a perfect fourth above the 3rd — two octaves above the fundamental. Listen: the first harmonics of C2.'),
          t('泛音之间是简单的整数比，小整数比很可能就是协和音程的基础。', '倍音同士は簡単な整数比で、小さな整数比が協和音程の基礎だと考えられています。', 'Harmonics relate by whole-number ratios, and small ratios are likely the basis of consonance.'),
        ] },
      { type: 'choice', ref: 'wiki-harmonic-series',
        prompt: t('第 2 泛音（频率是基频的 2 倍）比基频高多少？', '第 2 倍音（基音の 2 倍）は基音よりどれだけ高い？', 'The 2nd harmonic (twice the frequency) is how far above the fundamental?'),
        options: [t('一个八度', 'オクターヴ', 'an octave'), t('一个纯五度', '完全 5 度', 'a perfect fifth'), t('一个大三度', '長 3 度', 'a major third')], answer: 0,
        hint: t('频率翻倍 = 高八度。', '周波数 2 倍 = オクターヴ上。', 'Double the frequency = an octave up.'),
        explain: t('2:1 就是八度：频率每翻一倍，音高升高一个八度。', '2:1 がオクターヴ。周波数が 2 倍になるごとにオクターヴ上がります。', '2:1 is the octave: each doubling raises the pitch an octave.') },
      { type: 'fill', ref: 'wiki-harmonic-series',
        prompt: t('第 3 泛音比第 2 泛音高一个纯 ___ 度，第 4 泛音比第 3 泛音高一个纯 ___ 度', '第 3 倍音は第 2 倍音の完全 ___ 度上、第 4 倍音は第 3 倍音の完全 ___ 度上', 'The 3rd harmonic is a perfect ___ above the 2nd; the 4th is a perfect ___ above the 3rd'),
        bank: [opt('5', t('五', '5', 'fifth')), opt('4', t('四', '4', 'fourth')), opt('3', t('三', '3', 'third'))], answer: ['5', '4'],
        hint: t('3:2 和 4:3。', '3:2 と 4:3。', '3:2 and 4:3.'),
        explain: t('3:2 是纯五度，4:3 是纯四度；五度 + 四度 = 八度（4:2）。', '3:2 が完全 5 度、4:3 が完全 4 度。5 度 + 4 度 = オクターヴ（4:2）。', '3:2 is a perfect fifth, 4:3 a perfect fourth; fifth + fourth = octave (4:2).') },
      { type: 'choice', ref: 'wiki-harmonic-series',
        prompt: t('为什么长笛和小提琴奏同一个音，听起来却不一样？', '同じ音でもフルートとヴァイオリンで違って聞こえるのはなぜ？', 'Why do a flute and a violin sound different on the same note?'),
        options: [t('各个泛音的强弱比例不同', '倍音の強さの比率が違う', 'their overtones have different strengths'), t('基频不同', '基音が違う', 'their fundamentals differ'), t('一个有泛音，一个没有', '片方だけ倍音がある', 'one has overtones and one doesn’t')], answer: 0,
        hint: t('音高一样，基频就一样。', '高さが同じなら基音も同じ。', 'Same pitch, same fundamental.'),
        explain: t('音色主要由泛音的相对强弱决定；同一个基频，泛音配方不同，音色就不同。', '音色は主に倍音の相対的な強さで決まります。基音が同じでも配合が違えば音色が違う。', 'Timbre comes mainly from the relative strength of the overtones; same fundamental, different recipe, different sound.') },
      { type: 'match', ref: 'wiki-harmonic-series',
        prompt: t('术语 ↔ 意思', '用語 ↔ 意味', 'Term ↔ meaning'),
        pairs: [[t('基频', '基音', 'fundamental'), t('最低的那个，通常听成音高', 'いちばん低く、ふつう音高として聞く', 'the lowest, usually heard as the pitch')], [t('泛音', '上音（倍音）', 'overtone'), t('高于最低成分的任何成分', '最低成分より上の成分', 'any partial above the lowest')], [t('泛音列', '倍音列', 'harmonic series'), t('基频的整数倍：f、2f、3f……', '基音の整数倍：f・2f・3f……', 'integer multiples: f, 2f, 3f…')]],
        hint: t('"泛音"不包括基频本身。', '「上音」に基音は含まれない。', '“Overtone” excludes the fundamental.'),
        explain: t('基频本身就是泛音列的第 1 个成员；泛音指它上面的成分；整串整数倍就是泛音列。', '基音は倍音列の第 1 項、上音はその上の成分、整数倍の並び全体が倍音列。', 'The fundamental is the first harmonic; overtones are the partials above it; the whole set of integer multiples is the harmonic series.') },
    ],
  },
];

// 关卡顺序（从简到难）
const ORDER = ['heptatonic', 'thaat', 'world', 'harmonics', 'temperaments', 'welltemper'];
export const UNITS = ORDER.map((id) => {
  const unit = ALL.find((u) => u.id === id);
  if (!unit) throw new Error(`unknown unit ${id}`);
  return unit;
});
if (UNITS.length !== ALL.length) throw new Error('every unit must appear in ORDER');
