// 乐理闯关 · 旋律、对位与乐器的进阶关：每个主关后面 4 关（第 5 关"综合测验"在开局时抽题）。
// 题卡只用 references.js 中已登记、已核实的资料；{ type: 'gen' } 的题由 learn_generators.js 按同样的资料计算生成。
// 依据汇总（由 scripts/annotate-learn.mjs 生成）：
//   ref:omt2e-embellishing ref:zhwiki-nct ref:omt-embellishing ref:omt-species4 ref:omt-species3 ref:omt-cantus
//   ref:omt2e-intro ref:omt-species1 ref:omt-species2 ref:omt2e-fifth ref:omt2e-gradus ref:wiki-transposing-list
//   ref:ibmt-transposition ref:wiki-transposing ref:wiki-standard-tuning ref:agt-caged
// @refs-end

const t = (zh, ja, en) => ({ zh, ja, en });
const opt = (id, label) => ({ id, label });
const G = (gen, count = 2, params) => ({ type: 'gen', gen, count, ...(params ? { params } : {}) });
const L = (title, cards) => ({ title, cards });

export const BRANCHES = {
  nonchord: [
    L(t('经过音与辅助音', '経過音と刺繍音', 'Passing and neighbour tones'), [
      { type: 'guide', ref: ['omt2e-embellishing', 'zhwiki-nct'], tool: { feature: 'nonchord' }, visual: { kind: 'staff', notes: ['C4', 'D4', 'E4', 'F4', 'E4'] }, demo: { play: [[60], [62], [64], [65], [64]] },
        title: t('一步进来，一步出去', '1 歩入って 1 歩出る', 'Step in, step out'),
        steps: [
          t('经过音：级进进入，同方向级进离开，填满两个和弦音之间的空。C–D–E 里的 D。', '経過音：順次で入り、同じ向きへ順次で出る。2 つのコード音の間を埋める。C–D–E の D。', 'Passing tone: approached by step, left by step in the same direction, filling the gap between chord tones — the D in C–D–E.'),
          t('辅助音：级进进入，反方向级进离开；回到原来的音时叫完全辅助音。E–F–E 里的 F。听。', '刺繍音：順次で入り、反対へ順次で出る。元の音に戻れば完全な刺繍音。E–F–E の F。聴いて。', 'Neighbour tone: approached by step, left by step the other way; complete when it returns to the same note — the F in E–F–E. Listen.'),
        ] },
      { type: 'choice', ref: 'omt2e-embellishing',
        prompt: t('C 和弦里 G–A–G 的 A 是？', 'C の和音で G–A–G の A は？', 'Over a C chord, the A in G–A–G is…'),
        options: [t('上辅助音', '上刺繍音', 'an upper neighbour'), t('经过音', '経過音', 'a passing tone'), t('倚音', '倚音', 'an appoggiatura')], answer: 0,
        hint: t('从 G 上去又回到 G。', 'G から上がって G へ戻る。', 'Up from G and back to G.'),
        explain: t('级进上去、级进回来：上辅助音。', '順次で上がって順次で戻る：上刺繍音。', 'Step up, step back: an upper neighbour.') },
      { type: 'choice', ref: 'omt2e-embellishing',
        prompt: t('C 和弦里 E–F–G 的 F 是？', 'C の和音で E–F–G の F は？', 'Over a C chord, the F in E–F–G is…'),
        options: [t('经过音', '経過音', 'a passing tone'), t('辅助音', '刺繍音', 'a neighbour tone'), t('逃音', '逸音', 'an escape tone')], answer: 0,
        hint: t('方向一直往上。', 'ずっと上向き。', 'The direction keeps going up.'),
        explain: t('E、G 是和弦音，F 一步步经过：经过音。', 'E・G はコード音、F は順次で通過：経過音。', 'E and G are chord tones; F passes between them by step.') },
      G('nctType', 2),
    ]),
    L(t('双辅助音与不完全辅助音', '二重刺繍音と不完全な刺繍音', 'Double and incomplete neighbours'), [
      { type: 'guide', ref: 'omt-embellishing', demo: { play: [[64], [65], [62], [64]] },
        title: t('围着一个音转一圈', '1 音のまわりを一周', 'Circling one note'),
        steps: [
          t('双辅助音（环音）：从一个稳定音开始和结束，中间先后是它上方和下方的级进音：E–F–D–E。听。', '二重刺繍音：安定した音で始まり終わり、間にその上と下の隣接音：E–F–D–E。聴いて。', 'Double neighbour: begins and ends on a stable tone, with the step above and the step below in between: E–F–D–E. Listen.'),
          t('不完全辅助音：只有"进"或"出"其中一边是级进，另一边是跳进——倚音和逃音就属于这一类。', '不完全な刺繍音：入りか出のどちらか片方だけが順次で、もう片方は跳躍。倚音や逸音がこれ。', 'Incomplete neighbours have a step on only one side and a leap on the other — appoggiaturas and escape tones belong here.'),
        ] },
      { type: 'choice', ref: 'omt-embellishing',
        prompt: t('C–D–B–C 这个音型叫？', 'C–D–B–C の音型は？', 'The figure C–D–B–C is a…'),
        options: [t('双辅助音', '二重刺繍音', 'double neighbour'), t('经过音', '経過音', 'passing tone'), t('延留音', '掛留音', 'suspension')], answer: 0,
        hint: t('从 C 开始也在 C 结束，中间上下各一步。', 'C で始まり C で終わり、間に上下 1 歩ずつ。', 'Starts and ends on C, with a step above and below.'),
        explain: t('上方 D、下方 B 围着 C 转：双辅助音。', '上の D と下の B が C を囲む：二重刺繍音。', 'D above and B below circle C: a double neighbour.') },
      { type: 'choice', ref: 'omt-embellishing',
        prompt: t('"跳进进入、级进离开"属于哪一类？', '「跳躍で入り順次で出る」はどの種類？', '“Leap in, step out” belongs to which family?'),
        options: [t('不完全辅助音（倚音）', '不完全な刺繍音（倚音）', 'incomplete neighbour (appoggiatura)'), t('完全辅助音', '完全な刺繍音', 'complete neighbour'), t('经过音', '経過音', 'passing tone')], answer: 0,
        hint: t('只有一边是级进。', '片方だけ順次。', 'Only one side is a step.'),
        explain: t('一边跳、一边级进的辅助音是不完全的；跳进入就是倚音。', '片方が跳躍の刺繍音は不完全、跳躍で入るのが倚音。', 'A neighbour with a leap on one side is incomplete; leaping in makes an appoggiatura.') },
      G('nctType', 2),
    ]),
    L(t('装饰音的三大类', '非和声音の 3 つのグループ', 'The three families of embellishing tones'), [
      { type: 'guide', ref: 'omt2e-embellishing',
        title: t('级进、跳进、静止', '順次・跳躍・静止', 'Step, leap, static'),
        steps: [
          t('几乎所有装饰音都是三个音里的中间那个：前后两个音和低音协和，中间那个通常不属于和弦。', 'ほとんどの非和声音は 3 音の真ん中：前後の音はベースと協和し、真ん中はふつうコード音ではない。', 'Nearly every embellishing tone is the middle of a three-note gesture whose outer notes are consonant with the bass; the middle note usually isn’t in the chord.'),
          t('第一类只用级进：经过音、辅助音。第二类带跳进：倚音（通常在较强的拍位）、逃音。第三类有静止的音：延留音、上行延留音、持续音、先现音。', '第 1 グループは順次だけ：経過音・刺繍音。第 2 は跳躍を含む：倚音（ふつう強めの拍）・逸音。第 3 は静止した音：掛留・逆掛留・保続音・先取音。', 'Category 1 moves only by step: passing and neighbour tones. Category 2 involves a leap: appoggiatura (usually on a stronger part of the beat) and escape tone. Category 3 involves static notes: suspension, retardation, pedal, anticipation.'),
        ] },
      { type: 'match', ref: 'omt2e-embellishing',
        prompt: t('装饰音 ↔ 所属的类', '非和声音 ↔ グループ', 'Tone ↔ family'),
        pairs: [[t('经过音', '経過音', 'passing tone'), t('只用级进', '順次だけ', 'stepwise only')], [t('逃音', '逸音', 'escape tone'), t('带跳进', '跳躍を含む', 'involves a leap')], [t('持续音', '保続音', 'pedal'), t('有静止的音', '静止した音', 'static notes')]],
        hint: t('逃音跳着离开；持续音一直不动。', '逸音は跳躍で離れ、保続音は動かない。', 'An escape tone leaps away; a pedal never moves.'),
        explain: t('经过音、辅助音级进；倚音、逃音带跳进；延留、上行延留、持续、先现有静止的音。', '経過・刺繍は順次、倚音・逸音は跳躍、掛留・逆掛留・保続・先取は静止。', 'Passing and neighbour move by step; appoggiatura and escape tone leap; suspension, retardation, pedal and anticipation hold.') },
      { type: 'choice', ref: 'omt2e-embellishing',
        prompt: t('倚音通常出现在什么位置？', '倚音はふつうどこに出る？', 'Where does an appoggiatura typically occur?'),
        options: [t('比前后的音更强的拍位', '前後より強い拍', 'on a stronger part of the beat than its neighbours'), t('总在最后一拍', 'いつも最後の拍', 'always on the last beat'), t('只在低音', 'ベースだけ', 'only in the bass')], answer: 0,
        hint: t('它跳进来，带着重音。', '跳躍で入り、アクセントを伴う。', 'It leaps in, with weight.'),
        explain: t('倚音通常落在比周围音更强的拍位上。', '倚音はふつう周りより強い拍に来る。', 'The appoggiatura typically falls on a stronger part of the beat than the surrounding notes.') },
      G('nctType', 2),
    ]),
    L(t('装饰音综合', '非和声音の総合', 'Embellishing-tone review'), [
      { type: 'guide', ref: 'omt2e-embellishing', tool: { feature: 'nonchord' },
        title: t('三个问题', '3 つの質問', 'Three questions'),
        steps: [
          t('它怎么来？（级进、跳进、保持）它怎么走？（同向、反向）落在强拍还是弱拍？', 'どう来た？（順次・跳躍・保持）どう去る？（同じ向き・反対）強拍か弱拍か？', 'How does it arrive (step, leap, held)? How does it leave (same or opposite way)? Strong or weak beat?'),
        ] },
      G('nctType', 5),
    ]),
  ],

  nctmore: [
    L(t('延留音的三步', '掛留の 3 段階', 'The three stages of a suspension'), [
      { type: 'guide', ref: ['omt2e-embellishing', 'omt-species4'], demo: { play: [[48, 64, 72], [43, 62, 72], [43, 62, 71]] },
        title: t('准备、延留、解决', '予備・掛留・解決', 'Preparation, suspension, resolution'),
        steps: [
          t('准备：在前一个和弦里协和；延留：同一个音留到强拍上，变成不协和；解决：往下一步，回到协和。', '予備：前の和音で協和、掛留：同じ音が強拍に残って不協和、解決：1 歩下がって協和。', 'Preparation: consonant in the previous chord; suspension: the same note held into the strong beat, now dissonant; resolution: a step down, consonant again.'),
          t('常用名字按"不协和–解决"的音程叫：4–3、7–6、9–8。听：C 留到 G 和弦上（4），落到 B（3）。', '名前は「不協和–解決」の音程で：4–3・7–6・9–8。聴いて：C が G の和音に残り（4）、B へ（3）。', 'They are named by the intervals: 4–3, 7–6, 9–8. Listen: C held over G (the 4) falls to B (the 3).'),
        ] },
      { type: 'match', ref: 'omt-species4',
        prompt: t('步骤 ↔ 特点', '段階 ↔ 特徴', 'Stage ↔ trait'),
        pairs: [[t('准备', '予備', 'preparation'), t('协和', '協和', 'consonant')], [t('延留', '掛留', 'suspension'), t('强拍上不协和', '強拍で不協和', 'dissonant on the strong beat')], [t('解决', '解決', 'resolution'), t('往下一步', '1 歩下へ', 'a step down')]],
        hint: t('只有中间那步不协和。', '真ん中だけが不協和。', 'Only the middle stage is dissonant.'),
        explain: t('协和 → 不协和 → 往下级进到协和。', '協和 → 不協和 → 下へ順次で協和。', 'Consonant → dissonant → step down to consonant.') },
      { type: 'choice', ref: 'omt-species4',
        prompt: t('7–6 延留里，不协和的是哪个音程？', '7–6 の掛留で不協和なのは？', 'In a 7–6 suspension, which interval is dissonant?'),
        options: [t('七度', '7 度', 'the seventh'), t('六度', '6 度', 'the sixth'), t('都协和', 'どちらも協和', 'neither')], answer: 0,
        hint: t('第一个数字是延留，第二个是解决。', '最初の数字が掛留、2 つ目が解決。', 'The first number is the suspension, the second the resolution.'),
        explain: t('七度不协和，往下一步落到六度。', '7 度が不協和で、1 歩下がって 6 度。', 'The seventh is dissonant and steps down to the sixth.') },
      G('nctType', 2),
    ]),
    L(t('先现音、持续音与上行延留音', '先取音・保続音・逆掛留', 'Anticipations, pedals and retardations'), [
      { type: 'guide', ref: 'omt2e-embellishing', demo: { play: [[48, 64], [53, 65], [55, 62], [48, 64]] },
        title: t('早到、不走、往上解决', '早く来る・動かない・上へ解決', 'Early, staying, resolving up'),
        steps: [
          t('先现音：下一个和弦的音提前出现，在当前和弦里成为外音。', '先取音：次の和音の音が早めに現れ、今の和音では非和声音になる。', 'Anticipation: a note of the next chord arrives early, clashing with the current chord.'),
          t('持续音：低音一直保持同一个音，上方和弦照常变化。上行延留音：和延留音一样，只是往上一步解决。', '保続音：ベースが同じ音を保ち、上の和音は変わる。逆掛留：掛留と同じだが上へ 1 歩で解決。', 'Pedal: the bass holds one note while chords change above. Retardation: like a suspension, but resolving up by step.'),
        ] },
      { type: 'choice', ref: 'omt2e-embellishing',
        prompt: t('乐句最后 G 和弦的最后一拍，旋律提前唱出主和弦的 C，再在 C 和弦上保持。这个早到的 C 是？', 'フレーズ最後の G の和音の最後の拍で、旋律が主和音の C を先に歌い、C の和音でも保つ。この早い C は？', 'On the last beat of the final G chord, the melody sings the tonic’s C early, then holds it over the C chord. That early C is…'),
        options: [t('先现音', '先取音', 'an anticipation'), t('延留音', '掛留音', 'a suspension'), t('经过音', '経過音', 'a passing tone')], answer: 0,
        hint: t('下一个和弦的音"抢先"出现。', '次の和音の音が「先取り」。', 'The next chord’s note jumps the gun.'),
        explain: t('提前出现的下一个和弦音 = 先现音。', '次の和音の音が先に出る = 先取音。', 'A note of the next chord heard early = anticipation.') },
      { type: 'choice', ref: 'omt2e-embellishing',
        prompt: t('延留音和上行延留音的区别是？', '掛留と逆掛留の違いは？', 'How does a retardation differ from a suspension?'),
        options: [t('解决方向：上行延留音往上解决', '解決の向き：逆掛留は上へ', 'direction: the retardation resolves up'), t('上行延留音没有准备', '逆掛留には予備がない', 'the retardation has no preparation'), t('上行延留音在弱拍', '逆掛留は弱拍', 'the retardation is on a weak beat')], answer: 0,
        hint: t('其他都一样。', 'ほかは同じ。', 'Everything else is the same.'),
        explain: t('只有解决方向不同。', '解決の向きだけが違う。', 'Only the direction of resolution differs.') },
      G('nctType', 2),
    ]),
    L(t('三类对位里的换音（cambiata）', '第 3 類のカンビアータ', 'The nota cambiata'), [
      { type: 'guide', ref: 'omt-species3', demo: { play: [[72], [71], [67], [69], [71]] },
        title: t('五个音的特别音型', '5 音の特別な音型', 'A special five-note figure'),
        steps: [
          t('换音音型：下行一步 → 下行三度 → 上行一步 → 上行一步（或反过来）。第一、三、五个音要和定旋律协和；第二个音不协和，却跳走了。听：C–B–G–A–B。', 'カンビアータ：下へ 1 歩 → 下へ 3 度 → 上へ 1 歩 → 上へ 1 歩（またはその逆）。1・3・5 音目は定旋律と協和、2 音目は不協和なのに跳躍で離れる。聴いて：C–B–G–A–B。', 'The nota cambiata: step down → third down → step up → step up (or the mirror). Notes 1, 3, 5 are consonant with the cantus; note 2 is dissonant yet leaps away. Listen: C–B–G–A–B.'),
          t('整体从一个强拍走到下一个强拍时只差一步，所以听起来仍然平滑。', '強拍から次の強拍までは 1 歩の差なので、全体はなめらかに聞こえる。', 'From downbeat to downbeat it moves only a step, so it still sounds smooth.'),
        ] },
      { type: 'choice', ref: 'omt-species3',
        prompt: t('换音音型里，哪个音是不协和却跳走的？', 'カンビアータで不協和なのに跳躍で離れるのは？', 'In the cambiata, which note is dissonant yet leaps away?'),
        options: [t('第二个音', '2 音目', 'the second note'), t('第一个音', '1 音目', 'the first note'), t('第五个音', '5 音目', 'the fifth note')], answer: 0,
        hint: t('第一、三、五个音协和。', '1・3・5 音目は協和。', 'Notes 1, 3 and 5 are consonant.'),
        explain: t('第二个音不协和，接着跳三度，这是允许的例外。', '2 音目が不協和で 3 度跳ぶ。許された例外。', 'Note 2 is dissonant and leaps a third — an allowed exception.') },
      { type: 'choice', ref: 'omt-species3',
        prompt: t('三类对位里，不协和音一般可以出现在第几拍？', '第 3 類で不協和音が出てよい拍は？', 'In third species, dissonances may generally fall on which beats?'),
        options: [t('第 2、3、4 拍', '2・3・4 拍目', 'beats 2, 3 or 4'), t('只有第 1 拍', '1 拍目だけ', 'beat 1 only'), t('任何一拍', 'どの拍でも', 'any beat')], answer: 0,
        hint: t('强拍（第 1 拍）永远协和。', '強拍（1 拍目）は常に協和。', 'The downbeat is always consonant.'),
        explain: t('不协和可以出现在第 2、3、4 拍，前后通常是级进（双辅助音和换音例外）。', '不協和は 2・3・4 拍目、前後はふつう順次（二重刺繍音とカンビアータは例外）。', 'Dissonances may fall on beats 2–4, usually approached and left by step (double neighbours and cambiatas excepted).') },
      { type: 'fill', ref: 'omt-species3',
        prompt: t('换音（向下的形式）：下行一步 → 下行 ___ 度 → 上行一步 → 上行一步', 'カンビアータ（下向き）：1 歩下 → ___ 度下 → 1 歩上 → 1 歩上', 'Cambiata (downward form): step down → down a ___ → step up → step up'),
        bank: [opt('3', t('三', '3', 'third')), opt('2', t('二', '2', 'second')), opt('5', t('五', '5', 'fifth'))], answer: ['3'],
        hint: t('第二个音跳三度到第三个音。', '2 音目から 3 度跳ぶ。', 'Note 2 leaps a third to note 3.'),
        explain: t('下一步、下三度、上一步、上一步。', '1 歩下・3 度下・1 歩上・1 歩上。', 'Step down, third down, step up, step up.') },
    ]),
    L(t('装饰音进阶综合', '非和声音の発展総合', 'Advanced embellishing review'), [
      { type: 'guide', ref: 'omt2e-embellishing', tool: { feature: 'nonchord' },
        title: t('名字背后是走法', '名前の裏には動き方', 'Behind every name is a motion'),
        steps: [
          t('经过、辅助、倚音、逃音、延留、上行延留、先现、持续——都可以用"进、出、拍位"三个特征认出来。', '経過・刺繍・倚音・逸音・掛留・逆掛留・先取・保続——どれも「入り・出・拍」で見分けられる。', 'Passing, neighbour, appoggiatura, escape, suspension, retardation, anticipation, pedal — all recognisable by approach, departure and beat.'),
        ] },
      G('nctType', 5),
    ]),
  ],

  counterpoint: [
    L(t('写定旋律', '定旋律を書く', 'Writing a cantus firmus'), [
      { type: 'guide', ref: 'omt-cantus', tool: { feature: 'counterpoint' },
        title: t('一条简单而平衡的旋律', 'シンプルで均衡のとれた旋律', 'A simple, balanced melody'),
        steps: [
          t('定旋律是对位练习的出发点：全音符组成，从主音开始、在主音结束，大多级进，只有一个最高点。', '定旋律は対位法の出発点：全音符で、主音で始まり主音で終わり、ほぼ順次進行で、最高点は 1 つ。', 'The cantus firmus starts every exercise: whole notes, beginning and ending on the tonic, mostly stepwise, with a single climax.'),
        ] },
      { type: 'choice', ref: 'omt-cantus',
        prompt: t('定旋律应该有几个最高点？', '定旋律の最高点はいくつ？', 'How many climaxes should a cantus firmus have?'),
        options: [t('一个', '1 つ', 'one'), t('两个以上', '2 つ以上', 'two or more'), t('不需要', '不要', 'none')], answer: 0,
        hint: t('只有一个"山顶"。', '「山頂」は 1 つ。', 'One peak only.'),
        explain: t('一个清楚的最高点让旋律有方向。', 'はっきりした最高点が旋律に方向を与える。', 'A single clear climax gives the line direction.') },
      { type: 'choice', ref: 'omt-cantus',
        prompt: t('定旋律以什么音开始和结束？', '定旋律の始まりと終わりの音は？', 'What does a cantus firmus begin and end on?'),
        options: [t('主音', '主音', 'the tonic'), t('属音', '属音', 'the dominant'), t('任意音', 'どの音でも', 'any note')], answer: 0,
        hint: t('从家出发、回到家。', '家から出て家に戻る。', 'Leave home, come home.'),
        explain: t('定旋律从主音开始、在主音结束。', '定旋律は主音で始まり主音で終わる。', 'It begins and ends on the tonic.') },
      G('consonance', 2),
    ]),
    L(t('四种进行与平行五八度', '4 つの進行と並行 5・8 度', 'Four motions and parallel perfects'), [
      { type: 'guide', ref: ['omt2e-intro', 'omt-species1'], tool: { feature: 'counterpoint' },
        title: t('保持声部独立', '声部の独立を保つ', 'Keeping the parts independent'),
        steps: [
          t('反向、同向、平行、斜向四种进行里，反向最能保持声部独立。', '反行・並行・平行・斜行のうち、反行が最も声部の独立を保つ。', 'Of contrary, similar, parallel and oblique motion, contrary best keeps parts independent.'),
          t('一类对位禁止平行的纯五度、纯八度，也要小心用同向进行进入完全协和音程（隐伏五八度）。', '第 1 類では並行の完全 5 度・8 度は禁止、並行進行で完全協和に入る（隠伏 5・8 度）のにも注意。', 'First species forbids parallel fifths and octaves, and is wary of approaching perfect intervals by similar motion (direct fifths and octaves).'),
        ] },
      G('motion', 3), G('consonance', 2),
    ]),
    L(t('一类对位的开头与结尾', '第 1 類の始まりと終わり', 'Beginnings and endings in first species'), [
      { type: 'guide', ref: ['omt-species1', 'omt2e-intro'],
        title: t('从完全协和开始，级进到达结尾', '完全協和で始め、順次で終わりへ', 'Start perfect, arrive by step'),
        steps: [
          t('开头用完全协和（同度、五度、八度）；结尾的同度或八度要用级进、反向进行到达。', '始まりは完全協和（1・5・8 度）。終わりの 1 度か 8 度へは順次・反行で到達する。', 'Begin on a perfect consonance (unison, fifth, octave); reach the final unison or octave by step in contrary motion.'),
          t('倒数第二个音：定旋律是 re 时对位用 ti；定旋律是 ti 时对位用 re。', '最後から 2 番目：定旋律が re なら対旋律は ti、ti なら re。', 'Penultimate note: if the cantus has re, the counterpoint has ti; if the cantus has ti, the counterpoint has re.'),
        ] },
      { type: 'choice', ref: 'omt-species1',
        prompt: t('定旋律倒数第二个音是 re（D），对位声部在上方应该用？', '定旋律の最後から 2 番目が re（D）なら、上の対旋律は？', 'If the cantus’s penultimate note is re (D), the upper counterpoint should use…'),
        options: [t('ti（B）', 'ti（B）', 'ti (B)'), t('re（D）', 're（D）', 're (D)'), t('sol（G）', 'sol（G）', 'sol (G)')], answer: 0,
        hint: t('两个声部反向地走向 do。', '2 声が反行で do へ。', 'Both voices close on do in contrary motion.'),
        explain: t('D 往下到 C、B 往上到 C：反向级进到达八度或同度。', 'D は下へ C、B は上へ C：反行の順次で 8 度か 1 度へ。', 'D falls to C while B rises to C: stepwise contrary motion into the octave or unison.') },
      { type: 'choice', ref: 'omt2e-intro',
        prompt: t('对位最后到达八度或同度，最好用什么方式？', '最後の 8 度か 1 度へはどう到達する？', 'How should the final octave or unison be reached?'),
        options: [t('级进、反向进行', '順次・反行', 'by step in contrary motion'), t('两个声部一起跳进', '2 声が同時に跳躍', 'both voices leaping'), t('平行进行', '平行進行', 'parallel motion')], answer: 0,
        hint: t('最平滑的方式。', '最もなめらかな方法。', 'The smoothest way.'),
        explain: t('级进的反向进行让终止最自然。', '順次の反行が最も自然な終わり方。', 'Stepwise contrary motion makes the most natural close.') },
      G('motion', 2),
    ]),
    L(t('对位综合', '対位法の総合', 'Counterpoint review'), [
      { type: 'guide', ref: 'omt2e-intro', tool: { feature: 'counterpoint' },
        title: t('协和分类 + 进行方式', '協和の分類 + 進行', 'Consonance classes + motion'),
        steps: [
          t('完全协和：纯一、五、八度；不完全协和：三、六度；不协和：二、七度和增减音程。多用不完全协和，多用反向。', '完全協和：1・5・8 度、不完全協和：3・6 度、不協和：2・7 度と増減音程。不完全協和と反行を多く使う。', 'Perfect: unison, fifth, octave; imperfect: thirds and sixths; dissonant: seconds, sevenths, augmented, diminished. Favour imperfect consonances and contrary motion.'),
        ] },
      G('consonance', 3), G('motion', 3),
    ]),
  ],

  species: [
    L(t('二类对位：弱拍的经过音', '第 2 類：弱拍の経過音', 'Second species: weak-beat passing tones'), [
      { type: 'guide', ref: 'omt-species2', tool: { feature: 'counterpoint' },
        title: t('2:1 与强弱拍', '2:1 と強拍・弱拍', '2:1 and strong versus weak beats'),
        steps: [
          t('二类对位带来两个新问题：强拍与弱拍的区别，以及经过音这种不协和。强拍永远协和，多用三、六度，避免同度。', '第 2 類の新しい問題は 2 つ：強拍と弱拍の区別、そして経過音という不協和。強拍は常に協和、3・6 度を多く、1 度は避ける。', 'Second species adds two problems: strong versus weak beats, and the passing dissonance. Downbeats are always consonant, favouring thirds and sixths, avoiding unisons.'),
          t('可以用二分休止符开头再接一个二分音符；要跳进时，最好在小节内（强拍到弱拍）跳，而不是跨小节线跳。', '2 分休符で始めて 2 分音符を続けてもよい。跳躍は小節線をまたぐより小節内（強拍→弱拍）で。', 'You may open with a half rest; leap within the bar (strong to weak) rather than across the barline.'),
        ] },
      { type: 'choice', ref: 'omt-species2',
        prompt: t('二类对位里，不能连续两个小节的强拍都是同一个完全协和音程（如两个五度），为什么？', '第 2 類で 2 小節続けて強拍が同じ完全協和（5 度 2 つなど）ではいけないのはなぜ？', 'Why may two consecutive downbeats not be the same perfect interval (e.g. two fifths) in second species?'),
        options: [t('强拍到强拍要遵守一类对位的规则', '強拍から強拍へは第 1 類の規則に従う', 'downbeat-to-downbeat motion follows first-species rules'), t('二类对位不能有五度', '第 2 類に 5 度は使えない', 'second species has no fifths'), t('因为要用休止符', '休符を使うから', 'because rests are required')], answer: 0,
        hint: t('强拍连起来就像一类对位。', '強拍をつなぐと第 1 類のよう。', 'Connect the downbeats and you have first species.'),
        explain: t('强拍之间的进行按一类对位处理，所以不能连续同一个完全音程。', '強拍間の進行は第 1 類と同じ扱いなので、同じ完全音程を続けない。', 'Downbeat-to-downbeat motion follows first species, so no consecutive identical perfect intervals.') },
      { type: 'choice', ref: 'omt-species2',
        prompt: t('二类对位的弱拍上可以出现同度吗？', '第 2 類の弱拍で 1 度は使える？', 'Are unisons allowed on second-species weak beats?'),
        options: [t('可以，如果是平滑进行的结果', '使える、なめらかな進行の結果なら', 'yes, when they result from smooth motion'), t('绝对不行', '絶対だめ', 'never')], answer: 0,
        hint: t('节奏不同，声部仍然独立。', 'リズムが違えば声部は独立したまま。', 'Different rhythms keep the parts independent.'),
        explain: t('弱拍的同度在节奏错开的情况下不会削弱独立性，必要时可以用。', '弱拍の 1 度はリズムがずれていれば独立性を損なわず、必要なら使える。', 'With different rhythms a weak-beat unison doesn’t weaken independence, so it’s allowed when needed.') },
      G('consonance', 2),
    ]),
    L(t('三类对位：4:1', '第 3 類：4:1', 'Third species: 4:1'), [
      { type: 'guide', ref: 'omt-species3', tool: { feature: 'counterpoint' },
        title: t('强拍、次强拍、弱拍', '強拍・中強拍・弱拍', 'Strong, moderately strong, weak'),
        steps: [
          t('四分音符对全音符：第 1 拍最强，第 3 拍次强，第 2、4 拍弱。', '4 分音符対全音符：1 拍目が最も強く、3 拍目が中くらい、2・4 拍目が弱い。', 'Quarters against whole notes: beat 1 strongest, beat 3 moderately strong, beats 2 and 4 weak.'),
          t('新加入辅助音，以及两种可以带着不协和跳进的音型：双辅助音和换音。最后一个音必须是全音符的 do。', '刺繍音と、不協和を伴って跳躍できる 2 つの音型（二重刺繍音・カンビアータ）が加わる。最後は全音符の do。', 'It adds neighbour tones and two figures that let dissonances leap: the double neighbour and the cambiata. The final note must be a whole-note do.'),
        ] },
      { type: 'choice', ref: 'omt-species3',
        prompt: t('三类对位里，哪一拍是"次强拍"？', '第 3 類で中強拍は？', 'In third species, which beat is moderately strong?'),
        options: [t('第 3 拍', '3 拍目', 'beat 3'), t('第 2 拍', '2 拍目', 'beat 2'), t('第 4 拍', '4 拍目', 'beat 4')], answer: 0,
        hint: t('小节中间那一拍。', '小節の真ん中。', 'The middle of the bar.'),
        explain: t('第 1 拍强、第 3 拍次强、第 2、4 拍弱。', '1 拍目強・3 拍目中強・2・4 拍目弱。', 'Beat 1 strong, beat 3 moderately strong, beats 2 and 4 weak.') },
      { type: 'choice', ref: 'omt-species3',
        prompt: t('三个强拍连续都是同一个完全音程，可以吗？', '3 小節続けて強拍が同じ完全音程はよい？', 'May three consecutive bars begin with the same perfect interval?'),
        options: [t('不可以（两个可以）', 'だめ（2 つならよい）', 'no (two in a row is fine)'), t('可以', 'よい', 'yes')], answer: 0,
        hint: t('三类对位对这条放宽了一点。', '第 3 類はこの規則が少しゆるい。', 'Third species relaxes this slightly.'),
        explain: t('三类对位允许两个连续的强拍是同一个完全音程，但不能连续三个。', '第 3 類では 2 つ続くのはよいが、3 つは不可。', 'Two in a row are fine in third species, but not three.') },
      G('nctType', 2),
    ]),
    L(t('四类对位：切分与延留', '第 4 類：シンコペーションと掛留', 'Fourth species: syncopation and suspension'), [
      { type: 'guide', ref: 'omt-species4', tool: { feature: 'counterpoint' },
        title: t('尽量多用不协和延留', 'できるだけ不協和の掛留を', 'Use dissonant suspensions as much as possible'),
        steps: [
          t('四类对位里两个声部总是斜向进行；尽量多用不协和延留，旋律会变成大多往下级进，这没关系。', '第 4 類では 2 声は常に斜行。不協和の掛留をできるだけ使い、旋律がほぼ下行の順次になってもよい。', 'In fourth species the parts always move obliquely; use dissonant suspensions whenever possible — the line will mostly step downward, and that’s fine.'),
          t('上方可用：7–6、4–3、9–8；下方可用：2–3、5–6、4–5。延留按它的"解决音程"套用一类对位规则：不能连续两个 9–8 或 4–5。', '上：7–6・4–3・9–8、下：2–3・5–6・4–5。掛留は解決の音程で第 1 類の規則を当てはめる：9–8 や 4–5 を 2 回続けない。', 'Above: 7–6, 4–3, 9–8; below: 2–3, 5–6, 4–5. Apply first-species rules to the resolutions: no two 9–8s or 4–5s in a row.'),
        ] },
      { type: 'choice', ref: 'omt-species4',
        prompt: t('为什么不能连续两个 9–8 延留？', 'なぜ 9–8 の掛留を 2 回続けてはいけない？', 'Why may two 9–8 suspensions not follow each other?'),
        options: [t('解决音程都是八度，等于连续两个八度', '解決がどちらも 8 度で、8 度が 2 つ続くのと同じ', 'both resolve to octaves — like consecutive octaves'), t('九度不能用', '9 度は使えない', 'ninths are forbidden'), t('因为太低', '低すぎるから', 'because they are too low')], answer: 0,
        hint: t('看解决到的音程。', '解決先の音程を見る。', 'Look at where they resolve.'),
        explain: t('延留按解决音程套用一类对位规则：两个 9–8 就像两个连续八度。', '解決の音程で第 1 類の規則を適用：9–8 が 2 つは 8 度が 2 つ続くのと同じ。', 'Suspensions follow first-species rules by their resolutions: two 9–8s act like parallel octaves.') },
      { type: 'match', ref: 'omt-species4',
        prompt: t('位置 ↔ 允许的不协和延留', '位置 ↔ 使える不協和の掛留', 'Position ↔ allowed dissonant suspensions'),
        pairs: [[t('对位在上方', '対旋律が上', 'counterpoint above'), '7–6, 4–3, 9–8'], [t('对位在下方', '対旋律が下', 'counterpoint below'), '2–3, 5–6, 4–5']],
        hint: t('下方的延留往下解决后，和定旋律的距离变大。', '下の掛留は下へ解決すると定旋律との距離が広がる。', 'Below the cantus, resolving down widens the interval.'),
        explain: t('上方 7–6、4–3、9–8；下方 2–3、5–6、4–5（7–8 理论上可以，但最好避免）。', '上 7–6・4–3・9–8、下 2–3・5–6・4–5（7–8 は理論上可だが避ける）。', 'Above 7–6, 4–3, 9–8; below 2–3, 5–6, 4–5 (7–8 is possible but best avoided).') },
      { type: 'choice', ref: 'omt-species4',
        prompt: t('四类对位里两个声部是哪种进行？', '第 4 類で 2 声はどの進行？', 'What kind of motion do the parts make in fourth species?'),
        options: [t('斜向', '斜行', 'oblique'), t('平行', '平行', 'parallel'), t('同向', '並行', 'similar')], answer: 0,
        hint: t('一个声部保持（连音线），另一个声部动。', '片方が保たれ（タイ）、もう片方が動く。', 'One part is tied while the other moves.'),
        explain: t('错开半小节，所以总是一个动一个不动：斜向进行。', '半小節ずれているので常に片方だけ動く：斜行。', 'Offset by half a bar, one part always holds: oblique motion.') },
    ]),
    L(t('五类对位与 Fux', '第 5 類とフックス', 'Fifth species and Fux'), [
      { type: 'guide', ref: ['omt2e-fifth', 'omt2e-intro', 'omt2e-gradus'], tool: { feature: 'counterpoint' },
        title: t('把前四类混在一起', '前の 4 類を混ぜる', 'Mixing the first four species'),
        steps: [
          t('类别对位是一套循序渐进的练习方法，章节基于 Fux 1725 年的《Gradus ad Parnassum》：前五类都是两声部。', '類別対位法は段階的な練習法で、フックスの『グラドゥス・アド・パルナッスム』（1725）に基づく。最初の 5 類は 2 声。', 'Species counterpoint is a step-by-step method based on Fux’s Gradus ad Parnassum (1725); the first five species are for two voices.'),
          t('五类（华彩）对位把各类节奏混在一起，还会用成对的八分音符和装饰过的延留。', '第 5 類（華麗）は各類のリズムを混ぜ、8 分音符の組や装飾された掛留も使う。', 'Fifth (florid) species mixes the earlier rhythms, adding paired eighth notes and decorated suspensions.'),
        ] },
      { type: 'match', ref: ['omt-species2', 'omt-species3', 'omt-species4', 'omt2e-fifth'],
        prompt: t('类别 ↔ 特点', '類 ↔ 特徴', 'Species ↔ trait'),
        pairs: [[t('二类', '第 2 類', 'second'), '2:1'], [t('三类', '第 3 類', 'third'), '4:1'], [t('四类', '第 4 類', 'fourth'), t('切分与延留', 'シンコペーションと掛留', 'syncopation and suspensions')], [t('五类', '第 5 類', 'fifth'), t('各类混合', '各類の混合', 'a mixture of all')]],
        hint: t('五类叫"华彩对位"。', '第 5 類は「華麗対位法」。', 'Fifth species is “florid”.'),
        explain: t('2:1、4:1、切分延留、混合。', '2:1・4:1・掛留・混合。', '2:1, 4:1, suspensions, mixture.') },
      { type: 'choice', ref: 'omt2e-intro',
        prompt: t('类别对位的规则主要是为了？', '類別対位法の規則の主な目的は？', 'What are species-counterpoint rules mainly for?'),
        options: [t('训练基本技巧，不限于某种风格', '特定の様式に限らない基本技術の訓練', 'training basic skills, not one particular style'), t('只写 16 世纪的音乐', '16 世紀の音楽だけを書く', 'writing only 16th-century music'), t('写爵士', 'ジャズを書く', 'writing jazz')], answer: 0,
        hint: t('OMT 的说法：规则和 16 世纪音乐有关，但目的在训练。', 'OMT：規則は 16 世紀と関係するが目的は訓練。', 'OMT: the rules relate to the 16th century, but the aim is training.'),
        explain: t('它是一步步学写旋律、组合旋律的方法，训练的是独立于具体曲目的基本功。', '旋律を書き組み合わせることを段階的に学ぶ方法で、特定の曲目によらない基礎を鍛える。', 'It is a step-by-step way to learn to write and combine melodies, training skills independent of any repertoire.') },
      G('motion', 2),
    ]),
  ],

  instruments: [
    L(t('常见移调乐器练习', 'よく使う移調楽器の練習', 'Common transposing instruments'), [
      { type: 'guide', ref: ['wiki-transposing-list', 'ibmt-transposition'], tool: { feature: 'instruments' },
        title: t('写 C，响什么？', 'C と書くと何が鳴る？', 'Write C — what sounds?'),
        steps: [
          t('降 B 调单簧管、小号：响得低大二度；E♭ 中音萨克斯：低大六度；F 调圆号：低纯五度；次中音萨克斯：低大九度（大二度再加八度）。', 'B♭ クラリネット・トランペット：長 2 度低い、E♭ アルト・サックス：長 6 度低い、F ホルン：完全 5 度低い、テナー・サックス：長 9 度低い。', 'B♭ clarinet and trumpet sound a major 2nd lower; E♭ alto sax a major 6th; F horn a perfect 5th; tenor sax a major 9th (a 2nd plus an octave).'),
          t('反过来：想要某个实际音，就把谱子朝反方向移同样的距离。', '逆に、ある実音が欲しければ楽譜を反対方向へ同じだけ移す。', 'In reverse: for a given concert pitch, shift the written note the same distance the other way.'),
        ] },
      G('transposing', 5),
    ]),
    L(t('八度移调乐器', 'オクターヴ移調楽器', 'Octave-transposing instruments'), [
      { type: 'guide', ref: 'wiki-transposing', tool: { feature: 'instruments' },
        title: t('只差一个八度', 'オクターヴだけ違う', 'Just an octave off'),
        steps: [
          t('有些乐器只差八度：低音提琴、贝斯、吉他、低音大管实际低八度；短笛、木琴、钢片琴实际高八度。', 'オクターヴだけ違う楽器もある：コントラバス・ベース・ギター・コントラファゴットは 1 オクターヴ低く、ピッコロ・シロフォン・チェレスタは高い。', 'Some instruments differ only by an octave: double bass, bass guitar, guitar and contrabassoon sound an octave lower; piccolo, xylophone and celesta an octave higher.'),
          t('长号和大号按实际音高写（英国铜管乐队是例外）。', 'トロンボーンとチューバは実音で書く（英国のブラスバンドは例外）。', 'Trombone and tuba are written at concert pitch (British brass bands are the exception).'),
        ] },
      { type: 'match', ref: 'wiki-transposing',
        prompt: t('乐器 ↔ 实际声音比谱面', '楽器 ↔ 実音と楽譜', 'Instrument ↔ sounding versus written'),
        pairs: [[t('短笛', 'ピッコロ', 'piccolo'), t('高八度', '1 オクターヴ高い', 'an octave higher')], [t('低音提琴', 'コントラバス', 'double bass'), t('低八度', '1 オクターヴ低い', 'an octave lower')], [t('长号', 'トロンボーン', 'trombone'), t('一样', '同じ', 'the same')]],
        hint: t('长号按实际音高写。', 'トロンボーンは実音で書く。', 'Trombone is written at pitch.'),
        explain: t('短笛高八度、低音提琴低八度、长号不移调。', 'ピッコロは高く、コントラバスは低く、トロンボーンは移調しない。', 'Piccolo up an octave, double bass down an octave, trombone non-transposing.') },
      { type: 'choice', ref: 'wiki-transposing',
        prompt: t('钢片琴谱上写 C5，实际响什么？', 'チェレスタが C5 と書かれた音を弾くと？', 'Celesta reads C5. What sounds?'),
        options: ['C6', 'C5', 'C4'], answer: 0,
        hint: t('钢片琴实际高八度。', 'チェレスタは 1 オクターヴ高い。', 'Celesta sounds an octave up.'),
        explain: t('高八度：C6。', '1 オクターヴ上：C6。', 'An octave up: C6.') },
      { type: 'choice', ref: 'wiki-transposing',
        prompt: t('大号的谱子按实际音高写吗？', 'チューバは実音で書く？', 'Is tuba music written at concert pitch?'),
        options: [t('是（英国铜管乐队除外）', 'はい（英国ブラスバンドは例外）', 'yes (except in British brass bands)'), t('不是，低八度', 'いいえ、1 オクターヴ低い', 'no, an octave lower')], answer: 0,
        hint: t('和长号一样。', 'トロンボーンと同じ。', 'Like the trombone.'),
        explain: t('长号、大号一般按实际音高写；英国铜管乐队传统是例外。', 'トロンボーンとチューバはふつう実音、英国ブラスバンドは例外。', 'Trombone and tuba are usually at pitch; the British brass-band tradition is the exception.') },
    ]),
    L(t('为乐器写调号', '楽器のための調号', 'Key signatures for transposing instruments'), [
      { type: 'guide', ref: 'ibmt-transposition', tool: { feature: 'instruments' },
        title: t('整个调也要移', '調全体も移す', 'The whole key moves too'),
        steps: [
          t('乐队在 C 大调演奏时，降 B 调单簧管的谱子要写高大二度：D 大调（两个升号）。', 'オーケストラが C 長調のとき、B♭ クラリネットは長 2 度上の D 長調（シャープ 2 つ）で書く。', 'When the band plays in C, the B♭ clarinet part is written a major 2nd up: D major (two sharps).'),
          t('E♭ 中音萨克斯写高大六度：乐队 C 大调 → 萨克斯 A 大调。', 'E♭ アルト・サックスは長 6 度上：C 長調 → A 長調。', 'The E♭ alto sax is written a major 6th up: concert C → A major.'),
        ] },
      { type: 'choice', ref: 'ibmt-transposition',
        prompt: t('乐队在 F 大调，降 B 调小号的谱子写什么调？', 'バンドが F 長調のとき、B♭ トランペットは何調で書く？', 'The band is in F major. What key is the B♭ trumpet part written in?'),
        options: [t('G 大调', 'G 長調', 'G major'), t('E♭ 大调', 'E♭ 長調', 'E♭ major'), t('F 大调', 'F 長調', 'F major')], answer: 0,
        hint: t('写高大二度。', '長 2 度上に書く。', 'Write a major 2nd up.'),
        explain: t('F 往上大二度是 G。', 'F の長 2 度上は G。', 'A major 2nd above F is G.') },
      { type: 'choice', ref: 'ibmt-transposition',
        prompt: t('乐队在 C 大调，F 调圆号的谱子写什么调？', 'バンドが C 長調のとき、F ホルンは？', 'The band is in C major. What key is the F horn written in?'),
        options: [t('G 大调', 'G 長調', 'G major'), t('F 大调', 'F 長調', 'F major'), t('D 大调', 'D 長調', 'D major')], answer: 0,
        hint: t('圆号实际低纯五度，所以写高纯五度。', 'ホルンは完全 5 度低いので完全 5 度上に書く。', 'The horn sounds a 5th lower, so write a 5th higher.'),
        explain: t('C 往上纯五度是 G。', 'C の完全 5 度上は G。', 'A perfect 5th above C is G.') },
      G('transposing', 2),
    ]),
    L(t('移调乐器综合', '移調楽器の総合', 'Transposing-instrument review'), [
      { type: 'guide', ref: ['wiki-transposing-list', 'wiki-transposing'],
        title: t('名字里的调就是"写 C 响什么"', '名前の調 = C と書いたときの実音', 'The key in the name is what a written C sounds'),
        steps: [
          t('降 B 调乐器写 C 响 B♭，E♭ 调乐器写 C 响 E♭，F 调乐器写 C 响 F。', 'B♭ 楽器は C で B♭、E♭ 楽器は E♭、F 楽器は F が鳴る。', 'A B♭ instrument’s written C sounds B♭, an E♭ instrument’s sounds E♭, an F instrument’s sounds F.'),
        ] },
      G('transposing', 5),
    ]),
  ],

  fretboard: [
    L(t('指板上的音名', '指板の音名', 'Notes on the fretboard'), [
      { type: 'guide', ref: 'wiki-standard-tuning', tool: { feature: 'fretboard' },
        title: t('每品一个半音', '1 フレット = 半音', 'One fret, one half step'),
        steps: [
          t('标准调弦（6 弦 → 1 弦）：E A D G B E。每往上一品高一个半音，第 12 品回到空弦音的高八度。', '標準チューニング（6 → 1 弦）：E A D G B E。1 フレット上がるごとに半音、12 フレットで開放の 1 オクターヴ上。', 'Standard tuning (string 6 → 1): E A D G B E. Each fret adds a half step; fret 12 is the open note an octave up.'),
        ] },
      G('fretNote', 5),
    ]),
    L(t('相邻弦的音程', '隣の弦との音程', 'Intervals between strings'), [
      { type: 'guide', ref: 'wiki-standard-tuning',
        title: t('四度、四度、四度、大三度、四度', '4 度・4 度・4 度・長 3 度・4 度', 'Fourth, fourth, fourth, major third, fourth'),
        steps: [
          t('相邻弦大多相隔纯四度，只有 G 弦到 B 弦是大三度。所以第 5 品（纯四度）上的音等于下一根弦的空弦——G 弦要用第 4 品。', '隣の弦はほとんど完全 4 度、G–B だけ長 3 度。5 フレット（完全 4 度）の音が次の弦の開放と同じ。G 弦だけ 4 フレット。', 'Neighbouring strings are mostly a perfect fourth apart, except G to B, a major third. So fret 5 matches the next open string — fret 4 on the G string.'),
        ] },
      { type: 'choice', ref: 'wiki-standard-tuning',
        prompt: t('G 弦第几品和 B 弦空弦同音？', 'G 弦の何フレットが B 弦の開放と同じ？', 'Which fret on the G string matches the open B string?'),
        options: [t('第 4 品', '4 フレット', 'fret 4'), t('第 5 品', '5 フレット', 'fret 5'), t('第 3 品', '3 フレット', 'fret 3')], answer: 0,
        hint: t('G–B 是大三度 = 4 个半音。', 'G–B は長 3 度 = 半音 4。', 'G–B is a major third = 4 half steps.'),
        explain: t('G 往上 4 个半音是 B。', 'G から半音 4 つで B。', 'Four half steps above G is B.') },
      { type: 'choice', ref: 'wiki-standard-tuning',
        prompt: t('A 弦第 5 品是哪个音？', 'A 弦の 5 フレットは？', 'What note is fret 5 on the A string?'),
        options: ['D', 'E', 'C'], answer: 0,
        hint: t('第 5 品 = 纯四度 = 下一根弦的空弦。', '5 フレット = 完全 4 度 = 次の弦の開放。', 'Fret 5 = a perfect fourth = the next open string.'),
        explain: t('A 往上纯四度是 D——正好是 D 弦空弦。', 'A の完全 4 度上は D、D 弦の開放。', 'A perfect fourth above A is D — the open D string.') },
      { type: 'match', ref: 'wiki-standard-tuning',
        prompt: t('乐器 ↔ 标准调弦（低 → 高）', '楽器 ↔ 標準チューニング（低 → 高）', 'Instrument ↔ standard tuning (low → high)'),
        pairs: [[t('吉他', 'ギター', 'guitar'), 'E A D G B E'], [t('四弦贝斯', '4 弦ベース', 'bass guitar'), 'E A D G'], [t('曼陀林', 'マンドリン', 'mandolin'), 'G D A E']],
        hint: t('贝斯 = 吉他最低的四根弦（低八度）。', 'ベース = ギターの低い 4 本（1 オクターヴ下）。', 'Bass = the guitar’s lowest four strings, an octave down.'),
        explain: t('吉他 E2 A2 D3 G3 B3 E4；贝斯 E1 A1 D2 G2；曼陀林 G3 D4 A4 E5（按五度调）。', 'ギター E2 A2 D3 G3 B3 E4、ベース E1 A1 D2 G2、マンドリン G3 D4 A4 E5（5 度調弦）。', 'Guitar E2 A2 D3 G3 B3 E4; bass E1 A1 D2 G2; mandolin G3 D4 A4 E5 (tuned in fifths).') },
    ]),
    L(t('CAGED 五个形', 'CAGED の 5 つのフォーム', 'The five CAGED shapes'), [
      { type: 'guide', ref: 'agt-caged', tool: { feature: 'fretboard' },
        title: t('C、A、G、E、D 首尾相接', 'C・A・G・E・D がつながる', 'C, A, G, E, D link up'),
        steps: [
          t('五个开放和弦形 C、A、G、E、D 可以整体平移（用横按代替琴枕），按 C → A → G → E → D → C 的顺序沿指板一个接一个。', '5 つの開放コード形 C・A・G・E・D は丸ごと移動でき（セーハがナットの代わり）、C → A → G → E → D → C の順に指板上でつながる。', 'The five open shapes C, A, G, E, D can be moved whole (a barre replaces the nut) and link along the neck in the order C → A → G → E → D → C.'),
          t('例：C 形上移 2 品是 D；E 形在第 2 品是 F♯；D 形上移 3 品是 F。', '例：C フォームを 2 フレット上げると D、E フォームを 2 フレットで F♯、D フォームを 3 フレット上げると F。', 'Examples: the C shape up 2 frets is D; the E shape at fret 2 is F♯; the D shape up 3 frets is F.'),
        ] },
      { type: 'choice', ref: 'agt-caged',
        prompt: t('A 形横按在第 3 品，是什么和弦？', 'A フォームを 3 フレットでセーハすると？', 'The A shape barred at fret 3 is…'),
        options: ['C', 'B♭', 'D'], answer: 0,
        hint: t('A 往上 3 个半音。', 'A から半音 3 つ上。', 'Three half steps above A.'),
        explain: t('A → B♭ → B → C：C 和弦。', 'A → B♭ → B → C：C のコード。', 'A → B♭ → B → C: a C chord.') },
      { type: 'fill', ref: 'agt-caged',
        prompt: t('CAGED 的顺序：C → A → ___ → E → ___', 'CAGED の順：C → A → ___ → E → ___', 'CAGED order: C → A → ___ → E → ___'),
        bank: [opt('G', 'G'), opt('D', 'D'), opt('B', 'B')], answer: ['G', 'D'],
        hint: t('就是 CAGED 这个词。', 'CAGED という単語そのもの。', 'Just spell CAGED.'),
        explain: t('C A G E D，然后又回到 C。', 'C A G E D、そして C へ。', 'C A G E D, then back to C.') },
      { type: 'choice', ref: 'agt-caged',
        prompt: t('E 形在第 5 品是什么和弦？', 'E フォームを 5 フレットでは？', 'The E shape at fret 5 is…'),
        options: ['A', 'G', 'B'], answer: 0,
        hint: t('E 往上 5 个半音。', 'E から半音 5 つ。', 'Five half steps above E.'),
        explain: t('E F F♯ G G♯ A：A 和弦。', 'E F F♯ G G♯ A：A。', 'E F F♯ G G♯ A: an A chord.') },
    ]),
    L(t('指板综合', '指板の総合', 'Fretboard review'), [
      { type: 'guide', ref: ['wiki-standard-tuning', 'agt-caged'], tool: { feature: 'fretboard' },
        title: t('数半音就能找到任何音', '半音を数えればどの音も見つかる', 'Count half steps to find anything'),
        steps: [
          t('知道空弦音，再数品数，就能算出任何位置的音；CAGED 形让同一个和弦在整条指板上都能弹。', '開放弦とフレット数で任意の位置の音がわかる。CAGED で同じコードを指板全体で弾ける。', 'Know the open strings and count frets for any note; CAGED shapes let you play one chord all over the neck.'),
        ] },
      G('fretNote', 5),
    ]),
  ],
};
