// 乐理闯关 · 支线大关卡（入门部分；结构与规则见 learn_units_side.js 顶部的说明）
// 修改题卡后运行 node scripts/annotate-learn.mjs 更新下面的汇总与 references.js 的 usedIn
// 依据汇总（本文件题卡引用的全部资料）：
//   ref:wiki-polyrhythm ref:omt2e-20c-rhythm ref:wiki-metric-modulation ref:omt-pb-dictation ref:omt2e-rhythm
//   ref:omt2e-major-scales ref:omt2e-cadences ref:omt2e-phrase-model ref:omt2e-predominants ref:omt-pb-modal-schemas
//   ref:omt2e-pentatonic-harmony ref:omt2e-mixture
// @refs-end

const t = (zh, ja, en) => ({ zh, ja, en });
const opt = (id, label) => ({ id, label });
const m = (at, label, place) => ({ at: [].concat(at), label, ...(place ? { place } : {}) });
const cells = (...texts) => texts.map((text) => (typeof text === 'string' || text.zh ? { text } : text));

export const UNITS = [
  // ======================= 拍子 2：复节奏与节拍调制 =======================
  {
    id: 'meter2', parent: 'meter', section: 'basics', feature: 'rhythm', toolQuery: '@sub:poly', icon: '3:2',
    title: t('拍子 2：复节奏与节拍调制', '拍子 2：ポリリズムとメトリック・モジュレーション', 'Meter 2: polyrhythm & metric modulation'),
    blurb: t('3 对 2、3 对 4、共同网格，以及用一个时值把旧速度"接"到新速度', '3 対 2・3 対 4・共通グリッド、1 つの音価で新しいテンポへ橋渡し', '3 against 2, 3 against 4, the common grid, and bridging to a new tempo with one note value'),
    cards: [
      { type: 'guide', ref: 'wiki-polyrhythm',
        visual: { kind: 'blocks', rows: [
          { label: '3', cells: cells({ text: '1', lit: true }, '', '2', '', '3', '') },
          { label: '2', cells: cells({ text: '1', lit: true }, '', '', '2', '', '') },
        ] },
        tour: [
          m(['row0', 'row1'], t('两条节奏同时进行', '2 つのリズムを同時に', 'two rhythms at once')),
          m(['c0-0', 'c1-0'], t('只有第一下一起响', '最初の 1 打だけが重なる', 'only the first stroke coincides'), 'below'),
        ],
        title: t('3 对 2：两条节奏一起走', '3 対 2：2 つのリズムが一緒に進む', '3 against 2: two rhythms together'),
        steps: [
          t('复节奏是两种以上的节奏同时进行，而且它们不能简单地看成同一个拍子的派生。最常见的是 3 对 2：同一段时间里一条打 3 下，另一条打 2 下。', 'ポリリズムは 2 つ以上のリズムが同時に進み、同じ拍子から簡単に導けないもの。いちばん多いのは 3 対 2：同じ時間に一方が 3 打、もう一方が 2 打。', 'Polyrhythm is two or more rhythms at once that are not simply derived from one meter. The commonest is 3 against 2: in the same span one part plays 3 strokes, the other 2.'),
          t('把这段时间切成 6 格（3 和 2 的最小公倍数）：3 的那条在第 1、3、5 格，2 的那条在第 1、4 格，只有第 1 格一起响。', 'この時間を 6 マス（3 と 2 の最小公倍数）に分けると、3 の方は 1・3・5 マス、2 の方は 1・4 マス。重なるのは 1 マス目だけ。', 'Cut the span into 6 cells (the least common multiple of 3 and 2): the 3-part hits cells 1, 3, 5, the 2-part cells 1 and 4 — only cell 1 coincides.'),
        ] },
      { type: 'choice', ref: 'wiki-polyrhythm',
        prompt: t('3 对 2 的共同网格要切成几格？', '3 対 2 の共通グリッドは何マス？', 'How many cells does the common grid for 3 against 2 need?'),
        options: ['6', '5', '9'], answer: 0,
        hint: t('找 3 和 2 的最小公倍数。', '3 と 2 の最小公倍数。', 'The least common multiple of 3 and 2.'),
        explain: t('3 × 2 = 6：两条都能整齐地落在格子上。', '3 × 2 = 6 で、どちらもマスにぴったり乗る。', '3 × 2 = 6, so both parts land exactly on cells.') },
      { type: 'choice', ref: 'wiki-polyrhythm',
        prompt: t('3 对 2 里，两条节奏在一个循环中一起响几次？', '3 対 2 で、1 周の間に 2 つのリズムが重なるのは何回？', 'In 3 against 2, how many times per cycle do the two rhythms coincide?'),
        options: ['1', '2', '3'], answer: 0,
        hint: t('3 的位置 1 3 5，2 的位置 1 4。', '3 の位置 1・3・5、2 の位置 1・4。', 'Positions 1 3 5 and 1 4.'),
        explain: t('只有第 1 格重合，其余的都错开——正是这种错开让复节奏有"拉扯"的感觉。', '重なるのは 1 マス目だけ。ずれていることが引っ張り合う感じを生む。', 'Only cell 1 coincides; everything else is offset, which gives polyrhythm its tug.') },
      { type: 'match', ref: 'wiki-polyrhythm',
        prompt: t('比例 ↔ 共同网格的格数', '比 ↔ 共通グリッドのマス数', 'Ratio ↔ cells in the common grid'),
        pairs: [['3 : 2', '6'], ['3 : 4', '12'], ['5 : 4', '20']],
        hint: t('两个数的最小公倍数。', '2 つの数の最小公倍数。', 'Least common multiple.'),
        explain: t('3:2 → 6、3:4 → 12、5:4 → 20。', '3:2 → 6、3:4 → 12、5:4 → 20。', '3:2 → 6, 3:4 → 12, 5:4 → 20.') },
    ],
    branch: [
      {
        title: t('3 对 4 与重音', '3 対 4 とアクセント', '3 against 4 and accents'),
        cards: [
          { type: 'guide', ref: 'wiki-polyrhythm',
            visual: { kind: 'blocks', rows: [
              { label: '3', cells: cells({ text: '>', lit: true }, '', '', '', '·', '', '', '', '·', '', '', '') },
              { label: '4', cells: cells({ text: '>', lit: true }, '', '', '·', '', '', '·', '', '', '·', '', '') },
            ] },
            tour: [
              m(['row0', 'row1'], t('12 格：3 和 4 的最小公倍数', '12 マス：3 と 4 の最小公倍数', '12 cells: LCM of 3 and 4')),
              m(['c0-0', 'c1-0'], t('重音只在一起响的地方', 'アクセントは重なる所だけ', 'accent where they meet'), 'below'),
            ],
            title: t('越不整齐，越难听出谁是"主拍"', 'ずれるほど「主な拍」が分かりにくい', 'The less they line up, the harder it is to hear "the" beat'),
            steps: [
              t('3 对 4 的共同网格是 12 格：3 的那条每 4 格一下，4 的那条每 3 格一下，一个循环里也只在开头重合。', '3 対 4 の共通グリッドは 12 マス。3 の方は 4 マスごと、4 の方は 3 マスごとに打ち、1 周で重なるのは最初だけ。', '3 against 4 needs 12 cells: the 3-part hits every 4 cells, the 4-part every 3, and they meet only at the start of the cycle.'),
              t('只给开头加重音，耳朵比较容易抓住循环；把重音加到别处，两条线会更像各走各的。在节奏面板里可以单独静音一条听另一条。', '最初だけにアクセントを付けると周期がつかみやすい。ほかに付けると 2 本がより独立して聞こえる。リズム・パネルで片方を消して聴ける。', 'Accenting only the start helps the ear find the cycle; accents elsewhere make the lines sound more independent. In the rhythm panel you can mute one track.'),
            ] },
          { type: 'choice', ref: 'wiki-polyrhythm',
            prompt: t('3 对 4：打 4 下的那条，每隔几格打一下？', '3 対 4：4 打の方は何マスごと？', '3 against 4: the 4-stroke part hits every how many cells?'),
            options: ['3', '4', '2'], answer: 0,
            hint: t('12 格平分成 4 份。', '12 マスを 4 等分。', '12 cells split into 4.'),
            explain: t('12 ÷ 4 = 3；打 3 下的那条是 12 ÷ 3 = 4 格一下。', '12 ÷ 4 = 3。3 打の方は 12 ÷ 3 = 4 マスごと。', '12 ÷ 4 = 3; the 3-stroke part hits every 12 ÷ 3 = 4 cells.') },
          { type: 'choice', ref: 'wiki-polyrhythm',
            prompt: t('复节奏和"一条声部里出现三连音"有什么不同？', 'ポリリズムと「1 声部の中の 3 連符」の違いは？', 'How does polyrhythm differ from a triplet inside one part?'),
            options: [t('复节奏至少要两条节奏同时进行', 'ポリリズムは少なくとも 2 つのリズムが同時', 'polyrhythm needs at least two rhythms at once'), t('没有区别', '違いはない', 'no difference'), t('三连音必须更快', '3 連符は必ず速い', 'triplets must be faster')], answer: 0,
            hint: t('关键在"同时"。', '鍵は「同時」。', 'The key word is "simultaneous".'),
            explain: t('不规则的分割（如三连音）可以只出现在一个声部里；复节奏要求至少两条节奏在同一个循环里一起进行。', '3 連符のような分割は 1 声部だけでも起こる。ポリリズムは同じ周期の中で少なくとも 2 つが同時に進む。', 'Irregular divisions like triplets can occur in a single part; polyrhythm needs at least two rhythms running concurrently in the same cycle.') },
          { type: 'fill', ref: 'wiki-polyrhythm',
            prompt: t('3 对 4 的共同网格有 ___ 格，一个循环里两条节奏一起响 ___ 次', '3 対 4 の共通グリッドは ___ マス、1 周で重なるのは ___ 回', '3 against 4: the common grid has ___ cells, and the parts coincide ___ time(s) per cycle'),
            bank: [opt('12', '12'), opt('1', '1'), opt('7', '7'), opt('3', '3')], answer: ['12', '1'],
            hint: t('最小公倍数；重合的位置只有开头。', '最小公倍数。重なりは最初だけ。', 'LCM; they meet only at the start.'),
            explain: t('12 格；只在第 1 格重合。', '12 マス、重なるのは 1 マス目だけ。', '12 cells; they meet only on cell 1.') },
        ],
      },
      {
        title: t('节拍调制：细分不变', 'メトリック・モジュレーション：細分を保つ', 'Metric modulation: keep the subdivision'),
        cards: [
          { type: 'guide', ref: ['omt2e-20c-rhythm', 'wiki-metric-modulation'],
            visual: { kind: 'blocks', rows: [
              { label: '4/4', arrows: true, cells: cells({ text: '♩ = 120' }, { text: t('八分 = 八分', '8 分 = 8 分', 'eighth = eighth'), lit: true }, { text: t('附点四分 = 80', '付点 4 分 = 80', 'dotted quarter = 80') }) },
            ] },
            tour: [
              m('c0-1', t('两边的八分音符一样长', '両側の 8 分音符は同じ長さ', 'the eighth note keeps its length')),
              m('c0-2', t('拍子变成附点四分 速度数字变小', '拍が付点 4 分に、数字は小さく', 'the beat becomes a dotted quarter; the number drops'), 'below'),
            ],
            title: t('用一个"桥"把速度接过去', '1 つの「橋」でテンポを渡す', 'Bridge to the new tempo with one note value'),
            steps: [
              t('节拍调制：让旧速度里的某个时值等于新速度里的某个时值（谱上写"音符 = 音符"），速度的变化就变得平滑，往往要过一会儿才听出来。', 'メトリック・モジュレーション：古いテンポのある音価を新しいテンポのある音価と等しくする（譜面に「音符 = 音符」）。テンポの変化がなめらかになり、後から気づくことが多い。', 'Metric modulation makes a note value in the old tempo equal a note value in the new one (written "note = note"), smoothing the change so it is often noticed only afterwards.'),
              t('一种常见做法是细分不变：4/4 的八分音符 = 6/8 的八分音符。四分音符 = 120 时，八分音符每分钟 240 个；6/8 的一拍是三个八分（附点四分），所以新的一拍 = 240 ÷ 3 = 80。', 'よくあるのは細分を保つ方法：4/4 の 8 分 = 6/8 の 8 分。4 分 = 120 なら 8 分は毎分 240。6/8 の 1 拍は 8 分 3 つ（付点 4 分）なので 240 ÷ 3 = 80。', 'One common way keeps the subdivision: the 4/4 eighth = the 6/8 eighth. At quarter = 120 there are 240 eighths a minute; a 6/8 beat is three eighths (a dotted quarter), so the new beat is 240 ÷ 3 = 80.'),
            ] },
          { type: 'choice', ref: 'omt2e-20c-rhythm',
            prompt: t('节拍调制的谱面通常怎么标？', 'メトリック・モジュレーションは譜面でふつうどう書く？', 'How is a metric modulation usually notated?'),
            options: [t('"音符 = 音符"', '「音符 = 音符」', '"note value = note value"'), t('只写新的速度数字', '新しいテンポの数字だけ', 'only the new metronome mark'), t('换一个调号', '調号を変える', 'a new key signature')], answer: 0,
            hint: t('要说明哪个时值和哪个时值相等。', 'どの音価とどの音価が等しいかを示す。', 'It says which value equals which.'),
            explain: t('写成"音符 = 音符"，演奏者就知道哪个时值是桥。', '「音符 = 音符」と書けば、どの音価が橋かが分かる。', '"note = note" tells the performer which value is the bridge.') },
          { type: 'choice', ref: 'wiki-metric-modulation',
            prompt: t('4/4 四分音符 = 90，换到 6/8 且八分音符不变。新的附点四分是多少？', '4/4 で 4 分 = 90、8 分を保って 6/8 へ。新しい付点 4 分は？', '4/4 at quarter = 90, into 6/8 keeping the eighth. The new dotted quarter is…'),
            options: ['60', '90', '135'], answer: 0,
            hint: t('八分音符每分钟 180 个，三个一拍。', '8 分は毎分 180、3 つで 1 拍。', '180 eighths a minute, three per beat.'),
            explain: t('90 × 2 = 180 个八分；180 ÷ 3 = 60。', '90 × 2 = 180、180 ÷ 3 = 60。', '90 × 2 = 180 eighths; 180 ÷ 3 = 60.') },
          { type: 'choice', ref: 'omt2e-20c-rhythm',
            prompt: t('细分不变的节拍调制里，听者最容易抓住的是什么？', '細分を保つ場合、聴き手がいちばんつかみやすいのは？', 'In a metric modulation that keeps the subdivision, what can the listener hold on to?'),
            options: [t('一直不变的八分音符脉动', '変わらない 8 分音符の流れ', 'the unchanging eighth-note pulse'), t('不变的拍子数字', '変わらない拍子の数字', 'an unchanged time signature'), t('不变的调', '変わらない調', 'an unchanged key')], answer: 0,
            hint: t('桥就是那个保持不变的时值。', '橋は変わらない音価。', 'The bridge is the value that stays the same.'),
            explain: t('八分音符的长度不变，拍的分组从两个变成三个，所以速度数字变了，细小的脉动却没变。', '8 分の長さは同じで、拍のまとまりが 2 つから 3 つになる。数字は変わるが細かい流れは同じ。', 'The eighth keeps its length while the beat groups change from two to three — the tempo number changes, the small pulse does not.') },
        ],
      },
      {
        title: t('节拍调制：拍不变与公式', 'メトリック・モジュレーション：拍を保つ、公式', 'Metric modulation: keep the beat, and the formula'),
        cards: [
          { type: 'guide', ref: ['omt2e-20c-rhythm', 'wiki-metric-modulation'],
            visual: { kind: 'blocks', rows: [
              { label: t('拍不变', '拍を保つ', 'keep the beat'), arrows: true, cells: cells({ text: '♩ = 120' }, { text: t('四分 = 附点四分', '4 分 = 付点 4 分', 'quarter = dotted quarter'), lit: true }, { text: t('附点四分 = 120', '付点 4 分 = 120', 'dotted quarter = 120') }) },
              { label: t('公式', '公式', 'formula'), cells: cells({ text: t('新速度 ÷ 旧速度', '新テンポ ÷ 旧テンポ', 'new ÷ old') }, { text: '=' }, { text: t('新小节枢纽数 ÷ 旧小节枢纽数', '新小節の枢軸数 ÷ 旧小節の枢軸数', 'pivots per new bar ÷ per old bar') }) },
            ] },
            tour: [
              m('row0', t('拍的长度不变 八分音符变快', '拍の長さは同じ 8 分は速く', 'same beat, faster eighths')),
              m('row1', t('一般的算法', '一般的な計算', 'the general rule'), 'below'),
            ],
            title: t('另一种接法：拍不变，细分变', 'もう 1 つの渡し方：拍を保ち、細分を変える', 'Another bridge: keep the beat, change the subdivision'),
            steps: [
              t('拍不变：旧的四分音符 = 新的附点四分音符。拍还是那么快，但一拍里从两个八分变成三个八分，所以八分音符变快了。', '拍を保つ：古い 4 分 = 新しい付点 4 分。拍の速さは同じだが、1 拍の 8 分が 2 つから 3 つになり、8 分は速くなる。', 'Keep the beat: old quarter = new dotted quarter. The beat stays the same speed, but each beat now holds three eighths instead of two, so the eighths get faster.'),
              t('一般的公式：新速度 ÷ 旧速度 = 新小节里枢纽时值的个数 ÷ 旧小节里枢纽时值的个数。例：4/4 四分音符 = 84，把两个二分音符的时间等于三个新的二分音符，新速度 = 84 × 3 ÷ 2 = 126。', '一般式：新テンポ ÷ 旧テンポ = 新小節の枢軸音価の数 ÷ 旧小節の枢軸音価の数。例：4/4 で 4 分 = 84、2 分 2 つの時間を新しい 2 分 3 つにすると 84 × 3 ÷ 2 = 126。', 'The general formula: new tempo ÷ old tempo = pivot values per new bar ÷ pivot values per old bar. Example: 4/4 at quarter = 84, with two half notes made equal to three new half notes, the new tempo is 84 × 3 ÷ 2 = 126.'),
            ] },
          { type: 'choice', ref: 'omt2e-20c-rhythm',
            prompt: t('"四分 = 附点四分"的节拍调制之后，八分音符怎样了？', '「4 分 = 付点 4 分」のあと、8 分音符はどうなる？', 'After "quarter = dotted quarter", what happens to the eighth notes?'),
            options: [t('变快', '速くなる', 'they get faster'), t('变慢', '遅くなる', 'they get slower'), t('不变', '変わらない', 'unchanged')], answer: 0,
            hint: t('同样长的一拍里要放进三个八分。', '同じ長さの 1 拍に 8 分を 3 つ入れる。', 'Three eighths now fit in the same beat.'),
            explain: t('拍不变、一拍里的八分从两个变成三个，每个八分就更短、更快。', '拍は同じで 8 分が 2 つから 3 つになるので、1 つ 1 つが短く速くなる。', 'Same beat, three eighths instead of two, so each eighth is shorter and faster.') },
          { type: 'choice', ref: 'wiki-metric-modulation',
            prompt: t('旧速度 100：旧小节里 2 个枢纽时值，新小节里 3 个。新速度？', '旧テンポ 100：旧小節に枢軸音価 2 つ、新小節に 3 つ。新テンポは？', 'Old tempo 100: 2 pivot values per old bar, 3 per new bar. New tempo?'),
            options: ['150', '67', '200'], answer: 0,
            hint: t('新 ÷ 旧 = 3 ÷ 2。', '新 ÷ 旧 = 3 ÷ 2。', 'new ÷ old = 3 ÷ 2.'),
            explain: t('100 × 3 ÷ 2 = 150。', '100 × 3 ÷ 2 = 150。', '100 × 3 ÷ 2 = 150.') },
          { type: 'match', ref: 'omt2e-20c-rhythm',
            prompt: t('做法 ↔ 结果', 'やり方 ↔ 結果', 'Technique ↔ result'),
            pairs: [[t('细分不变（八分 = 八分）', '細分を保つ（8 分 = 8 分）', 'keep the subdivision (eighth = eighth)'), t('拍的速度变了', '拍の速さが変わる', 'the beat speed changes')], [t('拍不变（四分 = 附点四分）', '拍を保つ（4 分 = 付点 4 分）', 'keep the beat (quarter = dotted quarter)'), t('细分的速度变了', '細分の速さが変わる', 'the subdivision speed changes')]],
            hint: t('保持的那个不变 另一个就变。', '保つ方は変わらず、もう一方が変わる。', 'Whatever is kept stays; the other changes.'),
            explain: t('保留细分 → 拍变；保留拍 → 细分变。', '細分を保つ → 拍が変わる。拍を保つ → 細分が変わる。', 'Keep the subdivision → the beat changes; keep the beat → the subdivision changes.') },
        ],
      },
      {
        title: t('综合：听出复节奏与速度的接合', '総合：ポリリズムとテンポの接ぎ目を聴く', 'Putting it together'),
        cards: [
          { type: 'guide', ref: ['wiki-polyrhythm', 'wiki-metric-modulation'],
            visual: { kind: 'blocks', rows: [
              { label: t('复节奏', 'ポリリズム', 'polyrhythm'), cells: cells({ text: t('同时', '同時', 'at once') }, { text: '3 : 2', lit: true }) },
              { label: t('节拍调制', 'メトリック・モジュレーション', 'metric modulation'), arrows: true, cells: cells({ text: t('旧速度', '旧テンポ', 'old tempo') }, { text: t('桥：同一个时值', '橋：同じ音価', 'bridge: one value'), lit: true }, { text: t('新速度', '新テンポ', 'new tempo') }) },
            ] },
            tour: [
              m('row0', t('两条节奏叠在一起', '2 つのリズムを重ねる', 'two rhythms layered')),
              m('row1', t('一前一后 接成新速度', '前後でつないで新しいテンポへ', 'one after another, into a new tempo'), 'below'),
            ],
            title: t('一个是"同时"，一个是"先后"', '一方は「同時」、もう一方は「前後」', 'One is "at once", the other "one after another"'),
            steps: [
              t('复节奏是两种节奏同时进行；节拍调制是先后两个速度，用一个共同的时值连起来。', 'ポリリズムは 2 つのリズムが同時に進むこと。メトリック・モジュレーションは前後 2 つのテンポを共通の音価でつなぐこと。', 'Polyrhythm is two rhythms at the same time; metric modulation links two successive tempos through a shared note value.'),
              t('二者也能连起来用：先让 3 对 2 的"3"出现，再把它当成新速度的拍——旧的三连音就成了新的拍。', '組み合わせもできる：3 対 2 の「3」を先に聞かせ、それを新しいテンポの拍にする——古い 3 連符が新しい拍になる。', 'They can combine: let the "3" of a 3:2 appear first, then make it the beat of the new tempo — the old triplet becomes the new beat.'),
            ] },
          { type: 'choice', ref: 'wiki-metric-modulation',
            prompt: t('四分 = 60，把三连音八分（一拍三个）当成新的八分（一拍两个）。新的四分？', '4 分 = 60、3 連符の 8 分（1 拍 3 つ）を新しい 8 分（1 拍 2 つ）に。新しい 4 分は？', 'Quarter = 60; the triplet eighth (three per beat) becomes the new eighth (two per beat). New quarter?'),
            options: ['90', '40', '120'], answer: 0,
            hint: t('三连音八分每分钟 180 个，新的一拍两个。', '3 連符の 8 分は毎分 180、新しい 1 拍に 2 つ。', '180 triplet eighths a minute, two per new beat.'),
            explain: t('60 × 3 = 180；180 ÷ 2 = 90。', '60 × 3 = 180、180 ÷ 2 = 90。', '60 × 3 = 180; 180 ÷ 2 = 90.') },
          { type: 'choice', ref: 'wiki-polyrhythm',
            prompt: t('下面哪一个是复节奏？', 'ポリリズムはどれ？', 'Which one is a polyrhythm?'),
            options: [t('左手三下 右手两下 同时进行', '左手 3 打と右手 2 打を同時に', 'left hand three, right hand two, at once'), t('先 4/4 再换 3/4', '4/4 から 3/4 へ', '4/4 then 3/4'), t('速度从 90 变成 120', 'テンポが 90 から 120 へ', 'tempo changes from 90 to 120')], answer: 0,
            hint: t('要"同时"。', '「同時」であること。', 'It must be simultaneous.'),
            explain: t('3 对 2 同时进行是复节奏；换拍号、换速度都是前后发生的。', '3 対 2 を同時に鳴らすのがポリリズム。拍子やテンポの変更は前後に起こる。', 'Three against two at once is polyrhythm; changing meter or tempo happens in sequence.') },
          { type: 'choice', ref: 'omt2e-20c-rhythm',
            prompt: t('为什么说节拍调制常常"事后才听出来"？', 'メトリック・モジュレーションが「後から気づく」と言われるのはなぜ？', 'Why is a metric modulation often noticed only afterwards?'),
            options: [t('桥的时值前后一样 变化很平滑', '橋の音価が前後で同じで変化がなめらか', 'the bridge value is identical, so the change is smooth'), t('它总是很小声', 'いつも小さな音', 'it is always quiet'), t('它只出现在结尾', '終わりにしか出ない', 'it only happens at the end')], answer: 0,
            hint: t('想想那个"="。', '「=」を考えて。', 'Think of the "=".'),
            explain: t('因为有一个时值前后完全相同，耳朵顺着它就过去了，变化往往要过一会儿才察觉。', '前後でまったく同じ音価があるので、耳はそれに乗って進み、変化には少し後で気づく。', 'One value is identical on both sides, so the ear rides across it and notices the change only later.') },
        ],
      },
    ],
  },

  // ======================= 听写 =======================
  {
    id: 'dictation', parent: 'intervals', prerequisites: ['staff', 'rhythm', 'meter', 'major', 'triads', 'roman', 'cadences', 'functions'], section: 'basics', feature: 'ear', toolQuery: '@sub:dictation', icon: '听',
    title: t('听写：把听到的写下来', '聴音：聴いたものを書き取る', 'Dictation: write down what you hear'),
    blurb: t('节奏点格、旋律轮廓、低音线和和弦进行的听写方法', 'リズムのドット・グリッド、旋律の輪郭、バスラインと和声進行の聴き方', 'Dot grids for rhythm, contour for melody, and how to take down bass lines and progressions'),
    cards: [
      { type: 'guide', ref: 'omt-pb-dictation',
        visual: { kind: 'blocks', rows: [
          { label: t('点格', 'ドット', 'dots'), cells: cells('·', '·', '·', '·') },
          { label: t('标记', '記号', 'marks'), cells: cells({ text: '/', lit: true }, { text: '/ –' }, { text: 'o' }, { text: '/' }) },
        ] },
        tour: [
          m('row0', t('每拍一个点', '1 拍に 1 つの点', 'one dot per beat')),
          m('row1', t('/ 起音  – 延长  o 休止', '/ 打鍵  – 延ばす  o 休符', '/ attack  – sustain  o rest'), 'below'),
        ],
        title: t('先画格子，再写音符', 'まずマスを描き、それから音符', 'Grid first, notes second'),
        steps: [
          t('听写是把没见过的节奏、旋律或和弦进行写成谱。', '聴音は、見たことのないリズム・旋律・和声進行を譜面に書き取ること。', 'Dictation means writing unfamiliar rhythms, melodies or progressions into notation.'),
          t('节奏听写的一个方法是先画"点格"：每拍一个点；听到起音画斜线，延长画横线，休止画圆圈；最后再翻译成五线谱。', 'リズム聴音の方法の 1 つは「ドット・グリッド」：1 拍に 1 点。打鍵はスラッシュ、延ばしは横線、休符は丸。最後に五線譜に直す。', 'One rhythm method is a dot grid: one dot per beat; draw a slash for each attack, a dash for a sustain and a circle for a rest, then translate into staff notation.'),
        ] },
      { type: 'match', ref: 'omt-pb-dictation',
        prompt: t('点格上的记号 ↔ 意思', 'ドット・グリッドの記号 ↔ 意味', 'Dot-grid mark ↔ meaning'),
        pairs: [['/', t('起音', '打鍵', 'attack')], ['–', t('延长', '延ばす', 'sustain')], ['o', t('休止', '休符', 'rest')]],
        hint: t('斜线是"开始响"。', 'スラッシュは「鳴り始め」。', 'A slash is where a sound starts.'),
        explain: t('斜线标起音，横线标延长，圆圈标休止。', 'スラッシュが打鍵、横線が延ばし、丸が休符。', 'Slash = attack, dash = sustain, circle = rest.') },
      { type: 'choice', ref: 'omt-pb-dictation',
        prompt: t('点格里"/ –"占两拍，对应的是？', 'ドット・グリッドの「/ –」で 2 拍。これは？', 'On the dot grid "/ –" spans two beats. That is…'),
        options: [t('一个二分音符', '2 分音符 1 つ', 'one half note'), t('两个四分音符', '4 分音符 2 つ', 'two quarter notes'), t('一个四分休止', '4 分休符 1 つ', 'a quarter rest')], answer: 0,
        hint: t('只起音一次 然后延长。', '打鍵は 1 回、その後延ばす。', 'One attack, then sustain.'),
        explain: t('一次起音延长两拍，就是一个二分音符；两个四分音符要画两条斜线。', '1 回の打鍵が 2 拍続くので 2 分音符。4 分音符 2 つならスラッシュ 2 本。', 'One attack held for two beats is a half note; two quarters would need two slashes.') },
      { type: 'choice', ref: 'omt-pb-dictation',
        prompt: t('旋律听写时，可以先写下什么帮助记忆？', '旋律聴音で、まず何を書くと記憶の助けになる？', 'In melodic dictation, what can you jot down first?'),
        options: [t('轮廓线或唱名', '輪郭線や階名', 'a contour line or solfège'), t('和弦符号', 'コード記号', 'chord symbols'), t('速度数字', 'テンポの数字', 'the tempo')], answer: 0,
        hint: t('先抓住方向：往上还是往下。', 'まず方向：上か下か。', 'Catch the direction first.'),
        explain: t('旋律听写的方法包括画轮廓线、写唱名，再逐步变成准确的音高。', '旋律聴音では輪郭線や階名を書き、そこから正確な音高にしていく。', 'Melodic strategies include contour lines and writing solfège, refined into exact pitches.') },
    ],
    branch: [
      {
        title: t('节奏听写：从点格到五线谱', 'リズム聴音：ドットから五線譜へ', 'Rhythm: from dots to notes'),
        cards: [
          { type: 'guide', ref: ['omt-pb-dictation', 'omt2e-rhythm'],
            visual: { kind: 'blocks', rows: [
              { label: t('点格', 'ドット', 'grid'), cells: cells({ text: '/' }, { text: '/ /' }, { text: '/ –', lit: true }, { text: '–' }) },
              { label: t('音符', '音符', 'notes'), cells: cells({ text: '♩' }, { text: '♪♪' }, { text: t('二分', '2 分', 'half'), lit: true }, { text: '' }) },
            ] },
            tour: [
              m(['c0-1', 'c1-1'], t('一拍两条斜线 = 两个八分', '1 拍に 2 本 = 8 分 2 つ', 'two slashes in a beat = two eighths')),
              m(['c0-2', 'c0-3'], t('横线延续到下一拍', '横線は次の拍へ続く', 'the dash carries into the next beat'), 'below'),
            ],
            title: t('一拍里有几条斜线？', '1 拍にスラッシュは何本？', 'How many slashes in each beat?'),
            steps: [
              t('一拍一个斜线是四分音符；一拍两个斜线是两个八分音符；一个斜线后面接着横线，就是延长到下一拍。', '1 拍に 1 本なら 4 分、2 本なら 8 分 2 つ。スラッシュの後に横線が続けば次の拍まで延ばす。', 'One slash per beat is a quarter; two per beat are two eighths; a slash followed by a dash sustains into the next beat.'),
              t('先听一遍拍子在哪里，再一拍一拍地标，最后整体再听一遍核对。', 'まず拍の位置を聴き、1 拍ずつ記入し、最後に通して確認する。', 'Listen once for the beat, mark beat by beat, then listen through again to check.'),
            ] },
          { type: 'choice', ref: 'omt-pb-dictation',
            prompt: t('一拍里有两条斜线，写成什么？', '1 拍にスラッシュ 2 本。何と書く？', 'Two slashes in one beat are written as…'),
            options: [t('两个八分音符', '8 分音符 2 つ', 'two eighth notes'), t('一个四分音符', '4 分音符 1 つ', 'one quarter note'), t('一个二分音符', '2 分音符 1 つ', 'one half note')], answer: 0,
            hint: t('两次起音平分一拍。', '2 回の打鍵で 1 拍を等分。', 'Two attacks share the beat.'),
            explain: t('一拍里两次起音、平分这一拍，就是两个八分音符。', '1 拍に 2 回、等分なら 8 分 2 つ。', 'Two equal attacks in a beat are two eighths.') },
          { type: 'fill', ref: 'omt2e-rhythm',
            prompt: t('4/4 一小节：四分 + 两个八分 + 两个四分，一共 ___ 拍，有 ___ 次起音', '4/4 の 1 小節：4 分 + 8 分 2 つ + 4 分 2 つ、合計 ___ 拍、打鍵は ___ 回', 'A 4/4 bar: quarter + two eighths + two quarters = ___ beats with ___ attacks'),
            bank: [opt('4', '4'), opt('5', '5'), opt('3', '3'), opt('6', '6')], answer: ['4', '5'],
            hint: t('1 + 1 + 1 + 1；每个音符一次起音。', '1 + 1 + 1 + 1。音符ごとに 1 回の打鍵。', '1 + 1 + 1 + 1; one attack per note.'),
            explain: t('时值合计 1 + 0.5 + 0.5 + 1 + 1 = 4 拍；五个音符就是五次起音。', '1 + 0.5 + 0.5 + 1 + 1 = 4 拍、音符 5 つで打鍵 5 回。', '1 + 0.5 + 0.5 + 1 + 1 = 4 beats; five notes, five attacks.') },
          { type: 'choice', ref: 'omt-pb-dictation',
            prompt: t('节奏听写的推荐顺序？', 'リズム聴音のおすすめの順番は？', 'A good order for rhythmic dictation?'),
            options: [t('点格 → 斜线记号 → 五线谱', 'ドット → スラッシュ記号 → 五線譜', 'dot grid → slash notation → staff notation'), t('直接写五线谱', 'いきなり五線譜', 'straight to staff notation'), t('先写调号', 'まず調号', 'write the key signature first')], answer: 0,
            hint: t('先简单，后精确。', 'まず簡単に、それから正確に。', 'Simple first, precise later.'),
            explain: t('先在点格上用斜线和横线记下起音与延长，再翻译成五线谱。', 'まずドットにスラッシュと横線で記録し、それを五線譜に直す。', 'Mark attacks and sustains on the dot grid first, then translate into notation.') },
        ],
      },
      {
        title: t('旋律听写：轮廓与唱名', '旋律聴音：輪郭と階名', 'Melody: contour and solfège'),
        cards: [
          { type: 'guide', ref: ['omt-pb-dictation', 'omt2e-major-scales'], demo: { play: [[60], [62], [64], [62], [67], [64], [60]] },
            visual: { kind: 'notation', staves: [{ clef: 'treble' }], notes: [{ p: 'C4', d: 'q', label: 'do' }, { p: 'D4', d: 'q', label: 're' }, { p: 'E4', d: 'q', label: 'mi' }, { p: 'D4', d: 'q', label: 're' }, { p: 'G4', d: 'q', label: 'sol', lit: true }, { p: 'E4', d: 'q', label: 'mi' }, { p: 'C4', d: 'h', label: 'do' }] },
            tour: [
              m(['head0', 'head1', 'head2'], t('先听方向：往上走', 'まず方向：上へ', 'first the direction: rising')),
              m('head4', t('跳进要特别注意', '跳躍に注意', 'watch the leaps'), 'below'),
            ],
            title: t('方向对了，就完成一半', '方向が合えば半分できた', 'Get the direction right and you are halfway there'),
            steps: [
              t('先画轮廓：每个音比前一个高、低还是一样。', 'まず輪郭：前の音より高いか、低いか、同じか。', 'Draw the contour first: is each note higher, lower or the same as the last?'),
              t('再写唱名（do re mi……）或音级数字，最后换成五线谱上的音。可以先写下开头和结尾，再填中间。', '次に階名（ド・レ・ミ…）や音度の数字、最後に五線譜の音へ。最初と最後を先に書いて間を埋めてもよい。', 'Then write solfège or scale-degree numbers, and finally notes on the staff. You can write the beginning and end first, then fill the middle.'),
            ] },
          { type: 'choice', ref: 'omt-pb-dictation', audio: { notes: [[60], [64], [62], [60]], mode: 'sequence' },
            prompt: t('听：四个音的轮廓是？', '聴いて：4 音の輪郭は？', 'Listen: the contour of these four notes is…'),
            options: [t('上 下 下', '上 下 下', 'up, down, down'), t('下 上 上', '下 上 上', 'down, up, up'), t('上 上 下', '上 上 下', 'up, up, down')], answer: 0,
            hint: t('C → E → D → C。', 'C → E → D → C。', 'C → E → D → C.'),
            explain: t('C 到 E 往上，E 到 D 往下，D 到 C 再往下。', 'C→E 上、E→D 下、D→C 下。', 'C to E up, E to D down, D to C down.') },
          { type: 'choice', ref: 'omt2e-major-scales', audio: { notes: [[60], [62], [64], [67]], mode: 'sequence' },
            prompt: t('听：C 大调里，最后一个音的唱名？', '聴いて：ハ長調で最後の音の階名は？', 'Listen: in C major, the last note’s solfège syllable is…'),
            options: ['sol', 'fa', 'la'], answer: 0,
            hint: t('do re mi 之后跳了一下。', 'ド レ ミ のあと跳躍。', 'After do re mi there is a skip.'),
            explain: t('C D E G = do re mi sol：mi 到 sol 是三度跳进。', 'C D E G = ド レ ミ ソ。ミからソへ 3 度の跳躍。', 'C D E G = do re mi sol; mi to sol is a skip of a third.') },
          { type: 'choice', ref: 'omt-pb-dictation',
            prompt: t('一段旋律太长记不住，可以怎么做？', '旋律が長くて覚えられない時は？', 'The melody is too long to remember. What helps?'),
            options: [t('先写开头和结尾 再一遍遍补中间', '最初と最後を先に、何度か聴いて間を埋める', 'write the start and end first, then fill the middle over several hearings'), t('只写第一个音', '最初の音だけ書く', 'write only the first note'), t('放弃节奏只写和弦', 'リズムを捨てて和音だけ', 'skip the rhythm and write chords')], answer: 0,
            hint: t('从两头往中间。', '両端から中へ。', 'Work from both ends inwards.'),
            explain: t('先抓住开头和结尾的节奏与音高，之后每听一遍补一部分。', '最初と最後のリズムと音高をまずつかみ、聴くたびに一部ずつ埋める。', 'Get the rhythm and pitches of the start and end, then fill in more with each hearing.') },
        ],
      },
      {
        title: t('低音线听写', 'バスラインの聴音', 'Bass-line dictation'),
        cards: [
          { type: 'guide', ref: ['omt-pb-dictation', 'omt2e-cadences'], demo: { play: [[48], [53], [55], [48]] },
            visual: { kind: 'notation', staves: [{ clef: 'bass' }], notes: [{ p: 'C3', d: 'q', label: '1' }, { p: 'F3', d: 'q', label: '4' }, { p: 'G3', d: 'q', label: '5', lit: true }, { p: 'C3', d: 'q', label: '1' }] },
            tour: [
              m(['head0', 'head3'], t('从主音开始 回到主音', '主音で始まり主音へ', 'starts and ends on the tonic')),
              m('head2', t('终止前的属音', '終止前の属音', 'the dominant before the cadence'), 'below'),
            ],
            title: t('低音最常停在 1、4、5', 'バスは 1・4・5 によく止まる', 'Bass lines love 1, 4 and 5'),
            steps: [
              t('低音线也可以先画轮廓，再写音级数字（1 = 主音）。', 'バスラインも輪郭を描き、音度の数字（1 = 主音）を書く。', 'Bass lines too: contour first, then scale-degree numbers (1 = tonic).'),
              t('乐句结尾常是 5 → 1（正格终止 V–I 的低音）或停在 5（半终止）；听到结尾回到主音时，往前推回去会容易很多。', 'フレーズの終わりは 5 → 1（正格終止 V–I のバス）か 5 で止まる（半終止）が多い。終わりの主音から逆にたどると楽。', 'Phrase endings are often 5 → 1 (the bass of V–I) or stop on 5 (a half cadence); working backwards from a final tonic is much easier.'),
            ] },
          { type: 'choice', ref: 'omt2e-cadences', audio: { notes: [[48], [55], [48]], mode: 'sequence' },
            prompt: t('听：低音 1 → ? → 1，中间是第几级？', '聴いて：バス 1 → ? → 1、真ん中は何度？', 'Listen: bass 1 → ? → 1. The middle note is degree…'),
            options: ['5', '4', '2'], answer: 0,
            hint: t('往上跳了五度（或往下跳四度）。', '5 度上（または 4 度下）。', 'A leap up a fifth (or down a fourth).'),
            explain: t('C → G → C：中间是属音 5，这是正格终止的低音。', 'C → G → C。真ん中は属音 5、正格終止のバス。', 'C → G → C: the dominant, 5 — the bass of an authentic cadence.') },
          { type: 'choice', ref: 'omt2e-cadences', audio: { notes: [[48], [53], [55]], mode: 'sequence' },
            prompt: t('听：低音 1 → 4 → 5 就停了。这像哪种结尾？', '聴いて：バス 1 → 4 → 5 で止まる。どの終わり方？', 'Listen: the bass goes 1 → 4 → 5 and stops. Which ending does this suggest?'),
            options: [t('半终止', '半終止', 'a half cadence'), t('正格终止', '正格終止', 'an authentic cadence'), t('变格终止', '変格終止', 'a plagal cadence')], answer: 0,
            hint: t('停在 5 上。', '5 で止まる。', 'It stops on 5.'),
            explain: t('低音停在 5（属音）上，像半终止那样等待下文。', 'バスが 5（属音）で止まり、半終止のように続きを待つ。', 'The bass stops on 5, waiting like a half cadence.') },
          { type: 'choice', ref: 'omt-pb-dictation',
            prompt: t('听低音线时，最好先抓住什么？', 'バスラインを聴く時、まず何をつかむ？', 'When taking down a bass line, catch what first?'),
            options: [t('轮廓和起止音', '輪郭と最初・最後の音', 'its contour and first/last notes'), t('每个音的力度', '各音の強さ', 'the dynamics of each note'), t('上方声部的和弦音', '上声部の和音', 'the upper voices')], answer: 0,
            hint: t('和旋律听写一样。', '旋律聴音と同じ。', 'Same as melody.'),
            explain: t('先画轮廓、确定开头和结尾，再一级一级地填。', 'まず輪郭、最初と最後を決め、1 つずつ埋める。', 'Contour and endpoints first, then fill degree by degree.') },
        ],
      },
      {
        title: t('和弦进行听写', '和声進行の聴音', 'Progression dictation'),
        cards: [
          { type: 'guide', ref: ['omt2e-phrase-model', 'omt2e-predominants'], demo: { play: [[48, 55, 64, 72], [53, 57, 65, 72], [43, 55, 62, 71], [48, 55, 64, 72]] },
            visual: { kind: 'blocks', rows: [{ arrows: true, cells: cells({ text: 'I', sub: 'T' }, { text: 'IV', sub: 'PD' }, { text: 'V', sub: 'D', lit: true }, { text: 'I', sub: 'T' }) }] },
            tour: [
              m(['c0-0', 'c0-3'], t('开头和结尾通常是主和弦', '始めと終わりはたいてい主和音', 'tonic at both ends')),
              m(['c0-1', 'c0-2'], t('中间按 下属 → 属 的方向走', '真ん中は 下属 → 属 の方向', 'predominant then dominant in between'), 'below'),
            ],
            title: t('猜方向，比猜每个和弦更容易', '方向を予想する方が 1 つずつより楽', 'Predict the direction, not each chord in isolation'),
            steps: [
              t('乐句常按 主 → 下属 → 属 → 主 的方向走（T–PD–D–T）。', 'フレーズはよく 主 → 下属 → 属 → 主（T–PD–D–T）と進む。', 'Phrases often move tonic → predominant → dominant → tonic (T–PD–D–T).'),
              t('下属里 ii 常跟在 IV 后面、不在它前面；听到属和弦之后，下一步多半回到主和弦或停住（半终止）。', '下属では ii はよく IV の後に来て、前には来ない。属和音の後は主和音へ戻るか止まる（半終止）ことが多い。', 'Among predominants, ii follows IV rather than preceding it; after a dominant, the music usually goes home or stops (a half cadence).'),
            ] },
          { type: 'choice', ref: 'omt2e-phrase-model', audio: { notes: [[48, 55, 64, 72], [50, 57, 65, 74], [43, 55, 62, 71], [48, 55, 64, 72]], mode: 'chords' },
            prompt: t('听：I – ? – V – I，第二个和弦最可能是？', '聴いて：I – ? – V – I、2 つ目は？', 'Listen: I – ? – V – I. The second chord is most likely…'),
            options: ['ii', 'vi', 'iii'], answer: 0,
            hint: t('它在属之前，是下属功能；低音是 D。', '属の前の下属。バスは D。', 'It precedes V (predominant); the bass is D.'),
            explain: t('属和弦前面放下属功能的和弦，低音 D 的就是 ii。', '属和音の前は下属。バス D なら ii。', 'A predominant before V; with D in the bass it is ii.') },
          { type: 'choice', ref: 'omt2e-predominants',
            prompt: t('下面哪个顺序符合下属和弦的常见写法？', '下属和音のよくある順番はどれ？', 'Which order matches common predominant practice?'),
            options: ['IV – ii – V', 'ii – IV – V', 'V – IV – ii'], answer: 0,
            hint: t('ii 跟在 IV 后面。', 'ii は IV の後。', 'ii follows IV.'),
            explain: t('IV 之后可以接 ii 再到 V；ii 一般不放在 IV 前面。', 'IV のあと ii、そして V。ii を IV の前に置くことは少ない。', 'IV can move to ii, then V; ii is normally not placed before IV.') },
          { type: 'choice', ref: 'omt2e-cadences', audio: { notes: [[48, 55, 64, 72], [45, 57, 64, 72], [53, 57, 65, 72], [43, 55, 62, 71]], mode: 'chords' },
            prompt: t('听：最后停在哪个功能上？', '聴いて：最後はどの働きで止まる？', 'Listen: which function does it stop on?'),
            options: [t('属（半终止）', '属（半終止）', 'dominant (half cadence)'), t('主', '主', 'tonic'), t('下属', '下属', 'predominant')], answer: 0,
            hint: t('最后一个和弦低音是 G。', '最後の和音のバスは G。', 'The last bass note is G.'),
            explain: t('I – vi – IV – V：停在 V 上，是半终止。', 'I – vi – IV – V。V で止まる半終止。', 'I – vi – IV – V stops on V: a half cadence.') },
        ],
      },
    ],
  },

  // ======================= 调式 2：流行音乐里的调式套路 =======================
  {
    id: 'modes2', parent: 'modes', section: 'basics', feature: 'ref', icon: 'Mix',
    title: t('调式 2：流行音乐里的调式进行', '旋法 2：ポップスの旋法的な進行', 'Modes 2: modal progressions in pop'),
    blurb: t('Mixolydian 的 ♭VII、Aeolian 的 ♭VI ♭VII、Dorian 的大 IV、Lydian 的大 II，以及怎样用耳朵分辨', 'ミクソリディアの ♭VII、エオリアの ♭VI ♭VII、ドリアの長 IV、リディアの長 II、耳での見分け方', 'Mixolydian ♭VII, Aeolian ♭VI ♭VII, Dorian major IV, Lydian major II, and telling them apart by ear'),
    cards: [
      { type: 'guide', ref: 'omt-pb-modal-schemas', demo: { play: [[46, 58, 62, 65], [53, 57, 60, 65], [48, 55, 64, 72]] },
        visual: { kind: 'blocks', rows: [
          { label: t('双重变格', 'ダブル・プラガル', 'double plagal'), arrows: true, cells: cells({ text: '♭VII', lit: true }, { text: 'IV' }, { text: 'I' }) },
          { label: t('subtonic shuttle', 'サブトニック・シャトル', 'subtonic shuttle'), arrows: true, cells: cells({ text: 'I' }, { text: '♭VII', lit: true }, { text: 'I' }) },
        ] },
        tour: [
          m(['c0-0', 'c1-1'], t('♭VII 带着 te（B♭）', '♭VII に te（B♭）', '♭VII carries te (B♭)')),
          m('row0', t('Mixolydian 套路', 'ミクソリディアの型', 'a Mixolydian schema'), 'below'),
        ],
        title: t('一个"颜色音"就能带出调式', '1 つの「色の音」で旋法が出る', 'One colour note is enough to suggest a mode'),
        steps: [
          t('流行歌常用暗示别的调式的和弦进行，但整首歌不一定严格属于那个调式。', 'ポップスは別の旋法をにおわせる進行をよく使うが、曲全体がその旋法とは限らない。', 'Pop songs often use progressions that imply other modes without the whole song being strictly in that mode.'),
          t('Mixolydian 的颜色音是 te（降低的第七级）：大调里的 ♭VII 就是从 Mixolydian 借来的，常起属的作用，例如双重变格 ♭VII–IV–I 和 subtonic shuttle I–♭VII。', 'ミクソリディアの色の音は te（下がった第 7 音）。長調の ♭VII はミクソリディアからの借用で、属の働きをすることが多い。例：ダブル・プラガル ♭VII–IV–I、サブトニック・シャトル I–♭VII。', 'Mixolydian’s colour note is te (lowered 7th): ♭VII in major is borrowed from Mixolydian and usually acts as a dominant, as in the double plagal ♭VII–IV–I and the subtonic shuttle I–♭VII.'),
        ] },
      { type: 'choice', ref: 'omt-pb-modal-schemas', audio: { notes: [[46, 58, 62, 65], [53, 57, 60, 65], [48, 55, 64, 72]], mode: 'chords' },
        prompt: t('听：B♭ – F – C（C 大调），这是哪个套路？', '聴いて：B♭ – F – C（ハ長調）。どの型？', 'Listen: B♭ – F – C in C. Which schema?'),
        options: [t('双重变格 ♭VII–IV–I', 'ダブル・プラガル ♭VII–IV–I', 'double plagal ♭VII–IV–I'), t('正格终止', '正格終止', 'authentic cadence'), t('Dorian shuttle', 'ドリアン・シャトル', 'dorian shuttle')], answer: 0,
        hint: t('两次"变格"（下四度到上方）。', '2 回の変格。', 'Two plagal moves in a row.'),
        explain: t('♭VII–IV–I：B♭ 到 F、F 到 C 都是变格式的运动，大主和弦加上 te，是 Mixolydian 套路。', '♭VII–IV–I。B♭→F、F→C どちらも変格的、長い主和音と te でミクソリディア。', '♭VII–IV–I: B♭→F and F→C are both plagal motions; a major tonic plus te makes it Mixolydian.') },
      { type: 'choice', ref: 'omt-pb-modal-schemas',
        prompt: t('Mixolydian 的颜色音是？', 'ミクソリディアの色の音は？', 'Mixolydian’s colour note is…'),
        options: [t('te（降低的第七级）', 'te（下がった第 7 音）', 'te (lowered 7th)'), t('fi（升高的第四级）', 'fi（上がった第 4 音）', 'fi (raised 4th)'), t('ra（降低的第二级）', 'ra（下がった第 2 音）', 'ra (lowered 2nd)')], answer: 0,
        hint: t('和大调只差一个音：第七级。', '長調との違いは第 7 音だけ。', 'It differs from major only at the 7th.'),
        explain: t('Mixolydian = 大调降低第七级（te），所以出现 ♭VII 和小属 v。', 'ミクソリディア = 長調の第 7 音を下げたもの。だから ♭VII と短い v が出る。', 'Mixolydian is major with a lowered 7th (te), giving ♭VII and minor v.') },
      { type: 'choice', ref: 'omt-pb-modal-schemas',
        prompt: t('subtonic shuttle I–♭VII 里，主和弦是大三还是小三决定了什么？', 'サブトニック・シャトル I–♭VII で、主和音が長三か短三かで何が決まる？', 'In the subtonic shuttle, what does the quality of the tonic decide?'),
        options: [t('大三 → Mixolydian；小三 → Aeolian', '長三 → ミクソリディア、短三 → エオリア', 'major → Mixolydian; minor → Aeolian'), t('速度', 'テンポ', 'the tempo'), t('拍子', '拍子', 'the meter')], answer: 0,
        hint: t('同样的往返 区别只在主和弦。', '同じ往復、違いは主和音だけ。', 'Same shuttle, only the tonic differs.'),
        explain: t('同样的 I–♭VII：主和弦是大三暗示 Mixolydian，是小三（i–♭VII）暗示 Aeolian。', '同じ往復で、主和音が長三ならミクソリディア、短三（i–♭VII）ならエオリア。', 'The same shuttle implies Mixolydian with a major tonic and Aeolian with a minor one (i–♭VII).') },
    ],
    branch: [
      {
        title: t('Aeolian：♭VI 与 ♭VII', 'エオリア：♭VI と ♭VII', 'Aeolian: ♭VI and ♭VII'),
        cards: [
          { type: 'guide', ref: 'omt-pb-modal-schemas', demo: { play: [[44, 56, 60, 63], [46, 58, 62, 65], [48, 55, 63, 72]] },
            visual: { kind: 'blocks', rows: [
              { label: t('aeolian shuttle', 'エオリアン・シャトル', 'aeolian shuttle'), arrows: true, cells: cells('i', '♭VII', { text: '♭VI', lit: true }, '♭VII') },
              { label: t('aeolian cadence', 'エオリアン・カデンツ', 'aeolian cadence'), arrows: true, cells: cells('♭VI', '♭VII', { text: t('i（或 I）', 'i（または I）', 'i (or I)'), lit: true }) },
            ] },
            tour: [
              m('row0', t('在 i 与 ♭VI 之间往返', 'i と ♭VI の間を往復', 'between i and ♭VI')),
              m('row1', t('有目标的收束 不常循环', '目標のある終止 ループしにくい', 'goal-directed, not usually looped'), 'below'),
            ],
            title: t('aeolian：一个循环、一个收束', 'エオリア：ループと終止', 'Aeolian: one loop, one cadence'),
            steps: [
              t('Aeolian 的颜色音是 le 与 te，所以有 ♭VI 和 ♭VII（虽然在小调里是本来的和弦，仍写 ♭ 以免和 vii° 混淆）。', 'エオリアの色の音は le と te。だから ♭VI と ♭VII（短調では固有の和音だが vii° と区別するため ♭ を付ける）。', 'Aeolian’s colour notes are le and te, giving ♭VI and ♭VII (native in minor, but written with flats to avoid confusion with vii°).'),
              t('aeolian shuttle i–♭VII–♭VI–♭VII 在 i 和 ♭VI 之间往返，♭VII 作经过；aeolian cadence ♭VI–♭VII–i 是有目标的收束，常用皮卡迪三度变成全是大三和弦。', 'エオリアン・シャトル i–♭VII–♭VI–♭VII は i と ♭VI の間を往復し ♭VII が経過。エオリアン・カデンツ ♭VI–♭VII–i は目標のある終止で、ピカルディの 3 度ですべて長三和音になることも多い。', 'The aeolian shuttle i–♭VII–♭VI–♭VII moves between i and ♭VI with a passing ♭VII; the aeolian cadence ♭VI–♭VII–i is goal-directed and often ends with a Picardy third, making every chord major.'),
            ] },
          { type: 'choice', ref: 'omt-pb-modal-schemas', audio: { notes: [[44, 56, 60, 63], [46, 58, 62, 65], [48, 55, 63, 72]], mode: 'chords' },
            prompt: t('听：A♭ – B♭ – Cm，这是？', '聴いて：A♭ – B♭ – Cm。これは？', 'Listen: A♭ – B♭ – Cm. This is…'),
            options: [t('aeolian cadence', 'エオリアン・カデンツ', 'the aeolian cadence'), t('aeolian shuttle', 'エオリアン・シャトル', 'the aeolian shuttle'), t('双重变格', 'ダブル・プラガル', 'the double plagal')], answer: 0,
            hint: t('♭VI–♭VII–i，落到主和弦就结束。', '♭VI–♭VII–i、主和音で終わる。', '♭VI–♭VII–i, ending on the tonic.'),
            explain: t('♭VI–♭VII–i 是 aeolian cadence：根音一路上行进入主和弦，有目标感。', '♭VI–♭VII–i はエオリアン・カデンツ。根音が上行して主和音へ。', '♭VI–♭VII–i is the aeolian cadence, rising into the tonic with a sense of goal.') },
          { type: 'choice', ref: 'omt-pb-modal-schemas',
            prompt: t('为什么 aeolian shuttle 很难形成真正的终止？', 'エオリアン・シャトルが本当の終止になりにくいのはなぜ？', 'Why does the aeolian shuttle hardly ever make a true cadence?'),
            options: [t('它一直往返循环 没有目标', '往復を繰り返し目標がない', 'it keeps circling without a goal'), t('它没有主和弦', '主和音がない', 'it has no tonic'), t('它太短', '短すぎる', 'it is too short')], answer: 0,
            hint: t('终止意味着"到达"。', '終止は「到達」。', 'A cadence means arrival.'),
            explain: t('终止表示到达目标；在 i 与 ♭VI 之间不停往返的循环听起来没有目标。', '終止は目標への到達。i と ♭VI を往復し続けるループには目標がない。', 'A cadence means reaching a goal; an endless shuttle between i and ♭VI sounds goal-less.') },
          { type: 'choice', ref: 'omt-pb-modal-schemas',
            prompt: t('lament 型 i–♭VII–♭VI–v 为什么强烈暗示 Aeolian？', 'ラメント型 i–♭VII–♭VI–v がエオリアを強く示すのはなぜ？', 'Why does the lament i–♭VII–♭VI–v strongly imply Aeolian?'),
            options: [t('用小属 v 没有导音 而用 te', '短い v で導音がなく te を使う', 'minor v has no leading tone, using te instead'), t('它用了大 IV', '長 IV を使う', 'it uses major IV'), t('它停在 I 上', 'I で止まる', 'it ends on I')], answer: 0,
            hint: t('看最后一个和弦。', '最後の和音を見る。', 'Look at the last chord.'),
            explain: t('最后是小属 v：没有升高的导音（ti），只有 te，所以是 Aeolian 而不是和声小调的味道。', '最後が短い v：導音（ti）がなく te だけなので、エオリアの響き。', 'It ends on minor v, with te instead of a raised leading tone (ti) — Aeolian rather than harmonic minor.') },
        ],
      },
      {
        title: t('Dorian：小主和弦配大 IV', 'ドリア：短い主和音と長 IV', 'Dorian: minor tonic with major IV'),
        cards: [
          { type: 'guide', ref: 'omt-pb-modal-schemas', demo: { play: [[48, 55, 63, 72], [53, 57, 60, 69], [48, 55, 63, 72]] },
            visual: { kind: 'notation', brace: true, staves: [{ clef: 'treble' }, { clef: 'bass' }], notes: [
              { p: 'C3', s: 1, col: 0, d: 'w', label: 'i' }, { p: 'G4', s: 0, col: 0, d: 'w' }, { p: 'Eb4', s: 0, col: 0, d: 'w' },
              { p: 'F3', s: 1, col: 1, d: 'w', label: 'IV' }, { p: 'A4', s: 0, col: 1, d: 'w', lit: true }, { p: 'F4', s: 0, col: 1, d: 'w' },
              { p: 'C3', s: 1, col: 2, d: 'w', label: 'i' }, { p: 'G4', s: 0, col: 2, d: 'w' }, { p: 'Eb4', s: 0, col: 2, d: 'w' },
            ] },
            tour: [
              m('head4', t('la（A♮）是 Dorian 的颜色音', 'la（A♮）がドリアの色の音', 'la (A♮) is the Dorian colour note')),
              m(['head1', 'head4', 'head7'], t('上方声部做邻音 G–A–G', '上声部の隣接音 G–A–G', 'upper neighbour G–A–G'), 'below'),
            ],
            title: t('小调里出现明亮的 IV', '短調に明るい IV', 'A bright IV in a minor key'),
            steps: [
              t('Dorian 听起来像小调，但第六级是 la（不是 le），所以 IV 是大三和弦。小主和弦加上大 IV，是 Dorian 最主要的标志。', 'ドリアは短調に聞こえるが第 6 音が la（le ではない）なので IV が長三和音。短い主和音と長 IV がドリアの主な目印。', 'Dorian sounds minor, but its 6th degree is la (not le), so IV is major. A minor tonic with a major IV is Dorian’s main marker.'),
              t('dorian shuttle i–IV 往返，上方的 la 常做邻音，整体是主和弦的延长；也常扩展成 i–IV–i7–IV。', 'ドリアン・シャトル i–IV の往復では上の la がよく隣接音になり、全体は主和音の延長。i–IV–i7–IV に広げることも多い。', 'The dorian shuttle i–IV often uses la as an upper neighbour and prolongs the tonic; it is frequently expanded to i–IV–i7–IV.'),
            ] },
          { type: 'choice', ref: 'omt-pb-modal-schemas', audio: { notes: [[48, 55, 63, 72], [53, 57, 60, 69]], mode: 'chords' },
            prompt: t('听：Cm – F（大三），暗示哪个调式？', '聴いて：Cm – F（長三）。どの旋法？', 'Listen: Cm – F (major). Which mode?'),
            options: ['Dorian', 'Aeolian', 'Phrygian'], answer: 0,
            hint: t('F 大三里的 A♮ 是 la。', 'F の長三和音の A♮ が la。', 'The A♮ in F major is la.'),
            explain: t('小主和弦配大 IV（A♮ = la）是 Dorian；Aeolian 的 iv 是小三（A♭）。', '短い主和音と長 IV（A♮ = la）はドリア。エオリアの iv は短三（A♭）。', 'Minor tonic with major IV (A♮ = la) is Dorian; Aeolian’s iv is minor (A♭).') },
          { type: 'choice', ref: 'omt-pb-modal-schemas',
            prompt: t('Dorian 和自然小调（Aeolian）的差别在哪一级？', 'ドリアとエオリアの違いは何度？', 'Which degree separates Dorian from natural minor?'),
            options: [t('第六级（la 与 le）', '第 6 音（la と le）', 'the 6th (la vs le)'), t('第七级', '第 7 音', 'the 7th'), t('第三级', '第 3 音', 'the 3rd')], answer: 0,
            hint: t('影响 IV 和 ii 的性质。', 'IV と ii の性質に影響する。', 'It changes IV and ii.'),
            explain: t('Dorian 用 la，自然小调用 le；这一个音让 IV 变成大三、ii 变成小三。', 'ドリアは la、自然短音階は le。この 1 音で IV が長三、ii が短三になる。', 'Dorian uses la, natural minor le; that note makes IV major and ii minor.') },
          { type: 'choice', ref: 'omt-pb-modal-schemas',
            prompt: t('Dorian shuttle 整体是什么作用？', 'ドリアン・シャトル全体の働きは？', 'What does the dorian shuttle do overall?'),
            options: [t('延长主和弦', '主和音の延長', 'prolong the tonic'), t('转到新调', '新しい調へ転調', 'modulate'), t('构成正格终止', '正格終止を作る', 'form an authentic cadence')], answer: 0,
            hint: t('一直回到 i。', 'いつも i に戻る。', 'It keeps returning to i.'),
            explain: t('i 与 IV 往返、上方做邻音，整体听起来是在延长小主和弦。', 'i と IV の往復、上声部の隣接音で、全体は短い主和音の延長。', 'Shuttling i–IV with upper neighbours prolongs the minor tonic.') },
        ],
      },
      {
        title: t('Lydian：大三的 II', 'リディア：長三の II', 'Lydian: major II'),
        cards: [
          { type: 'guide', ref: 'omt-pb-modal-schemas', demo: { play: [[50, 57, 62, 66], [53, 57, 60, 65], [48, 55, 64, 72]] },
            visual: { kind: 'blocks', rows: [
              { label: t('lydian cadence', 'リディアン・カデンツ', 'lydian cadence'), arrows: true, cells: cells({ text: 'II♯', sub: 'F♯', lit: true }, { text: 'IV', sub: 'F' }, { text: 'I' }) },
              { label: t('lydian shuttle', 'リディアン・シャトル', 'lydian shuttle'), arrows: true, cells: cells('I', { text: 'II♯', lit: true }, 'I') },
            ] },
            tour: [
              m('c0-0', t('fi（F♯）是 Lydian 的颜色音', 'fi（F♯）がリディアの色の音', 'fi (F♯) is the Lydian colour note')),
              m('c0-1', t('马上被 fa（F）抵消', 'すぐ fa（F）で打ち消される', 'immediately cancelled by fa (F)'), 'below'),
            ],
            title: t('一闪而过的 Lydian 色彩', 'ちらりと見えるリディアの色', 'A flash of Lydian colour'),
            steps: [
              t('Lydian 是大调升高第四级（fi），所以 II 变成大三和弦（OMT 写成 II♯，♯ 表示三音被升高）。如果 II 接到 V，应该看作副属 V/V。', 'リディアは長調の第 4 音を上げた（fi）もの。だから II が長三和音（OMT は II♯ と書き、♯ は 3 音が上がったことを示す）。II が V に進むなら副属 V/V と見る。', 'Lydian is major with a raised 4th (fi), so II becomes major (OMT writes II♯, the sharp marking the raised third). If II goes to V, read it as an applied V/V.'),
              t('最常见的是 lydian cadence II♯–IV–I：II 的 fi 马上被 IV 的 fa 抵消，内声部有半音线条。整首歌真正在 Lydian 里的流行歌很少。', 'いちばん多いのはリディアン・カデンツ II♯–IV–I。II の fi がすぐ IV の fa で打ち消され、内声に半音の線。曲全体がリディアのポップスは少ない。', 'The commonest is the lydian cadence II♯–IV–I: II’s fi is immediately cancelled by IV’s fa, with a chromatic inner line. Pop songs truly in Lydian throughout are rare.'),
            ] },
          { type: 'choice', ref: 'omt-pb-modal-schemas', audio: { notes: [[50, 57, 62, 66], [53, 57, 60, 65], [48, 55, 64, 72]], mode: 'chords' },
            prompt: t('听：D – F – C（C 大调），这是？', '聴いて：D – F – C（ハ長調）。これは？', 'Listen: D – F – C in C. This is…'),
            options: [t('lydian cadence II♯–IV–I', 'リディアン・カデンツ II♯–IV–I', 'the lydian cadence II♯–IV–I'), t('双重变格', 'ダブル・プラガル', 'the double plagal'), t('正格终止', '正格終止', 'an authentic cadence')], answer: 0,
            hint: t('D 大三里有 F♯。', 'D の長三和音に F♯。', 'D major contains F♯.'),
            explain: t('D（II♯，带 fi）→ F（IV，fa）→ C：Lydian 的颜色一闪而过。', 'D（II♯、fi）→ F（IV、fa）→ C。リディアの色が一瞬。', 'D (II♯ with fi) → F (IV with fa) → C: a flash of Lydian.') },
          { type: 'choice', ref: 'omt-pb-modal-schemas',
            prompt: t('C 大调里 D 大三接到 G，应该怎么理解？', 'ハ長調で D の長三和音が G に進む。どう考える？', 'In C, a D major chord moving to G is best understood as…'),
            options: [t('副属 V/V', '副属 V/V', 'an applied V/V'), t('Lydian 的 II♯', 'リディアの II♯', 'Lydian II♯'), t('Dorian 的 IV', 'ドリアの IV', 'Dorian IV')], answer: 0,
            hint: t('接到 V 就是在指向 V。', 'V に進むなら V を指している。', 'Going to V means pointing at V.'),
            explain: t('II 接到 V 时（古典里常见）看作副属 V/V；只有不去 V 时才需要 II♯ 这个 Lydian 标签。', 'II が V に進むなら副属 V/V。V に行かない時だけリディアの II♯ と呼ぶ。', 'When II goes to V, call it V/V; the Lydian label II♯ is for when it goes elsewhere.') },
          { type: 'choice', ref: 'omt-pb-modal-schemas',
            prompt: t('Lydian 的颜色音是？', 'リディアの色の音は？', 'Lydian’s colour note is…'),
            options: [t('fi（升高的第四级）', 'fi（上がった第 4 音）', 'fi (raised 4th)'), t('te', 'te', 'te'), t('le', 'le', 'le')], answer: 0,
            hint: t('它让 II 变成大三。', 'これで II が長三に。', 'It makes II major.'),
            explain: t('Lydian = 大调升高第四级 fi；II 里的三音就是 fi。', 'リディア = 長調の第 4 音を上げた fi。II の 3 音が fi。', 'Lydian is major with fi; the third of II is fi.') },
        ],
      },
      {
        title: t('用耳朵分辨调式', '耳で旋法を見分ける', 'Identifying modes by ear'),
        cards: [
          { type: 'guide', ref: 'omt-pb-modal-schemas',
            visual: { kind: 'blocks', rows: [
              { label: '1', cells: cells({ text: t('主和弦是大还是小？', '主和音は長か短か？', 'major or minor tonic?'), lit: true }) },
              { label: '2', cells: cells({ text: t('第七级：ti 还是 te？', '第 7 音：ti か te か？', '7th: ti or te?') }) },
              { label: '3', cells: cells({ text: t('再听 fi（大）或 la（小）', 'fi（長）か la（短）を聴く', 'listen for fi (major) or la (minor)') }) },
            ] },
            tour: [
              m('row0', t('先分两大类', 'まず 2 つに分ける', 'two families first')),
              [m('row1', t('大主和弦 + te → Mixolydian；小主和弦 + ti → 小调', '長い主和音 + te → ミクソリディア、短い主和音 + ti → 短調', 'major + te → Mixolydian; minor + ti → minor')), m('row2', t('fi → Lydian；la → Dorian', 'fi → リディア、la → ドリア', 'fi → Lydian; la → Dorian'), 'below')],
            ],
            title: t('三步走', '3 つの手順', 'Three steps'),
            steps: [
              t('第一步听主和弦的三音：大三（大调、Mixolydian、Lydian）还是小三（小调、Aeolian、Dorian）。', '1：主和音の 3 音を聴く。長三（長調・ミクソリディア・リディア）か短三（短調・エオリア・ドリア）か。', 'Step 1: the tonic triad — major (major, Mixolydian, Lydian) or minor (minor, Aeolian, Dorian)?'),
              t('第二步听第七级：主音下方全音（te）还是半音（ti）？大主和弦 + te 是 Mixolydian；小主和弦 + ti 是小调。还没确定就做第三步：大的听 fi（有就是 Lydian），小的听 la（有就是 Dorian，否则 Aeolian）。', '2：第 7 音。主音の全音下（te）か半音下（ti）か。長い主和音 + te ならミクソリディア、短い主和音 + ti なら短調。まだなら 3：長なら fi を（あればリディア）、短なら la を（あればドリア、なければエオリア）。', 'Step 2: the 7th — a whole step (te) or half step (ti) below the tonic? Major tonic + te is Mixolydian; minor tonic + ti is minor. Otherwise step 3: in major listen for fi (Lydian), in minor for la (Dorian, else Aeolian).'),
            ] },
          { type: 'choice', ref: 'omt-pb-modal-schemas',
            prompt: t('大主和弦，第七级是 te。这是？', '長い主和音で第 7 音が te。これは？', 'Major tonic with te. That is…'),
            options: ['Mixolydian', 'Lydian', 'Dorian'], answer: 0,
            hint: t('第二步就能确定。', '手順 2 で決まる。', 'Step 2 settles it.'),
            explain: t('大主和弦 + te = Mixolydian。', '長い主和音 + te = ミクソリディア。', 'Major tonic + te = Mixolydian.') },
          { type: 'choice', ref: 'omt-pb-modal-schemas',
            prompt: t('小主和弦，第七级是 te，第六级是 la。这是？', '短い主和音、第 7 音が te、第 6 音が la。これは？', 'Minor tonic, te, and la. That is…'),
            options: ['Dorian', 'Aeolian', t('小调（和声小调）', '短調（和声的）', 'minor (harmonic)')], answer: 0,
            hint: t('第三步：有 la。', '手順 3：la がある。', 'Step 3: la is present.'),
            explain: t('小主和弦、te（不是 ti），再加上 la → Dorian。', '短い主和音、te（ti ではない）、la → ドリア。', 'Minor tonic, te rather than ti, plus la → Dorian.') },
          { type: 'choice', ref: 'omt-pb-modal-schemas',
            prompt: t('小主和弦，第七级是 ti。这是？', '短い主和音で第 7 音が ti。これは？', 'Minor tonic with ti. That is…'),
            options: [t('小调', '短調', 'minor'), 'Dorian', 'Aeolian'], answer: 0,
            hint: t('导音 ti 是小调（和声小调）的标志。', '導音 ti は短調の目印。', 'The leading tone ti marks minor.'),
            explain: t('小主和弦加上升高的导音 ti，就是一般说的小调，不是调式。', '短い主和音と上がった導音 ti は普通の短調で、旋法ではない。', 'A minor tonic with the raised leading tone ti is ordinary minor, not a mode.') },
        ],
      },
    ],
  },

  // ======================= 五声和声 =======================
  {
    id: 'pentaharm', parent: 'pentatonic', prerequisites: ['triads', 'roman', 'functions'], section: 'basics', feature: 'chinese', icon: '5♪',
    title: t('五声音阶在和声里', 'ペンタトニックと和声', 'Pentatonic harmony'),
    blurb: t('五声音阶的音当和弦根音、五种旋转、同一音级的两种形态与五度的关系', 'ペンタトニックの音を和音の根音に、5 つの回転、同じ音度の 2 つの形、5 度との関係', 'Pentatonic notes as chord roots, five rotations, cross relations and fifths'),
    cards: [
      { type: 'guide', ref: 'omt2e-pentatonic-harmony',
        visual: { kind: 'piano', from: 60, to: 72, lit: [60, 62, 64, 67, 69], names: 'white' },
        tour: [
          m(['k60', 'k62', 'k64', 'k67', 'k69'], t('C D E G A：没有半音', 'C D E G A：半音がない', 'C D E G A: no semitones')),
          m(['k60', 'k67', 'k62', 'k69', 'k64'], t('也能用五度连出来：C G D A E', '5 度でもつながる：C G D A E', 'also a chain of fifths: C G D A E'), 'below'),
        ],
        title: t('五个音 没有半音', '5 つの音、半音なし', 'Five notes, no semitones'),
        steps: [
          t('五声音阶是五个音的音集：它是自然音阶和布鲁斯音阶的子集，特点是只有五个音而且没有半音。', 'ペンタトニックは 5 音の音集合。全音階とブルース音階の部分集合で、5 音だけで半音がないのが特徴。', 'The pentatonic collection has five notes; it is a subset of the diatonic and blues collections, distinctive for its five pitches and lack of semitones.'),
          t('它也能用连续五度构成：C G D A E 排好就是 C D E G A（自然音阶是 F C G D A E B 七个五度连在一起）。', '連続する 5 度でも作れる：C G D A E を並べると C D E G A（全音階は F C G D A E B の 7 つ）。', 'It can be built from fifths: C G D A E in order is C D E G A (the diatonic set is the seven fifths F C G D A E B).'),
        ] },
      { type: 'choice', ref: 'omt2e-pentatonic-harmony',
        prompt: t('五声音阶和自然音阶的关系？', 'ペンタトニックと全音階の関係は？', 'How does the pentatonic relate to the diatonic collection?'),
        options: [t('是它的子集', 'その部分集合', 'it is a subset of it'), t('比它多两个音', '2 音多い', 'it has two more notes'), t('毫无关系', '関係ない', 'unrelated')], answer: 0,
        hint: t('五个音都在 C D E F G A B 里。', '5 音とも C D E F G A B に入っている。', 'All five notes are in C D E F G A B.'),
        explain: t('C D E G A 全都属于 C 大调音阶，所以是它的子集。', 'C D E G A はすべてハ長調の音で、部分集合。', 'C D E G A all belong to C major — a subset.') },
      { type: 'choice', ref: 'omt2e-pentatonic-harmony',
        prompt: t('五声音阶里有几个半音音程（相邻音相差半音）？', 'ペンタトニックに半音（隣り合う音が半音）はいくつ？', 'How many semitones (adjacent notes a half step apart) does the pentatonic have?'),
        options: ['0', '1', '2'], answer: 0,
        hint: t('C D E G A：E–G、A–C 都是三度。', 'C D E G A：E–G・A–C は 3 度。', 'C D E G A: E–G and A–C are thirds.'),
        explain: t('五声音阶没有半音，这是它的特点。', 'ペンタトニックには半音がない。それが特徴。', 'No semitones at all — that is what makes it distinctive.') },
      { type: 'fill', ref: 'omt2e-pentatonic-harmony',
        prompt: t('用五度连出五声音阶：C – G – ___ – A – ___', '5 度でペンタトニック：C – G – ___ – A – ___', 'Pentatonic by fifths: C – G – ___ – A – ___'),
        bank: [opt('D', 'D'), opt('E', 'E'), opt('F', 'F'), opt('B', 'B')], answer: ['D', 'E'],
        hint: t('每次往上一个纯五度。', '毎回完全 5 度上。', 'Up a perfect fifth each time.'),
        explain: t('C G D A E：五个连续的五度；F 和 B 不在里面。', 'C G D A E。F と B は入らない。', 'C G D A E — five consecutive fifths; F and B are left out.') },
    ],
    branch: [
      {
        title: t('五种旋转：大五声与小五声', '5 つの回転：メジャーとマイナー', 'Five rotations: major and minor pentatonic'),
        cards: [
          { type: 'guide', ref: 'omt2e-pentatonic-harmony',
            visual: { kind: 'blocks', rows: [
              { label: t('大五声', 'メジャー', 'major'), cells: cells({ text: 'C', lit: true }, 'D', 'E', 'G', 'A') },
              { label: t('小五声', 'マイナー', 'minor'), cells: cells({ text: 'A', lit: true }, 'C', 'D', 'E', 'G') },
            ] },
            tour: [
              m('c0-0', t('从 C 开始', 'C から', 'starting on C')),
              m('c1-0', t('同样五个音 从 A 开始', '同じ 5 音を A から', 'the same five notes from A'), 'below'),
            ],
            title: t('同样的五个音，从哪里开始', '同じ 5 音、どこから始めるか', 'Same five notes, different starting points'),
            steps: [
              t('五个音的音集有五种旋转（就像自然音阶有七种），而且这五种都不一样。', '5 音の集合には 5 つの回転があり（全音階に 7 つあるように）、5 つとも異なる。', 'A five-note collection has five rotations (as the diatonic has seven), and all five are different.'),
              t('流行音乐里最常用两种：大五声（C D E G A）和小五声（A C D E G）。', 'ポップスでよく使うのは 2 つ：メジャー（C D E G A）とマイナー（A C D E G）。', 'Pop music mostly uses two: major pentatonic (C D E G A) and minor pentatonic (A C D E G).'),
            ] },
          { type: 'choice', ref: 'omt2e-pentatonic-harmony',
            prompt: t('五声音阶有几种旋转？', 'ペンタトニックの回転はいくつ？', 'How many rotations does the pentatonic have?'),
            options: ['5', '7', '2'], answer: 0,
            hint: t('每个音都可以当起点。', 'どの音も始まりにできる。', 'Each note can be the start.'),
            explain: t('五个音各当一次起点，就有五种旋转。', '5 音それぞれを始まりにして 5 つ。', 'Five notes, five starting points.') },
          { type: 'choice', ref: 'omt2e-pentatonic-harmony',
            prompt: t('C 大五声和哪个小五声用同样的五个音？', 'C メジャー・ペンタと同じ 5 音のマイナー・ペンタは？', 'C major pentatonic shares its notes with which minor pentatonic?'),
            options: [t('A 小五声', 'A マイナー', 'A minor pentatonic'), t('C 小五声', 'C マイナー', 'C minor pentatonic'), t('E 小五声', 'E マイナー', 'E minor pentatonic')], answer: 0,
            hint: t('像关系大小调一样。', '平行調のように。', 'Like relative keys.'),
            explain: t('C D E G A 从 A 开始就是 A C D E G，A 小五声。', 'C D E G A を A から並べると A C D E G。', 'C D E G A from A is A C D E G — A minor pentatonic.') },
          { type: 'match', ref: 'omt2e-pentatonic-harmony',
            prompt: t('五声音阶 ↔ 音', 'ペンタトニック ↔ 音', 'Pentatonic ↔ notes'),
            pairs: [[t('C 大五声', 'C メジャー', 'C major pentatonic'), 'C D E G A'], [t('A 小五声', 'A マイナー', 'A minor pentatonic'), 'A C D E G'], [t('G 大五声', 'G メジャー', 'G major pentatonic'), 'G A B D E']],
            hint: t('大五声 = 1 2 3 5 6。', 'メジャー = 1 2 3 5 6。', 'Major = 1 2 3 5 6.'),
            explain: t('大五声是大调的 1 2 3 5 6；小五声是同一组音从第 6 个开始。', 'メジャーは長調の 1 2 3 5 6、マイナーは同じ音を 6 から。', 'Major pentatonic is 1 2 3 5 6 of major; the minor uses the same notes from 6.') },
        ],
      },
      {
        title: t('五声音阶当和弦根音', 'ペンタトニックを和音の根音に', 'Pentatonic notes as chord roots'),
        cards: [
          { type: 'guide', ref: 'omt2e-pentatonic-harmony', demo: { play: [[48, 55, 64], [50, 57, 66], [52, 59, 68], [55, 62, 71], [57, 64, 73]] },
            visual: { kind: 'blocks', rows: [
              { label: t('根音', '根音', 'roots'), cells: cells('C', 'D', 'E', 'G', 'A') },
              { label: t('全用大三', 'すべて長三', 'all major'), cells: cells('C', { text: 'D', sub: 'F♯' }, { text: 'E', sub: 'G♯', lit: true }, { text: 'G', sub: 'B' }, { text: 'A', sub: 'C♯' }) },
            ] },
            tour: [
              m('row0', t('五声音阶决定根音', 'ペンタトニックが根音を決める', 'the pentatonic gives the roots')),
              m(['c1-1', 'c1-2', 'c1-4'], t('和弦音跑出五声音阶', '和音の音がペンタからはみ出る', 'chord tones leave the pentatonic'), 'below'),
            ],
            title: t('根音是五声的 和弦性质随意', '根音はペンタ、和音の種類は自由', 'Pentatonic roots, any chord quality'),
            steps: [
              t('摇滚里常把五声音阶的音当和弦根音；和弦可以是大三、小三、强力和弦（只有根音和五音）或加了别的音。', 'ロックではペンタトニックの音を和音の根音にすることが多い。和音は長三・短三・パワーコード（根音と 5 音だけ）や付加音つきなど何でもよい。', 'Rock often uses pentatonic notes as chord roots; the chords can be major, minor, power chords (root and fifth only) or anything else.'),
              t('因为和弦性质很自由，所有和弦音合起来往往不只五声音阶，甚至不属于任何七声调式。也因此判断时看低音（根音）比较可靠。', '和音の種類が自由なので、全部の和音の音を合わせるとペンタトニックを越え、どの 7 音旋法にも当てはまらないことがある。だから判断はバス（根音）を見る方が確か。', 'Because quality is free, the combined chord tones often go beyond the pentatonic, even beyond any seven-note mode — which is why the bass (roots) is the more reliable guide.'),
            ] },
          { type: 'choice', ref: 'omt2e-pentatonic-harmony',
            prompt: t('五声和声里，什么来自五声音阶？', 'ペンタトニック和声で、ペンタから来るのは何？', 'In pentatonic harmony, what comes from the pentatonic scale?'),
            options: [t('和弦的根音（低音）', '和音の根音（バス）', 'the chord roots (bass)'), t('每个和弦的所有音', '各和音のすべての音', 'every note of every chord'), t('速度', 'テンポ', 'the tempo')], answer: 0,
            hint: t('和弦性质可以随意。', '和音の種類は自由。', 'Chord quality is free.'),
            explain: t('五声音阶决定根音；和弦本身可以是大三、小三、强力和弦等。', 'ペンタが根音を決め、和音自体は長三・短三・パワーコードなど。', 'The scale gives the roots; the chords can be major, minor, power chords and so on.') },
          { type: 'choice', ref: 'omt2e-pentatonic-harmony',
            prompt: t('强力和弦里有哪几个音？', 'パワーコードの音は？', 'What does a power chord contain?'),
            options: [t('根音和五音', '根音と 5 音', 'root and fifth'), t('根音和三音', '根音と 3 音', 'root and third'), t('根音、三音和七音', '根音・3 音・7 音', 'root, third and seventh')], answer: 0,
            hint: t('没有三音。', '3 音がない。', 'No third.'),
            explain: t('强力和弦只有根音和五音，没有三音，所以不分大小。', 'パワーコードは根音と 5 音だけで 3 音がなく、長短がない。', 'Root and fifth only — no third, so neither major nor minor.') },
          { type: 'choice', ref: 'omt2e-pentatonic-harmony',
            prompt: t('C 五声的根音上全用大三和弦，和弦音合起来还是五声音阶吗？', 'C ペンタの根音にすべて長三和音を乗せると、全体はまだペンタ？', 'Major triads on every C-pentatonic root: is the total still pentatonic?'),
            options: [t('不是 多出 F♯ G♯ B C♯ 等', 'いいえ、F♯ G♯ B C♯ などが加わる', 'no — F♯ G♯ B C♯ and others appear'), t('是 仍然是 C D E G A', 'はい、C D E G A のまま', 'yes, still C D E G A'), t('只多一个音', '1 音だけ増える', 'only one extra note')], answer: 0,
            hint: t('D 大三里有 F♯。', 'D の長三に F♯。', 'D major contains F♯.'),
            explain: t('D、E、A 大三分别带来 F♯、G♯、C♯，G 大三带来 B，总的音集远不止五个音。', 'D・E・A の長三和音が F♯・G♯・C♯、G が B をもたらし、5 音を大きく超える。', 'D, E and A major bring F♯, G♯, C♯, and G brings B — far beyond five notes.') },
        ],
      },
      {
        title: t('同一音级的两种形态', '同じ音度の 2 つの形', 'Cross relations'),
        cards: [
          { type: 'guide', ref: ['omt2e-pentatonic-harmony', 'omt2e-mixture'], demo: { play: [[48, 52, 55], [51, 55, 58], [48, 52, 55]] },
            visual: { kind: 'blocks', rows: [{ arrows: true, cells: cells({ text: 'C', sub: 'E = mi' }, { text: 'E♭', sub: 'E♭ = me', lit: true }, { text: 'C', sub: 'E = mi' }) }] },
            tour: [
              m(['c0-0', 'c0-1'], t('mi 和 me 先后出现', 'mi と me が続けて', 'mi then me')),
              m('c0-1', t('根音 E♭ 也在五声里（C 小五声）', '根音 E♭ もペンタ（C マイナー）', 'E♭ is a pentatonic root too (C minor pentatonic)'), 'below'),
            ],
            title: t('mi 与 me、la 与 le', 'mi と me、la と le', 'mi and me, la and le'),
            steps: [
              t('在五声根音上用平行的大三和弦，常会让"同一个音级"以两种形态出现，例如 mi 和 me、la 和 le——这叫音级冲突或交错关系。', 'ペンタの根音に平行な長三和音を乗せると、「同じ音度」が 2 つの形で現れることがある。mi と me、la と le など。これを音度の衝突・対斜という。', 'Parallel major triads on pentatonic roots often bring the "same" scale degree in two forms, such as mi and me or la and le — called scale-degree conflict or cross relation.'),
              t('OMT 提到，这种五声根音配平行大三和弦的写法在吉他上很顺手（横按和弦平移）。', 'OMT によれば、ペンタの根音に平行な長三和音という書き方はギターで弾きやすい（バレーコードの平行移動）。', 'OMT notes that pentatonic roots with parallel major triads suit the guitar well (sliding barre chords).'),
            ] },
          { type: 'choice', ref: 'omt2e-pentatonic-harmony',
            prompt: t('C 大三之后接 E♭ 大三，哪两个音级形成交错关系？', 'C の長三和音のあと E♭ の長三和音。対斜になる 2 つの音度は？', 'C major then E♭ major: which two forms of one degree clash?'),
            options: [t('mi（E）与 me（E♭）', 'mi（E）と me（E♭）', 'mi (E) and me (E♭)'), t('do 与 di', 'do と di', 'do and di'), t('sol 与 si', 'sol と si', 'sol and si')], answer: 0,
            hint: t('C 大三的三音 vs E♭ 的根音。', 'C の 3 音と E♭ の根音。', 'C’s third vs E♭’s root.'),
            explain: t('C 大三里有 E（mi），下一个和弦的根音是 E♭（me）。', 'C の長三に E（mi）、次の根音が E♭（me）。', 'C major has E (mi); the next root is E♭ (me).') },
          { type: 'choice', ref: 'omt2e-pentatonic-harmony',
            prompt: t('为什么说五声根音配平行大三和弦"很适合吉他"？', 'ペンタの根音と平行な長三和音が「ギター向き」なのはなぜ？', 'Why does "pentatonic roots + parallel major triads" suit the guitar?'),
            options: [t('同一个横按和弦指型平移就行', '同じバレーの形を平行移動するだけ', 'one barre shape just slides along'), t('吉他只能弹五个音', 'ギターは 5 音しか弾けない', 'guitars only play five notes'), t('因为没有低音', 'バスがないから', 'there is no bass')], answer: 0,
            hint: t('想想横按。', 'バレーを考えて。', 'Think barre chords.'),
            explain: t('同样性质的和弦用同一个横按指型在指板上平移，根音按五声音阶走。', '同じ種類の和音は同じバレーの形で平行移動、根音はペンタに沿う。', 'Same-quality chords use one barre shape slid along the neck, with roots following the pentatonic.') },
          { type: 'choice', ref: 'omt2e-pentatonic-harmony',
            prompt: t('判断一个五声和声进行时，最可靠的线索是？', 'ペンタトニック和声の進行を判断する時、いちばん確かな手がかりは？', 'The most reliable clue to a pentatonic progression is…'),
            options: [t('低音（根音）', 'バス（根音）', 'the bass (roots)'), t('每个和弦的三音', '各和音の 3 音', 'each chord’s third'), t('旋律的最高音', '旋律の最高音', 'the melody’s top note')], answer: 0,
            hint: t('和弦性质常常含糊。', '和音の種類はしばしばあいまい。', 'Chord quality is often ambiguous.'),
            explain: t('和弦性质可能含糊，但低音很清楚；OMT 的例子也是从低音读出五声。', '和音の種類があいまいでもバスははっきり。OMT の例もバスからペンタを読む。', 'Chord qualities can be ambiguous but the bass is clear; OMT’s examples read the pentatonic from the bass.') },
        ],
      },
      {
        title: t('五度与五声', '5 度とペンタトニック', 'Fifths and the pentatonic'),
        cards: [
          { type: 'guide', ref: ['omt2e-pentatonic-harmony', 'omt-pb-modal-schemas'], demo: { play: [[50, 57, 62, 66], [45, 57, 61, 64], [48, 55, 60, 64], [43, 55, 59, 62]] },
            visual: { kind: 'blocks', rows: [
              { label: t('两对五度', '5 度の 2 組', 'two fifth pairs'), arrows: true, cells: cells({ text: 'D' }, { text: 'A' }, { text: 'C', lit: true }, { text: 'G', lit: true }) },
              { label: t('另一种读法', '別の読み方', 'another reading'), cells: cells({ text: 'I – V – ♭VII – IV', sub: 'Mixolydian' }) },
            ] },
            tour: [
              m(['c0-0', 'c0-1'], t('一对五度', '5 度の 1 組', 'a pair of fifths')),
              m('row1', t('也能读成 Mixolydian 的双重变格 + V', 'ミクソリディアのダブル・プラガル + V とも読める', 'or a Mixolydian double plagal plus V'), 'below'),
            ],
            title: t('一样的进行，不止一种解释', '同じ進行、解釈は 1 つではない', 'One progression, more than one reading'),
            steps: [
              t('五声音阶能用五度连出来，所以五度运动的和弦进行常可用五声来理解，例如两对相隔全音的五度：D–A、C–G。', 'ペンタトニックは 5 度でつながるので、5 度進行の和音はペンタで説明できることが多い。例：全音離れた 2 組の 5 度 D–A・C–G。', 'Because the pentatonic is a chain of fifths, fifth-based progressions can often be heard pentatonically, such as two fifth pairs a whole step apart: D–A, C–G.'),
              t('同样的 D–A–C–G 也可以看作 D 调的 Mixolydian 双重变格 ♭VII–IV–I 再加上 V（I–V–♭VII–IV）。到底算五声还是 Mixolydian，OMT 认为是一个开放的问题。', '同じ D–A–C–G は D のミクソリディアのダブル・プラガル ♭VII–IV–I に V を加えた（I–V–♭VII–IV）とも見られる。ペンタかミクソリディアかは OMT でも開かれた問い。', 'The same D–A–C–G can also be a Mixolydian double plagal ♭VII–IV–I in D with a V added (I–V–♭VII–IV). OMT treats "pentatonic or Mixolydian?" as an open question.'),
            ] },
          { type: 'choice', ref: 'omt2e-pentatonic-harmony',
            prompt: t('D – A – C – G 里有哪两对五度？', 'D – A – C – G の 2 組の 5 度は？', 'Which two fifth pairs are in D – A – C – G?'),
            options: [t('D–A 与 C–G', 'D–A と C–G', 'D–A and C–G'), t('D–C 与 A–G', 'D–C と A–G', 'D–C and A–G'), t('A–C 与 G–D', 'A–C と G–D', 'A–C and G–D')], answer: 0,
            hint: t('相邻两个和弦根音相差五度。', '隣の根音が 5 度。', 'Neighbouring roots a fifth apart.'),
            explain: t('D 到 A、C 到 G 都是五度；两对之间相差一个全音。', 'D→A と C→G が 5 度、2 組の間は全音。', 'D→A and C→G are fifths, a whole step apart.') },
          { type: 'choice', ref: ['omt2e-pentatonic-harmony', 'omt-pb-modal-schemas'],
            prompt: t('把 D – A – C – G 读成 D 调，四个和弦的级数是？', 'D – A – C – G を D の調で読むと？', 'Read in D, the four chords are…'),
            options: ['I – V – ♭VII – IV', 'I – IV – V – I', 'vi – IV – I – V'], answer: 0,
            hint: t('C 在 D 调里是降七级。', 'D の調で C は ♭VII。', 'C is ♭VII in D.'),
            explain: t('D = I、A = V、C = ♭VII、G = IV：后面三个连起来就是双重变格的走法。', 'D = I、A = V、C = ♭VII、G = IV。', 'D = I, A = V, C = ♭VII, G = IV.') },
          { type: 'choice', ref: 'omt2e-pentatonic-harmony',
            prompt: t('这条进行到底是五声还是 Mixolydian？', 'この進行はペンタかミクソリディアか？', 'Is this progression pentatonic or Mixolydian?'),
            options: [t('两种读法都说得通 这是开放的问题', 'どちらの読みも成り立つ、開かれた問い', 'both readings work — an open question'), t('只能是五声', 'ペンタだけ', 'only pentatonic'), t('只能是 Mixolydian', 'ミクソリディアだけ', 'only Mixolydian')], answer: 0,
            hint: t('类别的界线不总是清楚。', '分類の境界は必ずしもはっきりしない。', 'Category lines are not always clear.'),
            explain: t('OMT 明说这种进行可以是五声也可以是 Mixolydian，怎样才算"典型的五声进行"是开放的问题。', 'OMT はペンタともミクソリディアとも言え、「典型的なペンタ進行」とは何かは開かれた問いだとしている。', 'OMT says it could be pentatonic and/or Mixolydian; what makes a quintessentially pentatonic progression is an open question.') },
        ],
      },
    ],
  },
];
