// Boss 跨章节客串的台词：每个关卡、每个角色各 3 句，内容都和这一关的主题有关（角色用自己的口吻评论这一关的概念或给一句提示）。
// 进阶 1–4 与综合测验用所属关卡的台词；章节测试按章、结业挑战各有自己的台词；复习用 learn_boss_lines.js 里的通用台词。
// 台词里出现的乐理事实都是这一关题卡与讲解里已经讲过的内容（依据见各关题卡的 ref），不引入新的事实。
// 零不用感叹号；没有任何角色说"杂鱼"。
const L = (zh, ja, en) => ({ zh, ja, en });

/** 每个关卡（主关与支线）：{ 角色: [3 句] } */
export const LEVEL_CAMEOS = {
  // ---------------- 第一章 · 入门 ----------------
  keys: {
    mimi: [L('E 和 F、B 和 C 之间没有黑键。这个我说了一百遍了。', 'E と F、B と C の間に黒鍵はない。百回言ったからね。', 'No black key between E–F or B–C. I’ve said it a hundred times.'), L('半音就是隔壁那个键，黑键白键都算。数清楚。', '半音は隣の鍵。黒鍵も白鍵も数えるの。ちゃんと数えて。', 'A half step is the very next key, black or white. Count properly.'), L('全音是两个半音。别一眼看成“隔一个白键”就完事。', '全音は半音二つ。「白鍵一つ飛ばし」で済ませないでよ。', 'A whole step is two half steps — not just “skip a white key”.')],
    sever: [L('升号升高半音，降号降低半音。定义清楚，才谈得上拼写。', 'シャープは半音上げ、フラットは半音下げ。定義が明確でこそ綴りがある。', 'A sharp raises a half step, a flat lowers one. Clear definitions come before spelling.'), L('同一个键可以有几个名字。名字由调性决定，不由手指决定。', '同じ鍵に名前はいくつもある。名前を決めるのは調だ。指ではない。', 'One key, several names. The key decides the name, not the finger.'), L('先数半音。和声的一切距离，都从这里开始。', 'まず半音を数えよ。和声のあらゆる距離はここから始まる。', 'Count half steps first. Every distance in harmony starts here.')],
    noa: [L('弹一下 E，再弹 F。听，挨得特别近吧。', 'E を弾いて、次に F。ほら、すごく近いでしょ。', 'Play E, then F. Hear how close they are?'), L('半音听起来有点“挤”，全音就宽松一点。', '半音はちょっと「詰まった」感じ、全音は少しゆったり。', 'A half step feels a bit squeezed; a whole step has more room.'), L('键盘上的距离，耳朵其实早就知道了。', '鍵盤の上の距離、耳はとっくに知ってるんだ。', 'Your ears already know the distances on the keyboard.')],
    jaz: [L('半音！爵士里到处都是半音接近音！', '半音！ジャズは半音のアプローチだらけ！', 'Half steps! Jazz is full of chromatic approach notes!'), L('同一个黑键，叫 F♯ 还是 G♭？看你要去哪儿！', '同じ黒鍵、F♯ か G♭ か？行き先次第！', 'Same black key — F♯ or G♭? Depends where you’re going!'), L('数半音要快，solo 的时候可没空慢慢数！', '半音は速く数えて。ソロ中にゆっくり数える暇はないぞ！', 'Count half steps fast — no time for that mid-solo!')],
    araya: [L('钢琴把八度分成十二个半音。这是一种选择，很好用的选择。', 'ピアノはオクターヴを十二の半音に分ける。一つの選択よ。とても便利な選択。', 'The piano splits the octave into twelve half steps. A choice — a very useful one.'), L('在钢琴上，升和降可能落在同一个键上。别的乐器未必这样。', 'ピアノではシャープとフラットが同じ鍵になる。ほかの楽器ではそうとは限らないわ。', 'On the piano, a sharp and a flat can share a key. Not every instrument works that way.'), L('先记住键盘上的距离。以后我们再去看键盘之外的。', 'まず鍵盤の上の距離を覚えて。鍵盤の外は、また今度。', 'Learn the keyboard’s distances first. We’ll look beyond the keyboard later.')],
    zero: [L('半音，是这里最小的单位。', '半音が、ここでの最小単位。', 'The half step is the smallest unit here.'), L('一个键，几个名字。名字是描述，不是本身。', '一つの鍵に、いくつもの名前。名前は記述で、実体ではない。', 'One key, several names. A name is a description, not the thing.'), L('数距离。以后你会只用数字。', '距離を数えて。いずれ数字だけを使うようになる。', 'Count distances. Later you will use only numbers.')],
  },
  staff: {
    mimi: [L('中央 C 写作 C4。数字别乱写。', '真ん中の C は C4。数字を適当に書かないで。', 'Middle C is C4. Don’t make up the number.'), L('高音谱号又叫 G 谱号，绕着 G 那条线画的。', 'ト音記号は G の線を中心に書くから G 記号。', 'The treble clef is the G clef — it curls around the G line.'), L('线和间要分清。数错一格就是另一个音。', '線と間を区別して。一つずれたら別の音。', 'Lines and spaces — miss one and it’s a different note.')],
    sever: [L('谱号决定每条线的名字。先看谱号。', '音部記号が各線の名を決める。まず記号を見よ。', 'The clef names every line. Look at the clef first.'), L('有多种谱号，是为了让不同音域少用加线。', '音部記号がいくつもあるのは、どの音域でも加線を減らすためだ。', 'Several clefs exist so each range needs fewer ledger lines.'), L('音高记号里的数字表示八度。C4 与 C5 不是同一个音。', '音名の数字はオクターヴを表す。C4 と C5 は同じ音ではない。', 'The number in pitch notation is the octave. C4 and C5 are not the same note.')],
    noa: [L('中音谱号？中提琴就用它。中间那条线是中央 C。', 'ハ音記号？ヴィオラが使うよ。真ん中の線が真ん中の C。', 'Alto clef? Violas use it. The middle line is middle C.'), L('五条线就像一段楼梯，音往上爬，音符也往上走。', '五線は階段みたい。音が上がると音符も上がる。', 'Five lines are like stairs — the note climbs, the dot climbs.'), L('看谱的时候，哼一哼，会更快记住。', '譜を見ながら口ずさむと、早く覚えられるよ。', 'Hum while you read — you’ll remember faster.')],
    jaz: [L('读谱要快！爵士手谱可不会等你！', '読譜は速く！ジャズの譜面は待ってくれない！', 'Read fast! A jazz chart won’t wait for you!'), L('C4 就是中央 C。记住它，其他都好找！', 'C4 が真ん中の C。これを覚えれば他は簡単！', 'C4 is middle C. Know it and everything else is easy!'), L('加线太多？换个谱号就清爽了！', '加線が多すぎ？音部記号を替えればすっきり！', 'Too many ledger lines? Switch clefs!')],
    araya: [L('五线谱是一种记法。还有很多传统，用别的方式记音。', '五線譜は一つの記法。音を別のやり方で記す伝統もたくさんあるわ。', 'The staff is one notation. Many traditions write sound differently.'), L('C4 这种名字，是给八度编了号。很方便的约定。', 'C4 のような名前は、オクターヴに番号を付けたもの。便利な約束ね。', 'Names like C4 number the octaves. A handy convention.'), L('读谱之前，先听一听这个音。', '譜を読む前に、その音を聴いてみて。', 'Before reading the note, listen to it.')],
    zero: [L('线与间，是一张坐标。', '線と間は、一つの座標。', 'Lines and spaces are coordinates.'), L('谱号改变的是读法，不是声音。', '音部記号が変えるのは読み方。音ではない。', 'A clef changes the reading, not the sound.'), L('C4。字母加数字，就能定位。', 'C4。文字と数字で、位置が決まる。', 'C4. A letter and a number fix the position.')],
  },
  rhythm: {
    mimi: [L('一个全音符等于四个四分音符。这都能错我会生气的。', '全音符は四分音符四つ。これを間違えたら怒るからね。', 'A whole note equals four quarters. Miss that and I’ll be mad.'), L('附点加的是原来时值的一半。别加成一整个。', '付点は元の長さの半分を足すの。丸ごと足さないで。', 'A dot adds half the original value. Not a whole one.'), L('连音线连起来的第二个音不再弹，只是延长。', 'タイでつないだ二つ目の音は弾き直さない。延ばすだけ。', 'The second note of a tie isn’t replayed — it just lasts longer.')],
    sever: [L('时值是比例关系。全、二分、四分，一级减半。', '音価は比例関係だ。全、二分、四分と、一段ごとに半分。', 'Note values are proportions: whole, half, quarter, each half the last.'), L('附点与连音线，作用相似，写法不同。', '付点とタイは働きが似ているが、書き方が違う。', 'Dots and ties do similar work, written differently.'), L('先算清楚时值，再谈节奏。', 'まず音価を正確に。リズムはそれからだ。', 'Get the values right before you talk about rhythm.')],
    noa: [L('长音让旋律喘口气，短音让它往前走。', '長い音は旋律の息つぎ、短い音は前へ進ませる。', 'Long notes let a melody breathe; short ones push it on.'), L('一边拍手一边数，比光看谱快多了。', '手を叩きながら数えると、譜を見るだけよりずっと早い。', 'Clap while you count — much faster than just reading.'), L('附点音符走起来有点“一瘸一拐”，挺好听的。', '付点のリズムはちょっと「よろける」感じ。いい響き。', 'Dotted rhythms limp a little. It sounds nice.')],
    jaz: [L('时值算对了，swing 才有底子！', '音価が正確でこそ、スウィングの土台ができる！', 'Get the values right — that’s the base of swing!'), L('连音线跨过小节线，切分就出来了！', 'タイが小節線をまたぐと、シンコペーションの出来上がり！', 'Tie across the bar line and there’s your syncopation!'), L('附点八分加十六分？我天天这么吹！', '付点八分に十六分？毎日そう吹いてるよ！', 'Dotted eighth plus sixteenth? I play that every day!')],
    araya: [L('音符的长短，在很多音乐里都按比例来分。', '音の長さは、多くの音楽で比率で分けられるの。', 'Many musics divide durations by proportion.'), L('有的传统不写时值，靠记忆和口传。', '音価を書かず、記憶と口伝えに頼る伝統もあるわ。', 'Some traditions don’t notate durations at all — memory carries them.'), L('一拍分成两份，是一种很常见的切法。', '一拍を二つに分けるのは、とても一般的な分け方ね。', 'Splitting a beat in two is a very common way to divide time.')],
    zero: [L('时值是二的幂。整齐的结构。', '音価は二の累乗。整った構造。', 'Durations are powers of two. A tidy structure.'), L('附点：原值乘一点五。', '付点：元の値の一・五倍。', 'A dot: the original value times one and a half.'), L('时间，也可以被数清楚。', '時間も、数えることができる。', 'Time, too, can be counted.')],
  },
  meter: {
    mimi: [L('六八拍是两大拍，每拍分三份。不是六拍！', '6/8 は大きく二拍、一拍が三つに分かれるの。六拍じゃない！', '6/8 is two big beats, each split in three. Not six!'), L('拍号上面那个数字是每小节几拍。看清楚。', '拍子記号の上の数字は一小節の拍数。よく見て。', 'The top number is beats per bar. Look carefully.'), L('跟着音乐点头，你点几下？数出来。', '音楽に合わせてうなずいて。何回？数えて。', 'Nod along. How many times? Count them.')],
    sever: [L('单拍子每拍分二，复拍子每拍分三。依据在细分。', '単純拍子は一拍を二つに、複合拍子は三つに分ける。根拠は細分だ。', 'Simple meters split the beat in two, compound in three. The grounds are the subdivision.'), L('三四拍与六八拍，八分音符一样多，组织不同。', '3/4 と 6/8、八分音符の数は同じ。組み立てが違う。', '3/4 and 6/8 hold the same eighths, organised differently.'), L('拍号是秩序的第一层。', '拍子記号は秩序の第一層だ。', 'The time signature is the first layer of order.')],
    noa: [L('六八拍走起来像在摇船，晃一晃。', '6/8 は舟をこぐみたいに揺れる。', '6/8 rocks like a boat.'), L('三拍子转一圈，二拍子往前走。', '三拍子はくるっと回る、二拍子は前へ歩く。', 'Triple meter turns; duple meter walks.'), L('先感觉重音落在哪儿，拍子就出来了。', 'まずアクセントの場所を感じて。拍子はそこから。', 'Feel where the accent lands, and the meter appears.')],
    jaz: [L('四四拍里我只认二、四拍！拍手打反拍！', '4/4 なら僕は 2 拍と 4 拍だけ！裏で手拍子！', 'In 4/4 I only care about 2 and 4! Clap the backbeat!'), L('六八拍的 swing？那是另一种摇法！', '6/8 のスウィング？それはまた別の揺れ！', 'Swing in 6/8? A whole different groove!'), L('拍子数对了，即兴才有地方落脚！', '拍子が数えられてこそ、アドリブの足場ができる！', 'Count the meter right and your solo has somewhere to land!')],
    araya: [L('有的音乐，一小节里是长短不等的拍。', '一小節の中に長さの違う拍がある音楽もあるわ。', 'In some musics, a bar holds beats of unequal length.'), L('二加三、三加二，这样的组合在很多地方都很自然。', '2+3、3+2 のような組み合わせは、多くの土地でとても自然なの。', 'Groupings like 2+3 or 3+2 feel natural in many places.'), L('拍子不只是数字，也是身体的感觉。', '拍子は数字だけじゃない。体の感覚でもあるの。', 'Meter isn’t just numbers. It’s a feeling in the body.')],
    zero: [L('拍号是一种分组规则。', '拍子記号は、一つのグループ分けの規則。', 'A time signature is a grouping rule.'), L('六个八分音符，可以分成二乘三，也可以三乘二。', '八分音符六つは、2×3 にも 3×2 にもなる。', 'Six eighths can be two times three, or three times two.'), L('分组不同，结构就不同。', 'グループが違えば、構造も違う。', 'A different grouping is a different structure.')],
  },
  intervals: {
    mimi: [L('数度数，起点那个音也算。C 到 E 是三度，不是二度。', '度数は出発の音も数える。C から E は 3 度、2 度じゃない。', 'Count the starting note. C to E is a third, not a second.'), L('数半音和数度数是两回事，别搞混。', '半音を数えるのと度数を数えるのは別物。混ぜないで。', 'Counting half steps and counting degrees are different things.'), L('听音程的时候别猜，先在心里唱一下。', '音程を聴くときは当てずっぽうにしないで。心の中で歌ってみて。', 'Don’t guess intervals by ear — sing them in your head first.')],
    sever: [L('音程有两个属性：度数和半音数。缺一不可。', '音程には度数と半音数の二つの性質がある。どちらも欠かせない。', 'An interval has two properties: its number and its size in half steps.'), L('纯五度七个半音。这是和声的支柱。', '完全 5 度は半音七つ。和声の柱だ。', 'A perfect fifth is seven half steps — a pillar of harmony.'), L('拼写决定度数。C 到 E♭ 是三度，不是二度。', '綴りが度数を決める。C から E♭ は 3 度で、2 度ではない。', 'Spelling decides the number. C to E♭ is a third, not a second.')],
    noa: [L('两个音一起响，听它们“合不合”。', '二つの音を一緒に鳴らして、「合うか」聴いてみて。', 'Sound two notes together and hear whether they blend.'), L('五度听起来很空、很稳，像大地。', '5 度は空っぽで安定した響き、大地みたい。', 'A fifth sounds open and steady, like the ground.'), L('大三度亮，小三度暗一点。耳朵分得出来。', '長 3 度は明るく、短 3 度は少し暗い。耳でわかるよ。', 'A major third is bright, a minor third a bit darker. Your ears can tell.')],
    jaz: [L('三度和七度！这是和弦的灵魂！', '3 度と 7 度！和音の魂だ！', 'Thirds and sevenths! The soul of a chord!'), L('音程听得准，即兴才能想到哪儿弹到哪儿！', '音程が聴き取れてこそ、思った音を弾けるんだ！', 'Hear intervals and you can play what you hear!'), L('五度往上叠，一下就到 Lydian 了！', '5 度を積み上げたら、すぐリディアン！', 'Stack fifths upward and you’re in Lydian in no time!')],
    araya: [L('五度和八度，在很多传统里都是最重要的音程。', '5 度とオクターヴは、多くの伝統で最も大切な音程なの。', 'Fifths and octaves are central in many traditions.'), L('钢琴上的三度，和纯律的三度，其实不完全一样。', 'ピアノの 3 度と純正律の 3 度は、実は少し違うの。', 'A piano’s third and a just third aren’t quite the same.'), L('先用耳朵听距离，再用名字记住它。', 'まず耳で距離を聴いて、それから名前で覚えて。', 'Hear the distance first, then remember its name.')],
    zero: [L('音程，就是两个数字的差。', '音程とは、二つの数の差。', 'An interval is the difference between two numbers.'), L('七个半音。你叫它纯五度。', '半音七つ。あなたはそれを完全 5 度と呼ぶ。', 'Seven half steps. You call it a perfect fifth.'), L('名字之外，还有距离。', '名前の外に、距離がある。', 'Beyond the name, there is distance.')],
  },
  intervalqual: {
    mimi: [L('转位以后度数相加等于九。三度转位就是六度。', '転回すると度数の和は 9。3 度を転回すれば 6 度。', 'Inverted intervals add up to nine. A third inverts to a sixth.'), L('大变小、小变大，增变减。性质也要跟着翻。', '長は短に、短は長に、増は減に。種類も一緒に反転するの。', 'Major becomes minor, minor major, augmented diminished.'), L('超过八度就是复音程。C4 到 D5 是九度！', 'オクターヴを超えたら複音程。C4 から D5 は 9 度！', 'Past the octave it’s compound. C4 to D5 is a ninth!')],
    sever: [L('纯音程只有一、四、五、八度。其余是大小。', '完全音程は 1・4・5・8 度だけだ。ほかは長短。', 'Only unisons, fourths, fifths and octaves are perfect. The rest are major or minor.'), L('增四度和减五度，等音，但拼写不同。', '増 4 度と減 5 度は異名同音だが、綴りが違う。', 'An augmented fourth and a diminished fifth sound alike but are spelled differently.'), L('性质由半音数和度数共同决定。', '種類は半音数と度数によって決まる。', 'Quality comes from half steps and number together.')],
    noa: [L('三全音听起来挺紧张的，想往外跑。', '三全音はかなり緊張してて、どこかへ行きたがる。', 'The tritone sounds tense — it wants to move.'), L('同样两个音，倒过来摆，味道就变了。', '同じ二つの音でも、上下を逆にすると味が変わる。', 'Flip the same two notes and the flavour changes.'), L('九度比二度宽多了，听起来松一点。', '9 度は 2 度よりずっと広くて、ゆったり聴こえる。', 'A ninth is much wider than a second — it breathes more.')],
    jaz: [L('九度、十一度、十三度！复音程就是我的延伸音！', '9 度、11 度、13 度！複音程は僕のテンションだ！', 'Ninths, elevenths, thirteenths! Compound intervals are my extensions!'), L('三全音是属七的心脏！', '三全音は属七の心臓！', 'The tritone is the heart of a dominant seventh!'), L('增五度？那就是 ♯5，altered 里有它！', '増 5 度？それは ♯5、オルタードに入ってる！', 'Augmented fifth? That’s ♯5 — it’s in the altered scale!')],
    araya: [L('“大”“小”“纯”这些名字，是西方体系的分类。', '「長」「短」「完全」という名前は、西洋の体系の分類ね。', '“Major”, “minor”, “perfect” are the Western system’s categories.'), L('有的体系里，三度不止大和小两种。', '3 度が長と短の二種類だけではない体系もあるわ。', 'Some systems have more than two sizes of third.'), L('名字很有用。但别忘了，先有声音。', '名前は便利。でも忘れないで、先に音があるの。', 'Names are useful. But remember, the sound comes first.')],
    zero: [L('转位：十二减去原来的半音数。', '転回：十二から元の半音数を引く。', 'Inversion: twelve minus the original size.'), L('九减度数。也是一种规则。', '9 から度数を引く。これも一つの規則。', 'Nine minus the number. Another rule.'), L('以后你会叫它“音程级”。', 'いずれ、それを「音程クラス」と呼ぶことになる。', 'Later you will call it an interval class.')],
  },
  major: {
    mimi: [L('全全半全全全半。背熟了再说别的。', '全全半全全全半。これを覚えてから次の話。', 'Whole, whole, half, whole, whole, whole, half. Memorise it first.'), L('七个字母一个都不能重复。G 大调要写 F♯。', '七つの文字は一つも重ねちゃダメ。G 長調は F♯ と書くの。', 'Seven letters, none repeated. G major needs F♯.'), L('升号调：最后一个升号往上半音就是主音。', 'シャープの調：最後のシャープの半音上が主音。', 'Sharp keys: a half step above the last sharp is the tonic.')],
    sever: [L('调号是一组约定，告诉你哪些音始终升降。', '調号は約束事だ。どの音が常に変化するかを示す。', 'A key signature is a convention: which notes are always altered.'), L('降号调：倒数第二个降号就是调名。', 'フラットの調：後ろから二番目のフラットが調名だ。', 'Flat keys: the second-to-last flat names the key.'), L('音级的名称——主、属、下属——是功能的起点。', '音度の名前——主・属・下属——が機能の出発点だ。', 'Degree names — tonic, dominant, subdominant — are where function begins.')],
    noa: [L('大调音阶唱一遍，最后那个半音，像回到家门口。', '長音階を歌ってみて。最後の半音、家の玄関に着いた感じ。', 'Sing a major scale — that last half step feels like reaching your front door.'), L('七级离主音只有半音，所以它特别想回去。', '第 7 音は主音まで半音だけ。だからすごく帰りたがるんだ。', 'The seventh degree is a half step from home, so it longs to return.'), L('换个调，整首歌一起挪，旋律还是那个旋律。', '調を変えると曲全体が移る。旋律は同じ旋律のまま。', 'Change key and the whole song moves — the tune stays the tune.')],
    jaz: [L('大调？那就是 Ionian！爵士里叫它家！', '長音階？それはイオニアン！ジャズの家だ！', 'Major? That’s Ionian — home base in jazz!'), L('调号背熟，看到降 E 调手谱才不慌！', '調号を覚えれば、E♭ の譜面を見ても慌てない！', 'Know your key signatures and an E♭ chart won’t scare you!'), L('大调第四级升高？那就是 Lydian 的颜色！', '長音階の 4 度を上げると？リディアンの色だ！', 'Raise the fourth of major? That’s Lydian colour!')],
    araya: [L('全全半全全全半，是众多音阶里的一种。', '全全半全全全半は、たくさんある音階の一つ。', 'Whole-whole-half… is one scale among many.'), L('它太常见了，常见到我们以为它就是“音阶”本身。', 'あまりに一般的で、それが「音階」そのものだと思ってしまうの。', 'It’s so common we forget it’s just one kind of scale.'), L('有的传统里，主音只是起点，不一定是“家”。', '主音が出発点にすぎず、「家」とは限らない伝統もあるわ。', 'In some traditions the tonic is just a starting point, not necessarily “home”.')],
    zero: [L('2 2 1 2 2 2 1。一个序列。', '2 2 1 2 2 2 1。一つの数列。', '2 2 1 2 2 2 1. A sequence.'), L('调号，是这个序列移位以后的记法。', '調号は、その数列を移したときの記法。', 'A key signature notates the sequence transposed.'), L('十二个调，同一个结构。', '十二の調、同じ一つの構造。', 'Twelve keys, one structure.')],
  },
  minor: {
    mimi: [L('三种小调：自然、和声、旋律。别只记得一种。', '短音階は三種類：自然・和声・旋律。一つだけ覚えないで。', 'Three minors: natural, harmonic, melodic. Don’t remember just one.'), L('关系调同调号，同主音调同主音。名字都说清楚了。', '平行調は同じ調号、同主調は同じ主音。名前の通りでしょ。', 'Relative keys share a signature; parallel keys share a tonic. The names say it.'), L('和声小调升高第七级。A 小调就是 G♯。', '和声短音階は第 7 音を上げる。イ短調なら G♯。', 'Harmonic minor raises the seventh. In A minor that’s G♯.')],
    sever: [L('升高导音，是为了让 V 成为大三和弦。', '導音を上げるのは、V を長三和音にするためだ。', 'The leading tone is raised so that V becomes major.'), L('关系小调在大调主音下方小三度。', '平行短調は長調の主音の短 3 度下にある。', 'The relative minor lies a minor third below the major tonic.'), L('和声小调的六、七级之间是增二度。', '和声短音階の第 6・7 音の間は増 2 度だ。', 'Harmonic minor has an augmented second between degrees six and seven.')],
    noa: [L('和声小调那个增二度，唱起来有点异国味。', '和声短音階の増 2 度、歌うとちょっと異国風。', 'That augmented second in harmonic minor sounds a bit exotic when sung.'), L('旋律小调往上唱很顺，往下又变回自然小调。', '旋律短音階は上りが滑らか、下りは自然短音階に戻る。', 'Melodic minor flows going up, and turns natural coming down.'), L('小调不一定悲伤，只是颜色暗一点。', '短調は悲しいとは限らない。色が少し暗いだけ。', 'Minor isn’t always sad — just a darker colour.')],
    jaz: [L('旋律小调！爵士小调！一整套调式都从它来！', '旋律短音階！ジャズ・マイナー！調式が丸ごとここから出てくる！', 'Melodic minor! Jazz minor! A whole family of modes comes from it!'), L('小调 ii–V–i，半减七接属七！', 'マイナーの ii–V–i、半減七から属七へ！', 'Minor ii–V–i: half-diminished to dominant!'), L('和声小调的五级？Phrygian dominant，带劲！', '和声短音階の 5 番目？フリジアン・ドミナント、かっこいい！', 'The fifth mode of harmonic minor? Phrygian dominant — spicy!')],
    araya: [L('“大调明亮、小调悲伤”是一种文化习惯。', '「長調は明るく、短調は悲しい」は文化的な習慣なの。', '“Major bright, minor sad” is a cultural habit.'), L('增二度在很多音乐传统里都很常见。', '増 2 度は多くの音楽の伝統でよく見られるわ。', 'The augmented second is common in many traditions.'), L('三种小调，说明一个体系里也有选择。', '三種類の短音階は、一つの体系の中にも選択があることを示すの。', 'Three minors show that even one system holds choices.')],
    zero: [L('同一组音，换一个起点，就是关系调。', '同じ音の組で起点を替えれば、平行調。', 'Same set, different starting point: the relative key.'), L('升高一个音，结构就变了。', '一つの音を上げれば、構造が変わる。', 'Raise one note and the structure changes.'), L('三种小调。三种规则。', '三つの短音階。三つの規則。', 'Three minors. Three rules.')],
  },
  modes: {
    mimi: [L('Lydian 最亮，Locrian 最暗。顺序背下来。', 'リディアンが一番明るく、ロクリアンが一番暗い。順番を覚えて。', 'Lydian is brightest, Locrian darkest. Learn the order.'), L('起始音也得是主音，才算这个调式。', '出発の音が主音でもあって、初めてその旋法になるの。', 'The starting note must also be the tonic for it to count.'), L('Dorian 是小调，但第六级是大六度。别漏了。', 'ドリアンは短調系、でも第 6 音は長 6 度。見落とさないで。', 'Dorian is minor-ish, but its sixth is major. Don’t miss it.')],
    sever: [L('调式的特征音，决定它和大小调的区别。', '旋法の特性音が、長短調との違いを決める。', 'A mode’s characteristic tone sets it apart from major and minor.'), L('Mixolydian：大调降低第七级。', 'ミクソリディアン：長調の第 7 音を下げたもの。', 'Mixolydian: major with a lowered seventh.'), L('同一组白键，七个不同的主音，七种调式。', '同じ白鍵で、主音が七つ違えば七つの旋法。', 'The same white keys, seven tonics, seven modes.')],
    noa: [L('Dorian 带一点爵士的味道，又有点民谣。', 'ドリアンは少しジャズっぽくて、少しフォークっぽい。', 'Dorian has a touch of jazz and a touch of folk.'), L('只改一个音，颜色就整个变了。听得出来吧？', '一音変えるだけで、色ががらっと変わる。わかるでしょ？', 'Change one note and the whole colour shifts. Hear it?'), L('Phrygian 开头那个小二度，一听就很特别。', 'フリジアンの最初の短 2 度、聴けばすぐ特別だとわかる。', 'That opening half step in Phrygian is instantly distinctive.')],
    jaz: [L('Dorian 配 ii，Mixolydian 配 V！调式我张口就来！', 'ii にはドリアン、V にはミクソリディアン！旋法ならすぐ出てくる！', 'Dorian on ii, Mixolydian on V! I’ve got modes on tap!'), L('So What 整首就在 Dorian 上！', '《ソー・ホワット》は丸ごとドリアン！', 'So What sits on Dorian the whole way!'), L('Lydian 的升四，一弹就飘起来！', 'リディアンの ♯4、弾けばふわっと浮く！', 'Lydian’s raised fourth — instant float!')],
    araya: [L('“调式”这个词，在不同文化里意思不太一样。', '「旋法」という言葉は、文化によって意味が少し違うの。', 'The word “mode” means different things in different cultures.'), L('七种教会调式，是一种整理声音的方法。', '七つの教会旋法は、音を整理する一つの方法。', 'The seven church modes are one way of organising sound.'), L('同一组音换个主音，世界就换了一个样子。', '同じ音で主音を替えれば、世界の見え方が変わる。', 'Same notes, new tonic — the world looks different.')],
    zero: [L('同一个集合，七种旋转。', '同じ集合、七つの回転。', 'One collection, seven rotations.'), L('中心换了，集合没换。', '中心は替わった。集合は替わらない。', 'The centre changed; the collection did not.'), L('明暗，是你给顺序起的名字。', '明暗は、あなたが順序に付けた名前。', 'Bright and dark are names you gave to an order.')],
  },
  pentatonic: {
    mimi: [L('五声音阶里没有半音。数一数就知道。', '五音音階に半音はない。数えればわかる。', 'No half steps in the pentatonic. Count and see.'), L('宫和角之间是大三度，靠它就能找到宫。', '宮と角の間は長 3 度。それで宮が見つかる。', 'Gong to jue is a major third — that’s how you find gong.'), L('同样五个音，停在哪个音上，就叫什么调式。', '同じ五つの音でも、どの音で止まるかで旋法の名前が決まる。', 'Same five notes — where it stops names the mode.')],
    sever: [L('五声音阶由五个连续的五度构成。', '五音音階は連続する五つの 5 度でできている。', 'The pentatonic is built from a chain of fifths.'), L('宫商角徵羽，五个音级各有名称。', '宮・商・角・徴・羽、五つの音度にはそれぞれ名前がある。', 'Gong, shang, jue, zhi, yu — each degree has its name.'), L('没有半音，就没有导音的倾向。', '半音がなければ、導音の傾向もない。', 'No half steps means no leading-tone pull.')],
    noa: [L('五个黑键随便弹，都好听。试试看。', '黒鍵五つを適当に弾いても、きれいに響く。やってみて。', 'Play the five black keys at random — it always sounds nice.'), L('五声旋律很好唱，没有难唱的半音。', '五音の旋律は歌いやすい。歌いにくい半音がないから。', 'Pentatonic tunes are easy to sing — no awkward half steps.'), L('停在羽上，就是另一种心情了。', '羽で止まると、また違う気分になる。', 'End on yu and it’s a different mood.')],
    jaz: [L('小调五声！吉他手最爱的那一把位！', 'マイナー・ペンタ！ギタリストが一番好きなポジション！', 'Minor pentatonic! Every guitarist’s favourite box!'), L('五声音阶加一个降五级，就是布鲁斯音阶！', 'ペンタに ♭5 を足したら、ブルース・スケール！', 'Add a flat five to the pentatonic and you’ve got the blues scale!'), L('五声 solo 简单？在 ii–V 上用好可不简单！', 'ペンタのソロは簡単？ii–V の上でうまく使うのは簡単じゃない！', 'Pentatonic solos easy? Not when you use them well over ii–V!')],
    araya: [L('五声音阶在世界很多地方都能听到。', '五音音階は世界の多くの場所で聴くことができるわ。', 'Pentatonic scales are heard in many parts of the world.'), L('宫商角徵羽，是中国传统给这五个音起的名字。', '宮商角徴羽は、中国の伝統がこの五つの音に付けた名前。', 'Gong, shang, jue, zhi, yu are the Chinese tradition’s names for these five.'), L('五个音，就够写一首好歌了。', '五つの音で、いい歌を作るには十分なの。', 'Five notes are enough for a good song.')],
    zero: [L('五个音，一串五度。', '五つの音、一連の 5 度。', 'Five notes, a chain of fifths.'), L('没有半音。一条约束。', '半音がない。一つの制約。', 'No half steps. A constraint.'), L('约束越少，组合越自由。', '制約が少ないほど、組み合わせは自由になる。', 'Fewer constraints, freer combinations.')],
  },
  texture: {
    mimi: [L('一个人清唱是单声部。这个都分不清不行。', '一人で無伴奏で歌うのは単声。これは区別して。', 'One voice alone is monophony. You have to know that.'), L('大家同一节奏换和弦，是主调，不是复调！', 'みんな同じリズムで和音を替えるのはホモフォニー、ポリフォニーじゃない！', 'Everyone moving together is homophony, not polyphony!'), L('几个人奏同一旋律、各加装饰，叫支声。', '何人かが同じ旋律を少しずつ飾って演奏するのはヘテロフォニー。', 'Several players decorating one tune — that’s heterophony.')],
    sever: [L('复调要求声部各自独立。反向进行是关键。', 'ポリフォニーは声部の独立を求める。反行が鍵だ。', 'Polyphony demands independent voices. Contrary motion is key.'), L('众赞歌是主调织体：节奏一致，和弦块状前进。', 'コラールはホモフォニー：リズムが揃い、和音が塊で進む。', 'A chorale is homophonic: shared rhythm, block chords.'), L('织体描述的是声部之间的关系。', 'テクスチュアは声部どうしの関係を記述する。', 'Texture describes the relationship between voices.')],
    noa: [L('两条线各走各的，又能一起好听，这就是复调。', '二本の線がそれぞれ歩いて、一緒にきれいに鳴る。それがポリフォニー。', 'Two lines walking their own way and still sounding good together — polyphony.'), L('一首歌里织体常常变：清唱、伴奏、对唱。', '一曲の中でテクスチュアはよく変わる。無伴奏、伴奏つき、掛け合い。', 'Texture often shifts within a song: solo, accompanied, call and answer.'), L('听的时候数一数，同时有几条线。', '聴きながら、同時に何本の線があるか数えてみて。', 'Count how many lines are going at once.')],
    jaz: [L('大乐队齐奏，每个人加点装饰——支声！', 'ビッグバンドのユニゾン、各自がちょっと飾る——ヘテロフォニー！', 'Big-band unison with everyone adding flourishes — heterophony!'), L('钢琴伴奏、我吹旋律，就是主调！', 'ピアノが伴奏、僕が旋律を吹く。それがホモフォニー！', 'Piano comps, I play the tune — homophony!'), L('集体即兴？那可是满满的复调！', '集団即興？それはポリフォニーたっぷり！', 'Collective improv? Polyphony galore!')],
    araya: [L('支声在很多传统音乐里很常见：大家唱同一旋律，各自变化。', 'ヘテロフォニーは多くの伝統音楽でよく見られる。同じ旋律を、それぞれが変えて。', 'Heterophony is common in many traditions: one tune, each voice varying it.'), L('织体，也是一种社会关系的声音。', 'テクスチュアは、人と人との関係の響きでもあるの。', 'Texture is also the sound of how people relate.'), L('一个人唱和一群人唱，是不同的世界。', '一人で歌うのと大勢で歌うのは、違う世界。', 'One voice and many voices are different worlds.')],
    zero: [L('织体：线的数量，和它们的关系。', 'テクスチュア：線の数と、その関係。', 'Texture: the number of lines and their relations.'), L('同步或独立。两种规则。', '同期か、独立か。二つの規則。', 'Synchronised or independent. Two rules.'), L('一条线，也是一种织体。', '一本の線も、一つのテクスチュア。', 'A single line is a texture too.')],
  },
};
