// 乐理闯关 · 旋律、对位与乐器：每张题卡标出依据（ref），只使用 references.js 中已登记、已核实的资料；解析用尽量通俗的话转述这些资料。
// 依据汇总（由 scripts/annotate-learn.mjs 生成）：
//   ref:ibmt-transposition ref:wiki-transposing ref:wiki-standard-tuning ref:agt-caged ref:omt2e-embellishing
//   ref:zhwiki-nct ref:omt-intervals ref:omt-species1 ref:omt2e-intro ref:omt-species2 ref:omt-species3
//   ref:omt-species4
// @refs-end

const t = (zh, ja, en) => ({ zh, ja, en });
const opt = (id, label) => ({ id, label });

const ALL = [
  {
    id: 'nonchord', section: 'melody', feature: 'nonchord', icon: '~',
    title: t('旋律里的"装饰音"', '旋律の「飾りの音」', 'Decorations in a melody'),
    blurb: t('经过音、辅助音、挂留', '経過音・刺繍音・掛留', 'Passing, neighbour and suspension'),
    cards: [
      { type: 'guide', ref: 'omt2e-embellishing', demo: { play: [[60], [62], [64], [64], [65], [64]] },
        title: t('不在和弦里的音', '和音にない音', 'Notes outside the chord'),
        steps: [
          t('旋律里有些音不属于当时的和弦，它们是来"装饰"的。', '旋律には、そのときの和音に属さない音があります。「飾り」です。', 'Some melody notes are not in the current chord — they are decorations.'),
          t('认它们的诀窍：看它是怎么来的（级进还是跳进）、又往哪儿去。', '見分けるコツ：どう来て（順次か跳躍か）、どこへ行くか。', 'The trick: how does it arrive (by step or leap) and where does it go?'),
          t('听：C–D–E（D 一路走过去），再听 E–F–E（F 出去又回来）。', '聴いて：C–D–E（D は通り過ぎる）、E–F–E（F は出て戻る）。', 'Listen: C–D–E (D walks through), then E–F–E (F steps out and back).'),
        ] },
      { type: 'choice', ref: 'omt2e-embellishing', audio: { notes: [60, 62, 64], mode: 'melody' },
        prompt: t('C 和 E 是和弦音，中间的 D 是？', 'C と E は和音の音。間の D は？', 'C and E are chord tones. The D in between is a…'),
        options: [t('经过音', '経過音', 'passing tone'), t('辅助音', '刺繍音', 'neighbour tone'), t('挂留音', '掛留音', 'suspension')], answer: 0,
        hint: t('它朝同一个方向一步一步走过去。', '同じ方向に一歩ずつ通り抜けます。', 'It keeps stepping in the same direction.'),
        explain: t('级进进入、再朝同方向级进离开：经过音。', '順次で入り、同じ方向へ順次で出る：経過音。', 'Approached by step and left by step in the same direction: a passing tone.') },
      { type: 'choice', ref: 'omt2e-embellishing', audio: { notes: [64, 65, 64], mode: 'melody' },
        prompt: t('E–F–E 里的 F 是？', 'E–F–E の F は？', 'In E–F–E, the F is a…'),
        options: [t('辅助音', '刺繍音', 'neighbour tone'), t('经过音', '経過音', 'passing tone'), t('逃音', '逸音', 'escape tone')], answer: 0,
        hint: t('出门一步，又回到原地。', '一歩出て、元に戻る。', 'One step out, then back home.'),
        explain: t('级进离开，再反方向级进回来：辅助音。', '順次で離れ、反対方向へ順次で戻る：刺繍音。', 'Stepped away and back the opposite way: a neighbour tone.') },
      { type: 'match', ref: 'omt2e-embellishing',
        prompt: t('装饰音 ↔ 走法', '飾りの音 ↔ 動き方', 'Embellishment ↔ how it moves'),
        pairs: [[t('经过音', '経過音', 'passing tone'), t('同方向级进穿过', '同じ方向へ順次で通過', 'steps through in one direction')], [t('辅助音', '刺繍音', 'neighbour'), t('级进出去再回来', '順次で出て戻る', 'steps out and back')], [t('倚音', '倚音', 'appoggiatura'), t('跳进来，反方向级进走', '跳躍で入り反対へ順次で出る', 'leaps in, steps away the other way')], [t('挂留', '掛留', 'suspension'), t('先保持，再级进下行', '保ってから順次下行', 'held over, then steps down')]],
        hint: t('看"怎么来"和"往哪儿去"。', '「どう来て」「どこへ行くか」を見る。', 'Look at the approach and the departure.'),
        explain: t('四种的区别都在进入和离开的方式上。', '4 つの違いは入り方と出方にあります。', 'All four differ only in how they are approached and left.') },
    ],
  },
  {
    id: 'counterpoint', section: 'melody', feature: 'counterpoint', icon: '⇅',
    title: t('两条旋律一起唱：一类对位', '2 本の旋律：第 1 類対位法', 'Two melodies at once: first species'),
    blurb: t('协和、不协和与平行五度', '協和・不協和・平行 5 度', 'Consonance, dissonance and parallel fifths'),
    cards: [
      { type: 'guide', ref: 'omt-intervals', demo: { play: [[48, 64], [50, 65], [52, 67], [48, 60]] },
        title: t('两条线各唱各的，又要好听', '別々に歌って、しかも美しく', 'Independent yet beautiful'),
        steps: [
          t('一类对位是"一个音对一个音"：下面一条旋律，上面再写一条。', '第 1 類は「1 音対 1 音」。下の旋律に上の旋律を書きます。', 'First species is note against note: a melody below, a new line above.'),
          t('每一对音都要好听：纯一度、纯五度、八度是"完全协和"，三度和六度是"不完全协和"。', 'それぞれの音の組を美しく：1・5・8 度は「完全協和」、3 度と 6 度は「不完全協和」。', 'Each pair must sound good: unisons, fifths and octaves are perfect consonances; thirds and sixths imperfect ones.'),
        ] },
      { type: 'match', ref: 'omt-intervals',
        prompt: t('音程 ↔ 分类', '音程 ↔ 分類', 'Interval ↔ category'),
        pairs: [[t('一度、五度、八度', '1・5・8 度', 'unison, fifth, octave'), t('完全协和', '完全協和', 'perfect consonance')], [t('三度、六度', '3・6 度', 'third, sixth'), t('不完全协和', '不完全協和', 'imperfect consonance')], [t('二度、七度', '2・7 度', 'second, seventh'), t('不协和', '不協和', 'dissonance')]],
        hint: t('最"空"的最完全，最"挤"的不协和。', 'いちばん空っぽなのが完全、ぶつかるのが不協和。', 'The emptiest are perfect; the crunchiest are dissonant.'),
        explain: t('完全协和：1、5、8 度；不完全协和：3、6 度；二度、七度是不协和。', '完全協和は 1・5・8 度、不完全協和は 3・6 度、2・7 度は不協和。', 'Perfect: 1, 5, 8; imperfect: 3, 6; seconds and sevenths are dissonant.') },
      { type: 'choice', ref: 'omt-intervals',
        prompt: t('两个声部之间的纯四度，在对位里算？', '2 声部間の完全 4 度は対位法では？', 'A perfect fourth between the two voices counts as…'),
        options: [t('不协和', '不協和', 'dissonant'), t('完全协和', '完全協和', 'perfectly consonant'), t('不完全协和', '不完全協和', 'imperfectly consonant')], answer: 0,
        hint: t('这条规矩有点出人意料。', 'ちょっと意外な決まり。', 'This rule is a little surprising.'),
        explain: t('在两声部对位中，纯四度被当作不协和音程。', '2 声の対位法では、完全 4 度は不協和として扱われます。', 'In two-voice counterpoint the perfect fourth is treated as a dissonance.') },
      { type: 'choice', ref: 'omt-species1', audio: { notes: [[48, 55], [50, 57]], mode: 'chords' },
        prompt: t('两个声部连续两个纯五度一起移动（平行五度），可以吗？', '2 声部が完全 5 度のまま続けて動く（平行 5 度）のは？', 'Two voices moving in consecutive perfect fifths (parallel fifths) — allowed?'),
        options: [t('不可以', 'だめ', 'No'), t('可以', '良い', 'Yes')], answer: 0,
        hint: t('两条线会听起来像一条——独立性没了。', '2 本が 1 本に聞こえて、独立性がなくなります。', 'The two lines start to sound like one.'),
        explain: t('平行的完全协和（五度、八度）在一类对位中是禁止的。', '平行の完全協和（5 度・8 度）は第 1 類で禁止です。', 'Parallel perfect consonances (fifths, octaves) are forbidden in first species.') },
      { type: 'choice', ref: 'omt2e-intro',
        prompt: t('结尾怎样到达最后的八度或同度？', '最後の 8 度・1 度へはどう到達する？', 'How do you arrive at the final octave or unison?'),
        options: [t('两个声部都级进到达', '両声部とも順次進行で', 'both voices by step'), t('大跳到达', '大きな跳躍で', 'by a big leap'), t('随便', '自由', 'any way')], answer: 0,
        hint: t('平稳地走回家。', '穏やかに家へ。', 'Walk home smoothly.'),
        explain: t('最后的八度或同度以级进到达，结束得最干净。', '最後の 8 度・1 度は順次進行で到達します。', 'The final octave or unison is reached by step.') },
    ],
  },
  {
    id: 'instruments', section: 'melody', feature: 'instruments', icon: 'B♭',
    title: t('写的和响的不一样：移调乐器', '書く音と鳴る音：移調楽器', 'Written vs sounding: transposing instruments'),
    blurb: t('单簧管、萨克斯、圆号', 'クラリネット・サックス・ホルン', 'Clarinet, saxophone, horn'),
    cards: [
      { type: 'guide', ref: 'ibmt-transposition',
        title: t('谱上写 C，耳朵听到 B♭？', '楽譜は C、聞こえるのは B♭？', 'Written C, sounding B♭?'),
        steps: [
          t('有些乐器的乐谱不按实际声音写。降 B 调单簧管谱上写 C，实际响的是 B♭（低一个大二度）。', '実際の音で書かない楽器があります。B♭ クラリネットは楽譜の C が実際には B♭（長 2 度下）。', 'Some instruments are not written at sounding pitch. A B♭ clarinet’s written C sounds B♭, a major second lower.'),
          t('要它响出某个音，就把谱子朝相反方向移同样的距离。', 'ある音を鳴らしたいなら、楽譜を反対方向へ同じだけ移します。', 'To get a given sound, write it the same distance in the opposite direction.'),
        ] },
      { type: 'choice', ref: 'ibmt-transposition',
        prompt: t('降 B 调单簧管谱上写 D，实际响什么？', 'B♭ クラリネットの楽譜の D、実際の音は？', 'A B♭ clarinet reads D. What sounds?'),
        options: ['C', 'E', 'D'], answer: 0,
        hint: t('实际声音比谱面低一个大二度。', '実音は楽譜より長 2 度低い。', 'It sounds a major second lower than written.'),
        explain: t('D 往下大二度是 C。', 'D から長 2 度下は C。', 'A major second below D is C.') },
      { type: 'match', ref: 'ibmt-transposition',
        prompt: t('乐器 ↔ 实际声音比谱面', '楽器 ↔ 実音は楽譜より', 'Instrument ↔ sounds compared with written'),
        pairs: [[t('降 B 调单簧管', 'B♭ クラリネット', 'B♭ clarinet'), t('低大二度', '長 2 度下', 'a major 2nd lower')], [t('中音萨克斯', 'アルト・サックス', 'alto saxophone'), t('低大六度', '長 6 度下', 'a major 6th lower')], [t('F 调圆号', 'F ホルン', 'horn in F'), t('低纯五度', '完全 5 度下', 'a perfect 5th lower')]],
        hint: t('看乐器名字里的调：B♭、E♭、F。', '楽器名の調を見て：B♭・E♭・F。', 'Use the key in the name: B♭, E♭, F.'),
        explain: t('单簧管低大二度，中音萨克斯低大六度，圆号低纯五度。', 'クラリネットは長 2 度下、アルト・サックスは長 6 度下、ホルンは完全 5 度下。', 'Clarinet a M2 lower, alto sax a M6 lower, horn a P5 lower.') },
      { type: 'choice', ref: 'ibmt-transposition',
        prompt: t('想让单簧管响出 C，谱上要写？', 'クラリネットで C を鳴らすには、楽譜に何と書く？', 'To make the clarinet sound C, write…'),
        options: ['D', 'B♭', 'C'], answer: 0,
        hint: t('反方向：往上大二度。', '反対方向：長 2 度上。', 'The opposite way: up a major second.'),
        explain: t('实际低大二度，所以谱子要写高大二度：D。', '実音が長 2 度低いので、楽譜は長 2 度高く D と書きます。', 'It sounds a M2 lower, so write a M2 higher: D.') },
      { type: 'choice', ref: 'wiki-transposing',
        prompt: t('吉他实际的音高比谱面？', 'ギターの実音は楽譜より？', 'A guitar sounds… compared with its written notes.'),
        options: [t('低一个八度', '1 オクターヴ低い', 'an octave lower'), t('一样', '同じ', 'the same'), t('高一个八度', '1 オクターヴ高い', 'an octave higher')], answer: 0,
        hint: t('它和低音提琴是一伙的。', 'コントラバスと同じ仲間。', 'It belongs with the double bass.'),
        explain: t('吉他、贝斯、低音提琴都比谱面低八度。', 'ギター・ベース・コントラバスは楽譜より 1 オクターヴ低く鳴ります。', 'Guitar, bass guitar and double bass sound an octave lower than written.') },
    ],
  },
  {
    id: 'fretboard', section: 'melody', feature: 'fretboard', icon: '#',
    title: t('吉他指板与 CAGED', 'ギター指板と CAGED', 'Guitar fretboard & CAGED'),
    blurb: t('六根弦、五个形', '6 本の弦と 5 つの形', 'Six strings, five shapes'),
    cards: [
      { type: 'guide', ref: 'wiki-standard-tuning', demo: { play: [[40], [45], [50], [55], [59], [64]] },
        title: t('六根弦怎么调？', '6 本の弦のチューニング', 'How are the six strings tuned?'),
        steps: [
          t('从最粗的弦到最细：E A D G B E。听一遍空弦。', '太い弦から：E A D G B E。開放弦を聴いてみよう。', 'From thickest to thinnest: E A D G B E. Hear the open strings.'),
          t('相邻两根弦大多差纯四度，只有 G 到 B 是大三度。', '隣り合う弦はほとんど完全 4 度、G–B だけが長 3 度。', 'Neighbouring strings are a perfect fourth apart — except G to B, a major third.'),
          t('CAGED 用五个开放和弦的形状（C、A、G、E、D）把整个指板串起来。', 'CAGED は 5 つのオープン・コードの形（C・A・G・E・D）で指板全体をつなぎます。', 'CAGED uses five open-chord shapes (C, A, G, E, D) to connect the whole neck.'),
        ] },
      { type: 'fill', ref: 'wiki-standard-tuning',
        prompt: t('标准调弦（低→高）：E A D ___ B E', '標準チューニング（低→高）：E A D ___ B E', 'Standard tuning (low → high): E A D ___ B E'),
        bank: [opt('G', 'G'), opt('C', 'C'), opt('F', 'F')], answer: ['G'],
        hint: t('D 往上纯四度。', 'D から完全 4 度上。', 'A perfect fourth above D.'),
        explain: t('E A D G B E——D 往上纯四度是 G。', 'E A D G B E。D から完全 4 度上は G。', 'E A D G B E — a fourth above D is G.') },
      { type: 'choice', ref: 'wiki-standard-tuning',
        prompt: t('哪两根相邻的弦之间不是纯四度？', '完全 4 度ではない隣り合う弦は？', 'Which neighbouring strings are NOT a perfect fourth apart?'),
        options: ['G–B', 'A–D', 'D–G'], answer: 0,
        hint: t('数半音：纯四度是 5 个。', '半音を数えて：完全 4 度は 5 つ。', 'Count half steps: a fourth is five.'),
        explain: t('G–B 只有 4 个半音，是大三度。', 'G–B は半音 4 つで長 3 度。', 'G–B spans four half steps: a major third.') },
      { type: 'fill', ref: 'agt-caged',
        prompt: t('五个形沿着指板的顺序：C → A → ___ → E → D', '指板に沿った形の順：C → A → ___ → E → D', 'Shapes along the neck: C → A → ___ → E → D'),
        bank: [opt('G', 'G'), opt('B', 'B'), opt('F', 'F')], answer: ['G'],
        hint: t('名字就是 C-A-G-E-D。', '名前そのまま C-A-G-E-D。', 'It spells C-A-G-E-D.'),
        explain: t('C 形接 A 形，A 接 G，G 接 E，E 接 D，D 又接回 C。', 'C → A → G → E → D → また C。', 'C joins A, A joins G, G joins E, E joins D, D joins C again.') },
      { type: 'choice', ref: 'agt-caged',
        prompt: t('E 形横按在第 2 品，是什么和弦？', 'E フォームを 2 フレットでセーハすると何のコード？', 'An E-shape barre at the 2nd fret makes…'),
        options: ['F♯', 'E', 'G'], answer: 0,
        hint: t('整个形往上挪两个半音。', '形全体を半音 2 つ上へ。', 'The whole shape moves up two half steps.'),
        explain: t('E 往上两个半音是 F♯，所以是 F♯ 和弦。', 'E から半音 2 つ上は F♯。', 'Two half steps above E is F♯.') },
    ],
  },
  {
    id: 'nctmore', section: 'melody', feature: 'nonchord', icon: '4-3',
    title: t('更多装饰音：倚音、逃音、延留音……', 'もっと非和声音：倚音・逸音・掛留……', 'More embellishing tones: appoggiatura, escape tone, suspension…'),
    blurb: t('看它怎么进来、怎么离开，就能叫出名字', '入り方と出方で名前がわかる', 'Name them by how they arrive and leave'),
    cards: [
      { type: 'guide', ref: ['omt2e-embellishing', 'zhwiki-nct'], demo: { play: [[48, 64, 72], [43, 62, 72], [43, 62, 71]] },
        title: t('只看两件事：怎么来，怎么走', '見るのは 2 つ：どう来て、どう去るか', 'Watch two things: how it arrives, how it leaves'),
        steps: [
          t('判断一个装饰音，只要看它前后：是级进（一步）还是跳进，方向一样还是相反，落在强拍还是弱拍。', '非和声音は前後を見ればわかります：順次進行か跳躍か、同じ方向か反対か、強拍か弱拍か。', 'To name an embellishing tone, check its neighbours: step or leap, same or opposite direction, strong or weak beat.'),
          t('倚音：跳进来，反方向一步离开，多在较强的拍子上。逃音反过来：一步进来，反方向跳走，多在较弱的拍子上。', '倚音：跳躍で入り、反対方向へ 1 歩で離れる。強い拍に多い。逸音は逆：1 歩で入り、反対方向へ跳んで離れる。弱い拍に多い。', 'Appoggiatura: leap in, step out the other way, usually on a stronger beat. Escape tone is the reverse: step in, leap out the other way, usually weaker.'),
          t('延留音：前一个和弦里的音保持不动，到了强拍变成外音，再往下一步解决。往上解决的叫上行延留音。听：C 和弦里的高音 C 留到 G 和弦上变成外音，再落到 B。', '掛留：前の和音の音をそのまま保ち、強拍で非和声音になり、1 歩下がって解決。上へ解決するものは逆掛留。聴いて：C の和音の上の C が G の和音に残って非和声音になり、B へ下がる。', 'Suspension: a note held over from the previous chord becomes dissonant on a strong beat, then resolves down by step. Resolving up is a retardation. Listen: the top C of a C chord is held into a G chord, then falls to B.'),
          t('先现音：下一个和弦的音提前出现；持续音：低音一直保持同一个音，上面的和弦在变。', '先取音：次の和音の音が早めに現れる。保続音：ベースが同じ音を保ち、上の和音が変わる。', 'Anticipation: a note of the next chord arrives early. Pedal: the bass holds one note while the chords above change.'),
        ] },
      { type: 'match', ref: 'omt2e-embellishing',
        prompt: t('装饰音 ↔ 走法', '非和声音 ↔ 動き方', 'Tone ↔ how it moves'),
        pairs: [[t('倚音', '倚音', 'appoggiatura'), t('跳进来，反方向级进离开', '跳躍で入り、反対へ順次で出る', 'leap in, step out the other way')], [t('逃音', '逸音', 'escape tone'), t('级进来，反方向跳进离开', '順次で入り、反対へ跳躍で出る', 'step in, leap out the other way')], [t('延留音', '掛留音', 'suspension'), t('保持前一个音，向下级进解决', '前の音を保ち、下へ順次で解決', 'held over, resolves down by step')], [t('先现音', '先取音', 'anticipation'), t('下一个和弦的音提前出现', '次の和音の音が先に出る', 'the next chord’s note arrives early')]],
        hint: t('倚音和逃音正好相反。', '倚音と逸音はちょうど逆。', 'Appoggiatura and escape tone are mirror images.'),
        explain: t('倚音：跳→级；逃音：级→跳；延留：保持→下行；先现：提前到。', '倚音：跳躍 → 順次、逸音：順次 → 跳躍、掛留：保持 → 下行、先取：早めに。', 'Appoggiatura: leap → step; escape: step → leap; suspension: hold → down; anticipation: early.') },
      { type: 'choice', ref: 'omt2e-embellishing',
        prompt: t('延留音往上解决，叫什么？', '掛留が上へ解決するものは？', 'A suspension that resolves upward is called…'),
        options: [t('上行延留音（retardation）', '逆掛留（リタデーション）', 'a retardation'), t('倚音', '倚音', 'an appoggiatura'), t('经过音', '経過音', 'a passing tone')], answer: 0,
        hint: t('其他都和延留音一样，只是方向反了。', 'ほかは掛留と同じで、向きだけ逆。', 'Everything matches a suspension except the direction.'),
        explain: t('保持进入、强拍上不协和，但向上一步解决：上行延留音。', '保持で入り、強拍で不協和、上へ 1 歩で解決：逆掛留。', 'Held in, dissonant on a strong beat, but resolving up by step: a retardation.') },
      { type: 'choice', ref: 'omt2e-embellishing',
        prompt: t('低音一直是 C，上面的和弦从 C 换到 F 又换到 G 再回 C。这个 C 叫？', 'ベースはずっと C、上の和音は C → F → G → C。この C は？', 'The bass stays on C while the chords above go C → F → G → C. That C is a…'),
        options: [t('持续音', '保続音', 'pedal tone'), t('先现音', '先取音', 'anticipation'), t('辅助音', '刺繍音', 'neighbour tone')], answer: 0,
        hint: t('像踩住踏板一样不放。', 'ペダルを踏み続けるように離さない。', 'Like holding a pedal down.'),
        explain: t('持续音：低音保持不变，上方和弦照常变化。', '保続音：ベースが変わらず、上の和音は変化する。', 'A pedal: the bass holds while the harmony changes above it.') },
      { type: 'choice', ref: 'omt2e-embellishing',
        prompt: t('一个外音从下面跳上来，然后往下走一步，落在强拍上。最可能是？', '下から跳んで入り、1 歩下がる。強拍にある。これは？', 'A non-chord tone is leapt to from below, then steps down; it falls on a strong beat. Most likely…'),
        options: [t('倚音', '倚音', 'an appoggiatura'), t('逃音', '逸音', 'an escape tone'), t('经过音', '経過音', 'a passing tone')], answer: 0,
        hint: t('跳进来、反方向级进走。', '跳躍で入り、反対へ順次で出る。', 'Leap in, step out in the opposite direction.'),
        explain: t('倚音：跳进、反向级进离开，多在较强拍。', '倚音：跳躍で入り反対へ順次、強い拍に多い。', 'Appoggiatura: leap in, step out the other way, usually on a stronger beat.') },
    ],
  },
  {
    id: 'species', section: 'melody', feature: 'counterpoint', icon: '2:1',
    title: t('对位进阶：四种进行与二、三、四类对位', '対位法の続き：4 つの進行と第 2・3・4 類', 'More counterpoint: four kinds of motion and species 2–4'),
    blurb: t('反向、同向、平行、斜向；2:1、4:1 与切分延留', '反行・並行・平行・斜行、2:1・4:1・シンコペーション掛留', 'Contrary, similar, parallel, oblique; 2:1, 4:1 and syncopated suspensions'),
    cards: [
      { type: 'guide', ref: ['omt2e-intro', 'omt-species2', 'omt-species3', 'omt-species4'],
        title: t('两条线怎么一起动', '2 本の線はどう一緒に動くか', 'How two lines move together'),
        steps: [
          t('两个声部之间有四种进行：反向（一上一下）、同向（都上或都下）、平行（同方向、同样的距离，前后音程一样）、斜向（一个动，另一个不动）。', '2 声部の進行は 4 種類：反行（上と下）、並行（同じ方向）、平行（同じ方向・同じ距離で音程が同じ）、斜行（一方だけ動く）。', 'Two parts can move four ways: contrary (opposite directions), similar (same direction), parallel (same direction and distance, keeping the interval), oblique (one moves, one stays).'),
          t('二类对位：对位声部用二分音符，对定旋律的全音符是 2:1。强拍必须协和；弱拍可以出现不协和，但只能是经过音。', '第 2 類：対旋律は 2 分音符、定旋律の全音符に対して 2:1。強拍は必ず協和、弱拍の不協和は経過音だけ。', 'Second species: half notes against the whole-note cantus, 2:1. Downbeats must be consonant; weak-beat dissonance must be a passing tone.'),
          t('三类对位：四分音符，4:1。加入了辅助音，还有两种允许跳进的特殊音型：双辅助音和"换音"（nota cambiata）。', '第 3 類：4 分音符で 4:1。刺繍音が加わり、跳躍を含む特別な音型（二重刺繍音とカンビアータ）も使えます。', 'Third species: quarter notes, 4:1. It adds neighbour tones and two figures that allow leaps: the double neighbour and the nota cambiata.'),
          t('四类对位：两个声部都是一小节动一次，但错开半小节——像切分。于是出现延留音：准备（协和）→ 延留（强拍上不协和）→ 解决（往下一步，协和）。', '第 4 類：どちらも 1 小節に 1 回動くが、半小節ずれる（シンコペーション）。掛留が生まれます：予備（協和）→ 掛留（強拍で不協和）→ 解決（1 歩下がって協和）。', 'Fourth species: both parts move once per bar but offset by half a bar — syncopation — creating suspensions: preparation (consonant) → suspension (dissonant on the downbeat) → resolution (a step down, consonant).'),
        ] },
      { type: 'match', ref: 'omt2e-intro',
        prompt: t('进行方式 ↔ 描述', '進行 ↔ 説明', 'Motion ↔ description'),
        pairs: [[t('反向', '反行', 'contrary'), t('一个往上，一个往下', '一方は上、一方は下', 'one up, one down')], [t('同向', '並行', 'similar'), t('同方向，距离不同', '同じ方向、距離は違う', 'same direction, different distance')], [t('平行', '平行', 'parallel'), t('同方向，前后音程一样', '同じ方向で音程が変わらない', 'same direction, same interval')], [t('斜向', '斜行', 'oblique'), t('一个动，一个不动', '一方だけ動く', 'one moves, one stays')]],
        hint: t('平行比同向更严格：连音程都不变。', '平行は並行より厳しい：音程まで同じ。', 'Parallel is stricter than similar: even the interval stays.'),
        explain: t('反向最能保持声部独立；平行五度、八度在对位里要避免。', '反行は声部の独立を保ちやすい。平行 5 度・8 度は対位法では避けます。', 'Contrary motion keeps parts most independent; parallel fifths and octaves are avoided in counterpoint.') },
      { type: 'choice', ref: 'omt-species2',
        prompt: t('二类对位里，弱拍上的不协和音必须是？', '第 2 類で、弱拍の不協和音は何でなければならない？', 'In second species, a weak-beat dissonance must be a…'),
        options: [t('经过音', '経過音', 'passing tone'), t('延留音', '掛留音', 'suspension'), t('随便什么都行', '何でもよい', 'anything at all')], answer: 0,
        hint: t('二类对位只引入了一种不协和。', '第 2 類で導入される不協和は 1 種類だけ。', 'Second species introduces just one kind of dissonance.'),
        explain: t('强拍永远协和；弱拍的不协和要像经过音那样，一步进、一步出、方向不变。', '強拍は常に協和。弱拍の不協和は経過音のように、1 歩入り 1 歩出て向きを変えない。', 'Downbeats are always consonant; a weak-beat dissonance must behave as a passing tone — step in, step out, same direction.') },
      { type: 'fill', ref: ['omt-species2', 'omt-species3'],
        prompt: t('二类对位是 ___ 比 1，三类对位是 ___ 比 1', '第 2 類は ___ 対 1、第 3 類は ___ 対 1', 'Second species is ___ to 1; third species is ___ to 1'),
        bank: [opt('2', '2'), opt('4', '4'), opt('3', '3'), opt('1', '1')], answer: ['2', '4'],
        hint: t('二分音符和四分音符各能塞进一个全音符几次？', '2 分音符と 4 分音符は全音符にいくつ入る？', 'How many halves and quarters fit in a whole note?'),
        explain: t('二分音符对全音符 2:1，四分音符对全音符 4:1。', '2 分音符で 2:1、4 分音符で 4:1。', 'Half notes give 2:1; quarter notes give 4:1.') },
      { type: 'match', ref: 'omt-species4',
        prompt: t('延留音的三个步骤', '掛留の 3 段階', 'The three parts of a suspension'),
        pairs: [[t('准备', '予備', 'preparation'), t('弱拍，协和', '弱拍、協和', 'weak beat, consonant')], [t('延留', '掛留', 'suspension'), t('强拍，同一个音，不协和', '強拍、同じ音、不協和', 'strong beat, same note, dissonant')], [t('解决', '解決', 'resolution'), t('弱拍，往下一步，协和', '弱拍、1 歩下、協和', 'weak beat, a step down, consonant')]],
        hint: t('先协和，再"卡住"，最后落下来。', 'まず協和、次に「引っかかり」、最後に下りる。', 'Consonant, then stuck, then it drops.'),
        explain: t('准备音连到强拍成为延留，然后向下级进解决。', '予備の音がタイで強拍へ続いて掛留になり、順次下行して解決。', 'The prepared note is tied into the downbeat as a suspension, then steps down to resolve.') },
      { type: 'choice', ref: 'omt-species4',
        prompt: t('对位声部在定旋律上方时，允许的不协和延留有哪些？', '定旋律の上での不協和な掛留は？', 'Which dissonant suspensions are allowed above the cantus?'),
        options: ['7–6, 4–3, 9–8', '2–3, 5–6, 4–5', '6–5, 3–2'], answer: 0,
        hint: t('从不协和开始，往下一步落到协和。', '不協和から始まり 1 歩下がって協和へ。', 'Start dissonant, step down to a consonance.'),
        explain: t('上方：7–6、4–3、9–8；下方：2–3、5–6、4–5。', '上：7–6・4–3・9–8、下：2–3・5–6・4–5。', 'Above: 7–6, 4–3, 9–8; below: 2–3, 5–6, 4–5.') },
      { type: 'choice', ref: 'omt-species3',
        prompt: t('三类对位里，C–D–B–C 这样围着一个音上下各走一步，叫？', '第 3 類で C–D–B–C のように 1 音の上下を回るのは？', 'In third species, a figure like C–D–B–C circling one note is a…'),
        options: [t('双辅助音', '二重刺繍音', 'double neighbour'), t('经过音', '経過音', 'passing tone'), t('延留音', '掛留音', 'suspension')], answer: 0,
        hint: t('第 1 和第 4 拍是同一个音。', '1 拍目と 4 拍目が同じ音。', 'Beats 1 and 4 are the same note.'),
        explain: t('双辅助音：第 2、3 拍分别是上方和下方的邻音，中间虽然跳了一下，线条仍然平滑。', '二重刺繍音：2・3 拍目が上下の隣接音。間で跳んでも線はなめらか。', 'Double neighbour: beats 2 and 3 are the upper and lower neighbours; the leap between them still sounds smooth.') },
    ],
  },
];

// 关卡顺序（从简到难）
const ORDER = ['instruments', 'fretboard', 'nonchord', 'nctmore', 'counterpoint', 'species'];
export const UNITS = ORDER.map((id) => {
  const unit = ALL.find((u) => u.id === id);
  if (!unit) throw new Error(`unknown unit ${id}`);
  return unit;
});
if (UNITS.length !== ALL.length) throw new Error('every unit must appear in ORDER');
