// 乐理闯关 · 世界音乐与律学的进阶关：每个主关后面 4 关（第 5 关"综合测验"在开局时抽题）。
// 题卡只用 references.js 中已登记、已核实的资料；{ type: 'gen' } 的题由 learn_generators.js 按同样的资料计算生成。
// 依据汇总（由 scripts/annotate-learn.mjs 生成）：
//   ref:maqamworld-jins ref:maqamworld-maqam ref:wiki-arabic-maqam ref:wiki-turkish-makam ref:wiki-thaat
//   ref:zhwiki-heptatonic ref:huain-xuangong ref:zhwiki-shierlu ref:zhwiki-pentatonic ref:wiki-pythagorean
//   ref:wiki-meantone ref:wiki-circle-of-fifths ref:wiki-werckmeister ref:wiki-vallotti ref:wiki-harmonic-series
//   ref:omt2e-collections
// @refs-end

const t = (zh, ja, en) => ({ zh, ja, en });
const opt = (id, label) => ({ id, label });
const G = (gen, count = 2, params) => ({ type: 'gen', gen, count, ...(params ? { params } : {}) });
const L = (title, cards) => ({ title, cards });

export const BRANCHES = {
  world: [
    L(t('jins：三四个音的小积木', 'ジンス：3〜4 音の小さなブロック', 'Ajnas: three- and four-note building blocks'), [
      { type: 'guide', ref: 'maqamworld-jins', tool: { feature: 'world' }, demo: { play: [[60], [62], [63.5], [65]] },
        title: t('用全音为单位量台阶', '全音を単位に段差を測る', 'Measuring steps in whole tones'),
        steps: [
          t('jins（复数 ajnas）是木卡姆的小积木，音程用全音为单位：1、¾、½、1½。', 'ジンス（複数アジュナース）はマカームの小さなブロックで、音程は全音単位：1・¾・½・1½。', 'A jins (plural ajnas) is a maqam building block, measured in whole tones: 1, ¾, ½, 1½.'),
          t('Rast：1、¾、¾、1（5 个音）；Bayati：¾、¾、1；Hijaz：½、1½、½；Nahawand：1、½、1、1；Kurd：½、1、1。听：Jins Rast（C D E½♭ F）。', 'ラスト：1・¾・¾・1（5 音）、バヤーティー：¾・¾・1、ヒジャーズ：½・1½・½、ナハワンド：1・½・1・1、クルド：½・1・1。聴いて：ジンス・ラスト（C D E½♭ F）。', 'Rast: 1, ¾, ¾, 1 (five notes); Bayati: ¾, ¾, 1; Hijaz: ½, 1½, ½; Nahawand: 1, ½, 1, 1; Kurd: ½, 1, 1. Listen: jins Rast (C D E½♭ F).'),
        ] },
      { type: 'match', ref: 'maqamworld-jins',
        prompt: t('jins ↔ 台阶（全音为 1）', 'ジンス ↔ 段差（全音 = 1）', 'Jins ↔ steps (whole tone = 1)'),
        pairs: [['Bayati', '¾ ¾ 1'], ['Hijaz', '½ 1½ ½'], ['Kurd', '½ 1 1'], ['Nahawand', '1 ½ 1 1']],
        hint: t('Hijaz 中间有一个 1½ 的大台阶。', 'ヒジャーズは真ん中に 1½ の大きな段差。', 'Hijaz has a big 1½ step in the middle.'),
        explain: t('Bayati 两个 ¾；Hijaz 中间 1½；Kurd 先 ½；Nahawand 是 1 ½ 1 1。', 'バヤーティーは ¾ が 2 つ、ヒジャーズは 1½、クルドは ½ から、ナハワンドは 1 ½ 1 1。', 'Bayati two ¾s; Hijaz the 1½; Kurd starts with ½; Nahawand 1 ½ 1 1.') },
      { type: 'choice', ref: 'maqamworld-jins',
        prompt: t('Jins Saba 有什么特别？', 'ジンス・サバの特徴は？', 'What is special about jins Saba?'),
        options: [t('大小不定，主导音可在第 3 或第 6 级', '大きさが一定せず、支配音は第 3 か第 6 音', 'its size varies; its dominant may be on degree 3 or 6'), t('它只有两个音', '2 音しかない', 'it has only two notes'), t('它就是大调', '長音階そのもの', 'it is just the major scale')], answer: 0,
        hint: t('MaqamWorld 说它的大小有歧义。', 'MaqamWorld では大きさがあいまいとされる。', 'MaqamWorld calls its size ambiguous.'),
        explain: t('Saba 的大小不固定，主导音可以在第 3 或第 6 级。', 'サバは大きさが一定せず、支配音は第 3 か第 6 音。', 'Saba’s size is ambiguous, with its dominant on degree 3 or 6.') },
      { type: 'choice', ref: 'maqamworld-jins',
        prompt: t('Jins Rast 有几个音？', 'ジンス・ラストは何音？', 'How many notes does jins Rast have?'),
        options: ['5', '3', '4'], answer: 0,
        hint: t('1 ¾ ¾ 1：四个台阶。', '1 ¾ ¾ 1：段差 4 つ。', '1 ¾ ¾ 1: four steps.'),
        explain: t('四个台阶连起五个音：C D E½♭ F G。', '段差 4 つで 5 音：C D E½♭ F G。', 'Four steps join five notes: C D E½♭ F G.') },
    ]),
    L(t('木卡姆由 jins 搭成', 'マカームはジンスでできている', 'Maqamat are built from ajnas'), [
      { type: 'guide', ref: 'maqamworld-maqam', tool: { feature: 'world' }, demo: { play: [[60], [62], [63.5], [65], [67], [69], [70.5], [72]] },
        title: t('下面一个，上面一个（或几个可换）', '下に 1 つ、上に 1 つ（替えられる）', 'One below, one (swappable) above'),
        steps: [
          t('木卡姆 Rast：第 1 级是 Jins Rast，第 5 级是 Upper Rast，也可以换成 Nahawand。听：Maqam Rast。', 'マカーム・ラスト：第 1 音にジンス・ラスト、第 5 音にアッパー・ラスト（ナハワンドにも替えられる）。聴いて：マカーム・ラスト。', 'Maqam Rast: jins Rast on degree 1, Upper Rast on degree 5 — replaceable by Nahawand. Listen: maqam Rast.'),
          t('Bayati：第 1 级 Bayati，第 4 级 Nahawand 或 Rast；Hijaz：第 1 级 Hijaz，第 4 级 Nahawand 或 Rast。', 'バヤーティー：第 1 音にバヤーティー、第 4 音にナハワンドかラスト。ヒジャーズ：第 1 音にヒジャーズ、第 4 音にナハワンドかラスト。', 'Bayati: Bayati on 1, Nahawand or Rast on 4; Hijaz: Hijaz on 1, Nahawand or Rast on 4.'),
        ] },
      { type: 'match', ref: 'maqamworld-maqam',
        prompt: t('木卡姆 ↔ 上方 jins 的起点', 'マカーム ↔ 上のジンスの位置', 'Maqam ↔ where the upper jins starts'),
        pairs: [['Rast', t('第 5 级', '第 5 音', 'degree 5')], ['Bayati', t('第 4 级', '第 4 音', 'degree 4')], ['Saba', t('第 3 级（Hijaz）', '第 3 音（ヒジャーズ）', 'degree 3 (Hijaz)')]],
        hint: t('Saba 的第二个 jins 很早就来了。', 'サバの 2 つ目のジンスは早く来る。', 'Saba’s second jins comes early.'),
        explain: t('Rast 第 5 级、Bayati 第 4 级、Saba 第 3 级接 Hijaz。', 'ラストは第 5、バヤーティーは第 4、サバは第 3 音にヒジャーズ。', 'Rast on 5, Bayati on 4, Saba has Hijaz on 3.') },
      { type: 'choice', ref: 'maqamworld-maqam',
        prompt: t('Maqam Nahawand 第 5 级可以接哪两种 jins？', 'マカーム・ナハワンドの第 5 音のジンスは？', 'Which ajnas can sit on degree 5 of maqam Nahawand?'),
        options: [t('Hijaz 或 Kurd', 'ヒジャーズかクルド', 'Hijaz or Kurd'), t('Rast 或 Sikah', 'ラストかスィーカー', 'Rast or Sikah'), t('只有 Ajam', 'アジャムだけ', 'only Ajam')], answer: 0,
        hint: t('MaqamWorld 的 Nahawand 页面。', 'MaqamWorld のナハワンドの頁。', 'MaqamWorld’s Nahawand page.'),
        explain: t('Nahawand：第 1 级 Nahawand，第 5 级 Hijaz 或 Kurd。', 'ナハワンド：第 1 音にナハワンド、第 5 音にヒジャーズかクルド。', 'Nahawand: Nahawand on 1, Hijaz or Kurd on 5.') },
      { type: 'choice', ref: 'wiki-arabic-maqam',
        prompt: t('记谱上的四分之一音（24 平均）在实际演奏中……', '記譜の四分音（24 平均）は実際の演奏で……', 'In practice, notated quarter tones (24-TET)…'),
        options: [t('只是记谱惯例，实际音高因地区、年代而异', '記譜の慣習で、実際の音高は地域・時代で違う', 'are a notational convention; real pitches vary by region and era'), t('永远精确等于 50 音分', 'いつも正確に 50 セント', 'are always exactly 50 cents')], answer: 0,
        hint: t('维基百科对 24 平均的说法。', 'ウィキペディアの 24 平均の説明。', 'Wikipedia on 24-TET.'),
        explain: t('四分之一音是方便记谱的近似，实际音高会变化。', '四分音は記譜の便宜的な近似で、実際の音高は変わる。', 'Quarter tones are a convenient approximation; actual pitches vary.') },
    ]),
    L(t('土耳其 makam', 'トルコのマカーム', 'Turkish makam'), [
      { type: 'guide', ref: 'wiki-turkish-makam', tool: { feature: 'world' },
        title: t('53 koma 与音名', '53 コマと音名', '53 commas and named tones'),
        steps: [
          t('土耳其理论把八度分成 53 个 koma（全音 = 9 koma），实际只用其中 24 个音。音程有名字：bakiye 4、küçük mücenneb 5、büyük mücenneb 8、tanîni 9。', 'トルコの理論はオクターヴを 53 コマ（全音 = 9 コマ）に分け、実際は 24 音を使う。音程には名前：bakiye 4・küçük mücenneb 5・büyük mücenneb 8・tanîni 9。', 'Turkish theory splits the octave into 53 commas (whole tone = 9) and uses 24 of the tones. Intervals have names: bakiye 4, küçük mücenneb 5, büyük mücenneb 8, tanîni 9.'),
          t('音有自己的名字：Makam Rast 从 Rast 开始，主导音是 Nevâ；Makam Bûselik 从 Dügâh 开始，主导音是 Hüseynî。', '音にも名前：マカーム・ラストは Rast から始まり支配音は Nevâ、マカーム・ブーセリクは Dügâh から始まり支配音は Hüseynî。', 'Tones have names: makam Rast starts on Rast with Nevâ as dominant; makam Bûselik starts on Dügâh with Hüseynî as dominant.'),
        ] },
      { type: 'choice', ref: 'wiki-turkish-makam',
        prompt: t('Makam Rast 的主导音（güçlü）是？', 'マカーム・ラストの支配音は？', 'What is the dominant of makam Rast?'),
        options: ['Nevâ', 'Hüseynî', 'Dügâh'], answer: 0,
        hint: t('Rast 开始，往上第五个音。', 'Rast から 5 番目の音。', 'The fifth tone up from Rast.'),
        explain: t('Rast – Dügâh – Segâh – Çârgâh – Nevâ：主导音 Nevâ。', 'Rast – Dügâh – Segâh – Çârgâh – Nevâ：支配音は Nevâ。', 'Rast – Dügâh – Segâh – Çârgâh – Nevâ: the dominant is Nevâ.') },
      { type: 'choice', ref: 'wiki-turkish-makam',
        prompt: t('53 koma 体系里一个八度实际用到多少个音？', '53 コマ体系で 1 オクターヴに実際使う音は？', 'How many tones per octave are actually used in the 53-comma system?'),
        options: ['24', '53', '12'], answer: 0,
        hint: t('53 只是分度，不是全部用上。', '53 は目盛りで、全部は使わない。', '53 is the grid; not all are used.'),
        explain: t('八度分 53 koma，但实际只用其中 24 个音。', '53 コマに分けるが、使うのは 24 音。', 'Fifty-three commas divide the octave, but only 24 tones are used.') },
      G('turkishKoma', 3),
    ]),
    L(t('世界调式综合', '世界の旋法の総合', 'World modes review'), [
      { type: 'guide', ref: ['maqamworld-jins', 'wiki-thaat', 'wiki-turkish-makam'], tool: { feature: 'world' },
        title: t('不只是"音阶"', '単なる「音階」ではない', 'More than scales'),
        steps: [
          t('木卡姆、拉格、makam 不只是一组音，还包括特征的旋律走向、装饰和用法；这里练的是它们的"骨架"。', 'マカーム・ラーガ・マカームは単なる音の集まりではなく、特有の旋律の動き・装飾・使い方を含む。ここで練習するのはその「骨組み」。', 'Maqam, raga and makam are more than pitch sets — they include characteristic gestures, ornaments and usage; here we drill their skeletons.'),
        ] },
      G('thaatNote', 2), G('turkishKoma', 2), G('edoCents', 1),
    ]),
  ],

  thaat: [
    L(t('thaat 与西方调式', 'タートと西洋の旋法', 'Thaats and Western modes'), [
      { type: 'guide', ref: 'wiki-thaat', tool: { feature: 'world' },
        title: t('六个和教会调式同音', '6 つは教会旋法と同じ', 'Six match the church modes'),
        steps: [
          t('Bilaval = Ionian、Kalyan = Lydian、Khamaj = Mixolydian、Kafi = Dorian、Asavari = Aeolian、Bhairavi = Phrygian；Bhairav 和双和声同音，Poorvi、Marva、Todi 则是别的组合。', 'ビラーワル = イオニアン、カリヤーン = リディアン、カマージ = ミクソリディアン、カーフィー = ドリアン、アーサーワリー = エオリアン、バイラヴィー = フリジアン。バイラヴはダブル・ハーモニック、プールヴィー・マールワー・トーディーは別の組み合わせ。', 'Bilaval = Ionian, Kalyan = Lydian, Khamaj = Mixolydian, Kafi = Dorian, Asavari = Aeolian, Bhairavi = Phrygian; Bhairav matches the double harmonic, and Poorvi, Marva and Todi are other combinations.'),
        ] },
      G('thaatNote', 5),
    ]),
    L(t('svara、komal 与 tivra', 'スワラ・コーマル・ティーヴラ', 'Svaras, komal and tivra'), [
      { type: 'guide', ref: 'wiki-thaat',
        title: t('32 种组合里选出 10 种', '32 通りから 10 を選ぶ', 'Ten chosen from 32'),
        steps: [
          t('七个 svara：Sa Re Ga Ma Pa Dha Ni（S R G M P D N）。Sa 和 Pa 不变；Re、Ga、Dha、Ni 可以是本位或降低（komal）；Ma 可以是本位或升高（tivra）。', '7 つのスワラ：Sa Re Ga Ma Pa Dha Ni（S R G M P D N）。Sa と Pa は不変、Re・Ga・Dha・Ni は本来か低め（コーマル）、Ma は本来か高め（ティーヴラ）。', 'Seven svaras: Sa Re Ga Ma Pa Dha Ni (S R G M P D N). Sa and Pa are fixed; Re, Ga, Dha, Ni can be natural or lowered (komal); Ma natural or raised (tivra).'),
          t('所以一共有 2⁵ = 32 种组合，Bhatkhande 只挑了 10 种当作 thaat。', 'だから 2⁵ = 32 通り。バートカンデはそのうち 10 をタートとした。', 'That gives 2⁵ = 32 combinations, of which Bhatkhande chose ten as thaats.'),
        ] },
      { type: 'choice', ref: 'wiki-thaat',
        prompt: t('哪两个 svara 永远不变？', '決して変わらないスワラは？', 'Which two svaras never change?'),
        options: ['Sa, Pa', 'Re, Ga', 'Ma, Ni'], answer: 0,
        hint: t('主音和五度。', '主音と 5 度。', 'The tonic and the fifth.'),
        explain: t('Sa（主音）和 Pa（五度）固定，其余五个可以变化。', 'Sa（主音）と Pa（5 度）は固定、残り 5 つが変わる。', 'Sa (tonic) and Pa (fifth) are fixed; the other five vary.') },
      { type: 'choice', ref: 'wiki-thaat',
        prompt: t('为什么一共有 32 种可能的组合？', 'なぜ 32 通り？', 'Why are there 32 possible combinations?'),
        options: [t('5 个音各有 2 种选择：2⁵ = 32', '5 音にそれぞれ 2 択：2⁵ = 32', 'five notes with two choices each: 2⁵ = 32'), t('因为有 32 个拉格', 'ラーガが 32 あるから', 'because there are 32 ragas'), t('因为八度分 32 份', 'オクターヴが 32 分割だから', 'because the octave has 32 parts')], answer: 0,
        hint: t('Re Ga Ma Dha Ni 各两种。', 'Re Ga Ma Dha Ni がそれぞれ 2 通り。', 'Re, Ga, Ma, Dha, Ni each have two forms.'),
        explain: t('2 × 2 × 2 × 2 × 2 = 32；Bhatkhande 只选了 10 种。', '2 × 2 × 2 × 2 × 2 = 32、バートカンデは 10 を選んだ。', '2 × 2 × 2 × 2 × 2 = 32; Bhatkhande picked ten.') },
      { type: 'choice', ref: 'wiki-thaat',
        prompt: t('Kalyan thaat 和 Bilaval 的区别是？', 'カリヤーンとビラーワルの違いは？', 'How does Kalyan differ from Bilaval?'),
        options: [t('Ma 升高（tivra Ma）', 'Ma が高い（ティーヴラ Ma）', 'a raised Ma (tivra)'), t('Ni 降低', 'Ni が低い', 'a lowered Ni'), t('Re 降低', 'Re が低い', 'a lowered Re')], answer: 0,
        hint: t('Kalyan = Lydian。', 'カリヤーン = リディアン。', 'Kalyan = Lydian.'),
        explain: t('升高的第 4 音：tivra Ma。', '上げた第 4 音：ティーヴラ Ma。', 'The raised 4th: tivra Ma.') },
    ]),
    L(t('北印度与南印度', '北インドと南インド', 'North and South India'), [
      { type: 'guide', ref: 'wiki-thaat',
        title: t('thaat 与 melakarta', 'タートとメーラカルタ', 'Thaat and melakarta'),
        steps: [
          t('thaat 是北印度（印度斯坦）的母音阶；南印度（卡纳提克）对应的叫 melakarta，由 Venkatamakhin 在约 1640 年整理。', 'タートは北インド（ヒンドゥスターニー）の親音階。南インド（カルナータカ）ではメーラカルタと呼び、1640 年ごろヴェンカタマキンが体系化。', 'Thaats are North Indian (Hindustani) parent scales; the South Indian (Carnatic) counterpart is the melakarta, systematised by Venkatamakhin around 1640.'),
          t('Bhatkhande 以 melakarta 为模型建立 thaat 体系；例如 Bilaval 对应第 29 号 melakarta Sankarabharanam。', 'バートカンデはメーラカルタを手本にタート体系を作った。例：ビラーワル = 第 29 メーラカルタ・シャンカラーバラナム。', 'Bhatkhande modelled the thaat system on the melakartas; Bilaval corresponds to the 29th, Sankarabharanam.'),
        ] },
      { type: 'choice', ref: 'wiki-thaat',
        prompt: t('南印度音乐里对应 thaat 的概念叫？', '南インドでタートに当たるのは？', 'In South Indian music, the counterpart of the thaat is the…'),
        options: ['melakarta', 'maqam', 'makam'], answer: 0,
        hint: t('Venkatamakhin 整理的。', 'ヴェンカタマキンが整理。', 'Systematised by Venkatamakhin.'),
        explain: t('卡纳提克音乐用 melakarta 给拉格分类。', 'カルナータカ音楽はメーラカルタでラーガを分類。', 'Carnatic music classifies ragas by melakarta.') },
      { type: 'match', ref: 'wiki-thaat',
        prompt: t('thaat ↔ 同名拉格', 'タート ↔ 同名のラーガ', 'Thaat ↔ eponymous raga'),
        pairs: [['Kalyan', 'Yaman'], ['Bilaval', 'Bilaval'], ['Todi', 'Miyan ki Todi']],
        hint: t('Kalyan 的拉格早先也叫 Kalyan。', 'カリヤーンのラーガは以前カリヤーンとも呼ばれた。', 'Kalyan’s raga was formerly also called Kalyan.'),
        explain: t('每个 thaat 以一个代表拉格命名：Kalyan – Yaman、Todi – Miyan ki Todi。', '各タートは代表的なラーガの名：カリヤーン – ヤマン、トーディー – ミヤーン・キ・トーディー。', 'Each thaat is named after a prominent raga: Kalyan – Yaman, Todi – Miyan ki Todi.') },
      G('thaatNote', 2),
    ]),
    L(t('thaat 综合', 'タートの総合', 'Thaat review'), [
      { type: 'guide', ref: 'wiki-thaat', tool: { feature: 'world' },
        title: t('分类工具，不是作曲规则', '分類の道具で、作曲の規則ではない', 'A classifier, not a composing rule'),
        steps: [
          t('属于某个 thaat 的拉格不一定用全它的音，也可能用别的音；thaat 主要是分类。', 'あるタートのラーガがその音をすべて使うとは限らず、ほかの音を使うこともある。タートは主に分類のため。', 'A raga in a thaat may omit notes or add others; the thaat is mainly a classification.'),
        ] },
      G('thaatNote', 5),
    ]),
  ],

  heptatonic: [
    L(t('偏音练习', '偏音の練習', 'Bian-note drill'), [
      { type: 'guide', ref: 'zhwiki-heptatonic', tool: { feature: 'chinese' },
        title: t('清高半音，变低半音', '清は半音上、変は半音下', 'Qing is a half step up, bian a half step down'),
        steps: [
          t('以宫为 do：清角 = fa、变徵 = ♯fa、闰（清羽）= ♭ti、变宫 = ti。', '宮を do とすると：清角 = fa・変徴 = ♯fa・閏（清羽）= ♭ti・変宮 = ti。', 'With gong as do: qingjue = fa, bianzhi = ♯fa, run (qingyu) = ♭ti, biangong = ti.'),
        ] },
      G('chineseNote', 5, { heptatonic: true }),
    ]),
    L(t('清乐、燕乐、雅乐', '清楽・燕楽・雅楽', 'Qingyue, Yanyue, Yayue'), [
      { type: 'guide', ref: 'zhwiki-heptatonic', tool: { feature: 'chinese' }, demo: { play: [[60], [62], [64], [65], [67], [69], [70], [72]] },
        title: t('三种七声音阶的别名', '3 つの七声音階の別名', 'Other names of the three scales'),
        steps: [
          t('清乐音阶又叫新音阶、下徵音阶；燕乐音阶又叫俗乐音阶、清商音阶；雅乐音阶又叫古音阶、正声音阶。听：燕乐音阶（C D E F G A B♭）。', '清楽音階は新音階・下徴音階、燕楽音階は俗楽音階・清商音階、雅楽音階は古音階・正声音階とも。聴いて：燕楽音階（C D E F G A B♭）。', 'Qingyue is also called the new or xiazhi scale; Yanyue the folk or qingshang scale; Yayue the ancient or zhengsheng scale. Listen: Yanyue (C D E F G A B♭).'),
        ] },
      { type: 'match', ref: 'zhwiki-heptatonic',
        prompt: t('七声音阶 ↔ 别名', '七声音階 ↔ 別名', 'Seven-tone scale ↔ other name'),
        pairs: [[t('清乐音阶', '清楽音階', 'Qingyue'), t('新音阶', '新音階', 'new scale')], [t('燕乐音阶', '燕楽音階', 'Yanyue'), t('俗乐音阶', '俗楽音階', 'folk scale')], [t('雅乐音阶', '雅楽音階', 'Yayue'), t('古音阶', '古音階', 'ancient scale')]],
        hint: t('雅乐 = 古。', '雅楽 = 古。', 'Yayue = ancient.'),
        explain: t('清乐 = 新音阶；燕乐 = 俗乐音阶；雅乐 = 古音阶。', '清楽 = 新音階、燕楽 = 俗楽音階、雅楽 = 古音階。', 'Qingyue = new; Yanyue = folk; Yayue = ancient.') },
      { type: 'choice', ref: 'zhwiki-heptatonic', audio: { notes: [60, 62, 64, 65, 67, 69, 70, 72], mode: 'melody' },
        prompt: t('听：C D E F G A B♭（C 为宫），哪种七声音阶？', '聴いて：C D E F G A B♭（C が宮）。どれ？', 'Listen: C D E F G A B♭ (C as gong). Which scale?'),
        options: [t('燕乐音阶', '燕楽音階', 'Yanyue'), t('清乐音阶', '清楽音階', 'Qingyue'), t('雅乐音阶', '雅楽音階', 'Yayue')], answer: 0,
        hint: t('有清角 F 和闰 B♭。', '清角 F と閏 B♭。', 'It has qingjue F and run B♭.'),
        explain: t('五声 + 清角 + 闰 = 燕乐音阶。', '五声 + 清角 + 閏 = 燕楽音階。', 'Pentatonic + qingjue + run = Yanyue.') },
      G('chineseNote', 2, { heptatonic: true }),
    ]),
    L(t('旋宫转调', '旋宮転調', 'Rotating the gong'), [
      { type: 'guide', ref: ['huain-xuangong', 'zhwiki-shierlu'], tool: { feature: 'chinese' },
        title: t('五声六律十二管旋相为宫', '五声六律十二管旋りて相い宮と為る', 'The five tones and twelve pipes take turns as gong'),
        steps: [
          t('"旋宫"让宫音在十二律上轮流转。同宫转调：宫不变，换调式主音（如五调朝元：宫、商、角、徵、羽五种调式依次转换，最后回到宫调式）。', '「旋宮」は宮を十二律の上で回す。同宮転調：宮はそのまま主音を変える（五調朝元：宮・商・角・徴・羽を順に巡り宮調式へ戻る）。', 'Xuangong rotates the gong through the twelve lü. Same-gong modulation keeps the gong and changes the modal tonic (as in “five modes returning to the origin”: gong, shang, jue, zhi, yu in turn, back to gong).'),
          t('异宫转调：宫音本身移到另一律上。清代王坦《琴旨》写道：角弦变成宫弦，宫就转为徵……这就是旋宫转调。', '異宮転調：宮そのものを別の律へ移す。清代の王坦『琴旨』：角弦を宮弦とすれば宮は徴に転じる……これが旋宮転調。', 'Cross-gong modulation moves the gong itself to another lü. Wang Tan’s Qin Zhi (Qing dynasty): make the jue string the gong string and gong turns into zhi… that is xuangong.'),
        ] },
      { type: 'choice', ref: 'huain-xuangong',
        prompt: t('"五调朝元"是哪一种转调？', '「五調朝元」はどの転調？', '“Five modes returning to the origin” is which kind of modulation?'),
        options: [t('同宫转调', '同宮転調', 'same-gong modulation'), t('异宫转调', '異宮転調', 'cross-gong modulation'), t('没有转调', '転調なし', 'no modulation')], answer: 0,
        hint: t('宫商角徵羽五种调式轮流，宫没变。', '宮商角徴羽を巡るが宮は同じ。', 'The five modes rotate but the gong stays.'),
        explain: t('同一个宫系统里换五种调式，最后回到宫调式。', '同じ宮の中で 5 つの旋法を巡り、宮調式に戻る。', 'Five modes within one gong system, ending back on gong.') },
      { type: 'choice', ref: 'huain-xuangong',
        prompt: t('"五声六律十二管旋相为宫"出自哪部古书？', '「五声六律十二管旋りて相い宮と為る」の出典は？', 'Which classic says “the five tones, six lü and twelve pipes take turns as gong”?'),
        options: [t('《礼记·礼运》', '『礼記・礼運』', 'the Book of Rites (Li Yun)'), t('《论语》', '『論語』', 'the Analects'), t('《道德经》', '『道徳経』', 'the Daodejing')], answer: 0,
        hint: t('先秦时期的礼书。', '先秦の礼の書。', 'A pre-Qin book of rites.'),
        explain: t('出自《礼记·礼运》。', '『礼記・礼運』。', 'From the Li Yun chapter of the Book of Rites.') },
      G('chineseNote', 2),
    ]),
    L(t('七声调式综合', '七声旋法の総合', 'Seven-tone review'), [
      { type: 'guide', ref: ['zhwiki-heptatonic', 'zhwiki-pentatonic'], tool: { feature: 'chinese' },
        title: t('五个正音当主音', '5 つの正音が主音', 'The five main tones serve as tonic'),
        steps: [
          t('七声调式仍按五声命名，主音一般是宫商角徵羽之一；偏音很不稳定，很少当主音。', '七声旋法も五声の名前で、主音はふつう宮商角徴羽のどれか。偏音は不安定で主音になることはまれ。', 'Seven-tone modes keep pentatonic names; the tonic is usually one of the five main tones, as bian notes are too unstable.'),
        ] },
      G('chineseNote', 3, { heptatonic: true }), G('chineseNote', 2),
    ]),
  ],

  temperaments: [
    L(t('毕达哥拉斯律', 'ピタゴラス音律', 'Pythagorean tuning'), [
      { type: 'guide', ref: 'wiki-pythagorean', tool: { feature: 'temperaments' },
        title: t('全用纯五度', 'すべて純正 5 度', 'All pure fifths'),
        steps: [
          t('毕达哥拉斯音阶只用纯五度（3:2）和八度（2:1）搭起来；为了只用 12 个音，它用 11 个纯五度（例如从 E♭ 到 G♯）。', 'ピタゴラス音階は純正 5 度（3:2）とオクターヴ（2:1）だけで作る。12 音に収めるため純正 5 度を 11 回使う（E♭ から G♯ など）。', 'The Pythagorean scale uses only pure fifths (3:2) and octaves (2:1); to keep 12 notes it uses 11 pure fifths (e.g. from E♭ to G♯).'),
          t('剩下的那个"五度"（G♯–E♭）特别难听，叫狼五度。在毕达哥拉斯律里，A♭ 和 G♯ 是不同的音。', '残る「5 度」（G♯–E♭）はひどく濁りウルフと呼ぶ。ピタゴラス音律では A♭ と G♯ は別の音。', 'The leftover “fifth” (G♯–E♭) is badly out of tune — the wolf. In Pythagorean tuning A♭ and G♯ are different pitches.'),
        ] },
      { type: 'choice', ref: 'wiki-pythagorean',
        prompt: t('毕达哥拉斯律里 G♯ 和 A♭ 是同一个音吗？', 'ピタゴラス音律で G♯ と A♭ は同じ音？', 'Are G♯ and A♭ the same pitch in Pythagorean tuning?'),
        options: [t('不是', 'いいえ', 'no'), t('是', 'はい', 'yes')], answer: 0,
        hint: t('只有平均律才把它们当成同一个音。', '平均律だけが同じ音として扱う。', 'Only equal temperament treats them as identical.'),
        explain: t('它们相对于 D 的频率比不同，所以频率不同。', 'D に対する比が違うので周波数も違う。', 'Their ratios to D differ, so their frequencies differ.') },
      G('ratioCents', 2), G('edoCents', 1),
    ]),
    L(t('中庸全音律', 'ミーントーン', 'Meantone temperament'), [
      { type: 'guide', ref: 'wiki-meantone', tool: { feature: 'temperaments' },
        title: t('缩窄五度，换纯三度', '5 度を狭め、純正 3 度を得る', 'Narrow the fifths, gain pure thirds'),
        steps: [
          t('中庸全音律把五度缩窄，换来纯正的大三度（5:4）。名字来自把大三度分成两个相等的全音（几何平均）。', 'ミーントーンは 5 度を狭めて純正長 3 度（5:4）を得る。名前は長 3 度を 2 つの等しい全音（幾何平均）に分けることから。', 'Meantone narrows the fifths to get pure 5:4 major thirds. The name comes from splitting the major third into two equal whole tones (a geometric mean).'),
          t('它从 15 世纪用到 19 世纪；四分之一音差中庸全音律的狼五度落在 G♯–E♭。', '15 世紀から 19 世紀まで使われた。1/4 コンマ・ミーントーンのウルフは G♯–E♭。', 'It was used from the 15th to the 19th century; quarter-comma meantone’s wolf falls at G♯–E♭.'),
        ] },
      { type: 'choice', ref: 'wiki-meantone',
        prompt: t('"中庸全音"这个名字来自？', '「ミーントーン」の名前の由来は？', 'Where does the name “meantone” come from?'),
        options: [t('把大三度分成两个相等的全音', '長 3 度を 2 つの等しい全音に分ける', 'splitting the major third into two equal whole tones'), t('一个中等大小的半音', '中くらいの半音', 'a medium-sized semitone'), t('平均分 12 份', '12 等分', 'dividing into 12 equal parts')], answer: 0,
        hint: t('几何平均。', '幾何平均。', 'A geometric mean.'),
        explain: t('全音是 5:4 的几何平均，所以叫"中庸"全音。', '全音は 5:4 の幾何平均なので「ミーン」トーン。', 'The whole tone is the geometric mean of 5:4 — the “mean” tone.') },
      { type: 'choice', ref: 'wiki-meantone',
        prompt: t('中庸全音律大约在什么时候使用？', 'ミーントーンが使われた時代は？', 'When was meantone in use?'),
        options: [t('15 世纪到 19 世纪', '15〜19 世紀', '15th to 19th century'), t('只在 20 世纪', '20 世紀だけ', 'only the 20th century'), t('古希腊', '古代ギリシャ', 'ancient Greece')], answer: 0,
        hint: t('今天仍有少量使用。', '今も少し使われる。', 'It is still used a little today.'),
        explain: t('15 世纪就有，一直常用到 19 世纪，今天仍有限使用。', '15 世紀からあり 19 世紀まで一般的、今も限定的に使われる。', 'In use by the 15th century, common into the 19th, still used a little today.') },
      G('ratioCents', 1),
    ]),
    L(t('十二平均律', '12 平均律', 'Twelve-tone equal temperament'), [
      { type: 'guide', ref: ['wiki-meantone', 'wiki-circle-of-fifths'], tool: { feature: 'temperaments' },
        title: t('把音差平均分给 12 个五度', 'コンマを 12 の 5 度に均等に', 'Spread the comma over all 12 fifths'),
        steps: [
          t('十二平均律让所有半音一样大（100 音分），每个五度正好 700 音分，比纯五度窄约 2 音分；音差被平均分摊，所以五度圈能闭合。', '12 平均律ではすべての半音が同じ（100 セント）、5 度はちょうど 700 セントで純正より約 2 セント狭い。コンマが均等に分けられ五度圏が閉じる。', 'Equal temperament makes every semitone 100 cents and every fifth exactly 700 — about 2 cents narrower than pure; the comma is shared out, so the circle closes.'),
          t('它是今天最常用的调律标准。', '今日もっとも広く使われる調律。', 'It is the most widely used tuning standard today.'),
        ] },
      { type: 'choice', ref: 'wiki-circle-of-fifths',
        prompt: t('为什么十二平均律的五度圈能刚好闭合？', 'なぜ 12 平均律の五度圏はぴったり閉じる？', 'Why does the circle of fifths close exactly in equal temperament?'),
        options: [t('每个五度都缩窄了一点（700 音分），把音差分摊掉', 'どの 5 度も少し狭め（700 セント）、コンマを分けたから', 'every fifth is slightly narrowed (700 cents), sharing out the comma'), t('五度都是纯的', '5 度はすべて純正', 'all fifths are pure'), t('它只有 7 个音', '7 音しかない', 'it has only 7 notes')], answer: 0,
        hint: t('纯五度叠 12 次会多出音差。', '純正 5 度を 12 回積むとコンマが余る。', 'Twelve pure fifths overshoot by a comma.'),
        explain: t('12 × 700 = 8400 = 7 个八度，正好回到起点。', '12 × 700 = 8400 = 7 オクターヴでぴったり。', '12 × 700 = 8400 = seven octaves exactly.') },
      G('edoCents', 2), G('ratioCents', 1),
    ]),
    L(t('律制综合', '音律の総合', 'Tuning review'), [
      { type: 'guide', ref: ['wiki-pythagorean', 'wiki-meantone'], tool: { feature: 'temperaments' },
        title: t('五度纯、三度纯、还是都差一点', '5 度を純正に、3 度を純正に、それとも全部少しずつ', 'Pure fifths, pure thirds, or everything slightly off'),
        steps: [
          t('毕达哥拉斯：五度纯，有狼五度；中庸全音：三度纯，有狼五度；平均律：全都差一点，但可以在任何调里演奏。', 'ピタゴラス：5 度は純正でウルフあり、ミーントーン：3 度が純正でウルフあり、平均律：全部少しずれるがどの調でも弾ける。', 'Pythagorean: pure fifths, with a wolf; meantone: pure thirds, with a wolf; equal: everything slightly off, but playable in every key.'),
        ] },
      G('ratioCents', 2), G('edoCents', 2),
    ]),
  ],

  welltemper: [
    L(t('计算毕达哥拉斯音差', 'ピタゴラス・コンマを計算', 'Computing the Pythagorean comma'), [
      { type: 'guide', ref: 'wiki-pythagorean',
        title: t('每个纯五度多 1.955 音分', '純正 5 度は 1.955 セント多い', 'Each pure fifth is 1.955 cents wide'),
        steps: [
          t('纯五度 ≈ 700 + 1.955 音分。叠 12 个就多出 12 × 1.955 ≈ 23.46 音分——毕达哥拉斯音差。', '純正 5 度 ≈ 700 + 1.955 セント。12 回で 12 × 1.955 ≈ 23.46 セント多い——ピタゴラス・コンマ。', 'A pure fifth ≈ 700 + 1.955 cents. Twelve of them overshoot by 12 × 1.955 ≈ 23.46 cents — the Pythagorean comma.'),
          t('所以毕达哥拉斯律的狼五度比纯五度窄了 23.46 音分；每个增、减音程也都和它的等音音程差这么多。', 'だからウルフは純正 5 度より 23.46 セント狭い。増減音程と異名同音の音程の差もこれだけ。', 'So the Pythagorean wolf is 23.46 cents narrower than a pure fifth, and each augmented or diminished interval differs from its enharmonic twin by that much.'),
        ] },
      { type: 'choice', ref: 'wiki-pythagorean',
        prompt: t('毕达哥拉斯律里的狼五度比纯五度窄多少？', 'ピタゴラス音律のウルフは純正 5 度よりどれだけ狭い？', 'How much narrower than pure is the Pythagorean wolf fifth?'),
        options: [t('约 23.46 音分', '約 23.46 セント', 'about 23.46 cents'), t('约 1.955 音分', '約 1.955 セント', 'about 1.955 cents'), t('50 音分', '50 セント', '50 cents')], answer: 0,
        hint: t('整个音差都堆在它身上。', 'コンマ全体が集まる。', 'The whole comma piles onto it.'),
        explain: t('11 个纯五度都纯，最后一个吸收了整个音差（12 × 1.955）。', '11 個の純正 5 度のあと、最後の 1 つがコンマ全体（12 × 1.955）を背負う。', 'Eleven pure fifths leave the last to absorb the whole comma (12 × 1.955).') },
      { type: 'fill', ref: 'wiki-pythagorean',
        prompt: t('纯五度约 ___ 音分；平均律五度正好 ___ 音分', '純正 5 度は約 ___ セント、平均律は ___ セント', 'A pure fifth is about ___ cents; an equal-tempered fifth exactly ___'),
        bank: [opt('702', '701.955'), opt('700', '700'), opt('696', '696.6')], answer: ['702', '700'],
        hint: t('纯五度比平均律宽一点。', '純正は平均律より少し広い。', 'Pure is slightly wider than tempered.'),
        explain: t('701.955 与 700：差约 1.955 音分。', '701.955 と 700：差は約 1.955 セント。', '701.955 versus 700: about 1.955 cents apart.') },
      G('ratioCents', 1),
    ]),
    L(t('Werckmeister III', 'ヴェルクマイスター III', 'Werckmeister III'), [
      { type: 'guide', ref: 'wiki-werckmeister', tool: { feature: 'temperaments' },
        title: t('只缩窄四个五度', '4 つの 5 度だけを狭める', 'Narrowing only four fifths'),
        steps: [
          t('Werckmeister 在 1691 年的论著里提出几种"良好律"。最有名的 Werckmeister III 大部分五度保持纯，只有 C–G、G–D、D–A、B–F♯ 四个五度各缩窄 1/4 音差。', 'ヴェルクマイスターは 1691 年の論文で「良い音律」をいくつか示した。有名な III は大半の 5 度を純正のまま、C–G・G–D・D–A・B–F♯ の 4 つだけを 1/4 コンマずつ狭める。', 'Werckmeister presented several “good temperaments” in his 1691 treatise. The famous Werckmeister III keeps most fifths pure and narrows only C–G, G–D, D–A and B–F♯ by 1/4 comma each.'),
          t('结果所有大三度都比较接近 400 音分，各个调的味道略有不同。', '結果、どの長 3 度も 400 セントに比較的近く、調ごとに少し色が違う。', 'As a result all major thirds are reasonably close to 400 cents, and each key has a slightly different colour.'),
        ] },
      { type: 'choice', ref: 'wiki-werckmeister',
        prompt: t('Werckmeister III 缩窄了哪些五度？', 'ヴェルクマイスター III で狭める 5 度は？', 'Which fifths does Werckmeister III narrow?'),
        options: ['C–G, G–D, D–A, B–F♯', t('全部 12 个', '12 すべて', 'all twelve'), 'F♯–C♯, C♯–G♯'], answer: 0,
        hint: t('四个，各缩 1/4 音差。', '4 つ、1/4 コンマずつ。', 'Four, each by 1/4 comma.'),
        explain: t('C–G、G–D、D–A、B–F♯ 各缩 1/4 音差，其余纯五度。', 'C–G・G–D・D–A・B–F♯ を 1/4 コンマずつ、残りは純正。', 'C–G, G–D, D–A and B–F♯ by 1/4 comma each; the rest pure.') },
      { type: 'choice', ref: 'wiki-werckmeister',
        prompt: t('Werckmeister 的良好律出现在哪一年的论著里？', 'ヴェルクマイスターの良い音律が出た論文の年は？', 'In which year’s treatise did Werckmeister present his good temperaments?'),
        options: ['1691', '1725', '1953'], answer: 0,
        hint: t('17 世纪末。', '17 世紀末。', 'Late 17th century.'),
        explain: t('1691 年。（1725 是 Fux 的《Gradus》，1953 是 LCC。）', '1691 年。（1725 はフックス、1953 は LCC。）', '1691. (1725 is Fux’s Gradus, 1953 LCC.)') },
      G('ratioCents', 1),
    ]),
    L(t('Vallotti', 'ヴァロッティ', 'Vallotti'), [
      { type: 'guide', ref: 'wiki-vallotti', tool: { feature: 'temperaments' },
        title: t('六个五度各缩 1/6', '6 つの 5 度を 1/6 ずつ', 'Six fifths, 1/6 each'),
        steps: [
          t('常见的现代 Vallotti 律：六个五度各缩窄 1/6 个毕达哥拉斯音差，另外六个保持纯——6 × 1/6 正好分完一个音差。', 'よく使われる現代のヴァロッティ：6 つの 5 度を 1/6 ピタゴラス・コンマずつ狭め、残り 6 つは純正。6 × 1/6 でちょうど 1 コンマ。', 'The common modern Vallotti narrows six fifths by 1/6 Pythagorean comma each and keeps six pure — 6 × 1/6 shares out exactly one comma.'),
        ] },
      { type: 'match', ref: ['wiki-vallotti', 'wiki-werckmeister', 'wiki-meantone'],
        prompt: t('律制 ↔ 怎么分音差', '音律 ↔ コンマの分け方', 'Temperament ↔ how it shares the comma'),
        pairs: [['Vallotti', t('6 个五度 × 1/6', '5 度 6 つ × 1/6', '6 fifths × 1/6')], ['Werckmeister III', t('4 个五度 × 1/4', '5 度 4 つ × 1/4', '4 fifths × 1/4')], [t('十二平均律', '12 平均律', 'equal temperament'), t('12 个五度平均分', '12 の 5 度で均等', 'all 12 fifths equally')]],
        hint: t('乘起来都等于 1 个音差。', 'どれも掛けると 1 コンマ。', 'Each multiplies to one comma.'),
        explain: t('三种都把一个音差分出去，只是分给的五度数量不同。', 'どれも 1 コンマを分けるが、分ける 5 度の数が違う。', 'All three share out one comma, over different numbers of fifths.') },
      { type: 'choice', ref: 'wiki-vallotti',
        prompt: t('Vallotti 律里有几个五度保持纯正？', 'ヴァロッティで純正のままの 5 度は？', 'How many fifths stay pure in Vallotti?'),
        options: ['6', '0', '11'], answer: 0,
        hint: t('12 − 6。', '12 − 6。', '12 − 6.'),
        explain: t('六个缩窄，六个保持纯。', '6 つ狭め、6 つ純正。', 'Six narrowed, six pure.') },
      G('edoCents', 1),
    ]),
    L(t('良好律综合', '良い音律の総合', 'Good-temperament review'), [
      { type: 'guide', ref: ['wiki-werckmeister', 'wiki-vallotti', 'wiki-pythagorean'], tool: { feature: 'temperaments' },
        title: t('一个音差，怎么分', '1 コンマをどう分けるか', 'One comma — how to share it'),
        steps: [
          t('所有"良好律"都在回答同一个问题：多出来的那个音差，分给哪几个五度？', '「良い音律」はどれも同じ問いに答えている：余ったコンマをどの 5 度に分けるか？', 'Every good temperament answers one question: which fifths get the leftover comma?'),
        ] },
      G('ratioCents', 2), G('edoCents', 2),
    ]),
  ],

  harmonics: [
    L(t('泛音之间的音程', '倍音どうしの音程', 'Intervals between harmonics'), [
      { type: 'guide', ref: 'wiki-harmonic-series', tool: { feature: 'micro' }, demo: { play: [[36], [48], [55], [60], [64], [67]] },
        title: t('n : (n−1)', 'n : (n−1)', 'n : (n−1)'),
        steps: [
          t('相邻两个泛音的比是 n:(n−1)：2:1 八度，3:2 纯五度，4:3 纯四度。频率每翻一倍，音高升一个八度。', '隣り合う倍音の比は n:(n−1)：2:1 オクターヴ、3:2 完全 5 度、4:3 完全 4 度。周波数が 2 倍になるとオクターヴ上がる。', 'Neighbouring harmonics have the ratio n:(n−1): 2:1 octave, 3:2 fifth, 4:3 fourth. Each doubling of frequency is an octave.'),
        ] },
      G('harmonicNumber', 3), G('ratioCents', 2),
    ]),
    L(t('频率比与音分', '周波数比とセント', 'Ratios and cents'), [
      { type: 'guide', ref: 'wiki-harmonic-series', tool: { feature: 'micro' },
        title: t('简单整数比与平均律', '単純な整数比と平均律', 'Simple ratios versus equal temperament'),
        steps: [
          t('泛音之间是整数比，小整数比很可能就是协和音程的基础。平均律的五度（700）很接近纯五度（约 702），所以听起来协和；平均律的小三度和纯律小三度差得多一些。', '倍音どうしは整数比で、小さな整数比が協和の基礎と考えられる。平均律の 5 度（700）は純正（約 702）にとても近いので協和的、平均律の短 3 度は純正との差が大きめ。', 'Harmonics relate by whole numbers, and small ratios likely underlie consonance. The tempered fifth (700) is very close to pure (about 702), so it sounds consonant; the tempered minor third strays further from just.'),
        ] },
      G('ratioCents', 4),
    ]),
    L(t('泛音与音色', '倍音と音色', 'Harmonics and timbre'), [
      { type: 'guide', ref: 'wiki-harmonic-series',
        title: t('同一个音，不同的配方', '同じ音、違う配合', 'Same note, different recipe'),
        steps: [
          t('"分音"是组成一个复合音的任何正弦波；"泛音"是最低分音之上的任何分音。和理想整数倍有偏差叫"非谐性"——钢琴琴弦就有一些。', '「部分音」は複合音を作る正弦波、「上音」は最低の部分音より上のもの。理想の整数倍からのずれを「非調和性」と呼び、ピアノの弦にも少しある。', 'A partial is any sine component of a complex tone; an overtone is any partial above the lowest. Deviation from ideal integer multiples is inharmonicity — piano strings have some.'),
          t('马林巴、颤音琴、定音鼓等多为非谐分音，却因为几个强分音而听得出音高；镲、锣听不出确定音高。合成器可以发出没有泛音的纯正弦波。', 'マリンバ・ヴィブラフォン・ティンパニなどは非調和な部分音が多いが、強い部分音のおかげで音高が感じられる。シンバルやタムタムには明確な音高がない。シンセは倍音のない正弦波を出せる。', 'Marimba, vibraphone and timpani have mostly inharmonic partials yet a sense of pitch from a few strong ones; cymbals and tam-tams have no definite pitch. Synthesizers can play pure sine waves with no overtones.'),
        ] },
      { type: 'choice', ref: 'wiki-harmonic-series',
        prompt: t('"非谐性"指的是？', '「非調和性」とは？', 'Inharmonicity means…'),
        options: [t('分音偏离理想的整数倍', '部分音が理想の整数倍からずれること', 'partials deviating from ideal integer multiples'), t('没有基频', '基音がないこと', 'having no fundamental'), t('音量太大', '音量が大きすぎる', 'being too loud')], answer: 0,
        hint: t('钢琴琴弦就有一点。', 'ピアノの弦に少しある。', 'Piano strings have some.'),
        explain: t('分音和理想泛音之间的偏差（以音分计）就是非谐性。', '部分音と理想の倍音のずれ（セントで測る）が非調和性。', 'The deviation of a partial from the ideal harmonic, in cents, is inharmonicity.') },
      { type: 'choice', ref: 'wiki-harmonic-series',
        prompt: t('哪种乐器几乎听不出确定的音高？', '明確な音高がほとんど感じられない楽器は？', 'Which instrument gives almost no definite pitch?'),
        options: [t('镲', 'シンバル', 'cymbals'), t('长笛', 'フルート', 'flute'), t('小提琴', 'ヴァイオリン', 'violin')], answer: 0,
        hint: t('充满非谐分音。', '非調和な部分音だらけ。', 'Full of inharmonic partials.'),
        explain: t('镲、锣的分音大多不谐和，听不出明确的音高。', 'シンバルやタムタムは部分音がほとんど非調和で、音高がはっきりしない。', 'Cymbals and tam-tams are rich in inharmonic partials, giving no clear pitch.') },
      { type: 'choice', ref: 'wiki-harmonic-series',
        prompt: t('"泛音"（overtone）包括基频吗？', '「上音」に基音は含まれる？', 'Does “overtone” include the fundamental?'),
        options: [t('不包括', '含まれない', 'no'), t('包括', '含まれる', 'yes')], answer: 0,
        hint: t('泛音是最低分音之上的。', '上音は最低の部分音より上。', 'Overtones are above the lowest partial.'),
        explain: t('所以第二泛音不一定是第三分音——数的时候要小心。', 'だから第 2 上音は第 3 部分音とは限らない。数えるとき注意。', 'So the second overtone isn’t the third partial — count carefully.') },
    ]),
    L(t('泛音列与 acoustic 音阶', '倍音列とアコースティック・スケール', 'The harmonic series and the acoustic scale'), [
      { type: 'guide', ref: ['omt2e-collections', 'wiki-harmonic-series'], demo: { play: [[60], [62], [64], [66], [67], [69], [70], [72]], chord: [48, 52, 55, 58] },
        title: t('最低几个泛音组成的音阶', '低い倍音でできた音階', 'A scale from the lowest harmonics'),
        steps: [
          t('acoustic 音集来自泛音列最低的几个音程：像大调，但第 4 音升高、第 7 音降低（C D E F♯ G A B♭）——也就是 Lydian dominant。听，最后是 C7。', 'アコースティック音集は倍音列の低い音程から：長調に似て第 4 音を上げ第 7 音を下げる（C D E F♯ G A B♭）、つまりリディアン・ドミナント。聴いて、最後は C7。', 'The acoustic collection comes from the lowest intervals of the overtone series: like major with a raised 4th and lowered 7th (C D E F♯ G A B♭) — the Lydian dominant. Listen, ending on C7.'),
        ] },
      { type: 'choice', ref: 'omt2e-collections',
        prompt: t('acoustic 音集和哪个调式一样？', 'アコースティック音集と同じ旋法は？', 'The acoustic collection is the same as which mode?'),
        options: ['Lydian dominant', 'Lydian', 'Mixolydian'], answer: 0,
        hint: t('升 4、降 7。', '♯4・♭7。', '♯4 and ♭7.'),
        explain: t('C D E F♯ G A B♭ = C Lydian dominant（旋律小调第 4 个调式）。', 'C D E F♯ G A B♭ = C リディアン・ドミナント（旋律短音階の第 4 旋法）。', 'C D E F♯ G A B♭ = C Lydian dominant (melodic minor’s mode 4).') },
      G('harmonicNumber', 2), G('ratioCents', 1),
    ]),
  ],
};
