// 乐理闯关 · 入门：每张题卡标出依据（ref），只使用 references.js 中已登记、已核实的资料；解析用尽量通俗的话转述这些资料。
// 依据汇总（由 scripts/annotate-learn.mjs 生成）：
//   ref:omt2e-half-whole ref:omt2e-notation ref:omt2e-clefs ref:omt2e-keyboard ref:omt2e-aspn ref:omt2e-rhythm
//   ref:omt2e-simple-meter ref:omt2e-compound-meter ref:omt-intervals ref:omt2e-intervals ref:omt2e-major-scales
//   ref:omt2e-minor ref:omt2e-modes ref:zhwiki-heptatonic ref:sccm-ethnic-modes ref:helvting-scales ref:omt2e-texture
// @refs-end

const t = (zh, ja, en) => ({ zh, ja, en });
const opt = (id, label) => ({ id, label });

const ALL = [
  {
    id: 'keys', section: 'basics', feature: 'chord', icon: '♪',
    title: t('键盘上的距离', '鍵盤の上の距離', 'Distances on the keyboard'),
    blurb: t('半音、全音和升降号', '半音・全音と変化記号', 'Half steps, whole steps and accidentals'),
    cards: [
      { type: 'guide', ref: 'omt2e-half-whole', demo: { keys: [60, 61], play: [[60], [61], [62]] },
        title: t('先看看钢琴', 'まずピアノを見てみよう', 'Look at a piano first'),
        steps: [
          t('白键用 C D E F G A B 这几个字母命名；黑键两个一组、三个一组地排着。', '白鍵は C D E F G A B の文字で呼びます。黒鍵は 2 つと 3 つのまとまりで並んでいます。', 'White keys are named with letters C D E F G A B; black keys sit in groups of two and three.'),
          t('紧挨着的两个键（不管黑白）就差"一个半音"——这是最小的一步。点一下亮着的两个键听听。', '隣り合う 2 つの鍵（白でも黒でも）は「半音」1 つ分。いちばん小さな一歩です。光っている 2 つを押してみよう。', 'Two keys right next to each other — black or white — are a half step apart: the smallest step. Tap the two lit keys.'),
          t('两个半音合起来，就是"一个全音"。', '半音 2 つで「全音」1 つ。', 'Two half steps make one whole step.'),
        ] },
      { type: 'choice', ref: 'omt2e-half-whole',
        prompt: t('E 和 F 中间有黑键吗？', 'E と F の間に黒鍵はある？', 'Is there a black key between E and F?'),
        options: [t('有', 'ある', 'Yes'), t('没有', 'ない', 'No')], answer: 1,
        hint: t('看看键盘上 E 的右边紧挨着谁。', '鍵盤で E のすぐ右は何かな。', 'What sits right next to E on the keyboard?'),
        explain: t('没有。E–F 和 B–C 本来就只差半音，所以中间没有黑键。', 'ない。E–F と B–C はもともと半音なので、間に黒鍵がありません。', 'No. E–F and B–C are already half steps, so there is no black key between them.') },
      { type: 'fill', ref: 'omt2e-half-whole',
        prompt: t('升号 ♯ 把音升高一个 ___，降号 ♭ 把音降低一个 ___。', 'シャープ ♯ は音を ___ 上げ、フラット ♭ は ___ 下げる。', 'A sharp ♯ raises a note by a ___, a flat ♭ lowers it by a ___.'),
        bank: [opt('half', t('半音', '半音', 'half step')), opt('whole', t('全音', '全音', 'whole step')), opt('octave', t('八度', 'オクターヴ', 'octave'))],
        answer: ['half', 'half'],
        hint: t('它们都只挪动最小的一步。', 'どちらも最小の一歩だけ動かします。', 'Both move by the smallest possible step.'),
        explain: t('♯ 升高半音，♭ 降低半音；还原号 ♮ 取消之前的升降。', '♯ は半音上げ、♭ は半音下げます。ナチュラル ♮ は変化を取り消します。', '♯ raises a half step, ♭ lowers a half step, and a natural ♮ cancels them.') },
      { type: 'choice', ref: 'omt2e-half-whole', audio: { notes: [60, 62], mode: 'melody' },
        prompt: t('C 往上走一个全音，是哪个音？', 'C から全音 1 つ上は？', 'One whole step above C is…'),
        options: ['D', 'C♯', 'E'], answer: 0,
        hint: t('全音 = 两个半音：C → C♯ → ?', '全音 = 半音 2 つ：C → C♯ → ?', 'Whole step = two half steps: C → C♯ → ?'),
        explain: t('C 和 D 之间夹着一个黑键，所以 C 到 D 是全音。', 'C と D の間には黒鍵が 1 つあるので、C–D は全音です。', 'There is a black key between C and D, so C to D is a whole step.') },
      { type: 'match', ref: 'omt2e-half-whole',
        prompt: t('写法不同、声音一样（同音异名）：连一连', '書き方は違っても同じ音（異名同音）：つなごう', 'Different names, same sound (enharmonics): match them'),
        pairs: [['C♯', 'D♭'], ['F♯', 'G♭'], ['A♯', 'B♭']],
        hint: t('C♯ 是 C 右边的黑键，它也是 D 左边的黑键。', 'C♯ は C の右の黒鍵で、D の左の黒鍵でもあります。', 'C♯ is the black key right of C — it is also left of D.'),
        explain: t('同一个黑键可以从左边的白键升上来，也可以从右边的白键降下来，所以有两个名字。', '同じ黒鍵は左の白鍵から上げても、右の白鍵から下げても作れるので、名前が 2 つあります。', 'A black key can be reached by raising the white key on its left or lowering the one on its right — hence two names.') },
      { type: 'choice', ref: 'omt2e-half-whole',
        prompt: t('B 往上一个半音是？', 'B から半音上は？', 'A half step above B is…'),
        options: ['C', 'C♯', 'A♯'], answer: 0,
        hint: t('B 和它右边的白键之间有黑键吗？', 'B と右隣の白鍵の間に黒鍵はある？', 'Is there a black key between B and the next white key?'),
        explain: t('B–C 和 E–F 一样，本身就是半音。', 'B–C も E–F と同じく、それ自体が半音です。', 'Like E–F, B–C is itself a half step.') },
    ],
  },
  {
    id: 'pentatonic', section: 'basics', feature: 'chinese', icon: '宫',
    title: t('五声音阶：宫商角徵羽', '五声音階：宮商角徴羽', 'The pentatonic: Gong Shang Jue Zhi Yu'),
    blurb: t('五个音就能写出好听的旋律', '5 つの音で美しい旋律', 'Five notes for a lovely tune'),
    cards: [
      { type: 'guide', ref: 'sccm-ethnic-modes', demo: { keys: [60, 62, 64, 67, 69], play: [[60], [62], [64], [67], [69], [72]] },
        title: t('只用五个音', '5 つの音だけ', 'Just five notes'),
        steps: [
          t('中国五声音阶的五个音叫：宫、商、角、徵、羽。', '中国の五声音階の 5 つの音は 宮・商・角・徴・羽。', 'The five notes of the Chinese pentatonic are Gong, Shang, Jue, Zhi, Yu.'),
          t('把 C 当作"宫"，它们就是 C D E G A。听听看——是不是很熟悉？', 'C を「宮」にすると C D E G A。聴いてみよう、聞き覚えがあるはず。', 'With C as Gong they are C D E G A. Listen — sound familiar?'),
          t('注意：这五个音里，任意相邻两个音之间都没有半音。', 'この 5 音では、隣り合う音の間に半音がありません。', 'Notice: no two neighbouring notes here are a half step apart.'),
        ] },
      { type: 'match', ref: 'sccm-ethnic-modes',
        prompt: t('以 C 为宫，连一连', 'C を宮として、つなごう', 'With C as Gong, match them'),
        pairs: [[t('宫', '宮', 'Gong'), 'C'], [t('商', '商', 'Shang'), 'D'], [t('角', '角', 'Jue'), 'E'], [t('徵', '徴', 'Zhi'), 'G'], [t('羽', '羽', 'Yu'), 'A']],
        hint: t('就是 C D E G A 的顺序。', 'C D E G A の順番です。', 'Follow the order C D E G A.'),
        explain: t('宫商角徵羽依次对应 C D E G A——跳过了 F 和 B。', '宮商角徴羽は順に C D E G A。F と B は飛ばします。', 'Gong to Yu are C D E G A in order — F and B are skipped.') },
      { type: 'choice', ref: 'sccm-ethnic-modes',
        prompt: t('C 宫五声音阶里没有哪个音？', 'C 宮の五声音階にない音は？', 'Which note is NOT in the C-Gong pentatonic?'),
        options: ['F', 'E', 'G'], answer: 0,
        hint: t('数一数 C D E G A。', 'C D E G A を数えてみよう。', 'Count C D E G A.'),
        explain: t('F 不在里面（B 也不在）。', 'F はありません（B もありません）。', 'F is missing (and so is B).') },
      { type: 'fill', ref: 'sccm-ethnic-modes',
        prompt: t('五声音阶里只有宫和角之间是 ___，靠它就能认出"宫"在哪儿。', '五声音階で ___ は宮と角の間だけ。これで「宮」を見つけられます。', 'Only Gong–Jue forms a ___ in the pentatonic, which is how you find Gong.'),
        bank: [opt('M3', t('大三度', '長 3 度', 'major third')), opt('m3', t('小三度', '短 3 度', 'minor third')), opt('P5', t('纯五度', '完全 5 度', 'perfect fifth'))],
        answer: ['M3'],
        hint: t('C 到 E 有几个半音？', 'C から E まで半音いくつ？', 'How many half steps from C to E?'),
        explain: t('C–E 是大三度，而且是五个音里唯一的大三度——找到它，宫就找到了。', 'C–E は長 3 度で、5 音の中で唯一の長 3 度。これが見つかれば宮もわかります。', 'C–E is a major third — the only one among the five notes. Find it and you have found Gong.') },
      { type: 'choice', ref: 'helvting-scales', audio: { notes: [60, 62, 64, 67, 69, 67, 64, 62, 69], mode: 'melody' },
        prompt: t('旋律用 C 宫的五个音，最后停在 A 上，这叫什么调式？', 'C 宮の 5 音で、最後に A で終わる旋律。何の旋法？', 'A tune uses the C-Gong notes and ends on A. Which mode is it?'),
        options: [t('A 羽调式', 'A 羽調式', 'A Yu mode'), t('C 宫调式', 'C 宮調式', 'C Gong mode'), t('A 宫调式', 'A 宮調式', 'A Gong mode')], answer: 0,
        hint: t('看结束在哪个音，它在宫商角徵羽里排第几？', '終わりの音は宮商角徴羽のどれ？', 'Which of Gong–Yu is the final note?'),
        explain: t('调式看旋律的中心和结束音。A 在 C 宫里是"羽"，所以叫 A 羽调式。', '旋法は旋律の中心と終止音で決めます。A は C 宮の「羽」なので A 羽調式。', 'The mode follows the melody’s centre and final. A is Yu in C-Gong, so it is the A Yu mode.') },
      { type: 'choice', ref: 'sccm-ethnic-modes',
        prompt: t('把 C 宫五声的 C D E G A 按高低排好，相邻两个音之间有半音吗？', 'C 宮五声の C D E G A を高さ順に並べると、隣り合う音の間に半音はある？', 'Put the C-Gong notes C D E G A in pitch order. Are any neighbouring notes a half step apart?'),
        options: [t('没有', 'ない', 'No'), t('有', 'ある', 'Yes')], answer: 0,
        hint: t('在键盘上数数每一步跨几个半音。', '鍵盤で各段差の半音を数えよう。', 'Count the half steps between neighbouring notes on the keyboard.'),
        explain: t('没有。C–D、D–E、G–A 是全音，E–G、A–C 是三个半音；相邻音没有半音。', 'ない。C–D・D–E・G–A は全音、E–G・A–C は半音 3 つで、隣り合う音に半音はありません。', 'No. C–D, D–E and G–A are whole steps; E–G and A–C span three half steps. No neighbouring pair is a half step apart.') },
    ],
  },
  {
    id: 'major', section: 'basics', feature: 'circle', icon: '♯',
    title: t('大调音阶与调号', '長音階と調号', 'Major scales & key signatures'),
    blurb: t('全全半全全全半', '全全半全全全半', 'W W H W W W H'),
    cards: [
      { type: 'guide', ref: 'omt2e-major-scales', demo: { keys: [60, 62, 64, 65, 67, 69, 71, 72], play: [[60], [62], [64], [65], [67], [69], [71], [72]] },
        title: t('大调的"台阶"', '長調の「階段」', 'The steps of a major scale'),
        steps: [
          t('大调音阶是一串固定的台阶：全、全、半、全、全、全、半（W W H W W W H）。', '長音階は決まった階段：全・全・半・全・全・全・半（W W H W W W H）。', 'A major scale is a fixed staircase: whole, whole, half, whole, whole, whole, half (W W H W W W H).'),
          t('从 C 开始刚好全是白键：C D E F G A B C。七个音须让 A–G 每个字母各出现一次，最后的 C 是高八度的重复。听一遍。', 'C から始めると全部白鍵：C D E F G A B C。7 音には A–G の各文字を 1 回ずつ使い、最後の C はオクターヴ上の繰り返し。', 'Starting on C it is all white keys: C D E F G A B C. The seven notes use each letter A–G once; the final C repeats the tonic an octave higher. Listen.'),
          t('从别的音开始，为了守住这个台阶，就要请升号或降号帮忙。升降号取决于调和音名拼写，不取决于上下行：G 大调用 F♯，F 大调用 B♭，上行、下行都一样。', '他の音から始めると階段を守るためにシャープやフラットが必要。記号は調と音名の綴りで決まり、上行・下行では変わりません。G 長調は F♯、F 長調は B♭。', 'Start anywhere else and sharps or flats preserve the pattern. They follow the key and note spelling, not the direction: G major uses F♯ and F major uses B♭, ascending or descending.'),
        ] },
      { type: 'fill', ref: 'omt2e-major-scales',
        prompt: t('大调的台阶：W W ___ W W W ___', '長音階の階段：W W ___ W W W ___', 'Major-scale steps: W W ___ W W W ___'),
        bank: [opt('H', 'H'), opt('W', 'W')], answer: ['H', 'H'],
        hint: t('C 大调里 E–F、B–C 是什么距离？', 'C 長調で E–F と B–C はどんな距離？', 'In C major, what are E–F and B–C?'),
        explain: t('第 3–4 级和第 7–8 级是半音，其余都是全音。', '第 3–4 音と第 7–8 音が半音、それ以外は全音。', 'Steps 3–4 and 7–8 are half steps; all others are whole steps.') },
      { type: 'choice', ref: 'omt2e-major-scales',
        prompt: t('补全 G 大调音阶（七个音须用不同字母）：G A B C D E ? G。? 应怎样拼写？', 'G 長音階を完成（7 音には異なる文字を使用）：G A B C D E ? G。? の正しい綴りは？', 'Complete G major using a different letter for each of its seven notes: G A B C D E ? G. How should "?" be spelled?'),
        options: ['F♯', 'F', 'G♭'], answer: 0,
        hint: t('E 后面须用字母 F，再调整升降号，让 E 到 ? 是全音、? 到 G 是半音。', 'E の次は文字 F を使い、E–? が全音、?–G が半音になるよう変化記号を付けます。', 'The letter after E must be F; adjust its accidental so E–? is a whole step and ?–G a half step.'),
        explain: t('应写 F♯：E–F♯ 是全音，F♯–G 是半音。在十二平均律中，G♭ 与 F♯ 同音，但写 G♭ 会缺少字母 F，并重复字母 G，所以它不是 G 大调第七级的正确拼写。本题考音阶拼写；G 大调上下行都用 F♯。', 'F♯ が正解。E–F♯ は全音、F♯–G は半音。12 平均律では G♭ と F♯ は同じ音高ですが、G♭ では文字 F が欠け、G が重複します。この問題は音階の綴りを問うので、G 長調の第 7 音は上行・下行とも F♯。', 'Spell it F♯: E–F♯ is a whole step and F♯–G a half step. In twelve-tone equal temperament, G♭ sounds the same, but it omits the letter F and repeats G. This question tests scale spelling: G major uses F♯ as its seventh degree both ascending and descending.') },
      { type: 'fill', ref: 'omt2e-major-scales',
        prompt: t('升号出场的顺序：F C G ___ A E B', 'シャープの順番：F C G ___ A E B', 'Order of sharps: F C G ___ A E B'),
        bank: [opt('D', 'D'), opt('B', 'B'), opt('F', 'F')], answer: ['D'],
        hint: t('降号顺序正好反过来：B E A D G C F。', 'フラットはちょうど逆：B E A D G C F。', 'Flats are the reverse: B E A D G C F.'),
        explain: t('升号依次是 F C G D A E B，降号是反过来的 B E A D G C F。', 'シャープは F C G D A E B、フラットは逆の B E A D G C F。', 'Sharps come in the order F C G D A E B; flats in the reverse, B E A D G C F.') },
      { type: 'choice', ref: 'omt2e-major-scales',
        prompt: t('小窍门：升号调里最后一个升号比主音低半音。调号是 F♯ C♯，是什么大调？', 'コツ：最後のシャープは主音の半音下。調号が F♯ C♯ なら何長調？', 'Tip: the last sharp is a half step below the tonic. Key signature F♯ C♯ is…'),
        options: [t('D 大调', 'D 長調', 'D major'), t('C♯ 大调', 'C♯ 長調', 'C♯ major'), t('A 大调', 'A 長調', 'A major')], answer: 0,
        hint: t('最后一个升号是 C♯，往上半音是？', '最後のシャープは C♯。その半音上は？', 'The last sharp is C♯ — what is a half step above it?'),
        explain: t('C♯ 往上半音是 D，所以是 D 大调。', 'C♯ の半音上は D なので D 長調。', 'A half step above C♯ is D, so it is D major.') },
      { type: 'choice', ref: 'omt2e-major-scales',
        prompt: t('降号调里倒数第二个降号就是主音。调号 B♭ E♭ A♭ 是？', 'フラット調では最後から 2 番目のフラットが主音。B♭ E♭ A♭ は？', 'In flat keys the second-to-last flat is the tonic. B♭ E♭ A♭ is…'),
        options: [t('E♭ 大调', 'E♭ 長調', 'E♭ major'), t('A♭ 大调', 'A♭ 長調', 'A♭ major'), t('B♭ 大调', 'B♭ 長調', 'B♭ major')], answer: 0,
        hint: t('倒数第二个是哪一个？', '最後から 2 番目は？', 'Which flat is second to last?'),
        explain: t('B♭ E♭ A♭ 中倒数第二个是 E♭，所以是 E♭ 大调。', 'B♭ E♭ A♭ の最後から 2 番目は E♭ なので E♭ 長調。', 'In B♭ E♭ A♭ the second-to-last is E♭, so it is E♭ major.') },
      { type: 'match', ref: 'omt2e-major-scales',
        prompt: t('大调 ↔ 升号个数', '長調 ↔ シャープの数', 'Major key ↔ number of sharps'),
        pairs: [[t('G 大调', 'G 長調', 'G major'), '1'], [t('D 大调', 'D 長調', 'D major'), '2'], [t('A 大调', 'A 長調', 'A major'), '3']],
        hint: t('按升号顺序 F C G…，最后一个升号比主音低半音。', 'F C G… の順で、最後のシャープは主音の半音下。', 'Use F C G… and "last sharp = half step below the tonic".'),
        explain: t('G：F♯；D：F♯ C♯；A：F♯ C♯ G♯。五度圈就是把这些调按升降号个数排成一圈。', 'G：F♯、D：F♯ C♯、A：F♯ C♯ G♯。五度圏はこれらを調号の数で輪に並べたもの。', 'G: F♯; D: F♯ C♯; A: F♯ C♯ G♯. The circle of fifths arranges keys by their number of sharps or flats.') },
    ],
  },
  {
    id: 'intervals', section: 'basics', feature: 'ear', icon: '↕',
    title: t('音程：两个音的距离', '音程：2 つの音の距離', 'Intervals: the distance between two notes'),
    blurb: t('数半音、听距离', '半音を数え、距離を聴く', 'Count half steps, hear the gap'),
    cards: [
      { type: 'guide', ref: 'omt-intervals', demo: { keys: [60, 64], play: [[60], [64], [60, 64]] },
        title: t('怎么量距离？', '距離はどう測る？', 'How do you measure it?'),
        steps: [
          t('最简单的办法：从下面的音往上数半音。C 到 E：C♯、D、D♯、E——4 个半音。', 'いちばん簡単なのは半音を数えること。C から E：C♯・D・D♯・E で 4 つ。', 'Easiest way: count half steps up. C to E: C♯, D, D♯, E — four half steps.'),
          t('音乐里还会说"几度"：只数字母，两头都算。C、D、E 三个字母，所以是"三度"。', '「何度」とも言います。文字だけを両端込みで数える。C・D・E で「3 度」。', 'Musicians also say "a third": count letters, including both ends — C, D, E make a third.'),
          t('把两者合起来：4 个半音的三度 = 大三度。', '合わせると：半音 4 つの 3 度 = 長 3 度。', 'Put together: a third spanning four half steps is a major third.'),
        ] },
      { type: 'choice', ref: 'omt-intervals', audio: { notes: [60, 67], mode: 'melody' },
        prompt: t('听：这两个音是什么音程？', '聴いて：この 2 音の音程は？', 'Listen: what interval is this?'),
        options: [t('纯五度', '完全 5 度', 'perfect fifth'), t('大三度', '長 3 度', 'major third'), t('八度', 'オクターヴ', 'octave')], answer: 0,
        hint: t('C 到 G，数数字母：C D E F G。', 'C から G。文字を数えると C D E F G。', 'C to G — count the letters C D E F G.'),
        explain: t('C 到 G 是五度，跨 7 个半音，叫纯五度——空旷、稳定。', 'C–G は 5 度で半音 7 つ、完全 5 度。広々と安定した響き。', 'C to G is a fifth spanning seven half steps: a perfect fifth, open and stable.') },
      { type: 'match', ref: 'omt-intervals',
        prompt: t('音程 ↔ 半音数', '音程 ↔ 半音の数', 'Interval ↔ number of half steps'),
        pairs: [[t('小三度', '短 3 度', 'minor third'), '3'], [t('大三度', '長 3 度', 'major third'), '4'], [t('纯五度', '完全 5 度', 'perfect fifth'), '7'], [t('八度', 'オクターヴ', 'octave'), '12']],
        hint: t('大三度比小三度多一个半音。', '長 3 度は短 3 度より半音 1 つ多い。', 'A major third is one half step bigger than a minor third.'),
        explain: t('小三度 3、大三度 4、纯五度 7、八度 12 个半音。', '短 3 度 3、長 3 度 4、完全 5 度 7、オクターヴ 12。', 'Minor third 3, major third 4, perfect fifth 7, octave 12 half steps.') },
      { type: 'fill', ref: 'omt-intervals',
        prompt: t('C 到 E♭ 是 ___ 个半音，叫 ___。', 'C から E♭ は半音 ___ つ、名前は ___。', 'C to E♭ is ___ half steps, called a ___.'),
        bank: [opt('3', '3'), opt('4', '4'), opt('m3', t('小三度', '短 3 度', 'minor third')), opt('M3', t('大三度', '長 3 度', 'major third'))],
        answer: ['3', 'm3'],
        hint: t('C 到 E 是 4 个半音，E♭ 低半音。', 'C–E は半音 4 つ、E♭ は半音低い。', 'C–E is four half steps; E♭ is one lower.'),
        explain: t('3 个半音的三度是小三度——听起来比大三度暗一点。', '半音 3 つの 3 度は短 3 度。長 3 度より少し暗い響き。', 'A third of three half steps is a minor third — a little darker than a major third.') },
      { type: 'choice', ref: 'omt-intervals', audio: { notes: [60, 64], mode: 'harmonic' },
        prompt: t('再听一次：这是大三度还是小三度？', 'もう一度：長 3 度？短 3 度？', 'Once more: major third or minor third?'),
        options: [t('大三度', '長 3 度', 'major third'), t('小三度', '短 3 度', 'minor third')], answer: 0,
        hint: t('明亮的那一种是大三度。', '明るい方が長 3 度。', 'The brighter one is the major third.'),
        explain: t('C 和 E 同时响：大三度，明亮。', 'C と E を同時に：長 3 度、明るい。', 'C and E together: a bright major third.') },
      { type: 'choice', ref: 'omt-intervals',
        prompt: t('C 到 A 是几度？', 'C から A は何度？', 'C up to A is a…'),
        options: [t('六度', '6 度', 'sixth'), t('五度', '5 度', 'fifth'), t('七度', '7 度', 'seventh')], answer: 0,
        hint: t('数字母，两头都算：C D E F G A。', '両端込みで文字を数える：C D E F G A。', 'Count letters including both ends: C D E F G A.'),
        explain: t('C D E F G A 一共 6 个字母，所以是六度。', 'C D E F G A で 6 文字、6 度です。', 'C D E F G A is six letters, so it is a sixth.') },
    ],
  },
  {
    id: 'staff', section: 'basics', feature: 'staff', icon: 'C4',
    title: t('五线谱、谱号与中央 C', '五線譜・音部記号・中央の C', 'Staff, clefs and middle C'),
    blurb: t('音写在哪条线上？C4 是什么意思？', '音はどの線に書く？C4 って何？', 'Which line is which note? What does C4 mean?'),
    cards: [
      { type: 'guide', ref: ['omt2e-notation', 'omt2e-clefs', 'omt2e-keyboard'], demo: { keys: [60], play: [[60]] },
        title: t('五条线就是一张"高度表"', '5 本の線は「高さの表」', 'Five lines make a height chart'),
        steps: [
          t('五线谱有五条线。音越高写得越高，从左往右读，就像读一行字。', '五線譜は 5 本の線。高い音ほど上に書き、文章のように左から右へ読みます。', 'A staff has five lines. Higher notes sit higher, and you read left to right like a line of text.'),
          t('谱号告诉你每条线是哪个音。高音谱号绕着第二线的 G，所以也叫 G 谱号；低音谱号的点从上数第二线 F 开始，也叫 F 谱号。', '音部記号が各線の音を決めます。ト音記号は第 2 線の G に巻きつくので G 記号、ヘ音記号は上から 2 本目の F 線から始まるので F 記号とも呼ばれます。', 'A clef tells you which note each line is. The treble clef curls around the G line (second from the bottom), so it is the G clef; the bass clef’s dot starts on the F line (second from the top), so it is the F clef.'),
          t('写不下的音，用短短的"加线"往上或往下接。', '収まらない音は、短い「加線」で上下に延ばします。', 'Notes that don’t fit get short ledger lines above or below.'),
          t('钢琴用大谱表（上高音、下低音）。夹在两行中间那条线上的音就是中央 C，记作 C4——键盘上点亮的那个键。', 'ピアノは大譜表（上がト音、下がヘ音）。2 段の間の線の音が中央の C で、C4 と書きます。光っている鍵です。', 'Pianists read the grand staff (treble above, bass below). The note on the line between the two staves is middle C, written C4 — the lit key.'),
        ] },
      { type: 'choice', ref: 'omt2e-clefs',
        prompt: t('高音谱号又叫什么谱号？', 'ト音記号の別名は？', 'The treble clef is also called the…'),
        options: [t('G 谱号', 'G 記号', 'G clef'), t('F 谱号', 'F 記号', 'F clef'), t('C 谱号', 'C 記号', 'C clef')], answer: 0,
        hint: t('它绕着哪条线打圈？', 'どの線に巻きついている？', 'Which line does it curl around?'),
        explain: t('高音谱号绕着从下数第二线，那条线就是 G。', 'ト音記号は下から 2 本目の線に巻きつき、その線が G です。', 'It curls around the second line from the bottom, which is G.') },
      { type: 'match', ref: 'omt2e-clefs',
        prompt: t('谱号 ↔ 它标出的那条线', '音部記号 ↔ 示している線', 'Clef ↔ the line it marks'),
        pairs: [[t('高音谱号（G 谱号）', 'ト音記号（G 記号）', 'treble clef (G clef)'), t('从下数第二线', '下から 2 本目', 'second line from the bottom')], [t('低音谱号（F 谱号）', 'ヘ音記号（F 記号）', 'bass clef (F clef)'), t('从上数第二线', '上から 2 本目', 'second line from the top')], [t('中音谱号（C 谱号）', 'アルト記号（C 記号）', 'alto clef (C clef)'), t('正中间那条线', '真ん中の線', 'the middle line')], [t('次中音谱号（C 谱号）', 'テノール記号（C 記号）', 'tenor clef (C clef)'), t('从上数第二线', '上から 2 本目', 'second line from the top')]],
        hint: t('括号里的字母就是那条线的音。', '括弧の中の文字がその線の音です。', 'The letter in brackets is the note of that line.'),
        explain: t('G 谱号绕着从下数第二线（G），F 谱号的点夹住从上数第二线（F），中音谱号的中心对准中线（C），次中音谱号对准从上数第二线（C）。低音谱号和次中音谱号都标在从上数第二线，所以这两条连线可以互换。', 'G 記号は下から 2 本目（G）を巻き、F 記号の点は上から 2 本目（F）をはさみ、アルト記号は真ん中の線（C）、テノール記号は上から 2 本目（C）を指します。ヘ音記号とテノール記号はどちらも上から 2 本目なので、この 2 本は入れ替えても正解です。', 'The G clef curls round the second line from the bottom (G), the F clef’s dots straddle the second line from the top (F), the alto clef centres on the middle line (C), and the tenor clef on the second line from the top (C). Bass and tenor clefs both mark the second line from the top, so those two connections are interchangeable.') },
      { type: 'fill', ref: 'omt2e-clefs',
        prompt: t('高音谱号的五条线从下往上：E G ___ D F', 'ト音記号の 5 本の線（下から）：E G ___ D F', 'Treble-clef lines, bottom to top: E G ___ D F'),
        bank: [opt('B', 'B'), opt('A', 'A'), opt('C', 'C')], answer: ['B'],
        hint: t('英语口诀 Every Good Bird Does Fly。', '英語の覚え方 Every Good Bird Does Fly。', 'Every Good Bird Does Fly.'),
        explain: t('线上的音每次跳过一个字母：E G B D F。', '線の音は 1 文字ずつ飛ばします：E G B D F。', 'Line notes skip a letter each time: E G B D F.') },
      { type: 'choice', ref: 'omt2e-aspn', audio: { notes: [60], mode: 'melody' },
        prompt: t('中央 C 用音高记号写作？', '中央の C の音高表記は？', 'Middle C is written as…'),
        options: ['C4', 'C3', 'C5'], answer: 0,
        hint: t('钢琴中间那个 C，数字是 4。', 'ピアノの真ん中の C は 4。', 'The C in the middle of the piano gets a 4.'),
        explain: t('字母说是哪个音，数字说在第几个八度。中央 C = C4，值得记住当作起点。', '文字が音名、数字がオクターヴ。中央の C = C4 を基準として覚えよう。', 'The letter names the note, the number names the octave. Middle C = C4 — a handy starting point.') },
      { type: 'choice', ref: 'omt2e-aspn',
        prompt: t('B3 往上一个白键是？', 'B3 のすぐ上の白鍵は？', 'The white key right above B3 is…'),
        options: ['C4', 'C3', 'B4'], answer: 0,
        hint: t('八度的编号从 C 开始换。', 'オクターヴの番号は C で切り替わる。', 'Octave numbers change at C.'),
        explain: t('每个八度从 C 数到 B，所以 B3 的下一个音进入第 4 个八度：C4。', '各オクターヴは C から B まで。B3 の次は第 4 オクターヴの C4。', 'Each octave runs C to B, so the note after B3 starts octave 4: C4.') },
      { type: 'choice', ref: 'omt2e-keyboard',
        prompt: t('在键盘上找 C：它紧挨在哪组黑键的左边？', '鍵盤で C を探す：どの黒鍵のまとまりのすぐ左？', 'Finding C: it sits just left of which black-key group?'),
        options: [t('两个一组的黑键', '2 つの黒鍵', 'the group of two'), t('三个一组的黑键', '3 つの黒鍵', 'the group of three')], answer: 0,
        hint: t('三个一组左边的是 F。', '3 つのまとまりの左は F。', 'Left of the group of three is F.'),
        explain: t('C 在两个黑键左边，F 在三个黑键左边。', 'C は 2 つの黒鍵の左、F は 3 つの黒鍵の左。', 'C is left of the two black keys; F is left of the three.') },
    ],
  },
  {
    id: 'rhythm', section: 'basics', feature: 'rhythm', icon: '♩',
    title: t('音符的长短', '音符の長さ', 'How long is a note?'),
    blurb: t('全音符、四分音符、附点和连音线', '全音符・4 分音符・付点・タイ', 'Whole notes, quarter notes, dots and ties'),
    cards: [
      { type: 'guide', ref: 'omt2e-rhythm', demo: { play: [[60], [60], [64], [67]] },
        title: t('像切披萨一样切时间', 'ピザを切るように時間を切る', 'Slice time like a pizza'),
        steps: [
          t('一个音符同时说两件事：多高、多长。', '音符は「高さ」と「長さ」の両方を表します。', 'A note says two things: how high and how long.'),
          t('常见的时值：全音符、二分音符、四分音符、八分音符、十六分音符。', 'よく使う音価：全音符・2 分音符・4 分音符・8 分音符・16 分音符。', 'Common values: whole, half, quarter, eighth and sixteenth notes.'),
          t('它们是一半一半切的：1 个全音符 = 2 个二分 = 4 个四分 = 8 个八分，就像一整张披萨切成两半、四块、八块。', '半分ずつ分かれます：全音符 1 = 2 分 2 = 4 分 4 = 8 分 8。ピザを 2 つ、4 つ、8 つに切るのと同じ。', 'Each splits in half: 1 whole = 2 halves = 4 quarters = 8 eighths — like cutting a pizza into halves, quarters, eighths.'),
          t('音符后面的小点（附点）让它变长一半；连音线把两个同样高的音连成一个长音，后面那个不再重新弹。', '付点は長さを半分だけ足し、タイは同じ高さの 2 音をつないで 1 つの長い音にします（後ろの音は弾き直さない）。', 'A dot adds half the note’s length; a tie joins two notes of the same pitch into one long note — the second is not played again.'),
        ] },
      { type: 'fill', ref: 'omt2e-rhythm',
        prompt: t('1 个全音符 = ___ 个四分音符 = ___ 个八分音符', '全音符 1 つ = 4 分音符 ___ つ = 8 分音符 ___ つ', '1 whole note = ___ quarter notes = ___ eighth notes'),
        bank: [opt('2', '2'), opt('4', '4'), opt('8', '8'), opt('16', '16')], answer: ['4', '8'],
        hint: t('每次对半切：1 → 2 → 4 → 8。', '半分ずつ：1 → 2 → 4 → 8。', 'Halve each time: 1 → 2 → 4 → 8.'),
        explain: t('全音符切两次得 4 个四分，切三次得 8 个八分。', '2 回切ると 4 分音符 4 つ、3 回で 8 分音符 8 つ。', 'Halving twice gives 4 quarters; three times gives 8 eighths.') },
      { type: 'choice', ref: 'omt2e-rhythm',
        prompt: t('附点二分音符一共多长？', '付点 2 分音符の長さは？', 'How long is a dotted half note?'),
        options: [t('3 个四分音符', '4 分音符 3 つ', '3 quarter notes'), t('2 个四分音符', '4 分音符 2 つ', '2 quarter notes'), t('4 个四分音符', '4 分音符 4 つ', '4 quarter notes')], answer: 0,
        hint: t('二分 = 2 个四分，再加它的一半。', '2 分 = 4 分 2 つ、そこに半分を足す。', 'A half = 2 quarters; add half of that.'),
        explain: t('2 + 1 = 3 个四分音符。附点永远是"加上自己的一半"。', '2 + 1 = 4 分音符 3 つ。付点はいつも「自分の半分を足す」。', '2 + 1 = 3 quarters. A dot always adds half of the note itself.') },
      { type: 'match', ref: 'omt2e-rhythm',
        prompt: t('音符 ↔ 等于几个八分音符', '音符 ↔ 8 分音符いくつ分', 'Note ↔ how many eighth notes'),
        pairs: [[t('全音符', '全音符', 'whole note'), '8'], [t('二分音符', '2 分音符', 'half note'), '4'], [t('四分音符', '4 分音符', 'quarter note'), '2'], [t('附点四分音符', '付点 4 分音符', 'dotted quarter'), '3']],
        hint: t('附点四分 = 四分（2 个八分）+ 一半（1 个八分）。', '付点 4 分 = 4 分（8 分 2 つ）+ その半分（1 つ）。', 'Dotted quarter = quarter (2 eighths) + half of it (1 eighth).'),
        explain: t('8、4、2，附点四分是 2 + 1 = 3。', '8・4・2、付点 4 分は 2 + 1 = 3。', '8, 4, 2 — and the dotted quarter is 2 + 1 = 3.') },
      { type: 'choice', ref: 'omt2e-rhythm',
        prompt: t('连音线连起来的第二个音，要再弹一次吗？', 'タイでつながれた 2 つ目の音は弾き直す？', 'Do you replay the second note of a tie?'),
        options: [t('不弹，只是把声音延长', '弾かない。音を延ばすだけ', 'No — it just extends the sound'), t('要再弹一次', 'もう一度弾く', 'Yes, play it again')], answer: 0,
        hint: t('连音线只连接同样高的音。', 'タイは同じ高さの音だけをつなぐ。', 'A tie only connects notes of the same pitch.'),
        explain: t('连音线把两个时值加在一起，被连过去的音不重新奏出。', 'タイは 2 つの音価を足し合わせ、つながれた音は弾き直しません。', 'A tie adds the two durations together; the tied-to note is not re-struck.') },
    ],
  },
  {
    id: 'minor', section: 'basics', feature: 'classical', icon: 'm',
    title: t('小调：三种小调与关系调', '短調：3 つの短音階と平行調', 'Minor keys: three minors and their relatives'),
    blurb: t('自然、和声、旋律小调；关系调和同主音调', '自然・和声・旋律短音階、平行調と同主調', 'Natural, harmonic and melodic minor; relative and parallel keys'),
    cards: [
      { type: 'guide', ref: 'omt2e-minor', demo: { keys: [57, 59, 60, 62, 64, 65, 67, 69], play: [[57], [59], [60], [62], [64], [65], [67], [69]], chord: [45, 48, 52, 55] },
        title: t('同一个主音，换一种"颜色"', '同じ主音で色を変える', 'Same home note, different colour'),
        steps: [
          t('小调和同名的大调相比，第三个音低了半音——一下子就变得暗一些。', '短調は同じ名前の長調より第 3 音が半音低く、少し暗く聞こえます。', 'A minor scale’s third note is a half step lower than in the major scale with the same name — it instantly sounds darker.'),
          t('自然小调的台阶：W H W W H W W（W 全音，H 半音）。点亮的是 A 自然小调——全是白键。', '自然短音階の段差：W H W W H W W（W 全音、H 半音）。光っているのは A 自然短音階で、白鍵だけ。', 'Natural minor steps: W H W W H W W (W = whole, H = half). The lit keys are A natural minor — all white keys.'),
          t('和声小调把第 7 个音升高半音；旋律小调上行时升高第 6、7 个音，下行时按自然小调走。', '和声短音階は第 7 音を半音上げ、旋律短音階は上行で第 6・7 音を上げ、下行は自然短音階どおり。', 'Harmonic minor raises the 7th note a half step; melodic minor raises the 6th and 7th going up and uses natural minor coming down.'),
          t('调号只按自然小调写。调号相同的一对大小调叫"关系调"（C 大调 ↔ A 小调）；主音相同的一对叫"同主音调"（C 大调 ↔ C 小调）。', '調号は自然短音階で書きます。調号が同じ長短調は「平行調」（C 長調 ↔ A 短調）、主音が同じなら「同主調」（C 長調 ↔ C 短調）。', 'Key signatures follow natural minor. A major and minor key sharing a signature are relative (C major ↔ A minor); sharing a tonic, parallel (C major ↔ C minor).'),
        ] },
      { type: 'fill', ref: 'omt2e-minor',
        prompt: t('自然小调：W H W W ___ W W', '自然短音階：W H W W ___ W W', 'Natural minor: W H W W ___ W W'),
        bank: [opt('H', 'H'), opt('W', 'W'), opt('3H', '3H')], answer: ['H'],
        hint: t('A 小调第 5 到第 6 个音是 E 到 F。', 'A 短調の第 5 → 第 6 音は E → F。', 'In A minor the 5th to 6th notes are E to F.'),
        explain: t('E–F 之间没有黑键，是半音，所以是 W H W W H W W。', 'E–F の間に黒鍵はなく半音。だから W H W W H W W。', 'E–F has no black key between — a half step — so W H W W H W W.') },
      { type: 'choice', ref: 'omt2e-minor', audio: { notes: [57, 59, 60, 62, 64, 65, 68, 69], mode: 'melody' },
        prompt: t('听：这是 A 和声小调。它和自然小调哪里不一样？', '聴いて：A 和声短音階。自然短音階とどこが違う？', 'Listen: A harmonic minor. How does it differ from natural minor?'),
        options: [t('第 7 个音升高了半音（G♯）', '第 7 音が半音上がる（G♯）', 'The 7th note is raised (G♯)'), t('第 3 个音升高了半音', '第 3 音が半音上がる', 'The 3rd note is raised'), t('第 6 个音降低了半音', '第 6 音が半音下がる', 'The 6th note is lowered')], answer: 0,
        hint: t('注意最后两步：F → G♯ 跨得特别大。', '最後の 2 歩に注目：F → G♯ が大きく開く。', 'Listen to the last steps: F → G♯ is a wide gap.'),
        explain: t('升高第 7 音后，第 6、7 音之间变成 3 个半音：W H W W H 3H H。', '第 7 音を上げると第 6・7 音の間が半音 3 つ：W H W W H 3H H。', 'Raising the 7th leaves three half steps between the 6th and 7th: W H W W H 3H H.') },
      { type: 'match', ref: 'omt2e-minor',
        prompt: t('三种小调 ↔ 特点', '3 つの短音階 ↔ 特徴', 'Three minors ↔ what makes them'),
        pairs: [[t('自然小调', '自然短音階', 'natural minor'), t('调号就是按它写的', '調号はこれで書く', 'the key signature follows it')], [t('和声小调', '和声短音階', 'harmonic minor'), t('只升高第 7 音', '第 7 音だけを上げる', 'raises only the 7th')], [t('旋律小调', '旋律短音階', 'melodic minor'), t('上行升 6、7 音，下行还原', '上行で 6・7 を上げ、下行は戻す', 'raises 6 and 7 going up, not coming down')]],
        hint: t('名字里有"旋律"的那个，上下行不一样。', '「旋律」の名がつくものは上行と下行が違う。', 'The “melodic” one differs going up and down.'),
        explain: t('三种小调都叫"某小调"，调号统一按自然小调写。', 'どれも「〇短調」と呼び、調号は自然短音階で書きます。', 'All three are just called “… minor”, and the key signature always follows natural minor.') },
      { type: 'choice', ref: 'omt2e-minor',
        prompt: t('G 大调（一个升号）的关系小调是？', 'G 長調（シャープ 1 つ）の平行調は？', 'The relative minor of G major (one sharp) is…'),
        options: [t('E 小调', 'E 短調', 'E minor'), t('G 小调', 'G 短調', 'G minor'), t('B 小调', 'B 短調', 'B minor')], answer: 0,
        hint: t('关系小调的主音比大调主音低三个半音。', '平行調の主音は長調の主音より半音 3 つ低い。', 'The relative minor’s tonic is three half steps below the major tonic.'),
        explain: t('G → F♯ → F → E，低三个半音是 E。E 小调也是一个升号。', 'G → F♯ → F → E。半音 3 つ下は E で、E 短調もシャープ 1 つ。', 'G → F♯ → F → E: three half steps down is E. E minor also has one sharp.') },
      { type: 'choice', ref: 'omt2e-minor',
        prompt: t('D 大调的同主音小调是？', 'D 長調の同主調は？', 'The parallel minor of D major is…'),
        options: [t('D 小调', 'D 短調', 'D minor'), t('B 小调', 'B 短調', 'B minor'), t('A 小调', 'A 短調', 'A minor')], answer: 0,
        hint: t('"同主音"= 主音一样。', '「同主」= 主音が同じ。', '“Parallel” means the same tonic.'),
        explain: t('D 大调和 D 小调主音都是 D；B 小调才是 D 大调的关系小调。', 'D 長調と D 短調はどちらも主音 D。B 短調は D 長調の平行調です。', 'D major and D minor share the tonic D; B minor is D major’s relative minor.') },
    ],
  },
  {
    id: 'modes', section: 'basics', feature: 'ref', icon: 'Dor',
    title: t('七种调式：从最亮到最暗', '7 つの旋法：いちばん明るいものから暗いものまで', 'The seven modes, bright to dark'),
    blurb: t('Ionian、Dorian、Phrygian、Lydian、Mixolydian、Aeolian、Locrian', 'イオニアン・ドリアン・フリジアン・リディアン・ミクソリディアン・エオリアン・ロクリアン', 'Ionian, Dorian, Phrygian, Lydian, Mixolydian, Aeolian, Locrian'),
    cards: [
      { type: 'guide', ref: ['omt2e-modes', 'zhwiki-heptatonic'], demo: { keys: [62, 64, 65, 67, 69, 71, 72, 74], play: [[62], [64], [65], [67], [69], [71], [72], [74]], chord: [50, 53, 57, 60] },
        title: t('同样七个白键，换个起点就换了味道', '同じ 7 つの白鍵でも、始まりを変えると味が変わる', 'Same seven white keys, a new starting point, a new flavour'),
        steps: [
          t('只弹白键：从 C 开始是 Ionian（就是大调），D 开始是 Dorian，E 是 Phrygian，F 是 Lydian，G 是 Mixolydian，A 是 Aeolian（就是自然小调），B 是 Locrian。点亮的是 D Dorian，播放到最后会补上它的主七和弦 Dm7（D F A C）。', '白鍵だけで：C から始めるとイオニアン（長音階）、D はドリアン、E はフリジアン、F はリディアン、G はミクソリディアン、A はエオリアン（自然短音階）、B はロクリアン。光っているのは D ドリアン。再生の最後に主和音の Dm7（D F A C）が鳴る。', 'White keys only: from C it is Ionian (major), D Dorian, E Phrygian, F Lydian, G Mixolydian, A Aeolian (natural minor), B Locrian. The lit keys are D Dorian; playback ends on its tonic seventh, Dm7 (D F A C).'),
          t('含大三度的比较"亮"：Lydian 最亮，然后 Ionian、Mixolydian。', '長 3 度を含むものは「明るい」：リディアンが最も明るく、次にイオニアン、ミクソリディアン。', 'Modes with a major third sound bright: Lydian is brightest, then Ionian, then Mixolydian.'),
          t('含小三度的比较"暗"：Dorian、Aeolian、Phrygian，最暗的是 Locrian。', '短 3 度を含むものは「暗い」：ドリアン、エオリアン、フリジアン、最も暗いのがロクリアン。', 'Modes with a minor third sound dark: Dorian, Aeolian, Phrygian, and darkest of all, Locrian.'),
          t('每个调式都有一个"特征音"：Lydian = 大调把第 4 音升高；Mixolydian = 大调把第 7 音降低；Dorian = 自然小调把第 6 音升高；Phrygian = 自然小调把第 2 音降低；Locrian = 再把第 5 音也降低。任何音都可以当起点。', '各旋法には「特徴音」があります：リディアン = 長音階の第 4 音を上げる、ミクソリディアン = 第 7 音を下げる、ドリアン = 自然短音階の第 6 音を上げる、フリジアン = 第 2 音を下げる、ロクリアン = さらに第 5 音も下げる。どの音からでも作れます。', 'Each mode has a colour note: Lydian = major with a raised 4th; Mixolydian = major with a lowered 7th; Dorian = natural minor with a raised 6th; Phrygian = natural minor with a lowered 2nd; Locrian = also a lowered 5th. Any note can be the start.'),
        ] },
      { type: 'match', ref: 'zhwiki-heptatonic',
        prompt: t('只弹白键：起点 ↔ 调式', '白鍵だけ：始まりの音 ↔ 旋法', 'White keys only: starting note ↔ mode'),
        pairs: [['D', 'Dorian'], ['E', 'Phrygian'], ['F', 'Lydian'], ['G', 'Mixolydian']],
        hint: t('从 C 开始按字母顺序：Ionian、Dorian、Phrygian、Lydian……', 'C から順に：イオニアン、ドリアン、フリジアン、リディアン……', 'In order from C: Ionian, Dorian, Phrygian, Lydian…'),
        explain: t('C Ionian、D Dorian、E Phrygian、F Lydian、G Mixolydian、A Aeolian、B Locrian。', 'C イオニアン、D ドリアン、E フリジアン、F リディアン、G ミクソリディアン、A エオリアン、B ロクリアン。', 'C Ionian, D Dorian, E Phrygian, F Lydian, G Mixolydian, A Aeolian, B Locrian.') },
      { type: 'choice', ref: 'omt2e-modes',
        prompt: t('七种调式里最"亮"的是？', '7 つの中でいちばん明るいのは？', 'Which mode is the brightest?'),
        options: ['Lydian', 'Ionian', 'Locrian'], answer: 0,
        hint: t('它比大调还多一个升高的音。', '長音階よりさらに 1 つ高くなった音がある。', 'It has one note raised even compared with major.'),
        explain: t('Lydian 是大调再把第 4 音升高，所以比大调还亮；Locrian 最暗。', 'リディアンは長音階の第 4 音を上げたもので、長音階より明るい。最も暗いのはロクリアン。', 'Lydian is major with a raised 4th, so it is brighter than major; Locrian is darkest.') },
      { type: 'match', ref: 'omt2e-modes',
        prompt: t('调式 ↔ 它的特征音', '旋法 ↔ 特徴音', 'Mode ↔ its colour note'),
        pairs: [['Lydian', t('大调 + 升高的 4', '長音階 + 上げた 4', 'major + raised 4')], ['Mixolydian', t('大调 + 降低的 7', '長音階 + 下げた 7', 'major + lowered 7')], ['Dorian', t('自然小调 + 升高的 6', '自然短音階 + 上げた 6', 'natural minor + raised 6')], ['Phrygian', t('自然小调 + 降低的 2', '自然短音階 + 下げた 2', 'natural minor + lowered 2')]],
        hint: t('亮的调式拿大调来比，暗的调式拿自然小调来比。', '明るい旋法は長音階と、暗い旋法は自然短音階と比べる。', 'Compare the bright modes with major and the dark ones with natural minor.'),
        explain: t('记住特征音，就能在任何音上搭出调式：先写大调或小调，再改那一个音。', '特徴音を覚えれば、どの音からでも作れます：長音階か短音階を書いて 1 音だけ変える。', 'Know the colour note and you can build any mode anywhere: write major or minor, then change that one note.') },
      { type: 'choice', ref: 'omt2e-modes', audio: { notes: [60, 62, 63, 65, 67, 69, 70, 72], mode: 'melody' },
        prompt: t('听：从 C 开始，有小三度（E♭），第 6 个音却是 A。这是？', '聴いて：C から、短 3 度（E♭）があるのに第 6 音は A。これは？', 'Listen: from C, a minor third (E♭) but the 6th note is A. Which mode?'),
        options: ['Dorian', 'Aeolian', 'Mixolydian'], answer: 0,
        hint: t('自然小调的第 6 音应该是 A♭。', '自然短音階なら第 6 音は A♭。', 'Natural minor would have A♭ as its 6th.'),
        explain: t('小调 + 升高的第 6 音 = Dorian。', '短調 + 上げた第 6 音 = ドリアン。', 'Minor plus a raised 6th = Dorian.') },
      { type: 'fill', ref: 'omt2e-modes',
        prompt: t('Aeolian 就是自然 ___ 调，Ionian 就是 ___ 调', 'エオリアンは自然 ___ 音階、イオニアンは ___ 音階', 'Aeolian is natural ___, Ionian is ___'),
        bank: [opt('minor', t('小', '短', 'minor')), opt('major', t('大', '長', 'major')), opt('blues', t('布鲁斯', 'ブルース', 'blues'))], answer: ['minor', 'major'],
        hint: t('A 开始的白键音阶、C 开始的白键音阶。', 'A からの白鍵の音階、C からの白鍵の音階。', 'The white-key scales from A and from C.'),
        explain: t('Aeolian = 自然小调，Ionian = 大调。', 'エオリアン = 自然短音階、イオニアン = 長音階。', 'Aeolian = natural minor; Ionian = major.') },
      { type: 'choice', ref: 'omt2e-modes',
        prompt: t('C Mixolydian 的第 7 个音是？', 'C ミクソリディアンの第 7 音は？', 'The 7th note of C Mixolydian is…'),
        options: ['B♭', 'B', 'A'], answer: 0,
        hint: t('Mixolydian = 大调 + 降低的 7。', 'ミクソリディアン = 長音階 + 下げた 7。', 'Mixolydian = major with a lowered 7th.'),
        explain: t('C 大调的第 7 音是 B，降低后是 B♭：C D E F G A B♭。', 'C 長調の第 7 音 B を下げて B♭：C D E F G A B♭。', 'C major’s 7th is B; lowered it is B♭: C D E F G A B♭.') },
    ],
  },
  {
    id: 'intervalqual', section: 'basics', feature: 'ear', icon: 'P5',
    title: t('音程的性质与转位', '音程の種類と転回', 'Interval quality and inversion'),
    blurb: t('纯、大、小、增、减；复音程；转位相加等于 9', '完全・長・短・増・減、複音程、転回は足して 9', 'Perfect, major, minor, augmented, diminished; compound intervals; inversions add to 9'),
    cards: [
      { type: 'guide', ref: 'omt2e-intervals', demo: { play: [[60, 64], [64, 72]] },
        title: t('度数 + 性质 = 准确的名字', '度数 + 種類 = 正確な名前', 'Size + quality = the exact name'),
        steps: [
          t('音程的"度数"只数字母（起点算 1），不管升降号：C–E 和 C–E♭ 都是三度。', '「度数」は文字だけを数え（出発点を 1）、変化記号は関係ありません：C–E も C–E♭ も 3 度。', 'An interval’s size just counts letters (start = 1), ignoring accidentals: C–E and C–E♭ are both thirds.'),
          t('1、4、5、8 度是"纯"音程；2、3、6、7 度分"大"和"小"。', '1・4・5・8 度は「完全」、2・3・6・7 度は「長」と「短」。', 'Unisons, fourths, fifths and octaves are perfect; seconds, thirds, sixths and sevenths are major or minor.'),
          t('比纯或大再大半音叫"增"，比纯或小再小半音叫"减"。超过八度的叫复音程，比如九度。', '完全・長より半音広いと「増」、完全・短より半音狭いと「減」。オクターヴを超えると複音程（9 度など）。', 'Half a step wider than perfect or major is augmented; half a step narrower than perfect or minor is diminished. Beyond an octave is a compound interval, like a ninth.'),
          t('把下面的音挪高八度叫"转位"：度数相加总是 9；大变小、小变大，纯还是纯，增变减。听：C–E 转成 E–C。', '下の音をオクターヴ上げるのが「転回」：度数は足して 9。長 ↔ 短、完全は完全、増 ↔ 減。聴いて：C–E が E–C に。', 'Moving the lower note up an octave inverts the interval: sizes add to 9; major ↔ minor, perfect stays perfect, augmented ↔ diminished. Listen: C–E becomes E–C.'),
        ] },
      { type: 'match', ref: 'omt2e-intervals',
        prompt: t('转位：度数 ↔ 转位后的度数', '転回：度数 ↔ 転回後の度数', 'Inversion: size ↔ size after inverting'),
        pairs: [[t('二度', '2 度', 'second'), t('七度', '7 度', 'seventh')], [t('三度', '3 度', 'third'), t('六度', '6 度', 'sixth')], [t('四度', '4 度', 'fourth'), t('五度', '5 度', 'fifth')], [t('同度', '1 度', 'unison'), t('八度', '8 度', 'octave')]],
        hint: t('两个数加起来等于 9。', '2 つの数を足すと 9。', 'The two numbers add up to 9.'),
        explain: t('2 + 7、3 + 6、4 + 5、1 + 8，都是 9。', '2 + 7、3 + 6、4 + 5、1 + 8、どれも 9。', '2 + 7, 3 + 6, 4 + 5, 1 + 8 — all make 9.') },
      { type: 'choice', ref: 'omt2e-intervals',
        prompt: t('大三度转位以后是？', '長 3 度を転回すると？', 'A major third inverts to…'),
        options: [t('小六度', '短 6 度', 'a minor sixth'), t('大六度', '長 6 度', 'a major sixth'), t('纯五度', '完全 5 度', 'a perfect fifth')], answer: 0,
        hint: t('3 + ? = 9，大变成……', '3 + ? = 9、長は……に変わる', '3 + ? = 9, and major becomes…'),
        explain: t('度数 3 → 6，性质大 → 小：小六度（例如 C–E 转成 E–C）。', '3 → 6、長 → 短で短 6 度（C–E → E–C）。', '3 → 6 and major → minor: a minor sixth (C–E becomes E–C).') },
      { type: 'choice', ref: 'omt2e-intervals', audio: { notes: [60, 66], mode: 'harmonic' },
        prompt: t('C 到 F♯ 叫什么？', 'C から F♯ は？', 'What is C up to F♯?'),
        options: [t('增四度', '増 4 度', 'augmented fourth'), t('减五度', '減 5 度', 'diminished fifth'), t('纯四度', '完全 4 度', 'perfect fourth')], answer: 0,
        hint: t('先数字母：C D E F 是几度？', 'まず文字を数える：C D E F は何度？', 'Count letters first: C D E F is what size?'),
        explain: t('C–F 是纯四度，F 升高成 F♯ 又大了半音，所以是增四度。（C–G♭ 声音一样，但字母是五度，叫减五度。）', 'C–F は完全 4 度、F♯ でさらに半音広いので増 4 度。（C–G♭ は同じ音でも 5 度なので減 5 度。）', 'C–F is a perfect fourth; F♯ is half a step wider, so an augmented fourth. (C–G♭ sounds the same but spans five letters: a diminished fifth.)') },
      { type: 'fill', ref: 'omt2e-intervals',
        prompt: t('比纯音程大半音叫 ___，比纯音程小半音叫 ___', '完全音程より半音広いと ___、半音狭いと ___', 'Half a step wider than perfect is ___; half a step narrower is ___'),
        bank: [opt('aug', t('增', '増', 'augmented')), opt('dim', t('减', '減', 'diminished')), opt('maj', t('大', '長', 'major')), opt('min', t('小', '短', 'minor'))], answer: ['aug', 'dim'],
        hint: t('纯音程没有"大小"，只能变成增或减。', '完全音程に長短はなく、増か減になる。', 'Perfect intervals have no major/minor — only augmented or diminished.'),
        explain: t('纯 → 增（大半音）或减（小半音）。大小音程也能再变成增或减。', '完全 → 増（半音広い）か減（半音狭い）。長短音程も増減になれます。', 'Perfect → augmented (wider) or diminished (narrower). Major and minor intervals can also become augmented or diminished.') },
      { type: 'choice', ref: 'omt2e-intervals',
        prompt: t('C4 到 D5 是什么音程？', 'C4 から D5 は？', 'What is C4 up to D5?'),
        options: [t('大九度（复音程）', '長 9 度（複音程）', 'a major ninth (compound)'), t('大二度', '長 2 度', 'a major second'), t('八度', 'オクターヴ', 'an octave')], answer: 0,
        hint: t('超过了一个八度。', 'オクターヴを超えている。', 'It goes past an octave.'),
        explain: t('八度再加一个大二度 = 大九度，超过八度的都叫复音程。', 'オクターヴ + 長 2 度 = 長 9 度。オクターヴを超えると複音程。', 'An octave plus a major second = a major ninth; anything beyond an octave is compound.') },
    ],
  },
  {
    id: 'texture', section: 'basics', feature: 'form', icon: '≡',
    title: t('织体：几条线怎么一起走', 'テクスチュア：何本の線がどう進むか', 'Texture: how the lines move together'),
    blurb: t('单声部、支声、主调、复调', 'モノフォニー・ヘテロフォニー・ホモフォニー・ポリフォニー', 'Monophony, heterophony, homophony, polyphony'),
    cards: [
      { type: 'guide', ref: 'omt2e-texture', demo: { play: [[60], [62], [64], [60, 64, 67], [62, 65, 69], [64, 67, 72]] },
        title: t('同样的音，不同的"编织法"', '同じ音でも「編み方」が違う', 'Same notes, different weaving'),
        steps: [
          t('织体说的是：有几条声部、它们怎样互相配合。', 'テクスチュアとは、声部がいくつあり、どう関わり合うかのこと。', 'Texture is how many voices there are and how they interact.'),
          t('单声部：只有一条旋律，没有伴奏。支声：几个人同时奏同一条旋律的不同变体。', 'モノフォニー：伴奏のない旋律 1 本。ヘテロフォニー：同じ旋律の変形が同時に鳴る。', 'Monophony: one unaccompanied melody. Heterophony: several variants of one melody at once.'),
          t('主调：几个声部节奏一致，一起换和声。复调：几条各自独立的旋律，节奏也各不相同。', 'ホモフォニー：声部が同じリズムで一緒に和声を動かす。ポリフォニー：独立した旋律がそれぞれのリズムで進む。', 'Homophony: voices move together at the same pace through the harmony. Polyphony: independent melodies with their own rhythms.'),
          t('大多数音乐不会只用一种织体，而是在它们之间来回切换。', 'たいていの音楽は 1 種類にとどまらず、行き来します。', 'Most music doesn’t stick to one texture; it moves between them.'),
        ] },
      { type: 'match', ref: 'omt2e-texture',
        prompt: t('织体 ↔ 描述', 'テクスチュア ↔ 説明', 'Texture ↔ description'),
        pairs: [[t('单声部', 'モノフォニー', 'monophony'), t('一条旋律，没有伴奏', '伴奏のない旋律 1 本', 'one melody, no accompaniment')], [t('支声', 'ヘテロフォニー', 'heterophony'), t('同一旋律的几种变体同时出现', '同じ旋律の変形が同時に', 'variants of one melody at once')], [t('主调', 'ホモフォニー', 'homophony'), t('各声部节奏一致地一起换和声', '同じリズムで一緒に和声を動かす', 'voices change harmony together')], [t('复调', 'ポリフォニー', 'polyphony'), t('几条独立的旋律和节奏', '独立した旋律とリズム', 'independent melodies and rhythms')]],
        hint: t('"复"= 好几条独立的线。', '「ポリ」= 独立した線が複数。', '“Poly” = several independent lines.'),
        explain: t('单声部 1 条线；支声是同一条线的变体；主调一起走；复调各走各的。', 'モノ 1 本、ヘテロは同じ線の変形、ホモは一緒、ポリは別々。', 'Monophony one line; heterophony variants of it; homophony together; polyphony independent.') },
      { type: 'choice', ref: 'omt2e-texture',
        prompt: t('一个人清唱，没有任何伴奏，是什么织体？', '伴奏なしの独唱は？', 'One person singing with no accompaniment is…'),
        options: [t('单声部', 'モノフォニー', 'monophony'), t('主调', 'ホモフォニー', 'homophony'), t('复调', 'ポリフォニー', 'polyphony')], answer: 0,
        hint: t('只有一条旋律。', '旋律は 1 本だけ。', 'Only one melody.'),
        explain: t('没有伴奏的单条旋律就是单声部。', '伴奏のない旋律 1 本がモノフォニー。', 'A single unaccompanied melody is monophony.') },
      { type: 'choice', ref: 'omt2e-texture',
        prompt: t('合唱团四个声部同一个节奏、一起换和弦，是？', '合唱の 4 声部が同じリズムで一緒に和音を変えるのは？', 'A choir’s four parts move in the same rhythm, changing chords together. That is…'),
        options: [t('主调', 'ホモフォニー', 'homophony'), t('复调', 'ポリフォニー', 'polyphony'), t('支声', 'ヘテロフォニー', 'heterophony')], answer: 0,
        hint: t('关键是"节奏一致"。', 'ポイントは「同じリズム」。', 'The key is “same rhythm”.'),
        explain: t('多个声部一起走和声 = 主调织体；如果每个声部节奏各不相同、像几条独立旋律，才是复调。', '一緒に和声を動かす = ホモフォニー。各声部が独立したリズムならポリフォニー。', 'Voices moving together through harmony = homophony; independent rhythms and lines would be polyphony.') },
      { type: 'choice', ref: 'omt2e-texture',
        prompt: t('一首曲子从头到尾只能是一种织体吗？', '1 曲は最初から最後まで 1 種類のテクスチュア？', 'Must a piece keep one texture from start to finish?'),
        options: [t('不是，常常来回切换', 'いいえ、よく切り替わる', 'No — it often switches'), t('是，必须统一', 'はい、統一する', 'Yes, it must stay the same')], answer: 0,
        hint: t('想想歌曲里有时齐唱、有时和声。', '歌でも斉唱になったりハモったりする。', 'Think of songs that alternate unison and harmony.'),
        explain: t('大多数音乐都会在不同织体之间移动。', 'たいていの音楽はテクスチュアの間を移動します。', 'Most music moves between textures.') },
    ],
  },
  {
    id: 'meter', section: 'basics', feature: 'rhythm', icon: '♩',
    title: t('拍子：跟着音乐点头', '拍子：音楽に合わせてうなずく', 'Meter: nod along'),
    blurb: t('单拍子与复拍子', '単純拍子と複合拍子', 'Simple and compound meters'),
    cards: [
      { type: 'guide', ref: 'omt2e-simple-meter',
        title: t('拍子就是你跟着点头的那个"拍"', '拍子はあなたがうなずく「拍」', 'The beat is what you nod to'),
        steps: [
          t('听音乐时会忍不住跟着拍手——那个一下一下规律出现的脉冲就是"拍"。', '音楽を聴くと思わず手拍子したくなる。その規則的な脈が「拍」。', 'The pulse you can’t help clapping along to is the beat.'),
          t('拍会两个、三个或四个一组：二拍子、三拍子、四拍子。', '拍は 2・3・4 つずつまとまる：2 拍子・3 拍子・4 拍子。', 'Beats group in twos, threes or fours: duple, triple, quadruple.'),
          t('每一拍再分成两份的是"单拍子"，分成三份的是"复拍子"。', '1 拍を 2 つに分けるのが「単純拍子」、3 つに分けるのが「複合拍子」。', 'If each beat splits in two it is simple meter; in three, compound meter.'),
        ] },
      { type: 'choice', ref: 'omt2e-simple-meter',
        prompt: t('拍号 3/4 上面的 3 表示？', '拍子記号 3/4 の上の 3 は？', 'In 3/4, the top 3 means…'),
        options: [t('每小节 3 拍', '1 小節に 3 拍', '3 beats per bar'), t('速度 3', 'テンポ 3', 'tempo 3'), t('3 个声部', '3 声部', '3 voices')], answer: 0,
        hint: t('单拍子里上面的数字数的是拍。', '単純拍子では上の数字は拍の数。', 'In simple meter the top number counts beats.'),
        explain: t('单拍子拍号：上面是每小节几拍，下面是哪种音符算一拍。3/4 是三拍子。', '単純拍子：上は 1 小節の拍数、下は 1 拍の音符。3/4 は 3 拍子。', 'Simple meter: top = beats per bar, bottom = the note that gets the beat. 3/4 is triple.') },
      { type: 'choice', ref: 'omt2e-compound-meter',
        prompt: t('复拍子的每一拍分成几份？', '複合拍子の 1 拍はいくつに分かれる？', 'In compound meter each beat divides into…'),
        options: ['3', '2', '4'], answer: 0,
        hint: t('像"嗒-嗒-嗒"一组一组地摇摆。', '「タ・タ・タ」と 3 つずつ揺れる感じ。', 'It sways in groups like "ta-ta-ta".'),
        explain: t('复拍子：每拍分成三份，再分成六份。', '複合拍子：1 拍が 3 つ、さらに 6 つに分かれます。', 'Compound meter: each beat divides into three, then six.') },
      { type: 'choice', ref: 'omt2e-compound-meter',
        prompt: t('6/8 每小节有几拍？', '6/8 は 1 小節に何拍？', 'How many beats per bar in 6/8?'),
        options: ['2', '6', '3'], answer: 0,
        hint: t('复拍子拍号上面的数字数的是"分份"，每拍 3 份。', '複合拍子の上の数字は「分割」の数で、1 拍 = 3。', 'In compound meter the top number counts divisions — three per beat.'),
        explain: t('6 个八分音符，每 3 个一拍——两拍，是复二拍子。', '8 分音符 6 つを 3 つずつで 2 拍、複合 2 拍子。', 'Six eighth notes in groups of three: two beats — compound duple.') },
    ],
  },
];

// 关卡顺序（从简到难）
const ORDER = ['keys', 'staff', 'rhythm', 'meter', 'intervals', 'intervalqual', 'major', 'minor', 'modes', 'pentatonic', 'texture'];
export const UNITS = ORDER.map((id) => {
  const unit = ALL.find((u) => u.id === id);
  if (!unit) throw new Error(`unknown unit ${id}`);
  return unit;
});
if (UNITS.length !== ALL.length) throw new Error('every unit must appear in ORDER');
