// Original beginner lessons and examples, checked against primary sources.
// ref:rubin-nonfunctional ref:koozin-planing ref:arndt-tonality
// ref:ircam-spectrum ref:ircam-spectral ref:gann-ji ref:gann-ji-reasons
export function makeModernStages({ t, chord, chain, frequencies, layers, midiForHz }) {
  const tagged = (audio, row, caption) => ({ ...audio, caption, events: audio.events.map(e => ({ ...e, targets: [`c${row}-0`], caption })) });
  const join = (...sounds) => {
    let offset = 0;
    const events = sounds.flatMap(sound => {
      const scale = 60 / sound.bpm;
      const result = sound.events.map(e => ({ ...e, at: offset + e.at * scale, beats: e.beats * scale }));
      offset += Math.max(...sound.events.map(e => (e.at + e.beats) * scale)) + .45;
      return result;
    });
    return { bpm: 60, events };
  };
  const compare = (...rows) => get => join(...rows.map(get));
  const stage = (title, records) => {
    const sounds = [];
    records.forEach(([label, text, audio], i) => {
      sounds.push(typeof audio === 'function' ? { ...audio(j => sounds[j]), caption: label } : tagged(audio, i, label));
    });
    return { title, labels: records.map(r => r[0]), steps: records.map(r => r[1]), sounds };
  };
  const C = [60,64,67], D = [62,66,69], E = [64,68,71];
  const planing = chain(C,D,E), pedal = chain([48,...C],[48,...D],[48,...E]);
  const low = [48,52,55,48], high = [78,82,85,78,82,85,78,78];
  const motif = chain(60,61,67), moved = chain(64,65,71);
  const just = frequencies(220,275,330), tempered = frequencies(220,220*2**(4/12),220*2**(7/12));
  const edo19 = frequencies(220,220*2**(6/19),220*2**(11/19));
  return {
    nonfunctional: [
      stage(t('和弦还可以这样连接','和音の別のつなぎ方','Another way to connect chords'), [
        [t('G7 → C：回到落脚点','G7 → C：落ち着く先へ','G7 → C: arriving home'), t('先听 G7 接 C。你可以把最后的 C 想成一个落脚点；G7 像在催着它到达。这是前面学过的属到主连接。先听感觉，不用背数字。','まず G7 から C を聴こう。最後の C を落ち着く場所、G7 をそこへ向かわせる響きと考えてみよう。前に学んだ属から主へのつながり。まず感じを聴けばよい。','Listen to G7 followed by C. Think of C as a place to settle and G7 as pointing towards it. This is the dominant-to-tonic connection from earlier lessons; start with the sound.'), chain([55,59,62,65],[48,...C])],
        [t('C 和弦：C E G','C 和音：C E G','C chord: C E G'), t('现在只听 C 和弦：C、E、G 三个音一起响。字母是音名；数字如 C4 表示它在哪个八度。把这三个音当作一个可以整体搬动的形状。','今度は C 和音だけ。C・E・G が同時に鳴る。文字は音名、C4 のような数字はオクターヴの位置。この 3 音をまとめて動かせる形と考えよう。','Now hear just the C chord: C, E and G together. Letters name notes; a number such as C4 gives the octave. Think of the three notes as one movable shape.'), chord(...C)],
        [t('C → D → E：同形移动','C → D → E：同じ形で移動','C → D → E: the same shape'), t('听三个大三和弦一起向上搬：C–E–G → D–F♯–A → E–G♯–B。每次每个音都升 2 个半音；半音是钢琴相邻键的距离，也要数黑键。这种保持内部距离的搬法叫同形平行移动。','3 つの長三和音を聴こう：C–E–G → D–F♯–A → E–G♯–B。毎回どの音も半音 2 つ上がる。半音は黒鍵も含む隣の鍵までの距離。この形を保つ動きを同形の平行移動という。','Hear C–E–G → D–F♯–A → E–G♯–B. Every note rises by two semitones each time. A semitone is the distance to the next piano key, including black keys. Keeping the internal shape this way is exact planing.'), planing],
        [t('低音 C 不动，上方移动','低音 C は固定、上は移動','Bass C stays; upper chords move'), t('再听一次，但底下每次都留着低音 C，上面的和弦继续移动。这个不动的低音叫持续低音。它能让 C 成为一个中心线索，上面却不必每次都走属到主。','もう一度、今度は下に低音 C を残し、上の和音だけ動かす。この固定した低音が持続低音。C を中心と感じる手がかりになるが、上の和音は毎回属から主へ進む必要はない。','Listen again with a fixed low C beneath the moving chords. This is a pedal tone. It can suggest C as a centre while the upper chords connect without a dominant-to-tonic pattern.'), pedal],
        [t('听连接方法，再找中心','つなぎ方と中心を別々に聴く','Hear connections and centres'), t('现在比较三个听例：回到 C、整体搬和弦、保留低音 C。非功能和声可以靠形状、共同音等关系连接。它不等于乱按音，也不等于一定没有中心。本关题目先只练“每个音搬同样远”。','3 例を比べよう：C へ落ち着く、和音をまとめて動かす、低音 C を残す。非機能和声は形や共通音などでつなげられる。無秩序でも、必ず中心がないという意味でもない。この関では全音を同じ幅だけ動かす練習をする。','Compare arriving at C, moving a chord shape, and retaining bass C. Nonfunctional harmony can connect through shapes or shared notes. It need not be random or lack a centre. The questions first practise moving every note by the same amount.'), compare(0,2,3)],
      ]),
      stage(t('分支 1：把整个和弦搬走','分岐 1：和音全体を動かす','Branch 1: move the whole chord'), [
        [t('原形 C E G：间距 4、3','元の C E G：間隔 4、3','Original C E G: gaps 4, 3'), t('先听 C–E–G。数相邻键位，C 到 E 是 4 个半音，E 到 G 是 3 个半音。这个“4、3”就是本例的内部形状。','C–E–G を聴こう。隣の鍵を数えると C から E は半音 4 つ、E から G は 3 つ。この「4、3」が内部の形。','Hear C–E–G. Counting adjacent keys, C to E is four semitones and E to G is three. The 4, 3 gaps describe its shape.'), chord(...C)],
        [t('都升 2：D F♯ A','全音を 2 上げる：D F♯ A','All rise by 2: D F♯ A'), t('把三个音各升 2 个半音：C→D，E→F♯，G→A。结果是 D–F♯–A；相邻间距仍是 4、3。注意不是只把最低音搬走。','全部を半音 2 つ上げる：C→D、E→F♯、G→A。D–F♯–A でも間隔は 4、3。最低音だけでなく全部を動かす。','Raise all three by two semitones: C→D, E→F♯, G→A. D–F♯–A still has gaps 4, 3. Move every note, not only the bass.'), chord(...D)],
        [t('比较：位置变，形状不变','比較：位置は変わり形は同じ','Compare: new position, same shape'), t('再听原形和新形。做题时先找到每个音的新键位，再检查它们之间的距离。这样能确认同形移动；只听见这种片段，还不能断言整首作品无调性。','元と新しい形を聴き比べよう。各音の新しい鍵を見つけ、間隔を確認する。これで同形移動は確かめられるが、この部分だけで全曲が無調とは決められない。','Compare the two shapes. Find each new key, then check the gaps. This establishes exact planing; the short passage alone does not establish that a whole work is atonal.'), compare(0,1)],
      ]),
      stage(t('分支 2：只在白键里移动','分岐 2：白鍵の中で動かす','Branch 2: move within the white keys'), [
        [t('C 大调白键：C E G','C 長調の白鍵：C E G','C-major white keys: C E G'), t('这次规则变了：只用 C 大调的白键。先听 C–E–G，记住原来是大三和弦，间距为 4、3 个半音。','今度は C 長調の白鍵だけ使う。まず C–E–G。元は長三和音で、間隔は半音 4、3。','Change the rule: use only the white keys of C major. Start with C–E–G, a major triad with gaps of four and three semitones.'), chord(...C)],
        [t('各到下个白键：D F A','次の白鍵へ：D F A','Next white key: D F A'), t('每个音去下一个白键：C→D，E→F，G→A。得到 D–F–A，是小三和弦，间距 3、4。这里的“下一步”按音阶数，所以每声部搬的半音数不一定相同。','各音を次の白鍵へ：C→D、E→F、G→A。D–F–A は短三和音で間隔 3、4。音階上の 1 歩なので、半音の移動幅は各声部で違ってよい。','Move each to the next white key: C→D, E→F, G→A. D–F–A is minor, with gaps 3, 4. A scale step need not move each voice by the same number of semitones.'), chord(62,65,69)],
        [t('比较：音阶规则与形状规则','比較：音階の規則と形の規則','Compare: scale rule versus shape'), t('这种按音阶位置搬的办法叫调内平行。它和同形平行的规则不同。题目写“限于某音阶”时先找音阶里的下一个音，再看结果和弦的性质。','音階位置に従う動きを音階内の平行移動という。同形移動とは規則が違う。「指定音階内」なら次の音階音を探し、結果の和音の種類を調べよう。','Moving by scale position is diatonic planing. Its rule differs from exact planing. When a question specifies a scale, find the next scale note, then identify the resulting chord.'), compare(0,1)],
      ]),
      stage(t('分支 3：留住两个音','分岐 3：2 音を残す','Branch 3: keep two notes'), [
        [t('第一组：C E G','第 1 組：C E G','First group: C E G'), t('先听 C–E–G。接下来不整体搬走它，而是留下其中两个音。看着 C 和 E，记住它们的位置。','まず C–E–G。全体を動かさず 2 音を残してみよう。C と E の位置を覚えておこう。','Hear C–E–G. This time we will keep two notes instead of moving the whole shape. Notice where C and E are.'), chord(...C)],
        [t('第二组：C E A','第 2 組：C E A','Second group: C E A'), t('现在听 C–E–A：C 和 E 没变，只有 G 换成 A。两个和弦里都有的音叫共同音。把两份音名并排找相同项，就能找出来。','次は C–E–A。C と E は同じで G だけ A になる。両方の和音にある音が共通音。2 つの音名リストで同じ項を探せばよい。','Now hear C–E–A: C and E stay, while G becomes A. Notes present in both chords are common tones. Find matching entries in the two note lists.'), chord(60,64,69)],
        [t('共同音：C、E','共通音：C、E','Common tones: C, E'), t('连着听两组，留意没有动的音。共同音可以让连接更连贯，功能和声也会用它。发现共同音这件事本身，不能证明转调或非功能和声。','続けて聴き、動かない音に注目。共通音は滑らかさを助け、機能和声でも使う。共通音があるだけで転調や非機能和声と決められない。','Listen in succession and notice the unchanged notes. Common tones can support continuity and also occur in functional harmony. They alone do not prove modulation or nonfunctional harmony.'), compare(0,1)],
      ]),
      stage(t('分支 4：下面不动，上面搬','分岐 4：下は固定、上は移動','Branch 4: fixed bass, moving upper chords'), [
        [t('只听低音：C C C','低音のみ：C C C','Bass alone: C C C'), t('先只听低音 C 反复出现。这里“中心”指一个像参照点的音；反复出现、停得久，都能成为中心线索。不是出现一次就算中心。','低音 C の繰り返しだけ聴こう。「中心」は基準点のように感じる音。反復や長さが手がかりになるが、1 回出ただけでは決まらない。','Hear repeated low C alone. A centre is a note that feels like a reference point. Repetition and duration can support that feeling; one occurrence is not enough.'), chain(48,48,48)],
        [t('C 低音＋上方 C D E','C 低音＋上の C D E','Bass C + upper C D E'), t('加回上面的 C、D、E 大三和弦。听低音始终在同一处，上方每个音各升 2 个半音。你可以同时记录“不动的底”和“移动的形状”。','上に C・D・E の長三和音を戻す。低音は同じ位置、上の各音は半音 2 つずつ上がる。固定した下と動く形を別々に記録できる。','Add back the upper C, D and E major chords. The bass stays while every upper note rises by two semitones. Record the fixed bass and moving shape separately.'), pedal],
        [t('中心线索 ≠ 属到主连接','中心の手がかり ≠ 属から主','Centre evidence ≠ a cadence'), t('中心和连接方法是两件事。本段有 C 的中心线索，上方靠平行移动连接，并没有演示属到主终止。做题只按给出的证据判断，不猜整首作品。','中心とつなぎ方は別のこと。この部分には C の手がかりがあり、上は平行移動でつながる。属から主への終止は示されていない。与えられた証拠の範囲で判断しよう。','A centre and a connection method are separate questions. Here C has centre evidence while the upper chords plane; no dominant-to-tonic cadence is demonstrated. Keep conclusions within the supplied evidence.'), compare(0,1)],
      ]),
    ],
    polytonality: [
      stage(t('先听两条线，再把它们叠起来','2 本の線を聴いてから重ねる','Hear two lines, then overlap them'), [
        [t('低声部：C E G C','低声部：C E G C','Low line: C E G C'), t('先听下面这条线：C–E–G–C。它从 C 出发，又回到 C。把“中心”理解成经常回去的落脚点；本例重复起音和结尾，给你 C 的线索。','まず下の線 C–E–G–C。C から始まり C へ戻る。「中心」は何度も帰る落ち着く先と考えよう。この例は始めと終わりで C を強調する。','Start with the low line C–E–G–C. It begins and returns to C. Think of a centre as a recurring place to settle; the repeated start and ending provide evidence for C.'), chain(...low)],
        [t('高声部：F♯ A♯ C♯ F♯','高声部：F♯ A♯ C♯ F♯','High line: F♯ A♯ C♯ F♯'), t('再单听上面这条线：F♯–A♯–C♯–F♯。♯ 表示升高半音。它回到的是 F♯，所以这一层的落脚点和下面不同。先把两层各听清楚。','次は上の線 F♯–A♯–C♯–F♯ だけ。♯ は半音上げる記号。こちらは F♯ へ戻るので下の層とは落ち着く先が違う。まず各層を聴き取ろう。','Hear the high line F♯–A♯–C♯–F♯ alone. ♯ means one semitone higher. This line returns to F♯, a different centre from the low line. First get to know each layer.'), chain(78,82,85,78)],
        [t('同时：C 层＋F♯ 层','同時：C 層＋F♯ 層','Together: C layer + F♯ layer'), t('现在两条线同时响。跟着低音找 C，再跟着高音找 F♯。两层各维持自己的中心，并且在同一段时间活动，这个教学例子叫双调性；多于一个中心同时活动，统称多调性。','今度は同時に鳴る。低音で C、高音で F♯ を追ってみよう。同じ時間に各層が別の中心を保つこの例は複調性。複数の中心が同時に働くものを多調性と呼ぶ。','Now overlap the lines. Follow low C, then high F♯. In this example each layer sustains its own centre at the same time: bitonality. Multiple simultaneous centres are called polytonality.'), layers(low,high)],
        [t('先后出现，与同时出现','順番に出る場合と同時の場合','One after another versus together'), t('最后先听两层依次出现，再听同时出现。先 C、后另一个调，只是先后变化。判断双调性要找齐三个线索：同时、不同中心、每层有支持中心的乐句。一个复杂和弦还不够。','最後に順番の場合と同時の場合を比べよう。C の後に別の調が来るだけなら時間的な変化。複調性には同時性、別の中心、各層のフレーズによる裏付けが必要。複雑な和音 1 つだけでは足りない。','Compare the two lines in succession with the overlap. C followed by another key is successive change. Look for simultaneity, different centres and phrases supporting each centre. One complex chord is insufficient.'), compare(0,1,2)],
      ]),
      stage(t('分支 1：每层的落脚点','分岐 1：各層が落ち着く先','Branch 1: each layer’s centre'), [
        [t('低层回到 C','低層は C へ戻る','Low layer returns to C'), t('先把耳朵放在低层：C–E–G–C。开头和结尾都落在 C，这是这个例子的中心线索。分析时先单独记录这一层。','低層 C–E–G–C を聴こう。始めと終わりが C で、この例の中心の手がかりになる。まずこの層だけ記録する。','Focus on low C–E–G–C. Its start and ending support C as this example’s centre. Record this layer on its own first.'), chain(...low)],
        [t('高层回到 D','高層は D へ戻る','High layer returns to D'), t('再听高层 D–F♯–A–D，它回到 D。不能因为低层有 C，就把高层所有音也当成 C 的附属；先看它自己的音和乐句。','高層 D–F♯–A–D は D へ戻る。低層が C だからといって、高層の音をすべて C に従わせない。各層の音とフレーズを調べる。','High D–F♯–A–D returns to D. Do not assign every high note to C simply because the low layer has C. Examine each line’s own notes and phrases.'), chain(74,78,81,74)],
        [t('同时保持 C 与 D','C と D を同時に保つ','Maintain C and D together'), t('现在叠起来听。记录要保留“哪些音属于哪层”以及“有没有同时响”。如果把所有音名混成一个列表，就会丢掉双调性的重要线索。','重ねて聴こう。どの音がどの層か、同時に鳴るかを残して記録する。全部を 1 つのリストに混ぜると複調性の手がかりが失われる。','Listen to the overlap. Preserve which notes belong to which layer and when they overlap. Merging all notes into one list loses important bitonality evidence.'), layers(low,[74,78,81,74,78,81,74,74])],
      ]),
      stage(t('分支 2：叠和弦，还不等于两个调','分岐 2：和音の重なりと 2 つの調','Branch 2: stacked chords and two keys'), [
        [t('下方和弦：C E G','下の和音：C E G','Lower chord: C E G'), t('先听 C 大三和弦：C、E、G。它只告诉我们现在一起响的是哪些音，还没有一条持续的旋律来建立中心。','まず C 長三和音 C・E・G。今同時に鳴る音は分かるが、中心を持続させる旋律はまだない。','Hear the C major triad, C, E and G. It tells us which notes sound together; we do not yet have a sustained line establishing a centre.'), chord(...C)],
        [t('上方和弦：D F♯ A','上の和音：D F♯ A','Upper chord: D F♯ A'), t('再听 D 大三和弦：D、F♯、A。把两组音合起来，一共有 C、D、E、F♯、G、A 六种音名，这一步是在描述材料。','次は D 長三和音 D・F♯・A。両方をまとめると C・D・E・F♯・G・A の 6 種類。この段階では素材を述べている。','Hear D, F♯ and A. Together the two groups contain C, D, E, F♯, G and A: six pitch classes. This describes the material.'), chord(74,78,81)],
        [t('同时叠置：六个音','同時に重ねる：6 音','Stacked together: six notes'), t('现在六个音一起响，这叫复合和弦。要叫双调性，还要有后续乐句，让两层各自维持不同中心。做题把“叠了哪些音”和“建立了哪些中心”分开判断。','6 音を同時に鳴らすと複和音。複調性というには、各層が別の中心を保つフレーズも必要。重なる音と成立する中心を分けて判断しよう。','Six notes together form a polychord. Bitonality additionally needs phrases sustaining different centres in each layer. Separate the stacked notes from evidence of centres.'), chord(...C,74,78,81)],
      ]),
      stage(t('分支 3：用高低和节奏分开两层','分岐 3：高さとリズムで層を分ける','Branch 3: separate layers by register and rhythm'), [
        [t('低层：每两拍一个音','低層：2 拍に 1 音','Low layer: one note every two beats'), t('先只听低层 C、E、G、C，每个音占两拍。可以一边数“一二、一二”。这是较慢的线；数起音时，每次重新发声才算一个。','低層 C・E・G・C を各 2 拍で聴こう。「1、2」と数えてみよう。ゆっくりした線で、新しく鳴り始めるたびに起音を 1 回と数える。','Hear low C, E, G, C, two beats per note. Count “one, two”. This is the slower line. An attack is a fresh start of a note.'), {bpm:100,events:low.map((n,i)=>({at:i*2,notes:[n],beats:1.8}))}],
        [t('高层：每拍一个音','高層：毎拍 1 音','High layer: one note each beat'), t('高层 D、F♯、A 等音每拍换一次，同样八拍会有八个起音。低层八拍只有四个。音区高低和快慢不同，能帮我们分辨两条线。','高層 D・F♯・A などは毎拍動く。同じ 8 拍で起音は 8 回、低層は 4 回。高さと速さの違いで線を聴き分けやすくなる。','The high line changes each beat: eight attacks in eight beats, compared with four below. Different registers and rhythms help distinguish the lines.'), {bpm:100,events:[74,78,81,74,78,81,74,74].map((n,i)=>({at:i,notes:[n],beats:.85}))}],
        [t('同时：慢低层＋快高层','同時：遅い低層＋速い高層','Together: slow low line + fast high line'), t('现在两层同时响，试着只数低层，再只数高层。分得清两层，不代表一定多调性；还要像前面的例子那样，检查各层是不是维持不同中心。','同時に聴き、低層だけ、高層だけ数えてみよう。層が明瞭でも必ず多調性ではない。各層が別の中心を保つかも確認する。','Hear both and count one layer at a time. Clear layers do not automatically imply polytonality; also check whether they maintain different centres.'), layers(low,[74,78,81,74,78,81,74,74])],
      ]),
      stage(t('分支 4：分清三种情况','分岐 4：3 つの場合を区別','Branch 4: distinguish three situations'), [
        [t('先 C，后 D','先に C、後で D','C first, then D'), t('第一种：先听 C 的片段，结束后才出现 D 的片段。没有同时重叠，所以不能仅凭“用了两个调”就叫双调性。','第 1 例：C の部分が終わってから D の部分。同時に重ならないので、2 つの調を使うだけでは複調性といわない。','First, a C passage ends before a D passage begins. Using two keys in succession is not sufficient for bitonality.'), chain(C,D)],
        [t('C 大调 → C 小调：E 换 E♭','C 長調 → C 短調：E を E♭ へ','C major → C minor: E becomes E♭'), t('第二种：C–E–G 换成 C–E♭–G。中间的音变了，中心仍可能是 C。这是大小调材料的变化，并没有因此自动出现两个中心。','第 2 例：C–E–G を C–E♭–G へ。真ん中の音は変わるが中心は C のままでもよい。長短の素材の変化だけで 2 中心にはならない。','Next, C–E–G becomes C–E♭–G. The middle note changes while C may remain the centre. Changing major/minor material does not automatically establish two centres.'), chain(C,[60,63,67])],
        [t('C 层与 D 层同时活动','C 層と D 層が同時に動く','C and D layers active together'), t('第三种：低层回到 C，高层回到 D，同时活动。它有不同中心的持续线索。判断时问三句：同时吗？中心不同吗？各层有什么证据？','第 3 例：低層は C、高層は D へ戻り同時に動く。別中心の持続的な手がかりがある。同時か、別中心か、各層の証拠は何かを問おう。','Finally, low C and high D recur in simultaneous lines. This supplies ongoing centre evidence. Ask: simultaneous? Different centres? What supports each centre?' ), layers(low,[74,78,81,74,78,81,74,74])],
      ]),
    ],
    atonality: [
      stage(t('不用一个“家”，也能有清楚的线索','1 つの「帰る先」がなくても仕組みはある','Organisation without one home note'), [
        [t('短旋律：C D♭ G','短い旋律：C D♭ G','Short idea: C D♭ G'), t('先只听三个音 C–D♭–G。这样一小段容易认出的音乐想法叫动机。无调性指不围绕一个稳定的调性中心组织；它仍然可以用这样的短想法建立联系。','まず C–D♭–G の 3 音。このような短く覚えやすい考えが動機。無調は安定した調性中心を軸に組織しないことだが、短い考えでつながりを作れる。','Hear C–D♭–G. A short recognisable idea like this is a motive. Atonality means not organising around a stable tonal centre; motives can still supply connections.'), motif],
        [t('走法：上 1，再上 6','動き：上へ 1、次に 6','Pattern: up 1, then up 6'), t('再听并看距离：C 到 D♭ 是向上 1 个半音，D♭ 到 G 是向上 6 个半音。半音要把黑键也数进去。先记住“近一步、远一跳”，不用猜调名。','距離を見てもう一度聴こう。C から D♭ は半音 1 つ上、D♭ から G は 6 つ上。黒鍵も数える。まず小さな一歩と大きな跳躍を覚え、調名は推測しない。','Listen again: C to D♭ is up one semitone, then D♭ to G is up six. Count black keys too. Remember the small step and larger leap without guessing a key.'), motif],
        [t('整体搬高：E F B','全体を上へ：E F B','Move it higher: E F B'), t('把每个音都升 4 个半音，听 E–F–B。起点变了，走法仍是上 1、上 6。把整段这样搬动叫移位；它不自动等于音乐已经转到新调。','各音を半音 4 つ上げ、E–F–B を聴こう。始めは変わっても上 1、上 6 の動きは同じ。全体を動かすのが移高だが、自動的に別の調への転調とはならない。','Raise every note by four semitones to hear E–F–B. The start changes but the up-1, up-6 pattern stays. This is transposition; it does not automatically establish a new key.'), moved],
        [t('能确认走法，不能猜整首','動きは確認、全曲は決めつけない','Confirm the pattern; keep the scope'), t('连着比较两遍，找相同的走法。只有这三个音和一个移位版本，不能证明整首无调性，也不是完整十二音列。本关只判断你看得到的局部关系。','2 つを続けて聴き、同じ動きを探そう。3 音と移高形だけでは全曲の無調を証明できず、完全な十二音列でもない。この関では見えている局所の関係を判断する。','Compare the two versions. Three notes and a transposed copy cannot establish that an entire piece is atonal and are not a complete twelve-tone row. Judge the local relationship supplied here.'), compare(0,2)],
      ]),
      stage(t('分支 1：把上行和下行记清楚','分岐 1：上がる・下がるを記録','Branch 1: record up and down'), [
        [t('C4 D♭4 G4：+1、+6','C4 D♭4 G4：+1、+6','C4 D♭4 G4: +1, +6'), t('数字 4 表示八度位置，+ 表示向上。C4→D♭4 是 +1，D♭4→G4 是 +6；每一项只比较相邻的两个音。','4 はオクターヴ位置、+ は上行。C4→D♭4 は +1、D♭4→G4 は +6。毎回隣り合う 2 音だけを比べる。','The 4 indicates octave position and + means up. C4→D♭4 is +1; D♭4→G4 is +6. Compare adjacent pairs separately.'), motif],
        [t('倒着读：G4 D♭4 C4','逆に読む：G4 D♭4 C4','Read backwards: G4 D♭4 C4'), t('现在从末尾倒着读，听 G4→D♭4→C4。先下 6 个半音，再下 1 个，写作 −6、−1。距离的顺序和方向都改变了。','終わりから逆に G4→D♭4→C4。まず半音 6 つ下、次に 1 つ下で −6、−1。距離の順番と方向の両方が変わる。','Read from the end: G4→D♭4→C4. Go down six, then down one: −6, −1. Both gap order and direction change.'), chain(67,61,60)],
        [t('比较：+1、+6 → −6、−1','比較：+1、+6 → −6、−1','Compare: +1, +6 → −6, −1'), t('做题别只交换数字，也要改方向。按“后一音减前一音”逐对计算；音名后面的八度数字不同，也必须计入实际距离。','数字を入れ替えるだけでなく方向も変える。後の音高から前を引き、各対を計算。オクターヴの数字が違えば実際の距離に含める。','Do not merely swap the numbers: reverse the directions too. Subtract the previous pitch from the next for each pair, including octave differences.'), compare(0,1)],
      ]),
      stage(t('分支 2：三个音一起移位','分岐 2：3 音を一緒に移高','Branch 2: transpose all three notes'), [
        [t('原形：C D♭ G','元の形：C D♭ G','Original: C D♭ G'), t('先听原形，走法是 +1、+6。接下来只改变它的位置，不改变各音之间的距离。','元の +1、+6 を聴こう。次は位置だけ変え、音同士の距離は保つ。','Hear the original +1, +6 pattern. Next we change its position while retaining the distances between notes.'), motif],
        [t('每音 +4：E F B','各音 +4：E F B','Each note +4: E F B'), t('C 升 4 个半音到 E，D♭ 到 F，G 到 B。听新形 E–F–B。三个音都搬同样远，所以内部走法没有变。','C は半音 4 つ上の E、D♭ は F、G は B。新しい E–F–B を聴こう。全音を同じ幅だけ動かしたので内部の動きは同じ。','C rises four semitones to E, D♭ to F, and G to B. Hear E–F–B. Equal movement preserves the internal pattern.'), moved],
        [t('检查：仍然 +1、+6','確認：まだ +1、+6','Check: still +1, +6'), t('比较两个版本。做题逐音搬位置，再逐对检查距离。只搬一个音会改变形状；整体移位说明一种操作，不足以证明调性转调。','2 つを比べ、各音を動かしてから各対の距離を確認。1 音だけ動かすと形は変わる。全体の移高という操作だけで調性の転調は証明できない。','Compare them. Move each note, then check each gap. Moving only one note changes the shape. Transposition is an operation, not sufficient evidence of modulation.'), compare(0,1)],
      ]),
      stage(t('分支 3：倒着读，和反方向走','分岐 3：逆順と方向の反転','Branch 3: backwards order versus reversed direction'), [
        [t('原形：C D♭ G','元の形：C D♭ G','Original: C D♭ G'), t('原形的规则是：从 C 出发，上 1 个半音，再上 6 个。先把音的顺序和移动方向都记清楚。','元の規則は C から上 1、次に上 6。音の順番と方向を別々に覚えよう。','The original starts at C, goes up one semitone, then up six. Keep note order and movement direction clear.'), motif],
        [t('倒序：G D♭ C；−6、−1','逆順：G D♭ C；−6、−1','Reverse order: G D♭ C; −6, −1'), t('第一种是倒着读：G、D♭、C，先下 6 再下 1。因为从末尾读，起音也变成 G。这叫逆行。','1 つ目は逆に読む G・D♭・C、下 6、下 1。終わりから読むので始めも G になる。これが逆行。','First read backwards: G, D♭, C, down six then down one. Starting from the end changes the first note to G. This is retrograde.'), chain(67,61,60)],
        [t('反向：C B F；−1、−6','方向反転：C B F；−1、−6','Reverse directions: C B F; −1, −6'), t('第二种保留起音 C，只把每一步的上改成下：下 1 到 B，再下 6 到 F。得到 C4–B3–F3。这叫倒影，和倒着读的顺序不同。','2 つ目は C を始めに保ち、上を下へ変える。下 1 で B、下 6 で F、C4–B3–F3。これが反行で、逆に読む場合とは順番が違う。','Next retain C as the start, reversing each up into down: down one to B, then down six to F, giving C4–B3–F3. This is inversion, different from reversing note order.'), chain(60,59,53)],
        [t('比较逆行与倒影','逆行と反行を比較','Compare retrograde and inversion'), t('听完原形、逆行、倒影后，看题目要改的是“顺序”还是“方向”。这两个按钮代表不同操作，不能把 −6、−1 和 −1、−6 混用。','元・逆行・反行を比べ、課題が変えるのは順番か方向かを確認。2 つは別の操作で −6、−1 と −1、−6 を混同しない。','Compare original, retrograde and inversion. Check whether the question changes order or direction. −6, −1 and −1, −6 describe different operations.'), compare(0,1,2)],
      ]),
      stage(t('分支 4：只说证据支持的结论','分岐 4：証拠が支える結論だけ','Branch 4: stay with the evidence'), [
        [t('材料一：C D♭ G','素材 1：C D♭ G','Material 1: C D♭ G'), t('假设题目只给三个音 C–D♭–G。你可以数出相邻距离 +1、+6，但还没听到整首作品，也没见到完整十二音列。','課題が C–D♭–G の 3 音だけなら +1、+6 は数えられる。しかし全曲や完全な十二音列はまだ示されていない。','Suppose the question gives only C–D♭–G. You can verify gaps +1, +6, but have not heard a whole work or seen a complete twelve-tone row.'), motif],
        [t('材料二：E F B','素材 2：E F B','Material 2: E F B'), t('再给 E–F–B，可以确认它是整体升 4 个半音，走法不变。这里“能确认”的是局部结构，不是整首的调性类别。','E–F–B もあれば全体が半音 4 つ上で動きは同じと確認できる。確かめられるのは局所構造で、全曲の調性の分類ではない。','With E–F–B too, you can establish a four-semitone transposition preserving the pattern. This verifies local structure, not a whole-piece tonal classification.'), moved],
        [t('相同走法；整体需更多材料','動きは同じ；全体には追加資料','Same pattern; more context needed'), t('做题优先选可以实际核对的描述。无调性并不等于没有结构；短片段有规律，也不代表它一定属于某个调。以后有更多材料再判断整体。','実際に確認できる記述を選ぼう。無調にも構造はあり、短い規則的な部分だけで特定の調とも決まらない。全体の判断は追加の素材で行う。','Choose the description you can verify. Atonality can have structure, and a short patterned passage need not belong to a particular key. Whole-piece judgements need more context.'), compare(0,1)],
      ]),
    ],
    spectralharmony: [
      stage(t('把声音拆成几根“音柱”','音をいくつかの成分に分ける','Build a sound from its components'), [
        [t('一个低音：110 Hz','1 つの低音：110 Hz','One low tone: 110 Hz'), t('先听一个低音。110 Hz 表示每秒振动 110 次；同样条件下，振动越快，音越高。先把 Hz 当作给音高标位置的数值，不用记公式。','まず低い音。110 Hz は 1 秒に 110 回の振動。同じ条件なら速い振動ほど高い音。Hz を音高の位置を表す数字として読もう。','Hear one low tone. 110 Hz means 110 vibrations each second; a faster vibration gives a higher pitch. First read Hz as a numerical pitch position.'), frequencies(110)],
        [t('倍数：110、220、330 Hz','倍数：110、220、330 Hz','Multiples: 110, 220, 330 Hz'), t('现在依次听 110、220、330 Hz，分别是 110 的 1、2、3 倍。理想谐波模型把最低的 110 叫基频，计作第 1 分音；第 2 分音是 2 倍，第 3 是 3 倍。','110、220、330 Hz を順に聴こう。110 の 1、2、3 倍。理想調和モデルでは最低の 110 が基周波数で第 1 部分音。第 2 は 2 倍、第 3 は 3 倍。','Hear 110, 220 and 330 Hz in order: one, two and three times 110. In this ideal harmonic model, 110 is the fundamental and partial 1; partial 2 is twice it and partial 3 is three times it.'), chain(...[110,220,330].map(midiForHz))],
        [t('第 4、5、6：440、550、660 Hz','第 4、5、6：440、550、660 Hz','Partials 4, 5, 6: 440, 550, 660 Hz'), t('继续数倍数：第 4 分音是 110×4=440，第 5 是 550，第 6 是 660 Hz。依次听这三个音。编号说的是基频的几倍，不是音程的几度。','倍数を続けよう。第 4 は 110×4=440、第 5 は 550、第 6 は 660 Hz。3 音を順に聴く。番号は基周波数の何倍かで、音程の度数ではない。','Continue the multiples: partial 4 is 110×4=440, partial 5 is 550, and partial 6 is 660 Hz. Hear them in order. Partial numbers count multiples, not interval names.'), chain(...[440,550,660].map(midiForHz))],
        [t('三根音柱一起响','3 成分を同時に鳴らす','Sound the three components together'), t('把 440、550、660 Hz 同时响起来，就从分音关系做成了一个和声材料。频谱和声会从声音的内部成分及变化寻找音乐材料，也会关心强弱和时间。这里先用三个音看懂这个想法。','440、550、660 Hz を同時に鳴らすと部分音の関係から和声素材ができる。スペクトル和声は音の成分と変化から素材を探し、強弱や時間も扱う。まず 3 音で考え方をつかもう。','Sound 440, 550 and 660 Hz together to build harmonic material from partial relationships. Spectral harmony draws on a sound’s components and transformations, including amplitude and time. Start with this three-tone model.'), frequencies(440,550,660)],
        [t('做题：基频 × 分音编号','問題：基周波数 × 部分音番号','For questions: fundamental × partial number'), t('本关先只练乘法：若基频换成 100 Hz，第 4 分音就是 100×4=400 Hz。现在听 100 后接 400。真实声音的分音可以更复杂；这里计算的是题目指定的理想谐波模型。','この関はまず掛け算。基周波数が 100 Hz なら第 4 は 100×4=400 Hz。100 の後で 400 を聴こう。実音の部分音はもっと複雑な場合もあるが、問題は指定の理想モデルを計算する。','Practise multiplication first: with fundamental 100 Hz, partial 4 is 100×4=400 Hz. Hear 100 followed by 400. Real sounds can have more complex partials; questions specify this ideal harmonic model.'), chain(midiForHz(100),midiForHz(400))],
      ]),
      stage(t('分支 1：编号与音程不是一回事','分岐 1：番号と音程は別のもの','Branch 1: partial numbers versus intervals'), [
        [t('基频＝第 1 分音：100 Hz','基音＝第 1 部分音：100 Hz','Fundamental = partial 1: 100 Hz'), t('先听基频 100 Hz。本课从基频开始编号，所以它自己就是第 1 分音，不从它上方才开始数。','基周波数 100 Hz を聴こう。この課では基音から番号を数えるので、それ自体が第 1 部分音。上の音から数え始めない。','Hear fundamental 100 Hz. Here numbering starts with the fundamental itself as partial 1, not with a tone above it.'), frequencies(100)],
        [t('第 4＝400；第 5＝500 Hz','第 4＝400；第 5＝500 Hz','Partial 4 = 400; partial 5 = 500 Hz'), t('乘以编号，得到 400 和 500 Hz，依次听它们。两音的频率比用高音除以低音：500÷400=5/4，不是把编号相减。','番号を掛けると 400 と 500 Hz。順に聴こう。2 音の周波数比は高い方÷低い方、500÷400=5/4。番号を引くのではない。','Multiply by the partial numbers to get 400 and 500 Hz. Hear them in order. Their frequency ratio is higher divided by lower: 500÷400=5/4, not the difference between partial numbers.'), chain(midiForHz(400),midiForHz(500))],
        [t('两音一起：频率比 5/4','同時に：周波数比 5/4','Together: frequency ratio 5/4'), t('现在一起听。这里“第 5”只说 5 倍基频，不代表比第 4 分音高五度。做题先算两个 Hz，再相除求比例。','同時に聴こう。「第 5」は基周波数の 5 倍という意味で、第 4 より 5 度上ではない。まず各 Hz を計算してから割って比を求める。','Hear them together. “Partial 5” means five times the fundamental, not a fifth above partial 4. Calculate both frequencies, then divide to find the ratio.'), frequencies(400,500)],
      ]),
      stage(t('分支 2：同一个音名，也可能不一样高','分岐 2：同じ音名でも高さは違いうる','Branch 2: one note name, different tuning'), [
        [t('原比例 7/4：968.83 音分','元の比 7/4：968.83 セント','Original 7/4: 968.83 cents'), t('音分是量音程的小尺子：一个十二平均律半音是 100 音分。先听 220 与 385 Hz，比例 385÷220=7/4，大小约 968.83 音分。','セントは音程の細かな物差しで、12 平均律の半音は 100 セント。220 と 385 Hz を聴こう。385÷220=7/4、約 968.83 セント。','Cents measure intervals finely: a 12-EDO semitone is 100 cents. Hear 220 and 385 Hz, ratio 7/4, about 968.83 cents.'), frequencies(220,385)],
        [t('钢琴近似：1000 音分','鍵盤の近似：1000 セント','Piano approximation: 1000 cents'), t('十二平均律把附近的位置放在 1000 音分。听这个近似版本，上面的音约 392 Hz，略高于原来的 385。没听出细微差别也没关系，可以看数值。','12 平均律の近い位置は 1000 セント。近似を聴こう。上は約 392 Hz で元の 385 より少し高い。細かな差が聴き取れなくても数値で確認できる。','The nearby 12-EDO position is 1000 cents. Hear the approximation: the upper tone is about 392 Hz, slightly above 385. You can use the numbers even if the small difference is hard to hear.'), frequencies(220,220*2**(1000/1200))],
        [t('近似−原值＝+31.17 音分','近似−元＝+31.17 セント','Approximation − original = +31.17 cents'), t('比较两种版本。误差按“近似减原值”：1000−968.83≈+31.17，正号表示近似更高。题目给了音分时直接相减；更精确的计算用未舍入值。','2 つを比べる。誤差は近似−元で 1000−968.83≈+31.17、+ は近似が高いこと。指定値を引き、厳密な計算では丸め前の値を使う。','Compare them. Error is approximation minus original: 1000−968.83≈+31.17. Positive means the approximation is higher. Subtract the given cents; use unrounded values for precise calculations.'), compare(0,1)],
      ]),
      stage(t('分支 3：把一根音柱稍微移开','分岐 3：成分を少しずらす','Branch 3: move one component slightly'), [
        [t('100、200、300：1、2、3 倍','100、200、300：1、2、3 倍','100, 200, 300: multiples 1, 2, 3'), t('题目指定基频 100 Hz。100、200、300 都是它的整数倍，先听这一组。第三项正好是第 3 分音。','指定基周波数は 100 Hz。100、200、300 は整数倍で、まずこれを聴く。第 3 項はちょうど第 3 部分音。','The given fundamental is 100 Hz. Hear 100, 200 and 300, all integer multiples. The third value is exactly partial 3.'), frequencies(100,200,300)],
        [t('100、200、305：最后 +5 Hz','100、200、305：最後を +5 Hz','100, 200, 305: last component +5 Hz'), t('只把 300 改成 305，其余不动。305÷100=3.05，不再是指定基频的整数倍。这里比较的是相对 100 Hz 的位置，不擅自换别的基频。','300 だけ 305 に変える。305÷100=3.05 で指定基周波数の整数倍ではない。100 Hz に対する位置を比べ、勝手に別の基音へ変えない。','Change only 300 to 305. Since 305÷100=3.05, it is no longer an integer multiple of the given fundamental. Compare against 100 Hz without substituting another fundamental.'), frequencies(100,200,305)],
        [t('听原组，再听偏移组','元とずらした組を比較','Compare original and offset'), t('比较后算偏移：305−300=5 Hz。偏离理想整数倍可以成为声音变形的材料，不等于所有这样的声音都只是噪声。判断遵守题目给定的模型。','比べてずれを計算：305−300=5 Hz。整数倍からのずれは音の変形素材にもなり、すべて雑音というわけではない。指定モデルで判断する。','Compare and calculate the offset: 305−300=5 Hz. Departures from integer multiples can provide transformation material; they are not all simply noise. Use the specified model.'), compare(0,1)],
      ]),
      stage(t('分支 4：音相同，进入时间不同','分岐 4：同じ音で入りの時間を変える','Branch 4: same tones, different entry times'), [
        [t('440、550、660：一起进入','440、550、660：同時に入る','440, 550, 660: enter together'), t('先听三个频率一起进入。它们在同一时刻开始，所以听起来是一块声音。先记录“哪些音”和“什么时候进”。','3 周波数を同時に入れて聴こう。同じ時刻に始まるので 1 つの響きになる。音の種類と入る時刻を記録する。','Hear the three frequencies start together as one sonority. Record which tones sound and when they enter.'), frequencies(440,550,660)],
        [t('同样三个音：依次进入','同じ 3 音：順番に入る','The same tones: enter in sequence'), t('再听同样的 440、550、660 Hz 依次进入。音高材料没有换，时间组织换了；“声音怎么变化”也能成为作曲的内容。','同じ 440、550、660 Hz を順に聴こう。音高の素材は同じで時間の組織が変わる。音の変化の仕方も作曲の内容になる。','Hear the same 440, 550 and 660 Hz enter in sequence. The pitch material stays while the timing changes. How a sound develops can itself be musical material.'), chain(...[440,550,660].map(midiForHz))],
        [t('比较：同时与依次','比較：同時と順番','Compare together and in sequence'), t('比较两种进入方式。真实频谱音乐还会改变各成分的强弱和配器。我们的听例只演示频率与时间，不复原真实乐器的完整音色。','2 つの入り方を比べよう。実際のスペクトル音楽は成分の強弱や楽器配置も変える。この例は周波数と時間だけで、実楽器の全音色を再現しない。','Compare the entry patterns. Actual spectral music also changes component amplitudes and instrumentation. These examples demonstrate frequencies and timing, not a complete instrumental timbre.'), compare(0,1)],
      ]),
    ],
    microtonalharmony: [
      stage(t('同一个和弦，音高可以调得更细','同じ和音をもっと細かく調律する','Tune a chord more precisely'), [
        [t('先定一个音：220 Hz','基準の 1 音：220 Hz','Start with a reference: 220 Hz'), t('先听 220 Hz。Hz 是每秒振动次数，是音高的数值位置。接下来用它当基准：像尺子的零点一样，先固定一个音，再决定另外两个音在哪里。','220 Hz を聴こう。Hz は 1 秒の振動回数で音高の位置。この音を基準にする。物差しの出発点のように、まず 1 音を固定して残りの位置を決める。','Hear 220 Hz. Hz measures vibrations per second and gives a numerical pitch position. Fix this note as a reference before deciding where the other notes belong.'), frequencies(220)],
        [t('再加一音：220 × 5/4 = 275','1 音追加：220 × 5/4 = 275','Add a tone: 220 × 5/4 = 275'), t('5/4 就是 1.25 倍。把基准 220 乘 1.25，得到 275 Hz，听这两个音。这里的比例是“新音频率÷基准频率”，不是钢琴键数。','5/4 は 1.25 倍。基準の 220 に掛けると 275 Hz。この 2 音を聴こう。比は新しい周波数÷基準周波数で、鍵の数ではない。','5/4 means 1.25 times. Multiply reference 220 by 1.25 to get 275 Hz, then hear the pair. A ratio compares frequencies, not piano-key counts.'), frequencies(220,275)],
        [t('三音：220、275、330 Hz','3 音：220、275、330 Hz','Three tones: 220, 275, 330 Hz'), t('第三个音用 3/2，也就是 1.5 倍：220×1.5=330。现在三个音一起响。比例 1:5/4:3/2 是这个纯律和弦的配方；纯律用频率比例安排音程。','3 音目は 3/2＝1.5 倍、220×1.5=330。3 音を同時に聴く。比 1:5/4:3/2 がこの純正律和音の配合。純正律は周波数比で音程を作る。','The third tone uses 3/2, or 1.5 times: 220×1.5=330. Hear all three. Ratios 1:5/4:3/2 specify this just-intonation chord; just intonation arranges intervals by frequency ratios.'), just],
        [t('十二平均律：220、277.18、329.63','12 平均律：220、277.18、329.63','12-EDO: 220, 277.18, 329.63'), t('钢琴常用十二平均律，把一个八度等分成 12 步。同一基准上，对应和弦约为 220、277.18、329.63 Hz。它和刚才的 275、330 略有差别；微分音和声会利用这种比半音更细的差异。','鍵盤で普通の 12 平均律は 1 オクターヴを 12 等分。同じ基準の対応する和音は約 220、277.18、329.63 Hz。先ほどの 275、330 と少し違う。微分音和声は半音より細かな違いも使う。','Common piano tuning divides an octave into 12 equal steps, or 12-EDO. At the same reference, this chord is about 220, 277.18 and 329.63 Hz. Microtonal harmony can use such differences smaller than a semitone.'), tempered],
        [t('比較：同一基准，两种调法','比較：同じ基準で 2 つの調律','Compare two tunings at one reference'), t('先听纯律，再听十二平均律。差别很细，听不出来也能看数值核对。本关只算“基准乘比例”，不评哪种更好听；分支再教等分、误差和共同音。','純正律、次に 12 平均律を比べよう。差は細かく、聴き取れなくても数値で確かめられる。この関は基準×比を計算し、好みは採点しない。等分・誤差・共通音は分岐で学ぶ。','Compare just intonation with 12-EDO. The difference is small; numbers can verify it even if you cannot hear it. This level calculates reference × ratio without grading preferences. Branches teach equal divisions, errors and common tones.'), compare(2,3)],
      ]),
      stage(t('分支 1：换高度，比例不变','分岐 1：高さを変えて比を保つ','Branch 1: change height, retain ratios'), [
        [t('原组：220、275、330 Hz','元の組：220、275、330 Hz','Original: 220, 275, 330 Hz'), t('先听原组。相对 220 的比例为 1、5/4、3/2。要移动这个和弦，先决定新的基准，再把同一套比例乘上去。','元の組を聴こう。220 に対する比は 1、5/4、3/2。和音を動かすなら新しい基準を決め、同じ比を掛ける。','Hear the original, with ratios 1, 5/4 and 3/2 relative to 220. To move the chord, choose a new reference and multiply by the same ratios.'), just],
        [t('全部 ×2：440、550、660 Hz','全部 ×2：440、550、660 Hz','All ×2: 440, 550, 660 Hz'), t('把基准和每个频率都乘 2，听高一个八度的 440、550、660。550÷440 仍是 5/4，660÷440 仍是 3/2，所以相对关系没变。','基準も各周波数も 2 倍にし、1 オクターヴ高い 440、550、660 を聴く。550÷440 は 5/4、660÷440 は 3/2 のままで相対関係は同じ。','Double the reference and every frequency to hear 440, 550 and 660, an octave higher. 550÷440 is still 5/4 and 660÷440 is still 3/2; relative relationships stay.'), frequencies(440,550,660)],
        [t('和弦上方两音：330/275 = 6/5','上の 2 音：330/275 = 6/5','Upper pair: 330/275 = 6/5'), t('只听原组上方的 275 和 330。它们之间的比例用 330÷275=6/5。求两个音之间的距离就让这两个频率相除，不把它们对基准的比例相加。','元の上 2 音、275 と 330 だけ聴こう。比は 330÷275=6/5。2 音間はその周波数を割り、基準への比を足さない。','Hear only the upper pair, 275 and 330. Their ratio is 330÷275=6/5. Divide their frequencies rather than adding their ratios to the reference.'), frequencies(275,330)],
      ]),
      stage(t('分支 2：把八度分成更多小步','分岐 2：オクターヴを細かく等分','Branch 2: divide the octave into finer steps'), [
        [t('19 等分：每步约 63.16 音分','19 等分：1 段は約 63.16 セント','19 equal steps: about 63.16 cents each'), t('一个八度是 1200 音分。19 等分律（19 EDO）把它切成 19 个一样大的步，每步 1200÷19≈63.16 音分。先听 220 和高一步的音；这一步小于钢琴的 100 音分半音。','1 オクターヴは 1200 セント。19 EDO は 19 等分で 1 段 1200÷19≈63.16 セント。220 と 1 段上を聴こう。鍵盤の半音 100 セントより細かい。','An octave is 1200 cents. 19-EDO divides it into 19 equal steps, each about 63.16 cents. Hear 220 and one step above it: smaller than a 100-cent piano semitone.'), frequencies(220,220*2**(1/19))],
        [t('目标 5/4：约 386.31 音分','目標 5/4：約 386.31 セント','Target 5/4: about 386.31 cents'), t('想在这些小步里找接近 5/4 的位置。5/4 是 386.31 音分，386.31÷63.16≈6.12，所以最近的整数位置是第 6 步。先听目标 220、275 Hz。','この段で 5/4 に近い位置を探す。5/4 は 386.31 セント、386.31÷63.16≈6.12 なので最近の整数は第 6 段。まず目標の 220、275 Hz。','Locate a step near 5/4. Its 386.31 cents divided by 63.16 is about 6.12, so the nearest whole step is step 6. First hear target 220 and 275 Hz.'), frequencies(220,275)],
        [t('第 6 步：378.95；误差 −7.37','第 6 段：378.95；誤差 −7.37','Step 6: 378.95; error −7.37'), t('听 19 等分的第 6 步。它约 378.95 音分；近似−目标≈−7.37，负号表示略低。精确公式 k=round(19×log₂(5/4))=6；log₂ 是把比例换成八度大小，工具会代算。','19 等分の第 6 段を聴こう。約 378.95 セント、近似−目標≈−7.37 で少し低い。厳密式 k=round(19×log₂(5/4))=6。log₂ は比をオクターヴの大きさへ換算し、工具でも計算できる。','Hear 19-EDO step 6 at about 378.95 cents, error about −7.37: slightly low. Precisely, k=round(19×log₂(5/4))=6. log₂ expresses a ratio in octaves; the tool can calculate it.'), frequencies(220,220*2**(6/19))],
        [t('比較目标与近似','目標と近似を比較','Compare target and approximation'), t('比较 5/4 和第 6 步。记三个数：选了几步、近似有多大、比目标偏高还是偏低。误差用未舍入的值算，不用听力猜正负号。','5/4 と第 6 段を比べよう。選ぶ段数、近似の大きさ、目標より高いか低いかを記録。誤差は丸め前の値で計算し、耳だけで符号を推測しない。','Compare 5/4 with step 6. Record the step count, approximated size and whether it is above or below the target. Calculate errors before rounding rather than guessing their sign by ear.'), compare(1,2)],
      ]),
      stage(t('分支 3：让一个音真的留在原处','分岐 3：1 音を本当に同じ位置へ保つ','Branch 3: keep one tone at its actual frequency'), [
        [t('旧基准 220：共同音 275 Hz','旧基準 220：共通音 275 Hz','Old reference 220: common tone 275 Hz'), t('第一组里 220×5/4=275 Hz。先听并记住中间的 275；我们想换到另一个和弦，但让这个音留在原来的实际高度。','最初は 220×5/4=275 Hz。真ん中の 275 を覚えよう。別の和音へ変えてもこの音の実際の高さを保ちたい。','In the first chord, 220×5/4=275 Hz. Notice the middle tone: we want to change chords while retaining its actual pitch.'), just],
        [t('新基准 200：275/200 = 11/8','新基準 200：275/200 = 11/8','New reference 200: 275/200 = 11/8'), t('基准换成 200，听新组 200、275、300。中间仍是 275，但相对新基准的比例要写 275÷200=11/8。基准变了，比例可以改变，实际音高才保住了。','基準を 200 にし 200、275、300 を聴く。中は 275 のままだが新基準への比は 275÷200=11/8。基準が変われば比を変えて実音高を保つ。','At reference 200, hear 200, 275 and 300. The middle tone stays at 275, but its new ratio is 275÷200=11/8. Changing the ratio can preserve the actual pitch when the reference changes.'), frequencies(200,275,300)],
        [t('若仍用 5/4：变成 250 Hz','5/4 のままなら 250 Hz','Reusing 5/4 gives 250 Hz'), t('如果照抄 5/4，200×5/4=250，中间音会往下跑。现在听 200、250、300，和上一组不同。所以“写了同样比例”不等于“留下同一个音”。','5/4 をそのまま使うと 200×5/4=250 で中の音が下がる。200、250、300 を聴こう。同じ比を書くことと同じ音を保つことは別。','Reusing 5/4 gives 200×5/4=250, moving the middle tone down. Hear 200, 250 and 300. The same ratio does not guarantee the same retained tone.'), frequencies(200,250,300)],
        [t('比较：保留 275，或改成 250','比較：275 を保つか 250 へ変えるか','Compare: retain 275 or change to 250'), t('最后比较两个新和弦。检查共同音时直接比实际 Hz；同音名、同一个比例，都可能隐藏调音变化。这里要保留的是 275 Hz。','新しい 2 和音を比べ、共通音は実際の Hz で確認する。同じ音名や比でも調律の変化は隠れうる。ここで保つのは 275 Hz。','Compare the new chords. Check common tones through actual Hz; matching note names or ratios can conceal retuning. The tone to retain here is 275 Hz.'), compare(1,2)],
      ]),
      stage(t('分支 4：写出别人也能重现的方案','分岐 4：他の人も再現できる案を書く','Branch 4: make a reproducible design'), [
        [t('方案 A：220 Hz，纯律','案 A：220 Hz、純正律','Design A: 220 Hz, just intonation'), t('先听方案 A：基准 220，比例 1、5/4、3/2，实际频率 220、275、330 Hz，同时进入。写清这四件事，别人就知道该放什么音。','案 A を聴こう。基準 220、比 1、5/4、3/2、実周波数 220、275、330 Hz、同時に入る。この 4 点を書けば再現できる。','Hear design A: reference 220, ratios 1, 5/4, 3/2, frequencies 220, 275, 330 Hz, simultaneous entry. Recording these four details makes playback reproducible.'), just],
        [t('方案 B：220 Hz，19 等分','案 B：220 Hz、19 等分','Design B: 220 Hz, 19-EDO'), t('方案 B 保持同样基准和进入时间，只改成 19 等分的最近步数：0、6、11。把步数、实际 Hz 和误差一起记录，避免只写一个含糊的和弦名。','案 B は基準と入りを保ち、19 等分の最近段 0、6、11 へ変える。段数・実 Hz・誤差を書き、曖昧な和音名だけにしない。','Keep the reference and entry times, changing only the tuning to nearest 19-EDO steps 0, 6 and 11. Record steps, actual Hz and errors rather than only a chord name.'), edo19],
        [t('公平比较：基准与时间相同','同じ基準と時間で比較','Compare at the same reference and timing'), t('比较两组。固定基准、音区和时间，才容易知道差异来自调音。喜欢哪种声音由你决定；做题核对计算和规则，不把喜好当对错。','2 つを比べよう。基準・音域・時間を固定すると調律の違いを追いやすい。好みは自分で決め、問題は計算と規則を確認する。','Compare the schemes at the same reference, register and timing to isolate tuning differences. Your preference is yours; questions assess calculations and rules, not taste.'), compare(0,1)],
      ]),
    ],
  };
}
