// Side-B 的错误类型：每类对应一个技能标签、一句说明，以及推荐回去看的地方（A 面关卡 / Side-B 关卡 / 工具）。
// 结果页按这里把错误归类，并给出针对性练习。
const t = (zh, ja, en) => ({ zh, ja, en });

/** 七个技能标签 */
export const SKILLS = ['identify', 'spell', 'calc', 'function', 'voiceLeading', 'hearing', 'apply'];
export const SKILL_NAMES = {
  identify: t('识别', '識別', 'Identification'),
  spell: t('拼写', '綴り', 'Spelling'),
  calc: t('计算', '計算', 'Calculation'),
  function: t('功能分析', '機能分析', 'Functional analysis'),
  voiceLeading: t('声部进行', '声部進行', 'Voice leading'),
  hearing: t('听觉与节奏', '聴覚とリズム', 'Hearing & rhythm'),
  apply: t('应用', '応用', 'Application'),
};

/**
 * 错误类型：skill 技能；label 名称；advice 怎么改；go 推荐去处（a: A 面关卡键，b: Side-B 关卡编号，tool: { feature, q }）
 */
export const ERRORS = {
  enharmonic: { skill: 'spell', label: t('同音异名拼错', '異名同音の綴り違い', 'Enharmonic misspelling'), advice: t('先数字母（度数），再数半音：字母决定拼法，半音只决定升降。', 'まず文字（度数）を数え、次に半音を数える。文字が綴りを決め、半音は臨時記号だけを決める。', 'Count letters (the interval number) first, then half steps: letters fix the spelling, half steps only the accidental.'), go: { a: 'intervalqual' } },
  'wrong-note': { skill: 'spell', label: t('音写错了', '音が違う', 'Wrong note'), advice: t('对照调号和临时记号，一个音一个音核对。', '調号と臨時記号を見ながら 1 音ずつ確認。', 'Check each note against the key signature and accidentals.'), go: { a: 'major' } },
  octave: { skill: 'spell', label: t('八度写错', 'オクターヴの違い', 'Wrong octave'), advice: t('中央 C = C4；每个八度从 C 开始数。', '中央の C = C4。各オクターヴは C から数える。', 'Middle C is C4; each octave number starts on C.'), go: { a: 'staff' } },
  'wrong-chord': { skill: 'identify', label: t('和弦不对', '和音が違う', 'Wrong chord'), advice: t('先在调里找到这个罗马数字的根音，再按性质叠三度。', '調の中でローマ数字の根音を見つけ、性質どおりに 3 度を重ねる。', 'Find the numeral’s root in the key, then stack thirds of the right quality.'), go: { a: 'roman' } },
  'wrong-inversion': { skill: 'identify', label: t('转位不对', '転回形が違う', 'Wrong inversion'), advice: t('数字只看低音：6 是三音在低音，6/4 是五音，6/5、4/3、4/2 是七和弦的三种转位。', '数字はバスだけを見る：6 は 3 音、6/4 は 5 音、6/5・4/3・4/2 は七の和音の転回形。', 'Figures describe the bass: 6 = third in the bass, 6/4 = fifth; 6/5, 4/3, 4/2 are the seventh-chord inversions.'), go: { a: 'figured' } },
  'chord-count': { skill: 'apply', label: t('和弦数量不对', '和音の数が違う', 'Wrong number of chords'), advice: t('每个和弦要上下两行同时开始、各写两个音。', '各和音は上下 2 段で同時に始め、それぞれ 2 音書く。', 'Each chord needs two notes on each staff, starting together.'), go: { tool: { feature: 'staff', q: 'grand' } } },
  'parallel-fifths': { skill: 'voiceLeading', label: t('平行五度', '平行 5 度', 'Parallel fifths'), advice: t('两个声部接连构成纯五度并且都在移动：让其中一个声部反向或保持。', '2 声部が続けて完全 5 度を作り両方動いている：どちらかを反行させるか保つ。', 'Two voices move in perfect fifths: move one in contrary motion or keep it still.'), go: { a: 'voicing', b: 'B2-4' } },
  'parallel-octaves': { skill: 'voiceLeading', label: t('平行八度', '平行 8 度', 'Parallel octaves'), advice: t('两个声部接连八度（或同度）：通常是重复了导音或七音，换一个重复音。', '2 声部が続けて 8 度：多くは導音や第 7 音の重複。重複する音を変える。', 'Consecutive octaves usually come from doubling a tendency tone: double another note.'), go: { a: 'voicing', b: 'B2-4' } },
  'direct-fifths': { skill: 'voiceLeading', label: t('直接五八度', '並達 5・8 度', 'Direct fifths / octaves'), advice: t('外声部同向进入完全音程时，女高音要级进。', '外声が同方向で完全音程に入るとき、ソプラノは順次進行に。', 'When the outer voices approach a perfect interval in similar motion, the soprano should move by step.'), go: { b: 'B2-4' } },
  'unresolved-leading-tone': { skill: 'voiceLeading', label: t('导音没有解决', '導音が未解決', 'Unresolved leading tone'), advice: t('外声部的导音要上行到主音；内声部可以下行到属音。', '外声の導音は主音へ上行。内声なら属音へ下がってもよい。', 'In an outer voice the leading tone rises to the tonic; in an inner voice it may fall to the dominant.'), go: { a: 'voicing', b: 'B2-4' } },
  'unresolved-seventh': { skill: 'voiceLeading', label: t('七音没有下行解决', '第 7 音が下行解決していない', 'Chordal seventh not resolved down'), advice: t('和弦七音级进下行一步解决。', '和音の第 7 音は 1 歩下行して解決。', 'A chordal seventh resolves down by step.'), go: { a: 'sevenths', b: 'B2-4' } },
  'voice-crossing': { skill: 'voiceLeading', label: t('声部交叉 / 超越', '声部の交差・超越', 'Voice crossing / overlap'), advice: t('每个声部都要待在相邻声部之间，也不要越过相邻声部上一个音的位置。', '各声部は隣の声部の間にとどめ、隣の直前の音も越えない。', 'Keep each voice between its neighbours and don’t pass a neighbour’s previous note.'), go: { b: 'B2-4' } },
  spacing: { skill: 'voiceLeading', label: t('间距太大', '間隔が広すぎる', 'Spacing too wide'), advice: t('女高–女中、女中–男高不超过八度；男高–男低可以到十二度。', 'S–A・A–T は 8 度以内、T–B は 12 度まで。', 'S–A and A–T within an octave; T–B up to a twelfth.'), go: { b: 'B2-4' } },
  range: { skill: 'voiceLeading', label: t('超出音域', '音域外', 'Out of range'), advice: t('核对四个声部的常用音域。', '4 声部の音域を確認。', 'Check each voice’s usual range.'), go: { b: 'B2-4' } },
  'bad-doubling': { skill: 'voiceLeading', label: t('重复了不该重复的音', '重複してはいけない音を重複', 'Faulty doubling'), advice: t('导音和和弦七音都不重复。', '導音と第 7 音は重複しない。', 'Never double the leading tone or the chordal seventh.'), go: { b: 'B2-4' } },
  'wrong-function': { skill: 'function', label: t('功能 / 罗马数字判断错', '機能・ローマ数字の誤り', 'Functional label wrong'), advice: t('先定调，再看低音与和弦性质，最后看它在乐句里的位置。', 'まず調、次にバスと和音の性質、最後にフレーズ内の位置。', 'Fix the key, then the bass and quality, then the chord’s place in the phrase.'), go: { a: 'functions' } },
  calc: { skill: 'calc', label: t('计算错误', '計算の誤り', 'Calculation error'), advice: t('把推导一步步写出来，每步检查单位（字母、半音、拍、音分）。', '推論を 1 歩ずつ書き、単位（文字・半音・拍・セント）を確かめる。', 'Write the derivation step by step and check the unit at each step (letters, half steps, beats, cents).'), go: {} },
  concept: { skill: 'identify', label: t('概念混淆', '概念の混同', 'Concept mix-up'), advice: t('回到讲解页对照定义和反例。', '講義ページで定義と反例を見直す。', 'Revisit the lecture pages: compare the definition with the counter-examples.'), go: {} },
  'misplaced-onset': { skill: 'hearing', label: t('起音位置不对', '打点の位置が違う', 'Attack in the wrong place'), advice: t('先在点格上数出拍点和细分，再标起音。', 'まずドット・グリッドで拍と細分を数え、打点を記入。', 'Count beats and subdivisions on a dot grid first, then mark attacks.'), go: { a: 'rhythm', tool: { feature: 'rhythm', q: '' } } },
  'missing-syncopation': { skill: 'hearing', label: t('没有构成切分', 'シンコペーションになっていない', 'No syncopation'), advice: t('切分：在弱位置起音，并延长过下一个拍点（或在拍点上休止）。', '弱い位置で打ち、次の拍頭をまたいで伸ばす（または拍頭で休む）。', 'Syncopation: attack on a weak position and hold through the next beat (or rest on the beat).'), go: { a: 'swing', b: 'B4-1' } },
  'wrong-meter': { skill: 'hearing', label: t('拍号设置不对', '拍子の設定が違う', 'Wrong meter setting'), advice: t('先确认拍号与每格的时值。', '拍子とマスの音価を確認。', 'Check the time signature and the cell value.'), go: { a: 'meter' } },
  'wrong-length': { skill: 'hearing', label: t('小节长度不对', '小節の長さが違う', 'Wrong bar length'), advice: t('格子数 = 每小节拍数 × 每拍格数。', 'マス数 = 1 小節の拍数 × 1 拍のマス数。', 'Cells = beats per bar × cells per beat.'), go: { a: 'meter' } },
  'wrong-ratio': { skill: 'hearing', label: t('复节奏比例不对', 'ポリリズムの比が違う', 'Wrong polyrhythm ratio'), advice: t('3:2 是同一段时间里一条打 3 下、另一条打 2 下。', '3:2 は同じ時間に片方 3 打、もう片方 2 打。', '3:2 means three attacks against two in the same span.'), go: { b: 'B4-10', tool: { feature: 'rhythm', q: '@sub:poly' } } },
  'tempo-calculation': { skill: 'calc', label: t('速度换算错', 'テンポ換算の誤り', 'Tempo calculation error'), advice: t('新速度 = 旧速度 × 新小节里枢纽时值的个数 ÷ 旧小节里的个数。', '新テンポ = 旧テンポ × 新しい小節の枢軸音価の数 ÷ 旧い小節の数。', 'New tempo = old tempo × pivot values per new unit ÷ pivot values per old unit.'), go: { b: 'B4-10', tool: { feature: 'rhythm', q: '@sub:poly' } } },
  'tool-setting': { skill: 'apply', label: t('工具里的设置不对', 'ツールの設定が違う', 'Tool not set as required'), advice: t('按任务条上的要求设置工具，再提交。', 'タスクバーの指示どおりに設定してから提出。', 'Set the tool as the task bar asks, then submit.'), go: {} },
  'not-auditioned': { skill: 'apply', label: t('没有试听', '試聴していない', 'Not auditioned'), advice: t('提交前先在工具里播放一遍，用耳朵确认。', '提出前にツールで再生して耳で確かめる。', 'Play it in the tool before submitting and check by ear.'), go: {} },
  'normal-order': { skill: 'calc', label: t('标准顺序算错', '正規順序の誤り', 'Normal order wrong'), advice: t('排成升序后找最紧凑的旋转（首尾距离最小）。', '昇順に並べ、最も詰まった回転（端から端が最小）を探す。', 'Sort ascending and pick the most compact rotation (smallest span).'), go: { a: 'setclass' } },
  'prime-form': { skill: 'calc', label: t('原型算错', 'プライム・フォームの誤り', 'Prime form wrong'), advice: t('标准顺序和它的倒影都移到 0 开头，取更靠左紧凑的那个。', '正規順序とその反行を 0 始まりに移し、より左に詰まった方を取る。', 'Transpose the normal order and its inversion to start on 0 and keep the one packed more to the left.'), go: { a: 'setclass' } },
  'interval-vector': { skill: 'calc', label: t('音程级向量算错', '音程クラス・ベクトルの誤り', 'Interval vector wrong'), advice: t('把每一对音的音程级都数一遍，按 1–6 分别计数。', 'すべての音の対の音程クラスを数え、1〜6 ごとに集計。', 'Count the interval class of every pair, tallying 1 to 6.'), go: { a: 'setclass' } },
  'tap-missed': { skill: 'hearing', label: t('漏打', '打ち漏れ', 'Missed attacks'), advice: t('先放慢速度，跟着节拍器数拍，再一边数一边打。', 'テンポを落とし、メトロノームで数えながら打つ。', 'Slow down, count along with the click, then tap while counting.'), go: { b: 'B4-10' } },
  'tap-extra': { skill: 'hearing', label: t('多打', '余分な打点', 'Extra taps'), advice: t('只在起音的位置打，延长的音不要再打。', '打点の位置だけ打ち、伸ばす音は打たない。', 'Tap only on attacks — not on sustained notes.'), go: { b: 'B4-10' } },
  'incomplete-chord': { skill: 'spell', label: t('和弦音不完整', '構成音が足りない', 'Incomplete chord'), advice: t('先列出这个和弦该有的音（根、三、七，以及标记写出的延伸音），再逐个打勾。', 'まずこの和音に必要な音（根音・3 度・7 度・記号にある拡張音）を書き出し、1 つずつ確認。', 'List the tones the chord needs (root, 3rd, 7th and any named extension) and tick them off.'), go: { a: 'sevenths', b: 'B2-1' } },
  'rough-voice-leading': { skill: 'voiceLeading', label: t('声部移动太多', '声部の動きが大きい', 'Too much voice motion'), advice: t('声部要"懒"：共同音先保持，其次走半音或全音，跳进留给真正需要的地方。', '声部は「怠け者」に：共通音を保ち、次に半音・全音、跳躍は必要な所だけ。', 'Keep voices lazy: hold common tones, then move by half or whole step; save leaps for when you need them.'), go: { a: 'jazzvoicing', b: 'B4-5' } },
  'missing-guide-tone': { skill: 'voiceLeading', label: t('少了三音或七音', '第 3・7 音が足りない', 'Missing 3rd or 7th'), advice: t('三音和七音决定和弦性质，五音可以省，这两个不能省。', '第 3 音と第 7 音が和音の種類を決める。5 度は省けてもこの 2 つは省かない。', 'The 3rd and 7th define the quality; drop the 5th, never these.'), go: { a: 'jazzvoicing', b: 'B4-5' } },
  'root-in-voicing': { skill: 'apply', label: t('上方声部弹了根音', '上声で根音を弾いた', 'Root in the voicing'), advice: t('有低音时根音交给低音，上方声部留给三音、七音和延伸音。', 'ベースがいる時は根音を任せ、上声は 3 度・7 度・拡張音に。', 'With a bassist, leave the root to them; give the hands the 3rd, 7th and extensions.'), go: { a: 'jazzvoicing', b: 'B4-5' } },
  'avoid-note': { skill: 'apply', label: t('用了 avoid note', 'アヴォイド・ノート', 'Avoid note'), advice: t('大三和弦上的纯 11 音在三音上方半音，和三音冲突；改成 ♯11 或去掉。', '長三和音上の完全 11 度は第 3 音の半音上でぶつかる。♯11 にするか省く。', 'A natural 11th over a major-third chord sits a half step above the 3rd; raise it to ♯11 or drop it.'), go: { a: 'jazzvoicing', b: 'B4-5' } },
  'voicing-register': { skill: 'apply', label: t('延伸音放得太低', '拡張音の位置が低い', 'Extension voiced too low'), advice: t('13 音放在七音上方，否则听起来就是 6 音。', '13th は第 7 音より上に。下だと 6th に聞こえる。', 'Put the 13th above the 7th, or it sounds like a 6th.'), go: { a: 'jazzvoicing', b: 'B4-5' } },
  'missing-tie': { skill: 'hearing', label: t('没有跨拍连音', '拍をまたぐタイがない', 'No tie across the beat'), advice: t('把一个音用连音线连过下一个拍点：第二个音不再重新奏出。', '1 つの音をタイで次の拍の頭までつなぐ。2 つ目は弾き直さない。', 'Tie a note over the next beat; the tied-to note is not re-struck.'), go: { a: 'rhythm', b: 'B4-1' } },
  'illegal-duration': { skill: 'hearing', label: t('时值写法不合法', '音価の書き方の誤り', 'Illegal duration'), advice: t('连音线只连同一个音高的音，休止符不用连音线。', 'タイは同じ高さの音どうしだけ。休符にタイは付けない。', 'Ties join notes of the same pitch only; rests are never tied.'), go: { a: 'rhythm' } },
  'lost-pulse': { skill: 'hearing', label: t('拍子听不出来', '拍子が聞こえない', 'Meter lost'), advice: t('切分要有拍子当参照：每小节至少留一个落在拍点上的音。', 'シンコペーションには拍の基準が要る。各小節に拍の頭の音を 1 つは残す。', 'Syncopation needs a pulse to push against: keep at least one attack on a beat in each bar.'), go: { a: 'meter', b: 'B1-2' } },
  'incomplete-work': { skill: 'apply', label: t('还没写完', 'まだ途中', 'Not finished'), advice: t('先把要求的部分都写出来，评分会按写了的部分算。', 'まず求められた部分をすべて書こう。採点は書いた分で数える。', 'Write every required part first; scoring counts what is there.'), go: {} },
  polymeter: { skill: 'identify', label: t('复节奏 / 复拍子分不清', 'ポリリズムとポリメーターの混同', 'Polyrhythm vs polymeter'), advice: t('问自己：是两个拍号同时存在（复拍子），还是同一个拍子里几种节奏交错（复节奏）？', '2 つの拍子が同時にある（ポリメーター）か、1 つの拍子の中でリズムが交差する（ポリリズム）か。', 'Ask: are two meters running at once (polymeter), or are rhythms crossing inside one meter (polyrhythm)?'), go: { b: 'B4-10', tool: { feature: 'rhythm', q: '@sub:poly' } } },
  'meter-grouping': { skill: 'hearing', label: t('拍组听错', '拍のまとまりの聞き違い', 'Wrong beat grouping'), advice: t('跟着重音数八分音符：3+2 是一长一短，2+3 是一短一长。', 'アクセントに合わせて 8 分音符を数える：3+2 は長・短、2+3 は短・長。', 'Count eighths from accent to accent: 3+2 is long–short, 2+3 short–long.'), go: { a: 'meter2', b: 'B4-10' } },
  'mm-type': { skill: 'identify', label: t('节拍调制的类型认错', 'メトリック・モジュレーションの種類の誤り', 'Wrong kind of metric modulation'), advice: t('看"等号"两边哪个时值不变：细分不变还是拍子不变。', '「=」の両側で変わらない音価を見る：細分か拍か。', 'See which value stays fixed across the “=”: the subdivision or the beat.'), go: { b: 'B4-10', tool: { feature: 'rhythm', q: '@sub:poly' } } },
  'interval-size': { skill: 'calc', label: t('音程度数数错', '音程の度数の数え違い', 'Interval size miscounted'), advice: t('只看字母、两端都算：C 到 E 是 C、D、E 三个字母，所以是三度；转位的两个度数加起来是 9。', '文字だけを見て両端も数える：C から E は C・D・E の 3 つで 3 度。転回の度数の和は 9。', 'Count letters only, both ends included: C to E is C, D, E — a third; inverted sizes add to 9.'), go: { a: 'intervals', b: 'B1-3' } },
  'interval-quality': { skill: 'calc', label: t('音程性质判断错', '音程の性質の判断違い', 'Interval quality wrong'), advice: t('先定度数，再数半音：一四五八度分纯 / 增 / 减，二三六七度分大 / 小 / 增 / 减。', 'まず度数、次に半音を数える：1・4・5・8 度は完全・増・減、2・3・6・7 度は長・短・増・減。', 'Size first, then half steps: unisons, fourths, fifths and octaves are perfect/augmented/diminished; seconds, thirds, sixths and sevenths major/minor/augmented/diminished.'), go: { a: 'intervalqual', b: 'B1-3' } },
  'scale-pattern': { skill: 'spell', label: t('音阶 / 调号写错', '音階・調号の誤り', 'Scale or key signature wrong'), advice: t('对照全音半音的排列（大调 W-W-H-W-W-W-H），按字母一个个写；升号调看最后一个升号，降号调看倒数第二个降号。', '全音半音の並び（長調 W-W-H-W-W-W-H）を見ながら文字ごとに書く。♯ 系は最後の ♯、♭ 系は最後から 2 番目の ♭ を見る。', 'Follow the step pattern (major W-W-H-W-W-W-H) letter by letter; for sharp keys look at the last sharp, for flat keys the second-to-last flat.'), go: { a: 'major', b: 'B1-4' } },
  'mode-character': { skill: 'identify', label: t('调式特征认错', '旋法の特徴の取り違え', 'Mode character confused'), advice: t('先听三音是大是小（亮 / 暗），再找特征音：Lydian 升四、Mixolydian 降七、Dorian 升六、Phrygian 降二、Locrian 降二降五。', 'まず 3 度の長短（明・暗）、次に特性音：リディア ♯4、ミクソリディア ♭7、ドリア ♯6、フリギア ♭2、ロクリア ♭2 ♭5。', 'Hear whether the third is major or minor (bright/dark), then find the tell-tale note: Lydian ♯4, Mixolydian ♭7, Dorian ♯6, Phrygian ♭2, Locrian ♭2 ♭5.'), go: { a: 'modes', b: 'B1-5' } },
  'texture-type': { skill: 'identify', label: t('织体判断错', 'テクスチュアの判断違い', 'Texture misidentified'), advice: t('数一数有几条线，再看它们的关系：同一旋律的变体、节奏一致的和声、还是节奏各异的独立旋律。', '線が何本あるか数え、関係を見る：同じ旋律の変奏か、同じリズムの和声か、リズムの違う独立した旋律か。', 'Count the lines, then look at how they relate: variants of one melody, chords in one rhythm, or independent lines with their own rhythms.'), go: { a: 'texture', b: 'B1-7' } },
  'unknown-lab': { skill: 'apply', label: t('实操任务不存在', '実習が見つからない', 'Unknown lab'), advice: t('回到课程重新打开这个任务。', 'コースに戻ってもう一度開く。', 'Go back to the course and reopen the task.'), go: {} },
  'form-type': { skill: 'identify', label: t('乐句 / 曲式判断错', 'フレーズ・形式の判断違い', 'Phrase or form misidentified'), advice: t('先找终止，比较两句终止的强弱：前弱后强是乐段，相同是重复乐句；曲式看段落是否反复、开头的材料是否回来。', 'まず終止を見つけ、2 つの終止の強弱を比べる：前が弱く後が強ければ楽節、同じなら反復フレーズ。形式は部分の反復と冒頭の回帰を見る。', 'Find the cadences and compare their strength: weaker then stronger is a period, identical is a repeated phrase; for forms, check which sections repeat and whether the opening returns.'), go: { a: 'form', b: 'B2-7' } },
  'key-relation': { skill: 'identify', label: t('调关系判断错', '調の関係の判断違い', 'Key relationship wrong'), advice: t('在五度圈上找左右邻居（IV、V），再加上它们和原调的关系小调（ii、iii、vi）以及同主音小调（i）。', '五度圏で左右の隣（IV・V）を見つけ、それらと元の調の平行短調（ii・iii・vi）、同主短調（i）を加える。', 'Find the neighbours on the circle (IV, V), then add their and the home key’s relative minors (ii, iii, vi) and the parallel minor (i).'), go: { a: 'circle', b: 'B2-10' } },
  'nr-transform': { skill: 'calc', label: t('新黎曼变换算错', 'ネオ・リーマン変換の計算違い', 'Neo-Riemannian transformation wrong'), advice: t('从大三和弦出发：P 动三音、R 动五音（上行全音）、L 动根音（下行半音）；小三和弦方向相反。', '長三和音から：P は第 3 音、R は第 5 音（全音上）、L は根音（半音下）を動かす。短三和音は逆向き。', 'From a major triad: P moves the third, R the fifth (up a whole step), L the root (down a half step); from minor, the reverse.'), go: { a: 'neoriemann', b: 'B2-11' } },
  transposition: { skill: 'calc', label: t('移调算错', '移調の計算違い', 'Transposition wrong'), advice: t('先确定乐器的调（写 C 响什么），读谱往那个方向移，写谱往相反方向移；别忘了次中音、上低音萨克斯多出的八度。', 'まず楽器の調（C を吹くと何が鳴るか）を確かめ、読むときはその方向、書くときは反対方向へ。テナー・バリトン・サックスの余分なオクターヴを忘れずに。', 'Find the instrument’s key (what a written C sounds), move that way when reading and the opposite way when writing; remember the extra octave for tenor and baritone sax.'), go: { a: 'instruments', b: 'B3-1', tool: { feature: 'instruments', q: '' } } },
  fretboard: { skill: 'calc', label: t('指板位置算错', '指板の位置の誤り', 'Fretboard position wrong'), advice: t('相邻弦是纯四度（5 品），只有 G–B 是大三度（4 品）；形整体平移几品，根音就升高几个半音。', '隣の弦は完全 4 度（5 フレット）、G–B だけ長 3 度（4 フレット）。フォームを動かしたフレット数だけルートが上がる。', 'Neighbouring strings are a perfect fourth apart (5 frets), except G–B, a major third (4 frets); sliding a shape n frets raises the root n half steps.'), go: { a: 'fretboard', b: 'B3-2', tool: { feature: 'fretboard', q: '' } } },
  'nct-type': { skill: 'identify', label: t('非和弦音认错', '非和声音の取り違え', 'Embellishing tone misidentified'), advice: t('问两个问题：怎么进来（级进 / 跳进 / 保持）、怎么离开（同方向 / 反方向）；再看它在强位置还是弱位置。', '2 つの問い：どう入るか（順次・跳躍・保持）、どう出るか（同じ方向・反対）。それから強い位置か弱い位置か。', 'Ask two questions — how it arrives (step, leap, held) and how it leaves (same or opposite direction) — then check the beat strength.'), go: { a: 'nonchord', b: 'B3-3', tool: { feature: 'nonchord', q: '' } } },
  'cp-frame': { skill: 'apply', label: t('对位的开头 / 终止不对', '対位法の開始・終止の誤り', 'Counterpoint opening or cadence wrong'), advice: t('上方从 do 或 sol、下方从 do 开始；结尾反向级进到 do，倒数第二个音程是大六度或小三度。', '上は do か sol、下は do で始める。終わりは反行の順次進行で do へ、最後から 2 番目は長 6 度か短 3 度。', 'Start above on do or sol, below on do; finish on do by contrary step, with a major sixth or minor third just before.'), go: { a: 'counterpoint', b: 'B3-4', tool: { feature: 'counterpoint', q: '' } } },
  'cp-dissonance': { skill: 'voiceLeading', label: t('不协和处理不对', '不協和の扱いの誤り', 'Dissonance mishandled'), advice: t('第一类全协和；第二类的不协和只能是弱拍经过音；第三类要级进进出（双辅助音、换音除外）。', '第一類はすべて協和、第二類の不協和は弱拍の経過音だけ、第三類は順次で出入り（二重刺繍音・カンビアータは例外）。', 'First species is all consonant; second-species dissonance is only a weak-beat passing tone; third species moves by step in and out (double neighbour and cambiata excepted).'), go: { a: 'species', b: 'B3-4', tool: { feature: 'counterpoint', q: '' } } },
  suspension: { skill: 'voiceLeading', label: t('挂留没有预备或解决', '掛留の予備・解決の誤り', 'Suspension not prepared or resolved'), advice: t('弱拍协和的音用连音线连到强拍（预备），强拍不协和（挂留），再级进下行到协和（解决）；上方 7–6、4–3、9–8，下方 2–3、5–6、4–5。', '弱拍の協和音をタイで強拍へ（予備）、強拍で不協和（掛留）、順次下行で協和へ（解決）。上声 7–6・4–3・9–8、下声 2–3・5–6・4–5。', 'Tie a consonant weak-beat note into the downbeat (preparation), let it clash (suspension), then step down to a consonance (resolution); above 7–6, 4–3, 9–8, below 2–3, 5–6, 4–5.'), go: { a: 'species', b: 'B3-5', tool: { feature: 'counterpoint', q: '' } } },
  'cp-rhythm': { skill: 'apply', label: t('对位的节奏不对', '対位法のリズムの誤り', 'Counterpoint rhythm wrong'), advice: t('第一类每小节一个全音符；第二类两个二分音符（可以先休止半小节）；第四类先休止半小节，之后每个弱拍连到强拍；最后一小节是全音符。', '第一類は 1 小節 1 全音符、第二類は 2 分音符 2 つ（半小節休んでもよい）、第四類は半小節休んでから弱拍を強拍へタイ。最後の小節は全音符。', 'First species: one whole note per bar; second: two halves (a half rest may start); fourth: a half rest, then each weak beat tied into the downbeat; the last bar is a whole note.'), go: { b: 'B3-4', tool: { feature: 'counterpoint', q: '' } } },
  'cp-line': { skill: 'voiceLeading', label: t('旋律线条有毛病', '旋律線の問題', 'Melodic line problem'), advice: t('以级进为主，大跳后反向级进；一个只出现一次、不和定旋律重合的最高点；不交叉不超越；同音反复最多一次。', '順次進行を中心に、大跳躍の後は反対方向へ順次。最高点は 1 回だけで定旋律と重ねない。交差・超越なし、同音反復は 1 回まで。', 'Mostly steps, recover big leaps by contrary step; one climax that doesn’t coincide with the cantus; no crossing or overlap; at most one repeated note.'), go: { b: 'B3-4', tool: { feature: 'counterpoint', q: '' } } },
  'cantus-changed': { skill: 'apply', label: t('改动了定旋律', '定旋律を変えた', 'Cantus firmus changed'), advice: t('低音谱表上的定旋律是题目给的，不要改；对位写在另一行谱上。', 'ヘ音譜表の定旋律は課題なので変えない。対旋律はもう一方の段に。', 'The cantus on the bass staff is given — leave it; write the counterpoint on the other staff.'), go: { b: 'B3-4' } },
  'canon-type': { skill: 'identify', label: t('卡农类型认错', 'カノンの種類の取り違え', 'Canon type misidentified'), advice: t('看答句和导句的关系：同度 / 八度完全一样是轮唱；方向相反是倒影；倒着走是逆行；放慢或加快是比例卡农。', '後続声部と先行声部の関係を見る：同度・オクターヴで同じなら輪唱、逆向きなら反行、後ろからなら逆行、拡大・縮小なら比例カノン。', 'Compare follower and leader: exact at unison/octave is a round; contrary direction an inversion; backwards a retrograde; slower or faster a mensuration canon.'), go: { a: 'canon', b: 'B3-5', tool: { feature: 'counterpoint', q: '@sub:canon' } } },
  'swing-feel': { skill: 'hearing', label: t('摇摆 / 反拍认错', 'スウィング・バックビートの誤り', 'Swing or backbeat misunderstood'), advice: t('摇摆八分写成直八分、弹成前长后短（约 2:1）；反拍是四拍子的 2、4 拍。', 'スウィングの 8 分はストレートで書き前長後短（約 2:1）で弾く。バックビートは 4 拍子の 2・4 拍。', 'Swing eighths are written straight and played long–short (about 2:1); the backbeat is beats 2 and 4.'), go: { a: 'swing', b: 'B4-1', tool: { feature: 'rhythm', q: '' } } },
  'blues-form': { skill: 'function', label: t('布鲁斯形式认错', 'ブルースの形式の誤り', 'Blues form wrong'), advice: t('三句四小节：I I I I ｜ IV IV I I ｜ V IV I I；属七可以有任何功能，靠 IV–I 收束；小调布鲁斯第三句多用 ii–V–i。', '4 小節 × 3 フレーズ：I I I I ｜ IV IV I I ｜ V IV I I。属七はどの機能にもなり、IV–I で閉じる。マイナー・ブルースの第 3 フレーズは ii–V–i が多い。', 'Three 4-bar phrases: I I I I | IV IV I I | V IV I I; dominant sevenths take any function and close with IV–I; minor blues usually uses ii–V–i in phrase three.'), go: { a: 'blues', b: 'B4-2', tool: { feature: 'blues', q: '' } } },
  'chord-scale': { skill: 'apply', label: t('和弦—音阶配错', 'コード・スケールの誤り', 'Chord-scale mismatch'), advice: t('先用罗马数字定功能：I Ionian、ii Dorian、iii Phrygian、IV Lydian、V Mixolydian、vi Aeolian、viiø Locrian；同样是小七和弦，级数不同调式就不同。', 'まずローマ数字で機能を：I イオニアン、ii ドリアン、iii フリジアン、IV リディアン、V ミクソリディアン、vi エオリアン、viiø ロクリアン。同じ短七でも度数が違えば旋法が違う。', 'Fix the function with a Roman numeral first: I Ionian, ii Dorian, iii Phrygian, IV Lydian, V Mixolydian, vi Aeolian, viiø Locrian; minor sevenths on different degrees take different modes.'), go: { a: 'chordscale', b: 'B4-3', tool: { feature: 'cst', q: '' } } },
  'key-center': { skill: 'function', label: t('调性中心判断错', '調性の中心の誤り', 'Key centre misjudged'), advice: t('先找 ii–V（mi7 接根音低五度的 7），它指向的 I 就是这一段的调性中心。', 'まず ii–V（mi7 から根音 5 度下の 7）を探す。それが指す I がその部分の中心。', 'Find the ii–V (a mi7 moving to a 7 a fifth below); the I it points to is the passage’s key centre.'), go: { a: 'keycenter', b: 'B4-4', tool: { feature: 'circle', q: '' } } },
  substitution: { skill: 'calc', label: t('替代和弦算错', '代理和音の計算違い', 'Substitution wrong'), advice: t('三全音替代：根音移三全音、三音和七音互换；应用属七：五度进行里前一个和弦换成同根音属七；混合：iiø7、V7♭9 用 le。', '裏コード：根音を三全音移し 3 度と 7 度を交換。副属七：5 度進行の前の和音を同じ根音の属七に。借用：iiø7・V7♭9 は le を使う。', 'Tritone sub: move the root a tritone, swapping 3rd and 7th; applied dominant: the earlier chord of a fifth pair becomes a dominant on its root; mixture: iiø7 and V7♭9 use le.'), go: { a: 'substitutions', b: 'B4-8', tool: { feature: 'jazzmore', q: '' } } },
  'negative-harmony': { skill: 'calc', label: t('负和声算错', 'ネガティブ・ハーモニーの計算違い', 'Negative harmony wrong'), advice: t('在五度圈上沿主音与属音之间的轴镜像：C 调 C↔G、D↔F、E↔E♭、A↔B♭、B↔A♭、F♯↔D♭。', '五度圏上で主音と属音の間の軸で反転：C 調は C↔G・D↔F・E↔E♭・A↔B♭・B↔A♭・F♯↔D♭。', 'Mirror across the tonic–dominant axis on the circle: in C, C↔G, D↔F, E↔E♭, A↔B♭, B↔A♭, F♯↔D♭.'), go: { a: 'negharmony', b: 'B4-9', tool: { feature: 'circle', q: '' } } },
};

/** 结果页用：把错误次数汇总成按技能分组的推荐 */
export function recommend(errorCounts) {
  return Object.entries(errorCounts)
    .filter(([type]) => ERRORS[type])
    .sort((a, b) => b[1] - a[1])
    .map(([type, count]) => ({ type, count, ...ERRORS[type] }));
}
