// ref:koozin-planing
// Side-B additions: each extension revisits all four A-side branches before deeper tasks.
// ref:rubin-nonfunctional ref:arndt-tonality ref:ircam-spectral ref:ircam-spectrum ref:gann-ji ref:gann-ji-reasons
import { TOPICS, t, cents, stageVisual, generatorOf } from './modern_harmony_course.js?v=20261008-spectrum-side1';
import { MODERN_GENERATORS, pitch } from './modern_harmony_generators.js?v=20261009-audio1';
import {MODERN_MISSIONS,modernSceneTask,modernSceneDiscovery} from './sideb_modern_harmony_scenes.js?v=20261009-audio1';
const step = (label, answer, tol = 1e-9) => ({ kind: 'number', label, answer, tol });
const numericalHint = t('数值题，按给定单位计算；小数保留两位，容差 ±0.02。', '指定単位の数値を計算。小数 2 桁、許容誤差 ±0.02。', 'Calculate in the stated units. Round decimals to two places; tolerance ±0.02.');
export function integratedTask(topic, stage, variant = 0) {
  const r=[160,200,220,240][variant%4], shift=variant+2, root=48+variant;
  let prompt, steps, explain;
  if(topic.id==='nonfunctional') {
    if(stage===1) { prompt=t(`三声部 ${pitch(root)}、${pitch(root+4)}、${pitch(root+7)} 都上移 ${shift} 半音。推导结果相对最低原音的距离与内部距离。`, `3 声部 ${pitch(root)}、${pitch(root+4)}、${pitch(root+7)} を半音 ${shift} つ上げる。元の最低音に対する位置と内部距離を導く。`, `Raise ${pitch(root)}, ${pitch(root+4)}, ${pitch(root+7)} by ${shift} semitones. Derive positions relative to the original lowest pitch and internal gaps.`); steps=[step(t('新低音高出原低音多少半音','新低音は元低音より何半音上？','New bass above original, semitones'),shift),step(t('新中音高出原低音多少半音','新中音は元低音より何半音上？','New middle above original, semitones'),shift+4),step(t('新高音到新中音的上行距离','新中音から新高音への上行距離','Upward gap from new middle to new top'),3)]; }
    else if(stage===2) { const go=variant%2===0; prompt=t(`限定 C 大调，${go?'C4–E4–G4 → D4–F4–A4':'E4–G4–B4 → F4–A4–C5'}，每声部各升一个音阶位置。分别计算移动量与新和弦距离。`, `C 長調内で ${go?'C4–E4–G4 → D4–F4–A4':'E4–G4–B4 → F4–A4–C5'}、各声部を 1 音階位置上げる。移動量と新和音の距離を計算。`, `Within C major, move ${go?'C4–E4–G4 → D4–F4–A4':'E4–G4–B4 → F4–A4–C5'} up one scale position per voice. Calculate voice movements and new gaps.`);steps=[step(t('低声部移动半音数','低声部の移動半音数','Bass movement in semitones'),go?2:1),step(t('中声部移动半音数','中声部の移動半音数','Middle movement in semitones'),go?1:2),step(t('新低音到新中音距离','新低音から新中音の距離','New bass-to-middle gap'),go?3:4)]; }
    else if(stage===3) { prompt=t(`两个实际音高集合：{${pitch(root)}, ${pitch(root+4)}, ${pitch(root+7)}} 与 {${pitch(root-3)}, ${pitch(root)}, ${pitch(root+4)}}。先求共同音，再把旧高音升到 ${pitch(root+9)}。`, `実音高集合 {${pitch(root)}, ${pitch(root+4)}, ${pitch(root+7)}} と {${pitch(root-3)}, ${pitch(root)}, ${pitch(root+4)}}。共通音を数え、元の高音を ${pitch(root+9)} へ上げる。`, `Pitch sets {${pitch(root)}, ${pitch(root+4)}, ${pitch(root+7)}} and {${pitch(root-3)}, ${pitch(root)}, ${pitch(root+4)}}. Find common pitches; then raise the original top to ${pitch(root+9)}.`);steps=[step(t('共同音个数','共通音数','Common-pitch count'),2),step(t('第一集合中不共有的音数','第 1 集合で共有されない音数','Unshared pitches in first set'),1),step(t('旧高音到新高音上行半音数','旧高音から新高音への半音数','Semitone rise of the old top'),2)]; }
    else { prompt=t(`低音 ${pitch(root-12)} 保持不动，上方三和弦整体上移 ${shift} 半音。推导各声部实际移动量；这描述平行连接，并未提供属—主终止。`, `低音 ${pitch(root-12)} は固定し上の三和音全部を半音 ${shift} つ上げる。各声部の移動を導く。これは平行連結で属—主終止の証拠は与えていない。`, `Sustain bass ${pitch(root-12)} and raise the upper triad by ${shift} semitones. Derive each movement. This describes planing and supplies no dominant-to-tonic cadence.`);steps=[step(t('持续低音移动半音数','持続低音の移動半音数','Pedal movement in semitones'),0),step(t('上方每个声部移动半音数','上の各声部の移動半音数','Movement of each upper voice'),shift),step(t('上方保持 4、3 间距：两间距之和','上は 4、3 を保持：間隔の和','Upper gaps remain 4 and 3: their sum'),7)]; }
    explain=t('分别计算各声部和内部距离；共同音、平行移动和中心线索是不同的分析维度。','各声部と内部距離を別々に計算。共通音、平行移動、中心の手がかりは別の分析軸。','Calculate voice movements and internal gaps separately. Common tones, planing and centre evidence are distinct analytical dimensions.');
  } else if(topic.id==='polytonality') {
    const pairs=[[0,2],[0,7],[0,5],[2,8]], [a,b]=pairs[variant%4], notes=[a,(a+4)%12,(a+7)%12,b,(b+4)%12,(b+7)%12], unique=new Set(notes).size;
    if(stage===1 || stage===2) { prompt=t(`低层反复强调 ${pitch(48+a)} 中心的完整大三和弦，高层同时反复强调 ${pitch(72+b)} 中心的大三和弦；各自乐句支持这些不同中心。合并时只计音级、不计八度与重复。`, `低層は ${pitch(48+a)} 中心の長三和音、高層は同時に ${pitch(72+b)} 中心の長三和音を反復強調し、各フレーズも別中心を支える。統合ではオクターヴと重複を除く。`, `The low layer repeatedly emphasizes a major triad centred on ${pitch(48+a)}, while the high layer simultaneously emphasizes one on ${pitch(72+b)}. Each layer’s phrases support its distinct centre. Merge pitch classes without octave or duplicate counts.`);steps=[step(t('不同中心数','別中心数','Distinct-centre count'),2),step(t('合并后的不同音级数','統合した異なる音級数','Distinct pitch classes in the union'),unique),step(t('两三和弦共享的音级数','2 三和音の共有音級数','Pitch classes shared by the triads'),6-unique)]; }
    else if(stage===3) { const n=variant+4; prompt=t(`同一段 ${2*n} 拍中：低层每两拍一个起音，共 ${n} 个；高层每拍一个，共 ${2*n} 个。两层各维持不同中心。数各层起音（重叠时仍分别计），并检查时间重叠。`, `${2*n} 拍の同一区間：低層は 2 拍に 1 回で ${n} 回、高層は毎拍で ${2*n} 回。各層は別中心を保つ。重なる起音も層別に数え、同時性を確認。`, `During the same ${2*n}-beat passage, the low layer attacks every two beats (${n} attacks) and the high every beat (${2*n} attacks), maintaining distinct centres. Count attacks per layer, including simultaneous attacks separately, and check overlap.`);steps=[step(t('低层起音数','低層の起音数','Low-layer attacks'),n),step(t('两层起音合计数','両層の起音合計','Sum of both layers’ attacks'),3*n),step(t('同时活动：是填 1，否填 0','同時活動：はい 1、いいえ 0','Simultaneously active: enter 1 for yes, 0 for no'),1)]; }
    else { const simultaneous=variant%2===0; prompt=t(simultaneous?'两层同时活动，各自音阶和乐句支持 C 与 D 两个中心。请记录证据。':'先是 C 调完整片段，结束后才出现 D 调完整片段，没有重叠。请记录证据。',simultaneous?'2 層が同時に動き、各音階とフレーズが C と D の中心を支える。証拠を記録。':'C 調の部分終了後に D 調の部分が始まり、重なりはない。証拠を記録。',simultaneous?'Two simultaneous layers each have scales and phrases supporting C and D centres. Record the evidence.':'A C-key passage ends before a D-key passage begins, with no overlap. Record the evidence.');steps=[step(t('两种中心材料是否同时：是 1，否 0','別中心の素材は同時？ はい 1、いいえ 0','Different-centre material simultaneous? yes 1, no 0'),simultaneous?1:0),step(t('题中不同中心总数','記述全体の別中心総数','Distinct centres across the description'),2),step(t('是否满足此处双调性条件：是 1，否 0','ここで複調性の条件を満たす？ はい 1、いいえ 0','Meets the stated bitonality conditions? yes 1, no 0'),simultaneous?1:0)]; }
    explain=t('保留声部分层、重叠时间与各层中心证据；合并音集只说明纵向材料。','声部層、重なり、各中心の証拠を保つ。統合集合は縦の素材だけを示す。','Preserve layers, overlap and centre evidence. A merged collection only describes vertical material.');
  } else if(topic.id==='atonality') {
    const a=variant%3+1,b=variant%3+4, start=60+variant;
    const reverse=stage===3;
    prompt=t(`原动机为 ${pitch(start)}→${pitch(start+a)}→${pitch(start+a+b)}，实际相邻距离 +${a}、+${b}。${reverse?'比较倒着读与保持起音只反转距离方向。':`全体升 ${shift} 半音，再检查结构；这不自动证明调性转调。`}`, `原動機は ${pitch(start)}→${pitch(start+a)}→${pitch(start+a+b)}、隣接距離 +${a}、+${b}。${reverse?'逆順と起音を保った方向反転を比較。':`全部を半音 ${shift} つ上げ構造を確認。自動的に転調とはならない。`}`, `Original motive: ${pitch(start)}→${pitch(start+a)}→${pitch(start+a+b)}, adjacent gaps +${a}, +${b}. ${reverse?'Compare reversing note order with retaining the start and reversing gap directions.':`Raise all notes by ${shift} semitones and check the structure; this does not automatically establish modulation.`}`);
    steps=reverse?[step(t('倒着读：第一个有向距离','逆順：最初の有向距離','Reverse order: first directed gap'),-b),step(t('倒着读：第二个有向距离','逆順：第 2 有向距離','Reverse order: second directed gap'),-a),step(t('保持起音反方向：第一个距离','起音保持・方向反転：最初の距離','Retain start, reverse directions: first gap'),-a)]:[step(t('新动机第一相邻距离（半音）','新動機の最初の隣接距離（半音）','New first adjacent gap, semitones'),a),step(t('新动机第二相邻距离（半音）','新動機の第 2 隣接距離（半音）','New second adjacent gap, semitones'),b),step(t('新末音比原起音高多少半音','新終音は元の起音より何半音上？','New last pitch above the original start, semitones'),a+b+shift)];
    explain=t('同量移动保持差值；倒着读改变距离顺序与方向。局部结构可以明确，整首调性仍需上下文。','同量移動は差を保ち、逆順は距離順と方向を変える。局所構造は明確でも全曲の調性には文脈が要る。','Equal transposition preserves differences; reversing order reverses gap order and direction. Local structure can be definite while whole-piece tonality needs context.');
  } else if(topic.id==='spectralharmony') {
    const f0=[80,100,110,125][variant%4];
    if(stage===1) { prompt=t(`理想谐波基频 ${f0} Hz=第 1 分音。推导第 4、5 分音及其音程比（高÷低）。`, `理想調和基音 ${f0} Hz が第 1 部分音。第 4、5 と比（高÷低）を導く。`, `Ideal harmonic fundamental ${f0} Hz is partial 1. Derive partials 4 and 5 and their interval ratio (high/low).`);steps=[step(t('第 4 分音 Hz','第 4 部分音 Hz','Partial 4, Hz'),f0*4),step(t('第 5 分音 Hz','第 5 部分音 Hz','Partial 5, Hz'),f0*5),step(t('第 5÷第 4，填小数','第 5÷第 4、小数で','Partial 5/partial 4, decimal'),1.25)]; }
    else if(stage===2) {const ratio=[7/4,5/4,11/8,3/2][variant%4], c=cents(ratio), approx=Math.round(c/100)*100;prompt=t(`比例 ${ratio}。用 1200×log₂(比例) 求音分，再取最近的十二平均律半音，记录“近似−原值”误差。`, `比 ${ratio}。1200×log₂(比) でセントを求め、最近の 12 平均律半音と「近似−元」の誤差を記す。`, `Ratio ${ratio}. Calculate cents with 1200×log₂(ratio), round to the nearest 12-EDO semitone, then find “approximation minus original”.`);steps=[step(t('原值音分','元のセント値','Original cents'),c,.02),step(t('近似音分','近似セント値','Approximated cents'),approx),step(t('误差音分，保留正负号','誤差セント、符号を保つ','Signed error, cents'),approx-c,.02)];}
    else if(stage===3) { const offset=variant+3;prompt=t(`给定基频 ${f0} Hz，三频率为 ${f0}、${f0*2}、${f0*3+offset} Hz。检查第三频率相对这个指定理想谐波模型的偏移。`, `指定基周波数 ${f0} Hz、3 周波数 ${f0}、${f0*2}、${f0*3+offset} Hz。第 3 周波数の指定モデルからのずれを調べる。`, `Given fundamental ${f0} Hz and frequencies ${f0}, ${f0*2}, ${f0*3+offset} Hz, measure the third frequency’s offset from this specified harmonic model.`);steps=[step(t('理想第 3 分音 Hz','理想第 3 部分音 Hz','Ideal partial 3, Hz'),f0*3),step(t('实际第三项−理想第三项 Hz','実際の第 3−理想の第 3 Hz','Actual third minus ideal third, Hz'),offset),step(t('第三项与基频比，填小数','第 3 項÷基周波数、小数','Third frequency/fundamental, decimal'),(f0*3+offset)/f0,.02)]; }
    else {const gap=variant+1;prompt=t(`三个分音 ${4*f0}、${5*f0}、${6*f0} Hz 依次在第 0、${gap}、${2*gap} 拍进入。之后改成全在第 0 拍进入，频率不变。记录原方案时间与频率关系。`, `部分音 ${4*f0}、${5*f0}、${6*f0} Hz が拍 0、${gap}、${2*gap} に入り、後で全て拍 0 へ変更し周波数は固定。元の時間と周波数関係を記す。`, `Partials ${4*f0}, ${5*f0}, ${6*f0} Hz enter at beats 0, ${gap}, ${2*gap}; then move all entries to beat 0 without changing frequencies. Record the original timing and frequency relationships.`);steps=[step(t('原方案首末进入间隔（拍）','元の最初と最後の進入差（拍）','Original first-to-last entry gap, beats'),2*gap),step(t('最高÷最低频率比，填小数','最高÷最低周波数比、小数','Highest/lowest frequency ratio, decimal'),1.5),step(t('改为同时后首末进入间隔（拍）','同時化後の最初と最後の進入差（拍）','Entry gap after making them simultaneous, beats'),0)];}
    explain=t('先明确给定基频和分音编号，再算频率、比值、近似和时间；频率模型不等于完整音色。','指定基周波数と番号を明示し、周波数・比・近似・時間を計算。周波数モデルは完全な音色ではない。','Specify the fundamental and partial numbering, then calculate frequencies, ratios, approximation and timing. A frequency model is not a complete timbre.');
  } else {
    if(stage===1) {prompt=t(`基准 ${r} Hz，比例 1:5/4:3/2。求三音中的上方两音和它们之间的频率比。`, `基準 ${r} Hz、比 1:5/4:3/2。上の 2 音とその周波数比を求める。`, `Reference ${r} Hz, ratios 1:5/4:3/2. Derive the upper two frequencies and their interval ratio.`);steps=[step(t('5/4 音 Hz','5/4 音 Hz','5/4 tone, Hz'),r*5/4),step(t('3/2 音 Hz','3/2 音 Hz','3/2 tone, Hz'),r*3/2),step(t('上音÷中音，填小数','上音÷中音、小数','Top/middle ratio, decimal'),6/5)];}
    else if(stage===2) {const N=[19,24,31,53][variant%4],target=cents(5/4),k=Math.round(N*Math.log2(5/4));prompt=t(`用 ${N} EDO 最近步数近似 5/4。每步 1200/${N}，k=round(${N}×log₂(5/4))。推导步数、近似音分和“近似−原值”误差。`, `${N} EDO の最近段数で 5/4 を近似。1 段 1200/${N}、k=round(${N}×log₂(5/4))。段数・近似セント・「近似−元」誤差を導く。`, `Approximate 5/4 by the nearest step in ${N}-EDO: step size 1200/${N}, k=round(${N}×log₂(5/4)). Derive k, approximated cents and “approximation minus original” error.`);steps=[step(t('最近步数 k','最近段数 k','Nearest step k'),k),step(t('k 步音分','k 段のセント','Cents at k steps'),k*1200/N,.02),step(t('有符号误差（音分）','符号付き誤差（セント）','Signed error, cents'),k*1200/N-target,.02)];}
    else if(stage===3) { const common=r*5/4, next=r*10/11;prompt=t(`旧基准 ${r} Hz 的 5/4 音要作为共同音保留；新基准是 ${r}×10/11 Hz（≈${next.toFixed(2)}）。求共同音 Hz、新比例和误用 5/4 时的频率。`, `旧基準 ${r} Hz の 5/4 音を共通音として保つ。新基準は ${r}×10/11 Hz（≈${next.toFixed(2)}）。共通音 Hz、新比、5/4 を使い回した周波数を求める。`, `Retain the 5/4 tone of reference ${r} Hz as a common tone. New reference is ${r}×10/11 Hz (≈${next.toFixed(2)}). Find the retained Hz, new ratio and frequency if 5/4 were reused.`);steps=[step(t('保留的频率 Hz','保つ周波数 Hz','Retained frequency, Hz'),common),step(t('新比例，填小数','新比、小数','New ratio, decimal'),11/8,.02),step(t('误用 5/4 得到 Hz','5/4 の使い回し結果 Hz','Frequency from reusing 5/4, Hz'),next*5/4,.02)]; }
    else {const N=[19,24,31,53][variant%4],k=Math.round(N*Math.log2(3/2)),f=r*2**(k/N);prompt=t(`比较同一 ${r} Hz 基准上的纯律 3/2 与 ${N} EDO 最近步数 ${k}。EDO 频率=${r}×2^(${k}/${N})，记录两个 Hz 与“EDO−纯律”偏差。`, `同じ ${r} Hz 上の純正 3/2 と ${N} EDO 最近段 ${k} を比較。EDO 周波数=${r}×2^(${k}/${N})。両 Hz と「EDO−純正」差を記す。`, `Compare just 3/2 and nearest ${N}-EDO step ${k} at the same ${r} Hz reference. EDO frequency=${r}×2^(${k}/${N}). Record both Hz and “EDO minus just” difference.`);steps=[step(t('纯律 Hz','純正律 Hz','Just-intonation Hz'),r*3/2),step(t('EDO Hz','EDO Hz','EDO Hz'),f,.02),step(t('频率偏差 Hz，保留正负号','周波数差 Hz、符号付き','Signed frequency difference, Hz'),f-r*3/2,.02)];}
    explain=t('比例乘基准得到频率，两频率相除得到音程；误差用未舍入值计算，比较时固定基准。','比×基準で周波数、周波数同士を割って音程。誤差は丸め前の値で求め、比較の基準は固定。','Multiply ratios by the reference for frequencies; divide frequencies for intervals. Compute error before rounding and hold the reference fixed.');
  }
  return { prompt, steps, explain, hint: numericalHint };
}
const task = (topic, stage, suffix) => ({ id:`${topic.b}-${suffix}`, type:'derive', ref: topic.ref, error:'calc', skills:['calc','apply'], ...integratedTask(topic,stage), variants:[0,1,2,3].map(v=>integratedTask(topic,stage,(v+(suffix==='task2'?2:0))%4)) });
const G = (topic,stage,suffix) => ({ id:`${topic.b}-${suffix}`,type:'gen',gen:generatorOf(topic),params:{stage},count:1,skills:['identify','apply'],ref: topic.ref,error:'concept' });
const guide = (topic,index,suffix) => ({ id:`${topic.b}-${suffix}`,type:'guide',ref: topic.ref,title:topic.stages[index].title,skills:['apply'],
  steps:topic.stages[index].steps.map((text,i)=>({text,visual:stageVisual(topic.stages[index]),audio:topic.stages[index].sounds[i]})) });
function discovery(topic,stage,suffix) {
  const q=MODERN_GENERATORS[generatorOf(topic)].make(()=>.2,{stage});
  return { ...q,id:`${topic.b}-${suffix}`,type:'discover',practice:true,insight:{title:topic.stages[stage].title,text:q.explain} };
}
function content(topic,extension=false) {
  // B builds on the A side quests: assess the distinctive application, not the repeated introduction.
  const applicationStage = { atonality: 4, spectralharmony: 4, microtonalharmony: 3 }[topic.id] || 1;
  const mainGeneratorStage = applicationStage === 1 ? 0 : applicationStage;
  const challenge=extension?[1,2,3,4].map(s=>modernSceneTask(topic,s,`x-task${s}`)):[modernSceneTask(topic,1,'c-listen'),modernSceneTask(topic,2,'c-repair'),modernSceneTask(topic,3,'c-trace'),task(topic,applicationStage,'task1'),modernSceneTask(topic,4,'c-report')];
  challenge.push(...(extension?[1,2,3,4]:[mainGeneratorStage]).map((s,i)=>G(topic,s,`${extension?'x-':''}c${i+1}`)));
  challenge[0].breakthrough={id:`${topic.id}-design${extension?'-x':''}`,text:t('你用明确的规则解释并推导了这个音响方案。','明示された規則で響きの設計を説明・導出した。','You explained and derived the sound design using explicit rules.')};
  return { minutes:extension?19:12,insight:topic.stages[0].steps[0],coveredBranches:extension?topic.stages.slice(1).map((s)=>s.title):[],
    sections:{ discover:[modernSceneDiscovery(topic)],
      explain:extension?topic.stages.slice(1).flatMap((_,i)=>[guide(topic,i+1,`xg${i+1}`),discovery(topic,i+1,`xp${i+1}`)]):[guide(topic,applicationStage,'g1'),{...modernSceneTask(topic,3,'practice'),practice:true}],
      experiment:[{id:`${topic.b}-${extension?'x':''}toy`,type:'experiment',toy:'modernHarmony',params:{topic:topic.id,extension},ref: topic.ref,prompt:MODERN_MISSIONS[topic.id],breakthrough:{id:`${topic.id}-studio${extension?'-x':''}`,text:t('你完成了自己的音响实验，并用规则验证了改变。','自分の音の実験を完成し、変更を規則で確認した。','You completed a sound experiment and verified the change with explicit rules.')}}],challenge },
    pool:[1,2,3,4].map((s)=>G(topic,extension?s:mainGeneratorStage,`${extension?'x-':''}pool${s}`)) };
}
export const MODERN_B_LEVELS=Object.fromEntries(TOPICS.map(topic=>[topic.b,content(topic)]));
export const MODERN_B_EXTENSIONS=Object.fromEntries(TOPICS.map(topic=>[topic.b,content(topic,true)]));
