// Original listening puzzles checked against the registered sources; no borrowed scores or recordings.
// ref:rubin-nonfunctional ref:koozin-planing ref:arndt-tonality ref:ircam-spectrum ref:ircam-spectral ref:gann-ji ref:gann-ji-reasons
import { t, chord, chain, frequencies, layers } from './modern_harmony_course.js?v=20261008-spectrum-side1';
import { pitch } from './modern_harmony_generators.js?v=20261008-modern-tools1';
export const MODERN_MISSIONS = {
 nonfunctional:t('和弦连接工坊','和音連結の工房','Chord connection workshop'),
 polytonality:t('双声部侦探','二つの声部の探偵','Two-layer detective'),
 atonality:t('动机拼图','動機のパズル','Motif puzzle'),
 spectralharmony:t('声音调色台','音のパレット','Sound palette'),
 microtonalharmony:t('共同音调音室','共通音の調律室','Common-tone tuning room'),
};
const play=(label,audio)=>({label,audio});
const ask=(prompt,options,explain,extra={})=>({type:'choice',prompt,options,answer:0,explain,...extra});
const numberStep=(label,answer)=>({kind:'number',label,answer,tol:.02});
const trace=(prompt,choices,slots,explain,extra={})=>({type:'analyze',prompt,choices:choices.map(([id,label])=>({id,label})),slots:slots.map(([label,answer])=>({label,answer})),explain,...extra});
const A=t('听 A','A を聴く','Hear A'),B=t('听 B','B を聴く','Hear B');
export function modernBScene(topic,stage,variant=0){
 const n=60+variant, f=[100,120,150,200][variant%4], names=ns=>ns.map(pitch).join(' · '), C=[n,n+4,n+7], D=[n+2,n+6,n+9];
 let node;
 if(topic.id==='nonfunctional'){
  if(stage===1)node=ask(t(`工坊来了两份连接：A 是 ${names(C)} → ${names(D)}；B 把第二个和弦的中音降低半音。听后找出保留原形状的方案。`,`工房に二つの案。A は ${names(C)} → ${names(D)}。B は二つ目の和音の中央音を半音下げる。形を保つのは？`,`Two workshop drafts: A is ${names(C)} → ${names(D)}; B lowers the second chord’s middle note by one semitone. Which keeps the original shape?`),[t('A：每条声部都升两半音','A：各声部が2半音上がる','A: every voice rises two semitones'),t('B：只要低音一样就算同形','B：低音が同じなら同形','B: matching bass is sufficient'),t('两份都保留原形状','両方とも形を保つ','Both retain the shape'),t('都不能移动三和弦','どちらも三和音を動かせない','Neither can move a triad')],t('逐条核对移动量。A 保留 4、3 的内部距离；B 改变了中音，所以形状变了。','各声部の移動を確認。A は内部の4・3を保つ。B は中央音を変えるので形が変わる。','Check each voice. A keeps the internal gaps of 4 and 3; changing B’s middle note changes its shape.'),{type:'listen',play:[play(A,chain(C,D)),play(B,chain(C,[n+2,n+5,n+9]))]});
  else if(stage===2)node={type:'spell',prompt:t('只用 C 大调白键，把 C4–E4–G4 的每条声部往上移一个音阶位置。给第二个和弦补好三个音，含八度。','C 長調の白鍵だけで C4–E4–G4 を各声部1音階位置上へ。二つ目の和音の3音をオクターヴ付きで補おう。','Using only C-major white keys, move each voice of C4–E4–G4 up one scale position. Supply all three notes of the next chord, with octaves.'),answer:['D4','F4','A4'],explain:t('结果是 D4–F4–A4。这里保留音阶位置的关系，中间声部只升半音，不需要保持大三和弦性质。','結果は D4–F4–A4。音階位置を保ち、中央の声部は半音上。長三和音の性質は保たなくてよい。','The result is D4–F4–A4. Scale positions are preserved; the middle voice rises only a semitone, so major quality need not remain.'),play:[play(A,chord(60,64,67))]};
  else if(stage===3)node=trace(t(`连接 ${names(C)} → ${names([n-3,n,n+4])}。给两个声部贴标签：原来的 ${pitch(n)} 与 ${pitch(n+4)} 都还在下一和弦原处吗？`,`連結 ${names(C)} → ${names([n-3,n,n+4])}。元の ${pitch(n)} と ${pitch(n+4)} は次の和音でも同じ高さに残る？`,`Connect ${names(C)} → ${names([n-3,n,n+4])}. Tag the original ${pitch(n)} and ${pitch(n+4)}: do they remain at the same pitches in the next chord?`),[['kept',t('实际音高保留','実音高を保持','Pitch retained')],['lost',t('实际音高消失','実音高がなくなる','Pitch absent')]],[ [pitch(n),'kept'],[pitch(n+4),'kept'] ],t('两个音都留下了。先找实际共同音，不需要先为这段连接指定属—主功能。','両音が残る。まず実際の共通音を探し、属主機能を先に決めなくてよい。','Both pitches remain. Identify the actual common tones before assigning a dominant–tonic explanation.'));
  else node=ask(t(`导演希望底下 ${pitch(n-12)} 一直不动，上面两和弦继续移动。哪份配音满足这个要求？`,`下で ${pitch(n-12)} を固定し、上の和音は動かしたい。どの配置が合う？`,`Keep ${pitch(n-12)} underneath while the upper chords move. Which voicing meets the brief?`),[t('两和弦都保留该低音，上方 C 型→D 型','両和音に低音を残し、上はC型→D型','Retain that bass in both; move the upper shape'),t('所有声部一起升两半音','全声部を2半音上げる','Raise every voice two semitones'),t('只播放第二个和弦','二つ目の和音だけ再生','Play only the second chord'),t('只要写同样音名，八度可随意换','音名が同じならオクターヴは自由','A matching name is enough; change octave freely')],t('持续低音要保留实际高度；只有上面的形状移动。它是中心线索，不自动证明每个上方和弦有属—主功能。','持続低音は実際の高さを保持。上の形だけ動く。中心の手がかりだが各和音の属主機能を自動的に示さない。','A pedal retains its actual pitch while the upper shape moves. It supplies a centre cue without automatically giving each upper chord dominant–tonic function.'),{play:[play(A,chain([n-12,...C],[n-12,...D]))]});
 }else if(topic.id==='polytonality'){
  const high=[74+variant,78+variant,81+variant,74+variant],low=[48,52,55,48];
  if(stage===1)node=ask(t(`侦探先单听两层：低层 C3–E3–G3–C3，高层 ${names(high)}。高层反复回到哪里？先不要把两层混成一个音集。`,`探偵はまず別々に聴く。低層 C3–E3–G3–C3、高層 ${names(high)}。高層が繰り返し戻るのはどこ？`,`Hear the layers separately: low C3–E3–G3–C3, high ${names(high)}. Where does the high line repeatedly return? Keep the layers separate.`),[pitch(high[0]),'C3',pitch(high[1]),t('音最多的和弦一定就是中心','音が最多の和音が必ず中心','The largest chord must be the centre')],t('高层的首音与结尾支持自己的中心。单独记录每层，再检查它们是否同时维持不同中心。','高層の始めと終わりが自分の中心を支える。各層を記録し、別中心を同時に保つか確認。','The high line’s opening and ending support its own centre. Document each layer before checking simultaneous distinct centres.'),{type:'listen',play:[play(A,chain(...low)),play(B,chain(...high))]});
  else if(stage===2)node=ask(t('收到一张六音复合和弦截图，却没有后续旋律。哪份侦探报告最稳妥？','6音の複和音の写真だけ届き、続く旋律はない。適切な報告は？','You receive one snapshot of a six-note polychord, with no continuing lines. Which report is justified?'),[t('先记叠置材料；需要各层乐句证据才判断双调性','重なった素材を記録し、複調性には各層のフレーズの証拠も必要','Record the stack; bitonality needs evidence from each layer’s phrases'),t('六个音必定就是六个调','6音なら必ず6調','Six notes establish six keys'),t('任何复合和弦都证明双调性','複和音は必ず複調性を証明','Every polychord proves bitonality'),t('高音的和弦一定消灭低音的中心','高い和音が必ず低い中心を消す','The upper chord always erases the lower centre')],t('叠置描述纵向材料；双调性还要求同时活动并有不同中心的支持线索。','重なりは縦の素材の記述。複調性には同時性と別中心の裏付けも必要。','A stack describes vertical material; bitonality also needs simultaneity and support for distinct centres.'),{play:[play(A,chord(60,64,67,...high.slice(0,3)))]});
  else if(stage===3)node=trace(t('八拍里低层每两拍一个起音，高层每拍一个。给录音轨贴快慢标签；这是分辨声部的线索，不单独证明多调性。','8拍で低層は2拍ごと、高層は毎拍。トラックの速さを分類。声部を分ける手がかりで、これだけでは多調性を証明しない。','Across eight beats, low attacks every two beats and high every beat. Tag the tracks by attack rate; separation alone does not prove polytonality.'),[['slow',t('较慢：四个起音','遅い：4回の起音','Slower: four attacks')],['fast',t('较快：八个起音','速い：8回の起音','Faster: eight attacks')]],[ [t('低层','低層','Low'),'slow'],[t('高层','高層','High'),'fast'] ],t('各数各的起音。保留音区、节奏和所属声部，才不会把两条线误看成一条。','各層の起音を別々に数える。音域・リズム・声部を保って記録。','Count each layer separately and preserve its register, rhythm and identity.'),{play:[play(A,layers([48,52,55,48],[74,78,81,74,78,81,74,74]))]});
  else node=ask(t('听 A（两层先后出现）和 B（两层同时，各自重复回到 C 与 D）。哪份录音具有本例要求的双调性证据？','Aは層が順番、Bは同時に各々CとDへ反復して戻る。ここで複調性の証拠を持つのは？','A presents the layers in succession. B overlaps lines repeatedly returning to C and D. Which supplies the stated bitonality evidence?'),[t('B：同时、不同中心、各层有乐句线索','B：同時・別中心・各層のフレーズ','B: overlap, distinct centres, supporting phrases'),t('A：用了两种材料就一定双调性','A：2種類の素材だけで複調性','A: two kinds of material guarantee bitonality'),t('A 与 B 都仅凭音数就能判定','両方とも音数だけで判断できる','Note count alone settles both'),t('B 有两条线，所以必定没有中心','Bは2本の線なので中心がない','Two lines mean B has no centre')],t('把同时与先后分开判断。B 的两层同时活动并分别保有中心；A 只有先后变化。','同時と順番を分ける。Bは別中心を同時に保つ。Aは時間的な変化。','Separate succession from overlap. B maintains two centres at once; A only presents successive change.'),{type:'listen',play:[play(A,chain(...low,...[74,78,81,74])),play(B,layers(low,[74,78,81,74,78,81,74,74]))]});
 }else if(topic.id==='atonality'){
  const motif=[n,n+1,n+7],up=motif.map(x=>x+2),inv=motif.map(x=>2*n-x);
  if(stage===1)node=ask(t(`拼图原件 ${names(motif)} 的走法是上1、上6半音。A为 ${names(up)}，B为 ${names(inv)}。谁只搬了高度、没有换走法？`,`元のピース ${names(motif)} は上1・上6半音。Aは ${names(up)}、Bは ${names(inv)}。高さだけ変えて進み方を保つのは？`,`The motif ${names(motif)} rises 1 then 6 semitones. A is ${names(up)}; B is ${names(inv)}. Which changes height while retaining the directed pattern?`),[t('A：整体移位','A：全体の移高','A: transposition'),t('B：上下方向不影响走法','B：上下方向は関係ない','B: direction does not affect the pattern'),t('两个都一定是完整十二音列','両方とも完全な12音列','Both are complete twelve-tone rows'),t('起点变了就一定换调','始まりが変われば必ず転調','A different start guarantees modulation')],t('A 保留上1、上6；B 改成下1、下6，是方向翻转。先比较局部关系，不凭三个音判断整曲调性。','Aは上1・上6、Bは下1・下6。局所関係を比べ、3音だけで曲全体の調性を決めない。','A keeps +1,+6; B changes to −1,−6. Compare the local relationship without classifying a whole piece from three notes.'),{type:'listen',play:[play(A,chain(...up)),play(B,chain(...inv))]});
  else if(stage===2)node={type:'spell',prompt:t(`原件 ${names(motif)} 整体升两半音。给新拼图补全三个音（含八度）；不要只移动第一个音。`,`元の ${names(motif)} 全体を2半音上へ。新しい3音をオクターヴ付きで補おう。最初だけ動かさない。`,`Raise every note of ${names(motif)} by two semitones. Supply all three pitches with octaves; do not move only the first note.`),answer:up.map(pitch),acceptEnharmonic:true,explain:t(`结果 ${names(up)}，相邻有向距离仍是+1、+6。`,`結果 ${names(up)}。隣接する有向距離は+1・+6のまま。`,`Result: ${names(up)}, retaining directed gaps +1,+6.`),play:[play(A,chain(...motif))]};
  else if(stage===3)node=trace(t(`原件 ${names(motif)}。片段 A：${names([...motif].reverse())}；片段 B：${names(inv)}。分别给变形贴标签。`,`元は ${names(motif)}。A：${names([...motif].reverse())}、B：${names(inv)}。各変形を分類。`,`Original: ${names(motif)}. A: ${names([...motif].reverse())}; B: ${names(inv)}. Label each transformation.`),[['R',t('逆行：音的先后倒过来','逆行：順番を逆にする','Retrograde: reverse order')],['I',t('倒影：围绕首音翻转上下','反転：最初の音を軸に上下を反転','Inversion: flip direction about the first pitch')],['T',t('移位：走法不变','移高：進み方を保つ','Transposition: retain directed pattern')]],[['A','R'],['B','I']],t('A 倒转时间顺序；B 围绕给定轴音反转音程方向。它们是不同操作。','Aは時間順序、Bは指定軸に対する音程方向を反転。別の操作。','A reverses order in time; B reverses interval direction about the stated axis.'));
  else node=ask(t('你认出了一个短动机及它的移位版本。编辑要你给整首作品贴“无调性”标签，现有证据够吗？','短い動機と移高版を見つけた。編集者に曲全体を無調と分類するよう頼まれた。証拠は十分？','You identify a short motif and its transposition. An editor asks you to label the whole work atonal. Is the evidence sufficient?'),[t('不够：局部变形明确，整曲中心还需更多语境','不十分：局所変形は分かるが曲全体の中心には文脈が必要','No: the local relation is clear, but whole-piece centricity needs context'),t('够：只要移位就是无调性','移高があれば無調','Yes: transposition guarantees atonality'),t('够：三个音就是完整十二音列','3音が完全な12音列','Yes: three notes form a full twelve-tone row'),t('不够：任何动机都只能用在大调','動機は長調でしか使えない','No: motifs only work in major keys')],t('说明证据支持什么，也说明没有提供什么。无调性不是“没有组织”。','証拠が示すことと示さないことを区別。無調は無組織ではない。','State what the evidence supports and what it lacks. Atonality does not mean absence of organisation.'));
 }else if(topic.id==='spectralharmony'){
  const hz=[4*f,5*f,6*f];
  if(stage===1)node=ask(t(`调色台 A 与 B 都用 ${hz.join('、')} Hz。A同时进入，B逐个进入。先听，两份材料主要改了什么？`,`パレットAとBはどちらも ${hz.join('・')} Hz。Aは同時、Bは順に入る。主に何が変わった？`,`Both palette drafts use ${hz.join(', ')} Hz. A enters together; B enters separately. What changes?`),[t('进入时间','入る時間','Entry timing'),t('三种频率都换了','3周波数すべて','Every frequency'),t('基频一定变了','基周波数が必ず変わる','The fundamental necessarily changes'),t('音分单位变了','セントの単位','The unit of cents')],t('材料频率相同，时间组织不同。先控制一个变量，才知道差异来自哪里。','周波数は同じで時間組織が違う。一つの変数ずつ変えて原因を追う。','The frequency material stays the same; timing changes. Control one variable to locate the difference.'),{type:'listen',play:[play(A,frequencies(...hz)),play(B,chain(...hz.map(x=>69+12*Math.log2(x/440))))]});
  else if(stage===2)node={type:'derive',prompt:t(`修一根偏移音柱：基频 ${f} Hz，第三项现在 ${3*f+5} Hz。要回到指定模型的第3分音，目标和需要向下调的量各是多少？`,`ずれた柱を修正。基周波数 ${f} Hz、第3項は ${3*f+5} Hz。指定モデルの第3部分音へ戻す目標と下げる量は？`,`Repair one shifted stem: reference ${f} Hz, third component ${3*f+5} Hz. Give the target for harmonic 3 and how far to lower it.`),steps:[numberStep(t('目标 Hz','目標 Hz','Target Hz'),3*f),numberStep(t('向下调整 Hz','下げる Hz','Lower by, Hz'),5)],explain:t('先找指定基频的三倍，再比较实际位置。这里的非整数偏移是设计参数，不自动等于噪声。','指定基周波数の3倍を求め実際と比較。非整数のずれは設計値で、必ず雑音ではない。','Find three times the stated reference, then compare with the actual position. A noninteger offset is a design parameter, not automatically noise.')};
  else if(stage===3)node=trace(t('音柱固定550 Hz。操作 A把振幅0.8改为0.2；操作 B把进入时间从第0拍改为第2拍。给两个旋钮贴标签，别把它们当移调。','柱は550 Hzで固定。操作Aは振幅0.8→0.2、Bは進入を拍0→2。二つのつまみを分類。移高と混同しない。','Keep a stem at 550 Hz. Edit A changes amplitude 0.8→0.2; edit B changes entry beat 0→2. Label the controls without calling them transposition.'),[['amplitude',t('振幅','振幅','Amplitude')],['time',t('进入时间','進入時間','Entry time')],['frequency',t('频率','周波数','Frequency')]],[['A','amplitude'],['B','time']],t('振幅决定该成分的强弱，进入时间决定何时开始；这里都没改变550 Hz。','振幅は成分の強さ、進入時間は開始時刻。どちらも550 Hzは変えない。','Amplitude sets component strength; entry time sets its start. Neither edit changes 550 Hz.'));
  else node=ask(t(`录音任务：让 ${hz.join('、')} Hz 依次在第0、2、4拍开始。哪张时间表能复现这个进入顺序？`,`録音課題：${hz.join('・')} Hz を拍0・2・4に順に開始。再現できる時間表は？`,`Recording brief: start ${hz.join(', ')} Hz at beats 0,2,4 respectively. Which schedule reproduces it?`),[t('低→中→高：0、2、4拍','低→中→高：拍0・2・4','Low→middle→high: beats 0,2,4'),t('三个都在第0拍','全て拍0','All at beat 0'),t('高→中→低：0、2、4拍','高→中→低：拍0・2・4','High→middle→low: beats 0,2,4'),t('只写频率，不写时间就能确定','周波数だけで時刻も確定','Frequencies alone determine the timing')],t('把每根音柱和进入时间配对记录。频率表不包含时间，不能单独复现这段过程。','各柱と開始時刻を対応させる。周波数表だけでは時間過程を再現できない。','Pair each component with its entry time; a frequency list alone cannot reproduce the temporal process.'),{play:[play(A,{bpm:100,events:hz.map((h,i)=>({at:i*2,notes:[69+12*Math.log2(h/440)],beats:1.8}))})]});
 }else{
  const ref=[200,220,240,260][variant%4],just=ref*5/4,tempered=ref*2**(4/12);
  if(stage===1)node=ask(t(`调音室同一基准 ${ref} Hz。A中音 ${just} Hz；B中音 ${tempered.toFixed(2)} Hz。可听可看数值：哪个准确使用5/4？无需凭耳朵猜微小误差。`,`同じ基準 ${ref} Hz。Aの中央音 ${just} Hz、Bは ${tempered.toFixed(2)} Hz。数値も見て5/4を正確に使うのは？ 微小差を耳だけで当てなくてよい。`,`Same reference ${ref} Hz: A’s middle is ${just} Hz, B’s is ${tempered.toFixed(2)} Hz. Listen and inspect the numbers. Which uses exact 5/4? You need not guess a tiny difference by ear.`),[t('A：基准×5/4','A：基準×5/4','A: reference×5/4'),t('B：只要像大三度就完全相同','B：長3度らしければ完全に同じ','B: any major-third sound is identical'),t('两种必然是同一频率','必ず同じ周波数','They must be the same frequency'),t('离钢琴更近就一定是纯律','ピアノに近ければ純正律','The closer to piano, the more just it is')],t('固定基准后，比例乘基准得到实际Hz。两种方案可很接近，但数值不必相同；喜好不计分。','基準を固定して比を掛ける。近くても値は異なり得る。好みは採点しない。','Multiply the ratio by the fixed reference. Close tuning plans need not be identical; preference is not graded.'),{type:'listen',play:[play(A,frequencies(ref,just,ref*3/2)),play(B,frequencies(ref,tempered,ref*2**(7/12)))]});
  else if(stage===2)node={type:'derive',prompt:t(`还原纯律配方：基准 ${ref} Hz，上方两音标为5/4与3/2。修好频率标签，再用工具核对，不比较哪种更好听。`,`純正律の配合を復元。基準 ${ref} Hz、上の2音は5/4と3/2。周波数ラベルを直し、好みではなくツールで確認。`,`Restore the just-intonation recipe: reference ${ref} Hz, upper tones 5/4 and 3/2. Repair their frequency labels, then verify in the tool rather than ranking preference.`),steps:[numberStep(t('中音 Hz','中央音 Hz','Middle Hz'),just),numberStep(t('高音 Hz','上の音 Hz','Top Hz'),ref*3/2)],explain:t('每个比例各乘同一基准。改变基准时，同一配方会整体移动。','各比を同じ基準に掛ける。基準を変えると同じ配合全体が動く。','Multiply each ratio by the same reference. Changing that reference moves the whole recipe.')};
  else if(stage===3)node=trace(t('原和弦里有275 Hz。换成200 Hz基准后：方案 A用11/8，仍为275；方案 B照抄5/4，变成250。哪些真的保住原音？','元の和音に275 Hz。基準を200 Hzへ：Aは11/8で275、Bは5/4の使い回しで250。元の音を保つのは？','The old chord contains 275 Hz. At a new 200 Hz reference, A uses 11/8 and retains 275; B reuses 5/4 and gives 250. Tag the outcomes.'),[['kept',t('原频率保住了','元の周波数を保持','Original frequency retained')],['moved',t('原频率移动了','元の周波数が動いた','Original frequency moved')]],[['A','kept'],['B','moved']],t('共同音看实际Hz：275÷200=11/8。照抄比例不能保证同一高度。','共通音は実際のHz。275÷200=11/8。比の使い回しは同じ高さを保証しない。','Common tones use actual Hz: 275/200=11/8. Reusing a ratio does not guarantee a retained pitch.'));
  else node=ask(t(`你要把本工具 ${ref} Hz基准的19 EDO音响发给伙伴复现。哪份便条能明确频率与进入时间？`,`このツールで基準 ${ref} Hzの19 EDOの響きを再現してもらう。周波数と開始時刻が明確なメモは？`,`A partner must recreate this tool’s 19-EDO sound at ${ref} Hz. Which note specifies frequencies and entry times?`),[t(`基准${ref} Hz；19等分；步数0、6、11；同时进入`,`基準${ref} Hz、19等分、段0・6・11、同時開始`,`Reference ${ref} Hz; 19-EDO; steps 0,6,11; start together`),t('只写“大三和弦”','長三和音とだけ書く','Only “major chord”'),t('只写19 EDO，不写基准和步数','19 EDOだけで基準も段もなし','Only “19-EDO”, without reference or steps'),t('只写“更柔和一些”','柔らかめとだけ書く','Only “a softer sound”')],t('写清基准、律制、位置和时间，才能核对本工具的音高与进入过程；这不复原真实配器的全部音色。','基準・音律・位置・時間を明記してツールの音高と進入を確認。実際の楽器の全音色は復元しない。','Specify reference, tuning, positions and timing to check this tool’s pitches and entries; it does not reproduce an instrument’s complete timbre.'));
 }
 return {...node,ref:topic.ref,error:'concept',skills:node.type==='listen'?['hearing','apply']:node.type==='derive'?['calc','apply']:node.type==='spell'?['spell']:['apply'],sceneStage:stage};
}
export function modernSceneTask(topic,stage,suffix){
 return {...modernBScene(topic,stage),id:`${topic.b}-${suffix}`,variants:[0,1,2,3].map(v=>modernBScene(topic,stage,v))};
}
export function modernSceneDiscovery(topic){
 const scene=modernBScene(topic,1);
 return {...scene,type:'discover',practice:true,id:`${topic.b}-d`,insight:{title:MODERN_MISSIONS[topic.id],text:scene.explain}};
}
