// 乐理闯关 · 节奏、布鲁斯与爵士的进阶关：每个主关后面 4 关（第 5 关"综合测验"在开局时抽题）。
// 题卡只用 references.js 中已登记、已核实的资料；{ type: 'gen' } 的题由 learn_generators.js 按同样的资料计算生成。
// 依据汇总（由 scripts/annotate-learn.mjs 生成）：
//   ref:omt2e-rhythm-more ref:omt2e-swing ref:wiki-twelve-bar ref:omt2e-blues-harmony ref:wiki-blues-for-alice
//   ref:omt2e-blues-scale ref:omt2e-iivi ref:omt2e-embellishing-chords ref:omt2e-substitutions ref:omt2e-chord-scale
//   ref:wiki-jazz-minor ref:wiki-altered-scale ref:wiki-harmonic-minor ref:wiki-harmonic-major ref:wiki-whole-tone
//   ref:wiki-octatonic ref:wiki-messiaen-modes ref:wiki-neapolitan-scale ref:wiki-double-harmonic
//   ref:wiki-bebop-scale ref:omt2e-modes ref:omt2e-jazz-voicings ref:wiki-voicing ref:guitar-chord-drop
//   ref:wiki-so-what ref:wiki-upper-structure ref:omt2e-tonicization ref:wiki-backdoor ref:wiki-axis-system
//   ref:wiki-coltrane ref:soundquest-blk ref:wiki-augmented-triad ref:aizcutei-lcc ref:george-russell-lcc
//   ref:omt2e-roman-numerals ref:omt2e-major-scales ref:omt2e-modulation ref:wiki-negative-harmony
// @refs-end

const t = (zh, ja, en) => ({ zh, ja, en });
const opt = (id, label) => ({ id, label });
const G = (gen, count = 2, params) => ({ type: 'gen', gen, count, ...(params ? { params } : {}) });
const L = (title, cards) => ({ title, cards });

export const BRANCHES = {
  swing: [
    L(t('三连音与二连音', '3 連符と 2 連符', 'Triplets and duplets'), [
      { type: 'guide', ref: 'omt2e-rhythm-more', visual: { kind: 'beats', groups: [3, 2, 3, 2] },
        title: t('借来的分法', '借りた分割', 'Borrowed divisions'),
        steps: [
          t('单拍子里一拍分成三份 = 三连音（像从复拍子借来）；复拍子里一拍分成两份 = 二连音（像从单拍子借来）。', '単純拍子で 1 拍を 3 つ = 3 連符（複合拍子から借用）、複合拍子で 1 拍を 2 つ = 2 連符（単純拍子から借用）。', 'Three per beat in simple meter = triplet (borrowed from compound); two per beat in compound meter = duplet (borrowed from simple).'),
          t('三连音可以出现在任何层级：一拍三个四分音符、八分音符的三连音，甚至跨好几拍。', '3 連符はどの階層にも：1 拍の 3 連符、8 分音符の 3 連符、数拍にまたがるものも。', 'Triplets can occur at any level: on the beat, on a subdivision, or spanning several beats.'),
        ] },
      { type: 'choice', ref: 'omt2e-rhythm-more',
        prompt: t('二连音出现在什么拍子里？', '2 連符はどの拍子に出る？', 'Where do duplets appear?'),
        options: [t('复拍子', '複合拍子', 'compound meter'), t('单拍子', '単純拍子', 'simple meter'), t('只在 4/4', '4/4 だけ', 'only in 4/4')], answer: 0,
        hint: t('复拍子一拍本来分三份。', '複合拍子の 1 拍はもともと 3 分割。', 'A compound beat normally divides in three.'),
        explain: t('在复拍子里把一拍分成两份，就是二连音。', '複合拍子で 1 拍を 2 つに分けると 2 連符。', 'Splitting a compound beat in two makes a duplet.') },
      { type: 'choice', ref: 'omt2e-rhythm-more',
        prompt: t('2/4 里一个十六分音符三连音占多长？', '2/4 で 16 分音符の 3 連符はどれだけの長さ？', 'In 2/4, how long is a sixteenth-note triplet?'),
        options: [t('一个八分音符', '8 分音符 1 つ', 'one eighth note'), t('一个四分音符', '4 分音符 1 つ', 'one quarter note'), t('一个十六分音符', '16 分音符 1 つ', 'one sixteenth note')], answer: 0,
        hint: t('三个十六分三连音挤进两个十六分的位置。', '16 分の 3 連符 3 つが 16 分 2 つ分に入る。', 'Three triplet sixteenths fit where two sixteenths would go.'),
        explain: t('三个十六分三连音 = 两个十六分音符的长度 = 一个八分音符。', '16 分の 3 連符 3 つ = 16 分音符 2 つ = 8 分音符 1 つ。', 'Three triplet sixteenths = two sixteenths = one eighth.') },
      G('noteValue', 2),
    ]),
    L(t('摇摆与反拍', 'スウィングとバックビート', 'Swing and the backbeat'), [
      { type: 'guide', ref: 'omt2e-swing', visual: { kind: 'beats', groups: [2, 2, 2, 2] }, tool: { feature: 'rhythm' }, demo: { play: [[60], [67], [60], [67], [60], [67]] },
        title: t('照着写、摇着弹', '書いたとおり、揺らして弾く', 'Written straight, played swung'),
        steps: [
          t('摇摆八分音符写成普通八分音符，演奏时前长后短，大约 2:1。如果每次都用三连音来写会很乱，所以乐手自己知道要"摇"。', 'スウィングの 8 分音符は普通の 8 分音符で書き、前を長く後ろを短く約 2:1。毎回 3 連符で書くと煩雑なので、奏者が自分で揺らす。', 'Swing eighths are written as straight eighths and played long–short, about 2:1. Writing triplets everywhere would be cluttered, so players just know to swing.'),
          t('反拍（backbeat）：四拍子里在第 2、4 拍加重音，是爵士里常见的切分。', 'バックビート：4 拍子の 2・4 拍目のアクセント。ジャズでよくあるシンコペーション。', 'The backbeat accents beats 2 and 4 of a four-beat bar — a common jazz syncopation.'),
        ] },
      { type: 'choice', ref: 'omt2e-swing',
        prompt: t('为什么爵士谱不把摇摆八分音符写成三连音？', 'なぜジャズの楽譜はスウィングを 3 連符で書かない？', 'Why isn’t swing written out as triplets in jazz charts?'),
        options: [t('太乱，乐手自己知道要摇', '煩雑すぎ、奏者は揺らすことを知っている', 'it would be cluttered — players know to swing'), t('因为摇摆不是 2:1', 'スウィングは 2:1 ではないから', 'because swing is not 2:1'), t('因为爵士没有三连音', 'ジャズに 3 連符はないから', 'because jazz has no triplets')], answer: 0,
        hint: t('想象满页的三连音记号。', 'ページ一面の 3 連符を想像して。', 'Imagine a page full of triplet brackets.'),
        explain: t('照普通八分音符写更清楚，演奏时自然地摇。', '普通の 8 分音符で書いたほうが見やすく、演奏で自然に揺らす。', 'Straight notation is cleaner; the swing comes in performance.') },
      { type: 'choice', ref: 'omt2e-swing',
        prompt: t('摇摆八分音符的长短比大约是？', 'スウィング 8 分音符の長短の比は約？', 'The long–short ratio of swing eighths is roughly…'),
        options: ['2:1', '1:1', '3:1'], answer: 0,
        hint: t('像三连音的"长–短"。', '3 連符の「長–短」。', 'Like a triplet’s long–short.'),
        explain: t('第一个大约是第二个的两倍长。', '1 つ目が 2 つ目の約 2 倍。', 'The first is about twice as long as the second.') },
      G('meterClass', 2),
    ]),
    L(t('切分：打乱拍子的层级', 'シンコペーション：拍の階層を崩す', 'Syncopation: blurring the metric hierarchy'), [
      { type: 'guide', ref: ['omt2e-swing', 'omt2e-rhythm-more'], visual: { kind: 'beats', groups: [2, 2, 2, 2] },
        title: t('重音不在"该在"的地方', 'アクセントが「あるべき」場所にない', 'Accents where they “shouldn’t” be'),
        steps: [
          t('拍子有强弱层级：第 1 拍最强……切分就是把这个层级打乱，让重音落在弱拍或拍子之间。', '拍子には強弱の階層がある：1 拍目が最強……。シンコペーションはこれを崩し、弱拍や拍の間にアクセントを置く。', 'Meter has a strong–weak hierarchy with beat 1 strongest; syncopation obscures it, putting accents on weak beats or between beats.'),
          t('连音线、附点、休止符、力度记号都能制造切分。"超拍子"则是更大层级（乐句层面）的重音模式。', 'タイ・付点・休符・強弱記号で作れる。「ハイパーメーター」はさらに大きな（フレーズの）アクセントの型。', 'Ties, dots, rests and dynamics create it. Hypermeter is the accent pattern at a larger (phrase) level.'),
        ] },
      { type: 'choice', ref: 'omt2e-rhythm-more',
        prompt: t('"超拍子"（hypermeter）指的是？', '「ハイパーメーター」とは？', 'Hypermeter refers to…'),
        options: [t('更大层级（几小节）的重音模式', '数小節単位の大きなアクセントの型', 'accent patterns at a larger, multi-bar level'), t('特别快的拍子', 'とても速い拍子', 'a very fast meter'), t('三连音', '3 連符', 'triplets')], answer: 0,
        hint: t('"超" = 在小节之上。', '「ハイパー」= 小節の上の層。', '“Hyper” = above the bar.'),
        explain: t('超拍子是小节层面的强弱模式，比如四小节一组里第一小节最强。', 'ハイパーメーターは小節単位の強弱の型。', 'Hypermeter is the strong–weak pattern of whole bars.') },
      { type: 'choice', ref: 'omt2e-swing',
        prompt: t('OMT 对"切分"的说法是？', 'OMT の「シンコペーション」の説明は？', 'How does OMT describe syncopation?'),
        options: [t('拍子的层级被打乱、变得模糊', '拍の階層が崩れてあいまいになる', 'the metric hierarchy is obscured'), t('音变得很快', '音が速くなる', 'the notes get faster'), t('调性改变', '調が変わる', 'the key changes')], answer: 0,
        hint: t('强拍不再明显是强拍。', '強拍がはっきり強拍でなくなる。', 'The strong beats stop sounding strong.'),
        explain: t('切分让本来的强弱层级变得不清楚。', '本来の強弱の階層がはっきりしなくなる。', 'Syncopation blurs the usual strong–weak hierarchy.') },
      G('noteValue', 2),
    ]),
    L(t('节奏综合', 'リズムの総合', 'Rhythm review'), [
      { type: 'guide', ref: ['omt2e-swing', 'omt2e-rhythm-more'], tool: { feature: 'rhythm' },
        title: t('三连、二连、摇摆、切分', '3 連・2 連・スウィング・シンコペーション', 'Triplets, duplets, swing, syncopation'),
        steps: [
          t('三连音和二连音是借来的分法；摇摆是演奏方式；切分是重音的位置。', '3 連符と 2 連符は借りた分割、スウィングは演奏法、シンコペーションはアクセントの位置。', 'Triplets and duplets are borrowed divisions; swing is a performance practice; syncopation is about where accents fall.'),
        ] },
      G('noteValue', 3), G('meterClass', 2),
    ]),
  ],

  blues: [
    L(t('十二小节的和弦', '12 小節のコード', 'The chords of the 12-bar'), [
      { type: 'guide', ref: 'wiki-twelve-bar', tool: { feature: 'blues' },
        title: t('I I I I｜IV IV I I｜V IV I V', 'I I I I｜IV IV I I｜V IV I V', 'I I I I | IV IV I I | V IV I V'),
        steps: [
          t('基本十二小节：三个四小节乐句，只用 I、IV、V 三个和弦，而且全是属七和弦。', '基本の 12 小節：4 小節フレーズ 3 つ、I・IV・V の 3 つだけで、すべて属七。', 'The basic 12-bar: three four-bar phrases using only I, IV and V — all dominant sevenths.'),
        ] },
      G('twelveBar', 5),
    ]),
    L(t('布鲁斯的变体', 'ブルースのバリエーション', 'Blues variants'), [
      { type: 'guide', ref: ['wiki-twelve-bar', 'omt2e-blues-harmony'], tool: { feature: 'jazzmore' },
        title: t('quick change、小调、爵士布鲁斯', 'クイック・チェンジ・マイナー・ジャズ・ブルース', 'Quick change, minor and jazz blues'),
        steps: [
          t('quick change：第 2 小节就先去 IV 再回 I。小调布鲁斯：和弦换成 im7、ivm7 等小七和弦。', 'クイック・チェンジ：2 小節目で IV へ行って I に戻る。マイナー・ブルース：im7・ivm7 などの短七に。', 'Quick change: bar 2 visits IV before returning to I. Minor blues: im7, ivm7 and other minor sevenths.'),
          t('常见变体还有 16 小节布鲁斯和爵士布鲁斯；爵士布鲁斯把布鲁斯和爵士的和声语言混在一起（比如加入 ii–V）。布鲁斯可以改很多，依然算"布鲁斯"。', 'ほかに 16 小節ブルースとジャズ・ブルースも。ジャズ・ブルースはブルースとジャズの和声を混ぜる（ii–V を加えるなど）。大きく変えてもブルースはブルース。', 'Other variants include the 16-bar blues and the jazz blues, which blends blues and jazz harmony (adding ii–Vs, say). The blues can change a lot and still be “a blues”.'),
        ] },
      { type: 'choice', ref: 'wiki-twelve-bar',
        prompt: t('quick change 和基本布鲁斯的区别在第几小节？', 'クイック・チェンジと基本形の違いは何小節目？', 'In which bar does the quick change differ from the basic blues?'),
        options: [t('第 2 小节（改成 IV）', '2 小節目（IV に）', 'bar 2 (it becomes IV)'), t('第 9 小节', '9 小節目', 'bar 9'), t('第 12 小节', '12 小節目', 'bar 12')], answer: 0,
        hint: t('"快"一点去 IV。', '「早めに」IV へ。', 'It reaches IV “quickly”.'),
        explain: t('quick change 在第 2 小节先去 IV，第 3 小节回到 I。', 'クイック・チェンジは 2 小節目で IV、3 小節目で I に戻る。', 'The quick change visits IV in bar 2 and returns to I in bar 3.') },
      { type: 'choice', ref: 'wiki-twelve-bar',
        prompt: t('C 小调布鲁斯第 5 小节通常是？', 'C マイナー・ブルースの 5 小節目は？', 'Bar 5 of a C minor blues is usually…'),
        options: ['Fm7', 'F7', 'Gm7'], answer: 0,
        hint: t('IV 级变成小七和弦。', 'IV が短七に。', 'IV becomes a minor seventh.'),
        explain: t('小调布鲁斯：im7 … ivm7（Fm7）……', 'マイナー・ブルース：im7 … ivm7（Fm7）……', 'Minor blues: im7 … ivm7 (Fm7) …') },
      { type: 'choice', ref: 'omt2e-blues-harmony',
        prompt: t('布鲁斯和爵士是同一个来源吗？', 'ブルースとジャズは同じ起源？', 'Do the blues and jazz share the same origin?'),
        options: [t('不是，布鲁斯有自己独立的来源', 'いいえ、ブルースには独自の起源がある', 'no — the blues has distinct origins'), t('是', 'はい', 'yes')], answer: 0,
        hint: t('布鲁斯源自非裔美国人的劳动号子等；爵士最先在新奥尔良发展。', 'ブルースはアフリカ系アメリカ人の労働歌などから、ジャズはニューオーリンズで。', 'The blues grew from field hollers and work songs; jazz developed first in New Orleans.'),
        explain: t('虽然爵士乐手常弹布鲁斯，但布鲁斯传统有自己不同的来源，所以很多调性音乐和爵士的规律在布鲁斯里并不适用。', 'ジャズ奏者はよくブルースを弾くが、ブルースの伝統は別の起源をもち、調性音楽やジャズの常識が当てはまらないことも多い。', 'Jazz musicians play the blues often, but the blues tradition has distinct origins, so many tonal and jazz truisms don’t hold there.') },
    ]),
    L(t('bebop 布鲁斯与 Blues for Alice', 'ビバップ・ブルースと Blues for Alice', 'Bebop blues and Blues for Alice'), [
      { type: 'guide', ref: ['wiki-twelve-bar', 'wiki-blues-for-alice'], tool: { feature: 'jazzmore' },
        title: t('在布鲁斯里塞进更多 ii–V', 'ブルースに ii–V を詰め込む', 'Packing ii–Vs into the blues'),
        steps: [
          t('bebop 布鲁斯在基本框架里加进更多和弦：第 4 小节用 ii–V 走向 IV，第 6 小节用升 IV 级减七等。', 'ビバップ・ブルースは基本の枠に和音を足す：4 小節目に IV への ii–V、6 小節目に ♯IV の減七など。', 'The bebop blues adds chords to the basic frame: a ii–V into IV in bar 4, a ♯IV diminished seventh in bar 6, and so on.'),
          t('Charlie Parker 的《Blues for Alice》（"Bird blues"）更进一步：开头就是一连串下行的 ii–V。', 'チャーリー・パーカーの『Blues for Alice』（「バード・ブルース」）はさらに進み、冒頭から下行する ii–V の連続。', 'Charlie Parker’s Blues for Alice (“Bird blues”) goes further, opening with a chain of descending ii–Vs.'),
        ] },
      { type: 'choice', ref: 'wiki-blues-for-alice',
        prompt: t('《Blues for Alice》是谁写的？', '『Blues for Alice』の作者は？', 'Who wrote Blues for Alice?'),
        options: ['Charlie Parker', 'John Coltrane', 'Miles Davis'], answer: 0,
        hint: t('所以也叫"Bird blues"。', 'だから「バード・ブルース」。', 'Hence “Bird blues”.'),
        explain: t('Charlie Parker（外号 Bird）。', 'チャーリー・パーカー（愛称バード）。', 'Charlie “Bird” Parker.') },
      { type: 'choice', ref: 'wiki-twelve-bar',
        prompt: t('bebop 布鲁斯相比基本布鲁斯……', 'ビバップ・ブルースは基本形に比べて……', 'Compared with the basic blues, the bebop blues…'),
        options: [t('和弦更多、更密', 'コードが多く密', 'has more, denser chords'), t('和弦更少', 'コードが少ない', 'has fewer chords'), t('只有 8 小节', '8 小節だけ', 'is only 8 bars')], answer: 0,
        hint: t('bebop 喜欢快速换和弦。', 'ビバップは速いコード・チェンジが好き。', 'Bebop loves fast changes.'),
        explain: t('在 12 小节里加入 ii–V、减七等更多和弦。', '12 小節に ii–V や減七などを足す。', 'It adds ii–Vs, diminished sevenths and more within the 12 bars.') },
      G('twelveBar', 2),
    ]),
    L(t('布鲁斯综合', 'ブルースの総合', 'Blues review'), [
      { type: 'guide', ref: ['wiki-twelve-bar', 'omt2e-blues-harmony'], tool: { feature: 'blues' },
        title: t('三个和弦，很多变化', '3 つのコード、多くの変化', 'Three chords, many variations'),
        steps: [
          t('记住基本框架，再记住各种改法：quick change、小调、bebop、爵士布鲁斯。', '基本の枠を覚え、変え方（クイック・チェンジ・マイナー・ビバップ・ジャズ）を覚える。', 'Learn the basic frame, then the variants: quick change, minor, bebop, jazz blues.'),
        ] },
      G('twelveBar', 4),
    ]),
  ],

  bluesscale: [
    L(t('各调的布鲁斯音阶', '各調のブルース・スケール', 'Blues scales in every key'), [
      { type: 'guide', ref: 'omt2e-blues-scale', tool: { feature: 'blues' }, demo: { play: [[60], [63], [65], [66], [67], [70], [72]], chord: [48, 52, 55, 58] },
        title: t('do me fa fi sol te', 'do me fa fi sol te', 'do me fa fi sol te'),
        steps: [
          t('布鲁斯音阶 = 小调五声音阶 + 经过音 fi。听：C 布鲁斯音阶，最后是 C7。', 'ブルース・スケール = マイナー・ペンタトニック + 経過音 fi。聴いて：C ブルース・スケール、最後は C7。', 'Blues scale = minor pentatonic + the passing tone fi. Listen: C blues scale ending on C7.'),
        ] },
      G('bluesScale', 5),
    ]),
    L(t('大调布鲁斯音阶', 'メジャー・ブルース・スケール', 'The major blues scale'), [
      { type: 'guide', ref: 'omt2e-blues-scale', demo: { play: [[60], [62], [63], [64], [67], [69], [72]] },
        title: t('同一组音，换个起点', '同じ音、別の出発点', 'Same notes, new starting point'),
        steps: [
          t('把布鲁斯音阶从第二个音开始转，就得到大调布鲁斯音阶：do re ri mi sol la。C 上是 C D D♯ E G A。听。', 'ブルース・スケールを 2 番目の音から回すとメジャー・ブルース：do re ri mi sol la。C なら C D D♯ E G A。聴いて。', 'Rotate the blues scale to its second note and you get the major blues scale: do re ri mi sol la — on C, C D D♯ E G A. Listen.'),
          t('A 布鲁斯音阶（A C D D♯ E G）和 C 大调布鲁斯音阶（C D D♯ E G A）用的是同一组音。', 'A ブルース（A C D D♯ E G）と C メジャー・ブルース（C D D♯ E G A）は同じ音の集まり。', 'A blues (A C D D♯ E G) and C major blues (C D D♯ E G A) use the same notes.'),
        ] },
      { type: 'fill', ref: 'omt2e-blues-scale',
        prompt: t('G 大调布鲁斯音阶：G A ___ B D E', 'G メジャー・ブルース：G A ___ B D E', 'G major blues: G A ___ B D E'),
        bank: [opt('As', 'A♯'), opt('Bb', 'B♭'), opt('C', 'C')], answer: ['As'],
        hint: t('do re ri mi：ri 是升高的 re。', 'do re ri mi：ri は上げた re。', 'do re ri mi: ri is a raised re.'),
        explain: t('re = A，ri = A♯。', 're = A、ri = A♯。', 're = A, ri = A♯.') },
      { type: 'choice', ref: 'omt2e-blues-scale',
        prompt: t('E 布鲁斯音阶和哪个大调布鲁斯音阶同音？', 'E ブルースと同じ音のメジャー・ブルースは？', 'E blues uses the same notes as which major blues scale?'),
        options: ['G', 'E', 'A'], answer: 0,
        hint: t('大调布鲁斯从布鲁斯音阶的第二个音开始。', 'メジャー・ブルースはブルースの 2 番目の音から。', 'Major blues starts on the blues scale’s second note.'),
        explain: t('E 布鲁斯：E G A A♯ B D——从 G 开始就是 G 大调布鲁斯。', 'E ブルース：E G A A♯ B D。G から始めれば G メジャー・ブルース。', 'E blues: E G A A♯ B D — start on G for G major blues.') },
      G('bluesScale', 2),
    ]),
    L(t('布鲁斯的歌词与问答', 'ブルースの歌詞とコール＆レスポンス', 'Blues lyrics and call-and-response'), [
      { type: 'guide', ref: 'omt2e-blues-scale',
        title: t('aab 和留白', 'aab と余白', 'aab and the gaps'),
        steps: [
          t('十二小节的三个四小节乐句常配 aab 歌词：唱一句、重复（可稍改）、再唱对比的一句。', '12 小節の 3 つの 4 小節フレーズにはよく aab の歌詞：1 行・繰り返し（少し変えて）・対照的な 1 行。', 'The three four-bar phrases often carry aab lyrics: a line, its repeat (perhaps altered), a contrasting line.'),
          t('旋律常常留出空当，让乐器"应答"——问答（call and response）。例如 Bessie Smith 1923 年录的《Gulf Coast Blues》。', '旋律はよく隙間を残し、楽器が「応える」——コール＆レスポンス。例：ベッシー・スミスが 1923 年に録音した『Gulf Coast Blues』。', 'Melodies leave gaps for instruments to answer — call and response — as in Bessie Smith’s 1923 recording of “Gulf Coast Blues”.'),
        ] },
      { type: 'choice', ref: 'omt2e-blues-scale',
        prompt: t('布鲁斯旋律为什么常留出空当？', 'ブルースの旋律はなぜ隙間を残す？', 'Why do blues melodies often leave gaps?'),
        options: [t('让乐器应答（问答）', '楽器が応えるため（コール＆レスポンス）', 'for instruments to answer (call and response)'), t('因为忘词了', '歌詞を忘れたから', 'because the singer forgets'), t('为了换气而已', '息継ぎのためだけ', 'only to breathe')], answer: 0,
        hint: t('一问一答。', '問いと答え。', 'Question and answer.'),
        explain: t('空当留给其他乐器回应，形成问答。', '隙間にほかの楽器が応えてコール＆レスポンスになる。', 'The gaps let other instruments respond: call and response.') },
      { type: 'match', ref: 'omt2e-blues-scale',
        prompt: t('十二小节 ↔ 歌词', '12 小節 ↔ 歌詞', '12-bar phrase ↔ lyric'),
        pairs: [[t('第 1–4 小节', '1–4 小節', 'bars 1–4'), t('a：唱第一句', 'a：1 行目', 'a: first line')], [t('第 5–8 小节', '5–8 小節', 'bars 5–8'), t('a：重复第一句', 'a：1 行目の繰り返し', 'a: the line repeated')], [t('第 9–12 小节', '9–12 小節', 'bars 9–12'), t('b：对比的一句', 'b：対照的な行', 'b: a contrasting line')]],
        hint: t('aab。', 'aab。', 'aab.'),
        explain: t('每个四小节乐句对应一行歌词：a、a、b。', '4 小節ごとに歌詞 1 行：a・a・b。', 'Each four-bar phrase carries one line: a, a, b.') },
      G('bluesScale', 2),
    ]),
    L(t('布鲁斯音阶综合', 'ブルース・スケールの総合', 'Blues-scale review'), [
      { type: 'guide', ref: ['omt2e-blues-scale', 'omt2e-blues-harmony'], tool: { feature: 'blues' },
        title: t('小调布鲁斯、大调布鲁斯，配属七', 'マイナー・メジャー・ブルースと属七', 'Minor blues, major blues, over dominant sevenths'),
        steps: [
          t('布鲁斯里所有和弦都是属七，所以布鲁斯音阶里的 me 和大三和弦的 mi 会撞在一起——这正是布鲁斯的味道。', 'ブルースではすべて属七なので、ブルース・スケールの me と長三和音の mi がぶつかる。それがブルースらしさ。', 'Every blues chord is a dominant seventh, so the scale’s me rubs against the chord’s mi — that clash is the blues sound.'),
        ] },
      G('bluesScale', 3), G('twelveBar', 2),
    ]),
  ],

  jazz: [
    L(t('各调的 ii–V–I', '各調の ii–V–I', 'ii–V–I in every key'), [
      { type: 'guide', ref: 'omt2e-iivi', tool: { feature: 'cst' }, demo: { play: [[50, 53, 57, 60], [43, 53, 55, 59], [48, 52, 55, 59]] },
        title: t('根音五度 + 固定的和弦性质', '根音の 5 度 + 決まった種類', 'Fifth-related roots + fixed qualities'),
        steps: [
          t('大调 ii7–V7–Imaj7（m7–7–maj7），小调 ii∅7–V7–i7（∅7–7–m7）。根音按五度往下走，加上这串性质，就能认出 ii–V–I。', '長調 ii7–V7–Imaj7（m7–7–maj7）、短調 ii∅7–V7–i7（∅7–7–m7）。根音が 5 度ずつ下がり、この種類の並びで ii–V–I とわかる。', 'Major ii7–V7–Imaj7 (m7–7–maj7), minor ii∅7–V7–i7 (∅7–7–m7). Falling-fifth roots plus this quality pattern identify a ii–V–I.'),
          t('它常出现在终止处，也像积木一样出现在曲子各处。', '終止によく現れ、曲のあちこちにブロックのように出てくる。', 'It appears at cadences and as a building block throughout tunes.'),
        ] },
      G('iiVI', 5),
    ]),
    L(t('附加的 ii', '付加された ii', 'Applied ii chords'), [
      { type: 'guide', ref: ['omt2e-iivi', 'omt2e-embellishing-chords'], demo: { play: [[47, 50, 54, 57], [40, 50, 52, 56], [45, 48, 52, 55]] },
        title: t('任何属七前面都能加一个 ii', 'どの属七の前にも ii を足せる', 'Any dominant can get a ii'),
        steps: [
          t('副属的概念可以扩展到"副下属"：在一个属七和弦前面加上它上方五度的 m7 或 ∅7，就形成一个小的 ii–V。', '副属の考えは「副下属」へ広がる：属七の前にその 5 度上の m7 か ∅7 を置くと小さな ii–V。', 'The applied-chord idea extends to applied subdominants: put the m7 or ∅7 a fifth above any dominant seventh in front of it and you get a little ii–V.'),
          t('例：C 调里 E7 → Am，可以在 E7 前加 Bm7（或 Bm7♭5）：Bm7 – E7 – Am。听。', '例：C で E7 → Am なら、E7 の前に Bm7（Bm7♭5）を：Bm7 – E7 – Am。聴いて。', 'Example: in C, E7 → Am can become Bm7 (or Bm7♭5) – E7 – Am. Listen.'),
        ] },
      { type: 'choice', ref: 'omt2e-embellishing-chords',
        prompt: t('在 A7 前面加一个附加的 ii，应该是？', 'A7 の前に付加する ii は？', 'An applied ii before A7 would be…'),
        options: ['Em7', 'Dm7', 'Bm7'], answer: 0,
        hint: t('A 上方五度。', 'A の 5 度上。', 'A fifth above A.'),
        explain: t('A 上方五度是 E：Em7 – A7。', 'A の 5 度上は E：Em7 – A7。', 'A fifth above A is E: Em7 – A7.') },
      { type: 'choice', ref: 'omt2e-iivi',
        prompt: t('只有 ii–V、后面没接 I，还能认出来吗？', 'ii–V だけで I がなくても見分けられる？', 'Can you still spot a ii–V with no I after it?'),
        options: [t('能，根音五度 + m7–7 的组合很有辨识度', 'できる。根音の 5 度と m7–7 の組み合わせで', 'yes — the root motion and m7–7 pattern are distinctive'), t('不能', 'できない', 'no')], answer: 0,
        hint: t('OMT 说不完整的 ii–V 也能识别。', 'OMT：不完全な ii–V も識別できる。', 'OMT says incomplete ii–Vs can be identified too.'),
        explain: t('根音五度关系加上 m7 → 7 的性质，即使没有 I 也能认出。', '根音の 5 度関係と m7 → 7 で、I がなくてもわかる。', 'Fifth-related roots with m7 → 7 make it recognisable without the I.') },
      G('iiVI', 2),
    ]),
    L(t('小调的 ii–V–i', '短調の ii–V–i', 'Minor ii–V–i'), [
      { type: 'guide', ref: ['omt2e-iivi', 'omt2e-substitutions'], demo: { play: [[50, 53, 56, 60], [43, 53, 55, 59], [48, 51, 55, 58]] },
        title: t('∅7 – 7 – m7', '∅7 – 7 – m7', '∅7 – 7 – m7'),
        steps: [
          t('小调的 ii 是半减七，i 是小七和弦：Dm7♭5 – G7 – Cm7。听。', '短調の ii は半減七、i は短七：Dm7♭5 – G7 – Cm7。聴いて。', 'Minor’s ii is half-diminished and i is minor seventh: Dm7♭5 – G7 – Cm7. Listen.'),
          t('大调里也常借用小调的 ii∅7，并在 V7 上加 ♭9——这是爵士最常见的调式混合。', '長調でも短調の ii∅7 を借り、V7 に ♭9 を加えることが多い。ジャズで最もよくある借用。', 'Major keys often borrow minor’s ii∅7 and add ♭9 to V7 — jazz’s most common mixture.'),
        ] },
      G('iiVI', 3), G('chordSymbolNotes', 2),
    ]),
    L(t('ii–V–I 与调式综合', 'ii–V–I と旋法の総合', 'ii–V–I and modes review'), [
      { type: 'guide', ref: ['omt2e-iivi', 'omt2e-chord-scale'], tool: { feature: 'cst' },
        title: t('Dorian、Mixolydian、Ionian', 'ドリアン・ミクソリディアン・イオニアン', 'Dorian, Mixolydian, Ionian'),
        steps: [
          t('ii–V–I 最先学的三种和弦—音阶对应：ii7 配 Dorian，V7 配 Mixolydian，Imaj7 配 Ionian。', 'ii–V–I で最初に学ぶ対応：ii7 にドリアン、V7 にミクソリディアン、Imaj7 にイオニアン。', 'The first chord–scale pairings for ii–V–I: Dorian on ii7, Mixolydian on V7, Ionian on Imaj7.'),
        ] },
      G('iiVI', 3), G('chordScaleDegree', 3),
    ]),
  ],

  chordscale: [
    L(t('调内七个和弦的调式', '調内 7 つの和音の旋法', 'Modes for all seven diatonic chords'), [
      { type: 'guide', ref: 'omt2e-chord-scale', tool: { feature: 'cst' },
        title: t('第几级 = 第几个调式', '何度 = 何番目の旋法', 'Degree = mode number'),
        steps: [
          t('大调七个音各起一个调式，对应七个顺阶和弦：I Ionian、ii Dorian、iii Phrygian、IV Lydian、V Mixolydian、vi Aeolian、vii Locrian。', '長音階の 7 音がそれぞれ旋法の起点で、7 つの和音に対応：I イオニアン・ii ドリアン・iii フリジアン・IV リディアン・V ミクソリディアン・vi エオリアン・vii ロクリアン。', 'Each of the seven notes starts a mode matching a diatonic chord: I Ionian, ii Dorian, iii Phrygian, IV Lydian, V Mixolydian, vi Aeolian, vii Locrian.'),
        ] },
      G('chordScaleDegree', 5),
    ]),
    L(t('同一种和弦，三种选择', '同じ種類のコード、3 つの選択肢', 'One chord quality, three choices'), [
      { type: 'guide', ref: 'omt2e-chord-scale',
        title: t('按功能挑，而不是按性质', '種類ではなく働きで選ぶ', 'Choose by function, not quality'),
        steps: [
          t('按性质重新排：小七和弦可以配 Dorian（ii）、Phrygian（iii）或 Aeolian（vi）；大七和弦配 Ionian（I）或 Lydian（IV）。', '種類で並べ直すと：m7 はドリアン（ii）・フリジアン（iii）・エオリアン（vi）、maj7 はイオニアン（I）・リディアン（IV）。', 'Grouped by quality: minor sevenths can take Dorian (ii), Phrygian (iii) or Aeolian (vi); major sevenths Ionian (I) or Lydian (IV).'),
          t('《Fly Me to the Moon》开头一串五度进行都在 C 调里：区分 vi 和 ii、I 和 IV，才能选出贴合原调的调式。', '「Fly Me to the Moon」冒頭の 5 度進行はすべて C の中：vi と ii、I と IV を区別すると原調に合った旋法を選べる。', 'The opening of “Fly Me to the Moon” circles fifths entirely in C; telling vi from ii and I from IV picks modes that fit the key.'),
        ] },
      { type: 'choice', ref: 'omt2e-chord-scale',
        prompt: t('C 大调里的 Am7（vi）按功能配哪个调式？', 'C 長調の Am7（vi）は？', 'In C major, Am7 (vi) takes which mode by function?'),
        options: ['A Aeolian', 'A Dorian', 'A Phrygian'], answer: 0,
        hint: t('第 6 个调式。', '第 6 旋法。', 'Mode 6.'),
        explain: t('vi → Aeolian：A B C D E F G，全是 C 大调的音。', 'vi → エオリアン：A B C D E F G、すべて C 長調の音。', 'vi → Aeolian: A B C D E F G, all in C major.') },
      { type: 'choice', ref: 'omt2e-chord-scale',
        prompt: t('C 大调里的 Fmaj7（IV）配哪个调式？', 'C 長調の Fmaj7（IV）は？', 'In C major, Fmaj7 (IV) takes which mode?'),
        options: ['F Lydian', 'F Ionian', 'F Mixolydian'], answer: 0,
        hint: t('第 4 个调式。', '第 4 旋法。', 'Mode 4.'),
        explain: t('IV → Lydian：F G A B C D E，B 是 C 大调的音。', 'IV → リディアン：F G A B C D E、B は C 長調の音。', 'IV → Lydian: F G A B C D E — B belongs to C major.') },
      G('chordScaleDegree', 2),
    ]),
    L(t('和弦—音阶理论的局限', 'コード・スケール理論の限界', 'Limits of chord–scale theory'), [
      { type: 'guide', ref: 'omt2e-chord-scale',
        title: t('有用，但不是全部', '役に立つが、すべてではない', 'Useful, but not everything'),
        steps: [
          t('批评之一：它没讲和弦之间的声部进行，容易让人把每个和弦都当成新调，旋律变得断断续续。', '批判の 1 つ：和音間の声部進行を扱わず、コードごとに新しい調のように考えて旋律が途切れがちになる。', 'One critique: it ignores voice leading between chords, so students treat each chord as a new key and lines get choppy.'),
          t('它也缺少 bebop 和布鲁斯常用的半音装饰、蓝调音；1920–50 年代的乐手也并不按调式思考；而且它偏重眼睛和理性，替代不了听唱片、扒谱、和别人一起即兴。', 'ビバップやブルースの半音的な装飾やブルー・ノートも扱わない。1920〜50 年代の奏者は旋法で考えていなかったし、目と理屈に偏り、録音を聴く・採譜する・一緒に演奏することの代わりにはならない。', 'It also lacks the chromaticism and blue notes of bebop and blues, applies a 1960s modal idea to 1920–50 players who didn’t think that way, and favours eye and intellect over ear — no substitute for transcribing and playing with others.'),
        ] },
      { type: 'choice', ref: 'omt2e-chord-scale',
        prompt: t('下面哪一条是对和弦—音阶理论的批评？', 'コード・スケール理論への批判はどれ？', 'Which is a criticism of chord–scale theory?'),
        options: [t('忽略和弦之间的声部进行', '和音間の声部進行を無視する', 'it ignores voice leading between chords'), t('它不讲调式', '旋法を扱わない', 'it has no modes'), t('它只能用于古典音乐', 'クラシックにしか使えない', 'it only works for classical music')], answer: 0,
        hint: t('每个和弦都当新调。', 'コードごとに新しい調扱い。', 'Every chord treated as a new key.'),
        explain: t('缺少声部进行的思考，容易让即兴变得断续。', '声部進行の考えがなく、即興が途切れがちになる。', 'Without voice-leading thinking, improvisation can get choppy.') },
      { type: 'choice', ref: 'omt2e-chord-scale',
        prompt: t('和弦—音阶理论基于谁的理论？', 'コード・スケール理論の元になったのは？', 'Chord–scale theory is based on whose theory?'),
        options: [t('George Russell 的 LCC', 'ジョージ・ラッセルの LCC', 'George Russell’s LCC'), t('Fux 的对位法', 'フックスの対位法', 'Fux’s counterpoint'), t('Rameau 的和声学', 'ラモーの和声論', 'Rameau’s harmony')], answer: 0,
        hint: t('1953 年出版。', '1953 年出版。', 'Published in 1953.'),
        explain: t('它基于 George Russell 的利迪亚半音概念，由 Aebersold、Baker、Coker 等人推广，Berklee 等学校都在教。', 'ジョージ・ラッセルのリディアン・クロマティック・コンセプトに基づき、エーバーソルド・ベイカー・コーカーらが広め、バークリーなどで教えられる。', 'It is based on George Russell’s Lydian Chromatic Concept and was popularised by Aebersold, Baker and Coker; Berklee and others teach it.') },
      { type: 'choice', ref: 'omt2e-chord-scale',
        prompt: t('即兴时把和弦音放在正拍，作用是？', '即興で正拍にコード音を置く効果は？', 'Putting chord tones on downbeats when improvising…'),
        options: [t('让旋律"说出"现在的和弦', '旋律で今のコードを示す', 'lets the melody imply the chord'), t('让节奏变快', 'リズムが速くなる', 'speeds up the rhythm'), t('避免和弦音', 'コード音を避ける', 'avoids chord tones')], answer: 0,
        hint: t('七音调式 = 4 个和弦音 + 3 个经过音。', '7 音の旋法 = コード音 4 + 経過音 3。', 'A seven-note mode = 4 chord tones + 3 passing tones.'),
        explain: t('正拍上的和弦音把旋律和和弦连起来。', '正拍のコード音が旋律と和音をつなぐ。', 'Downbeat chord tones tie the line to the chord.') },
    ]),
    L(t('和弦—音阶综合', 'コード・スケールの総合', 'Chord–scale review'), [
      { type: 'guide', ref: 'omt2e-chord-scale', tool: { feature: 'ref' },
        title: t('罗马数字决定调式', 'ローマ数字が旋法を決める', 'Roman numerals choose the mode'),
        steps: [
          t('先做罗马数字分析，再按级数选调式；调式只是给和弦上色，不代表转调。', 'まずローマ数字分析、音度で旋法を選ぶ。旋法はコードの色づけで転調ではない。', 'Do the Roman-numeral analysis, then choose modes by degree; the modes colour chords, they don’t modulate.'),
        ] },
      G('chordScaleDegree', 4), G('modeSpell', 2),
    ]),
  ],

  melodicminor: [
    L(t('旋律小调调式的拼写', '旋律短音階の旋法の綴り', 'Spelling the melodic-minor modes'), [
      { type: 'guide', ref: ['wiki-jazz-minor', 'wiki-altered-scale'], tool: { feature: 'ref' },
        title: t('先写爵士小调，再换起点', 'まずジャズ・マイナー、そして起点を変える', 'Write jazz minor, then change the start'),
        steps: [
          t('每个调式都是某个爵士小调从不同音开始。拼写时先找它的母音阶，再从那个音开始写七个字母。', 'どの旋法もあるジャズ・マイナーを別の音から始めたもの。綴るときはまず親音階を見つけ、その音から 7 文字を書く。', 'Each mode is some jazz minor started elsewhere: find the parent, then write seven letters from the new start.'),
        ] },
      G('scaleLibrary', 5, { ids: ['melodic_minor', 'dorian_flat_2', 'lydian_sharp_5', 'lydian_dominant', 'aeolian_dominant', 'aeolian_flat_5', 'altered_dominant'] }),
    ]),
    L(t('Lydian dominant 与 Mixolydian ♭6', 'リディアン・ドミナントとミクソリディアン ♭6', 'Lydian dominant and Mixolydian ♭6'), [
      { type: 'guide', ref: 'wiki-jazz-minor', demo: { play: [[60], [62], [64], [66], [67], [69], [70], [72]], chord: [48, 52, 55, 58] },
        title: t('两种属七音阶', '2 つの属七の音階', 'Two dominant scales'),
        steps: [
          t('Lydian dominant（第 4 个调式，又叫 Acoustic 音阶）= 大调升 4 降 7：C D E F♯ G A B♭，配 C7（♯11）。听，最后是 C7。', 'リディアン・ドミナント（第 4 旋法、アコースティック・スケール）= 長調の ♯4・♭7：C D E F♯ G A B♭、C7（♯11）に。聴いて、最後は C7。', 'Lydian dominant (mode 4, the acoustic scale) = major with ♯4 and ♭7: C D E F♯ G A B♭, for C7(♯11). Listen, ending on C7.'),
          t('Mixolydian ♭6（第 5 个调式，又叫 Aeolian dominant）= 大调降 6 降 7：C D E F G A♭ B♭。', 'ミクソリディアン ♭6（第 5 旋法、エオリアン・ドミナント）= 長調の ♭6・♭7：C D E F G A♭ B♭。', 'Mixolydian ♭6 (mode 5, Aeolian dominant) = major with ♭6 and ♭7: C D E F G A♭ B♭.'),
        ] },
      { type: 'choice', ref: 'wiki-jazz-minor',
        prompt: t('D Lydian dominant 是哪个爵士小调的第 4 个调式？', 'D リディアン・ドミナントはどのジャズ・マイナーの第 4 旋法？', 'D Lydian dominant is mode 4 of which jazz minor?'),
        options: [t('A 爵士小调', 'A ジャズ・マイナー', 'A jazz minor'), t('D 爵士小调', 'D ジャズ・マイナー', 'D jazz minor'), t('G 爵士小调', 'G ジャズ・マイナー', 'G jazz minor')], answer: 0,
        hint: t('从 D 往下数到母音阶的第一个音（纯四度以下）。', 'D から親音階の第 1 音（完全 4 度下）へ。', 'Count down to the parent’s first note, a fourth below.'),
        explain: t('A 爵士小调 A B C D E F♯ G♯；从 D 开始：D E F♯ G♯ A B C = D Lydian dominant。', 'A ジャズ・マイナー A B C D E F♯ G♯、D から：D E F♯ G♯ A B C。', 'A jazz minor is A B C D E F♯ G♯; from D: D E F♯ G♯ A B C.') },
      { type: 'match', ref: 'wiki-jazz-minor',
        prompt: t('调式 ↔ 和大调相比', '旋法 ↔ 長調との違い', 'Mode ↔ compared with major'),
        pairs: [['Lydian dominant', '♯4, ♭7'], ['Mixolydian ♭6', '♭6, ♭7'], ['Lydian augmented', '♯4, ♯5']],
        hint: t('名字已经告诉你了。', '名前が答え。', 'The names tell you.'),
        explain: t('Lydian（♯4）+ dominant（♭7）；Mixolydian（♭7）+ ♭6；Lydian（♯4）+ augmented（♯5）。', 'リディアン（♯4）+ ドミナント（♭7）、ミクソ（♭7）+ ♭6、リディアン（♯4）+ オーギュメント（♯5）。', 'Lydian (♯4) + dominant (♭7); Mixolydian (♭7) + ♭6; Lydian (♯4) + augmented (♯5).') },
      G('scaleLibrary', 2, { ids: ['lydian_dominant', 'aeolian_dominant', 'lydian_sharp_5'] }),
    ]),
    L(t('Altered 与 Locrian ♮2', 'オルタードとロクリアン ♮2', 'Altered and Locrian ♮2'), [
      { type: 'guide', ref: ['wiki-jazz-minor', 'wiki-altered-scale'], demo: { play: [[55], [56], [58], [59], [61], [63], [65], [67]], chord: [43, 53, 59, 63] },
        title: t('最紧张的属七音阶', '最も緊張した属七の音階', 'The tensest dominant scale'),
        steps: [
          t('Altered（第 7 个调式，Super Locrian）：G A♭ B♭ C♭ D♭ E♭ F——保留根音、三音（写成 C♭=B）、七音，其余全是变化音（♭9、♯9、♭5、♯5）。听：G Altered，最后是 G7alt。', 'オルタード（第 7 旋法、スーパー・ロクリアン）：G A♭ B♭ C♭ D♭ E♭ F。根音・3 度（C♭=B）・7 度を残し、ほかは変化音（♭9・♯9・♭5・♯5）。聴いて：G オルタード、最後は G7alt。', 'Altered (mode 7, Super Locrian): G A♭ B♭ C♭ D♭ E♭ F — root, third (spelled C♭ = B) and seventh, everything else altered (♭9, ♯9, ♭5, ♯5). Listen: G altered, ending on G7alt.'),
          t('Locrian ♮2（第 6 个调式，又叫 Half-diminished）：Locrian 把第 2 音还原，配 m7♭5 和弦。', 'ロクリアン ♮2（第 6 旋法、ハーフ・ディミニッシュ）：ロクリアンの第 2 音を戻したもので、m7♭5 に。', 'Locrian ♮2 (mode 6, half-diminished): Locrian with a natural 2nd, for m7♭5 chords.'),
        ] },
      { type: 'choice', ref: 'wiki-altered-scale',
        prompt: t('C Altered 是哪个爵士小调的第 7 个调式？', 'C オルタードはどのジャズ・マイナーの第 7 旋法？', 'C altered is mode 7 of which jazz minor?'),
        options: [t('D♭ 爵士小调', 'D♭ ジャズ・マイナー', 'D♭ jazz minor'), t('C 爵士小调', 'C ジャズ・マイナー', 'C jazz minor'), t('B♭ 爵士小调', 'B♭ ジャズ・マイナー', 'B♭ jazz minor')], answer: 0,
        hint: t('比根音高半音。', '根音の半音上。', 'A half step above the root.'),
        explain: t('D♭ 爵士小调从 C 开始：C D♭ E♭ F♭ G♭ A♭ B♭。', 'D♭ ジャズ・マイナーを C から：C D♭ E♭ F♭ G♭ A♭ B♭。', 'D♭ jazz minor from C: C D♭ E♭ F♭ G♭ A♭ B♭.') },
      { type: 'choice', ref: 'wiki-jazz-minor',
        prompt: t('Locrian ♮2 和 Locrian 差在哪个音？', 'ロクリアン ♮2 とロクリアンの違いは？', 'How does Locrian ♮2 differ from Locrian?'),
        options: [t('第 2 音还原（大二度）', '第 2 音が戻る（長 2 度）', 'a natural (major) 2nd'), t('第 5 音还原', '第 5 音が戻る', 'a natural 5th'), t('第 7 音升高', '第 7 音が上がる', 'a raised 7th')], answer: 0,
        hint: t('名字里的 ♮2。', '名前の ♮2。', 'The ♮2 in the name.'),
        explain: t('C Locrian ♮2：C D E♭ F G♭ A♭ B♭——只有 D 和 Locrian 不同。', 'C ロクリアン ♮2：C D E♭ F G♭ A♭ B♭、D だけがロクリアンと違う。', 'C Locrian ♮2: C D E♭ F G♭ A♭ B♭ — only D differs from Locrian.') },
      G('scaleLibrary', 2, { ids: ['altered_dominant', 'aeolian_flat_5', 'dorian_flat_2'] }),
    ]),
    L(t('旋律小调调式综合', '旋律短音階の旋法の総合', 'Melodic-minor modes review'), [
      { type: 'guide', ref: 'wiki-jazz-minor', tool: { feature: 'ref' },
        title: t('七个调式，一个母音阶', '7 つの旋法、1 つの親音階', 'Seven modes, one parent'),
        steps: [
          t('爵士小调、Dorian ♭2、Lydian augmented、Lydian dominant、Mixolydian ♭6、Locrian ♮2、Altered。', 'ジャズ・マイナー・ドリアン ♭2・リディアン・オーギュメント・リディアン・ドミナント・ミクソ ♭6・ロクリアン ♮2・オルタード。', 'Jazz minor, Dorian ♭2, Lydian augmented, Lydian dominant, Mixolydian ♭6, Locrian ♮2, altered.'),
        ] },
      G('scaleLibrary', 5, { ids: ['melodic_minor', 'dorian_flat_2', 'lydian_sharp_5', 'lydian_dominant', 'aeolian_dominant', 'aeolian_flat_5', 'altered_dominant'] }),
    ]),
  ],

  harmonicminor: [
    L(t('和声小调调式的拼写', '和声短音階の旋法の綴り', 'Spelling the harmonic-minor modes'), [
      { type: 'guide', ref: 'wiki-harmonic-minor', tool: { feature: 'ref' },
        title: t('每个调式里都藏着一个增二度', 'どの旋法にも増 2 度が隠れている', 'Every mode hides an augmented second'),
        steps: [
          t('和声小调的七个调式都带着那个增二度，只是落在不同的位置：Phrygian dominant 在 ♭2–3，Lydian ♯2 在 1–♯2，Dorian ♯4 在 ♭3–♯4。', '和声短音階の 7 つの旋法はどれも増 2 度を持ち、位置が違うだけ：フリジアン・ドミナントは ♭2–3、リディアン ♯2 は 1–♯2、ドリアン ♯4 は ♭3–♯4。', 'All seven harmonic-minor modes carry the augmented second in different places: Phrygian dominant at ♭2–3, Lydian ♯2 at 1–♯2, Dorian ♯4 at ♭3–♯4.'),
        ] },
      G('scaleLibrary', 5, { ids: ['harmonic_minor', 'locrian_natural_6', 'ionian_sharp_5', 'dorian_sharp_4', 'phrygian_dominant', 'lydian_sharp_2', 'altered_super_locrian'] }),
    ]),
    L(t('Lydian ♯2 与 Dorian ♯4', 'リディアン ♯2 とドリアン ♯4', 'Lydian ♯2 and Dorian ♯4'), [
      { type: 'guide', ref: 'wiki-harmonic-minor', demo: { play: [[60], [63], [64], [66], [67], [69], [71], [72]], chord: [48, 52, 55, 59] },
        title: t('第 6 和第 4 个调式', '第 6 と第 4 の旋法', 'Modes 6 and 4'),
        steps: [
          t('Lydian ♯2（第 6 个调式）：C D♯ E F♯ G A B——Lydian 再把第 2 音升高，配大七和弦。听，最后是 Cmaj7。', 'リディアン ♯2（第 6 旋法）：C D♯ E F♯ G A B。リディアンの第 2 音をさらに上げ、maj7 に。聴いて、最後は Cmaj7。', 'Lydian ♯2 (mode 6): C D♯ E F♯ G A B — Lydian with a raised 2nd, for major sevenths. Listen, ending on Cmaj7.'),
          t('Dorian ♯4（第 4 个调式，又叫 Ukrainian Dorian、Romanian minor）：C D E♭ F♯ G A B♭，配小七和弦。', 'ドリアン ♯4（第 4 旋法、ウクライナ・ドリアン、ルーマニアン・マイナー）：C D E♭ F♯ G A B♭、m7 に。', 'Dorian ♯4 (mode 4, Ukrainian Dorian or Romanian minor): C D E♭ F♯ G A B♭, for minor sevenths.'),
        ] },
      { type: 'choice', ref: 'wiki-harmonic-minor',
        prompt: t('C Lydian ♯2 是哪个和声小调的第 6 个调式？', 'C リディアン ♯2 はどの和声短音階の第 6 旋法？', 'C Lydian ♯2 is mode 6 of which harmonic minor?'),
        options: [t('E 和声小调', 'E 和声短音階', 'E harmonic minor'), t('C 和声小调', 'C 和声短音階', 'C harmonic minor'), t('A 和声小调', 'A 和声短音階', 'A harmonic minor')], answer: 0,
        hint: t('第 6 级是母音阶主音往上小六度；倒过来往上大三度。', '第 6 音は親の主音の短 6 度上、逆に言えば長 3 度上が親。', 'Degree 6 is a minor sixth above the parent; so the parent is a major third above.'),
        explain: t('E 和声小调 E F♯ G A B C D♯，从 C 开始：C D♯ E F♯ G A B。', 'E 和声短音階 E F♯ G A B C D♯、C から：C D♯ E F♯ G A B。', 'E harmonic minor E F♯ G A B C D♯, from C: C D♯ E F♯ G A B.') },
      { type: 'match', ref: 'wiki-harmonic-minor',
        prompt: t('调式 ↔ 和弦家族', '旋法 ↔ コード・ファミリー', 'Mode ↔ chord family'),
        pairs: [['Lydian ♯2', 'maj7'], ['Dorian ♯4', 'm7'], ['Phrygian dominant', '7'], ['Locrian ♮6', 'm7♭5']],
        hint: t('看 1、3、5、7 音。', '1・3・5・7 音を見る。', 'Check notes 1, 3, 5, 7.'),
        explain: t('Lydian ♯2 大七、Dorian ♯4 小七、Phrygian dominant 属七、Locrian ♮6 半减七。', 'リディアン ♯2 は長七、ドリアン ♯4 は短七、フリジアン・ドミナントは属七、ロクリアン ♮6 は半減七。', 'Lydian ♯2 maj7, Dorian ♯4 m7, Phrygian dominant 7, Locrian ♮6 m7♭5.') },
      G('scaleLibrary', 2, { ids: ['lydian_sharp_2', 'dorian_sharp_4', 'phrygian_dominant'] }),
    ]),
    L(t('和声大调和它的调式', '和声長音階とその旋法', 'Harmonic major and its modes'), [
      { type: 'guide', ref: 'wiki-harmonic-major', demo: { play: [[60], [62], [64], [65], [67], [68], [71], [72]], chord: [48, 52, 55, 59] },
        title: t('大调只降第 6 音', '長調の第 6 音だけを下げる', 'Major with only the 6th lowered'),
        steps: [
          t('和声大调 = 大调降 6（也是和声小调升 3），上半段和和声小调一样。Rimsky-Korsakov 认为大调、自然小调、和声小调、和声大调是和声的四个基础音阶。听，最后是 Cmaj7。', '和声長音階 = 長調の ♭6（和声短音階の ♯3 とも）、上半分は和声短音階と同じ。リムスキー＝コルサコフは長・自然短・和声短・和声長を和声の 4 つの基礎音階とした。聴いて、最後は Cmaj7。', 'Harmonic major = major with ♭6 (or harmonic minor with ♯3); its upper half matches harmonic minor. Rimsky-Korsakov counted major, natural minor, harmonic minor and harmonic major as the four bases of harmony. Listen, ending on Cmaj7.'),
          t('它也有七个调式，例如第 2 个 Dorian ♭5、第 3 个 Phrygian ♭4。爵士独奏常用它的各个调式。', '7 つの旋法があり、例えば第 2 はドリアン ♭5、第 3 はフリジアン ♭4。ジャズのソロでよく使われる。', 'It too has seven modes, such as Dorian ♭5 (mode 2) and Phrygian ♭4 (mode 3); jazz soloists often use them.'),
        ] },
      { type: 'choice', ref: 'wiki-harmonic-major',
        prompt: t('D 是 C 和声大调的第 2 个音，从 D 开始的调式叫？', 'C 和声長音階を D から始めた旋法は？', 'Starting C harmonic major on D gives which mode?'),
        options: ['Dorian ♭5', 'Dorian', 'Phrygian ♭4'], answer: 0,
        hint: t('D E F G A♭ B C：第 5 音是 A♭。', 'D E F G A♭ B C：第 5 音が A♭。', 'D E F G A♭ B C: the 5th is A♭.'),
        explain: t('和 Dorian 相比只是第 5 音降低：Dorian ♭5。', 'ドリアンと比べて第 5 音だけ下がる：ドリアン ♭5。', 'Like Dorian with a lowered 5th: Dorian ♭5.') },
      { type: 'choice', ref: 'wiki-harmonic-major',
        prompt: t('谁把和声大调列为和声的四个基础音阶之一？', '和声長音階を和声の 4 つの基礎音階の 1 つとしたのは？', 'Who counted harmonic major among the four bases of harmony?'),
        options: ['Rimsky-Korsakov', 'Rameau', 'Fux'], answer: 0,
        hint: t('俄国作曲家。', 'ロシアの作曲家。', 'A Russian composer.'),
        explain: t('Rimsky-Korsakov：大调、自然小调、和声小调、和声大调。', 'リムスキー＝コルサコフ：長・自然短・和声短・和声長。', 'Rimsky-Korsakov: major, natural minor, harmonic minor, harmonic major.') },
      G('scaleLibrary', 2, { ids: ['harmonic_major', 'harmonic_minor', 'ionian_sharp_5'] }),
    ]),
    L(t('和声小调调式综合', '和声短音階の旋法の総合', 'Harmonic-minor modes review'), [
      { type: 'guide', ref: 'wiki-harmonic-minor', tool: { feature: 'ref' },
        title: t('增二度的七种位置', '増 2 度の 7 つの位置', 'The augmented second in seven places'),
        steps: [
          t('和声小调、Locrian ♮6、Ionian ♯5、Dorian ♯4、Phrygian dominant、Lydian ♯2、Super-Locrian 𝄫7。', '和声短音階・ロクリアン ♮6・イオニアン ♯5・ドリアン ♯4・フリジアン・ドミナント・リディアン ♯2・スーパー・ロクリアン 𝄫7。', 'Harmonic minor, Locrian ♮6, Ionian ♯5, Dorian ♯4, Phrygian dominant, Lydian ♯2, Super-Locrian 𝄫7.'),
        ] },
      G('scaleLibrary', 5, { ids: ['harmonic_minor', 'locrian_natural_6', 'ionian_sharp_5', 'dorian_sharp_4', 'phrygian_dominant', 'lydian_sharp_2', 'altered_super_locrian', 'harmonic_major'] }),
    ]),
  ],

  symmetric: [
    L(t('全音音阶', '全音音階', 'The whole-tone scale'), [
      { type: 'guide', ref: 'wiki-whole-tone', tool: { feature: 'ref' }, demo: { play: [[60], [62], [64], [66], [68], [70], [72]], chord: [48, 52, 56, 58] },
        title: t('朦胧、没有主音', 'ぼんやりして主音がない', 'Blurry, with no tonic'),
        steps: [
          t('全音音阶在速查里属于"增七"家族（C7♯5）。它的两个增三和弦相差大二度：C E G♯ 与 D F♯ A♯ 合起来就是全部六个音。听，最后是 C7♯5。', '全音音階は早見表で「増七」ファミリー（C7♯5）。長 2 度離れた 2 つの増三和音（C E G♯ と D F♯ A♯）で 6 音そろう。聴いて、最後は C7♯5。', 'In the reference the whole-tone scale belongs to the augmented-seventh family (C7♯5). Two augmented triads a whole step apart, C E G♯ and D F♯ A♯, cover all six notes. Listen, ending on C7♯5.'),
          t('爵士里的例子：Wayne Shorter 的《JuJu》大量使用全音音阶。', 'ジャズの例：ウェイン・ショーターの『JuJu』は全音音階を多用。', 'A jazz example: Wayne Shorter’s “JuJu” uses the whole-tone scale heavily.'),
        ] },
      { type: 'choice', ref: 'wiki-whole-tone',
        prompt: t('C 全音音阶可以由哪两个增三和弦组成？', 'C の全音音階を作る 2 つの増三和音は？', 'Which two augmented triads make up the C whole-tone scale?'),
        options: [t('C E G♯ 与 D F♯ A♯', 'C E G♯ と D F♯ A♯', 'C E G♯ and D F♯ A♯'), t('C E G 与 D F♯ A', 'C E G と D F♯ A', 'C E G and D F♯ A'), t('C E♭ G♭ 与 D F A♭', 'C E♭ G♭ と D F A♭', 'C E♭ G♭ and D F A♭')], answer: 0,
        hint: t('两个增三和弦相差大二度。', '長 2 度離れた増三和音。', 'Augmented triads a whole step apart.'),
        explain: t('C E G♯ + D F♯ A♯ = C D E F♯ G♯ A♯。', 'C E G♯ + D F♯ A♯ = C D E F♯ G♯ A♯。', 'C E G♯ + D F♯ A♯ = C D E F♯ G♯ A♯.') },
      G('symmetricScale', 3),
    ]),
    L(t('减音阶的两种排法', 'ディミニッシュの 2 つの形', 'Two forms of the diminished scale'), [
      { type: 'guide', ref: 'wiki-octatonic', demo: { play: [[60], [62], [63], [65], [66], [68], [69], [71], [72]], chord: [48, 51, 54, 57] },
        title: t('先全后半，或先半后全', '全–半か半–全', 'Whole–half or half–whole'),
        steps: [
          t('W-H（先全后半）：C D E♭ F G♭ A♭ A B，配减七和弦（如 Edim7）。它可以看成两个交错的减七和弦。听，最后是 Cdim7。', 'W-H（全–半）：C D E♭ F G♭ A♭ A B、減七（Edim7 など）に。2 つの減七が組み合わさったもの。聴いて、最後は Cdim7。', 'W-H (whole–half): C D E♭ F G♭ A♭ A B, for diminished sevenths (e.g. Edim7). It is two interlocking diminished seventh chords. Listen, ending on Cdim7.'),
          t('H-W（先半后全）：C D♭ E♭ E F♯ G A B♭，配属七和弦——速查里叫"属减音阶"。', 'H-W（半–全）：C D♭ E♭ E F♯ G A B♭、属七に。早見表では「属減音階」。', 'H-W (half–whole): C D♭ E♭ E F♯ G A B♭, for dominant sevenths — the “dominant diminished” scale in the reference.'),
        ] },
      { type: 'choice', ref: 'wiki-octatonic',
        prompt: t('C 的 H-W 减音阶里有没有 C7 的全部四个音（C E G B♭）？', 'C の H-W に C7（C E G B♭）の 4 音はすべてある？', 'Does C half–whole contain all four notes of C7 (C E G B♭)?'),
        options: [t('有', 'ある', 'yes'), t('缺 G', 'G がない', 'G is missing'), t('缺 E', 'E がない', 'E is missing')], answer: 0,
        hint: t('C D♭ E♭ E F♯ G A B♭。', 'C D♭ E♭ E F♯ G A B♭。', 'C D♭ E♭ E F♯ G A B♭.'),
        explain: t('C、E、G、B♭ 都在里面，所以 H-W 适合属七和弦。', 'C・E・G・B♭ がすべてあるので、H-W は属七向き。', 'C, E, G and B♭ are all there, so half–whole suits dominant sevenths.') },
      { type: 'choice', ref: 'wiki-octatonic',
        prompt: t('Edim7 适合用哪种减音阶？', 'Edim7 にはどちらのディミニッシュ？', 'Which diminished scale suits Edim7?'),
        options: [t('先全后半（W-H）', '全–半（W-H）', 'whole–half (W-H)'), t('先半后全（H-W）', '半–全（H-W）', 'half–whole (H-W)')], answer: 0,
        hint: t('维基百科的例子。', 'ウィキペディアの例。', 'Wikipedia’s example.'),
        explain: t('W-H 配减七和声（如 Edim7），H-W 配属七和声。', 'W-H は減七（Edim7 など）、H-W は属七。', 'W-H goes with diminished harmony (e.g. Edim7), H-W with dominant harmony.') },
      G('symmetricScale', 2),
    ]),
    L(t('有限移位调式', '移調の限られた旋法', 'Modes of limited transposition'), [
      { type: 'guide', ref: ['wiki-messiaen-modes', 'wiki-whole-tone'], tool: { feature: 'posttonal' },
        title: t('梅西安的七种调式', 'メシアンの 7 つの旋法', 'Messiaen’s seven modes'),
        steps: [
          t('梅西安把移位几次就回到同一组音的音阶叫"有限移位调式"。他的第一种就是全音音阶（只有 2 个版本），第二种是八声（减）音阶（3 个版本）。', 'メシアンは何回か移すと同じ音に戻る音階を「移調の限られた旋法」と呼んだ。第 1 番は全音音階（2 通り）、第 2 番は八音（ディミニッシュ）音階（3 通り）。', 'Messiaen called scales that return to the same notes after a few transpositions “modes of limited transposition”. His first is the whole-tone scale (2 versions), the second the octatonic (3 versions).'),
        ] },
      { type: 'choice', ref: 'wiki-messiaen-modes',
        prompt: t('梅西安的第一种有限移位调式是？', 'メシアンの第 1 番の旋法は？', 'Messiaen’s first mode of limited transposition is…'),
        options: [t('全音音阶', '全音音階', 'the whole-tone scale'), t('减音阶', 'ディミニッシュ', 'the diminished scale'), t('五声音阶', '五声音階', 'the pentatonic')], answer: 0,
        hint: t('只有 2 个版本。', '2 通りだけ。', 'Only 2 versions.'),
        explain: t('第一种是全音音阶；第二种是八声音阶。', '第 1 番は全音音階、第 2 番は八音音階。', 'Mode 1 is whole-tone; mode 2 is octatonic.') },
      { type: 'choice', ref: 'wiki-octatonic',
        prompt: t('为什么十二平均律里只有 3 个不同的减音阶？', 'なぜ 12 平均律でディミニッシュは 3 つだけ？', 'Why are there only 3 distinct diminished scales?'),
        options: [t('三个减七和弦里任取两个组合，只有 3 种', '3 つの減七から 2 つを選ぶ組み合わせが 3 通り', 'choosing two of the three diminished sevenths gives 3 combinations'), t('因为它有 3 个音', '3 音だから', 'it has 3 notes'), t('作曲家规定', '作曲家が決めた', 'composers decided')], answer: 0,
        hint: t('12 个音分成 3 个减七和弦。', '12 音は 3 つの減七に分かれる。', 'The 12 notes split into three dim7 chords.'),
        explain: t('任意两个减七和弦合起来就是一个八声音阶：3 选 2 = 3 种。', '任意の 2 つの減七で八音音階：3 から 2 = 3 通り。', 'Any two dim7 chords make an octatonic scale: 3 choose 2 = 3.') },
      G('symmetricScale', 2),
    ]),
    L(t('对称音阶综合', '対称音階の総合', 'Symmetric-scale review'), [
      { type: 'guide', ref: ['wiki-whole-tone', 'wiki-octatonic'], tool: { feature: 'ref' },
        title: t('6 个音或 8 个音', '6 音か 8 音', 'Six notes or eight'),
        steps: [
          t('全音音阶 6 个音、2 个版本、配 7♯5；减音阶 8 个音、3 个版本，W-H 配 dim7、H-W 配 7。', '全音音階は 6 音・2 通り・7♯5 に、ディミニッシュは 8 音・3 通り、W-H は dim7、H-W は 7。', 'Whole-tone: 6 notes, 2 versions, for 7♯5; diminished: 8 notes, 3 versions — W-H for dim7, H-W for 7.'),
        ] },
      G('symmetricScale', 5),
    ]),
  ],

  morescales: [
    L(t('那不勒斯音阶', 'ナポリ音階', 'Neapolitan scales'), [
      { type: 'guide', ref: 'wiki-neapolitan-scale', tool: { feature: 'ref' }, demo: { play: [[60], [61], [63], [65], [67], [68], [71], [72]], chord: [48, 51, 55, 59] },
        title: t('降 2 的小调', '♭2 の短調', 'Minor with a lowered 2nd'),
        steps: [
          t('那不勒斯小调 = 和声小调降 2：C D♭ E♭ F G A♭ B；那不勒斯大调 = 旋律小调降 2：C D♭ E♭ F G A B。两者都配小大七和弦（CmMaj7）。听，最后是 CmMaj7。', 'ナポリ短音階 = 和声短音階の ♭2：C D♭ E♭ F G A♭ B、ナポリ長音階 = 旋律短音階の ♭2：C D♭ E♭ F G A B。どちらも CmMaj7 に。聴いて、最後は CmMaj7。', 'Neapolitan minor = harmonic minor with ♭2: C D♭ E♭ F G A♭ B; Neapolitan major = melodic minor with ♭2: C D♭ E♭ F G A B. Both suit CmMaj7. Listen, ending on CmMaj7.'),
          t('名字里虽然有"大调"，两种其实都有小三度；区别在第 6 音。', '名前に「長」とあっても、どちらも短 3 度。違いは第 6 音。', 'Despite the name, both have a minor third; they differ in the 6th.'),
        ] },
      { type: 'choice', ref: 'wiki-neapolitan-scale',
        prompt: t('那不勒斯大调和那不勒斯小调的区别在？', 'ナポリ長音階と短音階の違いは？', 'Neapolitan major and minor differ in…'),
        options: [t('第 6 音', '第 6 音', 'the 6th'), t('第 3 音', '第 3 音', 'the 3rd'), t('第 2 音', '第 2 音', 'the 2nd')], answer: 0,
        hint: t('两种都是 ♭2、♭3。', 'どちらも ♭2・♭3。', 'Both have ♭2 and ♭3.'),
        explain: t('小调 ♭6（A♭），大调 ♮6（A）。', '短は ♭6（A♭）、長は ♮6（A）。', 'Minor has ♭6 (A♭), major ♮6 (A).') },
      { type: 'choice', ref: 'wiki-neapolitan-scale',
        prompt: t('那不勒斯大调的三度是大三度吗？', 'ナポリ長音階の 3 度は長 3 度？', 'Does the Neapolitan major have a major third?'),
        options: [t('不是，也是小三度', 'いいえ、短 3 度', 'no — it also has a minor third'), t('是', 'はい', 'yes')], answer: 0,
        hint: t('名字不说明三度。', '名前は 3 度を表していない。', 'The name doesn’t describe the third.'),
        explain: t('两种那不勒斯音阶都有小三度，"大""小"指的是第 6 音。', 'どちらのナポリ音階も短 3 度で、「長・短」は第 6 音のこと。', 'Both have a minor third; “major” and “minor” refer to the 6th.') },
      G('scaleLibrary', 2, { ids: ['neapolitan_major', 'neapolitan_minor'] }),
    ]),
    L(t('双和声音阶', 'ダブル・ハーモニック', 'The double harmonic scale'), [
      { type: 'guide', ref: 'wiki-double-harmonic', demo: { play: [[60], [61], [64], [65], [67], [68], [71], [72]], chord: [48, 52, 55, 59] },
        title: t('两个增二度', '増 2 度が 2 つ', 'Two augmented seconds'),
        steps: [
          t('双和声 = 大调降 2 降 6：C D♭ E F G A♭ B，台阶是 半、增二、半、全、半、增二、半。速查里标作"Arabic"，配大七和弦。听，最后是 Cmaj7。', 'ダブル・ハーモニック = 長調の ♭2・♭6：C D♭ E F G A♭ B、段差は 半・増2・半・全・半・増2・半。早見表では「Arabic」、maj7 に。聴いて、最後は Cmaj7。', 'Double harmonic = major with ♭2 and ♭6: C D♭ E F G A♭ B, steps half, aug 2nd, half, whole, half, aug 2nd, half. The reference calls it “Arabic”, for maj7. Listen, ending on Cmaj7.'),
          t('它和印度的 Bhairav thaat、南印度的 Mayamalavagowla 同音。', 'インドのバイラヴ・タートや南インドのマーヤーマーラヴァゴウラと同じ音。', 'It matches India’s Bhairav thaat and the Carnatic Mayamalavagowla.'),
        ] },
      { type: 'fill', ref: 'wiki-double-harmonic',
        prompt: t('C 双和声：C ___ E F G ___ B', 'C ダブル・ハーモニック：C ___ E F G ___ B', 'C double harmonic: C ___ E F G ___ B'),
        bank: [opt('Db', 'D♭'), opt('Ab', 'A♭'), opt('D', 'D'), opt('A', 'A')], answer: ['Db', 'Ab'],
        hint: t('降低第 2 和第 6 音。', '第 2 と第 6 音を下げる。', 'Lower the 2nd and 6th.'),
        explain: t('C D♭ E F G A♭ B。', 'C D♭ E F G A♭ B。', 'C D♭ E F G A♭ B.') },
      { type: 'choice', ref: 'wiki-double-harmonic',
        prompt: t('双和声音阶是怎么从 Ionian 得到的？', 'ダブル・ハーモニックはイオニアンからどう作る？', 'How is the double harmonic derived from Ionian?'),
        options: [t('降低第 2 和第 6 音', '第 2 と第 6 音を下げる', 'lower the 2nd and 6th'), t('升高第 4 音', '第 4 音を上げる', 'raise the 4th'), t('降低第 3 和第 7 音', '第 3 と第 7 音を下げる', 'lower the 3rd and 7th')], answer: 0,
        hint: t('又叫 Ionian ♭2 ♭6。', 'イオニアン ♭2 ♭6 とも。', 'Also called Ionian ♭2 ♭6.'),
        explain: t('Ionian ♭2 ♭6 = 双和声音阶。', 'イオニアン ♭2 ♭6 = ダブル・ハーモニック。', 'Ionian ♭2 ♭6 = double harmonic.') },
      G('scaleLibrary', 2, { ids: ['arabic', 'phrygian_dominant'] }),
    ]),
    L(t('四种 bebop 音阶', '4 つのビバップ・スケール', 'The four bebop scales'), [
      { type: 'guide', ref: 'wiki-bebop-scale', tool: { feature: 'jazzmore' }, demo: { play: [[72], [71], [70], [69], [67], [65], [64], [62], [60]] },
        title: t('七个音 + 一个经过音', '7 音 + 経過音 1 つ', 'Seven notes plus one passing tone'),
        steps: [
          t('属七 bebop：在 ♭7 和 1 之间加音；大调 bebop：在 5 和 6 之间加 ♯5；旋律小调 bebop：在 5 和 6 之间加音；和声小调 bebop：在 ♭6 和 7 之间加 ♭7。', 'ドミナント・ビバップ：♭7 と 1 の間、メジャー・ビバップ：5 と 6 の間に ♯5、メロディック・マイナー：5 と 6 の間、ハーモニック・マイナー：♭6 と 7 の間に ♭7。', 'Dominant bebop adds a note between ♭7 and 1; major bebop adds ♯5 between 5 and 6; melodic-minor bebop adds one between 5 and 6; harmonic-minor bebop adds ♭7 between ♭6 and 7.'),
          t('Barry Harris 把大调 bebop 音阶叫做"大六度减音阶"：大六和弦与减七和弦交替。听：C 属七 bebop 下行，和弦音都落在正拍。', 'バリー・ハリスはメジャー・ビバップを「メジャー 6th ディミニッシュ」と呼んだ：メジャー 6 とディミニッシュ 7 が交互。聴いて：C ドミナント・ビバップの下行、コード音が正拍に来る。', 'Barry Harris calls the major bebop scale the major sixth diminished scale, alternating a major sixth chord and a diminished seventh. Listen: C dominant bebop descending, chord tones on the beats.'),
        ] },
      { type: 'match', ref: 'wiki-bebop-scale',
        prompt: t('bebop 音阶 ↔ 加音的位置', 'ビバップ・スケール ↔ 足す位置', 'Bebop scale ↔ where the extra note goes'),
        pairs: [[t('属七', 'ドミナント', 'dominant'), t('♭7 与 1 之间', '♭7 と 1 の間', 'between ♭7 and 1')], [t('大调', 'メジャー', 'major'), t('5 与 6 之间（♯5）', '5 と 6 の間（♯5）', 'between 5 and 6 (♯5)')], [t('和声小调', 'ハーモニック・マイナー', 'harmonic minor'), t('♭6 与 7 之间（♭7）', '♭6 と 7 の間（♭7）', 'between ♭6 and 7 (♭7)')]],
        hint: t('属七 bebop 补上的是大七度。', 'ドミナントは長 7 度を足す。', 'Dominant bebop adds the major seventh.'),
        explain: t('属七加 7、大调加 ♯5、和声小调加 ♭7。', 'ドミナントは 7、メジャーは ♯5、ハーモニック・マイナーは ♭7。', 'Dominant adds 7, major adds ♯5, harmonic minor adds ♭7.') },
      { type: 'choice', ref: 'wiki-bebop-scale',
        prompt: t('Barry Harris 把大调 bebop 音阶叫什么？', 'バリー・ハリスはメジャー・ビバップを何と呼んだ？', 'What did Barry Harris call the major bebop scale?'),
        options: [t('大六度减音阶', 'メジャー 6th ディミニッシュ', 'the major sixth diminished scale'), t('布鲁斯音阶', 'ブルース・スケール', 'the blues scale'), t('全音音阶', '全音音階', 'the whole-tone scale')], answer: 0,
        hint: t('大六和弦 + 减七和弦。', 'メジャー 6 + ディミニッシュ 7。', 'Major sixth + diminished seventh.'),
        explain: t('音阶里的音交替组成大六和弦与减七和弦。', '音階の音が交互にメジャー 6 と減七を作る。', 'Its notes alternate between a major sixth chord and a diminished seventh.') },
      G('bebopDominant', 2),
    ]),
    L(t('速查音阶大综合', '早見表の音階の総合', 'Chord–scale library review'), [
      { type: 'guide', ref: ['omt2e-modes', 'wiki-jazz-minor', 'wiki-harmonic-minor'], tool: { feature: 'ref' },
        title: t('二十多种音阶，三个问题', '20 種以上の音階、3 つの質問', 'Two dozen scales, three questions'),
        steps: [
          t('任何一个音阶都可以问：它的音是什么？它配哪种和弦（1、3、5、7）？它是哪个母音阶的第几个调式？', 'どの音階にも：音は？どのコード（1・3・5・7）に？どの親音階の第何旋法？', 'Ask of any scale: what are its notes? Which chord (1, 3, 5, 7)? Which mode of which parent?'),
        ] },
      G('scaleLibrary', 6),
    ]),
  ],

  jazzvoicing: [
    L(t('壳音配置', 'シェル・ヴォイシング', 'Shell voicings'), [
      { type: 'guide', ref: 'omt2e-jazz-voicings', tool: { feature: 'jazzmore' }, demo: { play: [[43, 53, 59], [48, 52, 59], [50, 53, 60]] },
        title: t('根音 + 三音 + 七音', '根音 + 3 度 + 7 度', 'Root + third + seventh'),
        steps: [
          t('左手根音，上面只放三音和七音，就能清楚表达和弦性质；五音几乎都可以省。', '左手で根音、上に 3 度と 7 度だけで性質がはっきりする。5 度はほぼ省ける。', 'Root in the left hand with just the third and seventh above shows the quality; the fifth can almost always go.'),
          t('间距模仿泛音列：低音区间隔宽，高音区间隔窄；延伸音放高声部。', '間隔は倍音列をまねる：低音域は広く、高音域は狭く。テンションは上の声部へ。', 'Space like the harmonic series: wide low, close high; extensions in the upper voices.'),
        ] },
      G('guideTones', 5),
    ]),
    L(t('Drop 2 练习', 'ドロップ 2 の練習', 'Drop-2 drill'), [
      { type: 'guide', ref: ['wiki-voicing', 'guitar-chord-drop'],
        title: t('数清楚"从上往下第几个"', '「上から何番目」を正確に', 'Count from the top'),
        steps: [
          t('紧密排列由低到高写好，再从最高音往下数：第二个降八度 = drop 2，第三个降八度 = drop 3。', '密集配置を下から書き、最高音から下へ数える：2 番目をオクターヴ下げ = ドロップ 2、3 番目 = ドロップ 3。', 'Write the close voicing low to high, then count down from the top: drop the second = drop 2, the third = drop 3.'),
        ] },
      G('drop2', 5),
    ]),
    L(t('So What 与四度和弦', 'ソー・ホワットと 4 度和音', 'So What and quartal sounds'), [
      { type: 'guide', ref: 'wiki-so-what', demo: { play: [[52, 57, 62, 67, 71]] },
        title: t('三个纯四度 + 一个大三度', '完全 4 度 3 つ + 長 3 度', 'Three perfect fourths + a major third'),
        steps: [
          t('So What 和弦：自下而上三个纯四度，再叠一个大三度。E A D G B 当作 Em11（1 4 ♭7 ♭3 5）。', 'ソー・ホワット・コード：下から完全 4 度 3 つ、上に長 3 度。E A D G B を Em11（1 4 ♭7 ♭3 5）として。', 'The So What chord: three perfect fourths topped by a major third. E A D G B as Em11 (1 4 ♭7 ♭3 5).'),
          t('名字来自 Miles Davis 的《So What》，钢琴手 Bill Evans 在那首曲子里用了这种配置。听。', '名前はマイルス・デイヴィスの『So What』から。ピアノのビル・エヴァンスがこの曲で使った。聴いて。', 'It is named after Miles Davis’s “So What”, where pianist Bill Evans used it. Listen.'),
        ] },
      { type: 'fill', ref: 'wiki-so-what',
        prompt: t('D 上的 So What 和弦：D G C ___ A', 'D の上のソー・ホワット：D G C ___ A', 'So What chord on D: D G C ___ A'),
        bank: [opt('F', 'F'), opt('E', 'E'), opt('G', 'G')], answer: ['F'],
        hint: t('C 往上纯四度。', 'C の完全 4 度上。', 'A perfect fourth above C.'),
        explain: t('D G C F 是三个纯四度，最后 F–A 是大三度：Dm11。', 'D G C F は完全 4 度 3 つ、F–A が長 3 度：Dm11。', 'D G C F are three perfect fourths, then F–A a major third: Dm11.') },
      { type: 'choice', ref: 'wiki-so-what',
        prompt: t('So What 和弦通常当作哪种和弦用？', 'ソー・ホワット・コードはふつう何として使う？', 'The So What chord is usually used as a…'),
        options: [t('小十一和弦', 'マイナー・イレブンス', 'minor eleventh'), t('属七和弦', '属七', 'dominant seventh'), t('增三和弦', '増三和音', 'augmented triad')], answer: 0,
        hint: t('1 4 ♭7 ♭3 5。', '1 4 ♭7 ♭3 5。', '1 4 ♭7 ♭3 5.'),
        explain: t('里面有 ♭3 和 ♭7，还有 11 音：小十一和弦。', '♭3・♭7・11 を含むのでマイナー・イレブンス。', 'It holds ♭3, ♭7 and the 11th: a minor eleventh.') },
      G('guideTones', 2),
    ]),
    L(t('高结构三和弦', 'アッパー・ストラクチャー', 'Upper-structure triads'), [
      { type: 'guide', ref: 'wiki-upper-structure', tool: { feature: 'jazzmore' }, demo: { play: [[52, 58, 62, 66, 69]] },
        title: t('左手三全音，右手一个三和弦', '左手に三全音、右手に三和音', 'Tritone left, triad right'),
        steps: [
          t('左手弹属七的三音和七音（C7 里的 E、B♭），右手弹一个三和弦，组合出带延伸音的属和弦。', '左手で属七の 3 度と 7 度（C7 なら E・B♭）、右手で三和音を弾き、テンション付きの属和音を作る。', 'The left hand plays the dominant’s third and seventh (E and B♭ in C7), the right hand a triad, producing a dominant with tensions.'),
          t('例：C7 上方弹 D 大三和弦（D F♯ A），就得到 9、♯11、13。听。', '例：C7 の上で D の長三和音（D F♯ A）を弾くと 9・♯11・13。聴いて。', 'Example: a D major triad (D F♯ A) over C7 gives the 9th, ♯11 and 13th. Listen.'),
        ] },
      { type: 'choice', ref: 'wiki-upper-structure',
        prompt: t('C7 上方弹 D 大三和弦（D F♯ A），得到哪些延伸音？', 'C7 の上で D の長三和音（D F♯ A）を弾くと？', 'A D major triad (D F♯ A) over C7 supplies which tensions?'),
        options: ['9, ♯11, 13', '♭9, 11, ♭13', '♯9, 5, 7'], answer: 0,
        hint: t('以 C 为根音数：D 九、F♯ 升十一、A 十三。', 'C から数える：D は 9、F♯ は ♯11、A は 13。', 'From C: D is 9, F♯ is ♯11, A is 13.'),
        explain: t('D = 9，F♯ = ♯11，A = 13。', 'D = 9・F♯ = ♯11・A = 13。', 'D = 9, F♯ = ♯11, A = 13.') },
      { type: 'choice', ref: 'wiki-upper-structure',
        prompt: t('高结构配置里左手通常弹什么？', 'アッパー・ストラクチャーで左手はふつう？', 'In upper-structure voicings, what does the left hand usually play?'),
        options: [t('三音和七音（三全音）', '3 度と 7 度（三全音）', 'the third and seventh (a tritone)'), t('根音和五音', '根音と 5 度', 'root and fifth'), t('一个三和弦', '三和音', 'a triad')], answer: 0,
        hint: t('属七的"骨架"。', '属七の「骨格」。', 'The dominant’s skeleton.'),
        explain: t('三音、七音确定属七性质，右手的三和弦负责延伸音。', '3 度・7 度が属七を決め、右手の三和音がテンションを担う。', 'Third and seventh define the dominant; the right-hand triad supplies tensions.') },
      G('guideTones', 2),
    ]),
  ],

  substitutions: [
    L(t('三全音替代练习', '裏コードの練習', 'Tritone-sub drill'), [
      { type: 'guide', ref: 'omt2e-substitutions', tool: { feature: 'jazzmore' },
        title: t('共享同一个三全音', '同じ三全音を共有', 'Sharing one tritone'),
        steps: [
          t('属七和弦可以换成相隔三全音的另一个属七：名字同时说明了"两个和弦相隔三全音"和"它们共享一个三全音"。', '属七は三全音離れた属七に置き換えられる。名前は「2 つが三全音離れている」と「三全音を共有する」の両方を表す。', 'A dominant seventh can be replaced by the one a tritone away; the name refers to both the distance and the shared tritone.'),
        ] },
      G('tritoneSub', 5),
    ]),
    L(t('副属替代与借用', '副属の代理と借用', 'Applied-chord substitution and mixture'), [
      { type: 'guide', ref: ['omt2e-substitutions', 'omt2e-tonicization'], demo: { play: [[48, 52, 55, 59], [45, 49, 52, 55], [50, 53, 57, 60], [43, 53, 55, 59]] },
        title: t('五度进行里把前一个和弦变成属七', '5 度進行で前のコードを属七に', 'Turn the first chord of a fifth into a dominant'),
        steps: [
          t('以五度进行的两个和弦，可以把第一个换成同根音的属七，它就成了第二个和弦的副属和弦。C 调 I–vi–ii–V 里的 Am 可以换成 A7。听。', '5 度で進む 2 つのコードでは、前を同じ根音の属七にでき、後ろの副属になる。C の I–vi–ii–V の Am を A7 に。聴いて。', 'In a fifth progression, make the first chord a dominant seventh on the same root; it becomes the applied dominant of the second. In C, the Am of I–vi–ii–V can become A7. Listen.'),
          t('调式混合：大调借小调，最常见的是 ii∅7 代替 ii7、V7 加 ♭9——两者都是用 le 代替 la。', '同主調借用：長調が短調から借りる。多いのは ii7 の代わりの ii∅7、V7 の ♭9——どちらも la の代わりに le。', 'Mixture borrows from minor; most common are ii∅7 for ii7 and ♭9 on V7 — both substitute le for la.'),
        ] },
      G('secondaryDominant', 3), G('iiVI', 2),
    ]),
    L(t('后门进行', 'バックドア進行', 'The backdoor progression'), [
      { type: 'guide', ref: ['wiki-backdoor', 'wiki-axis-system'], demo: { play: [[53, 56, 60, 63], [46, 56, 58, 62], [48, 52, 55, 59]] },
        title: t('不走正门 V，走后门 ♭VII7', '正面の V ではなく裏口の ♭VII7', 'Not the front door V but the back door ♭VII7'),
        steps: [
          t('后门进行把 V7 – I 换成 iv7 – ♭VII7 – I：C 调里是 Fm7 – B♭7 – C。名字是相对于"正门" ii–V–I 起的。听。', 'バックドアは V7 – I を iv7 – ♭VII7 – I に：C なら Fm7 – B♭7 – C。「正面玄関」の ii–V–I に対する名前。聴いて。', 'The backdoor replaces V7 – I with iv7 – ♭VII7 – I: in C, Fm7 – B♭7 – C — named against the “front door” ii–V–I. Listen.'),
          t('轴心体系的角度：♭VII（B♭）在属轴上（G、E、C♯、B♭），所以它能代替属和弦。', '軸システムで見ると：♭VII（B♭）はドミナント軸（G・E・C♯・B♭）にあるので属和音を代理できる。', 'In axis terms, ♭VII (B♭) lies on the dominant axis (G, E, C♯, B♭), so it can stand in for the dominant.'),
        ] },
      { type: 'choice', ref: 'wiki-backdoor',
        prompt: t('F 调的后门进行是？', 'F のバックドア進行は？', 'The backdoor progression in F is…'),
        options: ['B♭m7 – E♭7 – F', 'Gm7 – C7 – F', 'G♭7 – F'], answer: 0,
        hint: t('iv7 – ♭VII7 – I。', 'iv7 – ♭VII7 – I。', 'iv7 – ♭VII7 – I.'),
        explain: t('F 调 iv = B♭m7，♭VII = E♭7。', 'F の iv = B♭m7、♭VII = E♭7。', 'In F, iv = B♭m7 and ♭VII = E♭7.') },
      { type: 'choice', ref: 'wiki-axis-system',
        prompt: t('后门进行的 ♭VII7 为什么能代替属和弦？（按轴心体系）', 'なぜ ♭VII7 は属和音を代理できる？（軸システム）', 'Why can the backdoor ♭VII7 replace the dominant (axis system)?'),
        options: [t('♭VII 在属轴上', '♭VII はドミナント軸にある', '♭VII lies on the dominant axis'), t('♭VII 是主和弦', '♭VII は主和音', '♭VII is the tonic'), t('它们音完全一样', '音がまったく同じ', 'they have identical notes')], answer: 0,
        hint: t('C 调属轴：G、E、C♯、B♭。', 'C のドミナント軸：G・E・C♯・B♭。', 'C’s dominant axis: G, E, C♯, B♭.'),
        explain: t('B♭ 和 G 同在属轴上，相隔小三度。', 'B♭ と G は同じドミナント軸で短 3 度離れる。', 'B♭ and G share the dominant axis, a minor third apart.') },
      G('tritoneSub', 2),
    ]),
    L(t('Coltrane 进行', 'コルトレーン・チェンジ', 'Coltrane changes'), [
      { type: 'guide', ref: 'wiki-coltrane', tool: { feature: 'jazzmore' },
        title: t('三个相隔大三度的调中心', '長 3 度ずつ離れた 3 つの調', 'Three key centres a major third apart'),
        steps: [
          t('Coltrane 进行把 C 调的 ii–V–I 展开成：Dm7 E♭7 A♭maj7 B7 Emaj7 G7 Cmaj7——经过 A♭、E、C 三个相隔大三度的调中心。', 'コルトレーン・チェンジは C の ii–V–I を Dm7 E♭7 A♭maj7 B7 Emaj7 G7 Cmaj7 に広げる——長 3 度ずつ離れた A♭・E・C を経由。', 'Coltrane changes expand ii–V–I in C into Dm7 E♭7 A♭maj7 B7 Emaj7 G7 Cmaj7 — passing through A♭, E and C, a major third apart.'),
          t('最有名的例子是 Coltrane 1960 年的《Giant Steps》；他在快速、陌生的调中心之间主要用琶音和音阶片段来即兴。', '最も有名なのは 1960 年の『Giant Steps』。速く珍しい調の移り変わりの中、主にアルペジオと音階の断片で即興した。', 'The best-known example is Coltrane’s “Giant Steps” (1960), where he improvised mainly with arpeggios and scale fragments over the fast, unusual key centres.'),
        ] },
      { type: 'choice', ref: 'wiki-coltrane',
        prompt: t('C 调的 Coltrane 进行经过哪三个调中心？', 'C のコルトレーン・チェンジが経由する 3 つの調は？', 'Which three key centres do Coltrane changes in C pass through?'),
        options: ['A♭, E, C', 'F, G, C', 'D, A, E'], answer: 0,
        hint: t('相隔大三度，把八度平均分成三份。', '長 3 度ずつで、オクターヴを 3 等分。', 'Major thirds apart — dividing the octave in three.'),
        explain: t('A♭maj7、Emaj7、Cmaj7：每两个相隔大三度。', 'A♭maj7・Emaj7・Cmaj7：長 3 度ずつ。', 'A♭maj7, Emaj7, Cmaj7: each a major third apart.') },
      { type: 'fill', ref: 'wiki-coltrane',
        prompt: t('Coltrane 进行：Dm7 E♭7 A♭maj7 ___ Emaj7 G7 Cmaj7', 'コルトレーン：Dm7 E♭7 A♭maj7 ___ Emaj7 G7 Cmaj7', 'Coltrane changes: Dm7 E♭7 A♭maj7 ___ Emaj7 G7 Cmaj7'),
        bank: [opt('B7', 'B7'), opt('Bb7', 'B♭7'), opt('C7', 'C7')], answer: ['B7'],
        hint: t('Emaj7 的属七。', 'Emaj7 の属七。', 'The dominant of Emaj7.'),
        explain: t('B7 → Emaj7：每个新调前都有它的属七。', 'B7 → Emaj7：新しい調の前にはその属七。', 'B7 → Emaj7: each new key is preceded by its dominant.') },
      G('tritoneSub', 2),
    ]),
  ],

  color: [
    L(t('Altered 音阶与 alt 和弦', 'オルタード・スケールと alt コード', 'The altered scale and alt chords'), [
      { type: 'guide', ref: 'wiki-altered-scale', tool: { feature: 'chordsymbols', q: 'G7alt' }, demo: { play: [[55], [56], [58], [59], [61], [63], [65], [67]] },
        title: t('根音、三音、七音之外全是变化音', '根音・3 度・7 度以外はすべて変化音', 'Everything but root, third and seventh is altered'),
        steps: [
          t('Altered 音阶 = 旋律小调第 7 个调式，含有属七的根音、三音、七音和四个变化音：♭9、♯9、♭5（♯11）、♯5（♭13）。', 'オルタード・スケール = 旋律短音階の第 7 旋法。属七の根音・3 度・7 度と 4 つの変化音（♭9・♯9・♭5（♯11）・♯5（♭13））を含む。', 'The altered scale is melodic minor’s mode 7: the dominant’s root, third and seventh plus four alterations — ♭9, ♯9, ♭5 (♯11), ♯5 (♭13).'),
          t('7alt 和弦没有固定的音：从这些变化音里选几个。和弦标记查询每次会随机给出一种排法，可以点"换一组"。', '7alt コードには決まった音がなく、変化音から何個か選ぶ。コード記号検索は毎回ランダムな配置を示し、「別の構成」で変えられる。', 'A 7alt chord has no fixed notes — pick some of these alterations. The Chord Symbols tool shows a random realisation each time, refreshable.'),
        ] },
      G('scaleLibrary', 3, { ids: ['altered_dominant'] }),
    ]),
    L(t('Blackadder 和弦', 'ブラックアダー・コード', 'The Blackadder chord'), [
      { type: 'guide', ref: 'soundquest-blk', tool: { feature: 'chordsymbols', q: 'Cblk' }, demo: { play: [[48, 58, 62, 66]] },
        title: t('增三和弦放在全音之上的低音上', '全音上のベースに増三和音', 'An augmented triad over a bass a whole step below'),
        steps: [
          t('Blackadder 和弦 = 一个增三和弦，下面加一个比增三和弦根音低全音的低音：Cblk = C + B♭ D F♯（B♭aug/C）。听。', 'ブラックアダー = 増三和音 + その根音の全音下のベース：Cblk = C + B♭ D F♯（B♭aug/C）。聴いて。', 'A Blackadder chord = an augmented triad over a bass a whole step below its root: Cblk = C + B♭ D F♯ (B♭aug/C). Listen.'),
          t('它也可以读成 C9(♭5) 省略三音、或 C+6(♯11) 省略三音；音全部来自全音音阶。', 'C9(♭5) の 3 度省略、C+6(♯11) の 3 度省略とも読め、音はすべて全音音階から。', 'It can also be read as C9(♭5) omit 3 or C+6(♯11) omit 3; all its notes come from a whole-tone scale.'),
        ] },
      { type: 'choice', ref: 'soundquest-blk',
        prompt: t('Gblk 由哪些音组成？', 'Gblk の構成音は？', 'Which notes make Gblk?'),
        options: ['G F A C♯', 'G B D F', 'G F♯ A♯ D'], answer: 0,
        hint: t('G 上方的增三和弦根音比 G 高小七度（低全音的八度转位）：F。', 'G の全音下の F が増三和音の根音。', 'The augmented triad’s root is a whole step below G: F.'),
        explain: t('F 增三和弦 F A C♯ 放在 G 上：G F A C♯。', 'F の増三和音 F A C♯ を G の上に：G F A C♯。', 'F augmented (F A C♯) over G: G F A C♯.') },
      { type: 'choice', ref: 'soundquest-blk',
        prompt: t('A♯aug/C 在标准写法里是？', 'A♯aug/C の標準形は？', 'A♯aug/C in standard notation is…'),
        options: ['Cblk', 'A♯blk', 'Caug'], answer: 0,
        hint: t('以低音命名。', 'ベースで名づける。', 'It is named after the bass.'),
        explain: t('A♯ = B♭，B♭aug/C = Cblk。', 'A♯ = B♭、B♭aug/C = Cblk。', 'A♯ = B♭, so B♭aug/C = Cblk.') },
      { type: 'choice', ref: 'soundquest-blk',
        prompt: t('Blackadder 和弦的音都来自哪种音阶？', 'ブラックアダーの音はどの音階から？', 'All Blackadder notes come from which scale?'),
        options: [t('全音音阶', '全音音階', 'the whole-tone scale'), t('大调音阶', '長音階', 'the major scale'), t('布鲁斯音阶', 'ブルース・スケール', 'the blues scale')], answer: 0,
        hint: t('C D F♯ B♭：全是全音和大三度的距离。', 'C D F♯ B♭：全音と長 3 度だけ。', 'C D F♯ B♭: whole steps and major thirds.'),
        explain: t('C D F♯ B♭ 都在 C 全音音阶里。', 'C D F♯ B♭ はすべて C の全音音階。', 'C D F♯ B♭ all belong to the C whole-tone scale.') },
    ]),
    L(t('增三和弦的用法', '増三和音の使い方', 'Uses of the augmented triad'), [
      { type: 'guide', ref: ['wiki-augmented-triad', 'wiki-harmonic-minor'], demo: { play: [[43, 59, 63, 67], [48, 52, 55, 60]] },
        title: t('V+、III+ 与 I+maj7', 'V+・III+・I+maj7', 'V+, III+ and I+maj7'),
        steps: [
          t('增三和弦可以出现在：带小七度的 V（V+7）、代替属和弦的 III+（和声小调里本来就有），以及带大七度的 I（Imaj7♯5）。听：G+ → C。', '増三和音は：短 7 度付きの V（V+7）、ドミナントの代わりの III+（和声短音階に元からある）、長 7 度付きの I（Imaj7♯5）に出てくる。聴いて：G+ → C。', 'Augmented triads appear as V with a minor seventh (V+7), as III+ substituting for the dominant (native to harmonic minor), and as I with a major seventh (Imaj7♯5). Listen: G+ → C.'),
        ] },
      { type: 'choice', ref: 'wiki-harmonic-minor',
        prompt: t('A 和声小调里哪一级是增三和弦？', 'A 和声短音階で増三和音はどの音度？', 'Which degree of A harmonic minor is augmented?'),
        options: ['III+ (C E G♯)', 'V (E G♯ B)', 'VI (F A C)'], answer: 0,
        hint: t('升高的 G♯ 和 C、E 组成。', '上げた G♯ と C・E。', 'The raised G♯ with C and E.'),
        explain: t('C E G♯：两个大三度 = 增三和弦。', 'C E G♯：長 3 度 2 つ = 増三和音。', 'C E G♯: two major thirds = augmented.') },
      G('triadSpell', 2), G('scaleLibrary', 1, { ids: ['lydian_sharp_5', 'ionian_sharp_5'] }),
    ]),
    L(t('特殊和弦综合', '特殊なコードの総合', 'Colour-chord review'), [
      { type: 'guide', ref: ['wiki-altered-scale', 'soundquest-blk'], tool: { feature: 'chordsymbols' },
        title: t('alt、blk、aug', 'alt・blk・aug', 'alt, blk, aug'),
        steps: [
          t('alt：属七加各种变化音，每次可以不同；blk：增三和弦 + 低全音的低音；aug：两个大三度。', 'alt：属七 + 変化音（毎回違ってよい）、blk：増三和音 + 全音下のベース、aug：長 3 度 2 つ。', 'alt: a dominant plus altered tensions, varying each time; blk: an augmented triad over a bass a whole step below; aug: two major thirds.'),
        ] },
      G('scaleLibrary', 2, { ids: ['altered_dominant', 'lydian_sharp_5'] }), G('chordSymbolNotes', 2), G('symmetricScale', 1),
    ]),
  ],

  lcc: [
    L(t('调性顺序：五度一串', '調性の順序：5 度の連なり', 'Tonal order: a chain of fifths'), [
      { type: 'guide', ref: ['aizcutei-lcc', 'george-russell-lcc'], tool: { feature: 'lcc' }, visual: { kind: 'circle', highlight: ['C', 'G', 'D', 'A', 'E', 'B', 'F#'] },
        title: t('I、V、II、VI、III……', 'I・V・II・VI・III……', 'I, V, II, VI, III…'),
        steps: [
          t('从 C 往上叠五度：C、G、D、A、E、B、F♯……这个顺序在 LCC 里叫"调性顺序"（Tonal Order），代表和中心音联系的强弱。和 C 直接联系的是 F♯，所以 LCC 认为 Lydian（用 F♯ 而不是 F）最统一。', 'C から 5 度を積む：C・G・D・A・E・B・F♯……。LCC ではこれを「調性の順序」と呼び、中心音とのつながりの強さを表す。C に直接つながるのは F♯ なので、LCC は（F ではなく F♯ の）リディアンが最も統一的とする。', 'Stack fifths from C: C, G, D, A, E, B, F♯… LCC calls this the tonal order, showing strength of connection to the centre. The note directly linked to C is F♯, so LCC sees Lydian (F♯, not F) as most unified.'),
          t('顺序靠前的叫 ingoing（往里走，比较"安定"），靠后的叫 outgoing（往外走，"脱离"）。', '順序の前のほうを ingoing（内向き、落ち着く）、後ろを outgoing（外向き、離れる）と呼ぶ。', 'Notes early in the order are ingoing (settling); late ones are outgoing (pulling away).'),
        ] },
      { type: 'fill', ref: 'aizcutei-lcc',
        prompt: t('C 的调性顺序：C G D A ___ B', 'C の調性の順序：C G D A ___ B', 'Tonal order from C: C G D A ___ B'),
        bank: [opt('E', 'E'), opt('F', 'F'), opt('Fs', 'F♯')], answer: ['E'],
        hint: t('A 往上五度。', 'A の 5 度上。', 'A fifth above A.'),
        explain: t('C G D A E B F♯……每一步一个纯五度。', 'C G D A E B F♯……1 歩ずつ完全 5 度。', 'C G D A E B F♯… a perfect fifth each step.') },
      { type: 'choice', ref: 'aizcutei-lcc',
        prompt: t('调性顺序里靠后的音被描述为？', '調性の順序で後ろのほうの音は？', 'Notes late in the tonal order are described as…'),
        options: ['outgoing', 'ingoing', 'tonic'], answer: 0,
        hint: t('"走出去"。', '「外へ出る」。', '“Going out”.'),
        explain: t('靠前 ingoing（安定），靠后 outgoing（脱离）。', '前は ingoing（安定）、後ろは outgoing（離脱）。', 'Early = ingoing (settled); late = outgoing (departing).') },
      G('circleStep', 2),
    ]),
    L(t('七个主要音阶', '7 つの主要音階', 'The seven principal scales'), [
      { type: 'guide', ref: 'aizcutei-lcc', tool: { feature: 'lcc' },
        title: t('从 Lydian 长出来的七个音阶', 'リディアンから生まれた 7 つの音階', 'Seven scales grown from Lydian'),
        steps: [
          t('LCC 的七个主要音阶：Lydian、Lydian Augmented、Lydian Diminished、Lydian Flat 7th，以及三个"辅助"音阶 Aux. Augmented、Aux. Diminished、Aux. Diminished Blues。', 'LCC の 7 つの主要音階：リディアン・リディアン・オーギュメント・リディアン・ディミニッシュ・リディアン ♭7、そして補助の 3 つ（Aux. Augmented・Aux. Diminished・Aux. Diminished Blues）。', 'LCC’s seven principal scales: Lydian, Lydian Augmented, Lydian Diminished, Lydian Flat 7th, plus three auxiliaries — Aux. Augmented, Aux. Diminished, Aux. Diminished Blues.'),
          t('那三个辅助音阶其实就是常说的全音音阶、减音阶（W-H）和属减音阶（H-W）。另有四个"水平"音阶：Major、Minor Flat 7th（Mixolydian）、Major Augmented 5th（Ionian ♯5）和 African-American Blues。', '補助の 3 つは一般に全音音階・ディミニッシュ（W-H）・属減音階（H-W）と呼ばれるもの。さらに「水平」の 4 つ：Major・Minor Flat 7th（ミクソリディアン）・Major Augmented 5th（イオニアン ♯5）・African-American Blues。', 'The three auxiliaries are the familiar whole-tone, diminished (W-H) and dominant diminished (H-W) scales. There are also four “horizontal” scales: Major, Minor Flat 7th (Mixolydian), Major Augmented 5th (Ionian ♯5) and African-American Blues.'),
        ] },
      { type: 'match', ref: 'aizcutei-lcc',
        prompt: t('LCC 名称 ↔ 一般名称', 'LCC の名前 ↔ 一般的な名前', 'LCC name ↔ common name'),
        pairs: [['Aux. Augmented', t('全音音阶', '全音音階', 'whole-tone')], ['Aux. Diminished', t('减音阶（W-H）', 'ディミニッシュ（W-H）', 'diminished (W-H)')], ['Aux. Diminished Blues', t('属减音阶（H-W）', '属減音階（H-W）', 'dominant diminished (H-W)')], ['Minor Flat 7th', 'Mixolydian']],
        hint: t('三个 Aux. 都是对称音阶。', 'Aux. の 3 つはどれも対称音階。', 'All three Aux. scales are symmetric.'),
        explain: t('Aux. Augmented = 全音，Aux. Diminished = 减（W-H），Aux. Diminished Blues = 属减（H-W），Minor Flat 7th = Mixolydian。', 'Aux. Augmented = 全音、Aux. Diminished = ディミニッシュ、Aux. Diminished Blues = 属減、Minor Flat 7th = ミクソリディアン。', 'Aux. Augmented = whole-tone, Aux. Diminished = W-H diminished, Aux. Diminished Blues = H-W, Minor Flat 7th = Mixolydian.') },
      { type: 'choice', ref: 'aizcutei-lcc',
        prompt: t('Lydian Augmented 和 Lydian Flat 7th 在旋律小调里分别是第几个调式？', 'リディアン・オーギュメントとリディアン ♭7 は旋律短音階の第何旋法？', 'Lydian Augmented and Lydian Flat 7th are which modes of melodic minor?'),
        options: [t('第 3 和第 4 个', '第 3 と第 4', 'the 3rd and 4th'), t('第 1 和第 2 个', '第 1 と第 2', 'the 1st and 2nd'), t('第 6 和第 7 个', '第 6 と第 7', 'the 6th and 7th')], answer: 0,
        hint: t('Lydian ♯5 和 Lydian dominant。', 'リディアン ♯5 とリディアン・ドミナント。', 'Lydian ♯5 and Lydian dominant.'),
        explain: t('以旋律小调为母音阶时，它们是第 3、4 个调式；LCC 则说它们都来自 Lydian 半音阶。', '旋律短音階を親とすれば第 3・4 旋法。LCC はすべてリディアン・クロマティックから来るとする。', 'With melodic minor as parent they are modes 3 and 4; LCC says all come from the Lydian Chromatic Scale.') },
      G('symmetricScale', 1),
    ]),
    L(t('Lydian 主音', 'リディアン・トニック', 'The Lydian tonic'), [
      { type: 'guide', ref: 'aizcutei-lcc', tool: { feature: 'lcc', q: 'G7' },
        title: t('G7 用 F Lydian', 'G7 には F リディアン', 'G7 takes F Lydian'),
        steps: [
          t('一般理论按调（C 调 → C），和弦—音阶理论按和弦根音（G7 → G Mixolydian）。LCC 都不是：它给每个和弦找一个 Lydian 母音阶，中心叫"Lydian 主音"。', '一般理論は調で（C 調 → C）、コード・スケール理論は根音で（G7 → G ミクソリディアン）。LCC はどちらでもなく、各コードにリディアンの親音階を探し、その中心を「リディアン・トニック」と呼ぶ。', 'General theory goes by key (C), chord–scale theory by root (G7 → G Mixolydian). LCC does neither: it finds a Lydian parent for each chord, whose centre is the Lydian tonic.'),
          t('例：G7 用 F Lydian（全是白键，能对应 G7）；Fmaj7 用 F Lydian，Cmaj7 用 C Lydian。和弦根音到 Lydian 主音的距离叫 Lydian Tonic Interval：G7 的是小七度（或大二度）。', '例：G7 には F リディアン（白鍵だけで G7 に合う）、Fmaj7 は F リディアン、Cmaj7 は C リディアン。根音とリディアン・トニックの間を Lydian Tonic Interval と呼ぶ：G7 は短 7 度（長 2 度）。', 'Example: G7 takes F Lydian (all white keys, fitting G7); Fmaj7 takes F Lydian, Cmaj7 C Lydian. The distance from root to Lydian tonic is the Lydian Tonic Interval: for G7, a minor seventh (or major second).'),
        ] },
      { type: 'choice', ref: 'aizcutei-lcc',
        prompt: t('按 LCC，C 调里的 G7 用哪个 Lydian 音阶？', 'LCC では C の G7 にどのリディアン？', 'In LCC, which Lydian scale fits G7 in C?'),
        options: ['F Lydian', 'G Lydian', 'C Lydian'], answer: 0,
        hint: t('全是白键的 Lydian。', '白鍵だけのリディアン。', 'The all-white-key Lydian.'),
        explain: t('F Lydian = F G A B C D E，正好是白键，能对应 G7。', 'F リディアン = F G A B C D E、白鍵で G7 に合う。', 'F Lydian = F G A B C D E, the white keys, fitting G7.') },
      { type: 'choice', ref: 'aizcutei-lcc',
        prompt: t('Cmaj7 的 Lydian 主音是？', 'Cmaj7 のリディアン・トニックは？', 'What is the Lydian tonic of Cmaj7?'),
        options: ['C', 'F', 'G'], answer: 0,
        hint: t('大七和弦的 Lydian 主音和根音一致。', '長七のリディアン・トニックは根音と同じ。', 'For major sevenths the Lydian tonic equals the root.'),
        explain: t('Cmaj7 用 C Lydian；除了大七和弦，其他和弦的 Lydian 主音都和根音错开。', 'Cmaj7 は C リディアン。長七以外はリディアン・トニックが根音とずれる。', 'Cmaj7 takes C Lydian; for every other chord the Lydian tonic differs from the root.') },
      { type: 'choice', ref: 'aizcutei-lcc',
        prompt: t('G7 的 Lydian Tonic Interval（根音到 Lydian 主音）是？', 'G7 の Lydian Tonic Interval は？', 'G7’s Lydian Tonic Interval is…'),
        options: [t('小七度（或大二度）', '短 7 度（長 2 度）', 'a minor seventh (or major second)'), t('纯五度', '完全 5 度', 'a perfect fifth'), t('同度', '1 度', 'a unison')], answer: 0,
        hint: t('G 到 F。', 'G から F。', 'G to F.'),
        explain: t('G 往上小七度（往下大二度）是 F。', 'G の短 7 度上（長 2 度下）が F。', 'F is a minor seventh above G (a major second below).') },
    ]),
    L(t('LCC 综合', 'LCC の総合', 'LCC review'), [
      { type: 'guide', ref: ['george-russell-lcc', 'aizcutei-lcc'], tool: { feature: 'lcc' },
        title: t('垂直、水平、Lydian 主音', '垂直・水平・リディアン・トニック', 'Vertical, horizontal, Lydian tonic'),
        steps: [
          t('LCC 先建立"垂直"（一个和弦、一个 Lydian 母音阶），再加入"水平"（跨和弦、靠功能走向解决）的视角。', 'LCC はまず「垂直」（1 つのコードに 1 つのリディアン）を作り、そのあと「水平」（コードをまたいで解決へ向かう）の視点を加える。', 'LCC builds the vertical view first (one chord, one Lydian parent) and then adds the horizontal view (across chords, seeking resolution).'),
        ] },
      { type: 'choice', ref: 'george-russell-lcc',
        prompt: t('LCC 一共有多少个 Lydian 半音阶？', 'リディアン・クロマティック・スケールはいくつ？', 'How many Lydian Chromatic Scales are there?'),
        options: ['12', '7', '1'], answer: 0,
        hint: t('五度圈上每个音一个。', '五度圏の各音に 1 つ。', 'One for each note on the circle of fifths.'),
        explain: t('十二平均律里共有 12 个，对应五度圈。', '12 平均律で 12 個、五度圏に対応。', 'Twelve in equal temperament, one per step of the circle.') },
      { type: 'choice', ref: 'aizcutei-lcc',
        prompt: t('Dm7 – G7 – Cmaj7 按 LCC 都可以用哪个 Lydian 来衡量？', 'Dm7 – G7 – Cmaj7 を LCC でまとめて測るリディアンは？', 'In LCC, Dm7 – G7 – Cmaj7 can all be measured against which Lydian?'),
        options: [t('F Lydian（全白键）', 'F リディアン（白鍵）', 'F Lydian (all white keys)'), 'D Lydian', 'G Lydian'], answer: 0,
        hint: t('三个和弦的音都是白键。', '3 つのコードの音はすべて白鍵。', 'All three chords use white keys.'),
        explain: t('F Lydian 包含 C 大调的全部音，可以对应这三个和弦（Cmaj7 也可以单独用 C Lydian）。', 'F リディアンは C 長調の全音を含み、3 つに対応できる（Cmaj7 は C リディアンでも）。', 'F Lydian contains all of C major’s notes and fits all three (Cmaj7 can also take C Lydian).') },
      G('scaleLibrary', 2, { ids: ['lydian', 'lydian_sharp_5', 'lydian_dominant'] }),
    ]),
  ],

  keycenter: [
    L(t('调内和弦找调', '調内のコードから調を探す', 'Finding the key from diatonic chords'), [
      { type: 'guide', ref: 'omt2e-roman-numerals', tool: { feature: 'other' },
        title: t('看大小，找位置', '長短を見て位置を探す', 'Check qualities, find their places'),
        steps: [
          t('大调里 I、IV、V 是大三和弦，ii、iii、vi 是小三和弦，vii° 是减三和弦。一串和弦里，减三和弦、两个相邻的大三和弦（IV、V）都是很好的线索。', '長調では I・IV・V が長、ii・iii・vi が短、vii° が減。減三和音や隣り合う 2 つの長三和音（IV・V）は良い手がかり。', 'In major, I, IV and V are major, ii, iii and vi minor, vii° diminished. A diminished triad, or two adjacent major triads (IV and V), are great clues.'),
        ] },
      G('keyCenter', 5),
    ]),
    L(t('强功能进行', '強い機能進行', 'Strong functional motion'), [
      { type: 'guide', ref: 'omt2e-iivi', tool: { feature: 'other' },
        title: t('属七 + 根音上行四度', '属七 + 根音 4 度上行', 'Dominant seventh + root up a fourth'),
        steps: [
          t('"进行分析"把"属七和弦的根音往上走纯四度"标为强功能进行（Dominant Motion）；只是根音五度关系、但第一个和弦不是属七，就标为下五度进行。', '「進行分析」は「属七の根音が完全 4 度上へ」を強い機能進行（ドミナント・モーション）、根音が 5 度関係でも前が属七でなければ 5 度下行とする。', 'Progression Analysis marks a dominant seventh whose root rises a perfect fourth as strong functional (dominant) motion; fifth-related roots without a dominant seventh are plain falling-fifth motion.'),
        ] },
      G('dominantMotion', 5),
    ]),
    L(t('工具里的三种音阶体系', 'ツールの 3 つの音階体系', 'The tool’s three scale systems'), [
      { type: 'guide', ref: ['wiki-jazz-minor', 'wiki-harmonic-minor', 'omt2e-major-scales'], tool: { feature: 'other' },
        title: t('大调、爵士小调、和声小调', '長調・ジャズ・マイナー・和声短音階', 'Major, jazz minor, harmonic minor'),
        steps: [
          t('"调性中心"会在每个音上试三种音阶：大调、爵士小调（旋律小调上行）、和声小调。和弦音落在音阶里加分，落在外面扣分。', '「調性の中心」は各音で 3 種を試す：長音階・ジャズ・マイナー（旋律短音階上行形）・和声短音階。コード音が入れば加点、外れれば減点。', 'Key Center tries three scales on every note: major, jazz minor (ascending melodic minor) and harmonic minor, adding points for chord tones inside and subtracting for those outside.'),
          t('所以带 G♯ 的 E7 出现在 A 小调的进行里时，和声小调（A B C D E F G♯）会得分更高。', 'だから G♯ を含む E7 が A 短調の進行に出ると、和声短音階（A B C D E F G♯）の点が高くなる。', 'So when E7 (with G♯) appears in an A-minor progression, harmonic minor (A B C D E F G♯) scores higher.'),
        ] },
      { type: 'choice', ref: 'wiki-harmonic-minor',
        prompt: t('Am、Dm、E7、Am 最适合哪种音阶体系？', 'Am・Dm・E7・Am に最も合う音階は？', 'Am, Dm, E7, Am best fit which scale system?'),
        options: [t('A 和声小调', 'A 和声短音階', 'A harmonic minor'), t('C 大调', 'C 長調', 'C major'), t('A 爵士小调', 'A ジャズ・マイナー', 'A jazz minor')], answer: 0,
        hint: t('E7 里有 G♯。', 'E7 には G♯。', 'E7 contains G♯.'),
        explain: t('G♯ 是升高的导音，和声小调里有它，F 也是和声小调的音（爵士小调是 F♯）。', 'G♯ は上げた導音で和声短音階にあり、F も和声短音階の音（ジャズ・マイナーは F♯）。', 'G♯ is the raised leading tone in harmonic minor, and F belongs to it too (jazz minor has F♯).') },
      { type: 'choice', ref: 'wiki-jazz-minor',
        prompt: t('Cm(maj7) 这个和弦，在大调、爵士小调、和声小调里，哪种体系的主和弦是它？', 'Cm(maj7) が主和音になるのは長調・ジャズ・マイナー・和声短音階のどれ？', 'CmMaj7 is the tonic chord of which system(s)?'),
        options: [t('爵士小调和和声小调', 'ジャズ・マイナーと和声短音階', 'jazz minor and harmonic minor'), t('只有大调', '長調だけ', 'major only'), t('都不是', 'どれでもない', 'none')], answer: 0,
        hint: t('小三度 + 大七度。', '短 3 度 + 長 7 度。', 'Minor third + major seventh.'),
        explain: t('两种小调都有 ♭3 和大七度 7，所以主和弦都是小大七和弦。', 'どちらも ♭3 と長 7 度を持ち、主和音は短長七。', 'Both have ♭3 and a major 7, so both tonic chords are minor-major sevenths.') },
      G('keyCenter', 2),
    ]),
    L(t('调性中心综合', '調性の中心の総合', 'Key-centre review'), [
      { type: 'guide', ref: ['omt2e-modulation', 'omt2e-roman-numerals'], tool: { feature: 'other' },
        title: t('线索、证据、打分', '手がかり・証拠・採点', 'Clues, proof, scoring'),
        steps: [
          t('临时记号是线索，终止式是证据，工具的分数是参考：三者结合判断调性中心。', '臨時記号は手がかり、終止形は証拠、ツールの点数は参考。3 つを合わせて調性の中心を判断する。', 'Accidentals are clues, cadences proof, the tool’s score a guide: combine all three.'),
        ] },
      G('keyCenter', 3), G('dominantMotion', 2),
    ]),
  ],

  negharmony: [
    L(t('单音的负和声', '単音のネガティブ', 'Negatives of single notes'), [
      { type: 'guide', ref: 'wiki-negative-harmony', visual: { kind: 'clock', pcs: [0, 7], mirror: 7 }, tool: { feature: 'other' },
        title: t('镜子在主音和属音正中间', '鏡は主音と属音の真ん中', 'The mirror sits midway between tonic and dominant'),
        steps: [
          t('在钟面上把主音和属音的中点连成一条线，每个音都按这条线翻到另一边。C 调：C↔G、D↔F、E↔E♭、A↔B♭、B↔A♭。', '時計で主音と属音の中点を通る線を引き、各音をその線で反対側へ。C：C↔G・D↔F・E↔E♭・A↔B♭・B↔A♭。', 'Draw a line through the tonic–dominant midpoint on the clock and flip each note across it. In C: C↔G, D↔F, E↔E♭, A↔B♭, B↔A♭.'),
        ] },
      G('negative', 5),
    ]),
    L(t('和弦的负和声', '和音のネガティブ', 'Negatives of chords'), [
      { type: 'guide', ref: 'wiki-negative-harmony', visual: { kind: 'clock', pcs: [7, 11, 2, 5], mirror: 7 }, demo: { play: [[55, 59, 62, 65], [48, 52, 55, 60], [50, 53, 56, 60], [48, 52, 55, 60]] },
        title: t('大三变小三，依旧回家', '長は短に、それでも家へ帰る', 'Major turns minor, still heading home'),
        steps: [
          t('在 C 调里：I（C）↔ i（Cm）；IV（F）↔ v（Gm）；V7（G7）↔ Dm7♭5（也就是 Fm6）。', 'C では：I（C）↔ i（Cm）、IV（F）↔ v（Gm）、V7（G7）↔ Dm7♭5（Fm6）。', 'In C: I (C) ↔ i (Cm); IV (F) ↔ v (Gm); V7 (G7) ↔ Dm7♭5 (i.e. Fm6).'),
          t('负和声保留了向主和弦的引力：G7 → C 和它的负版本 Dm7♭5 → C 都会回到家。听：G7 → C，再听 Dm7♭5 → C。', 'ネガティブは主和音への引力を保つ：G7 → C も Dm7♭5 → C も家へ帰る。聴いて：G7 → C、Dm7♭5 → C。', 'Negative harmony keeps the pull home: G7 → C and its negative Dm7♭5 → C both resolve. Listen: G7 → C, then Dm7♭5 → C.'),
        ] },
      { type: 'choice', ref: 'wiki-negative-harmony',
        prompt: t('C 调里 F 大三和弦（F A C）的负和声是？', 'C で F の長三和音（F A C）のネガティブは？', 'In C, the negative of F major (F A C) is…'),
        options: [t('Gm（D B♭ G）', 'Gm（D B♭ G）', 'Gm (D B♭ G)'), t('Fm', 'Fm', 'Fm'), t('Dm', 'Dm', 'Dm')], answer: 0,
        hint: t('F→D、A→B♭、C→G。', 'F→D・A→B♭・C→G。', 'F→D, A→B♭, C→G.'),
        explain: t('D B♭ G 排成 G B♭ D = G 小三和弦。', 'D B♭ G を並べると G B♭ D = G の短三和音。', 'D B♭ G reorders to G B♭ D = G minor.') },
      G('negative', 3),
    ]),
    L(t('负和声从哪里来', 'ネガティブ・ハーモニーの由来', 'Where negative harmony comes from'), [
      { type: 'guide', ref: 'wiki-negative-harmony',
        title: t('从 Zarlino 到 Jacob Collier', 'ツァルリーノからジェイコブ・コリアーまで', 'From Zarlino to Jacob Collier'),
        steps: [
          t('Zarlino（16 世纪）发现：从一个音往上叠大三度和纯五度得到大三和弦，往下叠就得到小三和弦——两者是"极性相反"的。后来 Riemann 发展了"和声二元论"。', 'ツァルリーノ（16 世紀）は、ある音から上に長 3 度と完全 5 度を積むと長三和音、下に積むと短三和音になり、両者は「極性が逆」だと気づいた。のちにリーマンが「和声二元論」へ発展させた。', 'Zarlino (16th century) noticed that stacking a major third and fifth above a note makes a major triad and stacking them below makes a minor triad — polar opposites. Riemann later built harmonic dualism on this.'),
          t('Ernst Levy 把翻转的中心从根音移到了根音和五音的中点（C 调的 E♭ 与 E 之间）。Steve Coleman 起了"负和声"这个名字；Jacob Collier 让它流行，他更在意"顺时针（变格）也能带来回家的感觉"。', 'Ernst Levy は折り返しの中心を根音から根音と 5 度の中点（C なら E♭ と E の間）へ移した。Steve Coleman が「ネガティブ・ハーモニー」と名づけ、Jacob Collier が広めた。コリアーは「時計回り（変格）でも帰ってくる感じが出せる」点に注目した。', 'Ernst Levy moved the centre of reflection from the root to the midpoint of root and fifth (between E♭ and E in C). Steve Coleman named it; Jacob Collier popularised it, focusing on how clockwise (plagal) motion can also feel like coming home.'),
        ] },
      { type: 'match', ref: 'wiki-negative-harmony',
        prompt: t('人物 ↔ 贡献', '人物 ↔ 貢献', 'Person ↔ contribution'),
        pairs: [['Zarlino', t('大小三和弦极性相反', '長短三和音は極性が逆', 'major and minor as polar opposites')], ['Ernst Levy', t('把轴放在根音与五音中点', '軸を根音と 5 度の中点に', 'axis at the root–fifth midpoint')], ['Steve Coleman', t('起名"负和声"', '「ネガティブ・ハーモニー」と命名', 'coined “negative harmony”')], ['Jacob Collier', t('让它广为人知', '広く知らしめた', 'popularised it')]],
        hint: t('Levy 的书里没有"负和声"这个词。', 'Levy の本にこの言葉はない。', 'The term isn’t in Levy’s book.'),
        explain: t('Zarlino 观察，Levy 定轴，Coleman 命名，Collier 推广。', 'ツァルリーノが観察、Levy が軸、Coleman が命名、Collier が普及。', 'Zarlino observed, Levy set the axis, Coleman named it, Collier spread it.') },
      { type: 'choice', ref: 'wiki-negative-harmony',
        prompt: t('Jacob Collier 关心的是，变格进行在五度圈上往哪个方向走、也能带来回家感？', 'コリアーが注目した、変格進行の五度圏上の向きは？', 'Collier notes that plagal motion — moving which way on the circle — can also feel like coming home?'),
        options: [t('顺时针', '時計回り', 'clockwise'), t('逆时针', '反時計回り', 'counterclockwise')], answer: 0,
        hint: t('正格（V–I）是逆时针。', '正格（V–I）は反時計回り。', 'Authentic V–I is counterclockwise.'),
        explain: t('正格终止在五度圈上逆时针，变格（IV–I）是顺时针。', '正格終止は反時計回り、変格（IV–I）は時計回り。', 'Authentic cadences run counterclockwise; plagal (IV–I) runs clockwise.') },
      G('negative', 1),
    ]),
    L(t('负和声综合', 'ネガティブ・ハーモニーの総合', 'Negative-harmony review'), [
      { type: 'guide', ref: 'wiki-negative-harmony', tool: { feature: 'other' },
        title: t('翻转、颜色变、引力不变', '折り返し・色は変わり・引力は残る', 'Flip, colour changes, pull remains'),
        steps: [
          t('负和声工具：输入和弦和"轴"（主音），它会把每个音翻过去。', 'ネガティブ・ツール：コードと「軸」（主音）を入れると各音を折り返す。', 'The negative-harmony tool takes a chord and an axis (the tonic) and flips every note.'),
        ] },
      G('negative', 5),
    ]),
  ],

  guidetone: [
    L(t('导向音练习', 'ガイド・トーンの練習', 'Guide-tone drill'), [
      { type: 'guide', ref: 'omt2e-jazz-voicings', tool: { feature: 'other' },
        title: t('三音 + 七音', '3 度 + 7 度', 'Third + seventh'),
        steps: [
          t('任何七和弦的导向音就是它的三音和七音。', 'どの七の和音もガイド・トーンは 3 度と 7 度。', 'Any seventh chord’s guide tones are its third and seventh.'),
        ] },
      G('guideTones', 5),
    ]),
    L(t('导向音路径', 'ガイド・トーンの道筋', 'Guide-tone paths'), [
      { type: 'guide', ref: 'omt2e-jazz-voicings', tool: { feature: 'other' }, demo: { play: [[65, 72], [65, 71], [64, 71]] },
        title: t('三音 → 七音，七音 → 三音', '3 度 → 7 度、7 度 → 3 度', 'Third → seventh, seventh → third'),
        steps: [
          t('爵士常见的平滑连接：一个和弦的三音连到下一个和弦的七音；另一条线把第一个和弦的九音连到第二个的十三音。', 'ジャズのなめらかな連結：前の 3 度を次の 7 度へ、もう 1 本の線で前の 9 度を次の 13 度へ。', 'A common smooth jazz scheme: the third of one chord leads to the seventh of the next, while another line connects the ninth of the first to the thirteenth of the second.'),
          t('听：Dm7 → G7 → Cmaj7 里，上面两条线 F–F–E、C–B–B。', '聴いて：Dm7 → G7 → Cmaj7 の上の 2 本 F–F–E・C–B–B。', 'Listen: over Dm7 → G7 → Cmaj7, the lines F–F–E and C–B–B.'),
        ] },
      G('guidePath', 3), G('guideTones', 2),
    ]),
    L(t('和弦报告：配置', 'コード・レポート：ヴォイシング', 'Chord report: voicings'), [
      { type: 'guide', ref: ['omt2e-jazz-voicings', 'wiki-voicing'], tool: { feature: 'other' },
        title: t('壳音、drop 2 与伴奏节奏', 'シェル・ドロップ 2・伴奏リズム', 'Shells, drop 2 and comping rhythms'),
        steps: [
          t('和弦报告会给出这个和弦的壳音配置（根音 + 三音 + 七音）和 drop 2 配置，还附上几种伴奏节奏型（如 Charleston、Red Garland、四拍平均）。', 'コード・レポートはシェル（根音 + 3 度 + 7 度）とドロップ 2、さらに伴奏リズム（チャールストン・レッド・ガーランド・4 つ打ち）を示す。', 'The Chord Report gives shell (root + third + seventh) and drop-2 voicings, plus comping rhythms such as Charleston, Red Garland and four-on-the-floor.'),
        ] },
      G('drop2', 3), G('guideTones', 2),
    ]),
    L(t('和弦报告：替代与即兴建议', 'コード・レポート：代理と即興', 'Chord report: substitutes and improvisation'), [
      { type: 'guide', ref: ['omt2e-substitutions', 'omt2e-chord-scale', 'george-russell-lcc'], tool: { feature: 'other' },
        title: t('换什么、弹什么', '何に替え、何を弾く', 'What to swap, what to play'),
        steps: [
          t('报告里的替代和弦包括三全音替代等；即兴建议同时给出和弦—音阶（CST，按亮度排序）和 LCC 的母音阶候选。', 'レポートの代理には裏コードなど、即興の提案はコード・スケール（CST、明るさ順）と LCC の親音階候補を示す。', 'Its substitutes include the tritone sub; its improvisation advice lists chord–scale (CST, ordered by brightness) and LCC parent-scale candidates.'),
        ] },
      G('tritoneSub', 2), G('chordScaleDegree', 2), G('scaleLibrary', 2),
    ]),
  ],
};
