// 乐理闯关 · 节奏、布鲁斯与爵士：每张题卡标出依据（ref），只使用 references.js 中已登记、已核实的资料；解析用尽量通俗的话转述这些资料。
// 依据汇总（由 scripts/annotate-learn.mjs 生成）：
//   ref:omt2e-rhythm-more ref:omt2e-swing ref:wiki-twelve-bar ref:omt2e-blues-scale ref:omt2e-blues-harmony
//   ref:wiki-minor-seventh ref:aizcutei-jazz ref:omt2e-jazz-voicings ref:omt2e-chord-scale ref:omt2e-substitutions
//   ref:omt2e-roman-numerals ref:omt2e-modulation ref:omt2e-iivi ref:wiki-voicing ref:guitar-chord-drop
//   ref:wiki-so-what ref:wiki-upper-structure ref:wiki-jazz-minor ref:wiki-altered-scale ref:wiki-harmonic-minor
//   ref:wiki-harmonic-major ref:wiki-whole-tone ref:wiki-octatonic ref:wiki-neapolitan-scale ref:wiki-double-harmonic
//   ref:wiki-bebop-scale ref:wiki-backdoor ref:wiki-coltrane ref:omt2e-embellishing-chords ref:soundquest-blk
//   ref:omt2e-collections ref:wiki-negative-harmony ref:george-russell-lcc ref:aizcutei-lcc
// @refs-end

const t = (zh, ja, en) => ({ zh, ja, en });
const opt = (id, label) => ({ id, label });

const ALL = [
  {
    id: 'blues', section: 'jazz', feature: 'blues', icon: 'B',
    title: t('十二小节布鲁斯', '12 小節ブルース', 'The 12-bar blues'),
    blurb: t('只用三个和弦', '3 つのコードだけ', 'Just three chords'),
    cards: [
      { type: 'guide', ref: 'wiki-twelve-bar', demo: { play: [[48, 52, 55], [48, 52, 55], [53, 57, 60], [48, 52, 55], [55, 59, 62], [53, 57, 60], [48, 52, 55]] },
        title: t('12 个小节，三个和弦', '12 小節、3 つのコード', 'Twelve bars, three chords'),
        steps: [
          t('最基本的布鲁斯用 I、IV、V 三个和弦，排满 12 个小节。', 'もっとも基本的なブルースは I・IV・V の 3 つで 12 小節を埋めます。', 'The basic blues fills 12 bars with just I, IV and V.'),
          t('基本版：I I I I｜IV IV I I｜V IV I V。听一遍感受一下。', '基本形：I I I I｜IV IV I I｜V IV I V。聴いてみよう。', 'Basic form: I I I I | IV IV I I | V IV I V. Give it a listen.'),
        ] },
      { type: 'fill', ref: 'wiki-twelve-bar',
        prompt: t('基本十二小节：I I I I｜IV IV I I｜___ IV I V', '基本の 12 小節：I I I I｜IV IV I I｜___ IV I V', 'Basic 12-bar: I I I I | IV IV I I | ___ IV I V'),
        bank: [opt('V', 'V'), opt('IV', 'IV'), opt('I', 'I')], answer: ['V'],
        hint: t('最后一行从最"想回家"的和弦开始。', '最後の段は「いちばん帰りたい」和音から。', 'The last line starts on the chord that longs for home.'),
        explain: t('第 9 小节是 V，然后 IV、I，第 12 小节再回到 V 准备下一轮。', '第 9 小節が V、次に IV・I、第 12 小節で V に戻って次の周回へ。', 'Bar 9 is V, then IV, I, and bar 12 returns to V to start again.') },
      { type: 'choice', ref: 'wiki-twelve-bar',
        prompt: t('基本布鲁斯的第 5 小节换到哪个和弦？', '基本ブルースの第 5 小節は？', 'In the basic blues, bar 5 moves to…'),
        options: ['IV', 'V', 'I'], answer: 0,
        hint: t('第二行开头。', '2 段目の頭。', 'The start of the second line.'),
        explain: t('第二行从 IV 开始：IV IV I I。', '2 段目は IV から：IV IV I I。', 'The second line begins on IV: IV IV I I.') },
      { type: 'choice', ref: 'wiki-twelve-bar',
        prompt: t('在 C 调里，这三个和弦是？', 'C の調では 3 つのコードは？', 'In C, the three chords are…'),
        options: ['C F G', 'C D E', 'C E G'], answer: 0,
        hint: t('I、IV、V 就是第 1、4、5 级。', 'I・IV・V は第 1・4・5 音。', 'I, IV, V are degrees 1, 4 and 5.'),
        explain: t('C 大调的第 1、4、5 级是 C、F、G。', 'C 長調の第 1・4・5 音は C・F・G。', 'Degrees 1, 4, 5 of C major are C, F, G.') },
    ],
  },
  {
    id: 'jazz', section: 'jazz', feature: 'cst', icon: 'ii',
    title: t('爵士的 ii–V–I 与调式', 'ジャズの ii–V–I と旋法', 'Jazz ii–V–I and modes'),
    blurb: t('爵士最常见的一句话', 'ジャズでいちばんよく聞くフレーズ', 'Jazz’s most common sentence'),
    cards: [
      { type: 'guide', ref: 'wiki-minor-seventh', demo: { play: [[50, 53, 57, 60], [55, 59, 62, 65], [48, 52, 55, 59]] },
        title: t('二、五、一', '2・5・1', 'Two, five, one'),
        steps: [
          t('C 调的 ii–V–I：Dm7 → G7 → Cmaj7。几乎每首爵士标准曲里都有。', 'C の ii–V–I：Dm7 → G7 → Cmaj7。ほとんどのスタンダードに出てきます。', 'ii–V–I in C: Dm7 → G7 → Cmaj7. It is in almost every jazz standard.'),
          t('ii 是小七和弦，V 是属七和弦，最后落到 I。', 'ii は短七、V は属七、最後に I へ。', 'ii is a minor seventh, V a dominant seventh, landing on I.'),
        ] },
      { type: 'fill', ref: 'wiki-minor-seventh',
        prompt: t('C 调 ii–V–I：Dm7 → ___ → Cmaj7', 'C の ii–V–I：Dm7 → ___ → Cmaj7', 'ii–V–I in C: Dm7 → ___ → Cmaj7'),
        bank: [opt('G7', 'G7'), opt('F7', 'F7'), opt('A7', 'A7')], answer: ['G7'],
        hint: t('C 调的第 5 级是哪个音？', 'C の第 5 音は？', 'What is degree 5 of C?'),
        explain: t('V 是 G，做成属七和弦就是 G7。', 'V は G、属七にすると G7。', 'V is G; as a dominant seventh, G7.') },
      { type: 'choice', ref: 'wiki-minor-seventh',
        prompt: t('ii–V–I 里的 ii 通常是哪种七和弦？', 'ii–V–I の ii はふつう？', 'The ii in a ii–V–I is usually a…'),
        options: ['m7', 'maj7', '7'], answer: 0,
        hint: t('大调第 2 级上的七和弦。', '長調第 2 音の上の七の和音。', 'The seventh chord on degree 2 of a major key.'),
        explain: t('大调的 ii、iii、vi 上都是小七和弦，所以 ii7 是 m7。', '長調の ii・iii・vi は短七。だから ii7 は m7。', 'ii, iii and vi in major are minor sevenths, so ii7 is m7.') },
      { type: 'match', ref: 'aizcutei-jazz',
        prompt: t('大调的调式：第几个 ↔ 名字', '長調の旋法：何番目 ↔ 名前', 'Modes of major: number ↔ name'),
        pairs: [['1', 'Ionian'], ['2', 'Dorian'], ['4', 'Lydian'], ['5', 'Mixolydian']],
        hint: t('顺序：Ionian、Dorian、Phrygian、Lydian、Mixolydian、Aeolian、Locrian。', '順番：Ionian・Dorian・Phrygian・Lydian・Mixolydian・Aeolian・Locrian。', 'Order: Ionian, Dorian, Phrygian, Lydian, Mixolydian, Aeolian, Locrian.'),
        explain: t('从大调的第 1、2、4、5 个音开始，分别是 Ionian、Dorian、Lydian、Mixolydian。', '長調の第 1・2・4・5 音から始めると Ionian・Dorian・Lydian・Mixolydian。', 'Starting on degrees 1, 2, 4, 5 of the major scale gives Ionian, Dorian, Lydian, Mixolydian.') },
      { type: 'choice', ref: 'aizcutei-jazz',
        prompt: t('D Dorian 用的音跟哪个大调一样？', 'D ドリアンの音はどの長調と同じ？', 'D Dorian uses the same notes as which major key?'),
        options: [t('C 大调', 'C 長調', 'C major'), t('D 大调', 'D 長調', 'D major'), t('G 大调', 'G 長調', 'G major')], answer: 0,
        hint: t('Dorian 是大调的第 2 个调式；D 是哪个大调的第 2 个音？', 'ドリアンは長調の第 2 旋法。D は何長調の第 2 音？', 'Dorian is mode 2; D is the second note of which major scale?'),
        explain: t('D 是 C 大调的第 2 个音，所以 D Dorian 就是从 D 开始弹 C 大调的白键。', 'D は C 長調の第 2 音。D ドリアンは D から C 長調の白鍵を弾くこと。', 'D is the 2nd note of C major, so D Dorian is C major’s white keys starting on D.') },
    ],
  },
  {
    id: 'color', section: 'jazz', feature: 'chordsymbols', icon: '✶',
    title: t('特别的和弦：alt 与 Blackadder', '特別な和音：alt とブラックアダー', 'Special chords: alt and Blackadder'),
    blurb: t('紧张、闪亮的声音', '緊張感のある、きらめく響き', 'Tense, sparkling sounds'),
    cards: [
      { type: 'guide', ref: 'wiki-altered-scale', demo: { play: [[48, 52, 58, 61, 63], [48, 58, 62, 66]] },
        title: t('把属和弦拧到最紧', '属和音を極限まで締める', 'Wind the dominant all the way up'),
        steps: [
          t('C7alt：只留下根音、三音和七音，其余的音全部"变化"（升高或降低）。', 'C7alt：根音・3 度・7 度だけ残し、他はすべて「変化」させます（上げるか下げる）。', 'C7alt keeps only root, third and seventh; everything else is altered (raised or lowered).'),
          t('具体加哪几个变化音由演奏者决定——所以 alt 的音不是固定的。', 'どの変化音を加えるかは奏者次第。だから alt の音は固定されていません。', 'Which altered notes to add is the player’s choice — so alt’s notes are not fixed.'),
          t('第二个声音是 Cblk（Blackadder 和弦）：在 C 上面放一个 B♭ 的增三和弦。', '2 つ目は Cblk（ブラックアダー）：C の上に B♭ の増三和音。', 'The second sound is Cblk (Blackadder): a B♭ augmented triad over C.'),
        ] },
      { type: 'choice', ref: 'wiki-altered-scale',
        prompt: t('C7alt 里一定会有的音是？', 'C7alt に必ずある音は？', 'Which notes are always in C7alt?'),
        options: ['C E B♭', 'C G D', 'C E G'], answer: 0,
        hint: t('只有三个"必要"的音不变。', '変えない「必須」の音は 3 つだけ。', 'Only three essential notes stay unaltered.'),
        explain: t('根音 C、大三度 E、小七度 B♭ 一定保留，它们决定了"属七"的身份。', '根音 C・長 3 度 E・短 7 度 B♭ は必ず残り、属七であることを決めています。', 'Root C, major third E and minor seventh B♭ always stay — they define it as a dominant.') },
      { type: 'choice', ref: 'wiki-altered-scale',
        prompt: t('C7alt 里不会出现哪个音？', 'C7alt に出てこない音は？', 'Which note never appears in C7alt?'),
        options: [t('D（自然的九度）', 'D（自然な 9 度）', 'D (the natural 9th)'), 'D♭', 'G♯'], answer: 0,
        hint: t('自然的 9、11、5、13 都被变化掉了。', '自然な 9・11・5・13 はすべて変化させます。', 'Natural 9, 11, 5 and 13 are all altered away.'),
        explain: t('alt 里九度只能是 ♭9（D♭）或 ♯9（D♯），不会用自然的 D。', 'alt の 9 度は ♭9（D♭）か ♯9（D♯）だけで、自然な D は使いません。', 'In alt the ninth is ♭9 (D♭) or ♯9 (D♯) — never natural D.') },
      { type: 'fill', ref: 'soundquest-blk',
        prompt: t('Cblk = ___ 增三和弦放在 C 上', 'Cblk = ___ の増三和音を C の上に', 'Cblk = a ___ augmented triad over C'),
        bank: [opt('Bb', 'B♭'), opt('D', 'D'), opt('E', 'E')], answer: ['Bb'],
        hint: t('增三和弦的根音比低音低一个全音。', '増三和音の根音はベースより全音低い。', 'The augmented triad’s root is a whole step below the bass.'),
        explain: t('Blackadder = 增三和弦 + 比它高一个全音的低音。C 往下全音是 B♭：B♭ D F♯ 放在 C 上。', 'ブラックアダー = 増三和音 + その全音上のベース。C の全音下は B♭：B♭ D F♯ を C の上に。', 'Blackadder = an augmented triad over a bass a whole step above its root. A whole step below C is B♭: B♭ D F♯ over C.') },
      { type: 'choice', ref: ['soundquest-blk', 'omt2e-collections'],
        prompt: t('Blackadder 的音全部来自哪种音阶？', 'ブラックアダーの音はどの音階から？', 'All of the Blackadder’s notes come from which scale?'),
        options: [t('全音音阶', '全音音階', 'the whole-tone scale'), t('大调音阶', '長音階', 'the major scale'), t('五声音阶', '五声音階', 'the pentatonic')], answer: 0,
        hint: t('C D F♯ B♭：相邻的都差全音吗？', 'C D F♯ B♭：隣同士が全音？', 'C D F♯ B♭ — are neighbours whole steps apart?'),
        explain: t('它的四个音都在全音音阶里，所以听起来很紧张、像悬在空中。', '4 つの音はすべて全音音階の中。だから緊張感があり宙に浮いたように聞こえます。', 'All four notes belong to the whole-tone scale, which is why it sounds so tense and floating.') },
    ],
  },
  {
    id: 'swing', section: 'jazz', feature: 'rhythm', icon: '3',
    title: t('三连音、切分与摇摆', '3 連符・シンコペーション・スウィング', 'Triplets, syncopation and swing'),
    blurb: t('把一拍分成三份；重音放在"不该"的地方', '1 拍を 3 つに分ける、アクセントを「意外な」場所に', 'Split a beat in three; put accents where you don’t expect them'),
    cards: [
      { type: 'guide', ref: ['omt2e-rhythm-more', 'omt2e-swing'],
        title: t('一拍不一定只能分两半', '1 拍は 2 つに分けるだけじゃない', 'A beat need not split in two'),
        steps: [
          t('单拍子里一拍通常分成两份。把一拍分成三份，就是"三连音"，在音符上方写个 3；它像是从复拍子"借"来的。', '単純拍子では 1 拍はふつう 2 分割。3 つに分けるのが「3 連符」で、上に 3 と書きます。複合拍子から「借りた」分割です。', 'In simple meter a beat usually splits in two. Splitting it in three is a triplet, marked with a 3 — “borrowed” from compound meter.'),
          t('反过来，在复拍子里把一拍分成两份，叫"二连音"，上方写 2。', '逆に複合拍子で 1 拍を 2 つに分けるのが「2 連符」で、上に 2 と書きます。', 'The reverse — two notes in a compound-meter beat — is a duplet, marked with a 2.'),
          t('切分：把重音放在弱拍或拍子之间，可以用连音线、附点、休止符或力度来制造。', 'シンコペーション：弱拍や拍の間にアクセントを置くこと。タイ・付点・休符・強弱で作れます。', 'Syncopation puts accents off the beat, using ties, dots, rests or dynamics.'),
          t('爵士的摇摆八分音符：谱上写成普通八分音符，演奏时前长后短，大约 2:1，像三连音的"长–短"。四拍子里在第 2、4 拍加重音叫"反拍"（backbeat）。', 'ジャズのスウィング 8 分音符：楽譜は普通の 8 分音符でも、前を長く後ろを短く、約 2:1（3 連符の「長–短」）で弾きます。4 拍子の 2・4 拍目のアクセントがバックビート。', 'Jazz swing eighths are written as plain eighths but played long–short, roughly 2:1, like a triplet. Accenting beats 2 and 4 of a four-beat bar is the backbeat.'),
        ] },
      { type: 'choice', ref: 'omt2e-rhythm-more',
        prompt: t('在一拍里平均奏三个音，记谱时上面写什么？', '1 拍に 3 音を均等に入れるとき、上に何と書く？', 'Three even notes in one beat are marked with…'),
        options: ['3', '2', '6'], answer: 0,
        hint: t('名字叫"三连音"。', '名前は「3 連符」。', 'They are called triplets.'),
        explain: t('三连音写 3；复拍子里一拍两个音的二连音写 2。', '3 連符は 3、複合拍子で 1 拍 2 音の 2 連符は 2。', 'Triplets get a 3; duplets in compound meter get a 2.') },
      { type: 'choice', ref: 'omt2e-swing',
        prompt: t('爵士谱上的八分音符通常怎么演奏？', 'ジャズの楽譜の 8 分音符はふつうどう弾く？', 'How are written eighth notes usually played in jazz?'),
        options: [t('前长后短，约 2:1', '前が長く後ろが短い、約 2:1', 'long–short, about 2:1'), t('完全一样长', 'まったく同じ長さ', 'exactly even'), t('前短后长', '前が短く後ろが長い', 'short–long')], answer: 0,
        hint: t('像三连音里的"长–短"。', '3 連符の「長–短」のよう。', 'Like the long–short of a triplet.'),
        explain: t('摇摆八分音符照普通八分音符记谱，乐手自己知道要"摇"起来：第一个大约是第二个的两倍长。', 'スウィングは普通の 8 分音符で書かれ、奏者が自分で揺らします。1 つ目が 2 つ目の約 2 倍。', 'Swing eighths are notated straight and players know to swing them: the first is about twice as long as the second.') },
      { type: 'choice', ref: 'omt2e-swing',
        prompt: t('四拍子里，"反拍"（backbeat）是把重音放在？', '4 拍子のバックビートはどこにアクセント？', 'In four-beat time, the backbeat accents…'),
        options: [t('第 2、4 拍', '2・4 拍目', 'beats 2 and 4'), t('第 1、3 拍', '1・3 拍目', 'beats 1 and 3'), t('只有第 1 拍', '1 拍目だけ', 'only beat 1')], answer: 0,
        hint: t('本来比较弱的那两拍。', '本来弱い 2 つの拍。', 'The two normally weaker beats.'),
        explain: t('重音放在 2、4 拍，打破了"1、3 强"的常规，这也是一种切分。', '2・4 拍目のアクセントは「1・3 が強い」常識を崩すシンコペーションの一種。', 'Accenting 2 and 4 upsets the usual strong 1 and 3 — a kind of syncopation.') },
      { type: 'match', ref: 'omt2e-rhythm-more',
        prompt: t('节奏现象 ↔ 意思', 'リズム ↔ 意味', 'Rhythm term ↔ meaning'),
        pairs: [[t('三连音', '3 連符', 'triplet'), t('单拍子里一拍分三份', '単純拍子で 1 拍を 3 分割', 'three per beat in simple meter')], [t('二连音', '2 連符', 'duplet'), t('复拍子里一拍分两份', '複合拍子で 1 拍を 2 分割', 'two per beat in compound meter')], [t('切分', 'シンコペーション', 'syncopation'), t('重音落在弱拍或拍子之间', 'アクセントが弱拍や拍の間に', 'accents off the beat')]],
        hint: t('三连音和二连音是"借"来的分法。', '3 連符と 2 連符は「借りた」分割。', 'Triplets and duplets are borrowed divisions.'),
        explain: t('三连音从复拍子借三分法，二连音从单拍子借二分法；切分则是重音错位。', '3 連符は複合拍子から、2 連符は単純拍子から分割を借りる。シンコペーションはアクセントのずれ。', 'Triplets borrow compound meter’s three-way split, duplets borrow simple meter’s two-way split; syncopation shifts the accent.') },
    ],
  },
  {
    id: 'bluesscale', section: 'jazz', feature: 'blues', icon: '♭5',
    title: t('布鲁斯音阶与布鲁斯的变体', 'ブルース・スケールとブルースの変化形', 'The blues scale and blues variants'),
    blurb: t('小调与大调布鲁斯音阶；aab 歌词；16 小节与小调布鲁斯', 'マイナー／メジャー・ブルース・スケール、aab の歌詞、16 小節やマイナー・ブルース', 'Minor and major blues scales; aab lyrics; 16-bar and minor blues'),
    cards: [
      { type: 'guide', ref: ['omt2e-blues-scale', 'omt2e-blues-harmony'], demo: { keys: [60, 63, 65, 66, 67, 70], play: [[60], [63], [65], [66], [67], [70], [72]], chord: [48, 52, 55, 58] },
        title: t('五声音阶 + 一个"蓝色"的音', '五音音階 + 「ブルー」な 1 音', 'A pentatonic scale plus one “blue” note'),
        steps: [
          t('布鲁斯音阶 = 小调五声音阶 + 一个半音经过音：do–me–fa–fi–sol–te。C 上就是 C E♭ F F♯ G B♭（点亮的键）。', 'ブルース・スケール = マイナー・ペンタトニック + 半音の経過音：do–me–fa–fi–sol–te。C なら C E♭ F F♯ G B♭（光っている鍵）。', 'The blues scale is a minor pentatonic plus a chromatic passing tone: do–me–fa–fi–sol–te. On C: C E♭ F F♯ G B♭ (the lit keys).'),
          t('把它从第二个音开始转一下，就得到"大调布鲁斯音阶"：do–re–ri–mi–sol–la，C 上是 C D D♯ E G A。', '2 番目の音から回すと「メジャー・ブルース・スケール」：do–re–ri–mi–sol–la、C なら C D D♯ E G A。', 'Rotate it to start on its second note and you get the major blues scale: do–re–ri–mi–sol–la, on C: C D D♯ E G A.'),
          t('布鲁斯歌词常是 aab：第一句唱完重复一次，第三句不一样。旋律里常留空当，让乐器"应答"。', 'ブルースの歌詞はよく aab：1 行目を繰り返し、3 行目が違う。旋律には楽器が「応える」すき間を残します。', 'Blues lyrics are often aab: a line, its repeat, then a contrasting line. Melodies leave gaps for instruments to answer — call and response.'),
          t('标准十二小节布鲁斯里所有和弦都是属七和弦。常见变体有 16 小节布鲁斯、小调布鲁斯和爵士布鲁斯。', '標準の 12 小節ブルースでは和音はすべて属七。よくある変化形は 16 小節ブルース・マイナー・ブルース・ジャズ・ブルース。', 'In a standard 12-bar blues every chord is a dominant seventh. Common variants are the 16-bar blues, minor blues and jazz blues.'),
        ] },
      { type: 'fill', ref: 'omt2e-blues-scale',
        prompt: t('C 布鲁斯音阶：C E♭ F ___ G B♭', 'C ブルース・スケール：C E♭ F ___ G B♭', 'C blues scale: C E♭ F ___ G B♭'),
        bank: [opt('Fs', 'F♯'), opt('E', 'E'), opt('A', 'A')], answer: ['Fs'],
        hint: t('五声音阶之外多出来的那个半音经过音（fi）。', 'ペンタトニックに加わる半音の経過音（fi）。', 'The extra chromatic passing tone (fi).'),
        explain: t('F 和 G 之间插进 F♯，就成了布鲁斯音阶。', 'F と G の間に F♯ を入れるとブルース・スケール。', 'Slip F♯ between F and G and you have the blues scale.') },
      { type: 'choice', ref: 'omt2e-blues-scale', audio: { notes: [60, 62, 63, 64, 67, 69, 72], mode: 'melody' },
        prompt: t('听：C D D♯ E G A，这是？', '聴いて：C D D♯ E G A は？', 'Listen: C D D♯ E G A is the…'),
        options: [t('大调布鲁斯音阶', 'メジャー・ブルース・スケール', 'major blues scale'), t('小调布鲁斯音阶', 'マイナー・ブルース・スケール', 'minor blues scale'), t('大调音阶', '長音階', 'major scale')], answer: 0,
        hint: t('do–re–ri–mi–sol–la。', 'do–re–ri–mi–sol–la。', 'do–re–ri–mi–sol–la.'),
        explain: t('大调五声音阶 + 经过音 ri（D♯）= 大调布鲁斯音阶。', 'メジャー・ペンタトニック + 経過音 ri（D♯）= メジャー・ブルース。', 'Major pentatonic plus the passing tone ri (D♯) = the major blues scale.') },
      { type: 'choice', ref: 'omt2e-blues-scale',
        prompt: t('布鲁斯歌词常见的结构是？', 'ブルースの歌詞でよくある形は？', 'A common blues lyric structure is…'),
        options: ['aab', 'abab', 'abc'], answer: 0,
        hint: t('第一句会再唱一遍。', '1 行目をもう一度歌う。', 'The first line is sung again.'),
        explain: t('a 唱一句，a 重复（有时稍作变化），b 是对比的一句；十二小节的三个四小节乐句正好对上。', 'a、その繰り返しの a、対照的な b。12 小節の 3 つの 4 小節フレーズにぴったり合います。', 'a, a repeated (sometimes altered), then a contrasting b — matching the three four-bar phrases of a 12-bar blues.') },
      { type: 'choice', ref: 'omt2e-blues-harmony',
        prompt: t('标准十二小节布鲁斯里，和弦都是哪一种？', '標準の 12 小節ブルースの和音はどれ？', 'In a standard 12-bar blues, every chord is a…'),
        options: [t('属七和弦', '属七の和音', 'dominant seventh'), t('大七和弦', '長七の和音', 'major seventh'), t('小三和弦', '短三和音', 'minor triad')], answer: 0,
        hint: t('连 I 也是"七"。', 'I までも「7」。', 'Even I gets a 7.'),
        explain: t('布鲁斯里的 I7、IV7、V7 全是属七和弦——这和古典、爵士里属七只出现在 V 上很不一样。', 'ブルースでは I7・IV7・V7 がすべて属七。古典やジャズで属七が主に V だけなのとは大違い。', 'I7, IV7 and V7 are all dominant sevenths — very unlike classical and jazz, where the dominant seventh mostly lives on V.') },
    ],
  },
  {
    id: 'chordscale', section: 'jazz', feature: 'cst', icon: 'Dm13',
    title: t('和弦—音阶：每个和弦配一个音阶', 'コード・スケール：コードごとに音階を', 'Chord–scale: a scale for every chord'),
    blurb: t('十三和弦摊开就是一个调式；按功能选调式', '13 の和音を並べ直すと旋法になる、働きで選ぶ', 'A thirteenth chord spread out is a mode; choose by function'),
    cards: [
      { type: 'guide', ref: 'omt2e-chord-scale', demo: { play: [[50, 53, 57, 60, 64, 67, 71]] },
        title: t('和弦叠高了，就是一个音阶', 'コードを積み上げると音階になる', 'Stack a chord tall and it becomes a scale'),
        steps: [
          t('Dm7 一直往上叠到十三音：D F A C E G B——重新按顺序排，就是 D Dorian。所以在 Dm7 上即兴，可以用 D Dorian 的音。', 'Dm7 を 13 度まで積むと D F A C E G B。並べ直すと D ドリアン。だから Dm7 の上では D ドリアンの音で即興できます。', 'Stack Dm7 up to the thirteenth: D F A C E G B. Reorder it and you have D Dorian — so over Dm7 you can improvise with D Dorian.'),
          t('最常先学的是 ii–V–I：ii7 配 Dorian，V7 配 Mixolydian，Imaj7 配 Ionian。', '最初に学ぶのは ii–V–I：ii7 にドリアン、V7 にミクソリディアン、Imaj7 にイオニアン。', 'Start with ii–V–I: Dorian on ii7, Mixolydian on V7, Ionian on Imaj7.'),
          t('罗马数字对应调式编号：ii 是大调的第 2 个调式（Dorian）。所以同样是小七和弦，ii 用 Dorian、iii 用 Phrygian、vi 用 Aeolian——要按功能挑，不是每个和弦都换一次调。', 'ローマ数字が旋法の番号に対応：ii は長調の第 2 旋法（ドリアン）。同じ m7 でも ii はドリアン、iii はフリジアン、vi はエオリアン。働きで選び、コードごとに転調するわけではありません。', 'Roman numerals map to mode numbers: ii is the 2nd mode (Dorian). So among minor sevenths, ii takes Dorian, iii Phrygian, vi Aeolian — choose by function; the key doesn’t change with every chord.'),
          t('即兴时把和弦音放在正拍上，旋律就能"说出"和弦；其他音当经过音或延伸音。', '即興では正拍にコード音を置くと旋律がコードを示せます。ほかの音は経過音やテンションとして。', 'Put chord tones on the downbeats and the melody implies the chord; the other notes act as passing tones or extensions.'),
        ] },
      { type: 'fill', ref: 'omt2e-chord-scale',
        prompt: t('C 调 ii–V–I：Dm7 配 ___，G7 配 ___，Cmaj7 配 Ionian', 'C の ii–V–I：Dm7 に ___、G7 に ___、Cmaj7 にイオニアン', 'ii–V–I in C: Dm7 takes ___, G7 takes ___, Cmaj7 takes Ionian'),
        bank: [opt('dor', 'Dorian'), opt('mix', 'Mixolydian'), opt('lyd', 'Lydian'), opt('aeo', 'Aeolian')], answer: ['dor', 'mix'],
        hint: t('D 开始的白键音阶、G 开始的白键音阶。', 'D からの白鍵、G からの白鍵。', 'The white-key scales from D and from G.'),
        explain: t('都还是 C 大调的七个音，只是从各自的根音开始：D Dorian、G Mixolydian、C Ionian。', 'どれも C 長調の 7 音で、根音から始めるだけ：D ドリアン・G ミクソリディアン・C イオニアン。', 'All seven notes of C major, started from each root: D Dorian, G Mixolydian, C Ionian.') },
      { type: 'match', ref: 'omt2e-chord-scale',
        prompt: t('C 大调里：和弦 ↔ 调式', 'C 長調で：コード ↔ 旋法', 'In C major: chord ↔ mode'),
        pairs: [['Em7 (iii)', 'Phrygian'], ['Fmaj7 (IV)', 'Lydian'], ['Am7 (vi)', 'Aeolian'], ['Bm7b5 (vii)', 'Locrian']],
        hint: t('第几级就用第几个调式。', '何度の和音なら何番目の旋法。', 'Degree number = mode number.'),
        explain: t('iii → 第 3 个调式 Phrygian，IV → Lydian，vi → Aeolian，vii → Locrian。', 'iii → 第 3 旋法フリジアン、IV → リディアン、vi → エオリアン、vii → ロクリアン。', 'iii → 3rd mode Phrygian, IV → Lydian, vi → Aeolian, vii → Locrian.') },
      { type: 'choice', ref: 'omt2e-chord-scale',
        prompt: t('和弦—音阶理论是不是说"每换一个和弦就转一次调"？', 'コード・スケール理論は「コードごとに転調する」という意味？', 'Does chord–scale theory mean the key changes with every chord?'),
        options: [t('不是，调式只是给和弦上色', 'いいえ、旋法はコードの色づけ', 'No — the modes just colour each chord'), t('是的', 'はい', 'Yes')], answer: 0,
        hint: t('《Fly Me to the Moon》开头一串和弦都在 C 调里。', '「Fly Me to the Moon」の冒頭はすべて C の中。', 'The opening of “Fly Me to the Moon” stays in C throughout.'),
        explain: t('这些调式不是新的调中心；用罗马数字分清功能，选出的调式才贴合原调。', '旋法は新しい調の中心ではありません。ローマ数字で働きを見分けると、原調に合った旋法を選べます。', 'The modes aren’t new key centres; reading the Roman numerals keeps the choices in the home key.') },
      { type: 'choice', ref: 'omt2e-chord-scale',
        prompt: t('用调式即兴时，正拍上最好放什么音？', '旋法で即興するとき、正拍に置くとよいのは？', 'Improvising with a mode, what belongs on the downbeats?'),
        options: [t('和弦音', 'コード音', 'chord tones'), t('避免音', 'アヴォイド・ノート', 'avoid notes'), t('随便', '何でも', 'anything')], answer: 0,
        hint: t('让旋律"说出"现在是什么和弦。', '旋律で今のコードを示す。', 'Let the melody spell the current chord.'),
        explain: t('把七音调式看成"四个和弦音 + 三个经过音或延伸音"，正拍放和弦音。', '7 音の旋法を「コード音 4 + 経過音・テンション 3」と考え、正拍にコード音を。', 'Think of the mode as four chord tones plus three passing tones or extensions, with chord tones on the downbeats.') },
    ],
  },
  {
    id: 'melodicminor', section: 'jazz', feature: 'ref', icon: 'alt',
    title: t('旋律小调的七个调式', '旋律短音階の 7 つの旋法', 'The seven modes of melodic minor'),
    blurb: t('爵士小调、Lydian dominant、Altered……', 'ジャズ・マイナー・リディアン・ドミナント・オルタード……', 'Jazz minor, Lydian dominant, altered…'),
    cards: [
      { type: 'guide', ref: ['wiki-jazz-minor', 'wiki-altered-scale'], demo: { keys: [60, 62, 63, 65, 67, 69, 71], play: [[60], [62], [63], [65], [67], [69], [71], [72]], chord: [48, 51, 55, 59] },
        title: t('大调只改一个音，又能生出七个调式', '長音階を 1 音変えるだけで、また 7 つの旋法', 'Change one note of major and seven new modes appear'),
        steps: [
          t('爵士小调（旋律小调上行）= 大调把第三音降低：1 2 ♭3 4 5 6 7，台阶 W H W W W W H。C 上是 C D E♭ F G A B。', 'ジャズ・マイナー（旋律短音階の上行形）= 長音階の第 3 音を下げたもの：1 2 ♭3 4 5 6 7、W H W W W W H。C なら C D E♭ F G A B。', 'Jazz minor (ascending melodic minor) = major with a lowered third: 1 2 ♭3 4 5 6 7, W H W W W W H. On C: C D E♭ F G A B.'),
          t('像大调一样，从它的每个音开始都得到一个调式，名字是借大调调式改出来的：第 2 个 Dorian ♭2（Phrygian ♮6），第 3 个 Lydian augmented（Lydian ♯5），第 4 个 Lydian dominant（又叫 Acoustic 音阶），第 5 个 Mixolydian ♭6（Aeolian dominant），第 6 个 Locrian ♮2（Half-diminished），第 7 个 Altered（Super Locrian）。', '長音階と同じく各音から旋法ができ、名前は長音階の旋法を変えたもの：第 2 ドリアン ♭2（フリジアン ♮6）、第 3 リディアン・オーギュメント（リディアン ♯5）、第 4 リディアン・ドミナント（アコースティック・スケール）、第 5 ミクソリディアン ♭6（エオリアン・ドミナント）、第 6 ロクリアン ♮2（ハーフ・ディミニッシュ）、第 7 オルタード（スーパー・ロクリアン）。', 'Like major, each note starts a mode, named by tweaking the major modes: 2nd Dorian ♭2 (Phrygian ♮6), 3rd Lydian augmented (Lydian ♯5), 4th Lydian dominant (the acoustic scale), 5th Mixolydian ♭6 (Aeolian dominant), 6th Locrian ♮2 (half-diminished), 7th altered (Super Locrian).'),
          t('它适合放在小大七和弦（如 CmMaj7）上。', 'マイナー・メジャー・セブンス（CmMaj7 など）に合います。', 'It fits a minor-major seventh chord such as CmMaj7.'),
          t('窍门：要给一个属七和弦找"变化音"，就用比它根音高半音的爵士小调——G7 用 A♭ 爵士小调，也就是 G Altered。', 'コツ：属七にオルタード・テンションが欲しいときは、根音の半音上のジャズ・マイナーを使う。G7 には A♭ ジャズ・マイナー、つまり G オルタード。', 'Trick: for altered tensions on a dominant seventh, use the jazz minor a half step above its root — over G7, A♭ jazz minor, i.e. G altered.'),
        ] },
      { type: 'fill', ref: 'wiki-jazz-minor',
        prompt: t('C 爵士小调：C D ___ F G A ___', 'C ジャズ・マイナー：C D ___ F G A ___', 'C jazz minor: C D ___ F G A ___'),
        bank: [opt('Eb', 'E♭'), opt('E', 'E'), opt('B', 'B'), opt('Bb', 'B♭')], answer: ['Eb', 'B'],
        hint: t('大调只降低第三音，第七音保持。', '長音階の第 3 音だけを下げ、第 7 音はそのまま。', 'Lower only the third; keep the seventh.'),
        explain: t('C D E♭ F G A B：小三度 + 大七度，这就是它和自然小调（B♭）的区别。', 'C D E♭ F G A B：短 3 度 + 長 7 度。自然短音階（B♭）との違いです。', 'C D E♭ F G A B: minor third plus major seventh — that is how it differs from natural minor (B♭).') },
      { type: 'match', ref: 'wiki-jazz-minor',
        prompt: t('从第几个音开始 ↔ 调式名', '何番目から ↔ 旋法名', 'Starting degree ↔ mode name'),
        pairs: [[t('第 3 个音', '第 3 音', '3rd note'), 'Lydian augmented'], [t('第 4 个音', '第 4 音', '4th note'), 'Lydian dominant'], [t('第 6 个音', '第 6 音', '6th note'), 'Locrian ♮2'], [t('第 7 个音', '第 7 音', '7th note'), 'Altered']],
        hint: t('最后一个就是"变化属音阶"。', '最後がオルタード。', 'The last one is the altered scale.'),
        explain: t('Ⅲ Lydian augmented、Ⅳ Lydian dominant、Ⅵ Locrian ♮2、Ⅶ Altered。', 'Ⅲ リディアン・オーギュメント、Ⅳ リディアン・ドミナント、Ⅵ ロクリアン ♮2、Ⅶ オルタード。', 'III Lydian augmented, IV Lydian dominant, VI Locrian ♮2, VII altered.') },
      { type: 'choice', ref: 'wiki-jazz-minor',
        prompt: t('C Lydian dominant 的音是？', 'C リディアン・ドミナントの音は？', 'C Lydian dominant is…'),
        options: ['C D E F♯ G A B♭', 'C D E F G A B♭', 'C D E F♯ G A B'], answer: 0,
        hint: t('名字说了两件事：Lydian（升 4）+ dominant（降 7）。', '名前が 2 つを示す：リディアン（♯4）+ ドミナント（♭7）。', 'The name says two things: Lydian (♯4) + dominant (♭7).'),
        explain: t('大调 + 升 4 + 降 7 = C D E F♯ G A B♭，它是 G 爵士小调的第 4 个调式。', '長音階 + ♯4 + ♭7 = C D E F♯ G A B♭。G ジャズ・マイナーの第 4 旋法です。', 'Major + ♯4 + ♭7 = C D E F♯ G A B♭ — the 4th mode of G jazz minor.') },
      { type: 'choice', ref: ['wiki-jazz-minor', 'wiki-altered-scale'],
        prompt: t('想在 G7 上用 Altered 音阶，应该弹哪个爵士小调？', 'G7 でオルタードを使うなら、どのジャズ・マイナー？', 'To play altered over G7, which jazz minor do you use?'),
        options: [t('A♭ 爵士小调', 'A♭ ジャズ・マイナー', 'A♭ jazz minor'), t('G 爵士小调', 'G ジャズ・マイナー', 'G jazz minor'), t('C 爵士小调', 'C ジャズ・マイナー', 'C jazz minor')], answer: 0,
        hint: t('比属七的根音高半音。', '属七の根音の半音上。', 'A half step above the dominant’s root.'),
        explain: t('A♭ 爵士小调里有 G7 的根音、三音、七音，加上最常见的四个变化音；从 G 开始弹就是 G Altered。', 'A♭ ジャズ・マイナーには G7 の根音・3 度・7 度とよく使う 4 つの変化音があり、G から弾けば G オルタード。', 'A♭ jazz minor holds G7’s root, third and seventh plus its four common alterations; start it on G and it is G altered.') },
      { type: 'choice', ref: 'wiki-jazz-minor', audio: { notes: [60, 62, 64, 66, 68, 69, 71, 72], mode: 'melody' },
        prompt: t('听：C D E F♯ G♯ A B，这是？', '聴いて：C D E F♯ G♯ A B は？', 'Listen: C D E F♯ G♯ A B is…'),
        options: ['Lydian augmented', 'Lydian', 'Altered'], answer: 0,
        hint: t('Lydian（升 4）再加一个升 5。', 'リディアン（♯4）にさらに ♯5。', 'Lydian (♯4) plus a ♯5.'),
        explain: t('Lydian ♯5 = Lydian augmented，是 A 爵士小调的第 3 个调式。', 'リディアン ♯5 = リディアン・オーギュメント、A ジャズ・マイナーの第 3 旋法。', 'Lydian ♯5 = Lydian augmented, the 3rd mode of A jazz minor.') },
    ],
  },
  {
    id: 'harmonicminor', section: 'jazz', feature: 'ref', icon: '♯2',
    title: t('和声小调、和声大调的调式', '和声短音階・和声長音階の旋法', 'Modes of harmonic minor and harmonic major'),
    blurb: t('Phrygian dominant、Lydian ♯2、Dorian ♯4……以及和声大调', 'フリジアン・ドミナント・リディアン ♯2・ドリアン ♯4……と和声長音階', 'Phrygian dominant, Lydian ♯2, Dorian ♯4… and harmonic major'),
    cards: [
      { type: 'guide', ref: ['wiki-harmonic-minor', 'wiki-harmonic-major'], demo: { keys: [57, 59, 60, 62, 64, 65, 68, 69], play: [[57], [59], [60], [62], [64], [65], [68], [69]], chord: [45, 48, 52, 56] },
        title: t('一个"增二度"带来的异国味道', '1 つの「増 2 度」がもたらす異国の香り', 'One augmented second, a whole new flavour'),
        steps: [
          t('和声小调 = 自然小调把第七音升高：1 2 ♭3 4 5 ♭6 7。第 6、7 音之间出现一个"增二度"（三个半音）。', '和声短音階 = 自然短音階の第 7 音を上げたもの：1 2 ♭3 4 5 ♭6 7。第 6・7 音の間に増 2 度（半音 3 つ）。', 'Harmonic minor = natural minor with a raised 7th: 1 2 ♭3 4 5 ♭6 7, leaving an augmented second (three half steps) between 6 and 7.'),
          t('它最常用在 V7 上：除了让 V 变成大三和弦，还带来 ♭9、♯5 这些紧张的音。', 'いちばんの使いどころは V7：V を長三和音にするだけでなく、♭9 や ♯5 の緊張音も加わります。', 'Its main use is over V7: besides making V major, it adds tense notes like ♭9 and ♯5.'),
          t('它的七个调式：1 和声小调（Aeolian ♮7）、2 Locrian ♮6、3 Ionian ♯5、4 Dorian ♯4（Ukrainian Dorian）、5 Phrygian dominant（Hijaz、Freygish）、6 Lydian ♯2、7 Super-Locrian 𝄫7。', '7 つの旋法：1 和声短音階（エオリアン ♮7）、2 ロクリアン ♮6、3 イオニアン ♯5、4 ドリアン ♯4（ウクライナ・ドリアン）、5 フリジアン・ドミナント（ヒジャーズ、フライギッシュ）、6 リディアン ♯2、7 スーパー・ロクリアン 𝄫7。', 'Its seven modes: 1 harmonic minor (Aeolian ♮7), 2 Locrian ♮6, 3 Ionian ♯5, 4 Dorian ♯4 (Ukrainian Dorian), 5 Phrygian dominant (Hijaz, Freygish), 6 Lydian ♯2, 7 Super-Locrian 𝄫7.'),
          t('和声大调 = 大调把第六音降低：1 2 3 4 5 ♭6 7；也可以看成和声小调把三音升高。它的上半段（四音列）和和声小调一样。', '和声長音階 = 長音階の第 6 音を下げたもの：1 2 3 4 5 ♭6 7。和声短音階の第 3 音を上げたものとも言えます。上半分（テトラコード）は和声短音階と同じ。', 'Harmonic major = major with a lowered 6th: 1 2 3 4 5 ♭6 7 — or harmonic minor with a raised third. Its upper tetrachord matches harmonic minor.'),
        ] },
      { type: 'choice', ref: 'wiki-harmonic-minor',
        prompt: t('和声小调哪两个音之间是增二度？', '和声短音階で増 2 度があるのはどこ？', 'Where is the augmented second in harmonic minor?'),
        options: [t('第 6 和第 7 音之间', '第 6 音と第 7 音の間', 'between the 6th and 7th notes'), t('第 2 和第 3 音之间', '第 2 音と第 3 音の間', 'between the 2nd and 3rd'), t('第 4 和第 5 音之间', '第 4 音と第 5 音の間', 'between the 4th and 5th')], answer: 0,
        hint: t('A 和声小调：F → G♯。', 'A 和声短音階：F → G♯。', 'A harmonic minor: F → G♯.'),
        explain: t('♭6 到升高的 7，中间隔了三个半音，就是增二度。', '♭6 から上げた 7 までが半音 3 つ、つまり増 2 度。', 'From ♭6 up to the raised 7 is three half steps — an augmented second.') },
      { type: 'match', ref: 'wiki-harmonic-minor',
        prompt: t('和声小调：第几个调式 ↔ 名字', '和声短音階：第何旋法 ↔ 名前', 'Harmonic minor: mode number ↔ name'),
        pairs: [['2', 'Locrian ♮6'], ['3', 'Ionian ♯5'], ['5', 'Phrygian dominant'], ['6', 'Lydian ♯2']],
        hint: t('第 5 个调式是在属音上开始的，所以带"dominant"。', '第 5 旋法は属音から始まるので「ドミナント」。', 'The 5th mode starts on the dominant — hence “dominant”.'),
        explain: t('2 Locrian ♮6、3 Ionian ♯5、4 Dorian ♯4、5 Phrygian dominant、6 Lydian ♯2、7 Super-Locrian 𝄫7。', '2 ロクリアン ♮6、3 イオニアン ♯5、4 ドリアン ♯4、5 フリジアン・ドミナント、6 リディアン ♯2、7 スーパー・ロクリアン 𝄫7。', '2 Locrian ♮6, 3 Ionian ♯5, 4 Dorian ♯4, 5 Phrygian dominant, 6 Lydian ♯2, 7 Super-Locrian 𝄫7.') },
      { type: 'choice', ref: 'wiki-harmonic-minor', audio: { notes: [64, 65, 68, 69, 71, 72, 74, 76], mode: 'melody' },
        prompt: t('听：E F G♯ A B C D，从 A 和声小调的第 5 个音开始。它叫？', '聴いて：E F G♯ A B C D、A 和声短音階の第 5 音から。名前は？', 'Listen: E F G♯ A B C D, A harmonic minor from its 5th note. It is…'),
        options: ['Phrygian dominant', 'Phrygian', 'Mixolydian'], answer: 0,
        hint: t('像 Phrygian（♭2），但三音是大三度。', 'フリジアン（♭2）のようで、3 度が長 3 度。', 'Like Phrygian (♭2) but with a major third.'),
        explain: t('♭2 + 大三度 + ♭7：Phrygian dominant，也叫 Hijaz。正好配 A 小调的 E7。', '♭2 + 長 3 度 + ♭7：フリジアン・ドミナント（ヒジャーズ）。A 短調の E7 にぴったり。', '♭2 + major third + ♭7: Phrygian dominant, also called Hijaz — a perfect fit for E7 in A minor.') },
      { type: 'fill', ref: 'wiki-harmonic-major',
        prompt: t('C 和声大调：C D E F G ___ B', 'C 和声長音階：C D E F G ___ B', 'C harmonic major: C D E F G ___ B'),
        bank: [opt('Ab', 'A♭'), opt('A', 'A'), opt('Bb', 'B♭')], answer: ['Ab'],
        hint: t('大调只把第六音降低。', '長音階の第 6 音だけを下げる。', 'Major with only the 6th lowered.'),
        explain: t('C D E F G A♭ B：上半段 G A♭ B C 和 C 和声小调一样。', 'C D E F G A♭ B：上半分 G A♭ B C は C 和声短音階と同じ。', 'C D E F G A♭ B: the upper half G A♭ B C matches C harmonic minor.') },
      { type: 'choice', ref: 'wiki-harmonic-minor',
        prompt: t('传统上，和声小调在即兴里主要用在哪个和弦上？', '伝統的に、和声短音階は即興でどのコードに使う？', 'Traditionally, harmonic minor is used mainly over which chord when improvising?'),
        options: ['V7', 'i', 'IV'], answer: 0,
        hint: t('名字里的"和声"来自它能让 V 变成大三和弦。', '「和声」の名は V を長三和音にできることから。', '“Harmonic” because it makes V a major chord.'),
        explain: t('升高的第七音让 V 有了导音；同时还带出 ♭9 和 ♯5，比大调的 V7 更紧张。', '上げた第 7 音で V に導音ができ、♭9・♯5 も加わって長調の V7 より緊張します。', 'The raised 7th gives V its leading tone and brings ♭9 and ♯5 — tenser than a major-key V7.') },
    ],
  },
  {
    id: 'symmetric', section: 'jazz', feature: 'ref', icon: 'W-H',
    title: t('对称音阶：全音音阶与减音阶', '対称音階：全音音階とディミニッシュ', 'Symmetric scales: whole-tone and diminished'),
    blurb: t('一直重复同一种台阶的音阶', '同じ段差を繰り返す音階', 'Scales that repeat one step pattern'),
    cards: [
      { type: 'guide', ref: ['wiki-whole-tone', 'wiki-octatonic'], demo: { play: [[60], [62], [64], [66], [68], [70], [72]], chord: [48, 52, 56, 58] },
        title: t('每一步都一样，就分不出"家"', 'どの段差も同じだと「家」がわからない', 'When every step is the same, there’s no clear home'),
        steps: [
          t('全音音阶：每一步都是全音，一共 6 个音。十二平均律里只有两个不同的全音音阶。听：C D E F♯ G♯ A♯。', '全音音階：すべて全音で 6 音。12 平均律では異なる全音音階は 2 つだけ。聴いて：C D E F♯ G♯ A♯。', 'Whole-tone scale: every step a whole step, six notes. In 12-tone equal temperament there are only two different ones. Listen: C D E F♯ G♯ A♯.'),
          t('它没有导音，在它上面搭的三和弦全是增三和弦（两个相差大二度的增三和弦就凑齐了 6 个音），所以听起来朦胧、没有明确的主音。梅西安称它为第一种"有限移位调式"。', '導音がなく、その上の三和音はすべて増三和音（長 2 度離れた 2 つの増三和音で 6 音そろう）。だからぼんやりして主音がはっきりしません。メシアンの「移調の限られた旋法」第 1 番。', 'It has no leading tone, and every triad on it is augmented (two augmented triads a whole step apart cover all six notes), so it sounds blurry with no clear tonic. Messiaen called it his first mode of limited transposition.'),
          t('减音阶（八声音阶）：全音、半音交替，一共 8 个音。只有三个不同的减音阶。它由两个交错的减七和弦组成。', 'ディミニッシュ・スケール（八音音階）：全音と半音が交互、8 音。異なるものは 3 つだけ。2 つの減七の和音が組み合わさってできています。', 'Diminished (octatonic) scale: whole and half steps alternate, eight notes. There are only three distinct ones, each made of two interlocking diminished seventh chords.'),
          t('它有两种排法：先全后半（W-H），配减七和弦；先半后全（H-W），配属七和弦——本工具里叫"属减音阶"。', '2 つの形：全–半（W-H）は減七に、半–全（H-W）は属七に。本ツールでは後者を「属減音階」と呼びます。', 'Two modes: whole–half (W-H) goes with diminished sevenths; half–whole (H-W) goes with dominant sevenths — the “dominant diminished” scale in this toolbox.'),
        ] },
      { type: 'choice', ref: 'wiki-whole-tone',
        prompt: t('全音音阶有几个音？', '全音音階は何音？', 'How many notes are in a whole-tone scale?'),
        options: ['6', '7', '8'], answer: 0,
        hint: t('12 个半音 ÷ 每步 2 个半音。', '半音 12 ÷ 1 歩につき半音 2。', '12 half steps ÷ 2 per step.'),
        explain: t('12 ÷ 2 = 6，所以全音音阶是六声音阶。', '12 ÷ 2 = 6 で六音音階。', '12 ÷ 2 = 6: a six-note scale.') },
      { type: 'choice', ref: 'wiki-whole-tone',
        prompt: t('在全音音阶的音上搭三和弦，会得到哪种三和弦？', '全音音階の上で三和音を作ると？', 'Triads built from a whole-tone scale are all…'),
        options: [t('增三和弦', '増三和音', 'augmented'), t('大三和弦', '長三和音', 'major'), t('减三和弦', '減三和音', 'diminished')], answer: 0,
        hint: t('全音 + 全音 = 大三度，再叠一个大三度……', '全音 + 全音 = 長 3 度、さらに長 3 度……', 'Whole + whole = a major third; stack another…'),
        explain: t('两个大三度叠在一起就是增三和弦，所以全音音阶里只有增三和弦，听不出明确的主音。', '長 3 度を 2 つ重ねると増三和音。全音音階には増三和音しかなく、主音がはっきりしません。', 'Two stacked major thirds make an augmented triad — that’s all the whole-tone scale offers, so no clear tonic.') },
      { type: 'match', ref: 'wiki-octatonic',
        prompt: t('减音阶的两种排法 ↔ 适合的和弦', 'ディミニッシュの 2 つの形 ↔ 合うコード', 'Two diminished-scale modes ↔ the chord they fit'),
        pairs: [[t('先全后半（W-H）', '全–半（W-H）', 'whole–half (W-H)'), t('减七和弦，如 Edim7', '減七、例 Edim7', 'diminished seventh, e.g. Edim7')], [t('先半后全（H-W）', '半–全（H-W）', 'half–whole (H-W)'), t('属七和弦（属减音阶）', '属七（属減音階）', 'dominant seventh (dominant diminished)')]],
        hint: t('从根音往上第一步是半音的，能含有大三度和小七度。', '根音から最初が半音のほうに長 3 度と短 7 度が入る。', 'The one starting with a half step contains a major third and minor seventh.'),
        explain: t('W-H 配减七和弦；H-W 配属七和弦——C H-W 里有 C E G B♭。', 'W-H は減七、H-W は属七。C の H-W には C E G B♭ がある。', 'W-H with diminished harmony; H-W with dominant — C half–whole contains C E G B♭.') },
      { type: 'fill', ref: 'wiki-octatonic',
        prompt: t('减音阶有 ___ 个音，十二平均律里只有 ___ 个不同的减音阶', 'ディミニッシュは ___ 音、12 平均律で異なるものは ___ つ', 'The diminished scale has ___ notes; there are only ___ distinct ones'),
        bank: [opt('8', '8'), opt('3', '3'), opt('12', '12'), opt('6', '6')], answer: ['8', '3'],
        hint: t('三个减七和弦里任取两个组合。', '3 つの減七から 2 つを選ぶ組み合わせ。', 'Combine any two of the three diminished seventh chords.'),
        explain: t('12 个音分成 3 个减七和弦，任取两个合起来就是一个八声音阶：共 3 种。', '12 音は 3 つの減七に分かれ、2 つを合わせると八音音階：3 通り。', 'The 12 notes split into three diminished sevenths; any two together make an octatonic scale — three in all.') },
      { type: 'choice', ref: 'wiki-whole-tone',
        prompt: t('为什么全音音阶只有两个不同的版本？', '全音音階が 2 種類しかないのはなぜ？', 'Why are there only two different whole-tone scales?'),
        options: [t('它是对称的，往上移全音还是同一组音', '対称なので、全音ずらしても同じ音の集まり', 'It is symmetric: shifting up a whole step gives the same notes'), t('因为它只有 6 个音', '6 音しかないから', 'Because it has only six notes'), t('作曲家规定的', '作曲家が決めた', 'Composers decided so')], answer: 0,
        hint: t('C 全音音阶往上移到 D，音还是那几个。', 'C の全音音階を D に移しても、音は同じ。', 'Move C whole-tone up to D — same notes.'),
        explain: t('只有移半音才会得到新的一组，再移半音又回到原来那组，所以只有两个。这正是"有限移位"的意思。', '半音ずらすと新しい組になり、さらに半音で元に戻るので 2 つだけ。これが「移調の限られた」の意味。', 'Only a half-step shift gives new notes, and another half step returns to the first set — so two. That is what “limited transposition” means.') },
    ],
  },
  {
    id: 'morescales', section: 'jazz', feature: 'ref', icon: '♭2',
    title: t('更多音阶：那不勒斯、双和声、bebop', 'もっと音階：ナポリ・ダブル・ハーモニック・ビバップ', 'More scales: Neapolitan, double harmonic, bebop'),
    blurb: t('和弦音阶速查里剩下的那些音阶', 'コード・スケール早見表に残る音階', 'The remaining scales in the chord–scale reference'),
    cards: [
      { type: 'guide', ref: ['wiki-neapolitan-scale', 'wiki-double-harmonic', 'wiki-bebop-scale'], demo: { play: [[60], [61], [64], [65], [67], [68], [71], [72]], chord: [48, 52, 55, 59] },
        title: t('换掉一两个音，音阶就有了地方色彩', '1、2 音を替えるだけで地方色が出る', 'Swap a note or two and a scale gains local colour'),
        steps: [
          t('那不勒斯音阶两种都有小三度和降低的第二音（♭2）：那不勒斯小调 1 ♭2 ♭3 4 5 ♭6 7（像和声小调降 2），那不勒斯大调 1 ♭2 ♭3 4 5 6 7（像旋律小调降 2）。', 'ナポリ音階はどちらも短 3 度と下げた第 2 音（♭2）：ナポリ短音階 1 ♭2 ♭3 4 5 ♭6 7（和声短音階の ♭2 版）、ナポリ長音階 1 ♭2 ♭3 4 5 6 7（旋律短音階の ♭2 版）。', 'Both Neapolitan scales have a minor third and a lowered 2nd: Neapolitan minor 1 ♭2 ♭3 4 5 ♭6 7 (harmonic minor with ♭2) and Neapolitan major 1 ♭2 ♭3 4 5 6 7 (melodic minor with ♭2).'),
          t('双和声音阶 = 大调把第 2、第 6 音都降低：台阶是 半、增二、半、全、半、增二、半，有两个增二度。它和印度的 Bhairav 音阶同音；本工具里标作"Arabic"。听：C D♭ E F G A♭ B。', 'ダブル・ハーモニック = 長音階の第 2・6 音を下げたもの：半・増 2・半・全・半・増 2・半で増 2 度が 2 つ。インドの Bhairav と同じ音で、本ツールでは「Arabic」。聴いて：C D♭ E F G A♭ B。', 'Double harmonic = major with both 2nd and 6th lowered: half, augmented second, half, whole, half, augmented second, half — two augmented seconds. It matches India’s Bhairav; this toolbox labels it “Arabic”. Listen: C D♭ E F G A♭ B.'),
          t('bebop 音阶：在七声音阶里加一个半音经过音，凑成 8 个音，让八分音符一路走下来时和弦音总落在正拍上。属七 bebop 音阶在 ♭7 和 1 之间加一个音。', 'ビバップ・スケール：7 音音階に半音の経過音を 1 つ加えて 8 音にし、8 分音符で下りるときコード音がいつも正拍に来るようにします。ドミナント・ビバップは ♭7 と 1 の間に 1 音。', 'Bebop scales add one chromatic passing tone to a seven-note scale, making eight, so that running eighth notes keep chord tones on the beats. The dominant bebop scale adds a note between ♭7 and 1.'),
        ] },
      { type: 'match', ref: ['wiki-neapolitan-scale', 'wiki-double-harmonic'],
        prompt: t('音阶 ↔ 组成（以 C 为主音）', '音階 ↔ 構成（C から）', 'Scale ↔ notes (on C)'),
        pairs: [[t('那不勒斯小调', 'ナポリ短音階', 'Neapolitan minor'), 'C D♭ E♭ F G A♭ B'], [t('那不勒斯大调', 'ナポリ長音階', 'Neapolitan major'), 'C D♭ E♭ F G A B'], [t('双和声（Arabic）', 'ダブル・ハーモニック（Arabic）', 'double harmonic (Arabic)'), 'C D♭ E F G A♭ B']],
        hint: t('双和声有大三度 E；两种那不勒斯的差别在第六音。', 'ダブル・ハーモニックは長 3 度 E。ナポリの 2 つは第 6 音が違う。', 'Double harmonic has the major third E; the Neapolitans differ in the 6th.'),
        explain: t('那不勒斯小调 ♭6（A♭），大调 ♮6（A）；双和声是大三度加 ♭2、♭6。', 'ナポリ短は ♭6（A♭）、長は ♮6（A）。ダブル・ハーモニックは長 3 度 + ♭2・♭6。', 'Neapolitan minor has ♭6 (A♭), major has ♮6 (A); double harmonic is a major third with ♭2 and ♭6.') },
      { type: 'choice', ref: 'wiki-neapolitan-scale',
        prompt: t('两种那不勒斯音阶和和声/旋律小调最大的不同是？', 'ナポリ音階と和声／旋律短音階の大きな違いは？', 'What sets the Neapolitan scales apart from harmonic and melodic minor?'),
        options: [t('第二音降低了（♭2）', '第 2 音が下がっている（♭2）', 'a lowered 2nd (♭2)'), t('三音是大三度', '3 度が長 3 度', 'a major third'), t('没有第七音', '第 7 音がない', 'no 7th')], answer: 0,
        hint: t('名字来自"那不勒斯六和弦"建在哪一级上。', '名前は「ナポリの六」がどの音の上にあるかから。', 'Think of which degree the Neapolitan sixth is built on.'),
        explain: t('降低的第二音（也像 Phrygian），所以它们也被叫作"Phrygian 和声小调""Phrygian 旋律小调"。', '下げた第 2 音（フリジアンと同じ）。だから「フリジアン和声短音階」「フリジアン旋律短音階」とも呼ばれます。', 'The lowered 2nd (shared with Phrygian) — hence the names “Phrygian harmonic minor” and “Phrygian melodic minor”.') },
      { type: 'choice', ref: 'wiki-double-harmonic',
        prompt: t('双和声音阶里有几个增二度？', 'ダブル・ハーモニックに増 2 度はいくつ？', 'How many augmented seconds does the double harmonic scale have?'),
        options: ['2', '1', '0'], answer: 0,
        hint: t('看 ♭2 → 3 和 ♭6 → 7。', '♭2 → 3 と ♭6 → 7 を見る。', 'Look at ♭2 → 3 and ♭6 → 7.'),
        explain: t('D♭–E 和 A♭–B 都是三个半音，所以叫"双"和声。', 'D♭–E と A♭–B がどちらも半音 3 つ、だから「ダブル」。', 'D♭–E and A♭–B are both three half steps — hence “double”.') },
      { type: 'choice', ref: 'wiki-bebop-scale',
        prompt: t('bebop 音阶为什么要多加一个经过音？', 'ビバップ・スケールはなぜ経過音を足す？', 'Why does a bebop scale add a passing tone?'),
        options: [t('让和弦音在八分音符里一直落在正拍', '8 分音符でコード音を正拍に保つため', 'to keep chord tones on the beats in running eighths'), t('让音阶变成 12 个音', '12 音にするため', 'to make it twelve notes'), t('为了避开根音', '根音を避けるため', 'to avoid the root')], answer: 0,
        hint: t('7 个音配 8 个八分音符会错位。', '7 音を 8 分音符 8 つに並べるとずれる。', 'Seven notes against eight eighths drift off the beat.'),
        explain: t('加一个音凑成 8 个，一小节的八分音符正好走完一个八度，和弦音一直在正拍上。', '8 音にすれば 1 小節の 8 分音符でちょうど 1 オクターヴ、コード音がいつも正拍に。', 'With eight notes a bar of eighths spans exactly an octave and the chord tones stay on the beats.') },
      { type: 'choice', ref: 'wiki-bebop-scale',
        prompt: t('C 属七 bebop 音阶是在 Mixolydian 里哪里加音？', 'C ドミナント・ビバップはミクソリディアンのどこに音を足す？', 'Where does the C dominant bebop scale add its note to Mixolydian?'),
        options: [t('B♭ 和 C 之间（加 B）', 'B♭ と C の間（B を足す）', 'between B♭ and C (adding B)'), t('E 和 F 之间', 'E と F の間', 'between E and F'), t('G 和 A 之间', 'G と A の間', 'between G and A')], answer: 0,
        hint: t('在 ♭7 和根音之间。', '♭7 と根音の間。', 'Between ♭7 and the root.'),
        explain: t('C D E F G A B♭ B：多了 B，下行时 C、B♭、G、E 这些和弦音就能落在正拍上。', 'C D E F G A B♭ B：B が加わり、下行で C・B♭・G・E などのコード音が正拍に来ます。', 'C D E F G A B♭ B: with the extra B, chord tones like C, B♭, G and E land on the beats going down.') },
    ],
  },
  {
    id: 'jazzvoicing', section: 'jazz', feature: 'jazzmore', icon: 'Dr2',
    title: t('爵士和弦配置', 'ジャズのヴォイシング', 'Jazz voicings'),
    blurb: t('壳音、Drop 2 / Drop 3、So What、高结构三和弦', 'シェル・ドロップ 2／3・ソー・ホワット・アッパー・ストラクチャー', 'Shells, drop 2 / drop 3, So What and upper structures'),
    cards: [
      { type: 'guide', ref: ['omt2e-jazz-voicings', 'wiki-voicing', 'guitar-chord-drop', 'wiki-so-what', 'wiki-upper-structure'], demo: { play: [[48, 52, 58], [48, 58, 64], [52, 57, 62, 67, 71]] },
        title: t('爵士钢琴不会把和弦从下往上叠满', 'ジャズ・ピアノはコードを下から全部積まない', 'Jazz pianists don’t stack every chord tone in thirds'),
        steps: [
          t('最关键的是三音和七音（它们决定和弦性质），五音几乎都可以省掉。只留根音、三音、七音的配置常叫"壳音"。听：C E B♭ 与 C B♭ E。', '大事なのは 3 度と 7 度（性質を決める）で、5 度はほとんど省けます。根音・3 度・7 度だけのものを「シェル」と呼びます。聴いて：C E B♭ と C B♭ E。', 'The key notes are the third and seventh (they define the quality); the fifth can almost always go. Root–third–seventh voicings are called shells. Listen: C E B♭ and C B♭ E.'),
          t('Drop 2：把紧密排列里从上往下数第二个音降低八度；Drop 3：降低第三个音。这样音域拉开，吉他也好按。', 'ドロップ 2：密集配置の上から 2 番目の音をオクターヴ下げる。ドロップ 3：3 番目を下げる。音域が広がり、ギターでも押さえやすい。', 'Drop 2 lowers the second note from the top of a close voicing by an octave; drop 3 lowers the third. The spread is wider and easier on guitar.'),
          t('So What 和弦：自下而上三个纯四度，再加一个大三度，当作小十一和弦（1 4 ♭7 ♭3 5）。听：E A D G B。', 'ソー・ホワット・コード：下から完全 4 度を 3 つ、上に長 3 度。マイナー・イレブンス（1 4 ♭7 ♭3 5）として使います。聴いて：E A D G B。', 'The So What chord: three perfect fourths topped by a major third, used as a minor eleventh (1 4 ♭7 ♭3 5). Listen: E A D G B.'),
          t('高结构三和弦：左手弹三音和七音（三全音），右手弹一个三和弦，组成带延伸音的属和弦。', 'アッパー・ストラクチャー：左手で 3 度と 7 度（三全音）、右手で三和音を弾き、テンション付きの属和音を作ります。', 'Upper-structure triads: the left hand plays the third and seventh (a tritone), the right hand a triad, giving a dominant chord with tensions.'),
        ] },
      { type: 'choice', ref: 'omt2e-jazz-voicings',
        prompt: t('爵士配置里，哪个音几乎总可以省掉？', 'ジャズのヴォイシングでほぼいつも省ける音は？', 'Which chord tone can almost always be left out in jazz voicings?'),
        options: [t('五音', '5 度', 'the fifth'), t('三音', '3 度', 'the third'), t('七音', '7 度', 'the seventh')], answer: 0,
        hint: t('决定大小和"七"的那两个音要留下。', '長短と「7」を決める 2 音は残す。', 'Keep the two notes that define major/minor and the seventh.'),
        explain: t('三音和七音决定和弦性质，五音最"可有可无"；要重复的话通常重复低音或根音。', '3 度と 7 度が性質を決め、5 度はなくてもよい。重複するならふつうベースか根音。', 'Third and seventh define the quality; the fifth is the most dispensable. If you double, usually double the bass or root.') },
      { type: 'choice', ref: 'wiki-voicing',
        prompt: t('Cmaj7 紧密排列 C E G B，做 Drop 2 要动哪个音？', 'Cmaj7 の密集配置 C E G B をドロップ 2 にするには？', 'Cmaj7 in close position is C E G B. For drop 2, which note moves?'),
        options: [t('G 降低八度', 'G をオクターヴ下げる', 'G drops an octave'), t('B 降低八度', 'B をオクターヴ下げる', 'B drops an octave'), t('E 降低八度', 'E をオクターヴ下げる', 'E drops an octave')], answer: 0,
        hint: t('从上往下数第二个。', '上から 2 番目。', 'Second from the top.'),
        explain: t('从上数：B、G、E、C——第二个是 G，降八度后变成 G C E B。', '上から B・G・E・C、2 番目の G を下げて G C E B。', 'From the top: B, G, E, C — the second is G, giving G C E B.') },
      { type: 'match', ref: ['guitar-chord-drop', 'wiki-so-what', 'wiki-upper-structure', 'omt2e-jazz-voicings'],
        prompt: t('配置 ↔ 做法', 'ヴォイシング ↔ 作り方', 'Voicing ↔ recipe'),
        pairs: [['Drop 3', t('从上数第三个音降八度', '上から 3 番目をオクターヴ下げる', 'drop the third note from the top an octave')], ['So What', t('三个纯四度 + 一个大三度', '完全 4 度 3 つ + 長 3 度', 'three perfect fourths + a major third')], [t('高结构三和弦', 'アッパー・ストラクチャー', 'upper structure'), t('左手三全音，右手三和弦', '左手に三全音、右手に三和音', 'tritone in the left hand, triad in the right')], [t('壳音', 'シェル', 'shell'), t('根音 + 三音 + 七音', '根音 + 3 度 + 7 度', 'root + third + seventh')]],
        hint: t('So What 来自 Miles Davis 的同名曲。', 'ソー・ホワットはマイルス・デイヴィスの同名曲から。', 'So What is named after the Miles Davis tune.'),
        explain: t('Drop 3 拉开第三个音；So What 叠四度；高结构是两只手各管一层；壳音只留骨架。', 'ドロップ 3 は 3 番目を下げる、ソー・ホワットは 4 度堆積、アッパー・ストラクチャーは両手で 2 層、シェルは骨組みだけ。', 'Drop 3 spreads the third voice; So What stacks fourths; upper structures split two layers between the hands; shells keep the skeleton.') },
      { type: 'choice', ref: 'omt2e-jazz-voicings',
        prompt: t('爵士里常见的平滑连接：一个和弦的三音，常常走到下一个和弦的？', 'ジャズのなめらかな連結：前のコードの 3 度はよく次のコードの何へ？', 'A common smooth jazz connection: the third of one chord moves to the next chord’s…'),
        options: [t('七音', '7 度', 'seventh'), t('根音', '根音', 'root'), t('五音', '5 度', 'fifth')], answer: 0,
        hint: t('Dm7 的三音 F → G7 的 F。', 'Dm7 の 3 度 F → G7 の F。', 'Dm7’s third F → G7’s F.'),
        explain: t('五度进行里，三音常常不动或只挪一点就成了下一个和弦的七音——"懒"一点的声部进行最顺。', '5 度進行では、3 度がほとんど動かずに次のコードの 7 度になります。「怠けた」声部進行がいちばんなめらか。', 'In fifth-based progressions the third barely moves to become the next seventh — “lazy” voice leading sounds smoothest.') },
    ],
  },
  {
    id: 'substitutions', section: 'jazz', feature: 'jazzmore', icon: '♭II7',
    title: t('和弦替代与重配', 'コードの代理とリハーモナイズ', 'Substitutions and reharmonisation'),
    blurb: t('三全音替代、副属、借用、后门进行、Coltrane 进行', '裏コード・副属・借用・バックドア・コルトレーン・チェンジ', 'Tritone subs, applied chords, mixture, backdoor and Coltrane changes'),
    cards: [
      { type: 'guide', ref: ['omt2e-substitutions', 'omt2e-iivi', 'wiki-backdoor', 'wiki-coltrane', 'omt2e-embellishing-chords'], demo: { play: [[50, 53, 57, 60], [49, 53, 56, 59], [48, 52, 55, 59]] },
        title: t('同一首歌，换一套和弦', '同じ曲に別のコードを', 'Same tune, new chords'),
        steps: [
          t('小调的 ii–V–i 是 ∅7 – 7 – m7（如 Dm7♭5 G7 Cm7），大调是 m7 – 7 – maj7。', '短調の ii–V–i は ∅7 – 7 – m7（Dm7♭5 G7 Cm7 など）、長調は m7 – 7 – maj7。', 'Minor ii–V–i is ∅7 – 7 – m7 (e.g. Dm7♭5 G7 Cm7); major is m7 – 7 – maj7.'),
          t('三全音替代：把属七和弦换成相隔三全音的另一个属七和弦。两者共享同一个三全音（G7 的 B–F 就是 D♭7 的 F–C♭）。听：Dm7 – D♭7 – Cmaj7。', '裏コード：属七を三全音離れた属七に置き換える。両者は同じ三全音を共有（G7 の B–F = D♭7 の F–C♭）。聴いて：Dm7 – D♭7 – Cmaj7。', 'Tritone substitution swaps a dominant seventh for the one a tritone away; both share the same tritone (G7’s B–F is D♭7’s F–C♭). Listen: Dm7 – D♭7 – Cmaj7.'),
          t('副属替代：五度进行中，可以把前一个和弦换成同根音的属七和弦。借用：大调里借小调的音，最常见的是用 ii∅7 代替 ii7，以及在 V7 上加 ♭9。', '副属：5 度進行で前のコードを同じ根音の属七に。借用：長調で短調の音を借りる。多いのは ii7 の代わりの ii∅7、V7 に ♭9 を足すこと。', 'Applied-chord substitution: in a fifth progression, make the first chord a dominant seventh on the same root. Mixture borrows minor’s notes in major — most often ii∅7 for ii7, and ♭9 on V7.'),
          t('后门进行：用 iv7 – ♭VII7 – I 代替 V7 – I（和"正门" ii–V–I 相对）。Coltrane 进行：把 C 调的 ii–V–I 展开成 Dm7 E♭7 A♭maj7 B7 Emaj7 G7 Cmaj7。', 'バックドア：V7 – I を iv7 – ♭VII7 – I に（「正面玄関」ii–V–I に対して）。コルトレーン・チェンジ：C の ii–V–I を Dm7 E♭7 A♭maj7 B7 Emaj7 G7 Cmaj7 に展開。', 'The backdoor replaces V7 – I with iv7 – ♭VII7 – I (versus the “front door” ii–V–I). Coltrane changes expand ii–V–I in C into Dm7 E♭7 A♭maj7 B7 Emaj7 G7 Cmaj7.'),
        ] },
      { type: 'choice', ref: 'omt2e-substitutions',
        prompt: t('G7 的三全音替代是？', 'G7 の裏コードは？', 'The tritone substitute for G7 is…'),
        options: ['D♭7', 'D7', 'C♯m7'], answer: 0,
        hint: t('从 G 往上或往下数三个全音。', 'G から全音 3 つ上（または下）。', 'Three whole steps from G.'),
        explain: t('G–D♭ 是三全音。两个和弦共享 B（C♭）和 F 这对三全音，所以可以互换。', 'G–D♭ が三全音。B（C♭）と F の三全音を共有するので交換できます。', 'G–D♭ is a tritone; both chords share the tritone B (C♭)–F, so they can trade places.') },
      { type: 'fill', ref: 'omt2e-iivi',
        prompt: t('C 小调 ii–V–i：___ G7 Cm7', 'C 短調の ii–V–i：___ G7 Cm7', 'ii–V–i in C minor: ___ G7 Cm7'),
        bank: [opt('dm7b5', 'Dm7♭5'), opt('dm7', 'Dm7'), opt('d7', 'D7')], answer: ['dm7b5'],
        hint: t('小调 ii 是半减七和弦。', '短調の ii は半減七。', 'Minor’s ii is half-diminished.'),
        explain: t('小调里 ii 是 ∅7：D F A♭ C = Dm7♭5。', '短調の ii は ∅7：D F A♭ C = Dm7♭5。', 'In minor, ii is ∅7: D F A♭ C = Dm7♭5.') },
      { type: 'match', ref: ['omt2e-substitutions', 'wiki-backdoor', 'wiki-coltrane'],
        prompt: t('技巧 ↔ C 调里的例子', 'テクニック ↔ C での例', 'Technique ↔ example in C'),
        pairs: [[t('三全音替代', '裏コード', 'tritone sub'), 'Dm7 – D♭7 – Cmaj7'], [t('后门进行', 'バックドア', 'backdoor'), 'Fm7 – B♭7 – Cmaj7'], [t('借用', '借用', 'mixture'), 'Dm7♭5 – G7♭9 – Cmaj7'], ['Coltrane', 'Dm7 E♭7 A♭maj7 B7 Emaj7 G7 Cmaj7']],
        hint: t('后门 = iv7 – ♭VII7 – I。', 'バックドア = iv7 – ♭VII7 – I。', 'Backdoor = iv7 – ♭VII7 – I.'),
        explain: t('D♭7 替 G7；Fm7–B♭7 是后门；Dm7♭5 和 ♭9 是从小调借来的；Coltrane 进行经过 A♭ 和 E 两个调中心。', 'D♭7 が G7 の代わり、Fm7–B♭7 がバックドア、Dm7♭5 と ♭9 は短調から借用、コルトレーンは A♭ と E を経由。', 'D♭7 replaces G7; Fm7–B♭7 is the backdoor; Dm7♭5 and ♭9 are borrowed from minor; Coltrane changes pass through A♭ and E.') },
      { type: 'choice', ref: 'omt2e-substitutions',
        prompt: t('C 调里，在 Dm7 – G7 前面，把 Am7 换成 A7，这是哪种替代？', 'C で Dm7 – G7 の前の Am7 を A7 にするのは？', 'In C, changing the Am7 before Dm7 – G7 into A7 is which substitution?'),
        options: [t('副属替代（A7 = V7/ii）', '副属（A7 = V7/ii）', 'an applied chord (A7 = V7/ii)'), t('三全音替代', '裏コード', 'a tritone sub'), t('后门进行', 'バックドア', 'a backdoor progression')], answer: 0,
        hint: t('A 到 D 是五度进行，把前一个变成属七。', 'A → D は 5 度進行、前を属七に。', 'A → D moves by fifth; make the first chord dominant.'),
        explain: t('同根音换成属七，它就成了下一个和弦（Dm7）的副属和弦。', '同じ根音の属七にすると、次のコード（Dm7）の副属になります。', 'Same root, now a dominant seventh: it becomes the applied dominant of the next chord (Dm7).') },
      { type: 'choice', ref: 'omt2e-embellishing-chords',
        prompt: t('在一个属七和弦前面加上它上方五度的 m7 和弦，会形成什么效果？', '属七の前に、その 5 度上の m7 を置くとどうなる？', 'Putting the m7 chord a fifth above in front of a dominant seventh creates…'),
        options: [t('一个小的 ii–V', '小さな ii–V', 'a little ii–V'), t('一个终止式 I', '終止の I', 'a cadence on I'), t('一个四六和弦', '四六の和音', 'a 6/4 chord')], answer: 0,
        hint: t('E7 前面加 Bm7。', 'E7 の前に Bm7。', 'Bm7 before E7.'),
        explain: t('Bm7 – E7 就是 E7 的 ii–V：附加的 ii 和弦可以用来装饰任何属和弦。', 'Bm7 – E7 は E7 の ii–V。付加された ii はどの属和音でも飾れます。', 'Bm7 – E7 is a ii–V onto E7: an applied ii can decorate any dominant chord.') },
    ],
  },
  {
    id: 'lcc', section: 'jazz', feature: 'lcc', icon: 'Lyd',
    title: t('LCC：利迪亚半音概念', 'LCC：リディアン・クロマティック・コンセプト', 'LCC: the Lydian Chromatic Concept'),
    blurb: t('George Russell 用五度叠出来的"家"', 'ジョージ・ラッセルが 5 度で積んだ「家」', 'George Russell’s “home” built from fifths'),
    cards: [
      { type: 'guide', ref: ['george-russell-lcc', 'omt2e-chord-scale', 'aizcutei-lcc'], demo: { play: [[48], [55], [62], [69], [76], [83], [90]] },
        title: t('把纯五度叠起来，就是 Lydian', '完全 5 度を積むとリディアン', 'Stack perfect fifths and you get Lydian'),
        steps: [
          t('LCC 是 George Russell 在 1953 年首次出版的理论（全名 Lydian Chromatic Concept of Tonal Organization）。', 'LCC はジョージ・ラッセルが 1953 年に初めて出版した理論（正式名 Lydian Chromatic Concept of Tonal Organization）。', 'LCC is George Russell’s theory, first published in 1953 (full name: the Lydian Chromatic Concept of Tonal Organization).'),
          t('它的出发点是"Lydian 音阶"：七个音，彼此相隔六个纯五度。从 C 叠：C G D A E B F♯——排起来就是 C Lydian。听：从 C 往上一路叠五度。', '出発点は「リディアン音階」：完全 5 度で 6 回つながる 7 音。C から：C G D A E B F♯、並べると C リディアン。聴いて：C から 5 度を積み上げる。', 'Its starting point is the Lydian scale: seven notes, six perfect fifths apart. From C: C G D A E B F♯ — reordered, C Lydian. Listen: fifths stacked up from C.'),
          t('Russell 认为音之间有一种"调性引力"，中心是"Lydian 主音"。他说 Lydian 音阶是"垂直"的、完整的状态；大调依赖属—主这样的功能和声，是"水平"的、寻求解决的状态。', 'ラッセルは音に「調性の引力」があり、その中心が「リディアン・トニック」だと考えました。リディアンは「垂直」で完結した状態、属–主の機能和声に頼る長音階は「水平」で解決を求める状態。', 'Russell describes a “tonal gravity” centred on the Lydian tonic. The Lydian scale is vertical — a state of being; the major scale, relying on dominant–tonic function, is horizontal — a state of becoming.'),
          t('扩展到十二个音就是"Lydian 半音阶"，十二平均律里一共 12 个（对应五度圈）。它的"和弦—音阶统一"思想深刻影响了调式爵士，后来的和弦—音阶理论也以它为基础。', '12 音に広げたのが「リディアン・クロマティック・スケール」で、12 平均律に 12 個（五度圏に対応）。「コードとスケールの統一」という考えはモード・ジャズに大きな影響を与え、のちのコード・スケール理論の土台にもなりました。', 'Expanded to twelve notes it becomes the Lydian Chromatic Scale — twelve of them in equal temperament, one per step of the circle of fifths. Its chord–scale unity shaped modal jazz, and chord–scale theory is built on it.'),
        ] },
      { type: 'fill', ref: 'george-russell-lcc',
        prompt: t('Lydian 音阶：___ 个音，彼此一共相隔 ___ 个纯五度', 'リディアン音階：___ 音、完全 5 度で ___ 回つながる', 'The Lydian scale: ___ notes, linked by ___ perfect fifths'),
        bank: [opt('7', '7'), opt('6', '6'), opt('5', '5'), opt('12', '12')], answer: ['7', '6'],
        hint: t('C G D A E B F♯，数一数音和间隔。', 'C G D A E B F♯ の音と間を数える。', 'Count the notes and gaps in C G D A E B F♯.'),
        explain: t('7 个音之间有 6 个五度间隔。', '7 音の間に 5 度の間隔が 6 つ。', 'Seven notes have six fifths between them.') },
      { type: 'choice', ref: 'george-russell-lcc',
        prompt: t('从 C 叠六个纯五度得到的音，排成音阶是？', 'C から完全 5 度を 6 回積んだ音を並べると？', 'Six perfect fifths stacked from C, put in scale order, give…'),
        options: ['C Lydian', 'C Ionian', 'G Mixolydian'], answer: 0,
        hint: t('最后一个音是 F♯。', '最後の音は F♯。', 'The last note is F♯.'),
        explain: t('C D E F♯ G A B：大调升高第 4 音 = Lydian。', 'C D E F♯ G A B：長音階の第 4 音を上げた = リディアン。', 'C D E F♯ G A B: major with a raised 4th = Lydian.') },
      { type: 'match', ref: 'george-russell-lcc',
        prompt: t('LCC 的说法 ↔ 意思', 'LCC の用語 ↔ 意味', 'LCC term ↔ meaning'),
        pairs: [[t('垂直', '垂直', 'vertical'), t('Lydian：完整的状态', 'リディアン：完結した状態', 'Lydian: a state of being')], [t('水平', '水平', 'horizontal'), t('大调：靠属—主寻求解决', '長音階：属–主で解決を求める', 'major: seeks resolution via dominant–tonic')], [t('Lydian 主音', 'リディアン・トニック', 'Lydian tonic'), t('调性引力的中心', '調性の引力の中心', 'the centre of tonal gravity')]],
        hint: t('"水平"跟着功能和声往前走。', '「水平」は機能和声で前へ進む。', '“Horizontal” moves forward through functional harmony.'),
        explain: t('垂直 = 存在（Lydian），水平 = 变成（大调的功能进行），中心是 Lydian 主音。', '垂直 = 存在（リディアン）、水平 = 生成（長音階の機能進行）、中心はリディアン・トニック。', 'Vertical = being (Lydian), horizontal = becoming (major’s functional motion), centred on the Lydian tonic.') },
      { type: 'choice', ref: ['george-russell-lcc', 'omt2e-chord-scale'],
        prompt: t('LCC 对爵士最大的影响是？', 'LCC がジャズに与えた最大の影響は？', 'LCC’s biggest influence on jazz was…'),
        options: [t('推动了调式爵士与和弦—音阶思想', 'モード・ジャズとコード・スケールの考え方', 'modal jazz and chord–scale thinking'), t('发明了十二小节布鲁斯', '12 小節ブルースの発明', 'inventing the 12-bar blues'), t('发明了摇摆节奏', 'スウィングの発明', 'inventing swing')], answer: 0,
        hint: t('它的核心口号是"和弦与音阶统一"。', '中心の考えは「コードとスケールの統一」。', 'Its core idea is chord–scale unity.'),
        explain: t('和弦—音阶统一的思想开启了调式爵士时期；Berklee 等学校教的和弦—音阶理论也基于 LCC。', 'コードとスケールの統一がモード・ジャズの時代を開き、バークリーなどで教えるコード・スケール理論も LCC に基づきます。', 'Chord–scale unity ushered in modal jazz, and the chord–scale theory taught at Berklee and elsewhere is based on LCC.') },
    ],
  },
  {
    id: 'keycenter', section: 'jazz', feature: 'other', icon: 'Key',
    title: t('调性中心与进行分析', '調性の中心と進行分析', 'Key centre and progression analysis'),
    blurb: t('一串和弦属于哪个调？哪里是强功能进行？', 'コード進行はどの調？強い機能進行はどこ？', 'Which key do these chords belong to? Where is the strong functional motion?'),
    cards: [
      { type: 'guide', ref: ['omt2e-roman-numerals', 'omt2e-modulation', 'omt2e-iivi'], tool: { feature: 'other' },
        title: t('先看和弦音落在哪个音阶里', 'まずコード音がどの音階に入るか', 'First see which scale the chord tones fit'),
        steps: [
          t('"调性中心"工具把每个和弦的音和各个调的音阶比一比：音落在音阶里就加分，落在外面就扣分，分数最高的调最可能是中心。它会试大调、爵士小调和和声小调三种音阶。', '「調性の中心」ツールは各コードの音を各調の音階と比べる：音階内なら加点、外なら減点し、最高点の調が中心の候補。長音階・ジャズ・マイナー・和声短音階の 3 種で試す。', 'The Key Center tool compares each chord’s notes with every key’s scale: notes inside score points, notes outside lose points, and the top key is the likely centre. It tries major, jazz minor and harmonic minor.'),
          t('乐理上判断调：反复出现的同一个临时记号是线索，终止式才真正确立一个调。', '理論的には、同じ臨時記号の繰り返しが手がかりで、終止形が調を確立する。', 'In theory, a recurring accidental is a clue, and a cadence is what establishes a key.'),
          t('"进行分析"找的是五度根音进行：属七和弦的根音往上走纯四度（G7 → C）标为强功能进行；不是属七的五度进行（Dm7 → G7）则标为普通的下五度进行。', '「進行分析」は 5 度の根音進行を探す：属七の根音が完全 4 度上へ（G7 → C）なら強い機能進行、属七でない 5 度進行（Dm7 → G7）は普通の 5 度下行。', 'Progression Analysis looks for fifth-related roots: a dominant seventh whose root rises a fourth (G7 → C) is strong functional motion; other falling-fifth moves (Dm7 → G7) are plain falling-fifth motion.'),
        ] },
      { type: 'choice', ref: 'omt2e-roman-numerals', tool: { feature: 'other' },
        prompt: t('Dm7、G7、Cmaj7、Am7 全部属于哪个大调？', 'Dm7・G7・Cmaj7・Am7 がすべて入る長調は？', 'Dm7, G7, Cmaj7 and Am7 all belong to which major key?'),
        options: ['C', 'G', 'F'], answer: 0,
        hint: t('它们是 ii、V、I、vi。', 'ii・V・I・vi。', 'They are ii, V, I and vi.'),
        explain: t('都是 C 大调的顺阶七和弦：ii7、V7、Imaj7、vi7。', 'すべて C 長調の七の和音：ii7・V7・Imaj7・vi7。', 'All are diatonic sevenths of C major: ii7, V7, Imaj7, vi7.') },
      { type: 'choice', ref: 'omt2e-iivi',
        prompt: t('"进行分析"会把哪一对标为强功能进行？', '「進行分析」が強い機能進行とするのは？', 'Which pair does Progression Analysis mark as strong functional motion?'),
        options: ['G7 → Cmaj7', 'Dm7 → G7', 'Cmaj7 → Fmaj7'], answer: 0,
        hint: t('属七 + 根音上行四度。', '属七 + 根音 4 度上行。', 'Dominant seventh + root up a fourth.'),
        explain: t('G7 是属七，根音 G → C 上行四度；Dm7 → G7 根音也是四度，但 Dm7 不是属七。', 'G7 は属七で G → C は 4 度上。Dm7 → G7 も 4 度だが Dm7 は属七でない。', 'G7 is a dominant seventh rising a fourth to C; Dm7 → G7 also rises a fourth, but Dm7 is not a dominant.') },
      { type: 'choice', ref: 'omt2e-modulation',
        prompt: t('分析时，什么最能证明音乐真的转到了新调？', '本当に新しい調へ移ったと示すいちばんの証拠は？', 'What best proves the music has really moved to a new key?'),
        options: [t('在新调上出现终止式', '新しい調で終止形が出る', 'a cadence in the new key'), t('出现一个临时记号', '臨時記号が 1 つ出る', 'a single accidental'), t('速度变快', '速くなる', 'a faster tempo')], answer: 0,
        hint: t('终止式确立调性。', '終止形が調を確立する。', 'Cadences establish keys.'),
        explain: t('临时记号只是线索，终止式才确立新调。', '臨時記号は手がかりで、終止形が新しい調を確立する。', 'Accidentals are clues; cadences establish the new key.') },
      { type: 'choice', ref: 'omt2e-roman-numerals',
        prompt: t('Em、A7、D、Bm 最可能是哪个大调？', 'Em・A7・D・Bm はどの長調らしい？', 'Em, A7, D, Bm most likely belong to which major key?'),
        options: ['D', 'A', 'G'], answer: 0,
        hint: t('A7 是谁的 V7？', 'A7 は何の V7？', 'A7 is V7 of which key?'),
        explain: t('D 大调：ii（Em）、V7（A7）、I（D）、vi（Bm）。', 'D 長調：ii（Em）・V7（A7）・I（D）・vi（Bm）。', 'D major: ii (Em), V7 (A7), I (D), vi (Bm).') },
    ],
  },
  {
    id: 'negharmony', section: 'jazz', feature: 'other', icon: '⇄',
    title: t('负和声：照镜子的和声', 'ネガティブ・ハーモニー：鏡の和声', 'Negative harmony: harmony in a mirror'),
    blurb: t('以主音和属音的中点为轴翻转每个音', '主音と属音の中点を軸に各音を折り返す', 'Flip every note across the tonic–dominant midpoint'),
    cards: [
      { type: 'guide', ref: 'wiki-negative-harmony', visual: { kind: 'clock', pcs: [0, 4, 7], mirror: 7 }, tool: { feature: 'other' }, demo: { play: [[60, 64, 67], [60, 63, 67]] },
        title: t('一面放在 E♭ 和 E 之间的镜子', 'E♭ と E の間に置いた鏡', 'A mirror between E♭ and E'),
        steps: [
          t('负和声：每个音（以及每个音程、和弦）都有一个"负"的对应，做法是以主音和属音中间的轴翻过去。C 调的轴在 E♭ 和 E 之间。', 'ネガティブ・ハーモニー：各音（音程・和音も）に「負」の相手があり、主音と属音の中間の軸で折り返して得る。C の軸は E♭ と E の間。', 'In negative harmony every note (and so every interval and chord) has a “negative” counterpart, found by reflecting across an axis between tonic and dominant — between E♭ and E in C.'),
          t('翻过去以后：C ↔ G、E ↔ E♭；大三和弦变成小三和弦（C E G → C E♭ G），上行变成下行。听：C，再听它的负和声 Cm。', '折り返すと C ↔ G、E ↔ E♭。長三和音は短三和音に（C E G → C E♭ G）、上行は下行に。聴いて：C、そのネガティブの Cm。', 'Reflected: C ↔ G, E ↔ E♭; major chords become minor (C E G → C E♭ G) and rising lines fall. Listen: C, then its negative, Cm.'),
          t('想法来自 Ernst Levy 的"极性理论"（《A Theory of Harmony》），"负和声"这个名字是萨克斯手 Steve Coleman 起的，Jacob Collier 让它广为人知。负和声保留了往主和弦去的"引力"，但换了一种颜色。', '考え方は Ernst Levy の「極性理論」（『A Theory of Harmony』）に由来し、「ネガティブ・ハーモニー」の名はサックス奏者 Steve Coleman が付け、Jacob Collier が広めた。主和音への引力を保ちつつ色を変える。', 'The idea comes from Ernst Levy’s polarity theory (A Theory of Harmony); saxophonist Steve Coleman coined the name and Jacob Collier popularised it. It keeps the pull toward the tonic with a different colour.'),
        ] },
      { type: 'match', ref: 'wiki-negative-harmony', visual: { kind: 'clock', pcs: [0, 2, 4, 5, 7], mirror: 7 },
        prompt: t('C 调：音 ↔ 它的负和声', 'C：音 ↔ ネガティブ', 'In C: note ↔ its negative'),
        pairs: [['C', 'G'], ['E', 'E♭'], ['D', 'F'], ['B', 'A♭']],
        hint: t('两个音加起来"对称"在 E♭/E 中间：C(0)+G(7)=7，E(4)+E♭(3)=7。', '2 音の和が 7 になる：C(0)+G(7)、E(4)+E♭(3)。', 'Pairs add to 7 in pitch-class numbers: C(0)+G(7), E(4)+E♭(3).'),
        explain: t('镜子在 3.5 处：C↔G、D↔F、E↔E♭、B↔A♭。', '鏡は 3.5：C↔G・D↔F・E↔E♭・B↔A♭。', 'The mirror sits at 3.5: C↔G, D↔F, E↔E♭, B↔A♭.') },
      { type: 'choice', ref: 'wiki-negative-harmony',
        prompt: t('C 调里，G7（G B D F）的负和声是哪些音？', 'C で G7（G B D F）のネガティブは？', 'In C, which notes are the negative of G7 (G B D F)?'),
        options: ['C A♭ F D', 'C E G B♭', 'G B♭ D F'], answer: 0,
        hint: t('G→C、B→A♭、D→F、F→D。', 'G→C・B→A♭・D→F・F→D。', 'G→C, B→A♭, D→F, F→D.'),
        explain: t('得到 D F A♭ C，可以看成 Dm7♭5（也就是 Fm6）——它同样往 C 解决。', 'D F A♭ C となり Dm7♭5（Fm6）——これも C へ解決する。', 'The result, D F A♭ C, reads as Dm7♭5 (or Fm6) — and it still resolves to C.') },
      { type: 'choice', ref: 'wiki-negative-harmony',
        prompt: t('负和声和普通的旋律倒影有什么不同？', 'ネガティブ・ハーモニーと普通の旋律の反行の違いは？', 'How does negative harmony differ from ordinary melodic inversion?'),
        options: [t('每个音都严格翻转，而且结果移了一个五度', 'すべての音を厳密に折り返し、結果は 5 度ずれる', 'every note is strictly reflected, and the result is shifted by a fifth'), t('完全一样', 'まったく同じ', 'they are identical'), t('只翻转低音', 'ベースだけ折り返す', 'only the bass is flipped')], answer: 0,
        hint: t('自然音阶内的倒影会调整个别音留在调内。', '音階内の反行は個々の音を調内に収めるよう調整する。', 'Diatonic inversion adjusts notes to stay in the scale.'),
        explain: t('负和声严格反射每个音，并且相对原来的材料移了一个五度，而不是留在原调里。', '各音を厳密に反射し、元の素材に対して 5 度ずれる。', 'Negative harmony reflects every pitch strictly and is transposed by a fifth relative to the original.') },
      { type: 'choice', ref: 'wiki-negative-harmony',
        prompt: t('"负和声"这个名字是谁起的？', '「ネガティブ・ハーモニー」と名づけたのは？', 'Who coined the term “negative harmony”?'),
        options: ['Steve Coleman', 'Jacob Collier', 'Ernst Levy'], answer: 0,
        hint: t('Levy 的书里并没有这个词。', 'Levy の本にはこの言葉はない。', 'The term does not appear in Levy’s book.'),
        explain: t('Steve Coleman 在 1970 年代末或 80 年代初起了这个名字；Levy 提供了理论来源，Collier 让它流行。', 'Steve Coleman が 1970 年代末か 80 年代初めに命名。Levy が理論の源、Collier が広めた。', 'Steve Coleman coined it in the late 1970s or early 1980s; Levy supplied the theory, Collier popularised it.') },
    ],
  },
  {
    id: 'guidetone', section: 'jazz', feature: 'other', icon: '3·7',
    title: t('导向音路径与和弦报告', 'ガイド・トーンとコード・レポート', 'Guide-tone paths and chord reports'),
    blurb: t('三音、七音一路连下去；一个和弦的配置、替代与音阶', '3 度と 7 度をつなぐ、1 つのコードの配置・代理・音階', 'Linking thirds and sevenths; voicings, substitutes and scales for one chord'),
    cards: [
      { type: 'guide', ref: ['omt2e-jazz-voicings', 'omt2e-chord-scale', 'omt2e-substitutions'], tool: { feature: 'other' }, demo: { play: [[53, 60], [53, 59], [52, 59]] },
        title: t('只听三音和七音', '3 度と 7 度だけを聴く', 'Listen only to thirds and sevenths'),
        steps: [
          t('三音决定大小，七音决定是哪种七和弦，所以它们叫"导向音"。"导音路径"工具会列出每个和弦的三音、七音。', '3 度が長短、7 度が七の和音の種類を決めるので「ガイド・トーン」と呼ぶ。「導音路径」ツールは各コードの 3 度と 7 度を並べる。', 'The third decides major/minor and the seventh the seventh type, so they are guide tones. The Guide-Tone Path tool lists each chord’s third and seventh.'),
          t('五度进行里，前一个和弦的三音常常不动，变成下一个和弦的七音；七音往下走半音，变成下一个的三音。听：Dm7（F、C）→ G7（F、B）→ Cmaj7（E、B）。', '5 度進行では前の 3 度がそのまま次の 7 度に、7 度は半音下がって次の 3 度に。聴いて：Dm7（F・C）→ G7（F・B）→ Cmaj7（E・B）。', 'In fifth motion the third often stays to become the next seventh, while the seventh drops a half step to become the next third. Listen: Dm7 (F, C) → G7 (F, B) → Cmaj7 (E, B).'),
          t('"和弦报告"则针对一个和弦给出：壳音和 drop 2 配置、几种节奏伴奏型、替代和弦，以及和弦—音阶（CST）和 LCC 的即兴建议。', '「コード・レポート」は 1 つのコードについて：シェルとドロップ 2、伴奏リズム、代理コード、コード・スケール（CST）と LCC の即興の提案を示す。', 'The Chord Report gives, for one chord: shell and drop-2 voicings, comping rhythms, substitutions, and chord–scale (CST) and LCC improvisation suggestions.'),
        ] },
      { type: 'fill', ref: 'omt2e-jazz-voicings',
        prompt: t('G7 的导向音：三音 ___、七音 ___', 'G7 のガイド・トーン：3 度 ___、7 度 ___', 'G7’s guide tones: third ___, seventh ___'),
        bank: [opt('B', 'B'), opt('F', 'F'), opt('D', 'D'), opt('G', 'G')], answer: ['B', 'F'],
        hint: t('G B D F。', 'G B D F。', 'G B D F.'),
        explain: t('G7 = G B D F：三音 B、七音 F（它们构成三全音）。', 'G7 = G B D F：3 度 B・7 度 F（三全音）。', 'G7 = G B D F: third B, seventh F (a tritone).') },
      { type: 'choice', ref: 'omt2e-jazz-voicings',
        prompt: t('Dm7 → G7：Dm7 的七音 C 到了 G7 里往哪走最顺？', 'Dm7 → G7：Dm7 の 7 度 C は G7 でどこへ？', 'Dm7 → G7: where does Dm7’s seventh, C, move most smoothly?'),
        options: [t('往下半音到 B（G7 的三音）', '半音下の B（G7 の 3 度）へ', 'down a half step to B (G7’s third)'), t('跳到 G', 'G へ跳ぶ', 'leap to G'), t('上到 D', 'D へ上がる', 'up to D')], answer: 0,
        hint: t('七音往下走一步。', '7 度は 1 歩下がる。', 'Sevenths step down.'),
        explain: t('C → B 只动半音，正好落到 G7 的三音。', 'C → B は半音だけで G7 の 3 度。', 'C → B moves a half step, landing on G7’s third.') },
      { type: 'choice', ref: 'omt2e-substitutions',
        prompt: t('和弦报告给 G7 列出的替代和弦里，D♭7 属于哪一种？', 'コード・レポートの G7 の代理で D♭7 はどれ？', 'Among the Chord Report’s substitutes for G7, D♭7 is a…'),
        options: [t('三全音替代', '裏コード', 'tritone substitution'), t('关系小调', '平行調', 'relative minor'), t('借用和弦', '借用和音', 'borrowed chord')], answer: 0,
        hint: t('G 和 D♭ 相隔三全音。', 'G と D♭ は三全音。', 'G and D♭ are a tritone apart.'),
        explain: t('两者共享三全音 B（C♭）–F，可以互换。', 'どちらも三全音 B（C♭）–F を持ち、交換できる。', 'Both contain the tritone B (C♭)–F, so they can swap.') },
      { type: 'choice', ref: 'omt2e-chord-scale',
        prompt: t('在 C 大调里给 Dm7 做即兴，和弦—音阶理论最常建议哪个调式？', 'C 長調の Dm7 で即興するとき、コード・スケール理論がまず勧める旋法は？', 'Improvising on Dm7 in C major, which mode does chord–scale theory suggest first?'),
        options: ['D Dorian', 'D Aeolian', 'D Phrygian'], answer: 0,
        hint: t('ii 级 → 第 2 个调式。', 'ii → 第 2 旋法。', 'ii → mode 2.'),
        explain: t('Dm7 是 ii，配 Dorian；Dm13 的音正好是 D Dorian。', 'Dm7 は ii でドリアン。Dm13 の音はちょうど D ドリアン。', 'Dm7 is ii, so Dorian; Dm13’s notes are exactly D Dorian.') },
    ],
  },
];

// 关卡顺序（从简到难）
const ORDER = ['swing', 'blues', 'bluesscale', 'jazz', 'guidetone', 'keycenter', 'jazzvoicing', 'chordscale', 'melodicminor', 'harmonicminor', 'symmetric', 'morescales', 'substitutions', 'color', 'negharmony', 'lcc'];
export const UNITS = ORDER.map((id) => {
  const unit = ALL.find((u) => u.id === id);
  if (!unit) throw new Error(`unknown unit ${id}`);
  return unit;
});
if (UNITS.length !== ALL.length) throw new Error('every unit must appear in ORDER');
