// 乐理闯关 · 入门的进阶关：每个主关后面 4 关（第 5 关"综合测验"在开局时抽题）。
// 题卡只用 references.js 中已登记、已核实的资料；{ type: 'gen' } 的题由 learn_generators.js 按同样的资料计算生成。
// 依据汇总（由 scripts/annotate-learn.mjs 生成）：
//   ref:omt2e-half-whole ref:omt2e-keyboard ref:omt2e-clefs ref:omt2e-aspn ref:omt2e-rhythm ref:omt2e-rhythm-more
//   ref:zhwiki-pentatonic ref:helvting-scales ref:omt2e-collections ref:zhwiki-heptatonic ref:sccm-ethnic-modes
//   ref:omt2e-major-scales ref:omt2e-minor ref:omt2e-roman-numerals ref:omt2e-modes ref:omt2e-chord-scale
//   ref:omt-intervals ref:omt2e-intervals ref:omt2e-intro ref:omt2e-texture ref:omt2e-compound-meter ref:wiki-metre
//   ref:omt2e-20c-rhythm ref:omt2e-simple-meter
// @refs-end

const t = (zh, ja, en) => ({ zh, ja, en });
const opt = (id, label) => ({ id, label });
const G = (gen, count = 2, params) => ({ type: 'gen', gen, count, ...(params ? { params } : {}) });
const L = (title, cards) => ({ title, cards });

export const BRANCHES = {
  keys: [
    L(t('一个黑键两个名字', '黒鍵の 2 つの名前', 'One black key, two names'), [
      { type: 'guide', ref: 'omt2e-half-whole', visual: { kind: 'keys', keys: [61, 63] }, tool: { feature: 'chord', q: 'C#' },
        title: t('同音异名', '異名同音', 'Enharmonic spellings'),
        steps: [
          t('拼法不同、声音一样的音叫"同音异名"：C♯ = D♭，D♯ = E♭。', '書き方が違っても同じ音を「異名同音」と呼ぶ：C♯ = D♭、D♯ = E♭。', 'Notes spelled differently but sounding the same are enharmonic: C♯ = D♭, D♯ = E♭.'),
          t('白键也会有别名：E♯ 就是 F，C♭ 就是 B——因为 E–F、B–C 本来就只差半音。', '白鍵にも別名がある：E♯ は F、C♭ は B。E–F と B–C はもともと半音だから。', 'White keys get other names too: E♯ is F and C♭ is B — because E–F and B–C are already half steps.'),
        ] },
      { type: 'match', ref: 'omt2e-half-whole',
        prompt: t('同音异名：连一连', '異名同音：つなごう', 'Enharmonics: match them'),
        pairs: [['D♯', 'E♭'], ['G♯', 'A♭'], ['E♯', 'F'], ['C♭', 'B']],
        hint: t('E♯ 是 E 往上半音；C♭ 是 C 往下半音。', 'E♯ は E の半音上、C♭ は C の半音下。', 'E♯ is a half step above E; C♭ a half step below C.'),
        explain: t('E 往上半音就是 F，C 往下半音就是 B。', 'E の半音上は F、C の半音下は B。', 'A half step above E is F; a half step below C is B.') },
      { type: 'choice', ref: 'omt2e-half-whole',
        prompt: t('F♭ 弹在键盘上是哪个键？', 'F♭ は鍵盤のどの鍵？', 'Which key on the piano is F♭?'),
        options: [t('白键 E', '白鍵 E', 'the white key E'), t('黑键 E♭', '黒鍵 E♭', 'the black key E♭'), t('白键 F', '白鍵 F', 'the white key F')], answer: 0,
        hint: t('F 往下半音。', 'F の半音下。', 'A half step below F.'),
        explain: t('F 左边紧挨的就是白键 E，所以 F♭ 和 E 同音。', 'F のすぐ左は白鍵 E。F♭ と E は同じ音。', 'Right next to F on the left is the white key E, so F♭ sounds as E.') },
      G('halfWhole', 3),
    ]),
    L(t('在键盘上找音', '鍵盤で音を探す', 'Finding notes on the keyboard'), [
      { type: 'guide', ref: 'omt2e-keyboard', visual: { kind: 'keys', keys: [60, 65] },
        title: t('靠黑键分组认白键', '黒鍵のまとまりで白鍵を見つける', 'Use the black-key groups'),
        steps: [
          t('黑键两个一组、三个一组地重复。两个黑键左边是 C，三个黑键左边是 F。', '黒鍵は 2 つと 3 つのまとまりが繰り返す。2 つの左が C、3 つの左が F。', 'Black keys repeat in groups of two and three. Left of the two is C; left of the three is F.'),
          t('找到 C 和 F，其余白键按字母往右数：C D E F G A B。', 'C と F を見つけたら、残りは右へ文字順に：C D E F G A B。', 'Find C and F, then count the rest to the right: C D E F G A B.'),
        ] },
      { type: 'choice', ref: 'omt2e-keyboard',
        prompt: t('三个一组的黑键中间那个黑键，左右两边的白键是？', '3 つの黒鍵の真ん中の黒鍵の両隣の白鍵は？', 'The middle black key of the group of three sits between which white keys?'),
        options: ['G – A', 'F – G', 'A – B'], answer: 0,
        hint: t('三个黑键：F♯、G♯、A♯。', '3 つの黒鍵は F♯・G♯・A♯。', 'The three black keys are F♯, G♯, A♯.'),
        explain: t('中间那个是 G♯（A♭），夹在 G 和 A 之间。', '真ん中は G♯（A♭）で、G と A の間。', 'The middle one is G♯ (A♭), between G and A.') },
      G('keyName', 4),
    ]),
    L(t('重升与重降', 'ダブルシャープとダブルフラット', 'Double sharps and double flats'), [
      { type: 'guide', ref: 'omt2e-half-whole', visual: { kind: 'keys', keys: [62] },
        title: t('一次挪两个半音', '一度に半音 2 つ', 'Moving two half steps at once'),
        steps: [
          t('重升号（𝄪）把音升高一个全音，重降号（𝄫）把音降低一个全音。', 'ダブルシャープ（𝄪）は全音上げ、ダブルフラット（𝄫）は全音下げる。', 'A double sharp (𝄪) raises a note a whole step; a double flat (𝄫) lowers it a whole step.'),
          t('所以 C𝄪 弹的是 D，E𝄫 弹的也是 D。它们常出现在升降号很多的调里，用来保持"每个字母用一次"。', 'C𝄪 も E𝄫 も弾くのは D。調号の多い調で「各文字 1 回」を守るために出てきます。', 'So C𝄪 and E𝄫 both sound as D. They turn up in keys with many accidentals to keep “one letter each”.'),
          t('临时记号写在音符的左边，和音符在同一线或同一间。', '臨時記号は音符の左、同じ線か間に書く。', 'Accidentals go to the left of the note, on the same line or space.'),
        ] },
      { type: 'choice', ref: 'omt2e-half-whole',
        prompt: t('F𝄪 在键盘上和哪个音同音？', 'F𝄪 と同じ音は？', 'F𝄪 sounds the same as…'),
        options: ['G', 'F♯', 'G♯'], answer: 0,
        hint: t('F 往上一个全音。', 'F から全音上。', 'A whole step above F.'),
        explain: t('F → F♯ → G，升两个半音就是 G。', 'F → F♯ → G、半音 2 つで G。', 'F → F♯ → G: two half steps up is G.') },
      { type: 'choice', ref: 'omt2e-half-whole',
        prompt: t('B𝄫 在键盘上是哪个键？', 'B𝄫 は鍵盤のどれ？', 'Which key is B𝄫?'),
        options: [t('白键 A', '白鍵 A', 'the white key A'), t('黑键 B♭', '黒鍵 B♭', 'the black key B♭'), t('白键 C', '白鍵 C', 'the white key C')], answer: 0,
        hint: t('B 往下一个全音。', 'B から全音下。', 'A whole step below B.'),
        explain: t('B → B♭ → A，降两个半音就是 A。', 'B → B♭ → A、半音 2 つ下で A。', 'B → B♭ → A: two half steps down is A.') },
      { type: 'fill', ref: 'omt2e-half-whole',
        prompt: t('重升号升高一个 ___，重降号降低一个 ___', 'ダブルシャープは ___ 上げ、ダブルフラットは ___ 下げる', 'A double sharp raises a ___; a double flat lowers a ___'),
        bank: [opt('w', t('全音', '全音', 'whole step')), opt('h', t('半音', '半音', 'half step')), opt('o', t('八度', 'オクターヴ', 'octave'))], answer: ['w', 'w'],
        hint: t('"重" = 两次。', '「ダブル」= 2 回。', '“Double” = twice.'),
        explain: t('两个半音 = 一个全音。', '半音 2 つ = 全音 1 つ。', 'Two half steps = one whole step.') },
    ]),
    L(t('半音全音综合练习', '半音・全音の総合練習', 'Half and whole step workout'), [
      { type: 'guide', ref: 'omt2e-half-whole',
        title: t('下一个字母，正确的距离', '次の文字で、正しい距離', 'Next letter, right distance'),
        steps: [
          t('"往上一个全音"通常写成下一个字母：E 往上全音写 F♯，而不是 G♭。', '「全音上」はふつう次の文字で書く：E の全音上は F♯（G♭ ではない）。', '“A whole step up” is usually spelled with the next letter: a whole step above E is F♯, not G♭.'),
          t('先选好字母，再用升降号把距离调对。', 'まず文字を決め、変化記号で距離を合わせる。', 'Pick the letter first, then fix the distance with accidentals.'),
        ] },
      G('halfWhole', 4), G('keyName', 2),
    ]),
  ],

  staff: [
    L(t('读高音谱号', 'ト音記号を読む', 'Reading treble clef'), [
      { type: 'guide', ref: 'omt2e-clefs', visual: { kind: 'staff', notes: ['E4', 'G4', 'B4', 'D5', 'F5'], clef: 'treble' },
        title: t('线和间的口诀', '線と間の覚え方', 'Lines and spaces'),
        steps: [
          t('高音谱号的五条线（下→上）：E G B D F（Every Good Bird Does Fly）。', 'ト音記号の 5 本の線（下から）：E G B D F（Every Good Bird Does Fly）。', 'Treble lines, bottom to top: E G B D F (Every Good Bird Does Fly).'),
          t('四个间（下→上）：F A C E——正好拼出英文单词 face。', '4 つの間（下から）：F A C E。英単語 face になる。', 'The four spaces, bottom to top: F A C E — they spell “face”.'),
        ] },
      G('staffRead', 5, { clefs: ['treble'] }),
    ]),
    L(t('读低音谱号', 'ヘ音記号を読む', 'Reading bass clef'), [
      { type: 'guide', ref: 'omt2e-clefs', visual: { kind: 'staff', notes: ['G2', 'B2', 'D3', 'F3', 'A3'], clef: 'bass' },
        title: t('低音谱号的口诀', 'ヘ音記号の覚え方', 'Bass clef sayings'),
        steps: [
          t('低音谱号又叫 F 谱号：它的两个点夹住从上数第二线，那条线是 F。', 'ヘ音記号は F 記号：2 つの点が上から 2 本目の線（F）をはさむ。', 'The bass clef is the F clef: its dots surround the second line from the top, which is F.'),
          t('五条线（下→上）：G B D F A（Good Bikes Don’t Fall Apart）；四个间：A C E G（All Cows Eat Grass）。', '線（下から）：G B D F A、間：A C E G。', 'Lines bottom to top: G B D F A (Good Bikes Don’t Fall Apart); spaces: A C E G (All Cows Eat Grass).'),
        ] },
      G('staffRead', 5, { clefs: ['bass'] }),
    ]),
    L(t('中音谱号：C 谱号', 'ハ音記号（アルト）', 'The alto (C) clef'), [
      { type: 'guide', ref: 'omt2e-clefs',
        title: t('中线就是中央 C', '真ん中の線が中央の C', 'The middle line is middle C'),
        steps: [
          t('中音谱号的中心卡在正中间那条线上，那条线是中央 C，所以叫"C 谱号"。它现在用得比较少。', 'アルト記号の中心は真ん中の線で、そこが中央の C。だから「C 記号」。今はあまり使われない。', 'The alto clef centres on the middle line, which is middle C — hence “C clef”. It is less common today.'),
          t('它的五条线（下→上）：F A C E G（Fat Alley Cats Eat Garbage）；四个间：G B D F。', '線（下から）：F A C E G、間：G B D F。', 'Its lines bottom to top: F A C E G (Fat Alley Cats Eat Garbage); spaces: G B D F.'),
          t('不同的谱号是为了让不同音域的乐器少用加线：高音乐器用高音谱号，低音乐器用低音谱号。', '音部記号が複数あるのは、音域ごとに加線を減らすため。高い楽器はト音、低い楽器はヘ音。', 'Several clefs exist so each range needs fewer ledger lines: high instruments use treble, low ones bass.'),
        ] },
      { type: 'choice', ref: 'omt2e-clefs',
        prompt: t('中音谱号正中间的线是哪个音？', 'アルト記号の真ん中の線は？', 'Which note is the middle line of the alto clef?'),
        options: [t('中央 C', '中央の C', 'middle C'), 'G4', 'F3'], answer: 0,
        hint: t('它叫 C 谱号。', 'C 記号と呼ばれる。', 'It is called the C clef.'),
        explain: t('谱号的中心卡住中线，那条线就是中央 C（C4）。', '記号の中心が真ん中の線を指し、それが中央の C（C4）。', 'The clef’s centre points at the middle line: middle C (C4).') },
      { type: 'fill', ref: 'omt2e-clefs',
        prompt: t('中音谱号的五条线：F A ___ E G', 'アルト記号の線：F A ___ E G', 'Alto clef lines: F A ___ E G'),
        bank: [opt('C', 'C'), opt('B', 'B'), opt('D', 'D')], answer: ['C'],
        hint: t('中间那条线是 C。', '真ん中の線が C。', 'The middle line is C.'),
        explain: t('F A C E G：中线 C 就是中央 C。', 'F A C E G：真ん中の C が中央の C。', 'F A C E G: the middle C is middle C.') },
      { type: 'choice', ref: 'omt2e-clefs',
        prompt: t('为什么要有好几种谱号？', 'なぜ音部記号が何種類もある？', 'Why are there several clefs?'),
        options: [t('让不同音域都少用加线、好读', '音域ごとに加線を減らして読みやすく', 'so every range needs fewer ledger lines'), t('为了区分速度', '速さを区別するため', 'to show tempo'), t('为了区分乐器的音色', '音色を区別するため', 'to show timbre')], answer: 0,
        hint: t('想想低音提琴如果只用高音谱号要写多少加线。', 'コントラバスがト音記号だけだと加線がどれだけ必要か。', 'Imagine a double bass written only in treble clef.'),
        explain: t('谱号只是改变"哪条线是哪个音"，让高的低的乐器都能写在五条线附近。', '音部記号は「どの線がどの音か」を変えるだけ。高い楽器も低い楽器も 5 線の近くに書ける。', 'A clef only changes which line is which note, keeping high and low instruments near the staff.') },
    ]),
    L(t('八度编号与大谱表', 'オクターヴ番号と大譜表', 'Octave numbers and the grand staff'), [
      { type: 'guide', ref: ['omt2e-aspn', 'omt2e-keyboard'], visual: { kind: 'staff', notes: ['C3', 'C4', 'C5'], clef: 'treble' }, demo: { play: [[48], [60], [72]] },
        title: t('C4、C5 里的数字', 'C4・C5 の数字', 'The numbers in C4 and C5'),
        steps: [
          t('每个八度从 C 数到 B，八度的编号从 C 开始换：B3 的下一个白键是 C4。', '各オクターヴは C から B まで。番号は C で変わる：B3 の次の白鍵は C4。', 'Each octave runs C to B and the number changes at C: the white key after B3 is C4.'),
          t('钢琴大部分音在第 1 到第 7 个八度，两头各有一点第 0 和第 8 八度。', 'ピアノの音は主にオクターヴ 1〜7、両端に 0 と 8 が少し。', 'A piano mostly covers octaves 1–7, with a little of 0 and 8 at the ends.'),
          t('"音高"是具体的一个音（C4），"音级"不分八度（所有的 C）。', '「ピッチ」は具体的な音（C4）、「ピッチクラス」はオクターヴを問わない（すべての C）。', 'A pitch is one specific note (C4); a pitch class ignores octave (every C).'),
        ] },
      { type: 'choice', ref: 'omt2e-aspn',
        prompt: t('C4 往上一个八度的 C 写作？', 'C4 の 1 オクターヴ上の C は？', 'The C an octave above C4 is…'),
        options: ['C5', 'C3', 'C8'], answer: 0,
        hint: t('往上一个八度，数字加 1。', '1 オクターヴ上で数字 +1。', 'Up an octave, add 1.'),
        explain: t('C4 → C5；往下一个八度是 C3。', 'C4 → C5、下は C3。', 'C4 → C5; an octave down is C3.') },
      { type: 'choice', ref: 'omt2e-aspn',
        prompt: t('C4 和 C2 是同一个"音级"吗？', 'C4 と C2 は同じピッチクラス？', 'Are C4 and C2 the same pitch class?'),
        options: [t('是，都是 C', 'はい、どちらも C', 'Yes, both are C'), t('不是', 'いいえ', 'No')], answer: 0,
        hint: t('音级不管八度。', 'ピッチクラスはオクターヴを問わない。', 'Pitch class ignores octave.'),
        explain: t('它们是不同的音高，但属于同一个音级 C。', '違うピッチだが同じピッチクラス C。', 'Different pitches, same pitch class C.') },
      G('staffRead', 3),
    ]),
  ],

  rhythm: [
    L(t('休止符：安静也有时值', '休符：静けさにも長さ', 'Rests: silence has length too'), [
      { type: 'guide', ref: 'omt2e-rhythm',
        title: t('每种音符都有对应的休止符', 'どの音符にも休符がある', 'Every note value has a rest'),
        steps: [
          t('常见休止符：全休止符、二分休止符、四分休止符、八分休止符、十六分休止符——时值和同名音符一样。', 'よく使う休符：全休符・2 分休符・4 分休符・8 分休符・16 分休符。長さは同じ名前の音符と同じ。', 'Common rests: whole, half, quarter, eighth and sixteenth — each lasts as long as the matching note.'),
          t('休止符也能加附点，规则和音符一样：加上自己的一半。', '休符にも付点がつき、規則は音符と同じ：自分の半分を足す。', 'Rests can be dotted too, with the same rule: add half of itself.'),
        ] },
      { type: 'choice', ref: 'omt2e-rhythm',
        prompt: t('一个四分休止符等于几个八分休止符？', '4 分休符は 8 分休符いくつ分？', 'A quarter rest equals how many eighth rests?'),
        options: ['2', '4', '1'], answer: 0,
        hint: t('和音符一样对半切。', '音符と同じく半分ずつ。', 'Halve it, just like notes.'),
        explain: t('四分 = 2 个八分，休止符也一样。', '4 分 = 8 分 2 つ、休符も同じ。', 'A quarter is 2 eighths — rests too.') },
      { type: 'match', ref: 'omt2e-rhythm',
        prompt: t('休止符 ↔ 等于几个四分休止符', '休符 ↔ 4 分休符いくつ分', 'Rest ↔ how many quarter rests'),
        pairs: [[t('全休止符', '全休符', 'whole rest'), '4'], [t('二分休止符', '2 分休符', 'half rest'), '2'], [t('附点二分休止符', '付点 2 分休符', 'dotted half rest'), '3']],
        hint: t('附点加一半：2 + 1。', '付点で半分を足す：2 + 1。', 'A dot adds half: 2 + 1.'),
        explain: t('全 4、二分 2、附点二分 3。', '全 4・2 分 2・付点 2 分 3。', 'Whole 4, half 2, dotted half 3.') },
      G('noteValue', 2),
    ]),
    L(t('双附点', '複付点', 'Double dots'), [
      { type: 'guide', ref: 'omt2e-rhythm',
        title: t('第二个点加第一个点的一半', '2 つ目の点は 1 つ目の半分', 'The second dot adds half the first'),
        steps: [
          t('一个附点：加上音符本身的一半。', '付点 1 つ：音符の半分を足す。', 'One dot adds half the note.'),
          t('再加一个点：再加上"前一个点"的一半。所以双附点二分音符 = 2 + 1 + ½ = 3½ 个四分音符。', 'もう 1 つの点は「前の点」の半分を足す。複付点 2 分音符 = 2 + 1 + ½ = 4 分音符 3½ 個。', 'Another dot adds half of the previous dot. A double-dotted half = 2 + 1 + ½ = 3½ quarters.'),
        ] },
      { type: 'choice', ref: 'omt2e-rhythm',
        prompt: t('双附点四分音符等于几个十六分音符？', '複付点 4 分音符は 16 分音符いくつ？', 'A double-dotted quarter equals how many sixteenths?'),
        options: ['7', '6', '8'], answer: 0,
        hint: t('四分 = 4 个十六分；第一个点 +2，第二个点 +1。', '4 分 = 16 分 4 つ、1 つ目の点 +2、2 つ目 +1。', 'Quarter = 4 sixteenths; first dot +2, second dot +1.'),
        explain: t('4 + 2 + 1 = 7 个十六分音符。', '4 + 2 + 1 = 16 分音符 7 つ。', '4 + 2 + 1 = 7 sixteenths.') },
      { type: 'choice', ref: 'omt2e-rhythm',
        prompt: t('双附点二分音符等于几个八分音符？', '複付点 2 分音符は 8 分音符いくつ？', 'A double-dotted half equals how many eighths?'),
        options: ['7', '6', '5'], answer: 0,
        hint: t('二分 = 4 个八分；+2；+1。', '2 分 = 8 分 4 つ、+2、+1。', 'Half = 4 eighths; +2; +1.'),
        explain: t('4 + 2 + 1 = 7。', '4 + 2 + 1 = 7。', '4 + 2 + 1 = 7.') },
      G('noteValue', 2),
    ]),
    L(t('连音线与切分', 'タイとシンコペーション', 'Ties and syncopation'), [
      { type: 'guide', ref: ['omt2e-rhythm', 'omt2e-rhythm-more'], visual: { kind: 'beats', groups: [2, 2, 2, 2] },
        title: t('把重音挪到弱拍', 'アクセントを弱拍へ', 'Moving the accent off the beat'),
        steps: [
          t('连音线连接两个同样高的音，把它们的时值加在一起，被连过去的音不再弹。', 'タイは同じ高さの 2 音の長さを足し、つながれた音は弾き直さない。', 'A tie joins two notes of the same pitch, adding their lengths; the tied-to note is not replayed.'),
          t('切分：重音出现在弱拍或拍子之间。连音线、附点、休止符或力度都能制造切分。', 'シンコペーション：アクセントが弱拍や拍の間に来る。タイ・付点・休符・強弱で作れる。', 'Syncopation puts accents on weak beats or between beats, made with ties, dots, rests or dynamics.'),
        ] },
      { type: 'choice', ref: 'omt2e-rhythm-more',
        prompt: t('下面哪一种不能用来制造切分？', 'シンコペーションを作れないのは？', 'Which of these cannot create syncopation?'),
        options: [t('调号', '調号', 'a key signature'), t('连音线', 'タイ', 'a tie'), t('休止符', '休符', 'a rest')], answer: 0,
        hint: t('切分和节奏、重音有关。', 'シンコペーションはリズムとアクセントの話。', 'Syncopation is about rhythm and accent.'),
        explain: t('连音线、附点、休止符和力度都能把重音挪开；调号只管音高。', 'タイ・付点・休符・強弱はアクセントを動かせる。調号は音高だけ。', 'Ties, dots, rests and dynamics can shift the accent; a key signature only affects pitch.') },
      { type: 'choice', ref: 'omt2e-rhythm',
        prompt: t('连音线可以连两个不同高度的音吗？', 'タイは違う高さの音をつなげる？', 'Can a tie connect two different pitches?'),
        options: [t('不可以，只连同样的音', 'いいえ、同じ音だけ', 'No — only the same pitch'), t('可以', 'はい', 'Yes')], answer: 0,
        hint: t('不同高度的连线叫"圆滑线"，那是另一回事。', '高さの違う音をつなぐのはスラーで別物。', 'A curve between different pitches is a slur — something else.'),
        explain: t('连音线只连接同一个音高，作用是延长。', 'タイは同じ音高だけをつなぎ、伸ばすためのもの。', 'A tie only links the same pitch, to extend it.') },
      G('noteValue', 2),
    ]),
    L(t('时值计算', '音価の計算', 'Counting durations'), [
      { type: 'guide', ref: 'omt2e-rhythm',
        title: t('用最小的单位来数', 'いちばん小さい単位で数える', 'Count in the smallest unit'),
        steps: [
          t('把所有音符都换算成八分音符：全 8、二分 4、四分 2、八分 1。', 'すべて 8 分音符に換算：全 8・2 分 4・4 分 2・8 分 1。', 'Convert everything to eighths: whole 8, half 4, quarter 2, eighth 1.'),
          t('附点加一半：附点四分 = 3，附点二分 = 6。', '付点は半分を足す：付点 4 分 = 3、付点 2 分 = 6。', 'Dots add half: dotted quarter = 3, dotted half = 6.'),
        ] },
      G('noteValue', 5),
    ]),
  ],

  pentatonic: [
    L(t('五种五声调式', '5 つの五声旋法', 'The five pentatonic modes'), [
      { type: 'guide', ref: ['zhwiki-pentatonic', 'helvting-scales'], tool: { feature: 'chinese' }, demo: { play: [[69], [72], [74], [76], [79], [81]] },
        title: t('谁当主音，就是什么调式', '主音になった音で旋法が決まる', 'Whichever note is home names the mode'),
        steps: [
          t('同样五个音，宫、商、角、徵、羽都可以当主音，分别叫宫调式、商调式、角调式、徵调式、羽调式。', '同じ 5 音でも宮・商・角・徴・羽のどれもが主音になれ、宮調式・商調式・角調式・徴調式・羽調式と呼ぶ。', 'The same five notes can each be home: Gong, Shang, Jue, Zhi and Yu modes.'),
          t('名字写法是"主音 + 阶名"：用 C 宫的音、以 A 为主音，就是 A 羽调式。听：A 羽调式。', '名前は「主音 + 階名」：C 宮の音で A が主音なら A 羽調式。聴いて：A 羽調式。', 'Name = tonic + degree: C-Gong notes with A as home make A Yu mode. Listen: A Yu.'),
        ] },
      { type: 'choice', ref: 'zhwiki-pentatonic',
        prompt: t('用 C 宫的五个音，以 G 为主音，叫？', 'C 宮の 5 音で G が主音なら？', 'C-Gong notes with G as home make…'),
        options: [t('G 徵调式', 'G 徴調式', 'G Zhi mode'), t('G 宫调式', 'G 宮調式', 'G Gong mode'), t('G 羽调式', 'G 羽調式', 'G Yu mode')], answer: 0,
        hint: t('G 在 C 宫里是哪个阶名？', 'G は C 宮のどの階名？', 'Which degree is G in C-Gong?'),
        explain: t('C D E G A 里 G 是徵，所以是 G 徵调式。', 'C D E G A で G は徴なので G 徴調式。', 'In C D E G A, G is Zhi — so G Zhi mode.') },
      { type: 'choice', ref: 'zhwiki-pentatonic',
        prompt: t('D 商调式的宫音是？', 'D 商調式の宮は？', 'What is the Gong of D Shang mode?'),
        options: ['C', 'D', 'G'], answer: 0,
        hint: t('商比宫高一个大二度。', '商は宮の長 2 度上。', 'Shang is a major second above Gong.'),
        explain: t('D 往下大二度是 C，所以 D 商调式用 C 宫的音。', 'D の長 2 度下は C。D 商調式は C 宮の音。', 'A major second below D is C, so D Shang uses the C-Gong notes.') },
      G('chineseNote', 3),
    ]),
    L(t('五声音阶 = 五个纯五度', '五声音階 = 完全 5 度 5 つ', 'Pentatonic = a stack of fifths'), [
      { type: 'guide', ref: 'omt2e-collections', visual: { kind: 'keys', keys: [60, 62, 64, 67, 69] }, demo: { play: [[48], [55], [62], [69], [76]] },
        title: t('一个接一个地叠五度', '5 度を次々に積む', 'Stacking fifths one after another'),
        steps: [
          t('从 C 往上连叠五度：C G D A E（听），排进一个八度就是 C D E G A——五声音阶。', 'C から 5 度を重ねる：C G D A E（聴いて）、1 オクターヴに並べると C D E G A。', 'Stack fifths from C: C G D A E (listen), which fits into one octave as C D E G A — the pentatonic.'),
          t('它的台阶（半音数）是 2–2–3–2–3。钢琴的五个黑键也是一个五声音阶。', '段差（半音数）は 2–2–3–2–3。ピアノの 5 つの黒鍵も五声音階。', 'Its steps in half steps are 2–2–3–2–3. The five black keys are a pentatonic too.'),
        ] },
      { type: 'fill', ref: 'omt2e-collections',
        prompt: t('五声音阶的台阶（半音数）：2–2–___–2–___', '五声音階の段差（半音）：2–2–___–2–___', 'Pentatonic steps (half steps): 2–2–___–2–___'),
        bank: [opt('3', '3'), opt('1', '1'), opt('4', '4')], answer: ['3', '3'],
        hint: t('C D E 之后到 G 隔了多远？', 'C D E のあと G までは？', 'How far from E to G?'),
        explain: t('C–D 2、D–E 2、E–G 3、G–A 2、A–C 3。', 'C–D 2・D–E 2・E–G 3・G–A 2・A–C 3。', 'C–D 2, D–E 2, E–G 3, G–A 2, A–C 3.') },
      { type: 'choice', ref: 'omt2e-collections',
        prompt: t('钢琴的五个黑键组成什么音阶？', 'ピアノの 5 つの黒鍵は何の音階？', 'What do the five black keys form?'),
        options: [t('五声音阶', '五声音階', 'a pentatonic'), t('全音音阶', '全音音階', 'a whole-tone scale'), t('半音阶', '半音階', 'a chromatic scale')], answer: 0,
        hint: t('五个音。', '5 音。', 'Five notes.'),
        explain: t('C♯ D♯ F♯ G♯ A♯ 就是一个五声音阶。', 'C♯ D♯ F♯ G♯ A♯ は五声音階。', 'C♯ D♯ F♯ G♯ A♯ is a pentatonic.') },
      { type: 'choice', ref: 'omt2e-collections',
        prompt: t('从 G 往上连叠四个纯五度（共五个音），得到哪个五声音阶？', 'G から 5 度を 4 回重ねる（5 音）と？', 'Stack four fifths up from G (five notes). Which pentatonic?'),
        options: ['G A B D E', 'G A C D E', 'G B♭ C D F'], answer: 0,
        hint: t('G D A E B。', 'G D A E B。', 'G D A E B.'),
        explain: t('G D A E B 排起来是 G A B D E——G 宫五声音阶。', 'G D A E B を並べると G A B D E（G 宮）。', 'G D A E B reorders to G A B D E — G-Gong pentatonic.') },
    ]),
    L(t('偏音：七声的边上', '偏音：七声への入り口', 'Bian notes: toward seven tones'), [
      { type: 'guide', ref: 'zhwiki-heptatonic', visual: { kind: 'keys', keys: [60, 62, 64, 65, 67, 69, 71] },
        title: t('补上两个缺口', '2 つのすき間を埋める', 'Filling the two gaps'),
        steps: [
          t('五声里 E–G、A–C 是小三度的"缺口"。往缺口里加的音叫偏音：清角、变徵、闰（清羽）、变宫。', '五声の E–G と A–C は短 3 度の「すき間」。そこに加える音が偏音：清角・変徴・閏（清羽）・変宮。', 'E–G and A–C are minor-third gaps in the pentatonic. Notes added there are bian notes: qingjue, bianzhi, run (qingyu), biangong.'),
          t('"清"比旁边的正音高半音，"变"比旁边的正音低半音。', '「清」は隣の正音の半音上、「変」は半音下。', '“Qing” is a half step above a main tone, “bian” a half step below one.'),
        ] },
      G('chineseNote', 4, { heptatonic: true }),
    ]),
    L(t('五声调式综合', '五声旋法の総合', 'Pentatonic mixed practice'), [
      { type: 'guide', ref: ['zhwiki-pentatonic', 'sccm-ethnic-modes'],
        title: t('先找宫，再看主音', 'まず宮、次に主音', 'Find Gong, then the home note'),
        steps: [
          t('在五个音里找唯一的大三度：它下面的音就是宫。', '5 音の中で唯一の長 3 度を探す。その下の音が宮。', 'Find the only major third among the five notes: its lower note is Gong.'),
          t('再看旋律停在哪个音上，它的阶名就是调式名。', '旋律が止まる音の階名が旋法名。', 'Then see where the tune comes to rest: its degree names the mode.'),
        ] },
      { type: 'choice', ref: 'sccm-ethnic-modes',
        prompt: t('五个音是 F G A C D，宫是哪个音？', '5 音が F G A C D のとき宮は？', 'The notes are F G A C D. Which is Gong?'),
        options: ['F', 'C', 'D'], answer: 0,
        hint: t('找唯一的大三度。', '唯一の長 3 度を探す。', 'Find the only major third.'),
        explain: t('F–A 是唯一的大三度，所以 F 是宫。', 'F–A が唯一の長 3 度なので F が宮。', 'F–A is the only major third, so F is Gong.') },
      G('chineseNote', 3),
    ]),
  ],

  major: [
    L(t('级名与唱名', '音度名と階名', 'Degree names and solfège'), [
      { type: 'guide', ref: 'omt2e-major-scales', visual: { kind: 'staff', notes: ['C4', 'D4', 'E4', 'F4', 'G4', 'A4', 'B4'] }, demo: { play: [[60], [62], [64], [65], [67], [69], [71], [72]], chord: [60, 64, 67, 71] },
        title: t('每个音都有名字和"职位"', 'どの音にも名前と役職がある', 'Every degree has a name and a job'),
        steps: [
          t('唱名：do re mi fa sol la ti。级名：主音、上主音、中音、下属音、属音、下中音、导音。', '階名：do re mi fa sol la ti。音度名：主音・上主音・中音・下属音・属音・下中音・導音。', 'Solfège: do re mi fa sol la ti. Degree names: tonic, supertonic, mediant, subdominant, dominant, submediant, leading tone.'),
          t('音阶用开头那个音命名（连同升降号）：从 E♭ 开始就是 E♭ 大调。听：C 大调音阶，最后是主音上的大七和弦。', '音階は最初の音（変化記号ごと）で名づける：E♭ から始まれば E♭ 長調。聴いて：C 長音階、最後は主音上の長七の和音。', 'Scales are named after their first note, accidental included: starting on E♭ makes E♭ major. Listen: C major, ending on the tonic major-seventh chord.'),
        ] },
      { type: 'match', ref: 'omt2e-major-scales',
        prompt: t('级数 ↔ 级名', '音度 ↔ 名前', 'Degree ↔ name'),
        pairs: [['1', t('主音', '主音', 'tonic')], ['4', t('下属音', '下属音', 'subdominant')], ['5', t('属音', '属音', 'dominant')], ['7', t('导音', '導音', 'leading tone')]],
        hint: t('第 7 个音紧贴着主音，"导"向主音。', '第 7 音は主音のすぐ下で主音へ「導く」。', 'The 7th sits right under the tonic and leads to it.'),
        explain: t('1 主音、4 下属音、5 属音、7 导音。', '1 主音・4 下属音・5 属音・7 導音。', '1 tonic, 4 subdominant, 5 dominant, 7 leading tone.') },
      { type: 'choice', ref: 'omt2e-major-scales',
        prompt: t('唱名 sol 对应第几级？', '階名 sol は第何音？', 'Which degree is sol?'),
        options: ['5', '4', '6'], answer: 0,
        hint: t('do re mi fa sol。', 'do re mi fa sol。', 'do re mi fa sol.'),
        explain: t('sol 是第 5 级，也就是属音。', 'sol は第 5 音で属音。', 'Sol is degree 5, the dominant.') },
      G('majorDegree', 2),
    ]),
    L(t('升号与降号的顺序', 'シャープとフラットの順番', 'The order of sharps and flats'), [
      { type: 'guide', ref: 'omt2e-major-scales', visual: { kind: 'circle', highlight: ['G', 'D', 'A', 'F', 'Bb', 'Eb'] },
        title: t('两串字母倒过来就是对方', '2 つの文字列は互いの逆', 'Two strings that mirror each other'),
        steps: [
          t('升号出现的顺序：F C G D A E B；降号：B E A D G C F（正好倒过来）。', 'シャープの順：F C G D A E B、フラット：B E A D G C F（ちょうど逆）。', 'Sharps appear F C G D A E B; flats B E A D G C F — exactly reversed.'),
          t('升号调：最后一个升号往上半音就是主音。降号调：倒数第二个降号就是主音。', 'シャープ調：最後のシャープの半音上が主音。フラット調：最後から 2 番目のフラットが主音。', 'Sharp keys: the tonic is a half step above the last sharp. Flat keys: the second-to-last flat is the tonic.'),
          t('调号写在谱号之后、拍号之前。', '調号は音部記号のあと、拍子記号の前。', 'The key signature goes after the clef and before the time signature.'),
        ] },
      { type: 'fill', ref: 'omt2e-major-scales',
        prompt: t('降号的顺序：B E A ___ G C F', 'フラットの順：B E A ___ G C F', 'Order of flats: B E A ___ G C F'),
        bank: [opt('D', 'D'), opt('F', 'F'), opt('B', 'B')], answer: ['D'],
        hint: t('把升号顺序 F C G D A E B 倒过来。', 'シャープの順 F C G D A E B を逆に。', 'Reverse F C G D A E B.'),
        explain: t('B E A D G C F。', 'B E A D G C F。', 'B E A D G C F.') },
      { type: 'choice', ref: 'omt2e-major-scales',
        prompt: t('调号有四个升号（F♯ C♯ G♯ D♯），是哪个大调？', 'シャープ 4 つ（F♯ C♯ G♯ D♯）の長調は？', 'Four sharps (F♯ C♯ G♯ D♯) is which major key?'),
        options: ['E', 'D', 'A'], answer: 0,
        hint: t('最后一个升号 D♯ 往上半音。', '最後のシャープ D♯ の半音上。', 'A half step above the last sharp, D♯.'),
        explain: t('D♯ 往上半音是 E：E 大调。', 'D♯ の半音上は E：E 長調。', 'A half step above D♯ is E: E major.') },
      { type: 'choice', ref: 'omt2e-major-scales',
        prompt: t('调号有四个降号（B♭ E♭ A♭ D♭），是哪个大调？', 'フラット 4 つ（B♭ E♭ A♭ D♭）の長調は？', 'Four flats (B♭ E♭ A♭ D♭) is which major key?'),
        options: ['A♭', 'D♭', 'E♭'], answer: 0,
        hint: t('倒数第二个降号。', '最後から 2 番目のフラット。', 'The second-to-last flat.'),
        explain: t('倒数第二个是 A♭：A♭ 大调。', '最後から 2 番目は A♭：A♭ 長調。', 'The second-to-last is A♭: A♭ major.') },
    ]),
    L(t('各调的大调音阶', '各調の長音階', 'Major scales in every key'), [
      { type: 'guide', ref: 'omt2e-major-scales',
        title: t('台阶不变，起点换', '段差は同じ、出発点だけ変わる', 'Same steps, new start'),
        steps: [
          t('任何大调都是 W W H W W W H。先写七个连续字母，再加升降号让台阶对上。', 'どの長調も W W H W W W H。7 つの文字を順に書き、変化記号で段差を合わせる。', 'Every major scale is W W H W W W H. Write seven letters in order, then add accidentals to fit.'),
        ] },
      G('majorDegree', 5),
    ]),
    L(t('调号练习', '調号の練習', 'Key-signature drill'), [
      { type: 'guide', ref: 'omt2e-major-scales', visual: { kind: 'circle', highlight: ['C'] }, tool: { feature: 'circle' },
        title: t('五度圈上数格子', '五度圏でマスを数える', 'Count steps on the circle'),
        steps: [
          t('五度圈把所有大调的调号按升降号个数排成一圈：顺时针升号越来越多，逆时针降号越来越多。', '五度圏は長調を調号の数の順に一周させたもの：時計回りでシャープ、反時計回りでフラットが増える。', 'The circle orders the major keys by accidentals: sharps grow clockwise, flats counterclockwise.'),
        ] },
      G('keySignature', 5),
    ]),
  ],


  minor: [
    L(t('三种小调练习', '3 つの短音階の練習', 'Three minor scales drill'), [
      { type: 'guide', ref: 'omt2e-minor', demo: { play: [[57], [59], [60], [62], [64], [65], [68], [69]], chord: [57, 60, 64, 68] },
        title: t('只改第 6、7 音', '第 6・7 音だけを変える', 'Only the 6th and 7th change'),
        steps: [
          t('自然小调 W H W W H W W；和声小调升高第 7 音；旋律小调上行升高第 6、7 音，下行还原。', '自然 W H W W H W W、和声は第 7 音を上げる、旋律は上行で 6・7 を上げ下行で戻す。', 'Natural W H W W H W W; harmonic raises 7; melodic raises 6 and 7 going up and restores them coming down.'),
          t('听：A 和声小调，最后是主音上的小大七和弦（A C E G♯）。', '聴いて：A 和声短音階、最後は主音上の短長七（A C E G♯）。', 'Listen: A harmonic minor, ending on the tonic minor-major seventh (A C E G♯).'),
        ] },
      G('minorScale', 4),
    ]),
    L(t('小调的级名', '短調の音度名', 'Degree names in minor'), [
      { type: 'guide', ref: 'omt2e-minor',
        title: t('导音与下主音', '導音と下主音', 'Leading tone versus subtonic'),
        steps: [
          t('小调的级名和大调几乎一样，只有一个例外：自然小调的第 7 音比主音低全音，叫"下主音"（唱 te）。', '短調の音度名はほぼ長調と同じ。例外は自然短音階の第 7 音で、主音の全音下なので「下主音」（te）。', 'Minor uses nearly the same degree names, with one exception: natural minor’s 7th, a whole step below the tonic, is the subtonic (te).'),
          t('升高后离主音只差半音，它就重新成为"导音"（ti）。小调新的唱名还有 me（降 3）、le（降 6）。', '上げると主音の半音下になり「導音」（ti）に戻る。短調の新しい階名には me（♭3）と le（♭6）も。', 'Raised to a half step below the tonic, it becomes the leading tone (ti) again. Minor also adds me (♭3) and le (♭6).'),
        ] },
      { type: 'choice', ref: 'omt2e-minor',
        prompt: t('A 自然小调的 G 叫？', 'A 自然短音階の G は？', 'In A natural minor, G is the…'),
        options: [t('下主音', '下主音', 'subtonic'), t('导音', '導音', 'leading tone'), t('属音', '属音', 'dominant')], answer: 0,
        hint: t('G 到 A 是全音。', 'G–A は全音。', 'G to A is a whole step.'),
        explain: t('离主音一个全音 = 下主音（te）；升成 G♯ 才是导音。', '主音の全音下 = 下主音（te）、G♯ にして導音。', 'A whole step below the tonic = subtonic (te); G♯ would be the leading tone.') },
      { type: 'match', ref: 'omt2e-minor',
        prompt: t('小调唱名 ↔ 级数', '短調の階名 ↔ 音度', 'Minor solfège ↔ degree'),
        pairs: [['me', '♭3'], ['le', '♭6'], ['te', '♭7']],
        hint: t('都是降低的音。', 'どれも下がった音。', 'All are lowered degrees.'),
        explain: t('me = ♭3，le = ♭6，te = ♭7。', 'me = ♭3、le = ♭6、te = ♭7。', 'me = ♭3, le = ♭6, te = ♭7.') },
      G('minorScale', 2),
    ]),
    L(t('关系调与同主音调练习', '平行調と同主調の練習', 'Relative and parallel drill'), [
      { type: 'guide', ref: 'omt2e-minor', visual: { kind: 'circle', highlight: ['C'], inner: ['A'] },
        title: t('两种"亲戚"', '2 種類の「親戚」', 'Two kinds of relatives'),
        steps: [
          t('关系调：调号相同（C 大调 ↔ a 小调），小调主音比大调主音低三个半音。', '平行調：調号が同じ（C 長調 ↔ a 短調）、短調の主音は長調の半音 3 つ下。', 'Relative: same signature (C major ↔ A minor); the minor tonic is three half steps lower.'),
          t('同主音调：主音相同（C 大调 ↔ c 小调），小调多三个降号。升降号的出现顺序两边一样。', '同主調：主音が同じ（C 長調 ↔ c 短調）、短調はフラットが 3 つ多い。変化記号の順は同じ。', 'Parallel: same tonic (C major ↔ C minor); the minor has three more flats. The order of accidentals is the same.'),
        ] },
      G('relativeParallel', 5),
    ]),
    L(t('小调里的和弦', '短調の和音', 'Chords in a minor key'), [
      { type: 'guide', ref: 'omt2e-roman-numerals', demo: { play: [[57, 60, 64], [62, 65, 68], [64, 68, 71], [57, 60, 64]] },
        title: t('升高导音改变了 V 和 vii', '導音を上げると V と vii が変わる', 'Raising the leading tone changes V and vii'),
        steps: [
          t('小调：i、ii°、III、iv、v、VI、VII。', '短調：i・ii°・III・iv・v・VI・VII。', 'Minor: i, ii°, III, iv, v, VI, VII.'),
          t('把导音升高后，v 变成大三和弦 V，VII 变成减三和弦 vii°。听：A 小调 i – ii° – V – i。', '導音を上げると v は長三和音 V、VII は減三和音 vii° に。聴いて：A 短調 i – ii° – V – i。', 'With the raised leading tone, v becomes major V and VII becomes diminished vii°. Listen: A minor i – ii° – V – i.'),
        ] },
      { type: 'choice', ref: 'omt2e-roman-numerals',
        prompt: t('A 小调里升高导音后，vii° 是哪个和弦？', 'A 短調で導音を上げたときの vii° は？', 'In A minor with the raised leading tone, vii° is…'),
        options: ['G♯ B D', 'G B D', 'G♯ B D♯'], answer: 0,
        hint: t('根音是升高的第 7 音 G♯。', '根音は上げた第 7 音 G♯。', 'Its root is the raised 7th, G♯.'),
        explain: t('G♯ B D：小三度 + 减五度 = 减三和弦。', 'G♯ B D：短 3 度 + 減 5 度 = 減三和音。', 'G♯ B D: minor third + diminished fifth = diminished triad.') },
      G('romanChord', 3),
    ]),
  ],

  modes: [
    L(t('特征音练习', '特徴音の練習', 'Colour-note drill'), [
      { type: 'guide', ref: 'omt2e-modes', tool: { feature: 'ref' },
        title: t('先写大调或小调，再改一个音', 'まず長調か短調、そして 1 音だけ変える', 'Write major or minor, then change one note'),
        steps: [
          t('Lydian = 大调升 4；Mixolydian = 大调降 7；Dorian = 自然小调升 6；Phrygian = 自然小调降 2；Locrian = 自然小调降 2 和降 5。', 'リディアン = 長調 ♯4、ミクソリディアン = 長調 ♭7、ドリアン = 自然短調 ♮6、フリジアン = 自然短調 ♭2、ロクリアン = 自然短調 ♭2・♭5。', 'Lydian = major ♯4; Mixolydian = major ♭7; Dorian = natural minor ♮6; Phrygian = natural minor ♭2; Locrian = natural minor ♭2 and ♭5.'),
          t('任何音都可以当起点：D♭ Mixolydian、G♭ Aeolian、F♯ Lydian 都成立，注意升降号。', 'どの音からでも作れる：D♭ ミクソリディアン、G♭ エオリアン、F♯ リディアンなど。変化記号に注意。', 'Any note can start a mode — D♭ Mixolydian, G♭ Aeolian, F♯ Lydian — mind the accidentals.'),
        ] },
      G('modeSpell', 5),
    ]),
    L(t('听辨调式', '旋法を聴き分ける', 'Hearing the modes'), [
      { type: 'guide', ref: 'omt2e-modes', demo: { play: [[60], [62], [64], [66], [67], [69], [71], [72]], chord: [60, 64, 67, 71] },
        title: t('先听三音，再找特征音', 'まず 3 度、次に特徴音', 'Third first, then the colour note'),
        steps: [
          t('大三度 = 亮的一组（Lydian、Ionian、Mixolydian）；小三度 = 暗的一组。', '長 3 度 = 明るい組（リディアン・イオニアン・ミクソリディアン）、短 3 度 = 暗い組。', 'Major third = the bright group (Lydian, Ionian, Mixolydian); minor third = the dark group.'),
          t('最后补的和弦是这个调式的主七和弦，可以帮你确认：C Lydian 结束在 C E G B（Cmaj7）。听。', '最後の和音はその旋法の主和音（七の和音）。C リディアンは C E G B（Cmaj7）で終わる。聴いて。', 'The closing chord is the mode’s tonic seventh chord: C Lydian ends on C E G B (Cmaj7). Listen.'),
        ] },
      G('modeEar', 5),
    ]),
    L(t('从亮到暗，一次只改一个音', '明→暗、1 回に 1 音だけ', 'Bright to dark, one note at a time'), [
      { type: 'guide', ref: 'omt2e-modes',
        title: t('调式的明暗阶梯', '旋法の明暗のはしご', 'The brightness ladder'),
        steps: [
          t('Lydian → Ionian：降低第 4 音；Ionian → Mixolydian：降低第 7 音；Mixolydian → Dorian：降低第 3 音。', 'リディアン → イオニアン：第 4 音を下げる、イオニアン → ミクソリディアン：第 7 音、ミクソリディアン → ドリアン：第 3 音。', 'Lydian → Ionian: lower the 4th; Ionian → Mixolydian: lower the 7th; Mixolydian → Dorian: lower the 3rd.'),
          t('Dorian → Aeolian：降低第 6 音；Aeolian → Phrygian：降低第 2 音；Phrygian → Locrian：降低第 5 音。每往暗走一步，都只降低一个音。', 'ドリアン → エオリアン：第 6 音、エオリアン → フリジアン：第 2 音、フリジアン → ロクリアン：第 5 音。暗くなるたびに 1 音だけ下げる。', 'Dorian → Aeolian: lower the 6th; Aeolian → Phrygian: the 2nd; Phrygian → Locrian: the 5th. Each darker step lowers just one note.'),
        ] },
      { type: 'choice', ref: 'omt2e-modes',
        prompt: t('Mixolydian 再暗一级变成 Dorian，降低的是第几个音？', 'ミクソリディアンを 1 段暗くしてドリアンにするには第何音を下げる？', 'Going one step darker from Mixolydian to Dorian lowers which note?'),
        options: [t('第 3 个音', '第 3 音', 'the 3rd'), t('第 6 个音', '第 6 音', 'the 6th'), t('第 2 个音', '第 2 音', 'the 2nd')], answer: 0,
        hint: t('从"亮"（大三度）变"暗"（小三度）。', '「明」（長 3 度）から「暗」（短 3 度）へ。', 'From bright (major third) to dark (minor third).'),
        explain: t('Mixolydian 1 2 3 4 5 6 ♭7 → Dorian 1 2 ♭3 4 5 6 ♭7：只降低了第 3 音。', 'ミクソ 1 2 3 4 5 6 ♭7 → ドリアン 1 2 ♭3 4 5 6 ♭7：第 3 音だけ。', 'Mixolydian 1 2 3 4 5 6 ♭7 → Dorian 1 2 ♭3 4 5 6 ♭7: only the 3rd drops.') },
      G('modeBrightness', 3),
    ]),
    L(t('调式配什么和弦', '旋法に合うコード', 'Which chord fits each mode'), [
      { type: 'guide', ref: ['omt2e-modes', 'omt2e-chord-scale'], tool: { feature: 'ref' }, demo: { play: [[62], [64], [65], [67], [69], [71], [72], [74]], chord: [50, 53, 57, 60] },
        title: t('1、3、5、7 音叠起来', '1・3・5・7 音を重ねる', 'Stack notes 1, 3, 5, 7'),
        steps: [
          t('取调式的第 1、3、5、7 个音，就是它的"主七和弦"：Ionian、Lydian → maj7；Mixolydian → 7；Dorian、Phrygian、Aeolian → m7；Locrian → m7♭5。', '旋法の 1・3・5・7 音が主和音：イオニアン・リディアン → maj7、ミクソリディアン → 7、ドリアン・フリジアン・エオリアン → m7、ロクリアン → m7♭5。', 'Notes 1, 3, 5, 7 give the tonic seventh: Ionian, Lydian → maj7; Mixolydian → 7; Dorian, Phrygian, Aeolian → m7; Locrian → m7♭5.'),
          t('这就是和弦音阶速查里的"和弦家族"。听：D Dorian，最后是 Dm7。', 'これが早見表の「コード・ファミリー」。聴いて：D ドリアン、最後は Dm7。', 'That is the chord family in the chord–scale reference. Listen: D Dorian, ending on Dm7.'),
        ] },
      G('scaleLibrary', 5, { ids: ['ionian', 'dorian', 'phrygian', 'lydian', 'mixolydian', 'aeolian', 'locrian'] }),
    ]),
  ],

  intervals: [
    L(t('听旋律音程', '旋律音程を聴く', 'Hearing melodic intervals'), [
      { type: 'guide', ref: 'omt-intervals', tool: { feature: 'ear' },
        title: t('先估宽窄', 'まず広さを見積もる', 'Estimate the width first'),
        steps: [
          t('旋律音程是先后弹的两个音。先判断是"近"（二、三度）、"中"（四、五度）还是"远"（六、七、八度）。', '旋律音程は順に鳴る 2 音。まず「近い」（2・3 度）「中くらい」（4・5 度）「遠い」（6・7・8 度）を判断。', 'A melodic interval sounds its notes one after the other. Judge close (2nds, 3rds), middle (4ths, 5ths) or far (6ths–octave).'),
        ] },
      G('intervalEar', 5),
    ]),
    L(t('听和声音程', '和声音程を聴く', 'Hearing harmonic intervals'), [
      { type: 'guide', ref: 'omt2e-intervals',
        title: t('同时响的两个音', '同時に鳴る 2 音', 'Two notes at once'),
        steps: [
          t('和声音程是同时响的两个音。纯五度、八度很"空"，三度六度很"甜"，二度七度很"挤"。', '和声音程は同時に鳴る 2 音。5 度・8 度は「空っぽ」、3 度・6 度は「甘い」、2 度・7 度は「ぶつかる」。', 'A harmonic interval sounds both notes together. Fifths and octaves sound open, thirds and sixths sweet, seconds and sevenths crowded.'),
        ] },
      G('intervalEar', 5, { harmonic: true, codes: ['m2', 'M2', 'm3', 'M3', 'P4', 'P5', 'm6', 'M6', 'm7', 'M7', 'P8'] }),
    ]),
    L(t('读谱上的音程', '楽譜の音程を読む', 'Reading intervals on the staff'), [
      { type: 'guide', ref: 'omt2e-intervals', visual: { kind: 'staff', notes: ['C4', 'E4'] },
        title: t('线间数度数', '線と間で度数を数える', 'Count lines and spaces for size'),
        steps: [
          t('两个音都在线上（或都在间里）：三度、五度、七度；一个在线一个在间：二度、四度、六度。', '2 音とも線上（か間）：3・5・7 度、片方が線で片方が間：2・4・6 度。', 'Both on lines (or both in spaces): 3rds, 5ths, 7ths; one line and one space: 2nds, 4ths, 6ths.'),
          t('再数半音决定大小：C–E 4 个半音是大三度，C–E♭ 3 个半音是小三度。', '半音を数えて種類を決める：C–E は半音 4 で長 3 度、C–E♭ は 3 で短 3 度。', 'Then count half steps for the quality: C–E has 4 (major third), C–E♭ has 3 (minor third).'),
        ] },
      G('intervalName', 5),
    ]),
    L(t('协和与不协和', '協和と不協和', 'Consonance and dissonance'), [
      { type: 'guide', ref: ['omt2e-intervals', 'omt2e-intro'],
        title: t('稳定的与需要解决的', '安定と解決を求めるもの', 'Stable versus needing resolution'),
        steps: [
          t('协和音程听起来稳定，不需要解决；不协和音程不稳定，想往别处去。这种分类会随时代和风格变化。', '協和音程は安定して解決を求めず、不協和音程は不安定で動きたがる。分類は時代や様式で変わる。', 'Consonances sound stable and need no resolution; dissonances are unstable and want to move. The categories shift with era and style.'),
          t('对位里：纯一、五、八度是完全协和；三、六度是不完全协和；二、七度和增减音程是不协和。', '対位法では：完全 1・5・8 度は完全協和、3・6 度は不完全協和、2・7 度と増減音程は不協和。', 'In counterpoint: perfect unisons, fifths, octaves are perfect consonances; thirds and sixths imperfect; seconds, sevenths, augmented and diminished intervals dissonant.'),
        ] },
      G('consonance', 4),
    ]),
  ],

  intervalqual: [
    L(t('增音程与减音程', '増音程と減音程', 'Augmented and diminished intervals'), [
      { type: 'guide', ref: 'omt2e-intervals', visual: { kind: 'staff', notes: ['C4', 'F#4'] },
        title: t('比纯、大大一点，比纯、小小一点', '完全・長より広く、完全・短より狭く', 'Wider than perfect or major, narrower than perfect or minor'),
        steps: [
          t('增 = 比纯音程或大音程再大半音；减 = 比纯音程或小音程再小半音。', '増 = 完全か長より半音広い、減 = 完全か短より半音狭い。', 'Augmented = half a step wider than perfect or major; diminished = half a step narrower than perfect or minor.'),
          t('所以 C–F♯ 是增四度，C–G♭ 是减五度：声音一样，度数不同。', 'C–F♯ は増 4 度、C–G♭ は減 5 度：音は同じで度数が違う。', 'So C–F♯ is an augmented fourth and C–G♭ a diminished fifth: same sound, different size.'),
        ] },
      { type: 'choice', ref: 'omt2e-intervals',
        prompt: t('C 到 G♯ 是什么音程？', 'C から G♯ は？', 'C up to G♯ is…'),
        options: [t('增五度', '増 5 度', 'augmented fifth'), t('小六度', '短 6 度', 'minor sixth'), t('纯五度', '完全 5 度', 'perfect fifth')], answer: 0,
        hint: t('先数字母：C D E F G。', 'まず文字：C D E F G。', 'Count letters: C D E F G.'),
        explain: t('五个字母 = 五度；C–G 是纯五度，G♯ 再大半音 = 增五度。（C–A♭ 声音一样，但叫小六度。）', '5 文字 = 5 度、C–G は完全 5 度、G♯ で半音広く増 5 度。（C–A♭ は同じ音でも短 6 度。）', 'Five letters = a fifth; C–G is perfect and G♯ is half a step wider: augmented fifth. (C–A♭ sounds the same but is a minor sixth.)') },
      G('intervalName', 3, { codes: ['A4', 'd5', 'P4', 'P5', 'm6', 'M3'] }),
    ]),
    L(t('转位练习', '転回の練習', 'Inversion drill'), [
      { type: 'guide', ref: 'omt2e-intervals',
        title: t('9 和翻面', '9 と裏返し', 'Nine and flip'),
        steps: [
          t('度数相加等于 9；大↔小，增↔减，纯还是纯。', '度数の合計 9、長↔短・増↔減・完全はそのまま。', 'Sizes add to 9; major ↔ minor, augmented ↔ diminished, perfect stays perfect.'),
          t('难认的音程可以先转位，换一个好认的音在下面。', '難しい音程は転回して、わかりやすい音を下にしてもよい。', 'For a tricky interval, invert it to put an easier note at the bottom.'),
        ] },
      G('intervalInvert', 5),
    ]),
    L(t('复音程', '複音程', 'Compound intervals'), [
      { type: 'guide', ref: 'omt2e-intervals', visual: { kind: 'staff', notes: ['C4', 'D5'] }, demo: { play: [[60], [74]] },
        title: t('超过八度的音程', 'オクターヴを超える音程', 'Intervals beyond an octave'),
        steps: [
          t('同度到八度之间的叫单音程，超过八度的叫复音程。', '1 度〜8 度は単音程、それを超えると複音程。', 'Unison to octave are simple intervals; anything larger is compound.'),
          t('复音程 = 八度 + 单音程：九度 = 八度 + 二度，十度 = 八度 + 三度，十一度 = 八度 + 四度。', '複音程 = オクターヴ + 単音程：9 度 = 8 度 + 2 度、10 度 = 8 度 + 3 度、11 度 = 8 度 + 4 度。', 'Compound = octave + simple: a 9th = octave + 2nd, a 10th = octave + 3rd, an 11th = octave + 4th.'),
        ] },
      { type: 'match', ref: 'omt2e-intervals',
        prompt: t('复音程 ↔ 八度加上', '複音程 ↔ オクターヴ + ', 'Compound ↔ octave plus'),
        pairs: [[t('九度', '9 度', '9th'), t('二度', '2 度', '2nd')], [t('十度', '10 度', '10th'), t('三度', '3 度', '3rd')], [t('十一度', '11 度', '11th'), t('四度', '4 度', '4th')], [t('十三度', '13 度', '13th'), t('六度', '6 度', '6th')]],
        hint: t('减去 7。', '7 を引く。', 'Subtract 7.'),
        explain: t('9 − 7 = 2，10 − 7 = 3，11 − 7 = 4，13 − 7 = 6。', '9 − 7 = 2・10 − 7 = 3・11 − 7 = 4・13 − 7 = 6。', '9 − 7 = 2, 10 − 7 = 3, 11 − 7 = 4, 13 − 7 = 6.') },
      { type: 'choice', ref: 'omt2e-intervals',
        prompt: t('C4 到 E5 是什么音程？', 'C4 から E5 は？', 'C4 up to E5 is…'),
        options: [t('大十度', '長 10 度', 'a major 10th'), t('大三度', '長 3 度', 'a major 3rd'), t('大九度', '長 9 度', 'a major 9th')], answer: 0,
        hint: t('一个八度再加上 C–E。', 'オクターヴ + C–E。', 'An octave plus C–E.'),
        explain: t('八度 + 大三度 = 大十度。', 'オクターヴ + 長 3 度 = 長 10 度。', 'Octave + major third = major tenth.') },
      G('intervalName', 2),
    ]),
    L(t('音程综合', '音程の総合', 'Interval mixed practice'), [
      { type: 'guide', ref: 'omt2e-intervals',
        title: t('度数 + 性质', '度数 + 種類', 'Size + quality'),
        steps: [
          t('先数字母定度数（升降号不影响度数），再数半音定性质。', 'まず文字を数えて度数（変化記号は関係ない）、次に半音で種類。', 'Count letters for size (accidentals don’t change it), then half steps for quality.'),
        ] },
      G('intervalName', 3), G('intervalInvert', 2), G('intervalEar', 2),
    ]),
  ],

  texture: [
    L(t('辨认四种织体', '4 つのテクスチュアを見分ける', 'Spotting the four textures'), [
      { type: 'guide', ref: 'omt2e-texture',
        title: t('数线条，看关系', '線を数え、関係を見る', 'Count the lines, check how they relate'),
        steps: [
          t('只有一条线 → 单声部。几条线是同一旋律的变体 → 支声。', '線が 1 本 → モノフォニー。同じ旋律の変形が何本も → ヘテロフォニー。', 'One line → monophony. Several variants of one tune → heterophony.'),
          t('几条线节奏一致、一起换和声 → 主调。几条线各有旋律和节奏 → 复调。', '線が同じリズムで和声を動かす → ホモフォニー。線ごとに旋律もリズムも違う → ポリフォニー。', 'Lines moving together through chords → homophony. Lines with their own melodies and rhythms → polyphony.'),
        ] },
      { type: 'choice', ref: 'omt2e-texture',
        prompt: t('一首歌：主唱唱旋律，吉他按和弦伴奏。最接近哪种织体？', '歌：ボーカルが旋律、ギターが和音で伴奏。どのテクスチュアに近い？', 'A song: a singer has the tune, a guitar strums chords. Which texture is closest?'),
        options: [t('主调', 'ホモフォニー', 'homophony'), t('单声部', 'モノフォニー', 'monophony'), t('复调', 'ポリフォニー', 'polyphony')], answer: 0,
        hint: t('伴奏只是和声支持，不是另一条独立旋律。', '伴奏は和声の支えで、独立した旋律ではない。', 'The accompaniment supports the harmony; it is not a separate melody.'),
        explain: t('一条主要旋律加和声伴奏，属于主调织体。', '主旋律 + 和声伴奏はホモフォニー。', 'A main melody over chordal accompaniment is homophony.') },
      { type: 'choice', ref: 'omt2e-texture',
        prompt: t('几个乐手同时奏同一首曲调，但每人加了自己的装饰，略有不同。这是？', '何人かが同じ旋律を同時に、それぞれ少し飾りを変えて演奏。これは？', 'Several players play the same tune at once, each decorating it a little differently. That is…'),
        options: [t('支声', 'ヘテロフォニー', 'heterophony'), t('复调', 'ポリフォニー', 'polyphony'), t('主调', 'ホモフォニー', 'homophony')], answer: 0,
        hint: t('还是"同一条旋律"。', 'あくまで「同じ旋律」。', 'It is still one melody.'),
        explain: t('同一旋律的多个变体同时出现 = 支声。', '同じ旋律の変形が同時に = ヘテロフォニー。', 'Variants of one melody at the same time = heterophony.') },
      { type: 'choice', ref: 'omt2e-texture',
        prompt: t('二部对位里两个声部各唱各的旋律，节奏也不一样。这是？', '2 声の対位法で、それぞれ別の旋律とリズム。これは？', 'In two-part counterpoint each part has its own melody and rhythm. That is…'),
        options: [t('复调', 'ポリフォニー', 'polyphony'), t('主调', 'ホモフォニー', 'homophony'), t('单声部', 'モノフォニー', 'monophony')], answer: 0,
        hint: t('独立的线条。', '独立した線。', 'Independent lines.'),
        explain: t('独立的旋律与节奏 = 复调。', '独立した旋律とリズム = ポリフォニー。', 'Independent melodies and rhythms = polyphony.') },
    ]),
    L(t('主调与四部和声', 'ホモフォニーと四声体', 'Homophony and four-part writing'), [
      { type: 'guide', ref: ['omt2e-texture', 'omt2e-roman-numerals'], tool: { feature: 'classical' },
        title: t('一起走的四个声部', '一緒に動く 4 声', 'Four voices moving together'),
        steps: [
          t('合唱的女高、女中、男高、男低一起换和弦，是典型的主调织体。', '合唱のソプラノ・アルト・テノール・バスが一緒に和音を変えるのは典型的なホモフォニー。', 'A choir’s soprano, alto, tenor and bass changing chords together is classic homophony.'),
          t('"古典和声连接器"就是在写这种四部和声；对位则更偏向复调。', '「古典和声連結」はこの四声体を書くツール。対位法はポリフォニー寄り。', 'The Classical Harmony tool writes this kind of four-part texture; counterpoint leans toward polyphony.'),
        ] },
      { type: 'choice', ref: 'omt2e-texture',
        prompt: t('赞美诗风格的四部合唱（四个声部节奏几乎一样）通常是？', '賛美歌風の四声合唱（リズムがほぼ同じ）はふつう？', 'Hymn-style four-part singing (all parts nearly the same rhythm) is usually…'),
        options: [t('主调', 'ホモフォニー', 'homophony'), t('支声', 'ヘテロフォニー', 'heterophony'), t('单声部', 'モノフォニー', 'monophony')], answer: 0,
        hint: t('四个声部同步换和弦。', '4 声が同時に和音を変える。', 'All four change chords together.'),
        explain: t('节奏一致、一起走和声 = 主调。', 'リズムが同じで和声を一緒に = ホモフォニー。', 'Same rhythm, moving through harmony together = homophony.') },
      { type: 'choice', ref: 'omt2e-texture',
        prompt: t('如果四个声部中有一个开始唱完全不同节奏的独立旋律，织体会往哪边偏？', '4 声の 1 つが全く違うリズムの独立した旋律を歌い始めたら？', 'If one of four parts starts singing an independent tune in a different rhythm, the texture shifts toward…'),
        options: [t('复调', 'ポリフォニー', 'polyphony'), t('单声部', 'モノフォニー', 'monophony'), t('支声', 'ヘテロフォニー', 'heterophony')], answer: 0,
        hint: t('独立的线条增加了。', '独立した線が増えた。', 'More independent lines.'),
        explain: t('声部越独立，就越接近复调。', '声部が独立するほどポリフォニーに近づく。', 'The more independent the parts, the closer to polyphony.') },
      { type: 'choice', ref: 'omt2e-texture',
        prompt: t('"主调"织体里的各声部……', 'ホモフォニーの各声部は……', 'In homophony, the voices…'),
        options: [t('以相同的步调一起换和声', '同じ歩調で一緒に和声を変える', 'move through the harmony at the same pace'), t('各自唱不同的旋律和节奏', 'それぞれ違う旋律とリズム', 'each sing different tunes and rhythms'), t('只有一个声部', '声部は 1 つだけ', 'are just one line')], answer: 0,
        hint: t('定义里的关键词："同样的步调"。', '定義のキーワードは「同じ歩調」。', 'The key phrase is “the same pace”.'),
        explain: t('主调：多个声部以相同步调一起移动和声。', 'ホモフォニー：複数の声部が同じ歩調で和声を動かす。', 'Homophony: several voices moving harmonically together at the same pace.') },
    ]),
    L(t('织体会变化', 'テクスチュアは変わる', 'Textures change'), [
      { type: 'guide', ref: 'omt2e-texture',
        title: t('一首曲子里换来换去', '1 曲の中で行き来する', 'Switching within one piece'),
        steps: [
          t('大多数音乐不会只停在一种织体，而是在它们之间移动。', 'たいていの音楽は 1 つのテクスチュアにとどまらず行き来する。', 'Most music doesn’t stay in one texture; it moves between them.'),
          t('例如：开头独唱（单声部），接着加入伴奏（主调），间奏几把乐器各奏各的（复调）。', '例：冒頭は独唱（モノ）、伴奏が入り（ホモ）、間奏で楽器がそれぞれ動く（ポリ）。', 'For example: a solo opening (monophony), accompaniment joins (homophony), an interlude where instruments weave lines (polyphony).'),
        ] },
      { type: 'match', ref: 'omt2e-texture',
        prompt: t('一首歌的段落 ↔ 织体', '曲の部分 ↔ テクスチュア', 'Song section ↔ texture'),
        pairs: [[t('无伴奏独唱的开头', '無伴奏の独唱で始まる', 'an unaccompanied solo opening'), t('单声部', 'モノフォニー', 'monophony')], [t('主唱 + 和弦伴奏', 'ボーカル + 和音伴奏', 'lead vocal + chords'), t('主调', 'ホモフォニー', 'homophony')], [t('几把乐器交织的独立旋律', '楽器が独立した旋律を織り合わせる', 'instruments weaving independent tunes'), t('复调', 'ポリフォニー', 'polyphony')]],
        hint: t('看有几条独立的线。', '独立した線がいくつあるか。', 'Count the independent lines.'),
        explain: t('同一首歌可以依次用到三种织体。', '同じ曲で 3 つのテクスチュアを順に使える。', 'One song can pass through all three textures.') },
      { type: 'choice', ref: 'omt2e-texture',
        prompt: t('"织体"描述的是？', '「テクスチュア」が表すのは？', 'Texture describes…'),
        options: [t('各声部的密度和相互关系', '声部の密度と関わり方', 'the density of voices and how they interact'), t('乐曲的速度', '曲の速さ', 'the tempo'), t('乐曲的调性', '曲の調', 'the key')], answer: 0,
        hint: t('想想"编织"。', '「織物」を思い浮かべて。', 'Think of weaving.'),
        explain: t('织体 = 声部的密度与相互作用。', 'テクスチュア = 声部の密度と相互作用。', 'Texture = the density of, and interaction between, voices.') },
      { type: 'choice', ref: 'omt2e-texture',
        prompt: t('一首曲子从头到尾都必须保持同一种织体吗？', '1 曲は最後まで同じテクスチュアでなければならない？', 'Must a piece keep one texture throughout?'),
        options: [t('不必，常常变化', 'いいえ、よく変わる', 'No, it often changes'), t('必须', 'はい', 'Yes')], answer: 0,
        hint: t('大多数音乐都在移动。', 'たいていの音楽は動く。', 'Most music moves.'),
        explain: t('大多数音乐都会在不同织体之间移动。', 'たいていの音楽はテクスチュアの間を移動する。', 'Most music moves between textures.') },
    ]),
    L(t('织体综合', 'テクスチュアの総合', 'Texture review'), [
      { type: 'guide', ref: 'omt2e-texture',
        title: t('四个名字，两个问题', '4 つの名前、2 つの問い', 'Four names, two questions'),
        steps: [
          t('问自己：有几条线？它们是同一旋律、一起走和声，还是各走各的？', '自問する：線は何本？同じ旋律か、一緒に和声を動かすか、別々か？', 'Ask: how many lines? Are they one tune, moving together, or independent?'),
        ] },
      { type: 'match', ref: 'omt2e-texture',
        prompt: t('织体 ↔ 关键词', 'テクスチュア ↔ キーワード', 'Texture ↔ keyword'),
        pairs: [[t('单声部', 'モノフォニー', 'monophony'), t('一条线', '線 1 本', 'one line')], [t('支声', 'ヘテロフォニー', 'heterophony'), t('同一旋律的变体', '同じ旋律の変形', 'variants of one tune')], [t('主调', 'ホモフォニー', 'homophony'), t('一起换和声', '一緒に和声を変える', 'chords together')], [t('复调', 'ポリフォニー', 'polyphony'), t('各自独立', 'それぞれ独立', 'independent lines')]],
        hint: t('"复"是"多条独立"。', '「ポリ」は「独立した複数」。', '“Poly” = several independent lines.'),
        explain: t('单声部一条线；支声是变体；主调一起走；复调各走各的。', 'モノは 1 本、ヘテロは変形、ホモは一緒、ポリは別々。', 'Monophony one line; heterophony variants; homophony together; polyphony independent.') },
      { type: 'choice', ref: 'omt2e-texture',
        prompt: t('卡农（几个声部先后唱同一旋律，彼此错开）最接近？', 'カノン（同じ旋律をずらして重ねる）に近いのは？', 'A canon (voices enter one after another with the same tune, offset) is closest to…'),
        options: [t('复调', 'ポリフォニー', 'polyphony'), t('主调', 'ホモフォニー', 'homophony'), t('单声部', 'モノフォニー', 'monophony')], answer: 0,
        hint: t('错开以后，每个声部在同一时刻唱的是不同的音和节奏。', 'ずれると各声部は同じ瞬間に違う音とリズム。', 'Offset, each voice sings different notes and rhythms at any moment.'),
        explain: t('错开的声部同时进行各自的旋律线，属于复调。', 'ずれた声部がそれぞれの旋律を同時に進めるのでポリフォニー。', 'Offset voices running their own lines simultaneously make polyphony.') },
      { type: 'choice', ref: 'omt2e-texture',
        prompt: t('全体齐唱同一条旋律、没有伴奏（大家唱得完全一样），属于？', '全員が同じ旋律を無伴奏で斉唱（まったく同じ）するのは？', 'Everyone singing one tune in unison with no accompaniment (exactly the same) is…'),
        options: [t('单声部', 'モノフォニー', 'monophony'), t('复调', 'ポリフォニー', 'polyphony'), t('主调', 'ホモフォニー', 'homophony')], answer: 0,
        hint: t('人很多，但只有一条线。', '人数は多くても線は 1 本。', 'Many voices, one line.'),
        explain: t('没有伴奏的一条旋律，不管多少人唱，都是单声部。', '伴奏のない旋律 1 本は、何人で歌ってもモノフォニー。', 'One unaccompanied melody is monophony however many sing it.') },
    ]),
  ],
  meter: [
    L(t('复拍子：每拍分三份', '複合拍子：1 拍を 3 つに', 'Compound meter: three per beat'), [
      { type: 'guide', ref: ['omt2e-compound-meter', 'wiki-metre'], visual: { kind: 'beats', groups: [3, 3] }, tool: { feature: 'rhythm' },
        title: t('6/8 不是"快的 3/4"', '6/8 は「速い 3/4」ではない', '6/8 is not “fast 3/4”'),
        steps: [
          t('复拍子的每一拍分成三份：6/8 是两拍（每拍三个八分音符），9/8 三拍，12/8 四拍。拍号上面的数字数的是"分拍"，不是拍子。', '複合拍子は 1 拍を 3 つに分ける：6/8 は 2 拍（各 8 分音符 3 つ）、9/8 は 3 拍、12/8 は 4 拍。上の数字は拍ではなく分割を数える。', 'In compound meter each beat splits in three: 6/8 is two beats (three eighths each), 9/8 three, 12/8 four. The top number counts divisions, not beats.'),
          t('3/4 是三拍、每拍分两份；6/8 是两拍、每拍分三份——音符总数一样，重音完全不同。复拍子常带"摇摆、舞蹈"的感觉，很多吉格舞、西西里舞曲用它。', '3/4 は 3 拍で各 2 分割、6/8 は 2 拍で各 3 分割：音符の数は同じでもアクセントが違う。複合拍子は舞曲らしく、ジーグやシチリアーナによく使われる。', '3/4 is three beats split in two; 6/8 is two beats split in three — same number of notes, different accents. Compound time feels lilting and dance-like, common in gigues and sicilianas.'),
        ] },
      { type: 'choice', ref: 'omt2e-compound-meter', visual: { kind: 'beats', groups: [3, 3, 3] },
        prompt: t('9/8 每小节有几拍？', '9/8 は 1 小節何拍？', 'How many beats per bar in 9/8?'),
        options: ['3', '9', '4'], answer: 0,
        hint: t('9 个八分音符，每三个一拍。', '8 分音符 9 つ、3 つで 1 拍。', 'Nine eighths, three per beat.'),
        explain: t('9 ÷ 3 = 3 拍：复三拍子。', '9 ÷ 3 = 3 拍：複合 3 拍子。', '9 ÷ 3 = 3 beats: compound triple.') },
      { type: 'choice', ref: 'wiki-metre',
        prompt: t('3/4 和 6/8 每小节都是 6 个八分音符，它们的区别是？', '3/4 と 6/8 はどちらも 8 分音符 6 つ。違いは？', '3/4 and 6/8 both hold six eighths. What differs?'),
        options: [t('3/4 是 3 拍×2；6/8 是 2 拍×3', '3/4 は 3 拍×2、6/8 は 2 拍×3', '3/4 is 3 beats × 2; 6/8 is 2 beats × 3'), t('完全一样', '同じ', 'nothing'), t('6/8 更快', '6/8 のほうが速い', '6/8 is faster')], answer: 0,
        hint: t('看重音怎么分组。', 'アクセントのまとまりを見る。', 'Look at how the accents group.'),
        explain: t('3/4：强弱弱三拍，每拍两个八分；6/8：两拍，每拍三个八分。', '3/4：3 拍で各 8 分 2 つ、6/8：2 拍で各 8 分 3 つ。', '3/4: three beats of two eighths; 6/8: two beats of three eighths.') },
      G('meterClass', 3),
    ]),
    L(t('不对称拍子：5/8、7/8', '不均等な拍子：5/8・7/8', 'Asymmetrical meters: 5/8, 7/8'), [
      { type: 'guide', ref: ['omt2e-20c-rhythm', 'wiki-metre'], visual: { kind: 'beats', groups: [2, 2, 3] }, tool: { feature: 'rhythm' },
        title: t('长短不一的拍子', '長さの違う拍', 'Beats of unequal length'),
        steps: [
          t('不对称拍子把一小节分成长短不等的组，脉搏变得"一长一短"。5 拍常分成 2+3 或 3+2，7/8 可以是 2+2+3 等。', '不均等な拍子は小節を長さの違うまとまりに分け、脈が「長・短」になる。5 拍はよく 2+3 か 3+2、7/8 は 2+2+3 など。', 'Asymmetrical meters divide the bar into unequal groups, giving a long–short pulse. Five often splits 2+3 or 3+2; 7/8 can be 2+2+3 and so on.'),
          t('它也叫"混合拍子""复杂拍子"或"aksak"（土耳其语"跛行"）；巴尔干音乐里很常见，20 世纪的作曲家也用得越来越多。', '「混合拍子」「複雑な拍子」「アクサク」（トルコ語で「足を引きずる」）とも呼ばれ、バルカン音楽に多く、20 世紀の作曲家も多用した。', 'They are also called mixed or complex meters, or aksak (Turkish for “limping”); common in Balkan music and increasingly used by 20th-century composers.'),
        ] },
      G('additiveMeter', 4),
    ]),
    L(t('变拍子与复合节拍', '変拍子とポリメーター', 'Changing meter and polymeter'), [
      { type: 'guide', ref: ['omt2e-20c-rhythm', 'wiki-metre'], visual: { kind: 'beats', groups: [3, 2, 3, 2, 2] },
        title: t('拍号一直在换', '拍子が次々変わる', 'The time signature keeps changing'),
        steps: [
          t('变拍子：乐曲里不断更换拍号。斯特拉文斯基《春之祭》的结尾就是有名的例子（3/16、2/16、3/16……）。', '変拍子：曲の中で拍子が次々変わる。ストラヴィンスキー『春の祭典』の終わりが有名（3/16・2/16・3/16……）。', 'Changing meter switches time signatures throughout; the end of Stravinsky’s Rite of Spring is a famous example (3/16, 2/16, 3/16…).'),
          t('复合节拍（polymeter）：两种拍子同时进行。节拍转换（metric modulation）：用旧速度里的某个时值去对上新速度的时值，让速度变化变得平滑。', 'ポリメーター：2 つの拍子を同時に。メトリック・モジュレーション：古い速さのある音価を新しい速さの音価に合わせ、テンポの変化をなめらかにする。', 'Polymeter runs two meters at once. Metric modulation smooths a tempo change by matching a duration in the old tempo to one in the new.'),
        ] },
      { type: 'match', ref: 'omt2e-20c-rhythm',
        prompt: t('术语 ↔ 意思', '用語 ↔ 意味', 'Term ↔ meaning'),
        pairs: [[t('变拍子', '変拍子', 'changing meter'), t('拍号不断更换', '拍子が次々変わる', 'the time signature keeps changing')], [t('复合节拍', 'ポリメーター', 'polymeter'), t('两种拍子同时进行', '2 つの拍子が同時', 'two meters at once')], [t('节拍转换', 'メトリック・モジュレーション', 'metric modulation'), t('借共同时值平滑地换速度', '共通の音価でテンポを滑らかに変える', 'a shared duration smooths a tempo change')], [t('无拍子', 'アメトリック', 'ametric'), t('听不出任何拍子', '拍子が感じられない', 'no perceivable meter')]],
        hint: t('"poly" = 多个同时。', '「ポリ」= 複数同時。', '“Poly” = several at once.'),
        explain: t('变拍子换拍号、复合节拍同时叠拍号、节拍转换换速度、无拍子没有可感知的拍子。', '変拍子は拍子を変え、ポリメーターは重ね、メトリック・モジュレーションはテンポを変え、アメトリックは拍子がない。', 'Changing meter switches signatures, polymeter layers them, metric modulation changes tempo, ametric music has no perceivable meter.') },
      { type: 'choice', ref: 'wiki-metre',
        prompt: t('《春之祭》结尾连续出现 3/16、2/16、3/16……这叫？', '『春の祭典』の終わりで 3/16・2/16・3/16……と続くのは？', 'The Rite of Spring ends with 3/16, 2/16, 3/16… This is…'),
        options: [t('变拍子', '変拍子', 'changing meter'), t('复拍子', '複合拍子', 'compound meter'), t('切分', 'シンコペーション', 'syncopation')], answer: 0,
        hint: t('拍号一直在换。', '拍子が変わり続ける。', 'The time signature keeps changing.'),
        explain: t('不断更换拍号 = 变拍子（也叫混合拍子）。', '拍子を変え続ける = 変拍子（混合拍子とも）。', 'Constantly switching signatures = changing (mixed) meter.') },
      { type: 'choice', ref: 'omt2e-20c-rhythm',
        prompt: t('谱面写的拍子和听众感觉到的拍子不一样，这种情况叫？', '書かれた拍子と聴こえる拍子が違うのは？', 'When the notated meter differs from what listeners feel, it is a question of…'),
        options: [t('感知拍子与记谱拍子', '知覚される拍子と記譜上の拍子', 'perceived versus notated meter'), t('复合节拍', 'ポリメーター', 'polymeter'), t('节拍转换', 'メトリック・モジュレーション', 'metric modulation')], answer: 0,
        hint: t('看的和听的不一样。', '見たものと聴こえるものが違う。', 'What you see versus what you hear.'),
        explain: t('谱上写的不一定就是听到的拍子：这是感知拍子与记谱拍子的问题。', '書かれたものが聴こえる拍子とは限らない：知覚と記譜の問題。', 'The written meter isn’t always what is heard: perceived versus notated meter.') },
    ]),
    L(t('拍子综合', '拍子の総合', 'Meter review'), [
      { type: 'guide', ref: ['omt2e-simple-meter', 'omt2e-compound-meter'], tool: { feature: 'rhythm' },
        title: t('两个问题定拍子', '2 つの質問で拍子が決まる', 'Two questions decide a meter'),
        steps: [
          t('每拍分两份 → 单拍子；分三份 → 复拍子。每小节两拍 → 二拍子；三拍 → 三拍子；四拍 → 四拍子。其他分法按"加法"来看。', '1 拍を 2 つ → 単純、3 つ → 複合。1 小節 2 拍 → 2 拍子、3 拍 → 3 拍子、4 拍 → 4 拍子。それ以外は「加算」で考える。', 'Beat in two → simple; in three → compound. Two beats per bar → duple, three → triple, four → quadruple. Anything else is additive.'),
        ] },
      G('meterClass', 3), G('additiveMeter', 2),
    ]),
  ],

};
