// 套路和弦进行速查 · 条目说明的日文（理论解释 theory、适用限制 limits、变体关系 how、规范化说明 note）
// 内容与依据和 prog_library_data.js 里的中文、英文完全对应；prog_library_data.js 导入后合并进各条目
export const ENTRY_JA = {
  'u-4361': { theory: '4 つとも音階内の和音で根音は F E A C。iii と vi は主の働きの延長で、最後は I に着くが属和音を通らない。完全な終止かどうかはフレーズの位置と旋律次第', limits: 'V–I がないので正格終止ではない' },
  'u-14736251': { theory: '根音がずっと 5 度ずつ下がり（F から B は 1 度だけ減 5 度）、音階内の 7 つの和音を巡って主和音に戻る。7 は vii° で B の長三ではない。最後の ii–V–I は正格の帰着' },
  'u-62514736': { theory: '14736251 と同じ 5 度の連鎖を vi から始めて vi に戻る。始まりも終わりも Am なので Am が主に聞こえることも、C のままに聞こえることもある', how: '同じ 5 度の連鎖、始まりを変える' },
  'u-4536251': { theory: '王道型 IV–V–iii–vi に ii–V–I の終止を続けたもの。IVM7–V7–iii7–vi–ii7–V7–I は長調の 5 度下行の連鎖全体と説明される（V7 が vii° の代わり）', how: '4536 に ii–V–I を続ける' },
  'u-15634145': { theory: 'パッヘルベルのカノンのバスが示す 8 つの和音 I–V–vi–iii–IV–I–IV–V（ロマネスカという反復進行の型）。最後は V で止まり、ループでは I に戻る' },
  'i1-IV-iv-I': { theory: 'iv は同主短調から借りた小下属。F A C → F A♭ C → C E G で内声に A–A♭–G の半音下行、働きは下属から主のまま' },
  'i1-IV-iv-iii': { theory: '同じく借用の iv。内声 A–A♭–G が E G B の G に着いて iii で止まり、主和音に戻らない。先へ続く断片' },
  'i1-ii-iii-iv-V': { theory: '根音 D E F G が順次上行し、3 つ目で iv（A♭）を借用、最後は V で止まって次のフレーズを待つ', limits: 'V で止まる半終止的な宙づりで、完結ではない' },
  'i1-bVII-V': { theory: '♭VII は te（B♭）を含み、続く V で ti（B）に戻る。同じ音度の 2 つの色が続けて現れ、V で止まる' },
  'i1-bVII-IV': { theory: '局所的な変格関係（♭VII は IV の IV）とも、ダブル・プラガル ♭VII–IV–I の前半とも見られる。働きは文脈次第で、単独では決められない' },
  'i1-bVI-V': { theory: '長調では ♭VI は借用和音で、根音 A♭ が半音下の G へ。短調では ♭VI–V はどちらも本来の和音（フリギア的な半音のバス）。2 つの文脈の解釈は分けて考える' },
  'i1-iii-bIII-ii': { theory: '根音 E–E♭–D が半音で下がり、真ん中の ♭III（E♭ G B♭）が iii と ii をすべるようにつなぐ' },
  'i1-bVI-bVII-I': { theory: 'エオリアン・カデンツの長三の主和音版。♭VI と ♭VII はどちらも借用した長三和音で、根音 A♭ B♭ C が順次上行して主和音へ持ち上がる' },
  'i2-ii-V-iii-vi': { theory: '王道型の最初の IV を同じ下属の ii に代えたもの', how: 'IV を ii に' },
  'i2-IV-V-III-vi': { theory: 'iii を長三の III（E G♯ B）に。G♯ が A を指し、vi の副属 V/vi になる', how: 'iii を副属 III に' },
  'i2-ii-V-iii-VI': { theory: '最後の VI（A C♯ E）は ii に戻れば V/ii。単独の断片としてはその可能性にとどまり、解決したとは言えない' },
  'i2-IV-viio7-III-vi': { theory: 'Bm7♭5–E–Am は vi（イ短調）を指す局所的な iiø7–V–i と聞ける。この部分だけで全体がイ短調に転調したとは言えない', note: '画像の VIIø には 7 が書かれていない。ø はふつうハーフ・ディミニッシュの七の和音を表すので viiø7（Bm7b5）に正規化した' },
  'i2-IV-ivmM7-iii-vi': { theory: '借用の iv に長 7 度 E が付く。長調の mi（E）と le（A♭）が同時に鳴り、色はより暗く緊張する', note: 'IVmΔ7 は短三和音に長 7 度：ハ調で F A♭ C E。Fm7 の F A♭ C E♭ ではない' },
  'i2-IV-iv7-iii-bIII': { theory: '借用の iv7 のあと根音 E–E♭ が半音で ♭III へ下がり、借用和音で止まる。終止しない断片' },
  'i2-IV-V-iiio7-VI7': { theory: 'Em7♭5–A7 が Dm へ進めば ii を指す局所的な iiø7–V7–i。続かない時はその可能性にとどまる', note: '画像の IIIø には 7 がないので iiiø7（Em7b5）に正規化。VI7 は A7 で Am7 ではない' },
  'i2-IV-V-#vo7-VI7': { theory: 'バス F G G♯ A が半音で上行。G♯dim7（G♯ B D F）は A の導七の和音。A7–Dm との関係は後の進み方次第で、1 つの和音だけで転調とは判断できない' },
  'i3-141': { theory: '主–下属–主。IV–I は変格の動き。I–IV–I だけでは主和音の延長にすぎないこともあり、完全な変格終止とは限らない' },
  'i3-151': { theory: '主–属–主。V–I は正格の動き。完全な終止になるかはフレーズの位置と旋律次第' },
  'i3-1451': { theory: 'T–PD–D–T の基本的なフレーズ・モデル' },
  'i3-251': { theory: '根音 D G C が 2 回 5 度下行、PD–D–T。ジャズの七の和音版は Dm7–G7–Cmaj7' },
  'i3-1625': { theory: 'doo-wop 型 I–vi–IV–V の IV を ii に代えたもの。ジャズでいちばん多いターンアラウンド I–vi–ii–V でもあり、V で止まって I に戻る' },
  'i3-1541': { theory: 'V のあと I に戻らず IV に落ち、IV–I で帰る。ブルースの 3 つ目のフレーズ V–IV–I と同じ進み方' },
  'i3-4536': { theory: '王道進行の三和音形 IV–V–iii–vi。七の和音の元の形は IVM7–V7–iii7–vi' },
  'i3-6451': { theory: 'vi から始まり IV–V を経て I へ。終わりは V–I の正格の動き' },
  'i3-1564': { theory: 'I–V–vi–IV（Axis 進行。OMT の singer/songwriter 型のローテーションの 1 つ）。6415・4156・5641 は同じ和音のローテーション' },
  'i3-6415': { theory: 'singer/songwriter 型 vi–IV–I–V。正格終止がなく、主音は C にも Am にも聞こえうる（調性のあいまいさ）', how: 'ローテーション' },
  'i3-46': { theory: '2 つの和音は A と C を共有し、局所的なつなぎにすぎない' },
  'i3-61': { theory: 'vi と I は C と E を共有し、どちらも主の働き。同じ働きの中での色の変化' },
  'i3-54': { theory: '属のあと下属に戻るのは解決ではない。ブルースの 3 つ目のフレーズが V–IV–I' },
  'x-5641': { theory: 'Axis 進行の別のローテーション V–vi–IV–I', how: 'ローテーション' },
  'x-1645': { theory: 'doo-wop 型（’50s 進行）I–vi–IV–V。vi が主の働きを延長し、バス C A F が 3 度で下がる' },
  'x-1345': { theory: '始まりの I–iii–IV がパフ型で、そのあと V' },
  'x-1465': { theory: '音階内の 4 つの和音。明るい（I IV）と暗い（vi）が交互に現れ、V で止まる' },
  'x-1524': { theory: 'I–V–vi–IV の vi を ii に代えたよくある変形', how: 'vi を ii に' },
  'x-1624': { theory: 'V がなく主と下属だけなので、属の緊張は弱い' },
  'x-2415': { theory: '6415 の vi を ii に代えた形。最後は V で止まる' },
  'x-4156': { theory: 'singer/songwriter 型を IV から始めたローテーション。最後の V–vi は偽終止の進み方', how: 'ローテーション' },
  'x-4125': { theory: 'IV–I で主和音に戻ったあと、ii–V で次の周へ押し出す' },
  'x-1364': { theory: '隣り合う和音はそれぞれ 2 音を共有（C E G → E G B → A C E → F A C）' },
  'x-1415': { theory: '主・下属・主・属が交互に現れ、V で止まって I に戻る' },
  'x-451': { theory: 'PD–D–T、根音 F G C' },
  'x-456': { theory: 'V のあと I でなく vi へ行く、偽終止の進み方' },
  'x-1245': { theory: '根音 C D F G が上行し、下属の和音 2 つのあと V で止まる' },
  'x-164251': { theory: 'doo-wop の骨組みの IV のあとに ii を加え、ii–V–I で終わる' },
  'x-canon-bass': { theory: 'カノン型の骨組みに転回形を加え、バスがずっと順次で下がる。最後から 2 つ目はカノン本来の IV の代わりに ii（同じ下属の働き）。/3 /5 は和音の 3 音・5 音がバスにあることで、G/B の根音は G のまま', how: '転回形を加えてバスを順次進行に', note: '原文は iii/5 だが、ハ調の例 Em/G とバスライン C-B-A-G-F-E-D-G はどちらもバスが 3 音 G であることを示すので iii/3 に正規化した。iii/5 なら Em/B でバスは順次でなくなる' },
  'm-i-iv-V-i': { theory: 'V は上がった導音 B♮ を使い、C への引力を生む' },
  'm-i-iv-v-i': { theory: '短い v（G B♭ D）には導音がなく、V より引力が弱い' },
  'm-i-bVI-bIII-bVII': { theory: 'singer/songwriter 型の短調読み i–VI–III–VII。ハ長調の vi–IV–I–V（Am F C G）と移調すれば型は似ているが、ここでは主音が C で表記の基準が違う', how: '同じ型の短調読み（主音が違う）' },
  'm-aeolian-shuttle': { theory: 'エオリアン・シャトル：i と ♭VI の間を往復し、♭VII が経過する' },
  'm-i-bVI-iv-V': { theory: '♭VI と iv はどちらも下属の側。最後の V は導音を含む' },
  'm-andalusian': { theory: 'アンダルシア進行 i–♭VII–♭VI–V（ラメント型のよくある和声付けでもある）。名前に終止とあるが、ふつうは繰り返すオスティナートとして使われる' },
  'm-long-narrative': { theory: '根音の動きはカノン型と同じ（4 度下・2 度上の交互）で、それを短調に置いたもの。最後は導音を含む V' },
  'm-circle': { theory: '短調の 5 度の連鎖 i–iv–VII–III–VI–ii°–V–i（ここでは同主長調基準で ♭VII ♭III ♭VI と書く）' },
  'm-aeolian-cadence': { theory: 'エオリアン・カデンツ ♭VI–♭VII–i：目標のある終止で、ループにはあまり使わない。ピカルディの 3 度ですべて長三和音になることが多い' },
  'm-iv-V-i': { theory: 'PD–D–T の短調版。V は導音を含む' },
  'm-iio-V-i': { theory: '短調の ii° V i。七の和音版は Dm7♭5–G7–Cm で、主和音に 7 を加えるなら Cm7 か Cm(maj7) を選べる' },
  'm-i-V-bVI-iv': { theory: 'V のあと i に戻らず ♭VI へ行く、短調の偽終止的な進み方' },
  'r-double-plagal': { theory: 'ダブル・プラガル ♭VII–IV–I（ミクソリディアの型）の前に I を加えたもの' },
  'r-I-bVII-IV': { theory: 'ミクソリディアの ♭VII に IV。ループで IV から I に戻ればダブル・プラガル' },
  'r-I-IV-bVII-IV': { theory: 'V がなく ♭VII が属の側を担い、和音は I IV ♭VII の間を横に動く' },
  'r-I-bIII-IV-I': { theory: '♭III の me（E♭）が長い主和音の mi とぶつかる。ブルースでは長短の 3 度をよく混ぜる' },
  'r-I-bVI-bVII-I': { theory: 'エオリアン・カデンツの長い主和音版の前に I を加えたもの', how: '前に I を加える' },
  'r-dorian-shuttle': { theory: 'ドリアン・シャトル：短い主和音と長い IV の往復。長い IV の la（A♮）がドリアの特徴音で、全体は主和音の延長' },
  'r-i-bVII-IV-i': { theory: '短い主和音に長い IV（la）でドリアを示す。♭VII は自然短音階とドリアに共通の和音' },
  'r-phrygian': { theory: 'フリギア旋法は自然短音階の第 2 音を下げた（ra）もの。♭II（D♭ F A♭）はこの音を含み、主音と半音になる' },
  'r-lydian-cadence': { theory: 'II–IV–I はリディアン・カデンツ。II の fi（F♯）はすぐ IV の fa（F）で打ち消されるので、リディアの色にすぎず、全体がリディアではない' },
  'r-lydian-shuttle': { theory: 'リディアン・シャトル I–II。II が V に進むなら副属 V/V と見るべき。ポップスでは II が実は別の調の IV–V のこともあるので、続きを確かめる' },
  'r-mixolydian-v': { theory: '短い v（G B♭ D）は te を含み、ミクソリディアの重要な和音' },
  'b-I-IV-iv-I': { theory: 'IV を借用の iv に代えて I に戻る：A–A♭–G', how: '前に I を加える' },
  'b-I-iv-I': { theory: '借用の iv による変格の動き' },
  'b-IV-iv-I3': { theory: '最後を C/E に：バスが 3 音 E に着き、基本形より柔らかく終わる', how: '最後の和音を転回形に' },
  'b-I-bVI-IV-V': { theory: 'vi を借用の ♭VI に（根音が le になる）。働きは主と下属の間のまま', how: 'vi を ♭VI に' },
  'b-I-bIII-IV-V': { theory: 'iii を借用の ♭III に代え、根音 C E♭ F G が上行', how: 'iii を ♭III に' },
  'b-I-bII-I': { theory: '♭II の根音 D♭ は主音の半音上で、長い主和音の間に半音の隣接音を作る' },
  'b-backdoor-triad': { theory: '裏口進行 iv7–♭VII7–I の三和音の骨組み', how: '第 7 音を除く' },
  'b-passing-dim': { theory: 'C と Dm の間に C♯dim を挿入：バス C C♯ D が半音で上行（七の和音版は C♯dim7）' },
  'b-aug': { theory: 'C E G → C E G♯ → C E A：第 5 音 G G♯ A が半音で上行' },
  'b-line-cliche': { theory: 'マイナーのライン・クリシェ：m・m(maj7)・m7・m6。主音から半音で C B B♭ A と下がり、根音は動かない', note: 'ここの i6 はポップスのコード記号 Cm6（短三和音に長 6 度）で、古典のローマ数字の i6（第 1 転回形）ではない。当サイトでは 2 つの表記を分けるため i(add6) と書く' },
  'b-puff-III': { theory: 'パフ型の変形 I–III♯–IV のあとに借用の iv：内声 sol–si–la（G G♯ A）、そして A–A♭' },
  'j-I-VI-ii-V': { theory: 'I–VI–ii–V：VI の 3 音 C♯ で C C♯ D と半音上行し、VI は V/ii', how: 'vi を副属 VI に' },
  'j-iii-VI-ii-V': { theory: 'iii–VI–ii–V はよくあるターンアラウンドで、根音が続けて 5 度下行' },
  'j-I-III-vi-II-ii-V-I': { theory: 'III は V/vi、II は V/V。II のあとまず ii、それから V。同じ根音が長から短へ' },
  'j-II-V-I': { theory: 'II は V/V（D F♯ A）。七の和音版の II は D7 で、音階内の ii の Dm7 ではない' },
  'j-VI-II-V-I': { theory: 'ラグタイム進行 V7/vi–V7/ii–V7/V–V7–I の後半 4 つ。副属の連鎖' },
  'j-ii-V-I-vi': { theory: 'ii–V–I のあと vi が ii に戻ってループになる' },
  'j-I-vi-ii-V-I': { theory: 'I–vi–ii–V から I に戻る。vi ii V I は 5 度の連鎖の最後の部分', how: 'I に戻って終わる' },
  'j-ii7-V7-Imaj7': { theory: '長調の ii–V–I の和音の性質 m7–7–maj7', how: '七の和音の元の形' },
  'j-iio7-V7-i7': { theory: '短調の ii–V–I の和音の性質 ø7–7–m7' },
  'j-iio7-V7-imM7': { theory: '主和音を m(maj7) に：V7 の導音 B♮ を保ち、m7 より緊張した色', how: '主和音を m(maj7) に' },
  'j-tritone': { theory: 'G7 を D♭7 に：G7 の B F と D♭7 の C♭ F は同じ 3 全音（異名同音）。根音は D D♭ C と半音で下がる', how: 'V7 のトライトーン代理' },
  'j-backdoor': { theory: '裏口進行 iv7–♭VII7–I：♭VII7 は同主短調から来て G7 と共通音が 2 つ。A♭ と F が上からの導音として G と E へ解決する' },
  'j-Imaj7-VI7-ii7-V7': { theory: 'VI7 = A7 は V7/ii。今の奏者は I–VI–II–V の VI を属七で弾くことが多い', how: '七の和音と副属' },
  'j-iii7-VI7-ii7-V7': { theory: '根音 E A D G が続けて 5 度下行。3 音と第 7 音が順次でつながる', how: '七の和音の元の形' },
  'j-royal-7': { theory: '王道進行の七の和音形 IVM7–V7–iii7–vi7', how: '七の和音の元の形' },
  'bl-12': { theory: '12 小節ブルース：4 小節のフレーズ 3 つ I–IV–I–V–IV–I。七の和音版はすべて属七 I7 IV7 V7（ブルースでは属七がどの働きにもなる）' },
  'bl-quick': { theory: 'クイック・チェンジ（クイック・トゥ・フォー）：2 小節目で先に IV へ', how: '2 小節目を IV に' },
  'bl-minor': { theory: 'マイナー・ブルース：i と iv はマイナー・セブンス、V は属七のまま。3 つ目の V–IV–I はよく ii–V–I に代わる。9 小節目の iiø7 は OMT の文章の説明に基づく例' },
  'bl-jazz': { theory: 'ジャズ・ブルースは 8 小節目に副属（9 小節目の ii を指す）、3 つ目を ii–V–I に。具体的な和音はいろいろあり、これは OMT の文章の説明に基づく簡略な例' },
  'bl-turnaround': { theory: 'ブルースの終わりのターンアラウンドは V7 1 つだけのことも、完全な III–VI–II–V（属七の連鎖）のこともある' },
  'bl-shuffle': { theory: '12 小節ブルースの 3 つ目 V–IV–I–I（シャッフル・ブルース型）。変格の動きで終わる' },
  'x-hopscotch': { theory: 'hopscotch 型 IV–V–vi–I：根音は順次・順次・跳躍。singer/songwriter 型と同じく調性があいまいで、C に入る時に明確な終止はふつうない' },
  'x-puff': { theory: 'パフ型 I–iii–IV はふつうフレーズの始まりに現れ、IV のあとに何が来るかは決まっていない' },
};
