// 套路和弦进行速查 · 资料库（结构化数据；进行的和弦由 prog_library.js 解析生成）
// 三类说明分开存放：
//   original  来源图片里的原始写法与原图听感 / 场景（用户提供的参考资料 原文照录 不改写）
//   theory    经核对的理论解释（每条注明依据 ref）
//   suggested 补充的建议听感（不是图片原文；用户给出的建议听感与本站补充的都放这里）
// 听感不是固定结论：速度 节奏 配器 音区 旋律 和声节奏 转位与力度都会改变听感，标签只是常见倾向
// 罗马数字区分大小写；小调条目一律按平行大调参照写（C 小调的 Cm Ab Bb = i ♭VI ♭VII）
// 依据：
//   四和弦套路（doo-wop、singer/songwriter、hopscotch、旋转与代理）：ref:omt-pb-4chord
//   古典套路在流行音乐里（lament、五度链）：ref:omt-pb-classical-schemas
//   和弦替代（副属、调式混合、三全音替代）：ref:omt-pb-substitutions
//   调式套路（双重变格、subtonic shuttle、aeolian shuttle / cadence、dorian shuttle、lydian shuttle / cadence）：ref:omt-pb-modal-schemas
//   puff 套路（I–iii–IV、I–III♯–IV）：ref:omt-pb-puff
//   布鲁斯（12 小节、全部属七、小调布鲁斯、爵士布鲁斯、turnaround）：ref:omt-pb-blues ref:wiki-twelve-bar
//   五度链进行 I–IV–vii°–iii–vi–ii–V–I 与小调 i–iv–VII–III–VI–ii°–V–i：ref:wiki-circle-progression
//   Axis 进行与四种旋转：ref:wiki-axis-progression；'50s 进行 I–vi–IV–V：ref:wiki-50s-progression
//   王道进行 IVM7–V7–iii7–vi 及其变体：ref:wiki-royal-road
//   帕赫贝尔卡农的八个和弦 I–V–vi–iii–IV–I–IV–V：ref:wiki-pachelbel-canon
//   turnaround 的常见写法：ref:wiki-turnaround；ragtime 进行 V7/vi–V7/ii–V7/V–V7–I：ref:wiki-ragtime-progression
//   后门进行 iv7–♭VII7–I：ref:wiki-backdoor；安达卢西亚进行：ref:wiki-andalusian-cadence
//   小调 line cliché（m、m(maj7)、m7、m6）：ref:djangobooks-line-cliche
//   ii–V–I 的和弦性质：ref:omt2e-iivi；调式混合：ref:omt2e-mixture；副属：ref:omt2e-tonicization
//   弗里吉亚的 ♭2（ra）：ref:omt2e-modes；减七半音终止：ref:wiki-cadence

import { ENTRY_JA } from './prog_library_ja.js';

const t = (zh, en) => ({ zh, en });

/** 听感标签（可以多选 只是常见倾向） */
export const FEEL_TAGS = {
  warm: { zh: '温暖', ja: '温かい', en: 'warm' },
  calm: { zh: '平静', ja: '穏やか', en: 'calm' },
  bright: { zh: '明亮', ja: '明るい', en: 'bright' },
  nostalgic: { zh: '怀旧', ja: '懐かしい', en: 'nostalgic' },
  melancholy: { zh: '忧郁', ja: '憂うつ', en: 'melancholy' },
  sorrow: { zh: '哀愁', ja: '哀愁', en: 'wistful' },
  open: { zh: '开阔', ja: '開放的', en: 'open' },
  suspense: { zh: '悬念', ja: '宙づり', en: 'suspense' },
  tense: { zh: '紧张', ja: '緊張', en: 'tense' },
  mysterious: { zh: '神秘', ja: '神秘的', en: 'mysterious' },
  dramatic: { zh: '戏剧化', ja: 'ドラマチック', en: 'dramatic' },
  drive: { zh: '推进', ja: '推進', en: 'driving' },
  return: { zh: '回归', ja: '回帰', en: 'homecoming' },
  openEnd: { zh: '开放结尾', ja: '開いた終わり', en: 'open ending' },
};

/** 筛选分类 */
export const CATEGORIES = {
  major: { zh: '大调', ja: '長調', en: 'major' },
  minor: { zh: '小调', ja: '短調', en: 'minor' },
  modal: { zh: '调式', ja: '旋法', en: 'modal' },
  pop: { zh: '流行', ja: 'ポップ', en: 'pop' },
  rock: { zh: '摇滚', ja: 'ロック', en: 'rock' },
  jazz: { zh: '爵士', ja: 'ジャズ', en: 'jazz' },
  blues: { zh: '布鲁斯', ja: 'ブルース', en: 'blues' },
  classical: { zh: '古典', ja: 'クラシック', en: 'classical' },
  loop: { zh: '循环', ja: 'ループ', en: 'loop' },
  cadence: { zh: '终止', ja: '終止', en: 'cadence' },
  link: { zh: '连接', ja: 'つなぎ', en: 'link' },
  borrowed: { zh: '借用', ja: '借用', en: 'borrowed' },
  applied: { zh: '副属', ja: '副属', en: 'applied' },
  chromaticBass: { zh: '半音低音', ja: '半音ベース', en: 'chromatic bass' },
  fifths: { zh: '五度链', ja: '5 度の連鎖', en: 'circle of fifths' },
  triad: { zh: '三和弦', ja: '三和音', en: 'triads' },
  seventh: { zh: '七和弦', ja: '七の和音', en: 'sevenths' },
};

/** 完整终止 / 循环 / 片段 */
export const KINDS = {
  cadence: { zh: '收束', ja: '終止形', en: 'closing' },
  loop: { zh: '循环', ja: 'ループ', en: 'loop' },
  fragment: { zh: '片段', ja: '断片', en: 'fragment' },
};

export const SOURCES = {
  user: { zh: '用户指定', ja: 'ユーザー指定', en: 'user list' },
  img1: { zh: '图一', ja: '画像 1', en: 'image 1' },
  img2: { zh: '图二', ja: '画像 2', en: 'image 2' },
  img3: { zh: '图三', ja: '画像 3', en: 'image 3' },
  extra: { zh: '补充资料', ja: '補足', en: 'extra' },
};

/** 家族：同一骨架的版本 */
export const FAMILIES = {
  circle: { ...t('五度链', 'circle of fifths'), ja: '5 度の連鎖' },
  canon: { ...t('卡农型（Romanesca）', 'Canon (Romanesca)'), ja: 'カノン型（ロマネスカ）' },
  axis: { ...t('I–V–vi–IV 与旋转（Axis / singer/songwriter）', 'I–V–vi–IV and rotations (Axis / singer/songwriter)'), ja: 'I–V–vi–IV とローテーション（Axis / singer/songwriter）' },
  doowop: { ...t('doo-wop 型 I–vi–IV–V', 'doo-wop I–vi–IV–V'), ja: 'doo-wop 型 I–vi–IV–V' },
  hopscotch: { ...t('hopscotch 型 IV–V–vi–I', 'hopscotch IV–V–vi–I'), ja: 'hopscotch 型 IV–V–vi–I' },
  royal: { ...t('王道型 IV–V–iii–vi', 'royal road IV–V–iii–vi'), ja: '王道型 IV–V–iii–vi' },
  plagalMinor: { ...t('IV–iv 小下属借用', 'IV–iv borrowed minor subdominant'), ja: 'IV–iv の小下属の借用' },
  basic: { ...t('基本功能进行', 'basic functional progressions'), ja: '基本的な機能進行' },
  iiV: { ...t('ii–V 系', 'ii–V family'), ja: 'ii–V の仲間' },
  turnaround: { ...t('turnaround', 'turnarounds'), ja: 'ターンアラウンド' },
  minorLoop: { ...t('小调循环', 'minor loops'), ja: '短調のループ' },
  minorCadence: { ...t('小调收束', 'minor closings'), ja: '短調の終わり方' },
  lament: { ...t('lament / 安达卢西亚', 'lament / Andalusian'), ja: 'ラメント / アンダルシア' },
  mixolydian: { ...t('Mixolydian ♭VII', 'Mixolydian ♭VII'), ja: 'ミクソリディアの ♭VII' },
  aeolian: { ...t('Aeolian ♭VI ♭VII', 'Aeolian ♭VI ♭VII'), ja: 'エオリアの ♭VI ♭VII' },
  dorian: { ...t('Dorian IV', 'Dorian IV'), ja: 'ドリアの IV' },
  lydian: { ...t('Lydian II', 'Lydian II'), ja: 'リディアの II' },
  phrygian: { ...t('Phrygian ♭II', 'Phrygian ♭II'), ja: 'フリギアの ♭II' },
  chromatic: { ...t('半音与色彩', 'chromatic colour'), ja: '半音と色彩' },
  puff: { ...t('puff 型 I–iii–IV', 'puff I–iii–IV'), ja: 'パフ型 I–iii–IV' },
  blues: { ...t('布鲁斯', 'blues'), ja: 'ブルース' },
  single: { ...t('独立条目', 'standalone'), ja: '単独の項目' },
};

// 条目：roman 用空格分隔的罗马数字（prog_library.js 的写法）；bars 为布鲁斯这类每小节一个和弦的进行
const E = (o) => ({ mode: 'major', kind: 'loop', meter: [4], tempo: [72, 110], beats: 4, cats: [], tags: [], aliases: [], status: 'verified', ...o });

const RAW_ENTRIES = [
  // ======================= 用户指定的五条 =======================
  E({ id: 'u-4361', source: 'user', digits: '4361', roman: 'IV iii vi I', family: 'single', kind: 'cadence', cats: ['pop'], tags: ['sorrow', 'melancholy', 'return', 'bright'],
    suggested: '柔和内收 略带惆怅 最后回到明亮主和弦 适合抒情乐句或段落收束',
    theory: t('四个都是音阶内和弦 根音 F E A C；iii 与 vi 都是主功能的延伸 最后落到 I 但没有经过属和弦 是否算完整终止要看乐句位置与旋律', 'All diatonic, roots F E A C; iii and vi extend tonic and the line lands on I without a dominant — whether it is a full cadence depends on phrase position and melody'),
    refs: ['omt2e-cadences'], status: 'example', limits: t('没有 V–I 不是正格终止', 'no V–I, so not an authentic cadence') }),
  E({ id: 'u-14736251', source: 'user', digits: '14736251', roman: 'I IV vii° iii vi ii V I', family: 'circle', kind: 'cadence', cats: ['pop', 'classical', 'fifths'], tags: ['drive', 'return'], beats: 2,
    suggested: '连续五度链 推进连贯 具有展开感 最后的 ii-V-I 明确回归 适合较长乐句与连接段',
    theory: t('根音一路下行五度（F 到 B 是一次减五度） 走遍七个音阶内和弦再回到主和弦 7 是 vii° 不是 B 大三；结尾 ii–V–I 是正格回归', 'Roots fall by fifths (F→B is the one diminished fifth) through all seven diatonic chords back to I; the 7 is vii°, not B major; it ends with ii–V–I'),
    refs: ['wiki-circle-progression'], aliases: ['circle progression', '五度圈进行'] }),
  E({ id: 'u-62514736', source: 'user', digits: '62514736', roman: 'vi ii V I IV vii° iii vi', family: 'circle', kind: 'loop', cats: ['pop', 'fifths'], tags: ['melancholy', 'drive', 'openEnd'], beats: 2,
    suggested: '同一五度链从 vi 起始并返回 vi 相比前一条更容易形成小调倾向 适合循环和长线抒情 需提示主音感可能在 C 与 Am 之间变化',
    theory: t('和 14736251 是同一条五度链 只是从 vi 开始 回到 vi；起点与终点都是 Am 听起来可能以 Am 为主 也可能仍以 C 为主', 'The same chain as 14736251 started on vi and returning to vi; beginning and ending on Am, the tonic may sound like Am or still C'),
    refs: ['wiki-circle-progression'], variantOf: { id: 'u-14736251', how: t('同一五度链换起点', 'same chain, new starting point') } }),
  E({ id: 'u-4536251', source: 'user', digits: '4536251', roman: 'IV V iii vi ii V I', family: 'royal', kind: 'cadence', cats: ['pop', 'fifths'], tags: ['bright', 'drive', 'return'], beats: 2,
    suggested: '前半段明亮上扬 后半段顺势回归 常用于副歌扩展 先保持情绪流动再完成收束',
    theory: t('王道型 IV–V–iii–vi 后面接 ii–V–I 收束；文献把 IVM7–V7–iii7–vi–ii7–V7–I 看作大调里一整条下行五度链（V7 代替 vii°）', 'The royal road IV–V–iii–vi plus a ii–V–I closing; IVM7–V7–iii7–vi–ii7–V7–I is described as a full descending-fifths chain in major (V7 standing in for vii°)'),
    refs: ['wiki-royal-road'], variantOf: { id: 'i3-4536', how: t('4536 后接 ii–V–I', '4536 extended with ii–V–I') } }),
  E({ id: 'u-15634145', source: 'user', digits: '15634145', roman: 'I V vi iii IV I IV V', family: 'canon', kind: 'loop', cats: ['pop', 'classical'], tags: ['nostalgic', 'warm', 'drive', 'openEnd'], beats: 2,
    suggested: '卡农型和声骨架 兼有熟悉感 抒情感和持续推进 末尾 V 适合接下一轮 I 作为单次片段则保留期待',
    theory: t('就是帕赫贝尔卡农低音隐含的八个和弦 I–V–vi–iii–IV–I–IV–V（一种叫 Romanesca 的模进套路）；末尾停在 V 循环时接回 I', 'Exactly the eight chords implied by the bass of Pachelbel’s Canon, I–V–vi–iii–IV–I–IV–V (a sequential pattern called the Romanesca); it ends on V and loops back to I'),
    refs: ['wiki-pachelbel-canon'], aliases: ['卡农进行', 'Pachelbel', 'canon'] }),

  // ======================= 图一（原图写法与原图听感照录） =======================
  E({ id: 'i1-IV-iv-I', source: 'img1', roman: 'IV iv I', family: 'plagalMinor', kind: 'cadence', cats: ['pop', 'borrowed'], tags: ['sorrow', 'calm', 'return'],
    original: { text: 'IV-IVm-I', feel: '悲伤而平静', scene: '副歌结束' },
    theory: t('iv 是从同主音小调借来的小下属 F A C → F A♭ C → C E G：A–A♭–G 一条半音下行的内声部 功能仍是下属到主', 'iv is the minor subdominant borrowed from the parallel minor; F A C → F A♭ C → C E G gives the chromatic inner line A–A♭–G, still predominant to tonic'),
    refs: ['omt2e-mixture', 'omt-pb-substitutions'], aliases: ['minor plagal', '小下属'] }),
  E({ id: 'i1-IV-iv-iii', source: 'img1', roman: 'IV iv iii', family: 'plagalMinor', kind: 'fragment', cats: ['pop', 'borrowed'], tags: ['sorrow', 'melancholy', 'openEnd'],
    original: { text: 'IV-IVm-IIIm', feel: '悲伤而富有情感', scene: '副歌开始' },
    theory: t('同样用借来的 iv；A–A♭–G 的内声部下行接到 E G B 的 G 停在 iii 上 没有回到主和弦 是继续往下走的片段', 'Also uses borrowed iv; the inner line A–A♭–G lands on the G of E G B and stops on iii — an open fragment'),
    refs: ['omt2e-mixture'] }),
  E({ id: 'i1-ii-iii-iv-V', source: 'img1', roman: 'ii iii iv V', family: 'plagalMinor', kind: 'fragment', cats: ['pop', 'borrowed'], tags: ['sorrow', 'drive', 'suspense'],
    original: { text: 'IIm-IIIm-IVm-V', feel: '悲伤而情绪高涨', scene: '副歌之前' },
    theory: t('根音 D E F G 级进上行 第三个和弦借用 iv（A♭） 最后停在 V 上 等着下一句', 'Roots step up D E F G, the third chord borrows iv (A♭), and it stops on V, waiting for what comes next'),
    refs: ['omt2e-mixture', 'omt2e-cadences'], limits: t('停在 V 上 是半终止式的悬停 不是完成', 'stops on V — an open half-cadence feeling, not a close') }),
  E({ id: 'i1-bVII-V', source: 'img1', roman: '♭VII V', family: 'mixolydian', kind: 'fragment', cats: ['rock', 'borrowed', 'modal'], tags: ['open', 'suspense'],
    original: { text: '♭VII-V', feel: '漂浮感的高扬', scene: '副歌之前' },
    theory: t('♭VII 带 te（B♭） 之后的 V 换回 ti（B） 同一个音级的两种颜色接连出现 停在 V 上', '♭VII carries te (B♭), then V brings back ti (B) — two colours of one scale degree back to back, stopping on V'),
    refs: ['omt-pb-modal-schemas'] }),
  E({ id: 'i1-bVII-IV', source: 'img1', roman: '♭VII IV', family: 'mixolydian', kind: 'fragment', cats: ['rock', 'borrowed', 'modal'], tags: ['open', 'calm'],
    original: { text: '♭VII-IV', feel: '漂浮的着陆', scene: '任何地方' },
    theory: t('可看作局部的变格关系（♭VII 是 IV 的 IV） 或双重变格 ♭VII–IV–I 的前半；功能要看上下文 不能单独固定', 'Can be heard as a local plagal motion (♭VII is IV of IV) or the first half of the double plagal ♭VII–IV–I; its function depends on context'),
    refs: ['omt-pb-modal-schemas'] }),
  E({ id: 'i1-bVI-V', source: 'img1', roman: '♭VI V', family: 'aeolian', kind: 'fragment', cats: ['borrowed', 'minor'], tags: ['mysterious', 'suspense'], mode: 'any',
    original: { text: '♭VI-V', feel: '神秘', scene: '任何地方' },
    theory: t('在大调里 ♭VI 是借用和弦 根音 A♭ 半音下行到 G；在小调里 ♭VI–V 都是本调和弦（弗里吉亚式的半音低音） 两种语境的解释要分开', 'In major ♭VI is borrowed and its root falls a semitone to G; in minor both chords are native (a Phrygian-style semitone bass) — keep the two readings apart'),
    refs: ['omt2e-mixture', 'wiki-cadence'] }),
  E({ id: 'i1-iii-bIII-ii', source: 'img1', roman: 'iii ♭III ii', family: 'chromatic', kind: 'fragment', cats: ['pop', 'borrowed', 'chromaticBass'], tags: ['mysterious', 'drive'],
    original: { text: 'IIIm-♭III-IIm', feel: '感觉各异', scene: '副歌中途' },
    theory: t('根音 E–E♭–D 半音下降 中间的 ♭III（E♭ G B♭）把 iii 和 ii 滑着连起来', 'Roots slide E–E♭–D; the ♭III in the middle (E♭ G B♭) glides from iii to ii'),
    refs: ['omt2e-mixture'], status: 'example' }),
  E({ id: 'i1-bVI-bVII-I', source: 'img1', roman: '♭VI ♭VII I', family: 'aeolian', kind: 'cadence', cats: ['rock', 'borrowed', 'modal'], tags: ['open', 'dramatic', 'return'],
    original: { text: '♭VI-♭VII-I', feel: '豪迈的摇滚风', scene: '副歌结束' },
    theory: t('aeolian cadence 的大三主和弦版本：♭VI ♭VII 都是借来的大三和弦 根音 A♭ B♭ C 级进上行 抬升到主和弦', 'The aeolian cadence with a major (Picardy) tonic: borrowed ♭VI and ♭VII rise by step A♭ B♭ C into I'),
    refs: ['omt-pb-modal-schemas', 'wiki-backdoor'], aliases: ['aeolian cadence', 'Mario cadence'] }),

  // ======================= 图二（原图写法与原图感想照录；含七和弦的保留原版） =======================
  E({ id: 'i2-ii-V-iii-vi', source: 'img2', roman: 'ii V iii vi', family: 'royal', kind: 'loop', cats: ['pop'], tags: ['drive', 'melancholy'],
    original: { text: 'IIm-V-IIIm-VIm', feel: '更清晰有力' },
    theory: t('王道型的第一个和弦 IV 换成同属下属的 ii', 'The royal road with its first chord IV replaced by ii, also predominant'),
    refs: ['wiki-royal-road'], variantOf: { id: 'i3-4536', how: t('IV 换成 ii', 'IV replaced by ii') } }),
  E({ id: 'i2-IV-V-III-vi', source: 'img2', roman: 'IV V III vi', family: 'royal', kind: 'loop', cats: ['pop', 'applied'], tags: ['drive', 'dramatic'],
    original: { text: 'IV-V-III-VIm', feel: '更能表达情绪高涨' },
    theory: t('iii 换成大三的 III（E G♯ B） G♯ 指向 A 是 vi 的副属 V/vi', 'iii becomes major III (E G♯ B); the G♯ leads to A — V/vi'),
    refs: ['wiki-royal-road', 'omt2e-tonicization'], variantOf: { id: 'i3-4536', how: t('iii 改成副属 III', 'iii made into applied III') } }),
  E({ id: 'i2-ii-V-iii-VI', source: 'img2', roman: 'ii V iii VI', family: 'royal', kind: 'loop', cats: ['pop', 'jazz', 'applied'], tags: ['bright', 'drive'],
    original: { text: 'IIm-V-IIIm-VI', feel: '感觉更有希望' },
    suggested: '暂避直接落 I 再指向 ii 适合循环（补充资料里的爵士功能链也收了这一条）',
    theory: t('最后的 VI（A C♯ E） 如果接回 ii 就是 V/ii；作为单独片段时只保留这种可能 不算已经解决', 'The final VI (A C♯ E) is V/ii if it moves back to ii; as a standalone fragment that is only a possibility, not a resolution'),
    refs: ['omt2e-tonicization', 'wiki-turnaround'], aliases: ['Dm-G-Em-A'] }),
  E({ id: 'i2-IV-viio7-III-vi', source: 'img2', roman: 'IV viiø7 III vi', family: 'royal', kind: 'loop', cats: ['pop', 'applied', 'seventh'], tags: ['tense', 'dramatic'],
    original: { text: 'IV-VIIø-III-VIm', feel: '情绪更不稳定更令人震惊', note: t('原图 VIIø 没有另外写 7；ø 通常表示半减七和弦 这里规范化为 viiø7（Bm7b5）', 'the image writes VIIø without a 7; ø normally means half-diminished seventh, so it is normalised to viiø7 (Bm7b5)') },
    theory: t('Bm7♭5–E–Am 可以听成指向 vi（A 小调）的局部 iiø7–V–i；不能只凭这一段就说整段转到 A 小调', 'Bm7♭5–E–Am can be heard as a local iiø7–V–i pointing at vi (A minor); that alone does not make a full modulation'),
    refs: ['wiki-royal-road', 'omt2e-iivi', 'omt2e-tonicization'] }),
  E({ id: 'i2-IV-ivmM7-iii-vi', source: 'img2', roman: 'IV iv(maj7) iii vi', family: 'royal', kind: 'loop', cats: ['pop', 'borrowed', 'seventh'], tags: ['sorrow', 'melancholy'],
    original: { text: 'IV-IVmΔ7-IIIm-VIm', feel: '更加哀愁', note: t('IVmΔ7 是小三和弦加大七度：C 调为 F A♭ C E 不是 Fm7 的 F A♭ C E♭', 'IVmΔ7 is a minor triad plus a major seventh: F A♭ C E in C, not Fm7 (F A♭ C E♭)') },
    theory: t('借用的 iv 带上大七音 E：E 是大调的 mi 和 A♭（le）同时出现 色彩更暗也更紧', 'Borrowed iv with its major seventh E: mi and le (A♭) sound together — darker and tighter'),
    refs: ['omt2e-mixture', 'wiki-minor-major-seventh'] }),
  E({ id: 'i2-IV-iv7-iii-bIII', source: 'img2', roman: 'IV iv7 iii ♭III', family: 'royal', kind: 'fragment', cats: ['jazz', 'borrowed', 'chromaticBass', 'seventh'], tags: ['mysterious', 'openEnd'],
    original: { text: 'IV-IVm7-IIIm-♭III', feel: '更有 jazzy 的感觉' },
    theory: t('借用 iv7 之后 根音 E–E♭ 半音下行到 ♭III 停在借用和弦上 是没有收束的片段', 'After borrowed iv7, the root slides E–E♭ to ♭III and stops on a borrowed chord — an open fragment'),
    refs: ['omt2e-mixture'] }),
  E({ id: 'i2-IV-V-iiio7-VI7', source: 'img2', roman: 'IV V iiiø7 VI7', family: 'royal', kind: 'fragment', cats: ['jazz', 'applied', 'seventh'], tags: ['drive', 'tense'],
    original: { text: 'IV-V-IIIø-VI7', feel: '摇摆的绝招', note: t('原图 IIIø 没有另外写 7 规范化为 iiiø7（Em7b5）；VI7 是 A7 不是 Am7', 'IIIø without a 7 is normalised to iiiø7 (Em7b5); VI7 is A7, not Am7') },
    theory: t('Em7♭5–A7 如果接到 Dm 就是指向 ii 的局部 iiø7–V7–i；没有接下去时只保留这种可能', 'Em7♭5–A7 followed by Dm would be a local iiø7–V7–i pointing at ii; without it, that stays a possibility'),
    refs: ['omt2e-iivi', 'omt2e-tonicization'] }),
  E({ id: 'i2-IV-V-#vo7-VI7', source: 'img2', roman: 'IV V ♯v°7 VI7', family: 'royal', kind: 'fragment', cats: ['jazz', 'applied', 'chromaticBass', 'seventh'], tags: ['dramatic', 'drive'],
    original: { text: 'IV-V-♯V°7-VI7', feel: '上行的低音很戏剧化' },
    theory: t('低音 F G G♯ A 半音上行；G♯dim7（G♯ B D F）是 A 的导七和弦 它和 A7–Dm 的关系要看后面怎么走 不能凭一个和弦就判成转调', 'Bass F G G♯ A rises chromatically; G♯dim7 (G♯ B D F) leads to A — how it relates to A7–Dm depends on what follows, not on one chord'),
    refs: ['omt2e-tonicization', 'wiki-diminished-seventh'] }),

  // ======================= 图三（图片只给进行；听感是补充说明） =======================
  E({ id: 'i3-141', source: 'img3', digits: '141', roman: 'I IV I', family: 'basic', kind: 'cadence', cats: ['pop', 'classical'], tags: ['calm', 'warm', 'return'],
    suggested: '平稳 舒展 温和回归', theory: t('主–下属–主 IV–I 是变格运动；只写 I–IV–I 也可能只是主和弦的延长 不一定是完整的变格终止', 'Tonic–subdominant–tonic; IV–I is plagal motion, but I–IV–I may simply prolong tonic rather than form a full plagal cadence'),
    refs: ['omt2e-plagal'] }),
  E({ id: 'i3-151', source: 'img3', digits: '151', roman: 'I V I', family: 'basic', kind: 'cadence', cats: ['pop', 'classical'], tags: ['bright', 'return'],
    suggested: '简洁 明确 有问答与回归感', theory: t('主–属–主 V–I 是正格运动；是否构成完整终止还要看乐句位置与旋律', 'Tonic–dominant–tonic; V–I is authentic motion — whether it is a full cadence depends on phrase position and melody'),
    refs: ['omt2e-cadences'] }),
  E({ id: 'i3-1451', source: 'img3', digits: '1451', roman: 'I IV V I', family: 'basic', kind: 'cadence', cats: ['pop', 'classical'], tags: ['bright', 'drive', 'return'],
    suggested: '起承转合清楚 推进后收束', theory: t('T–PD–D–T 的基本乐句模式', 'The basic T–PD–D–T phrase model'), refs: ['omt2e-phrase-model'] }),
  E({ id: 'i3-251', source: 'img3', digits: '251', roman: 'ii V I', family: 'iiV', kind: 'cadence', cats: ['pop', 'jazz', 'classical', 'fifths'], tags: ['drive', 'return'],
    suggested: '流畅 有方向感 适合连接和终止', theory: t('根音 D G C 两次下行五度 PD–D–T；爵士里的七和弦版是 Dm7–G7–Cmaj7', 'Roots fall two fifths, D G C: PD–D–T; the jazz seventh version is Dm7–G7–Cmaj7'),
    refs: ['omt2e-iivi'] }),
  E({ id: 'i3-1625', source: 'img3', digits: '1625', roman: 'I vi ii V', family: 'doowop', kind: 'loop', cats: ['pop', 'jazz', 'fifths'], tags: ['warm', 'nostalgic', 'openEnd'], beats: 2,
    suggested: '柔和转向 暂不落地 适合循环与 turnaround', theory: t('doo-wop 型 I–vi–IV–V 里用 ii 代替 IV；也是爵士最常见的 turnaround I–vi–ii–V 停在 V 上接回 I', 'The doo-wop schema with ii for IV; also the most common jazz turnaround I–vi–ii–V, ending on V to loop back to I'),
    refs: ['omt-pb-4chord', 'wiki-turnaround', 'wiki-circle-progression'], aliases: ['turnaround', 'I-vi-ii-V'] }),
  E({ id: 'i3-1541', source: 'img3', digits: '1541', roman: 'I V IV I', family: 'basic', kind: 'cadence', cats: ['rock', 'pop'], tags: ['open', 'return'],
    suggested: '开阔 回落 带摇滚或民谣倾向', theory: t('V 之后不回 I 而落到 IV 再由 IV–I 回家；和布鲁斯第三句 V–IV–I 的走向相同', 'V falls back to IV, then IV–I goes home — the same motion as the blues third phrase V–IV–I'),
    refs: ['omt-pb-blues'], status: 'example' }),
  E({ id: 'i3-4536', source: 'img3', digits: '4536', roman: 'IV V iii vi', family: 'royal', kind: 'loop', cats: ['pop'], tags: ['bright', 'sorrow', 'drive'],
    suggested: '上扬后内收 明亮与惆怅交织 常见王道型骨架', theory: t('王道进行（王道進行）的三和弦形 IV–V–iii–vi；七和弦原版是 IVM7–V7–iii7–vi', 'The triad form of the royal road progression (ōdō shinkō) IV–V–iii–vi; the seventh original is IVM7–V7–iii7–vi'),
    refs: ['wiki-royal-road'], aliases: ['王道进行', '王道進行', 'royal road'] }),
  E({ id: 'i3-6451', source: 'img3', digits: '6451', roman: 'vi IV V I', family: 'single', kind: 'cadence', cats: ['pop'], tags: ['melancholy', 'drive', 'return', 'bright'],
    suggested: '从暗到明 逐渐打开并回到主和弦', theory: t('从 vi 开始 经 IV–V 进入 I 结尾是 V–I 的正格运动', 'Starts on vi and reaches I through IV–V, ending with authentic V–I motion'), refs: ['omt2e-cadences'], status: 'example' }),
  E({ id: 'i3-1564', source: 'img3', digits: '1564', roman: 'I V vi IV', family: 'axis', kind: 'loop', cats: ['pop'], tags: ['open', 'bright', 'drive'],
    suggested: '宽广 流行感强 易形成持续循环', theory: t('I–V–vi–IV（Axis 进行；OMT 叫 singer/songwriter 型的一种旋转）；和 6415 4156 5641 是同一组和弦的旋转', 'I–V–vi–IV (the Axis progression; one rotation of OMT’s singer/songwriter schema); 6415, 4156 and 5641 rotate the same chords'),
    refs: ['wiki-axis-progression', 'omt-pb-4chord'], aliases: ['Axis', 'four chords', 'singer/songwriter'] }),
  E({ id: 'i3-6415', source: 'img3', digits: '6415', roman: 'vi IV I V', family: 'axis', kind: 'loop', cats: ['pop'], tags: ['melancholy', 'sorrow', 'openEnd'],
    suggested: '抒情 略带忧郁 末尾保留推动下一轮的张力', theory: t('singer/songwriter 型 vi–IV–I–V；没有正格终止 主音可能听成 C 也可能听成 Am（调性模糊）', 'The singer/songwriter schema vi–IV–I–V; with no authentic cadence the tonic can sound like C or A minor (tonal ambiguity)'),
    refs: ['omt-pb-4chord', 'wiki-axis-progression'], variantOf: { id: 'i3-1564', how: t('旋转', 'rotation') } }),
  E({ id: 'i3-46', source: 'img3', digits: '46', roman: 'IV vi', family: 'single', kind: 'fragment', cats: ['pop', 'link'], tags: ['calm', 'melancholy'],
    suggested: '柔和转暗 适合局部衔接 本身不足以确定完整乐句', theory: t('两个和弦共享 A 和 C 两个音 只是局部衔接', 'The chords share A and C — just a local link'), refs: ['omt2e-triads'], status: 'example' }),
  E({ id: 'i3-61', source: 'img3', digits: '61', roman: 'vi I', family: 'single', kind: 'fragment', cats: ['pop', 'link'], tags: ['bright', 'calm'],
    suggested: '从相对暗色转向明亮 可用于轻柔释放', theory: t('vi 与 I 共享 C 和 E 都属主功能 这是同功能内部的换色', 'vi and I share C and E and both are tonic-function — a colour change within one function'), refs: ['omt2e-triads'], status: 'example' }),
  E({ id: 'i3-54', source: 'img3', digits: '54', roman: 'V IV', family: 'single', kind: 'fragment', cats: ['rock', 'link'], tags: ['calm', 'open'],
    suggested: '回落或松弛 在摇滚中常见 不等同于 V-I 的解决', theory: t('属之后回到下属 不是解决；布鲁斯第三句就是 V–IV–I', 'Dominant falling back to subdominant is not a resolution; the blues third phrase is V–IV–I'), refs: ['omt-pb-blues'] }),
  E({ id: 'x-5641', source: 'extra', digits: '5641', roman: 'V vi IV I', family: 'axis', kind: 'loop', cats: ['pop'], tags: ['drive', 'return'],
    suggested: '（补充）从属开始 中途转暗再回主和弦 循环时和 1564 交替出现', theory: t('Axis 进行的另一种旋转 V–vi–IV–I', 'Another rotation of the Axis progression, V–vi–IV–I'), refs: ['wiki-axis-progression'], variantOf: { id: 'i3-1564', how: t('旋转', 'rotation') } }),

  // ======================= 补充：大调 流行 抒情与循环 =======================
  E({ id: 'x-1645', source: 'extra', roman: 'I vi IV V', family: 'doowop', kind: 'loop', cats: ['pop'], tags: ['nostalgic', 'warm', 'openEnd'],
    suggested: '复古 温柔 怀旧 常见 doo-wop 型循环', theory: t('doo-wop 型（\'50s 进行）I–vi–IV–V；vi 延长主功能 低音 C A F 三度下行', 'The doo-wop (\'50s) progression I–vi–IV–V; vi prolongs tonic and the bass falls in thirds C A F'),
    refs: ['omt-pb-4chord', 'wiki-50s-progression'], aliases: ['doo-wop', '50s progression', '\'50s'] }),
  E({ id: 'x-1345', source: 'extra', roman: 'I iii IV V', family: 'puff', kind: 'loop', cats: ['pop'], tags: ['warm', 'drive', 'openEnd'],
    suggested: '细腻展开 渐渐上扬 末尾等待回归', theory: t('开头 I–iii–IV 是 puff 型 之后接 V', 'Opens with the puff schema I–iii–IV, then V'), refs: ['omt-pb-puff'] }),
  E({ id: 'x-1465', source: 'extra', roman: 'I IV vi V', family: 'single', kind: 'loop', cats: ['pop'], tags: ['bright', 'melancholy', 'openEnd'],
    suggested: '明暗交替 适合流行主歌与副歌', theory: t('四个音阶内和弦 明（I IV）暗（vi）交替 停在 V', 'Four diatonic chords alternating bright (I IV) and dark (vi), ending on V'), refs: ['omt2e-triads'], status: 'example' }),
  E({ id: 'x-1524', source: 'extra', roman: 'I V ii IV', family: 'axis', kind: 'loop', cats: ['pop'], tags: ['open', 'calm'],
    suggested: '开阔后收敛 适合流动的循环', theory: t('I–V–vi–IV 里用 ii 代替 vi 的常见变体', 'A common variant of I–V–vi–IV with ii in place of vi'), refs: ['wiki-axis-progression'], variantOf: { id: 'i3-1564', how: t('vi 换成 ii', 'vi replaced by ii') } }),
  E({ id: 'x-1624', source: 'extra', roman: 'I vi ii IV', family: 'doowop', kind: 'loop', cats: ['pop'], tags: ['warm', 'calm'],
    suggested: '柔和舒展 属张力较弱', theory: t('没有 V 只用主与下属功能 所以属张力弱', 'No V at all — only tonic and predominant, so little dominant pull'), refs: ['omt2e-predominants'], status: 'example' }),
  E({ id: 'x-2415', source: 'extra', roman: 'ii IV I V', family: 'axis', kind: 'loop', cats: ['pop'], tags: ['calm', 'openEnd'],
    suggested: '先铺垫再展开 末尾保留期待', theory: t('6415 里用 ii 代替 vi 的写法 末尾停在 V', 'Like 6415 with ii instead of vi, ending on V'), refs: ['omt-pb-4chord'], status: 'example' }),
  E({ id: 'x-4156', source: 'extra', roman: 'IV I V vi', family: 'axis', kind: 'loop', cats: ['pop'], tags: ['open', 'melancholy', 'openEnd'],
    suggested: '开放抒情 最后转向小和弦', theory: t('singer/songwriter 型从 IV 开始的旋转 结尾 V–vi 是阻碍终止式的走向', 'The singer/songwriter rotation starting on IV; the V–vi at the end is deceptive motion'),
    refs: ['omt-pb-4chord', 'wiki-axis-progression'], variantOf: { id: 'i3-1564', how: t('旋转', 'rotation') } }),
  E({ id: 'x-4125', source: 'extra', roman: 'IV I ii V', family: 'single', kind: 'loop', cats: ['pop'], tags: ['warm', 'drive'],
    suggested: '温和回归后重新蓄势', theory: t('IV–I 回到主和弦后 ii–V 再推向下一轮', 'After IV–I comes home, ii–V pushes into the next round'), refs: ['omt2e-iivi'], status: 'example' }),
  E({ id: 'x-1364', source: 'extra', roman: 'I iii vi IV', family: 'single', kind: 'loop', cats: ['pop'], tags: ['sorrow', 'calm'],
    suggested: '内收 抒情 共享音连接较多', theory: t('相邻和弦各共享两个音（C E G → E G B → A C E → F A C）', 'Each neighbouring pair shares two notes (C E G → E G B → A C E → F A C)'), refs: ['omt2e-triads'], status: 'example' }),
  E({ id: 'x-1415', source: 'extra', roman: 'I IV I V', family: 'basic', kind: 'loop', cats: ['pop', 'rock'], tags: ['bright', 'calm'],
    suggested: '简洁明快 适合民谣式循环', theory: t('主 下属 主 属 交替 停在 V 接回 I', 'Alternates tonic, subdominant, tonic, dominant; V loops back to I'), refs: ['omt2e-phrase-model'], status: 'example' }),
  E({ id: 'x-451', source: 'extra', roman: 'IV V I', family: 'basic', kind: 'cadence', cats: ['pop', 'classical'], tags: ['bright', 'return'],
    suggested: '明确抬升后收束', theory: t('PD–D–T 根音 F G C', 'PD–D–T, roots F G C'), refs: ['omt2e-phrase-model'] }),
  E({ id: 'x-456', source: 'extra', roman: 'IV V vi', family: 'basic', kind: 'fragment', cats: ['pop'], tags: ['suspense', 'sorrow'],
    suggested: '有推进但避开预期主和弦 带悬念或惆怅', theory: t('V 之后不去 I 而去 vi 是阻碍终止式的走向', 'V moves to vi instead of I — deceptive motion'), refs: ['omt2e-cadences'] }),
  E({ id: 'x-1245', source: 'extra', roman: 'I ii IV V', family: 'basic', kind: 'loop', cats: ['pop'], tags: ['drive', 'openEnd'],
    suggested: '逐步打开 适合段落蓄势', theory: t('根音 C D F G 上行 两个下属和弦之后停在 V', 'Roots rise C D F G; two predominants, then V'), refs: ['omt2e-predominants'], status: 'example' }),
  E({ id: 'x-164251', source: 'extra', roman: 'I vi IV ii V I', family: 'doowop', kind: 'cadence', cats: ['pop'], tags: ['warm', 'return'], beats: 2,
    suggested: '完整且连贯 适合较长抒情乐句', theory: t('doo-wop 骨架里 IV 之后再加 ii 用 ii–V–I 收束', 'The doo-wop frame with ii added after IV, closing with ii–V–I'), refs: ['omt-pb-4chord', 'omt2e-iivi'], status: 'example' }),
  E({ id: 'x-canon-bass', source: 'extra', roman: 'I V/3 vi iii/3 IV I/3 ii V', family: 'canon', kind: 'loop', cats: ['pop', 'classical'], tags: ['nostalgic', 'calm', 'drive'], beats: 2,
    original: { text: 'I-V/3-vi-iii/5-IV-I/3-ii-V', note: t('原文写 iii/5 但 C 调示例 Em/G 与低音线 C-B-A-G-F-E-D-G 都表明低音是三音 G 所以规范化为 iii/3；若按 iii/5 是 Em/B 低音线就不再级进', 'the source writes iii/5, but its C example Em/G and the bass line C-B-A-G-F-E-D-G both put the third G in the bass, so it is normalised to iii/3; iii/5 would be Em/B and break the stepwise bass') },
    suggested: '低音 C-B-A-G-F-E-D-G 带下行叙述感',
    theory: t('卡农型骨架加上转位 低音一路级进下行；倒数第二个和弦用 ii 代替了卡农原本的 IV（同属下属功能） /3 /5 指和弦的三音 五音在低音 G/B 的根音仍是 G', 'The canon frame with inversions so the bass walks down by step; the penultimate chord uses ii instead of the canon’s IV (same function); /3 and /5 mean the chord’s third or fifth in the bass — G/B still has root G'),
    refs: ['wiki-pachelbel-canon', 'omt2e-figured-bass'], status: 'ambiguous', variantOf: { id: 'u-15634145', how: t('加转位 让低音级进', 'inversions for a stepwise bass') } }),

  // ======================= 补充：小调（C 为主音 平行大调参照写法） =======================
  E({ id: 'm-i-iv-V-i', source: 'extra', mode: 'minor', roman: 'i iv V i', family: 'minorCadence', kind: 'cadence', cats: ['minor', 'classical'], tags: ['tense', 'return'],
    suggested: '紧张后回归 具有传统小调方向感', theory: t('V 用升高的导音 B♮ 产生向 C 的牵引', 'V uses the raised leading tone B♮ to pull to C'), refs: ['omt2e-minor', 'omt2e-cadences'] }),
  E({ id: 'm-i-iv-v-i', source: 'extra', mode: 'minor', roman: 'i iv v i', family: 'minorCadence', kind: 'cadence', cats: ['minor', 'modal'], tags: ['calm', 'melancholy'],
    suggested: '自然小调色彩 更柔和 较少导音牵引', theory: t('小属 v（G B♭ D）没有导音 牵引比 V 弱', 'Minor v (G B♭ D) has no leading tone, so the pull is weaker than V'), refs: ['omt2e-minor', 'omt-pb-modal-schemas'] }),
  E({ id: 'm-i-bVI-bIII-bVII', source: 'extra', mode: 'minor', roman: 'i ♭VI ♭III ♭VII', family: 'axis', kind: 'loop', cats: ['minor', 'pop'], tags: ['open', 'melancholy'],
    suggested: '宽广 抒情 适合循环', theory: t('singer/songwriter 型的小调读法 i–VI–III–VII；和 C 大调 vi–IV–I–V（Am F C G）移调后模式相似 但这里主音是 C 标注参照不同', 'The minor reading of the singer/songwriter schema, i–VI–III–VII; it resembles C-major vi–IV–I–V (Am F C G) after transposition, but here the tonic is C and the labels follow a different reference'),
    refs: ['omt-pb-4chord'], variantOf: { id: 'i3-6415', how: t('同一模式的小调读法（主音不同）', 'minor reading of the same pattern (different tonic)') } }),
  E({ id: 'm-aeolian-shuttle', source: 'extra', mode: 'minor', roman: 'i ♭VII ♭VI ♭VII', family: 'aeolian', kind: 'loop', cats: ['minor', 'modal', 'rock'], tags: ['melancholy', 'drive'],
    suggested: '下行后回升 暗色但持续流动', theory: t('aeolian shuttle：在 i 与 ♭VI 之间往返 ♭VII 作经过', 'The aeolian shuttle: moving between i and ♭VI with a passing ♭VII'), refs: ['omt-pb-modal-schemas'], aliases: ['aeolian shuttle'] }),
  E({ id: 'm-i-bVI-iv-V', source: 'extra', mode: 'minor', roman: 'i ♭VI iv V', family: 'minorLoop', kind: 'loop', cats: ['minor'], tags: ['dramatic', 'tense'],
    suggested: '深沉 逐渐积累终止张力', theory: t('♭VI 与 iv 都在下属一侧 最后的 V 带导音', '♭VI and iv are both on the predominant side; V brings the leading tone'), refs: ['omt2e-minor', 'omt2e-predominants'], status: 'example' }),
  E({ id: 'm-andalusian', source: 'extra', mode: 'minor', roman: 'i ♭VII ♭VI V', family: 'lament', kind: 'loop', cats: ['minor', 'classical', 'rock'], tags: ['dramatic', 'melancholy'],
    suggested: '安达卢西亚型根音下降 带戏剧感', theory: t('安达卢西亚进行 i–♭VII–♭VI–V（也是 lament 型的常见和声）；名字里有终止 但通常当作反复的固定音型使用', 'The Andalusian progression i–♭VII–♭VI–V (also a common lament harmonisation); despite the name it is usually a repeating ostinato rather than a true cadence'),
    refs: ['wiki-andalusian-cadence', 'omt-pb-classical-schemas'], aliases: ['Andalusian', '安达卢西亚', 'lament'] }),
  E({ id: 'm-long-narrative', source: 'extra', mode: 'minor', roman: 'i v ♭VI ♭III iv i iv V', family: 'canon', kind: 'loop', cats: ['minor'], tags: ['melancholy', 'drive'], beats: 2,
    suggested: '较长的小调叙述 对比和回归清楚', theory: t('根音走向和卡农型相同（下四度 上二度交替）放在小调里；最后用带导音的 V', 'The same root pattern as the canon (down a fourth, up a second) in minor, ending on V with the leading tone'), refs: ['wiki-pachelbel-canon', 'omt2e-minor'], status: 'example' }),
  E({ id: 'm-circle', source: 'extra', mode: 'minor', roman: 'i iv ♭VII ♭III ♭VI ii° V i', family: 'circle', kind: 'cadence', cats: ['minor', 'fifths', 'classical'], tags: ['drive', 'return'], beats: 2,
    suggested: '小调五度链 连贯而有展开感', theory: t('小调五度链 i–iv–VII–III–VI–ii°–V–i（这里按平行大调参照写成 ♭VII ♭III ♭VI）', 'The minor circle progression i–iv–VII–III–VI–ii°–V–i (written ♭VII ♭III ♭VI under the parallel-major reference)'), refs: ['wiki-circle-progression'] }),
  E({ id: 'm-aeolian-cadence', source: 'extra', mode: 'minor', roman: '♭VI ♭VII i', family: 'aeolian', kind: 'cadence', cats: ['minor', 'modal'], tags: ['drive', 'return', 'dramatic'],
    suggested: '上行积累后落到小调主和弦', theory: t('aeolian cadence ♭VI–♭VII–i：有目标的收束 不常拿来循环；常用皮卡迪三度变成全部大三和弦', 'The aeolian cadence ♭VI–♭VII–i: goal-directed, not usually looped; often ends with a Picardy third'), refs: ['omt-pb-modal-schemas'] }),
  E({ id: 'm-iv-V-i', source: 'extra', mode: 'minor', roman: 'iv V i', family: 'minorCadence', kind: 'cadence', cats: ['minor', 'classical'], tags: ['tense', 'return'],
    suggested: '精炼的小调收束', theory: t('PD–D–T 的小调版 V 带导音', 'The minor PD–D–T, V with the leading tone'), refs: ['omt2e-minor'] }),
  E({ id: 'm-iio-V-i', source: 'extra', mode: 'minor', roman: 'ii° V i', family: 'iiV', kind: 'cadence', cats: ['minor', 'classical', 'jazz'], tags: ['tense', 'return'],
    suggested: '前属紧张感较强 适合小调终止', theory: t('小调的 ii° V i；七和弦版是 Dm7♭5–G7–Cm 主和弦加七音可选 Cm7 或 Cm(maj7)', 'Minor ii° V i; the seventh version is Dm7♭5–G7–Cm, with Cm7 or Cm(maj7) as tonic options'), refs: ['omt2e-iivi', 'omt2e-minor'] }),
  E({ id: 'm-i-V-bVI-iv', source: 'extra', mode: 'minor', roman: 'i V ♭VI iv', family: 'minorLoop', kind: 'loop', cats: ['minor'], tags: ['dramatic', 'sorrow'],
    suggested: '戏剧性转折 随后内收', theory: t('V 之后不回 i 而去 ♭VI 是小调里的阻碍式走向', 'V goes to ♭VI instead of i — deceptive motion in minor'), refs: ['omt2e-cadences', 'omt2e-minor'], status: 'example' }),

  // ======================= 补充：摇滚 调式与民谣 =======================
  E({ id: 'r-double-plagal', source: 'extra', roman: 'I ♭VII IV I', family: 'mixolydian', kind: 'cadence', cats: ['rock', 'modal', 'borrowed'], tags: ['open', 'return'],
    suggested: '开阔 粗犷 常见双重变格型回归', theory: t('双重变格 ♭VII–IV–I（Mixolydian 套路）前面加上 I', 'The double plagal ♭VII–IV–I (a Mixolydian schema) preceded by I'), refs: ['omt-pb-modal-schemas'], aliases: ['double plagal'] }),
  E({ id: 'r-I-bVII-IV', source: 'extra', roman: 'I ♭VII IV', family: 'mixolydian', kind: 'loop', cats: ['rock', 'modal', 'borrowed'], tags: ['open', 'calm'],
    suggested: '松弛 有摇滚感 适合循环', theory: t('Mixolydian 的 ♭VII 加上 IV 循环时 IV 接回 I 就是双重变格', 'Mixolydian ♭VII with IV; looping IV back to I gives the double plagal'), refs: ['omt-pb-modal-schemas'] }),
  E({ id: 'r-I-IV-bVII-IV', source: 'extra', roman: 'I IV ♭VII IV', family: 'mixolydian', kind: 'loop', cats: ['rock', 'modal', 'borrowed'], tags: ['open'],
    suggested: '横向铺展 传统属功能较弱', theory: t('没有 V ♭VII 代替属一侧 和弦在 I IV ♭VII 之间横向移动', 'No V — ♭VII takes the dominant side and the harmony moves sideways among I IV ♭VII'), refs: ['omt-pb-modal-schemas'], status: 'example' }),
  E({ id: 'r-I-bIII-IV-I', source: 'extra', roman: 'I ♭III IV I', family: 'chromatic', kind: 'cadence', cats: ['rock', 'blues', 'borrowed'], tags: ['dramatic', 'return'],
    suggested: '明暗碰撞 带蓝调或摇滚色彩', theory: t('♭III 带 me（E♭）和大三主和弦的 mi 相撞 布鲁斯里大小三度常混用', '♭III brings me (E♭) against the major tonic’s mi — mixing major and minor thirds is common in the blues'), refs: ['omt-pb-blues', 'omt2e-mixture'], status: 'example' }),
  E({ id: 'r-I-bVI-bVII-I', source: 'extra', roman: 'I ♭VI ♭VII I', family: 'aeolian', kind: 'cadence', cats: ['rock', 'modal', 'borrowed'], tags: ['dramatic', 'open', 'return'],
    suggested: '戏剧性 扩张感 强势回归', theory: t('aeolian cadence 的大三主和弦版本前加 I', 'The aeolian cadence with a major tonic, preceded by I'), refs: ['omt-pb-modal-schemas'], variantOf: { id: 'i1-bVI-bVII-I', how: t('前面加上 I', 'with I in front') } }),
  E({ id: 'r-dorian-shuttle', source: 'extra', mode: 'minor', roman: 'i IV', family: 'dorian', kind: 'loop', cats: ['modal', 'minor'], tags: ['open', 'calm'],
    suggested: 'Dorian 色彩 小调中出现明亮的大四级', theory: t('dorian shuttle：小主和弦与大 IV 往返 大 IV 里的 la（A♮）是 Dorian 的特征音 整体是主和弦的延长', 'The dorian shuttle: minor i and major IV; IV’s la (A♮) is the Dorian colour note, prolonging the tonic'), refs: ['omt-pb-modal-schemas'], aliases: ['dorian shuttle'] }),
  E({ id: 'r-i-bVII-IV-i', source: 'extra', mode: 'minor', roman: 'i ♭VII IV i', family: 'dorian', kind: 'cadence', cats: ['modal', 'minor', 'rock'], tags: ['open', 'melancholy'],
    suggested: 'Dorian 倾向 暗色中带开放感', theory: t('小主和弦加上大 IV（la）指向 Dorian；♭VII 是自然小调与 Dorian 共有的和弦', 'Minor tonic with major IV (la) points to Dorian; ♭VII is shared by natural minor and Dorian'), refs: ['omt-pb-modal-schemas'], status: 'example' }),
  E({ id: 'r-phrygian', source: 'extra', mode: 'minor', roman: 'i ♭II i', family: 'phrygian', kind: 'loop', cats: ['modal', 'minor'], tags: ['tense', 'mysterious'],
    suggested: 'Phrygian 色彩 半音摩擦与压迫感', theory: t('弗里吉亚调式是自然小调降低第二级（ra） ♭II（D♭ F A♭）带着这个音 和主音形成半音', 'Phrygian is natural minor with a lowered second degree (ra); ♭II (D♭ F A♭) carries it, a semitone above the tonic'), refs: ['omt2e-modes'], status: 'example' }),
  E({ id: 'r-lydian-cadence', source: 'extra', roman: 'I II IV I', family: 'lydian', kind: 'cadence', cats: ['modal', 'pop'], tags: ['bright', 'open'],
    suggested: 'Lydian 色彩与调式交替混合 不能整体简单称为纯 Lydian', theory: t('II–IV–I 是 lydian cadence：II 的 fi（F♯）马上被 IV 的 fa（F）抵消 所以只是 Lydian 色彩 不是整段 Lydian', 'II–IV–I is the lydian cadence: II’s fi (F♯) is immediately neutralised by IV’s fa (F) — a Lydian colour, not Lydian throughout'), refs: ['omt-pb-modal-schemas'], aliases: ['lydian cadence'] }),
  E({ id: 'r-lydian-shuttle', source: 'extra', roman: 'I II I', family: 'lydian', kind: 'loop', cats: ['modal'], tags: ['bright', 'mysterious'],
    suggested: '在保持 C 主音的条件下可呈现 Lydian 色彩', theory: t('lydian shuttle I–II：如果 II 后面接 V 就应看作副属 V/V；在流行歌里 II 也可能其实是另一个调的 IV–V 要看后文', 'The lydian shuttle I–II: if II goes to V it is better read as V/V, and in pop the pair can turn out to be IV–V of another key — check what follows'), refs: ['omt-pb-modal-schemas'], status: 'ambiguous', aliases: ['lydian shuttle'] }),
  E({ id: 'r-mixolydian-v', source: 'extra', roman: 'I v IV I', family: 'mixolydian', kind: 'cadence', cats: ['modal', 'rock'], tags: ['calm', 'open'],
    suggested: 'Mixolydian 色彩 较松弛 不依赖大属和弦', theory: t('小属 v（G B♭ D）带 te 是 Mixolydian 的重要和弦', 'Minor v (G B♭ D) carries te, an important Mixolydian chord'), refs: ['omt-pb-modal-schemas'], status: 'example' }),

  // ======================= 补充：借用 半音与局部色彩 =======================
  E({ id: 'b-I-IV-iv-I', source: 'extra', roman: 'I IV iv I', family: 'plagalMinor', kind: 'cadence', cats: ['pop', 'borrowed'], tags: ['warm', 'sorrow', 'return'],
    suggested: '温暖转惆怅 然后释然', theory: t('IV 换成借来的 iv 再回 I：A–A♭–G', 'IV turns into borrowed iv, then home: A–A♭–G'), refs: ['omt2e-mixture'], variantOf: { id: 'i1-IV-iv-I', how: t('前面加上 I', 'with I in front') } }),
  E({ id: 'b-I-iv-I', source: 'extra', roman: 'I iv I', family: 'plagalMinor', kind: 'cadence', cats: ['pop', 'borrowed'], tags: ['sorrow', 'return'],
    suggested: '简短的小下属回归', theory: t('借用 iv 的变格运动', 'Plagal motion with borrowed iv'), refs: ['omt2e-mixture'] }),
  E({ id: 'b-IV-iv-I3', source: 'extra', roman: 'IV iv I/3', family: 'plagalMinor', kind: 'cadence', cats: ['pop', 'borrowed'], tags: ['sorrow', 'calm'],
    suggested: '半音内声部变化及较柔和的低音落点', theory: t('最后用 C/E：低音落在三音 E 上 收得比原位柔和', 'Ends on C/E: the bass lands on the third E, softer than root position'), refs: ['omt2e-mixture', 'omt2e-figured-bass'], variantOf: { id: 'i1-IV-iv-I', how: t('最后一个和弦转位', 'last chord inverted') } }),
  E({ id: 'b-I-bVI-IV-V', source: 'extra', roman: 'I ♭VI IV V', family: 'chromatic', kind: 'loop', cats: ['pop', 'borrowed'], tags: ['dramatic', 'drive'],
    suggested: '突然转暗 再积累张力', theory: t('vi 换成借来的 ♭VI（根音变成 le） 功能仍在主与下属之间', 'vi replaced by borrowed ♭VI (the root becomes le)'), refs: ['omt-pb-substitutions', 'omt2e-mixture'], variantOf: { id: 'x-1645', how: t('vi 换成 ♭VI', 'vi replaced by ♭VI') } }),
  E({ id: 'b-I-bIII-IV-V', source: 'extra', roman: 'I ♭III IV V', family: 'chromatic', kind: 'loop', cats: ['rock', 'borrowed'], tags: ['drive', 'dramatic'],
    suggested: '借用色彩 带摇滚式抬升', theory: t('iii 换成借来的 ♭III 根音 C E♭ F G 上行', 'iii replaced by borrowed ♭III; roots rise C E♭ F G'), refs: ['omt2e-mixture'], status: 'example', variantOf: { id: 'x-1345', how: t('iii 换成 ♭III', 'iii replaced by ♭III') } }),
  E({ id: 'b-I-bII-I', source: 'extra', roman: 'I ♭II I', family: 'phrygian', kind: 'cadence', cats: ['borrowed', 'chromaticBass'], tags: ['mysterious', 'dramatic'],
    suggested: '半音邻接 有陌生感或戏剧性', theory: t('♭II 的根音 D♭ 是主音上方半音 在大调主和弦之间形成半音邻音', '♭II’s root D♭ is a semitone above the tonic, a chromatic neighbour around I'), refs: ['omt2e-modes', 'omt2e-neapolitan'], status: 'example' }),
  E({ id: 'b-backdoor-triad', source: 'extra', roman: 'iv ♭VII I', family: 'iiV', kind: 'cadence', cats: ['jazz', 'borrowed'], tags: ['warm', 'return'],
    suggested: '后门回归的三和弦骨架 七和弦版更典型', theory: t('后门进行 iv7–♭VII7–I 的三和弦骨架', 'The triad frame of the backdoor iv7–♭VII7–I'), refs: ['wiki-backdoor'], variantOf: { id: 'j-backdoor', how: t('去掉七音', 'sevenths removed') } }),
  E({ id: 'b-passing-dim', source: 'extra', roman: 'I ♯i° ii V', family: 'chromatic', kind: 'loop', cats: ['jazz', 'pop', 'chromaticBass'], tags: ['drive'],
    suggested: '半音上行低音 带连接和推进感', theory: t('C 与 Dm 之间插入 C♯dim：低音 C C♯ D 半音上行（七和弦版用 C♯dim7）', 'C♯dim between C and Dm: the bass rises C C♯ D (C♯dim7 in the seventh version)'), refs: ['wiki-cadence', 'wiki-turnaround'] }),
  E({ id: 'b-aug', source: 'extra', roman: 'I I+ vi', family: 'chromatic', kind: 'fragment', cats: ['pop', 'classical'], tags: ['mysterious', 'drive'],
    suggested: '通过增三和弦改变色彩 内声部可半音上行', theory: t('C E G → C E G♯ → C E A：五音 G G♯ A 半音上行', 'C E G → C E G♯ → C E A: the fifth rises G G♯ A'), refs: ['wiki-augmented-triad'], status: 'example' }),
  E({ id: 'b-line-cliche', source: 'extra', mode: 'minor', roman: 'i i(maj7) i7 i(add6)', family: 'chromatic', kind: 'loop', cats: ['jazz', 'minor', 'seventh'], tags: ['mysterious', 'melancholy'],
    original: { text: 'i-i(maj7)-i7-i6', note: t('这里的 i6 是流行和弦符号 Cm6（小三和弦加大六度） 不是古典罗马数字里 i6 的第一转位；本站写成 i(add6) 把两种记法分开', 'here i6 means the pop symbol Cm6 (minor triad plus major sixth), not the classical first-inversion i6; it is written i(add6) to keep the two apart') },
    suggested: '小调 line cliché 七音到六音的半音下行 带悬疑或内省感', noTriad: t('这条的色彩全在七音和六音上 去掉以后四个和弦都变成 Cm 所以不提供三和弦版', 'all the colour is in the sevenths and sixth — as triads all four would be Cm, so no triad version'),
    theory: t('minor line cliché：m、m(maj7)、m7、m6；主音一路半音下行 C B B♭ A 低音不动', 'The minor line cliché m, m(maj7), m7, m6: a chromatic line from the tonic C B B♭ A over a static root'), refs: ['djangobooks-line-cliche', 'wiki-sixth-chord'], aliases: ['line cliche', 'line cliché'] }),
  E({ id: 'b-puff-III', source: 'extra', roman: 'I III IV iv', family: 'puff', kind: 'loop', cats: ['rock', 'borrowed', 'applied'], tags: ['dramatic', 'melancholy'],
    suggested: '（补充）明亮开头 转大三 III 后落到借用的 iv', theory: t('puff 型的变体 I–III♯–IV 再接借用 iv：内声部 sol–si–la（G G♯ A）然后 A–A♭', 'The puff variant I–III♯–IV followed by borrowed iv: inner line sol–si–la (G G♯ A), then A–A♭'), refs: ['omt-pb-puff'] }),

  // ======================= 补充：爵士与功能链 =======================
  E({ id: 'j-I-VI-ii-V', source: 'extra', roman: 'I VI ii V', family: 'turnaround', kind: 'loop', cats: ['jazz', 'applied'], tags: ['drive', 'warm'], beats: 2,
    suggested: '用大 VI 牵引 ii 更有局部推进感', theory: t('I–VI–ii–V：VI 的三音 C♯ 让 C C♯ D 半音上行 VI 是 V/ii', 'I–VI–ii–V: VI’s third C♯ gives C C♯ D chromatically — VI is V/ii'), refs: ['wiki-turnaround'], variantOf: { id: 'i3-1625', how: t('vi 改成副属 VI', 'vi made into applied VI') } }),
  E({ id: 'j-iii-VI-ii-V', source: 'extra', roman: 'iii VI ii V', family: 'turnaround', kind: 'loop', cats: ['jazz', 'applied', 'fifths'], tags: ['drive'], beats: 2,
    suggested: '连续功能牵引 适合 turnaround', theory: t('iii–VI–ii–V 是常见 turnaround 根音连续下行五度', 'iii–VI–ii–V is a common turnaround with roots falling by fifths'), refs: ['wiki-turnaround'] }),
  E({ id: 'j-I-III-vi-II-ii-V-I', source: 'extra', roman: 'I III vi II ii V I', family: 'turnaround', kind: 'cadence', cats: ['jazz', 'applied'], tags: ['drive', 'return'], beats: 2,
    suggested: '副属色彩与大小调变化交织', theory: t('III 是 V/vi II 是 V/V；II 之后先到 ii 再到 V 同一根音先大后小', 'III is V/vi and II is V/V; II then turns into ii before V — the same root, major then minor'), refs: ['omt2e-tonicization'], status: 'example' }),
  E({ id: 'j-II-V-I', source: 'extra', roman: 'II V I', family: 'iiV', kind: 'cadence', cats: ['jazz', 'applied'], tags: ['drive', 'return'],
    suggested: '重属到属再到主 方向感强', theory: t('II 是 V/V（D F♯ A）；七和弦版的 II 是 D7 不是音阶内 ii 的 Dm7', 'II is V/V (D F♯ A); its seventh version is D7, not the diatonic Dm7'), refs: ['wiki-turnaround', 'omt2e-tonicization'] }),
  E({ id: 'j-VI-II-V-I', source: 'extra', roman: 'VI II V I', family: 'turnaround', kind: 'cadence', cats: ['jazz', 'applied', 'fifths'], tags: ['drive', 'return'],
    suggested: '连续属功能链骨架 七和弦版更鲜明', theory: t('ragtime 进行 V7/vi–V7/ii–V7/V–V7–I 的后四个；一连串副属', 'The last four of the ragtime progression V7/vi–V7/ii–V7/V–V7–I — a chain of applied dominants'), refs: ['wiki-ragtime-progression'] }),
  E({ id: 'j-ii-V-I-vi', source: 'extra', roman: 'ii V I vi', family: 'iiV', kind: 'loop', cats: ['jazz', 'pop'], tags: ['return', 'openEnd'],
    suggested: '回归后再开启下一轮', theory: t('ii–V–I 之后 vi 接回 ii 形成循环', 'ii–V–I, then vi leads back into ii'), refs: ['wiki-circle-progression'], status: 'example' }),
  E({ id: 'j-I-vi-ii-V-I', source: 'extra', roman: 'I vi ii V I', family: 'turnaround', kind: 'cadence', cats: ['jazz', 'fifths'], tags: ['return', 'warm'],
    suggested: '完整 turnaround 与回归', theory: t('I–vi–ii–V 再回到 I；vi ii V I 是五度链的末段', 'I–vi–ii–V back to I; vi ii V I is the tail of the circle of fifths'), refs: ['wiki-circle-progression', 'wiki-turnaround'], variantOf: { id: 'i3-1625', how: t('回到 I 收束', 'closing on I') } }),
  // 七和弦原版（另提供简化对照）
  E({ id: 'j-ii7-V7-Imaj7', source: 'extra', roman: 'ii7 V7 Imaj7', family: 'iiV', kind: 'cadence', cats: ['jazz', 'seventh'], tags: ['return', 'warm'],
    suggested: '流畅的爵士大调回归', theory: t('大调 ii–V–I 的和弦性质 m7–7–maj7', 'Major ii–V–I qualities: m7–7–maj7'), refs: ['omt2e-iivi'], variantOf: { id: 'i3-251', how: t('七和弦原版', 'seventh original') } }),
  E({ id: 'j-iio7-V7-i7', source: 'extra', mode: 'minor', roman: 'iiø7 V7 i7', family: 'iiV', kind: 'cadence', cats: ['jazz', 'minor', 'seventh'], tags: ['melancholy', 'return'],
    suggested: '爵士小调回归 暗色且有牵引力', theory: t('小调 ii–V–I 的和弦性质 ø7–7–m7', 'Minor ii–V–I qualities: ø7–7–m7'), refs: ['omt2e-iivi'] }),
  E({ id: 'j-iio7-V7-imM7', source: 'extra', mode: 'minor', roman: 'iiø7 V7 i(maj7)', family: 'iiV', kind: 'cadence', cats: ['jazz', 'minor', 'seventh'], tags: ['tense', 'mysterious'],
    suggested: '小调回归后仍保留色彩张力', theory: t('主和弦用 m(maj7)：保留 V7 里的导音 B♮ 色彩比 m7 更紧', 'm(maj7) tonic keeps V7’s leading tone B♮ — tighter than m7'), refs: ['omt2e-iivi', 'wiki-minor-major-seventh'], status: 'example', variantOf: { id: 'j-iio7-V7-i7', how: t('主和弦换成 m(maj7)', 'tonic as m(maj7)') } }),
  E({ id: 'j-tritone', source: 'extra', roman: 'ii7 ♭II7 Imaj7', family: 'iiV', kind: 'cadence', cats: ['jazz', 'chromaticBass', 'seventh'], tags: ['mysterious', 'return'],
    suggested: '三全音替代 半音根音接近主和弦', theory: t('G7 换成 D♭7：G7 的 B F 与 D♭7 的 C♭ F 是同一个三全音（同音异名） 根音改成 D D♭ C 半音下行', 'G7 becomes D♭7: G7’s B F and D♭7’s C♭ F are the same tritone (enharmonic); the roots now slide D D♭ C'), refs: ['omt-pb-substitutions'], variantOf: { id: 'j-ii7-V7-Imaj7', how: t('V7 三全音替代', 'tritone-substituted V7') } }),
  E({ id: 'j-backdoor', source: 'extra', roman: 'iv7 ♭VII7 Imaj7', family: 'iiV', kind: 'cadence', cats: ['jazz', 'borrowed', 'seventh'], tags: ['warm', 'return'],
    suggested: '典型爵士后门回归 较柔和但有色彩张力', theory: t('后门进行 iv7–♭VII7–I：♭VII7 来自同主音小调 与 G7 有两个共同音 A♭ 与 F 作为上方导音分别解决到 G 与 E', 'The backdoor iv7–♭VII7–I: ♭VII7 comes from the parallel minor and shares two notes with G7; A♭ and F resolve down to G and E'), refs: ['wiki-backdoor'], aliases: ['backdoor'] }),
  E({ id: 'j-Imaj7-VI7-ii7-V7', source: 'extra', roman: 'Imaj7 VI7 ii7 V7', family: 'turnaround', kind: 'loop', cats: ['jazz', 'applied', 'seventh'], tags: ['drive', 'warm'], beats: 2,
    suggested: '爵士 turnaround 用副属强化第二级', theory: t('VI7 = A7 是 V7/ii；现在的乐手在 I–VI–II–V 里常把 VI 弹成属七', 'VI7 = A7 is V7/ii; players often use a dominant VI in I–VI–II–V'), refs: ['wiki-circle-progression', 'omt2e-tonicization'], variantOf: { id: 'i3-1625', how: t('七和弦加副属', 'sevenths plus applied VI7') } }),
  E({ id: 'j-iii7-VI7-ii7-V7', source: 'extra', roman: 'iii7 VI7 ii7 V7', family: 'turnaround', kind: 'loop', cats: ['jazz', 'applied', 'fifths', 'seventh'], tags: ['drive'], beats: 2,
    suggested: '连续五度运动与导向声部连接', theory: t('根音 E A D G 连续下行五度；三音与七音一路级进相接', 'Roots E A D G fall by fifths; thirds and sevenths connect by step'), refs: ['wiki-turnaround', 'omt2e-jazz-voicings'], variantOf: { id: 'j-iii-VI-ii-V', how: t('七和弦原版', 'seventh original') } }),
  E({ id: 'j-royal-7', source: 'extra', roman: 'IVmaj7 V7 iii7 vi7', family: 'royal', kind: 'loop', cats: ['pop', 'seventh'], tags: ['bright', 'sorrow'],
    suggested: '王道型的七和弦版本 更丰富且保留流动感', theory: t('王道进行的七和弦形 IVM7–V7–iii7–vi7', 'The royal road in sevenths IVM7–V7–iii7–vi7'), refs: ['wiki-royal-road'], variantOf: { id: 'i3-4536', how: t('七和弦原版', 'seventh original') } }),

  // ======================= 补充：布鲁斯 =======================
  E({ id: 'bl-12', source: 'extra', roman: 'I I I I IV IV I I V IV I V', family: 'blues', kind: 'loop', style: 'blues', cats: ['blues'], tags: ['calm', 'drive', 'openEnd'], tempo: [80, 140],
    suggested: '反复呼应 稳定律动 末尾推动下一轮', theory: t('12 小节布鲁斯：三个四小节乐句 I–IV–I–V–IV–I；七和弦版全部是属七 I7 IV7 V7（布鲁斯里属七可以是任何功能）', 'The 12-bar blues: three 4-bar phrases; in sevenths every chord is a dominant seventh I7 IV7 V7 (in the blues a dominant seventh can have any function)'), refs: ['omt-pb-blues', 'wiki-twelve-bar'], aliases: ['12-bar blues', '十二小节布鲁斯'] }),
  E({ id: 'bl-quick', source: 'extra', roman: 'I IV I I IV IV I I V IV I V', family: 'blues', kind: 'loop', style: 'blues', cats: ['blues'], tags: ['drive', 'openEnd'], tempo: [80, 140],
    suggested: '更早产生回应 第二小节就出现对比', theory: t('quick change（quick to four）：第二小节先到 IV', 'The quick change (quick to four): bar 2 already goes to IV'), refs: ['wiki-twelve-bar', 'omt-pb-blues'], variantOf: { id: 'bl-12', how: t('第二小节换成 IV', 'IV in bar 2') }, aliases: ['quick change', 'quick to four'] }),
  E({ id: 'bl-minor', source: 'extra', mode: 'minor', roman: 'i7 i7 i7 i7 iv7 iv7 i7 i7 iiø7 V7 i7 V7', family: 'blues', kind: 'loop', cats: ['blues', 'minor', 'seventh'], tags: ['melancholy', 'drive'], tempo: [70, 130],
    suggested: '（补充）暗色的布鲁斯 第三句用 ii–V–i 回到主和弦', theory: t('小调布鲁斯：i 与 iv 用小七 V 保持属七；第三句的 V–IV–I 常换成 ii–V–I；这里第九小节用 iiø7 是按 OMT 文字描述排的示例', 'Minor blues: i and iv are minor sevenths, V stays dominant; the third phrase’s V–IV–I is usually replaced by ii–V–I — the iiø7 in bar 9 is an example built from OMT’s description'), refs: ['omt-pb-blues', 'omt2e-iivi'], status: 'example' }),
  E({ id: 'bl-jazz', source: 'extra', roman: 'I7 IV7 I7 I7 IV7 IV7 I7 VI7 ii7 V7 I7 V7', family: 'blues', kind: 'loop', cats: ['blues', 'jazz', 'applied', 'seventh'], tags: ['drive', 'warm'], tempo: [100, 180],
    suggested: '（补充）布鲁斯里加入爵士的 ii–V', theory: t('爵士布鲁斯在第八小节用副属（指向第九小节的 ii） 第三句换成 ii–V–I；具体和弦有很多写法 这里是按 OMT 文字描述排的简化示例', 'The jazz blues adds an applied chord in bar 8 (pointing to ii in bar 9) and replaces the third phrase with ii–V–I; many versions exist — this is a simplified example built from OMT’s description'), refs: ['omt-pb-blues'], status: 'example' }),
  E({ id: 'bl-turnaround', source: 'extra', roman: 'III7 VI7 II7 V7', family: 'blues', kind: 'fragment', cats: ['blues', 'jazz', 'applied', 'fifths', 'seventh'], tags: ['drive', 'openEnd'], beats: 2,
    suggested: '（补充）放在最后一两小节 把音乐推回开头', theory: t('布鲁斯结尾的 turnaround 可以简单到一个 V7 也可以是完整的 III–VI–II–V（一串属七）', 'A blues turnaround can be as simple as one V7 or a full III–VI–II–V chain of dominants'), refs: ['omt-pb-blues', 'wiki-ragtime-progression'] }),
  E({ id: 'bl-shuffle', source: 'extra', roman: 'V IV I I', family: 'blues', kind: 'fragment', style: 'blues', cats: ['blues'], tags: ['return', 'calm'],
    suggested: '（补充）第三句的回落', theory: t('12 小节布鲁斯第三句 V–IV–I–I（shuffle blues 型） 以变格运动收束', 'The third phrase V–IV–I–I (shuffle blues pattern), closing with plagal motion'), refs: ['wiki-twelve-bar', 'omt-pb-blues'] }),

  // ======================= 补充：OMT 的另外两个四和弦 / puff 套路 =======================
  E({ id: 'x-hopscotch', source: 'extra', roman: 'IV V vi I', family: 'hopscotch', kind: 'loop', cats: ['pop'], tags: ['bright', 'drive', 'openEnd'],
    suggested: '（补充）步 步 跳 的根音走向 主音可能在 Am 与 C 之间', theory: t('hopscotch 型 IV–V–vi–I：根音级进 级进 跳进；和 singer/songwriter 型一样有调性模糊 进入 C 时通常没有明确的终止', 'The hopscotch schema IV–V–vi–I: roots step, step, skip; tonally ambiguous like singer/songwriter, with no clear cadence into C'), refs: ['omt-pb-4chord'], aliases: ['hopscotch'] }),
  E({ id: 'x-puff', source: 'extra', roman: 'I iii IV I', family: 'puff', kind: 'fragment', cats: ['pop'], tags: ['warm', 'calm'],
    suggested: '（补充）常用在乐句开头 不常拿来循环', theory: t('puff 型 I–iii–IV 通常出现在乐句开头 IV 之后接什么并不固定', 'The puff schema I–iii–IV usually opens a phrase; what follows IV varies'), refs: ['omt-pb-puff'], aliases: ['puff'] }),
];

/** 合并日文说明（prog_library_ja.js） */
const withJa = (text, ja) => (text && ja ? { ...text, ja } : text);
export const ENTRIES = RAW_ENTRIES.map((e) => {
  const ja = ENTRY_JA[e.id] || {};
  return {
    ...e,
    theory: withJa(e.theory, ja.theory),
    ...(e.limits ? { limits: withJa(e.limits, ja.limits) } : {}),
    ...(e.variantOf ? { variantOf: { ...e.variantOf, how: withJa(e.variantOf.how, ja.how) } } : {}),
    ...(e.original ? { original: { ...e.original, ...(e.original.note ? { note: withJa(e.original.note, ja.note) } : {}) } } : {}),
  };
});
