import { language } from '../../module_kit.js';
import { Battle, BattleState } from './battle-state.js';
import { BattleAudio } from './battle-audio.js';
import { BossPerformance } from './boss-reaction.js';
import { t, cloneScore, score } from './scenarios.js';
import { noteName, allNotes, chordFacts, pc } from './music-evaluation.js';
const $=id=>document.getElementById(id);
const TEXT={
 chapter:t('第四章 · 爵士与即兴','Chapter 04 · Jazz & improvisation','第4章 · ジャズと即興'),jazTitle:t('爵 · 即兴之王','The king of improvisation','ジャズ · 即興の王'),conviction:t('执念','Conviction','確信'),claimNote:t('他用复杂程度证明自己。','He proves himself through complexity.','複雑さで自分を証明する。'),restart:t('重开','Restart','やり直す'),player:t('编配者','Arranger','編曲者'),listenContext:t('♫ 听已有片段','♫ Hear the existing phrase','♫ 既存のフレーズ'),objective:t('音乐目标','Musical goal','音楽の目標'),analyze:t('观察事实','Inspect facts','事実を読む'),arrange:t('编辑配音','Build a voicing','配置を作る'),guard:t('建立防御','Build a guard','防御を作る'),hold:t('保持当前','Keep the current music','今の音楽を維持'),preview:t('试听草稿 · 1 次','Hear draft · once','草稿を聴く · 1回'),commit:t('COMMIT · 结算回合 ↗','COMMIT · resolve turn ↗','COMMIT · ターン確定 ↗'),continue:t('下一回合 →','Next turn →','次のターン →'),journal:t('战斗记录','Battle journal','戦闘記録'),footer:t('没有计时。编辑不发声、不判分。只有 Commit 才结算。','No timer. Editing is silent and ungraded. Only Commit resolves.','制限時間なし。編集は無音・未判定。Commit で確定。'),introTitle:t('你面对的，是一个观点。','You are fighting a belief.','戦う相手は、一つの考え方。'),introBody:t('爵真的很强。他相信“复杂就是高级”。看他的意图，分析音乐，亲手编配，再用音乐反击。','JAZ really is skilled. He believes complexity means quality. Read his intent, analyse the music, arrange it yourself, then answer with music.','JAZ の実力は本物。「複雑＝高度」と信じている。意図を読み、音楽を分析し、自分で編曲して反撃する。'),introRules:t('4 个普通回合 · 1 次大炮 · 1 段最终自由编配。真正的乐理错误才扣 HP；被预判的正确音乐会给大炮充能。音乐没有问题，也可能没有动摇他的执念。','4 normal turns · 1 cannon · 1 final free voicing. Only musical errors cost HP; predicted valid music charges the cannon. Valid music may still leave his belief intact.','通常4ターン・砲撃1回・自由配置の最終1回。音楽上の誤りだけが HP を減らす。予測された有効な音楽は砲撃を充電。'),previewRule:t('每回合只允许试听草稿一次。每次 Commit 都消耗行动；错误不会推进回合，会消耗有限 HP。你可以一直思考。','One draft audition per turn. Each Commit spends an action; mistakes cost finite HP and do not advance the turn. Think as long as you need.','草稿の試聴は1ターン1回。Commit は行動を消費。誤りは有限 HP を減らし、ターンは進まない。ゆっくり考えてよい。'),start:t('走上舞台 →','Take the stage →','舞台へ →')};
function tx(value){return typeof value==='string'?value:value?.[language()]??value?.en??'';}
function tr(zh,en,ja){return tx(t(zh,en,ja));}
function escape(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
let initial='zh';try{initial=localStorage.getItem('jc-lang')||'zh';}catch{}window.__lang=['zh','en','ja'].includes(initial)?initial:'zh';$('language').value=window.__lang;
let battle=new Battle(),audio=new BattleAudio(),performanceLayer=new BossPerformance($('stage'),$('jaz-sprite'),$('jaz-motion'),$('stage-impact'));
let resolvingJob=null;
function localize(){document.documentElement.lang={zh:'zh-CN',en:'en',ja:'ja'}[language()];document.querySelectorAll('[data-t]').forEach(el=>el.textContent=tx(TEXT[el.dataset.t]));}
const pitchOptions=(value,min=48,max=84)=>Array.from({length:max-min+1},(_,i)=>{const midi=min+i;return `<option value="${midi}" ${midi===value?'selected':''}>${noteName(midi)}</option>`;}).join('');
function voiceRow(value,{index='bass',part='draft',label='BASS',bass=false}={}){
 const attrs=`data-part="${part}" data-index="${index}"`;
 return `<div class="voice-row ${bass?'bass-row':''}"><label for="pitch-${part}-${index}">${label}</label><select id="pitch-${part}-${index}" ${attrs} aria-label="${label}">${pitchOptions(value,bass?36:48,bass?60:84)}</select><button ${attrs} data-step="-1" title="${tr('降低半音','Down a semitone','半音下げる')}">−</button><button ${attrs} data-step="1" title="${tr('升高半音','Up a semitone','半音上げる')}">+</button><button ${attrs} data-step="-12" title="${tr('降低八度','Down an octave','八度下げる')}">−8</button><button ${attrs} data-step="12" title="${tr('升高八度','Up an octave','八度上げる')}">+8</button>${bass?`<span class="voice-note-info">${tr('独立低音 · 可以改变转位','Independent bass · inversion is editable','独立した低音 · 転回を変更可')}</span>`:`<button class="delete" ${attrs} data-remove="true" aria-label="${tr('删除声部','Remove voice','声部を削除')} ${label}">×</button>`}</div>`;
}
function arrangementView(arr,part='draft'){
 return `<div class="arrangement"><div class="arrange-caption"><span>${tr('改变音高、八度、密度与转位。编辑不会结算。','Change pitch, octave, density and inversion. Editing does not resolve.','音高・八度・密度・転回を変更。編集だけでは確定しない。')}</span><b>${allNotes(arr).map(noteName).join(' · ')}</b></div><div class="voice-grid">${voiceRow(arr.bass,{part,bass:true})}${arr.voices.map((v,i)=>voiceRow(v.midi,{part,index:i,label:'VOICE '+(i+1)})).join('')}</div><div class="arrange-tools"><button data-add="${part}" ${arr.voices.length>=6?'disabled':''}>+ ${tr('添加声部','Add voice','声部を追加')}</button>${part==='draft'&&battle.scenario.families?.some(f=>['delay','substitute'].includes(f))?`<button id="toggle-continuation">${arr.continuation?'−':'+'} ${tr('写下一拍（延后 / 替代）','Write next beat (delay / substitution)','次の拍を書く（遅延・代理）')}</button>`:''}<span>${arr.voices.length} / 6 ${tr('伴奏声部','accompaniment voices','伴奏声部')}</span></div></div>`;
}
function renderArrange(){
 return arrangementView(battle.draft)+(battle.draft.continuation?`<div class="continuation"><h3>${tr('下一拍 · 仍使用给定旋律','Following beat · same given melody','次の拍 · 同じ旋律')}</h3>${arrangementView(battle.draft.continuation,'continuation')}</div>`:'');
}
function renderFacts(){const s=battle.scenario,chords=s.history??[];
 return `<div class="facts-grid"><div class="fact-block"><span>KEY CENTER</span><strong>${s.key}</strong><p>${tr('中心音 C；音名不限制你的完整配音。','Tonal centre C; note names do not prescribe a voicing.','調の中心は C。音名は配置の答えではない。')}</p></div>${chords.map(c=>`<div class="fact-block"><span>CHORD FACTS</span><strong>${escape(c.symbol)}</strong><p>${chordFacts(c.symbol).map(n=>`${escape(n.note)} [${escape(n.degree)}]`).join(' · ')||c.notes.map(noteName).join(' · ')}<br>BASS ${noteName(c.bass)}</p></div>`).join('')}<div class="fact-block"><span>CURRENT MELODY</span><strong>${noteName(s.melody)}</strong><p>${tr('旋律独立发声，伴奏不需要机械重复它。','Melody sounds independently; accompaniment need not double it mechanically.','旋律は独立して鳴る。機械的に倍奏する必要はない。')}</p></div>${!battle.defense?`<div class="fact-block"><span>EXISTING VOICES</span><strong>${allNotes(s.previous).map(noteName).join(' · ')}</strong><p>${tr('移动距离按真实音域计算。八度移位会改变连接。','Motion is measured in actual register; octave changes alter continuity.','実際の音域で移動を測る。八度変更で連結も変わる。')}</p></div>`:''}</div><p class="fact-notice">${tr('ANALYZE 只列音乐事实与已给定的目标，不推荐下一和弦，不判断草稿。3rd / 7th、音程与实际音域都由你结合意图判断。','ANALYZE lists facts and the stated goal. It neither recommends the next chord nor grades your draft. You interpret thirds, sevenths, intervals and register against the intent.','ANALYZE は事実と既存の目標だけを示す。次の和音の推奨・草稿の採点はしない。意図に照らして3度・7度・音程・音域を読む。')}</p>`;
}
function guardSelect(value,col,row){const attrs=`data-guard-col="${col}" data-guard-row="${row}"`;return `<div class="voice-row"><label for="guard-${col}-${row}">${row===0?'A':'B'}</label><select id="guard-${col}-${row}" ${attrs} aria-label="${['Dm7','G7','Cmaj7'][col]} ${tr('防御声部','guard voice','防御声部')} ${row+1}">${pitchOptions(value)}</select><button ${attrs} data-step="-1">−</button><button ${attrs} data-step="1">+</button></div>`;}
function renderGuard(){return `<p class="guard-heading">${tr('防御不是减伤开关。写出两条持续的声部，让每个和弦的性质和真实连接都成立。相同音名放到错误八度，也可能失去连贯性。','Guard is not a damage switch. Write two continuous voices preserving chord quality and actual continuity. The right pitch class in the wrong octave may still break the line.','防御は単なる減傷ボタンではない。和音の性質と実際の連結を保つ2声を作る。正しい音級でも、八度次第で流れが切れる。')}</p><div class="guard-score">${['Dm7','G7','Cmaj7'].map((c,col)=>`<div class="guard-column"><h3>${c}</h3><span class="guard-bass">BASS ${noteName([38,43,48][col])}</span>${[0,1].map(row=>guardSelect(battle.guardPaths[col][row],col,row)).join('')}</div>`).join('')}</div><p class="guard-tip">${tr('这里只编辑音乐，不自动标出正确的防御。未形成结构的举盾仅减免少量冲击。','This edits music, without marking a correct guard. Bracing without structural support only softens the impact slightly.','音楽を編集するだけで、正しい防御は表示しない。構造を欠く防御は少ししか衝撃を減らさない。')}</p>`;}
function renderHold(){const arr=battle.scenario.previous;return `<div class="hold-view"><div class="hold-icon">—</div><div><h3>${allNotes(arr).map(noteName).join(' · ')}</h3><p>${tr('原样保留当前伴奏，不增加、删除或移动任何音。音乐是否需要改变，将在 Commit 后按本回合目标结算。','Keep the current accompaniment unchanged: no additions, deletions or motion. Whether it needed change is resolved against this turn’s goal after Commit.','伴奏をそのまま維持。追加・削除・移動なし。変化が必要だったかは Commit 後に今回の目標で判定する。')}</p></div></div>`;}
const views={analyze:renderFacts,arrange:renderArrange,guard:renderGuard,hold:renderHold};
function renderContext(){const s=battle.scenario;const scoreShown=battle.action==='arrange'?battle.draft:s.previous;const cards=(s.history??[]).map(c=>({symbol:c.symbol,notes:[c.bass,...c.notes],melody:c.melody}));if(!battle.defense)cards.push({symbol:tr('你的配音','Your voicing','あなたの配置'),notes:allNotes(scoreShown),melody:s.melody,target:true});$('musical-context').innerHTML=cards.map((c,i)=>`<div class="context-chord ${c.target?'target':''}"><strong>${escape(c.symbol)}</strong><small>${c.notes.map(noteName).join(' · ')}</small><div class="melody">MELODY ${noteName(c.melody)}</div></div>${i<cards.length-1?'<span class="context-arrow">→</span>':''}`).join('');}
function renderStats(){const s=battle.scenario;$('phase-label').textContent='PHASE '+s.phase;$('turn-label').textContent=battle.defense?'DEFENSE / CANNON':battle.final?'FINAL / FREE VOICING':tr('回合','TURN','ターン')+' '+(battle.round+1)+' / 4';$('conviction-number').textContent=battle.conviction+'%';$('conviction-bar').style.width=battle.conviction+'%';$('hp-number').textContent=battle.hp+' / 100';$('hp-bar').style.width=battle.hp+'%';$('charge-number').textContent=battle.intent.charge+' / 3';document.querySelectorAll('.charge-blocks i').forEach((el,i)=>el.classList.toggle('filled',i<battle.intent.charge));$('intent-state').textContent=battle.defense?'ARMED':battle.intent.fired?'SPENT':'NEXT';$('intent-detail').textContent=tx(s.intent);$('stage').classList.toggle('armed',battle.defense);$('stage').classList.toggle('final-stage',battle.final);$('boss-state').textContent=battle.final?'EVERY NOTE':battle.breakOccurred?'LISTENING':'SHOWTIME';$('scenario-kicker').textContent=s.kicker;$('scenario-title').textContent=tx(s.title);$('objective').textContent=tx(s.goal);$('budget-readout').textContent=tr('草稿试听','DRAFT AUDITION','草稿試聴')+' '+battle.previewsLeft+' / 1';}
function renderAction(){
 $('action-title').innerHTML=battle.command.toUpperCase()+`<small>${battle.command==='analyze'?tr('不消耗回合 · 只有事实','No turn cost · facts only','ターン消費なし · 事実のみ'):tr('未结算 · 不会实时判分','Uncommitted · no live grading','未確定 · リアルタイム判定なし')}</small>`;
 $('action-content').innerHTML=views[battle.command]();
 document.querySelectorAll('[data-command]').forEach(b=>{b.classList.toggle('selected',b.dataset.command===battle.command);b.disabled=!battle.canEdit||battle.defense&&['arrange','hold'].includes(b.dataset.command);});
 $('commit').disabled=!battle.canEdit||!battle.action;$('preview').disabled=!battle.canEdit||!battle.action||battle.previewsLeft===0;$('commit').hidden=!battle.canEdit;$('preview').hidden=!battle.canEdit;$('continue').hidden=battle.status!==BattleState.RESULT;
 $('context-audio').disabled=!battle.canEdit||battle.contextListened;
 $('action-cost').textContent=battle.command==='analyze'?tr('看清音乐，再选择行动。','Read the music, then choose an action.','音楽を読んでから、行動を選ぶ。'):battle.defense?tr('GUARD 会结算整次炮击。没有计时，也没有 QTE。','GUARD resolves the entire cannon. No timer, no QTE.','GUARD で砲撃を確定。時間制限・QTEなし。'):tr('Commit 消耗本次行动。乐理错误扣 25 HP；有效音乐不扣 HP。','Commit spends this action. Musical error: −25 HP. Valid music: no HP cost.','Commit は行動を消費。音楽上の誤りは HP −25。有効な音楽は HP を減らさない。');
}
function renderJournal(){$('journal').innerHTML=battle.log.map((r,i)=>`<li><b>${String(i+1).padStart(2,'0')} · ${r.scenario} / ${r.action.toUpperCase()}</b> — ${r.valid?'MUSIC VALID':r.problems.join(' · ')} · HP ${r.before.hp}→${r.after.hp} · CONVICTION ${r.before.conviction}→${r.after.conviction}${r.predicted?' · JAZ PREDICTION SUCCESS':''}${r.broken?' · BREAK':''}</li>`).join('');}
function renderResult(){const r=battle.result;if(!r){$('result-panel').hidden=true;return;}$('result-panel').hidden=false;const hp=r.after.hp-r.before.hp,conv=r.after.conviction-r.before.conviction;
 const tactical=r.isCannon?(r.valid?'GUIDE TONE GUARD / COUNTER':'GUARD INCOMPLETE'):r.action==='guard'?'GUARD PREPARED':r.predicted?'JAZ PREDICTION SUCCESS':r.valid?'JAZ PREDICTION FAILED':'';
 $('result-panel').innerHTML=`<div class="result-header ${r.valid?'':'invalid'}"><h2>${r.valid?'MUSIC VALID':escape(r.problems[0])}</h2><div class="result-deltas"><span class="${hp<0?'bad':''}">HP ${hp===0?'±0':hp}</span><span class="${conv<0?'good':conv>0?'bad':''}">CONVICTION ${conv===0?'±0':conv+'%'}</span><span>CHARGE ${r.before.charge} → ${r.after.charge}</span></div></div><div class="result-subline">${tactical}${r.broken?' · BREAK':''}</div><div class="metrics">${r.metrics.map(m=>`<div class="metric ${m.pass?'':m.name==='REDUNDANCY'&&r.valid?'neutral':'fail'}"><strong>${m.pass?'●':'○'} ${m.name}</strong><p>${escape(tx(m.detail))}</p></div>`).join('')}</div>${r.purposes.length?`<div class="note-reasons">${r.purposes.map(p=>`<span><b>${noteName(p.midi)}</b><small>${p.degree} / ${p.role}</small></span>`).join('')}<span><b>${noteName(battle.scenario.melody)}</b><small>MELODY</small></span></div>`:''}`;
 $('claim-response').textContent=conv<0?tr('音乐成立；你的选择削弱了他的主张。','Valid music; your choices weaken his claim.','有効な音楽。選択が主張を弱めた。'):conv>0?tr('音乐成立，但没有作用的音强化了他的思维。','Valid music, but purposeless notes strengthen his habit.','音楽は成立。でも無目的な音が主張を強めた。'):tr('音乐与战术，分别结算。','Music and tactics resolve separately.','音楽と戦術は別々に判定する。');
}
function render(){localize();renderStats();renderContext();renderAction();renderResult();renderJournal();}
function endView(){audio.stop();performanceLayer.clear();const win=battle.status===BattleState.VICTORY;$('stage').classList.toggle('won',win);performanceLayer.pose(win?'endings/'+(battle.stars===3?'three_star':battle.stars===2?'two_star':'one_star'):'expressions/defiant');$('dialogue').innerHTML=win?tr('……行。<br>复杂本身没有价值。选择，才有。','…All right.<br>Complexity alone has no value. Choice does.','……いいだろう。<br>複雑さ自体に価値はない。選択にある。'):battle.hp===0?tr('先把音乐的功能和连接找回来。<br>这场演出，你还可以再来。','Find the music’s function and continuity again.<br>You can try this performance again.','機能と連結を取り戻せ。<br>もう一度演奏できる。'):tr('你的音乐成立。<br>可你还没有动摇“越复杂越高级”。','Your music is valid.<br>But you have not shaken “more complex is better.”','音楽は成立。<br>でも「複雑＝高度」はまだ揺らいでいない。');$('action-panel').hidden=true;$('result-panel').hidden=false;$('result-panel').innerHTML=`<div class="end-view"><div class="stars">${win?'✦ '.repeat(battle.stars)+'· '.repeat(3-battle.stars):'—'}</div><h2>${win?'EVERY NOTE NEEDS A REASON.':battle.hp===0?tr('演出中断。','Performance interrupted.','演奏中断。'):tr('音乐成立，执念未破。','Valid music. Claim intact.','音楽は成立、確信は残った。')}</h2><p>${win?tr('简单不天然高级。复杂也不天然高级。<br>你用每一个音的作用，证明了你的选择。','Simple is not inherently better. Complex is not inherently better.<br>You proved your choices through the purpose of every note.','単純さも複雑さも、それだけで高度ではない。<br>各音の役割で選択を証明した。'):tr('重新读意图、功能、旋律、连接和色彩。只有音乐证据能打破执念。','Read intent, function, melody, motion and colour again. Only musical evidence breaks conviction.','意図、機能、旋律、連結、色彩を読み直す。音楽の証拠でしか確信は崩せない。')}</p><div class="end-totals">HP ${battle.hp}/100 · CONVICTION ${battle.conviction}% · ${tr('理论错误','THEORY ERRORS','音楽上の誤り')} ${battle.errors}</div><button class="brass-button" id="replay">${tr('再战一次 ↻','Play again ↻','再挑戦 ↻')}</button></div>`;document.querySelectorAll('[data-command]').forEach(b=>b.disabled=true);$('commit').hidden=true;$('preview').hidden=true;$('continue').hidden=true;$('action-cost').textContent=tr('演出结束。','Performance finished.','演奏終了。');$('replay').onclick=restart;if(win)audio.ending();renderStats();renderJournal();}
function editPitch(element,step=null){if(!battle.canEdit)return;const d=element.dataset;
 if(d.guardCol!==undefined){const col=Number(d.guardCol),row=Number(d.guardRow),old=battle.guardPaths[col][row];battle.guardPaths[col][row]=step===null?Number(element.value):Math.max(48,Math.min(84,old+step));}
 else{const arr=d.part==='continuation'?battle.draft.continuation:battle.draft;if(!arr)return;const old=d.index==='bass'?arr.bass:arr.voices[Number(d.index)].midi,lo=d.index==='bass'?36:48,hi=d.index==='bass'?60:84,n=step===null?Number(element.value):Math.max(lo,Math.min(hi,old+step));if(d.index==='bass')arr.bass=n;else arr.voices[Number(d.index)].midi=n;}
 renderContext();renderAction();
}
$('action-content').addEventListener('change',e=>{if(e.target.matches('select'))editPitch(e.target);});
$('action-content').addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!battle.canEdit)return;const d=b.dataset;if(d.step!==undefined)editPitch(b,Number(d.step));else if(d.remove){const arr=d.part==='continuation'?battle.draft.continuation:battle.draft;if(arr.voices.length>1){arr.voices.splice(Number(d.index),1);renderContext();renderAction();}}else if(d.add){const arr=d.add==='continuation'?battle.draft.continuation:battle.draft;if(arr.voices.length<6){arr.voices.push({id:'v'+Date.now(),midi:60});renderContext();renderAction();}}else if(b.id==='toggle-continuation'){battle.draft.continuation=battle.draft.continuation?null:score(43,[59,62,65]);renderAction();}});
for(const b of document.querySelectorAll('[data-command]'))b.onclick=()=>{if(battle.choose(b.dataset.command)){renderAction();renderContext();}};
$('preview').onclick=()=>{if(!battle.preview())return;audio.unlock();if(battle.action==='guard')audio.guard(battle.guardPaths);else audio.draft(battle.scenario,battle.action==='hold'?battle.scenario.previous:battle.draft);renderStats();renderAction();};
$('context-audio').onclick=()=>{if(!battle.canEdit||battle.contextListened)return;battle.contextListened=true;audio.unlock();audio.context(battle.scenario);renderAction();};
$('commit').onclick=()=>{
 const result=battle.commit();if(!result)return;audio.unlock();renderAction();renderStats();$('dialogue').innerHTML=performanceLayer.react(result,tx);const arr=result.action==='hold'?battle.scenario.previous:battle.draft;audio.resolution(battle.scenario,result,arr,battle.guardPaths);
 resolvingJob=setTimeout(()=>{resolvingJob=null;battle.showResult();renderResult();renderAction();renderJournal();$('continue').textContent=!result.valid&&!result.isCannon&&battle.hp>0?tr('承受反击 · 重新编配 →','Take the counter · revise →','反撃を受けて再配置 →'):battle.final||battle.hp===0?tr('结束演出 →','End performance →','演奏を終える →'):result.isCannon?tr('炮击已结算 · 继续 →','Cannon resolved · continue →','砲撃確定 · 続ける →'):tr('下一回合 →','Next turn →','次のターン →');},850);
};
$('continue').onclick=()=>{audio.stop();performanceLayer.clear();battle.next();if([BattleState.VICTORY,BattleState.DEFEAT].includes(battle.status)){endView();return;}$('action-panel').hidden=false;render();$('dialogue').innerHTML=tx(battle.scenario.line);performanceLayer.pose(battle.defense?'boss/phase2':battle.breakOccurred?'expressions/serious':'poses/idle');};
function restart(){if(resolvingJob){clearTimeout(resolvingJob);resolvingJob=null;}audio.stop();performanceLayer.clear();battle=new Battle();$('stage').classList.remove('won','quiet-jaz');$('action-panel').hidden=false;render();$('dialogue').innerHTML=tx(battle.scenario.line);performanceLayer.pose('poses/idle');$('intro').showModal();}
$('restart').onclick=restart;$('start').onclick=()=>{audio.unlock();battle.start();$('intro').close();render();};
$('intro').addEventListener('cancel',e=>{e.preventDefault();});
$('mute').onclick=()=>{const muted=audio.toggle();$('mute').textContent=muted?'♪':'♫';$('mute').setAttribute('aria-pressed',String(muted));$('mute').setAttribute('aria-label',muted?tr('开启声音','Enable sound','音を有効'):tr('关闭声音','Mute sound','消音'));};
$('language').onchange=()=>{window.__lang=$('language').value;try{localStorage.setItem('jc-lang',window.__lang);}catch{}localize();if([BattleState.VICTORY,BattleState.DEFEAT].includes(battle.status))endView();else{render();$('dialogue').innerHTML=battle.result?tx((awaitReaction(battle.result))):tx(battle.scenario.line);}};
// The localized reaction is displayed again without replaying or mutating the encounter.
import { BossReaction } from './boss-reaction.js';
function awaitReaction(result){return BossReaction(result).line;}
window.addEventListener('keydown',e=>{if(e.key==='Escape')audio.stop();});window.addEventListener('pagehide',()=>{audio.stop();performanceLayer.clear();if(resolvingJob)clearTimeout(resolvingJob);});
render();$('dialogue').innerHTML=tx(battle.scenario.line);$('intro').showModal();
